import {reserveBoundedDispatch} from './bounded-workflow.js';
import {bytes,reject} from './contracts.js';
export const DEFAULT_LIMITS=Object.freeze({maxInputs:20,maxTargets:8,maxContext:2,maxContextBytes:4096,maxContentBytes:32768,maxRequestBytes:49152,maxOutputBytes:32768,maxCandidates:12,maxConcurrentJobs:1,maxRetries:3,timeoutMs:30000,sessionInputs:256,sessionBytes:2097152,sessionRequests:128,dailyInputs:1024,dailyBytes:8388608,dailyRequests:20,monetary:null});
export class BudgetPolicy {
 constructor(limits={}){this.limits={...DEFAULT_LIMITS,...limits};for(const [k,v]of Object.entries(this.limits))if(k!=='monetary'&&(!Number.isSafeInteger(v)||v<0))reject('BUDGET_EXCEEDED');this.version=1;}
 evaluate({inputCount=0,targetCount=0,contextCount=0,contextBytes=0,contentBytes=0,requestBytes=0,outputBytes=0,candidateCount=0,concurrent=0,session={inputs:0,bytes:0,requests:0},daily={inputs:0,bytes:0,requests:0}}={}){
  const l=this.limits,too=inputCount>l.maxInputs||targetCount>l.maxTargets||contextCount>l.maxContext||contextBytes>l.maxContextBytes||contentBytes>l.maxContentBytes||requestBytes>l.maxRequestBytes||outputBytes>l.maxOutputBytes||candidateCount>l.maxCandidates||session.inputs+inputCount>l.sessionInputs||session.bytes+requestBytes>l.sessionBytes||session.requests+1>l.sessionRequests||daily.inputs+inputCount>l.dailyInputs||daily.bytes+requestBytes>l.dailyBytes||daily.requests+1>l.dailyRequests;
  return {decision:too?'pause':concurrent>=l.maxConcurrentJobs?'queue':'allow',reason:too?'BUDGET_EXCEEDED':concurrent>=l.maxConcurrentJobs?'CONCURRENCY':'WITHIN_BUDGET',version:this.version,cost:{inputs:inputCount,bytes:requestBytes,requests:1},monetary:null};
 }
}
export async function bindBudgetSession(ledger,storage,uuid=()=>crypto.randomUUID()){const key='original-organizer-budget-session',saved=await storage.get(key);let id=saved?.[key];if(typeof id!=='string'||!id.length||id.length>100){id=uuid();await storage.set({[key]:id});}ledger.setSessionId(id);}
export class BudgetLedger {
 constructor(store,policy){this.store=store;this.policy=policy;this.sessionId=null;}
 setSessionId(value){this.sessionId=typeof value==='string'&&value.length<=100?value:null;}
 async reserve(t,job,request,onStep=()=>{}){const now=Date.parse(this.store.clock()),id='organizer-budget',row=await t.get('meta',id)||{id,startedAt:now,dailyAt:now,session:{inputs:0,bytes:0,requests:0},daily:{inputs:0,bytes:0,requests:0}},empty=()=>({inputs:0,bytes:0,requests:0}),valid=value=>value&&['inputs','bytes','requests'].every(k=>Number.isSafeInteger(value[k])&&value[k]>=0);if(this.sessionId&&row.sessionId!==this.sessionId){row.startedAt=now;row.session=empty();row.sessionId=this.sessionId;row.runtimeRepairVersion=1;}if(Number.isFinite(row.dailyAt)&&now-row.dailyAt>=86400000){row.dailyAt=now;row.daily=empty();}if(!valid(row.session)||!valid(row.daily)||!Number.isFinite(row.dailyAt))reject('BUDGET_EXCEEDED');const cost={inputCount:request.inputs.length,requestBytes:bytes(request),session:row.session,daily:row.daily},controls=await t.get('meta','organizer-controls'),policy=controls?new BudgetPolicy({...this.policy.limits,dailyRequests:controls.dailyRequests}):this.policy,decision=policy.evaluate(cost);if(decision.decision!=='allow')reject('BUDGET_EXCEEDED');await reserveBoundedDispatch(t,job,request);for(const w of ['session','daily'])for(const k of ['inputs','bytes','requests'])row[w][k]+=decision.cost[k];onStep('budget_state');await t.put('meta',row);const usage={id:this.store.uuid(),kind:'reservation',requestId:request.requestId,audit:job.audit,jobId:job.id,sequence:job.attempts,stateKey:0,state:'dispatched',createdAt:this.store.clock(),windowIds:['session:'+row.startedAt,'daily:'+row.dailyAt],cost:decision.cost};onStep('usage_reservation');await t.put('organizerUsage',usage);return usage.id;}
 async settle(t,id){const row=await t.get('organizerUsage',id);if(row){row.state='settled';row.stateKey=1;await t.put('organizerUsage',row);}}
 // A dispatched/unknown attempt is never refunded, including restart/cancel.
}
