import {commitBoundedProgress} from './bounded-workflow.js';
import {checkEvidenceInTransaction,inputProjection} from '../thought-evidence.js';
import {FAMILY_BY_TYPE,ENTRY_FIELDS,protections,markHuman,refreshEntryIndex,entrySnapshot,prefix,keyedHash,rankBetween} from '../thought-model.js';
import {journal,nextSequence} from '../thought-journal.js';
import {queueSearch} from '../library-search.js';
import {ActionPolicy} from './policy.js';
import {reject} from './contracts.js';
export async function leaseGuard(store,t,claim){const job=await t.get('organizerJobs',claim.id),gate=await t.get('meta','gate');if(job&&job.policyVersion!==1)reject('STALE_BASE');if(!job||job.state!=='running'||job.fence!==claim.fence||job.owner!==claim.owner||job.leaseUntil<=Date.parse(store.clock()))reject('CANCELLED');if(!gate?.enabled||gate.epoch!==job.consentEpoch)reject('CANCELLED');return job;}
export class LibraryCommitService {
 constructor(store){this.store=store;}
 async prepare(candidates,p){const s=this.store,secret=await s.run(()=>s.repository.transaction(false,async t=>(await t.get('meta','thought-suppression-key')).value,['meta']));const out=[];for(const c of candidates){const compared=p.request.entries.find(e=>e.ref===c.entryRef),signatureBody=c.action==='classify'?compared.body:c.body,signatureType=c.action==='refresh'?compared.type:c.type;const refs=[...new Set([...c.evidence.map(e=>e.ref),...Object.keys(p.maps).filter(ref=>p.maps[ref].role==='context_only')])],evidence=refs.map(ref=>p.maps[ref]),scopes=evidence.filter(e=>e.role!=='context_only').map(e=>e.scopeToken).sort();out.push({candidate:c,evidence,exactSignature:await keyedHash(secret,['body',signatureType,signatureBody]),exactKey:await keyedHash(secret,c.localOriginal?['original-exact',c.type,c.body]:['organizer-exact',c.type,c.body,scopes]),logicalKey:await keyedHash(secret,['suggestion',c.action,c.entryRef?p.entryMap[c.entryRef]:null,scopes,evidence.map(e=>e.versionToken).sort(),c.type,c.formation,c.topicRef?p.topicMap[c.topicRef]:c.newTopic||null])});}return out;}
 async commitOriginalBatch(batchId,p,prepared,usageId=null,terminal=[],progress=null,requestGuard=null){const s=this.store;return s.foundationWrite(async t=>{const receiptId='original-simple:'+batchId,prior=await t.get('operationReceipts',receiptId);if(prior){if(progress?.phase==='bootstrap'){const state=await t.get('meta','originalOrganizerBootstrap');if(state&&state.cursorSequence===progress.cursorBefore)await t.put('meta',{...state,state:progress.remainingCount===progress.selectedCount?'completed':'running',cursorSequence:progress.advanceSequence,totalEligible:Math.max(state.totalEligible||0,progress.totalEligible),processed:progress.processedBefore+progress.selectedCount,updatedAt:s.clock(),lastError:null});}return prior.result;}let requestRow;if(requestGuard){const pointer=await t.get('meta','originalProviderRequestCurrent');requestRow=await t.get('meta','originalProviderRequest:'+requestGuard.requestId);if(pointer?.requestId!==requestGuard.requestId||requestRow?.userActionId!==requestGuard.userActionId||requestRow?.state!=='validated')reject('CANCELLED');}await checkEvidenceInTransaction(s,t,p.evidence);for(const base of Object.values(p.topicMap)){const row=await s.canonicalTopic(t,base.id);if(row.id!==base.id||row.revision!==base.revision||row.organizationRevision!==base.organizationRevision||row.activeLayoutGeneration!==base.generation||row.layoutJobId)reject('STALE_BASE');}for(const base of Object.values(p.sectionMap)){const row=await t.get('sections',base.id);if(!row||row.revision!==base.revision||row.lifecycle!=='active'||row.redirectTo)reject('STALE_BASE');}
  const result={created:[],updated:[],suggestions:[],denied:0,processedInputCount:terminal.length,validInputCount:terminal.filter(x=>x.status==='processed').length,manualInputCount:terminal.filter(x=>x.status==='manual_required').length},counts=new Map(terminal.map(x=>[x.inputRef,{created:0,updated:0,denied:0}]));
  for(const item of prepared){const c=item.candidate;if(c.action!=='create'||c.localOriginal!==true||c.formation!=='explicit'||!counts.has(c.inputRef))reject('INVALID_OUTPUT');const suppressed=new Map();for(const e of item.evidence.filter(e=>e.role!=='context_only'))for(const x of await t.all('thoughtSuppressions','byScope',e.scopeToken,100))if(x.status==='active')suppressed.set(x.id,x);for(const x of await t.all('thoughtSuppressions','byExact',item.exactSignature,100))if(x.status==='active')suppressed.set(x.id,x);const oldScopes=new Set([...suppressed.values()].flatMap(x=>x.scopeTokens)),newEvidence=item.evidence.some(e=>e.role!=='context_only'&&!oldScopes.has(e.scopeToken)),policy=ActionPolicy.evaluate({candidate:c,entry:null,suppressed:!!suppressed.size,newEvidence});if(policy.decision!=='allow'){result.denied++;counts.get(c.inputRef).denied++;continue;}const applied=await this.apply(t,item,p,null,'ai',batchId);result[applied.created?'created':'updated'].push(applied.id);counts.get(c.inputRef)[applied.created?'created':'updated']++;}
  result.committedInputCount=[...counts.values()].filter(x=>x.created+x.updated>0).length;
  for(const item of terminal)await t.put('operationReceipts',{id:'original-simple-input:'+batchId+':'+item.inputRef,namespace:'original-simple-input',ownerId:batchId,operationSequence:0,createdAt:s.clock(),result:{inputId:p.maps[item.inputRef]?.inputId,inputRevision:p.maps[item.inputRef]?.basedOnContentRevision??0,status:counts.get(item.inputRef)?.denied&&!counts.get(item.inputRef)?.created&&!counts.get(item.inputRef)?.updated?'suppressed':item.status,...(item.code?{code:item.code}:{}),...counts.get(item.inputRef)}});
  if(progress?.phase==='bootstrap'){const state=await t.get('meta','originalOrganizerBootstrap');if(!state||state.cursorSequence!==progress.cursorBefore)reject('STALE_BASE');const completed=progress.remainingCount===progress.selectedCount;await t.put('meta',{...state,state:completed?'completed':'running',cursorSequence:progress.advanceSequence,totalEligible:Math.max(state.totalEligible||0,progress.totalEligible),processed:progress.processedBefore+progress.selectedCount,updatedAt:s.clock(),lastError:null});const current=await t.get('meta','originalOrganizerCheckpoint')||{id:'originalOrganizerCheckpoint',view:'original',version:2,inputVersions:{},lastSequence:0},inputVersions={...current.inputVersions};let sequence=current.lastSequence||0;for(const id of progress.inputIds){const row=await t.get('inputStates',id);if(row){inputVersions[id]={contentRevision:row.contentRevision,removalState:row.removalState,sourcePurged:!!row.sourcePurged,eligible:true,bodyDigest:p.evidence.find(e=>e.inputId===id)?.fieldDigests?.body};sequence=Math.max(sequence,row.deltaSequence||0);}}await t.put('meta',{...current,version:2,inputVersions,lastSequence:sequence,updatedAt:s.clock(),state:completed?'automatic_updated':'baseline_building'});}

  if(progress?.phase==='incremental'){const current=await t.get('meta','originalOrganizerCheckpoint')||{id:'originalOrganizerCheckpoint',view:'original',version:2,inputVersions:{},lastSequence:0,updatedAt:null},versions={...current.inputVersions};for(const id of progress.inputIds){const row=await t.get('inputStates',id);if(row)versions[id]={contentRevision:row.contentRevision,removalState:row.removalState,sourcePurged:!!row.sourcePurged,eligible:true,bodyDigest:p.evidence.find(e=>e.inputId===id)?.fieldDigests?.body};else delete versions[id];}await t.put('meta',{...current,version:2,inputVersions:versions,lastSequence:Math.max(current.lastSequence||0,progress.lastSequence||0),updatedAt:s.clock(),state:'automatic_updated'});}
  await commitBoundedProgress(t,requestGuard?.boundedActionId,{inputs:result.validInputCount,partial:result.manualInputCount>0});await t.put('operationReceipts',{id:receiptId,namespace:'original-simple',ownerId:batchId,operationSequence:0,createdAt:s.clock(),result});if(requestRow){const at=s.clock();await t.put('meta',{...requestRow,state:'committed',phase:'completed',phaseTimestamps:{...(requestRow.phaseTimestamps||{}),completed:at},localWriteStep:'completed',dbErrorCategory:null,committedItemCount:result.committedInputCount??result.created.length+result.updated.length,error:null,errorCode:null,updatedAt:at});}if(usageId)await s.organizerLedger.settle(t,usageId);return result;});}
 async commit(claim,p,prepared){const s=this.store;return s.foundationWrite(async t=>{const job=await leaseGuard(s,t,claim);await checkEvidenceInTransaction(s,t,p.evidence);const receiptId='organizer:'+job.id+':'+job.fence,prior=await t.get('operationReceipts',receiptId);if(prior)return prior.result;
  for(const base of Object.values(p.entryMap)){const e=await s.readableEntry(t,base.id);if(e.lifecycle!=='active'||e.revision!==base.revision||e.organizationRevision!==base.organizationRevision||e.dependencyRevision!==base.dependencyRevision)reject('STALE_BASE');}
  for(const base of Object.values(p.topicMap)){const row=await s.canonicalTopic(t,base.id);if(row.id!==base.id||row.revision!==base.revision||row.organizationRevision!==base.organizationRevision||row.activeLayoutGeneration!==base.generation||row.layoutJobId)reject('STALE_BASE');}
  for(const base of Object.values(p.sectionMap)){const row=await t.get('sections',base.id);if(!row||row.revision!==base.revision||row.redirectTo||row.lifecycle!=='active')reject('STALE_BASE');}
  const result={created:[],updated:[],suggestions:[],denied:0};for(const item of prepared){const c=item.candidate,entry=c.entryRef?await t.get('thoughts',p.entryMap[c.entryRef].id):null,suppressed=new Map();for(const e of p.evidence.filter(e=>e.role!=='context_only'))for(const x of await t.all('thoughtSuppressions','byScope',e.scopeToken,100))if(x.status==='active')suppressed.set(x.id,x);for(const x of await t.all('thoughtSuppressions','byExact',item.exactSignature,100))if(x.status==='active')suppressed.set(x.id,x);
   const oldScopes=new Set([...suppressed.values()].flatMap(x=>x.scopeTokens)),newEvidence=item.evidence.some(e=>e.role!=='context_only'&&!oldScopes.has(e.scopeToken)),policy=ActionPolicy.evaluate({candidate:c,entry,suppressed:!!suppressed.size,newEvidence});
   if(policy.decision==='deny'){result.denied++;continue;}
   if(policy.decision==='suggest'){const existing=await t.all('organizerSuggestions','byLogicalKey',item.logicalKey,100);if(existing.some(x=>['pending','rejected','accepted'].includes(x.status)))continue;if(entry){for(const older of await t.all('organizerSuggestions','byTarget',prefix(['entry',entry.id,0]),100)){if(older.baseRevision!==entry.revision&&older.item.candidate.action===c.action){older.status='superseded';older.statusKey=4;await t.put('organizerSuggestions',older);}}}const id=s.uuid(),sequence=await nextSequence(t),baseRevision=entry?.revision??0;await t.put('organizerSuggestions',{id,jobId:job.id,targetKind:entry?'entry':'library',targetId:entry?.id||'library',baseRevision,status:'pending',statusKey:0,sequence,logicalKey:item.logicalKey,reason:policy.reason,policyVersion:1,consentEpoch:job.consentEpoch,item,projection:{provider:p.provider,maps:p.maps,entryMap:p.entryMap,topicMap:p.topicMap,sectionMap:p.sectionMap},sourceRecordIds:[...new Set(p.evidence.flatMap(e=>e.sourceRecordIds))],topicStatusKeys:[],createdAt:s.clock()});result.suggestions.push(id);continue;}
   const r=await this.apply(t,item,p,entry,'ai',job.id);result[r.created?'created':'updated'].push(r.id);
  }
  job.state='completed';job.stateKey=1;job.result=result;job.finishedAt=s.clock();delete job.owner;await t.put('organizerJobs',job);const work=await t.get('organizerWorkItems',job.id);if(work){work.state='completed';work.stateKey=1;work.checkpoint='committed';await t.put('organizerWorkItems',work);}await t.put('operationReceipts',{id:receiptId,namespace:'organizer',ownerId:job.id,operationSequence:job.fence,createdAt:s.clock(),result});if(job.usageId)await s.organizerLedger.settle(t,job.usageId);return result;
 });}
 async apply(t,item,p,entry,actor,operationId){const s=this.store,c=item.candidate,at=s.clock();let created=false;
  if(c.action==='create'||c.action==='exact'){const exact=await t.edge('thoughts','byExact',item.exactKey);if(exact?.lifecycle==='active'){entry=exact;}else if(c.action==='exact')reject('INVALID_OUTPUT');else{created=true;const id=s.uuid(),sequence=await nextSequence(t);entry={id,storageSchema:2,...(c.title?.trim()?{title:c.title}:{}),thoughtText:c.body,note:'',family:FAMILY_BY_TYPE[c.type],type:c.type,formation:c.formation,origin:actor,revision:0,contentRevision:0,fieldRevisions:Object.fromEntries(ENTRY_FIELDS.map(f=>[f,0])),organizationRevision:0,dependencyRevision:0,createdAt:at,updatedAt:at,createdSequence:sequence,updatedSequence:sequence,hasHumanAction:actor==='user',userEdited:actor==='user',protections:protections(actor,operationId,at),authorship:Object.fromEntries(ENTRY_FIELDS.map(f=>[f,{actor,everHumanConfirmed:actor==='user',operationId,at}])),organizationIntents:{included:[],excluded:[]},lifecycle:'active',freshness:'current',integrity:'complete',staleReasons:[],sourceRecordIds:[],inputRefs:[],exactSignature:item.exactSignature,exactKey:item.exactKey,topics:[],types:['type:'+c.type],provenanceType:c.localOriginal?'input_original':'input_derived'};}}
  if(!entry)reject('INVALID_OUTPUT');const baseRevision=entry.revision,before=entrySnapshot(entry);
  if(actor==='user'&&!created&&c.action==='create'){for(const field of ENTRY_FIELDS)markHuman(entry,field,operationId,at);entry.revision++;}
  if(c.action==='refresh'||c.action==='classify'){const field=c.action==='refresh'?'body':'type',key=field==='body'?'thoughtText':'type';entry[key]=c[field];entry.fieldRevisions[field]++;entry.revision++;if(field==='body')entry.contentRevision++;if(actor==='user')markHuman(entry,field,operationId,at);entry.exactSignature=item.exactSignature;delete entry.exactKey;entry.family=FAMILY_BY_TYPE[entry.type];entry.types=['type:'+entry.type];if(c.action==='refresh'){for(const d of await t.all('dependencies','byTarget',prefix(['entry',entry.id])))await t.delete('dependencies',d.id);entry.freshness='current';entry.staleReasons=[];}}
  // Evidence consolidation is append-only; no duplicate-driven body/order rewrite.
  for(const e of item.evidence){const ref=Object.keys(p.maps).find(key=>p.maps[key]===e),span=c.evidence.find(x=>x.ref===ref),contributionKey=JSON.stringify([entry.id,e.inputId,e.basedOnContentRevision,e.role,e.versionToken,span?.start??null,span?.end??null]);if(await t.edge('provenance','byContribution',contributionKey))continue;await t.put('provenance',{id:s.uuid(),ownerKind:'entry',ownerId:entry.id,generationId:operationId,inputId:e.inputId,basedOnContentRevision:e.basedOnContentRevision,actualVersion:{inputRevision:e.basedOnContentRevision,projectionVersion:1,selectedFields:e.selectedFields,fieldDigests:e.fieldDigests},role:e.role,contributionType:e.role==='context_only'?'context':c.localOriginal?'exact_excerpt':c.formation==='synthesized'?'combination':'paraphrase',formation:c.formation,generatedAt:at,generator:{providerId:p.provider.providerId,providerVersion:p.provider.adapterVersion,modelVersion:p.provider.modelVersion,taskSchemaVersion:1,promptTemplateVersion:1,policyVersion:1},inputAuthorshipAtUse:'working_input',entryFieldAuthorshipAtCommit:actor,sourceRecordIds:e.sourceRecordIds,sourceIdentityTokens:e.sourceIdentityTokens,scopeToken:e.scopeToken,versionToken:e.versionToken,...(span?{span:{field:span.field,start:span.start,end:span.end}}:{}),availability:'resolvable',contributionKey});const depId=JSON.stringify([e.inputId,'entry',entry.id]),old=await t.get('dependencies',depId);if(!old||c.action==='refresh')await t.put('dependencies',{id:depId,inputId:e.inputId,inputList:[e.inputId,entry.id],thoughtId:entry.id,targetKind:'entry',targetId:entry.id,eligibilityEpochAtUse:e.epoch,basedOnContentRevision:e.basedOnContentRevision,selectedFields:e.selectedFields,fieldDigests:e.fieldDigests,validatedAgainstContentRevision:e.basedOnContentRevision,status:'valid',roles:[e.role],sourceRecordIds:e.sourceRecordIds,scopeToken:e.scopeToken,versionToken:e.versionToken});entry.sourceRecordIds=[...new Set([...entry.sourceRecordIds,...e.sourceRecordIds])];if(!entry.inputRefs.some(x=>x.inputBlockId===e.inputId))entry.inputRefs.push({inputBlockId:e.inputId,basedOnContentRevision:e.basedOnContentRevision});entry.dependencyRevision++;}
  if((created||c.action==='assign'||c.localOriginal&&c.topicRef)&&(c.topicRef||c.newTopic))await this.organize(t,entry,c,p,actor,operationId);
  entry.meaningfulContentAt=created||c.action==='refresh'?at:(entry.meaningfulContentAt||entry.updatedAt||entry.createdAt);entry.updatedAt=at;entry.updatedSequence=await nextSequence(t);refreshEntryIndex(entry);await t.put('thoughts',entry);await queueSearch(t,'entry',entry);await journal(s,t,{kind:'library_entry',entityId:entry.id,before,after:entrySnapshot(entry),fieldMask:created||actor==='user'&&c.action==='create'?ENTRY_FIELDS:c.action==='refresh'?['body']:c.action==='classify'?['type']:['provenance'],actor,reason:created?'baseline':'organizer',important:true,operationId,baseRevision,afterRevision:entry.revision,sourceRecordIds:entry.sourceRecordIds});return {id:entry.id,created};
 }
 async organize(t,entry,c,p,actor,operationId){const s=this.store,at=s.clock();let topic;
  if(c.topicRef)topic=await s.canonicalTopic(t,p.topicMap[c.topicRef].id);else{let matched=await t.edge('topics','byName',c.newTopic.toLocaleLowerCase());if(matched?.lifecycle==='removed'&&actor!=='user')return;if(matched?.redirectTo)matched=await s.canonicalTopic(t,matched.id);if(matched?.lifecycle==='active'&&!matched.redirectTo&&!matched.layoutJobId)topic=matched;else{const id=s.uuid(),sectionId=s.uuid();topic={id,defaultSectionId:sectionId,name:c.newTopic,summary:'',sourceRecordIds:[...entry.sourceRecordIds],nameKey:c.newTopic.toLocaleLowerCase(),revision:0,organizationRevision:0,activeLayoutGeneration:1,activeKey:0,pinKey:1,pinRank:rankBetween(),negativeUpdatedSequence:0,lifecycle:'active',createdBy:actor,createdAt:at,protections:protections(actor,operationId,at)};if(actor==='user')markHuman(topic,'name',operationId,at);await t.put('topics',topic);await t.put('sections',{id:JSON.stringify([id,1,sectionId]),topicId:id,layoutGeneration:1,sectionId,isDefault:true,title:'',rank:rankBetween(),revision:0,activeKey:0,lifecycle:'active',protections:protections(actor,operationId,at)});await journal(s,t,{kind:'topic',entityId:id,before:null,after:topic,fieldMask:['name'],actor,reason:'baseline',important:true,operationId,sourceRecordIds:entry.sourceRecordIds});}}
  if(topic.lifecycle!=='active')return;if(topic.layoutJobId||actor!=='user'&&entry.organizationIntents.excluded.includes(topic.id))reject('STALE_BASE');const id=JSON.stringify([topic.id,topic.activeLayoutGeneration,entry.id]),old=await t.get('placements',id);if(old&&(old.lifecycle!=='active'||old.sectionProtection||old.orderProtection)){if(actor!=='user')reject('STALE_BASE');}if(old?.lifecycle==='active')return;
  let section=await t.get('sections',c.sectionRef?p.sectionMap[c.sectionRef].id:JSON.stringify([topic.id,topic.activeLayoutGeneration,topic.defaultSectionId]));if(c.newSection){const existing=(await t.rangePage('sections','byTopicOrder',prefix([topic.id,topic.activeLayoutGeneration,0]),null,100)).rows.map(x=>x.value).find(x=>x.lifecycle==='active'&&!x.redirectTo&&x.title===c.newSection);if(existing)section=existing;else{const sectionId=s.uuid(),last=await t.edge('sections','byTopicOrder',prefix([topic.id,topic.activeLayoutGeneration,0]),'prev');section={id:JSON.stringify([topic.id,topic.activeLayoutGeneration,sectionId]),topicId:topic.id,layoutGeneration:topic.activeLayoutGeneration,sectionId,title:c.newSection,sourceRecordIds:[...entry.sourceRecordIds],rank:String(Number(last?.rank||0)+1024).padStart(12,'0'),revision:0,activeKey:0,lifecycle:'active',protections:protections(actor,operationId,at)};await t.put('sections',section);await queueSearch(t,'section',section);await journal(s,t,{kind:'section',entityId:sectionId,documentId:topic.id,before:null,after:section,fieldMask:['title'],actor,reason:'baseline',important:true,operationId,sourceRecordIds:entry.sourceRecordIds});}}
  const last=await t.edge('placements','bySectionOrder',prefix([topic.id,topic.activeLayoutGeneration,section.sectionId,0]),'prev'),row={id,topicId:topic.id,layoutGeneration:topic.activeLayoutGeneration,entryId:entry.id,sectionId:section.sectionId,rank:String(Number(last?.rank||0)+1024).padStart(12,'0'),sectionRank:section.rank,revision:(old?.revision??-1)+1,activeKey:0,lifecycle:'active',membershipAuthorship:actor,sectionProtection:actor==='user',orderProtection:actor==='user'};await t.put('placements',row);entry.topics=[...new Set([...entry.topics,topic.id])];entry.organizationRevision++;if(actor==='user'){entry.organizationIntents.excluded=entry.organizationIntents.excluded.filter(id=>id!==topic.id);entry.organizationIntents.included.push(topic.id);for(const f of ['topics','section','order'])markHuman(entry,f,operationId,at);}topic.organizationRevision++;await s.touchTopic(t,topic);await queueSearch(t,'topic',topic);await journal(s,t,{kind:'placement',entityId:id,documentId:topic.id,before:old||null,after:row,fieldMask:['membership','section','order'],actor,reason:'place',important:true,operationId,sourceRecordIds:entry.sourceRecordIds});
 }
}
