import {reject} from './contracts.js';
export const DEFAULT_CONTROLS=Object.freeze({dailyRequests:20,batchMode:'recommended',aiOnboardingSeen:false,readingSort:'asc',inputReadingSort:'asc',libraryView:'original'});
export async function organizerControls(s){await s.finishFoundation();return s.run(()=>s.repository.transaction(false,async t=>{const saved=await t.get('meta','organizer-controls'),budget=await t.get('meta','organizer-budget'),now=Date.parse(s.clock()),used=budget&&now-budget.dailyAt<86400000?budget.daily?.requests||0:0;const usageAudit={original:0,ai:0,failed:0};for(const row of await t.all('meta')){const kind=row.id.startsWith('originalProviderRequest:')?'original':row.id.startsWith('aiPresentationRequest:')?'ai':null;if(!kind||!row.startedAt||Date.parse(row.startedAt)<(budget?.dailyAt||now)||now-Date.parse(row.startedAt)>=86400000)continue;const dispatched=row.phaseTimestamps?.fetch_started;if(!dispatched)continue;usageAudit[kind]++;if(['failed','outcome_unknown'].includes(row.state))usageAudit.failed++;}return {usageAudit,...DEFAULT_CONTROLS,...Object.fromEntries(Object.keys(DEFAULT_CONTROLS).filter(k=>saved?.[k]!==undefined).map(k=>[k,saved[k]])),usedRequests:used,resetAt:budget?new Date(budget.dailyAt+86400000).toISOString():null};},['meta']));}
export async function setOrganizerControls(s,changes){
 if(!changes||typeof changes!=='object'||Array.isArray(changes)||Object.keys(changes).some(k=>!Object.hasOwn(DEFAULT_CONTROLS,k)))reject('INVALID_OUTPUT');
 if(changes.inputReadingSort!==undefined&&!['asc','desc'].includes(changes.inputReadingSort))reject('INVALID_OUTPUT');
 if(changes.readingSort!==undefined&&!['asc','desc'].includes(changes.readingSort)||changes.libraryView!==undefined&&!['original','ai'].includes(changes.libraryView))reject('INVALID_OUTPUT');
 if(changes.dailyRequests!==undefined&&(!Number.isInteger(changes.dailyRequests)||changes.dailyRequests<1||changes.dailyRequests>200)||changes.batchMode!==undefined&&!['recommended','compact'].includes(changes.batchMode)||changes.aiOnboardingSeen!==undefined&&typeof changes.aiOnboardingSeen!=='boolean')reject('INVALID_OUTPUT');
 await s.foundationWrite(async t=>{const prior=await t.get('meta','organizer-controls');await t.put('meta',{...DEFAULT_CONTROLS,...prior,...changes,id:'organizer-controls'});});return organizerControls(s);
}
