import {rankTopicCandidates} from './topic-quality.js';
import {planDelta,commitOriginalDelta,originalAutoUpdateEnabled} from '../dual-view.js';
import {inputProjection,checkEvidenceInTransaction} from '../thought-evidence.js';
import {prefix} from '../thought-model.js';
import {hashText} from '../dedupe.js';
import {bytes,descriptorOK,reject,safeError} from './contracts.js';
import {requestFromInputProjection,TASK_PROFILES} from './deepseek.js';
import {leaseGuard} from './commit.js';

const DEFAULT_TOPIC='未归入主题',bootstrapId='originalOrganizerBootstrap';
const originalJob=job=>job?.kind==='original_organize';
const emptyBootstrap=()=>({id:bootstrapId,state:'not_started',cursorSequence:-1,totalEligible:0,processed:0,updatedAt:null,lastError:null});
async function bootstrapPlan(store,t){const state=await t.get('meta',bootstrapId)||emptyBootstrap(),filter=await t.get('meta','smart-filter'),rows=[];for(const ix of await t.all('blockIndex','bySequence')){const p=await inputProjection(store,t,ix.id);if(p&&!await store.isFiltered(t,p.block,filter))rows.push({id:ix.id,documentId:p.documentId,sequence:ix.sequence});}const remaining=rows.filter(x=>x.sequence>state.cursorSequence),first=remaining[0],selected=first?remaining.slice(0,remaining.findIndex(x=>x.documentId!==first.documentId)<0?remaining.length:remaining.findIndex(x=>x.documentId!==first.documentId)).slice(0,Math.min(20,store.organizerBudget.limits.maxInputs)):[];return {state,rows,remaining,selected,totalEligible:rows.length,advanceSequence:selected.length?selected.at(-1).sequence:state.cursorSequence};}
export async function originalBootstrapStatus(store){await store.finishFoundation();return store.run(()=>store.repository.transaction(false,async t=>{const p=await bootstrapPlan(store,t),s=p.state;return {...s,totalEligible:Math.max(s.totalEligible||0,p.totalEligible),remainingInput:p.remaining.length,processed:Number.isSafeInteger(s.processed)?s.processed:p.rows.filter(x=>x.sequence<=s.cursorSequence).length,selected:p.selected};}));}
export async function startBootstrap(store){return store.foundationWrite(async t=>{const p=await bootstrapPlan(store,t),s=p.state;if(s.state==='completed')return s;const row={...s,state:'running',totalEligible:Math.max(s.totalEligible||0,p.totalEligible),updatedAt:store.clock(),lastError:null};await t.put('meta',row);return row;});}
export async function completeBootstrapBatch(store,job){if(!job.bootstrap)return null;return store.foundationWrite(async t=>{const s=await t.get('meta',bootstrapId)||emptyBootstrap();if(s.state==='completed'||job.bootstrapAdvanceSequence<=s.cursorSequence)return s;const p=await bootstrapPlan(store,t),row={...s,state:'running',cursorSequence:job.bootstrapAdvanceSequence,totalEligible:Math.max(s.totalEligible||0,p.totalEligible),processed:p.rows.filter(x=>x.sequence<=job.bootstrapAdvanceSequence).length,updatedAt:store.clock(),lastError:null};if(!p.rows.some(x=>x.sequence>row.cursorSequence))row.state='completed';await t.put('meta',row);return row;});}
export async function pauseBootstrap(store,code){return store.foundationWrite(async t=>{const s=await t.get('meta',bootstrapId)||emptyBootstrap();if(s.state==='running')await t.put('meta',{...s,state:'paused',lastError:code,updatedAt:store.clock()});});}
const runtimeId='originalOrganizerRuntime';
const diagnosticError=(code,stage)=>{const mapped={CREDENTIAL_FAILURE:'NO_CREDENTIAL',INVALID_CREDENTIAL:'INVALID_CREDENTIAL',RATE_LIMITED:'RATE_LIMITED',PROVIDER_TIMEOUT:'PROVIDER_TIMEOUT',NETWORK_ERROR:'NETWORK_ERROR',INVALID_PROVIDER_OUTPUT:'INVALID_PROVIDER_OUTPUT',STALE_BASE:'BASE_CHANGED',CANCELLED:stage==='commit'?'COMMIT_FAILED':'WORKER_INTERRUPTED',INVALID_OUTPUT:stage==='materialize'?'SPAN_VALIDATION_FAILED':stage==='commit'?'COMMIT_FAILED':'INVALID_PROVIDER_OUTPUT'}[code];return mapped||(code==='STORAGE_FAILED'&&stage==='commit'?'COMMIT_FAILED':code);};
const dispatchReason=(code,stage)=>{const reason={provider_registry:'provider_not_registered',provider_enabled:'provider_disabled',credential:'credential_unavailable',task_profile:'task_kind_not_supported',budget:'budget_blocked',request_build:'request_build_failed',permission:'permission_blocked',job_claim:'dispatch_not_reached'}[stage];return reason||(code==='BUDGET_EXCEEDED'?'budget_blocked':null);};
export async function runtimeStatus(store,patch){return store.foundationWrite(async t=>{const prior=await t.get('meta',runtimeId)||{id:runtimeId,lastUpdatedAt:null,lastApiProcessed:0,state:'pending',lastError:null};await t.put('meta',{...prior,...patch,id:runtimeId,updatedAt:store.clock()});});}
async function completeEmptyBootstrap(store){return store.foundationWrite(async t=>{const s=await t.get('meta',bootstrapId)||emptyBootstrap();if(s.state==='running')await t.put('meta',{...s,state:'completed',updatedAt:store.clock(),lastError:null});});}
async function claimGate(store,owner){return store.run(()=>store.repository.transaction(false,async t=>{const now=Date.parse(store.clock()),jobs=await t.all('organizerJobs','byMaintenance',prefix(['original_organize']),100),running=jobs.find(job=>job.state==='running'&&job.leaseUntil>now);if(running)return {code:'ACTIVE_LEASE',remainingMs:Math.max(0,running.leaseUntil-now),owner:running.owner===owner?'current':'previous'};const retry=jobs.find(job=>job.state==='retry'&&job.nextAttemptAt>now);if(retry)return {code:'RETRY_WAITING',remainingMs:Math.max(0,retry.nextAttemptAt-now)};if(jobs.some(job=>job.state==='cancelled'))return {code:'CANCELLED',remainingMs:0};return {code:'INVALID_JOB_STATE',remainingMs:0};}));}
export async function recoverOriginalWork(store,owner,{manual=false}={}){return store.foundationWrite(async t=>{const now=Date.parse(store.clock()),all=await t.all('organizerJobs','byMaintenance',prefix(['original_organize']),100),jobs=all.filter(job=>job.bootstrap);let result={code:'INVALID_JOB_STATE',remainingMs:0};for(const job of jobs){if(job.state==='cancelled'){result={code:'CANCELLED',remainingMs:0};continue;}const expired=job.state==='running'&&job.leaseUntil<=now,previousWorker=job.state==='running'&&job.owner!==owner,retryDue=job.state==='retry'&&job.nextAttemptAt<=now,retryManual=manual&&['paused','retry'].includes(job.state);if(expired||previousWorker||retryDue||retryManual){job.fence++;job.state='queued';job.stateKey=0;job.nextAttemptAt=0;delete job.owner;delete job.leaseUntil;await t.put('organizerJobs',job);const work=await t.get('organizerWorkItems',job.id);if(work){work.state='queued';work.stateKey=0;work.checkpoint='selected';await t.put('organizerWorkItems',work);}result={code:expired?'LEASE_EXPIRED_RECLAIMABLE':previousWorker?'STALE_OWNER_RECLAIMABLE':'QUEUED',remainingMs:0};continue;}if(job.state==='running')result={code:'ACTIVE_LEASE',remainingMs:Math.max(0,job.leaseUntil-now)};else if(job.state==='retry')result={code:'RETRY_WAITING',remainingMs:Math.max(0,job.nextAttemptAt-now)};else if(job.state==='queued')result={code:'QUEUED',remainingMs:0};}return result;});}
const sameInputScope=(a,b)=>a.length===b.length&&a.every((id,index)=>id===b[index]);
const runtimeRepairId='originalOrganizerRuntimeRepairVersion';
export async function selfHealOriginalRuntime(store,queued,{runtimeSnapshot=null}={}){const plan=queued?.plan;if(!queued?.queued||plan?.phase!=='bootstrap'||!plan.selected.length)return {repaired:false,manualRecovery:false};return store.foundationWrite(async t=>{const runtime=await t.get('meta',runtimeId),safetyRuntime=runtimeSnapshot||runtime,bootstrap=await t.get('meta',bootstrapId)||emptyBootstrap(),marker=await t.get('meta',runtimeRepairId),job=await t.get('organizerJobs',queued.id),selected=plan.selected.map(item=>item.id),receipts=job?await t.all('operationReceipts','byOwner',prefix(['organizer',job.id]),2):[],usage=job?await t.all('organizerUsage','byJob',prefix([job.id]),2):[],preDispatch=safetyRuntime?.providerStatus==='not_sent'&&safetyRuntime?.validatorResult==='not_started'&&safetyRuntime?.commitResult==='not_started',sameJob=!safetyRuntime?.lastJobId||safetyRuntime.lastJobId===job?.id,sameBatch=job?.bootstrap===true&&job.bootstrapAdvanceSequence===plan.advanceSequence&&sameInputScope(job.checkpointInputIds||[],selected),uncommitted=bootstrap.state!=='completed'&&bootstrap.cursorSequence<plan.advanceSequence,safe=preDispatch&&sameJob&&sameBatch&&uncommitted&&job&&!['completed','cancelled','abandoned'].includes(job.state)&&!marker&&!receipts.length&&!usage.length;if(!safe)return {repaired:false,manualRecovery:!preDispatch||!!receipts.length||!!usage.length||job?.state==='completed'||job?.state==='cancelled'};const repaired={...job,state:'abandoned',stateKey:1,dedupeKey:'runtime-repaired:'+job.id,fence:Number.isSafeInteger(job.fence)?job.fence+1:1,error:'PRE_DISPATCH_RUNTIME_REPAIRED',repairedAt:store.clock(),repairReason:'SAFE_PRE_DISPATCH_RUNTIME_CORRUPTION'};for(const key of ['owner','leaseUntil','nextAttemptAt','audit','usageId','requestId','scopeToken'])delete repaired[key];await t.put('organizerJobs',repaired);await t.delete('organizerWorkItems',job.id);await t.put('meta',{id:runtimeRepairId,version:1,jobId:job.id,bootstrapCursor:bootstrap.cursorSequence,appliedAt:store.clock()});await t.put('meta',{...runtime,id:runtimeId,state:'running',stage:'repairing',reasonCode:'SAFE_PRE_DISPATCH_RUNTIME_CORRUPTION',claimStatus:null,retryRemainingMs:0,lastError:null,lastErrorCode:null,updatedAt:store.clock()});return {repaired:true,manualRecovery:false,oldJobId:job.id,inputCount:selected.length};});}

// Planning never exposes text. It selects only active, Smart-Filter-eligible
// changes from one conversation, so a batch cannot widen into unrelated chats.
export async function planOriginalWork(store,{limit=store.organizerBudget.limits.maxInputs}={}){
 if(!Number.isInteger(limit)||limit<1||limit>store.organizerBudget.limits.maxInputs)reject('BUDGET_EXCEEDED');
 const bootstrap=await originalBootstrapStatus(store);
 if(bootstrap.state!=='completed')return store.run(()=>store.repository.transaction(false,async t=>{const selected=bootstrap.selected.slice(0,Math.min(20,limit)),topics=new Set();for(const x of selected)for(const dep of await t.all('dependencies','byInput',x.id))for(const placement of await t.all('placements','byEntry',prefix([dep.targetId||dep.thoughtId])))topics.add(placement.topicId);return {phase:'bootstrap',bootstrap,selected,acknowledgeInputIds:[],topicIds:[...topics].slice(0,20),counts:{addedInput:0,changedInput:0,removedInput:0,affectedTopic:topics.size,affectedEntry:0},advanceSequence:selected.length?selected.at(-1).sequence:bootstrap.cursorSequence};}));
 const delta=await planDelta(store,'original');
 const projected=await store.run(()=>store.repository.transaction(false,async t=>{
  const out=[];for(const change of delta.changes.filter(x=>x.eligible&&(x.kind==='added'||x.kind==='changed')).sort((a,b)=>a.deltaSequence-b.deltaSequence||a.id.localeCompare(b.id))){const p=await inputProjection(store,t,change.id);if(p)out.push({...change,documentId:p.documentId,body:p.body});}return out;
 }));
 const candidates=[],local=[];
 for(const {body,...item} of projected){const before=delta.checkpoint.inputVersions[item.id];if(before?.removalState==='active'&&!before.sourcePurged&&before.eligible!==false&&before.bodyDigest&&before.bodyDigest===await hashText(body))local.push(item.id);else candidates.push(item);}
 const first=candidates[0],selected=first?candidates.filter(x=>x.documentId===first.documentId).slice(0,limit):[],topics=new Set();
 await store.run(()=>store.repository.transaction(false,async t=>{for(const change of selected)for(const dep of await t.all('dependencies','byInput',change.id))for(const placement of await t.all('placements','byEntry',prefix([dep.targetId||dep.thoughtId])))topics.add(placement.topicId);}));
 return {...delta,phase:'incremental',selected,acknowledgeInputIds:[...local,...delta.changes.filter(x=>x.kind==='removed'||!x.eligible).map(x=>x.id)],topicIds:[...topics].slice(0,20)};

}

export async function enqueueOriginalWork(store,{limit}={}){
 const plan=await planOriginalWork(store,{limit});
 if(plan.phase==='bootstrap'&&plan.bootstrap.state!=='running')return {queued:false,plan};
 if(plan.acknowledgeInputIds.length)await commitOriginalDelta(store,plan.acknowledgeInputIds);
 if(!plan.selected.length)return {queued:false,plan};
 const specs=plan.selected.map(x=>({inputId:x.id,role:'primary',selectedFields:['body']})),evidence=await store.evidenceFor(specs),status=await store.status();if(!status.enabled)reject('CANCELLED');
 const dedupeKey=await hashText(JSON.stringify(['original_organize',plan.phase,evidence.map(x=>x.versionToken),plan.topicIds]));
 return store.foundationWrite(async t=>{await checkEvidenceInTransaction(store,t,evidence);const old=await t.edge('organizerJobs','byDedupe',dedupeKey);if(old)return {queued:true,id:old.id,plan};const id=store.uuid(),sequence=await store.nextOrganizerSequence(t),sourceRecordIds=[...new Set(evidence.flatMap(x=>x.sourceRecordIds))],row={id,kind:'original_organize',policyVersion:1,state:'queued',stateKey:0,nextAttemptAt:0,priority:0,sequence,dedupeKey,requestId:store.uuid(),scopeToken:store.uuid(),specs,topicIds:plan.topicIds,checkpointInputIds:[...new Set(plan.selected.map(x=>x.id))],...(plan.phase==='bootstrap'?{bootstrap:true,bootstrapAdvanceSequence:plan.advanceSequence}:{}),consentEpoch:status.epoch,sourceRecordIds,attempts:0,fence:0,createdAt:store.clock()};await t.put('organizerJobs',row);await t.put('organizerWorkItems',{id,jobId:id,state:'queued',stateKey:0,sequence,inputIds:row.checkpointInputIds,sourceRecordIds,checkpoint:'selected'});return {queued:true,id,plan};
 });
}

export async function claimOriginalWork(store,owner){return store.foundationWrite(async t=>{const now=Date.parse(store.clock()),active=await t.all('organizerJobs','byMaintenance',prefix(['original_organize',0]),100);let concurrent=0;for(const job of active)if(job.state==='running'&&job.leaseUntil>now)concurrent++;if(concurrent>=store.organizerBudget.limits.maxConcurrentJobs)return null;const job=active.find(x=>(x.state==='queued'||x.state==='retry'||x.state==='running'&&x.leaseUntil<=now)&&x.nextAttemptAt<=now);if(!job)return null;if(job.attempts>store.organizerBudget.limits.maxRetries){job.state='failed';job.stateKey=1;job.error='TIMEOUT';await t.put('organizerJobs',job);return null;}job.state='running';job.owner=owner;job.fence++;job.requestId=store.uuid();job.scopeToken=store.uuid();job.attempts++;job.leaseUntil=now+store.organizerBudget.limits.timeoutMs+1000;await t.put('organizerJobs',job);return job;});}

export async function originalProjection(store,job){
 const evidence=await store.evidenceFor(job.specs);
 return store.run(()=>store.repository.transaction(false,async t=>{
  const gate=await t.get('meta','gate');if(!gate?.enabled||gate.epoch!==job.consentEpoch)reject('CANCELLED');await checkEvidenceInTransaction(store,t,evidence);
  const inputs=[],maps={};for(let i=0;i<evidence.length;i++){const e=evidence[i],p=await inputProjection(store,t,e.inputId);if(!p)reject('STALE_BASE');const ref='i'+i;inputs.push({ref,role:'primary',fields:{body:p.body}});maps[ref]=e;}
  const candidateIds=job.kind==='original_simple'?await rankTopicCandidates(store,t,inputs.map(x=>x.fields.body),job.topicIds||[]):job.topicIds||[];const topicCandidates=[],topicMap={},sectionMap={};for(const id of candidateIds){if(topicCandidates.length>=20)break;const topic=await store.canonicalTopic(t,id);if(topic.id!==id||topic.lifecycle!=='active'||topic.layoutJobId)continue;const topicRef='t'+topicCandidates.length,sections=[];for(const {value:raw} of (await t.rangePage('sections','byTopicOrder',prefix([id,topic.activeLayoutGeneration,0]),null,20)).rows){const section=await store.safeOrganization(t,'section',raw);if(section?.lifecycle!=='active')continue;const title=section.title||'正文',sectionRef='s'+Object.keys(sectionMap).length;sections.push({id:sectionRef,name:title});sectionMap[sectionRef]={id:section.id,revision:section.revision,topicRef,title};}topicMap[topicRef]={id,revision:topic.revision,organizationRevision:topic.organizationRevision,generation:topic.activeLayoutGeneration,name:topic.name};topicCandidates.push({id:topicRef,name:topic.name,sections});}
  const request={requestId:job.requestId,inputs,entries:[],allowedTopicRefs:[],allowedSectionRefs:[],topicCandidates,budget:{maxOutputBytes:store.organizerBudget.limits.maxOutputBytes}};
  const decision=store.organizerBudget.evaluate({inputCount:inputs.length,targetCount:0,contentBytes:bytes(inputs),requestBytes:bytes(request)});if(decision.decision!=='allow')reject('BUDGET_EXCEEDED');return {request,maps,entryMap:{},topicMap,sectionMap,evidence};
 }));
}

export function materializeOriginalCandidates(rows,request,projection){
 const inputs=request.inputs,candidates=[];for(const row of rows){if(row.uncertain)continue;const spans=row.spans.length?row.spans:(inputs.length===1?[{inputRef:inputs[0].ref,start:0,end:inputs[0].fields.body.length}]:null);if(!spans)reject('INVALID_OUTPUT');for(const span of spans){const input=inputs.find(x=>x.ref===span.inputRef);if(!input||!Number.isSafeInteger(span.start)||!Number.isSafeInteger(span.end)||span.start<0||span.end<=span.start||span.end>input.fields.body.length)reject('INVALID_OUTPUT');const body=input.fields.body.slice(span.start,span.end);if(!body.trim())reject('INVALID_OUTPUT');const topicRef=Object.entries(projection.topicMap).find(([,value])=>value.name===row.topic)?.[0],sectionRef=topicRef?Object.entries(projection.sectionMap).find(([,value])=>value.topicRef===topicRef&&value.title===row.section)?.[0]:undefined;candidates.push({action:'create',body,type:row.type||'idea',formation:'explicit',evidence:[{ref:span.inputRef,field:'body',start:span.start,end:span.end}],...(topicRef?{topicRef}: {newTopic:row.topic||DEFAULT_TOPIC}),...(sectionRef?{sectionRef}:row.section?{newSection:row.section}:{}),localOriginal:true});}}
 return candidates;
}

export class OriginalOrganizerRunner {
 constructor(store,{provider,credentials}={}){this.store=store;this.provider=provider;this.credentials=credentials;this.owner=store.uuid();}
 async resumePaused(){return recoverOriginalWork(this.store,this.owner,{manual:true});}
 async wake({manual=false}={}){let recovery=null;if(manual){await startBootstrap(this.store);recovery=await this.resumePaused();}else{if(!await originalAutoUpdateEnabled(this.store))return null;recovery=await recoverOriginalWork(this.store,this.owner);}const bootstrap=await originalBootstrapStatus(this.store);if(bootstrap.state==='not_started'||bootstrap.state==='paused')return {pending:false,bootstrap,recovery};const result=await this.stepWithDiagnostics();return {...result,recovery};}
async step(){const s=this.store;await enqueueOriginalWork(s);const claim=await claimOriginalWork(s,this.owner);if(!claim)return {pending:false};let timer;try{const descriptor=descriptorOK(this.provider?.describe()),projection=await originalProjection(s,claim),credential=await this.credentials.acquire();projection.provider=descriptor;if(credential.status!=='ready')reject('CREDENTIAL_FAILURE');const providerRequest=requestFromInputProjection(projection,'original_classification');await s.foundationWrite(async t=>{const job=await leaseGuard(s,t,claim);job.audit={taskType:'original_organize',dataCategories:['working_input','topic_section_candidates'],inputCount:providerRequest.inputs.length,approximateSize:bytes(providerRequest),provider:descriptor.providerId,modelVersion:descriptor.modelVersion,providerVersion:descriptor.adapterVersion};job.usageId=await s.organizerLedger.reserve(t,job,projection.request);await t.put('organizerJobs',job);});const controller=new AbortController();let rows;try{rows=await Promise.race([this.provider.execute(providerRequest,{signal:controller.signal,credential:credential.handle}),new Promise((_,r)=>{timer=setTimeout(()=>{controller.abort();r({code:'PROVIDER_TIMEOUT'});},s.organizerBudget.limits.timeoutMs);})]);}finally{clearTimeout(timer);this.credentials.revoke(credential.handle);}const candidates=materializeOriginalCandidates(rows,projection.request,projection),prepared=await s.libraryCommit.prepare(candidates,projection);await s.repository.checkpoint('original-organizer-before-commit');const result=await s.libraryCommit.commit(claim,projection,prepared);await commitOriginalDelta(s,claim.checkpointInputIds);const bootstrap=await completeBootstrapBatch(s,claim);await s.foundationWrite(async t=>{await t.put('meta',{id:'originalOrganizerRuntime',lastUpdatedAt:s.clock(),lastApiProcessed:providerRequest.inputs.length,lastJobId:claim.id,state:'updated'});});return {pending:true,result,bootstrap};
 }catch(error){clearTimeout(timer);const code=safeError(error);await s.foundationWrite(async t=>{const job=await t.get('organizerJobs',claim.id);if(!originalJob(job)||job.fence!==claim.fence||job.state!=='running')return;const paused=['UNAVAILABLE','CREDENTIAL_FAILURE','INVALID_CREDENTIAL','BUDGET_EXCEEDED'].includes(code),terminal=['CANCELLED','STALE_BASE'].includes(code)||job.attempts>s.organizerBudget.limits.maxRetries||['INVALID_OUTPUT','INVALID_PROVIDER_OUTPUT'].includes(code)&&job.attempts>=2;job.state=paused?'paused':terminal?'failed':'retry';job.stateKey=paused||terminal?1:0;job.error=code;job.nextAttemptAt=Date.parse(s.clock())+Math.min(60000,1000*2**job.attempts);delete job.owner;await t.put('organizerJobs',job);await t.put('meta',{id:'originalOrganizerRuntime',lastUpdatedAt:null,lastApiProcessed:0,lastJobId:job.id,state:'pending',lastError:code});});if(claim.bootstrap)await pauseBootstrap(s,code);return {pending:true,error:code};}
 }
 async stepWithDiagnostics(){
  const s=this.store;let claim=null,timer,stage='batch_selection',plan=null;
  try{
   if(!this.provider){stage='provider_registry';reject('UNAVAILABLE');}
   const runtimeBeforeAttempt=await s.run(()=>s.repository.transaction(false,t=>t.get('meta',runtimeId),['meta']));let queued=await enqueueOriginalWork(s);plan=queued.plan;
   const batch=plan?.phase==='bootstrap'?{batchStart:(plan.bootstrap.processed||0)+1,batchEnd:(plan.bootstrap.processed||0)+plan.selected.length,selectedCount:plan.selected.length,totalEligible:plan.bootstrap.totalEligible}:{};
   await runtimeStatus(s,{state:'running',stage:'batch_selected',lastError:null,providerStatus:'not_sent',validatorResult:'not_started',commitResult:'not_started',reasonCode:null,claimStatus:null,retryRemainingMs:0,...batch});
   if(!queued.queued){if(plan?.phase==='bootstrap'&&plan.bootstrap.state==='running'&&!plan.selected.length)await completeEmptyBootstrap(s);return {pending:false,plan};}
   stage='job_claim';claim=await claimOriginalWork(s,this.owner);if(!claim){let reason=await claimGate(s,this.owner);if(reason.code==='INVALID_JOB_STATE'&&plan?.phase==='bootstrap'){await runtimeStatus(s,{state:'running',stage:'repairing',providerStatus:'not_sent',validatorResult:'not_started',commitResult:'not_started',reasonCode:'SAFE_PRE_DISPATCH_RUNTIME_CORRUPTION',claimStatus:null,retryRemainingMs:0,lastError:null,lastErrorCode:null});const healed=await selfHealOriginalRuntime(s,queued,{runtimeSnapshot:runtimeBeforeAttempt});if(healed.repaired){queued=await enqueueOriginalWork(s);plan=queued.plan;claim=await claimOriginalWork(s,this.owner);reason=claim?null:await claimGate(s,this.owner);}else if(healed.manualRecovery){await runtimeStatus(s,{state:'paused',stage:'recovery_refused',providerStatus:'not_sent',reasonCode:'MANUAL_RECOVERY_REQUIRED',claimStatus:null,retryRemainingMs:0,lastError:null,lastErrorCode:'MANUAL_RECOVERY_REQUIRED'});if(plan?.phase==='bootstrap')await pauseBootstrap(s,'MANUAL_RECOVERY_REQUIRED');return {pending:false,plan,reason:{code:'MANUAL_RECOVERY_REQUIRED'}};}}
   if(!claim){const active=reason.code==='ACTIVE_LEASE';await runtimeStatus(s,{state:active?'running':'paused',stage:'dispatch_gate',providerStatus:'not_sent',reasonCode:reason.code,claimStatus:reason.code,retryRemainingMs:reason.remainingMs,lastError:null,lastErrorCode:null});if(plan?.phase==='bootstrap'&&!active)await pauseBootstrap(s,reason.code);return {pending:false,plan,reason};}}
   await runtimeStatus(s,{state:'running',stage:'job_claimed',lastJobId:claim.id});
   stage='provider_registry';const descriptor=descriptorOK(this.provider.describe());if(typeof this.provider.supportsTask==='function'&&!this.provider.supportsTask('original_classification')){stage='task_profile';reject('UNAVAILABLE');}
   stage='credential';const credentialState=this.credentials?.status?await this.credentials.status():null;if(credentialState&&!credentialState.hasCredential)reject('CREDENTIAL_FAILURE');if(credentialState&&!credentialState.providerEnabled){stage='provider_enabled';reject('UNAVAILABLE');}const credential=await this.credentials?.acquire();if(credential?.status!=='ready')reject('CREDENTIAL_FAILURE');
   stage='budget';const projection=await originalProjection(s,claim);projection.provider=descriptor;
   stage='request_build';const providerRequest=requestFromInputProjection(projection,'original_classification');
   await runtimeStatus(s,{state:'running',stage:'api_request',providerStatus:'sending',validatorResult:'not_started',commitResult:'not_started',apiInputCount:providerRequest.inputs.length,reasonCode:null});
   await s.foundationWrite(async t=>{const job=await leaseGuard(s,t,claim);job.audit={taskType:'original_organize',dataCategories:['working_input','topic_section_candidates'],inputCount:providerRequest.inputs.length,approximateSize:bytes(providerRequest),provider:descriptor.providerId,modelVersion:descriptor.modelVersion,providerVersion:descriptor.adapterVersion};job.usageId=await s.organizerLedger.reserve(t,job,projection.request);await t.put('organizerJobs',job);});
   stage='request';const controller=new AbortController();let rows;try{rows=await Promise.race([this.provider.execute(providerRequest,{signal:controller.signal,credential:credential.handle}),new Promise((_,r)=>{timer=setTimeout(()=>{controller.abort();r({code:'PROVIDER_TIMEOUT'});},s.organizerBudget.limits.timeoutMs);})]);}finally{clearTimeout(timer);this.credentials.revoke(credential.handle);}
   await runtimeStatus(s,{state:'running',stage:'response_validated',providerStatus:'received',validatorResult:'passed'});
   stage='materialize';const candidates=materializeOriginalCandidates(rows,projection.request,projection),prepared=await s.libraryCommit.prepare(candidates,projection);
   stage='commit';await runtimeStatus(s,{state:'running',stage:'commit',commitResult:'committing'});await s.repository.checkpoint('original-organizer-before-commit');const result=await s.libraryCommit.commit(claim,projection,prepared);await commitOriginalDelta(s,claim.checkpointInputIds);const bootstrap=await completeBootstrapBatch(s,claim);
   await runtimeStatus(s,{lastUpdatedAt:s.clock(),lastApiProcessed:providerRequest.inputs.length,lastJobId:claim.id,state:'updated',stage:'committed',providerStatus:'success',validatorResult:'passed',commitResult:'committed',lastError:null,lastErrorCode:null});return {pending:true,result,bootstrap};
  }catch(error){clearTimeout(timer);const raw=safeError(error),code=diagnosticError(raw,stage),reason=dispatchReason(raw,stage),bootstrap=await originalBootstrapStatus(s);if(claim)await s.foundationWrite(async t=>{const job=await t.get('organizerJobs',claim.id);if(!originalJob(job)||job.fence!==claim.fence||job.state!=='running')return;const paused=['UNAVAILABLE','CREDENTIAL_FAILURE','INVALID_CREDENTIAL','BUDGET_EXCEEDED'].includes(raw),terminal=['CANCELLED','STALE_BASE'].includes(raw)||job.attempts>s.organizerBudget.limits.maxRetries||['INVALID_OUTPUT','INVALID_PROVIDER_OUTPUT'].includes(raw)&&job.attempts>=2;job.state=paused?'paused':terminal?'failed':'retry';job.stateKey=paused||terminal?1:0;job.error=code;job.nextAttemptAt=Date.parse(s.clock())+Math.min(60000,1000*2**job.attempts);delete job.owner;await t.put('organizerJobs',job);});await runtimeStatus(s,{state:'failed',stage:'error',lastUpdatedAt:null,lastApiProcessed:0,lastJobId:claim?.id||null,lastError:code,lastErrorCode:code,reasonCode:reason,providerStatus:stage==='request'?code:'not_sent',validatorResult:stage==='materialize'?'failed':'not_started',commitResult:stage==='commit'?'failed':'not_started'});if(claim?.bootstrap||bootstrap.state==='running')await pauseBootstrap(s,code);return {pending:true,error:code};}
 }
 }
