
import {planDynamicOriginalBatch} from './original-batch.js';
import {isTransientTopic} from './topic-quality.js';
import {hashText} from '../dedupe.js';
import {bytes,descriptorOK,reject,safeError} from './contracts.js';
import {requestFromInputProjection} from './deepseek.js';
import {originalBootstrapStatus,originalProjection,pauseBootstrap,planOriginalWork,runtimeStatus,startBootstrap} from './original.js';

const DEFAULT_TOPIC='未归入主题',RUNNER_MARKER='originalSimpleRunnerVersion',CURRENT_REQUEST='originalProviderRequestCurrent',REQUEST_PREFIX='originalProviderRequest:',ACTION_PREFIX='originalProviderAction:';
const ACTIVE_REQUEST_STATES=new Set(['prepared','sent','response_received','validated']);
const errorCode=(code,stage,step)=>{if(['HOST_PERMISSION_MISSING','HOST_PERMISSION_NOT_GRANTED','CSP_BLOCKED','WRONG_FETCH_CONTEXT','INTERNAL_RUNTIME_ERROR'].includes(code))return code;if(code==='UNAVAILABLE')return 'PROVIDER_UNAVAILABLE';if(code==='BUDGET_EXCEEDED')return 'BUDGET_EXCEEDED';if(code==='STORAGE_FAILED'||code==='STORAGE_FULL'){if(stage==='committing'&&step==='library_commit')return 'LIBRARY_COMMIT_FAILED';if(step==='bootstrap_state')return 'BOOTSTRAP_STATE_WRITE_FAILED';if(step==='single_flight_check'||step==='single_flight_marker'||step==='single_flight_pointer')return 'SINGLE_FLIGHT_ACQUIRE_FAILED';if(step==='request_ledger')return 'PREPARE_LEDGER_WRITE_FAILED';if(step==='budget_state'||step==='usage_reservation')return 'BATCH_STATE_WRITE_FAILED';if(step==='trace_write')return 'TRACE_WRITE_FAILED';return 'BATCH_STATE_WRITE_FAILED';}return {CREDENTIAL_FAILURE:'NO_CREDENTIAL',INVALID_CREDENTIAL:'INVALID_CREDENTIAL',RATE_LIMITED:'RATE_LIMITED',PROVIDER_TIMEOUT:'PROVIDER_TIMEOUT',NETWORK_ERROR:'NETWORK_ERROR',RESPONSE_BODY_READ_FAILED:'RESPONSE_BODY_READ_FAILED',INVALID_JSON:'INVALID_JSON',INVALID_SCHEMA:'INVALID_SCHEMA',INVALID_PROVIDER_OUTPUT:'INVALID_PROVIDER_OUTPUT',SPAN_VALIDATION_FAILED:'SPAN_VALIDATION_FAILED',PROVIDER_BAD_REQUEST:'PROVIDER_BAD_REQUEST',MODEL_NOT_AVAILABLE:'MODEL_NOT_AVAILABLE',PROVIDER_UNAVAILABLE:'PROVIDER_UNAVAILABLE',INVALID_OUTPUT:stage==='span_validating'?'SPAN_VALIDATION_FAILED':'INVALID_SCHEMA',STALE_BASE:'BASE_CHANGED',CANCELLED:'CANCELLED',REQUEST_ALREADY_IN_FLIGHT:'SINGLE_FLIGHT_ACQUIRE_FAILED',OUTCOME_UNKNOWN:'OUTCOME_UNKNOWN'}[code]||'INTERNAL_RUNTIME_ERROR';};

async function createRequestLedger(t,row,onStep=()=>{}){onStep('single_flight_check');const actionId=ACTION_PREFIX+row.userActionId;if(await t.get('meta',actionId))reject('REQUEST_ALREADY_IN_FLIGHT');const aiPointer=await t.get('meta','aiPresentationRequestCurrent'),ai=aiPointer&&await t.get('meta','aiPresentationRequest:'+aiPointer.requestId);if(ai&&ACTIVE_REQUEST_STATES.has(ai.state))reject('REQUEST_ALREADY_IN_FLIGHT');const pointer=await t.get('meta',CURRENT_REQUEST),current=pointer?.requestId?await t.get('meta',REQUEST_PREFIX+pointer.requestId):null;if(current&&ACTIVE_REQUEST_STATES.has(current.state))reject('REQUEST_ALREADY_IN_FLIGHT');onStep('single_flight_marker');await t.put('meta',{id:actionId,requestId:row.requestId,createdAt:row.startedAt});onStep('request_ledger');await t.put('meta',{id:REQUEST_PREFIX+row.requestId,...row});onStep('single_flight_pointer');await t.put('meta',{id:CURRENT_REQUEST,requestId:row.requestId,updatedAt:row.startedAt});}
async function transitionRequest(store,requestId,state,patch={}){if(!requestId)return null;return store.foundationWrite(async t=>{const row=await t.get('meta',REQUEST_PREFIX+requestId);if(!row)return null;if(['committed','failed','outcome_unknown'].includes(row.state))return row;const next={...row,...patch,state,updatedAt:store.clock()};await t.put('meta',next);return next;});}
async function traceRequest(store,requestId,state,patch={}){if(!requestId)return null;return store.foundationWrite(async t=>{const row=await t.get('meta',REQUEST_PREFIX+requestId);if(!row||['committed','failed','outcome_unknown'].includes(row.state))return row;const at=store.clock(),phase=patch.phase,next={...row,...patch,state,updatedAt:at};if(phase)next.phaseTimestamps={...(row.phaseTimestamps||{}),[phase]:row.phaseTimestamps?.[phase]||at};await t.put('meta',next);return next;});}
function deadlineGuard(deadlineAt){if(Date.now()>=deadlineAt)reject('PROVIDER_TIMEOUT');}
async function failCurrentRequest(store,code){return store.foundationWrite(async t=>{const pointer=await t.get('meta',CURRENT_REQUEST),row=pointer?.requestId?await t.get('meta',REQUEST_PREFIX+pointer.requestId):null;if(!row||!ACTIVE_REQUEST_STATES.has(row.state))return null;const next={...row,state:'failed',error:code,updatedAt:store.clock()};await t.put('meta',next);return next;});}

// This is a one-way fence only. The Simple Runner never claims, leases, resumes,
// or otherwise depends on these legacy job rows.
export async function isolateLegacyOriginalJobs(store){return store.foundationWrite(async t=>{const prior=await t.get('meta',RUNNER_MARKER);if(prior?.version===1)return {count:0,alreadyApplied:true};let count=0;for(const job of await t.all('organizerJobs')){if(job.kind!=='original_organize'||['completed','cancelled','legacy_stuck'].includes(job.state))continue;job.state='legacy_stuck';job.stateKey=1;job.fence=Number.isSafeInteger(job.fence)?job.fence+1:1;job.dedupeKey='legacy-stuck:'+job.id;job.error='LEGACY_STUCK';job.legacyStuckAt=store.clock();for(const key of ['owner','leaseUntil','nextAttemptAt','requestId','scopeToken'])delete job[key];await t.put('organizerJobs',job);const work=await t.get('organizerWorkItems',job.id);if(work){work.state='legacy_stuck';work.stateKey=1;work.checkpoint='legacy_ignored';await t.put('organizerWorkItems',work);}count++;}await t.put('meta',{id:RUNNER_MARKER,version:1,legacyIgnoredCount:count,appliedAt:store.clock()});return {count,alreadyApplied:false};});}

export async function simpleOriginalBatch(store,plan){const specs=plan.selected.map(item=>({inputId:item.id,role:'primary',selectedFields:['body']})),evidence=await store.evidenceFor(specs),cursor=plan.phase==='bootstrap'?plan.bootstrap.cursorSequence:plan.checkpoint?.lastSequence||0,batchId=await hashText(JSON.stringify(['original-simple-v2',plan.phase,cursor,evidence.map(item=>[item.inputId,item.basedOnContentRevision,item.versionToken])]));return {batchId,specs,evidence,cursor};}

function normalizeResult(result,request){
 if(result&&Array.isArray(result.items)&&Array.isArray(result.invalidItems))return result;
 // Compatibility for deterministic fixture providers used by older regression tests.
 if(Array.isArray(result)){const items=[];for(const row of result){const grouped=new Map();for(const span of row.spans||[]){if(!grouped.has(span.inputRef))grouped.set(span.inputRef,[]);grouped.get(span.inputRef).push({start:span.start,end:span.end});}for(const [inputRef,spans] of grouped)items.push({inputRef,topic:{...(row.topic?{proposedName:row.topic}:{})},section:{...(row.section?{proposedName:row.section}:{})},type:row.type||'idea',relatedGroupingCandidate:row.relatedGroup||null,spans,uncertain:row.uncertain===true});}return {items,invalidItems:[]};}
 reject('INVALID_PROVIDER_OUTPUT');
}

export function materializeOriginalBatch(providerResult,request,projection){
 const result=normalizeResult(providerResult,request),candidates=[],terminal=[],byRef=new Map(request.inputs.map(x=>[x.ref,x])),invalid=new Map(result.invalidItems.map(x=>[x.inputRef,x.code||'INVALID_PROVIDER_OUTPUT']));
 for(const row of result.items){if(invalid.has(row.inputRef)||!byRef.has(row.inputRef))continue;try{const input=byRef.get(row.inputRef),spans=row.spans.length?row.spans:[{start:0,end:input.text.length}],sectionRef=row.uncertain?null:row.section?.existingSectionId,topicRef=(row.uncertain?null:row.topic?.existingTopicId)||(sectionRef?projection.sectionMap[sectionRef]?.topicRef:null),newTopic=row.uncertain?DEFAULT_TOPIC:topicRef?null:(isTransientTopic(row.topic?.proposedName)?DEFAULT_TOPIC:row.topic?.proposedName)||DEFAULT_TOPIC,newSection=row.uncertain?null:sectionRef?null:row.section?.proposedName;
   if(topicRef&&!projection.topicMap[topicRef]||sectionRef&&(!projection.sectionMap[sectionRef]||topicRef&&projection.sectionMap[sectionRef].topicRef!==topicRef))throw Error('bad reference');
   for(const span of spans){if(!Number.isSafeInteger(span.start)||!Number.isSafeInteger(span.end)||span.start<0||span.end<=span.start||span.end>input.text.length)throw Error('bad span');const body=input.text.slice(span.start,span.end);if(!body.trim())throw Error('empty span');candidates.push({action:'create',inputRef:row.inputRef,body,type:row.type||'idea',formation:'explicit',evidence:[{ref:row.inputRef,field:'body',start:span.start,end:span.end}],...(topicRef?{topicRef}:{newTopic}),...(sectionRef?{sectionRef}:newSection?{newSection}:{}),localOriginal:true});}
  }catch{invalid.set(row.inputRef,'SPAN_VALIDATION_FAILED');for(let i=candidates.length-1;i>=0;i--)if(candidates[i].inputRef===row.inputRef)candidates.splice(i,1);}}
 const validRefs=new Set(candidates.map(x=>x.inputRef));for(const input of request.inputs){const code=invalid.get(input.ref);terminal.push(code?{inputRef:input.ref,status:'manual_required',code}:validRefs.has(input.ref)?{inputRef:input.ref,status:'processed'}:{inputRef:input.ref,status:'manual_required',code:'INVALID_PROVIDER_OUTPUT'});}
 return {candidates,terminal};
}

function progressFor(plan,batch){if(plan.phase==='bootstrap')return {phase:'bootstrap',cursorBefore:batch.cursor,advanceSequence:plan.advanceSequence,processedBefore:plan.bootstrap.processed||0,totalEligible:plan.bootstrap.totalEligible,remainingCount:plan.bootstrap.remainingInput,selectedCount:plan.selected.length,inputIds:plan.selected.map(x=>x.id)};return {phase:'incremental',inputIds:plan.selected.map(x=>x.id),nextInputVersions:plan.nextCheckpoint.inputVersions,lastSequence:plan.nextCheckpoint.lastSequence};}
// A local acknowledgement is tied to the exact plan snapshot. A concurrent body
// edit must remain pending, never be acknowledged merely because an older note edit
// had matched the cached original body.
async function acknowledgeLocalDelta(store,plan){return store.foundationWrite(async t=>{
 const current=await t.get('meta','originalOrganizerCheckpoint')||{id:'originalOrganizerCheckpoint',view:'original',version:2,inputVersions:{},lastSequence:0},versions={...current.inputVersions};
 for(const id of plan.acknowledgeInputIds){const expected=plan.nextCheckpoint.inputVersions[id],row=await t.get('inputStates',id);if(!expected){if(row)reject('STALE_BASE');delete versions[id];continue;}if(!row||row.contentRevision!==expected.contentRevision||row.removalState!==expected.removalState||!!row.sourcePurged!==expected.sourcePurged)reject('STALE_BASE');versions[id]={...versions[id],...expected};}
 await t.put('meta',{...current,inputVersions:versions,lastSequence:Math.max(current.lastSequence||0,plan.nextCheckpoint.lastSequence||0),updatedAt:store.clock()});
});}
async function receiptFor(store,batchId){return store.run(()=>store.repository.transaction(false,t=>t.get('operationReceipts','original-simple:'+batchId),['operationReceipts']));}

export class SimpleOriginalOrganizerRunner {
 constructor(store,{provider,credentials,batchLimit=20}={}){this.batchLimit=batchLimit;this.store=store;this.provider=provider;this.credentials=credentials;this.running=null;this.controller=null;}
 async reconcileInterrupted(){if(this.running)return {active:true};const s=this.store;return s.foundationWrite(async t=>{const pointer=await t.get('meta',CURRENT_REQUEST),row=pointer?.requestId?await t.get('meta',REQUEST_PREFIX+pointer.requestId):null,runtime=await t.get('meta','originalOrganizerRuntime');let code=null;if(row?.state==='prepared'){row.state='failed';row.error='WORKER_INTERRUPTED';row.errorCode='WORKER_INTERRUPTED';row.updatedAt=s.clock();await t.put('meta',row);code='WORKER_INTERRUPTED';}else if(row&&ACTIVE_REQUEST_STATES.has(row.state)){row.state='outcome_unknown';row.error='OUTCOME_UNKNOWN';row.errorCode='OUTCOME_UNKNOWN';row.updatedAt=s.clock();await t.put('meta',row);code='OUTCOME_UNKNOWN';}else if(!row&&['sending','validating','committing'].includes(runtime?.state))code='OUTCOME_UNKNOWN';if(code)await t.put('meta',{...runtime,id:'originalOrganizerRuntime',state:'failed',stage:'failed',providerStatus:code,lastError:code,lastErrorCode:code,updatedAt:s.clock()});return {active:false,error:code};});}
 wake({manual=true,userActionId=this.store.uuid(),boundedActionId=null,batchLimit=this.batchLimit}={}){if(!manual)return Promise.resolve({pending:false,error:'MANUAL_ACTION_REQUIRED'});if(this.running)return Promise.resolve({pending:true,error:'REQUEST_ALREADY_IN_FLIGHT'});this.controller=new AbortController();this.running=this.run(userActionId,{boundedActionId,batchLimit}).finally(()=>{this.running=null;this.controller=null;});return this.running;}
 async stop(code='CANCELLED'){this.controller?.abort();const row=await failCurrentRequest(this.store,code);if(row){await runtimeStatus(this.store,{state:'failed',stage:'failed',providerStatus:code,lastError:code,lastErrorCode:code});const bootstrap=await originalBootstrapStatus(this.store);if(bootstrap.state==='running')await pauseBootstrap(this.store,code);}return {stopped:!!row};}
 async run(userActionId,{boundedActionId=null,batchLimit=this.batchLimit}={}){const s=this.store,signal=this.controller.signal,assertActive=()=>{if(signal.aborted)reject('CANCELLED');},deadlineAt=Date.now()+30000;let stage='idle',localWriteStep='runtime_status',dbErrorCategory=null,providerRequest=null,usageId=null,plan=null,requestId=null,batchId=null,providerRequestCount=0,credential=null,committedResult=null;try{
  stage='preparing';await runtimeStatus(s,{state:'preparing',stage,localWriteStep,dbErrorCategory:null,providerStatus:'not_sent',validatorResult:'not_started',commitResult:'not_started',providerRequestCount:0,requestId:null,manualInputCount:0,validInputCount:0,committedItemCount:0,httpStatus:null,responseBytes:0,lastError:null,lastErrorCode:null});if(!this.provider)reject('UNAVAILABLE');localWriteStep='bootstrap_state';await runtimeStatus(s,{localWriteStep});await startBootstrap(s);localWriteStep='batch_selection';plan=await planDynamicOriginalBatch(s,{limit:batchLimit});const bootstrap=await originalBootstrapStatus(s),batchStart=(bootstrap.processed||0)+1,batchEnd=(bootstrap.processed||0)+plan.selected.length;await runtimeStatus(s,{state:'preparing',stage:'batch_selected',localWriteStep,batchStart,batchEnd,selectedCount:plan.selected.length,totalEligible:bootstrap.totalEligible,providerStatus:'not_sent',validatorResult:'not_started',commitResult:'not_started',reasonCode:null,claimStatus:null,retryRemainingMs:0,providerRequestCount:0,lastError:null,lastErrorCode:null});
  if(!plan.selected.length){assertActive();if(plan.phase==='bootstrap')await s.foundationWrite(async t=>{const b=await t.get('meta','originalOrganizerBootstrap');if(b)await t.put('meta',{...b,state:'completed',lastError:null,updatedAt:s.clock()});});if(plan.phase==='incremental'&&plan.acknowledgeInputIds.length)await acknowledgeLocalDelta(s,plan);await runtimeStatus(s,{state:'completed',stage:'completed'});return {pending:false,plan};}
  localWriteStep='legacy_isolation';await runtimeStatus(s,{localWriteStep});await isolateLegacyOriginalJobs(s);localWriteStep='batch_state';const batch=await simpleOriginalBatch(s,plan);batchId=batch.batchId;const prior=await receiptFor(s,batch.batchId);if(prior){const replayProjection={evidence:[],topicMap:{},sectionMap:{}},result=await s.libraryCommit.commitOriginalBatch(batch.batchId,replayProjection,[],null,[],progressFor(plan,batch)),resumed=await originalBootstrapStatus(s);await runtimeStatus(s,{state:'completed',stage:'completed',localWriteStep:'completed',providerStatus:'received',validatorResult:'passed',commitResult:'committed',providerRequestCount:0,lastUpdatedAt:s.clock(),lastApiProcessed:0,lastError:null,lastErrorCode:null});return {pending:true,result,bootstrap:resumed,replayed:true,batchId:batch.batchId};}
  const descriptor=descriptorOK(this.provider.describe());if(typeof this.provider.supportsTask==='function'&&!this.provider.supportsTask('original_classification'))reject('UNAVAILABLE');stage='preparing';credential=await this.credentials?.acquire();assertActive();if(credential?.status!=='ready')reject('CREDENTIAL_FAILURE');requestId=s.uuid();await runtimeStatus(s,{requestId});const status=await s.status(),direct={id:batch.batchId,kind:'original_simple',boundedActionId,policyVersion:1,state:'direct',requestId,scopeToken:'original-simple:'+batch.batchId,specs:batch.specs,topicIds:plan.topicIds||[],checkpointInputIds:plan.selected.map(item=>item.id),consentEpoch:status.epoch,attempts:1,fence:1,bootstrap:plan.phase==='bootstrap',bootstrapAdvanceSequence:plan.advanceSequence};
  const projection=await originalProjection(s,direct);projection.provider=descriptor;providerRequest=requestFromInputProjection(projection,'original_classification');const approximateBytes=bytes(providerRequest),startedAt=s.clock(),ledgerRow={requestId,batchId:batch.batchId,userActionId,startedAt,state:'prepared',phase:'preparing',phaseTimestamps:{preparing:startedAt},inputCount:providerRequest.inputs.length,approximateBytes,provider:descriptor.providerId,model:descriptor.modelVersion,httpStatus:null,responseBytes:0,errorCode:null,committedItemCount:0,localWriteStep:'request_ledger',dbErrorCategory:null};direct.audit={taskType:'original_organize',dataCategories:['working_input','topic_section_candidates'],inputCount:providerRequest.inputs.length,approximateSize:approximateBytes,provider:descriptor.providerId,modelVersion:descriptor.modelVersion,providerVersion:descriptor.adapterVersion};assertActive();localWriteStep='single_flight_check';await runtimeStatus(s,{localWriteStep});await s.foundationWrite(t=>createRequestLedger(t,ledgerRow,step=>{localWriteStep=step;}));localWriteStep='budget_state';await runtimeStatus(s,{localWriteStep});usageId=await s.foundationWrite(t=>s.organizerLedger.reserve(t,direct,projection.request,step=>{localWriteStep=step;}));
  stage='fetch_started';localWriteStep='trace_write';deadlineGuard(deadlineAt);assertActive();await runtimeStatus(s,{state:'sending',stage,localWriteStep,providerStatus:'sending',validatorResult:'not_started',commitResult:'not_started',apiInputCount:providerRequest.inputs.length,providerRequestCount:0});const onTrace=async patch=>{stage=patch.phase;localWriteStep='trace_write';const state=stage==='fetch_started'?'sent':'response_received',row=await traceRequest(s,requestId,state,patch);if(!row||!['sent','response_received'].includes(row.state))reject('CANCELLED');await runtimeStatus(s,{state:'sending',stage,localWriteStep,providerStatus:stage==='fetch_started'?'sending':'received',providerRequestCount:stage==='fetch_started'?1:providerRequestCount,httpStatus:patch.httpStatus??row.httpStatus??null,responseBytes:patch.responseBytes??row.responseBytes??0});};let response;try{if(this.provider.notifiesDispatch!==true)providerRequestCount=1;response=await this.provider.execute(providerRequest,{signal:this.controller.signal,credential:credential.handle,deadlineAt,onTrace,onDispatch:()=>{providerRequestCount=1;}});}finally{this.credentials.revoke(credential.handle);}deadlineGuard(deadlineAt);
  stage='span_validating';await traceRequest(s,requestId,'response_received',{phase:stage});await runtimeStatus(s,{state:'validating',stage,providerStatus:'received',validatorResult:'validating',commitResult:'not_started'});const materialized=materializeOriginalBatch(response,providerRequest,projection);await runtimeStatus(s,{validInputCount:materialized.terminal.filter(x=>x.status==='processed').length,manualInputCount:materialized.terminal.filter(x=>x.status==='manual_required').length});const prepared=await s.libraryCommit.prepare(materialized.candidates,projection);deadlineGuard(deadlineAt);const validated=await traceRequest(s,requestId,'validated',{phase:stage});if(validated?.state!=='validated')reject('CANCELLED');
  stage='committing';localWriteStep='trace_write';await traceRequest(s,requestId,'validated',{phase:stage});await runtimeStatus(s,{state:'committing',stage,localWriteStep,providerStatus:'received',validatorResult:materialized.terminal.some(x=>x.status==='manual_required')?'partial':'passed',commitResult:'committing'});deadlineGuard(deadlineAt);assertActive();localWriteStep='library_commit';const result=await s.libraryCommit.commitOriginalBatch(batch.batchId,projection,prepared,usageId,materialized.terminal,progressFor(plan,batch),{requestId,userActionId,boundedActionId});committedResult=result;const complete=await originalBootstrapStatus(s);await runtimeStatus(s,{state:'completed',stage:'completed',localWriteStep:'completed',dbErrorCategory:null,providerStatus:'received',validatorResult:result.manualInputCount?'partial':'passed',commitResult:'committed',manualInputCount:result.manualInputCount,processedInputCount:result.processedInputCount,committedItemCount:result.committedInputCount??result.created.length+result.updated.length,lastUpdatedAt:s.clock(),lastApiProcessed:providerRequest.inputs.length,lastError:null,lastErrorCode:null});return {pending:true,result,bootstrap:complete,batchId:batch.batchId,providerRequestCount:1};
 }catch(error){if(committedResult)return {pending:true,result:committedResult,batchId,providerRequestCount};const raw=error?.code?(safeError(error)==='STORAGE_FAILED'&&!['STORAGE_FAILED','STORAGE_FULL'].includes(error.code)?'INTERNAL_RUNTIME_ERROR':safeError(error)):'INTERNAL_RUNTIME_ERROR';dbErrorCategory=error?.dbCategory||(raw==='BUDGET_EXCEEDED'?'policy_denied':null);const mapped=errorCode(raw,stage,localWriteStep);let ledger=null;try{ledger=await transitionRequest(s,requestId,'failed',{error:mapped,errorCode:mapped,localWriteStep,dbErrorCategory});}catch{}const code=ledger?.state==='outcome_unknown'?'OUTCOME_UNKNOWN':ledger?mapped:errorCode(raw,stage,localWriteStep),failedPhase=ledger?.phase||stage||'preparing';try{await runtimeStatus(s,{state:'failed',stage:failedPhase,localWriteStep,dbErrorCategory,providerStatus:providerRequestCount?code:'not_sent',validatorResult:['schema_validating','span_validating'].includes(failedPhase)?'failed':'not_started',commitResult:failedPhase==='committing'?'failed':'not_started',providerRequestCount,httpStatus:ledger?.httpStatus??null,responseBytes:ledger?.responseBytes??0,committedItemCount:ledger?.committedItemCount??0,lastApiProcessed:0,lastError:code,lastErrorCode:code,reasonCode:null});const bootstrap=await originalBootstrapStatus(s);if(bootstrap.state==='running')await pauseBootstrap(s,code);}catch{}return {pending:true,error:code,phase:failedPhase,localWriteStep,dbErrorCategory,plan,batchId,providerRequestCount};}finally{if(credential?.handle)this.credentials?.revoke(credential.handle);}}
}
