import {productionProviders,CredentialProvider,descriptorOK,safeError,reject,bytes} from './contracts.js';
import {InputProjectionGateway} from './gateway.js';
import {CandidateValidator} from './validator.js';
import {leaseGuard} from './commit.js';
export class OrganizerRunner {
 constructor(store,{providers=productionProviders,credentials=new CredentialProvider()}={}){this.store=store;this.providers=providers;this.credentials=credentials;this.owner=store.uuid();this.gateway=new InputProjectionGateway(store,store.organizerBudget);this.validator=new CandidateValidator(store.organizerBudget);}
 async step(){const s=this.store,claim=await s.claimOrganizer(this.owner);if(!claim)return {pending:false};let timer;try{const provider=this.providers[0];if(!provider)reject('UNAVAILABLE');const descriptor=descriptorOK(provider.describe()),projection=await this.gateway.project(claim);projection.provider=descriptor;const credential=await this.credentials.acquire({providerId:descriptor.providerId,scopeToken:claim.scopeToken,consentEpoch:claim.consentEpoch});if(credential.status!=='ready')reject('CREDENTIAL_FAILURE');
   await s.foundationWrite(async t=>{const job=await leaseGuard(s,t,claim);job.audit={taskType:'organize',dataCategories:['working_input',...(projection.request.entries.length?['related_entry_minimum']:[])],inputCount:projection.request.inputs.length,approximateSize:bytes(projection.request),provider:descriptor.providerId,modelVersion:descriptor.modelVersion,providerVersion:descriptor.adapterVersion};job.usageId=await s.organizerLedger.reserve(t,job,projection.request);await t.put('organizerJobs',job);const work=await t.get('organizerWorkItems',job.id);work.checkpoint='dispatched';work.fence=job.fence;work.attempts=job.attempts;await t.put('organizerWorkItems',work);});
   // Provider promise is intentionally outside store.run / any IDB transaction.
   const controller=new AbortController();let output;try{output=await Promise.race([provider.execute(structuredClone(projection.request),{signal:controller.signal,credential:credential.handle}),new Promise((_,r)=>{timer=setTimeout(()=>{controller.abort();r({code:'TIMEOUT'});},s.organizerBudget.limits.timeoutMs);})]);}finally{clearTimeout(timer);this.credentials.revoke(credential.handle);}
   const candidates=this.validator.validate(output,projection);if(typeof output==='string')output=JSON.parse(output);if(output.providerVersion!==descriptor.adapterVersion||output.modelVersion!==descriptor.modelVersion)reject('INVALID_OUTPUT');const prepared=await s.libraryCommit.prepare(candidates,projection);await s.repository.checkpoint('organizer-before-commit');const result=await s.libraryCommit.commit(claim,projection,prepared);return {pending:true,result};
  }catch(e){clearTimeout(timer);const code=e?.code==='INVALID_REQUEST'?'STALE_BASE':safeError(e);await s.foundationWrite(async t=>{const job=await t.get('organizerJobs',claim.id);if(!job||job.fence!==claim.fence||job.state!=='running')return;const pause=['UNAVAILABLE','CREDENTIAL_FAILURE','BUDGET_EXCEEDED'].includes(code),terminal=['CANCELLED','STALE_BASE'].includes(code)||job.attempts>s.organizerBudget.limits.maxRetries||code==='INVALID_OUTPUT'&&job.attempts>=2;job.state=pause?'paused':terminal?'failed':'retry';job.stateKey=pause||terminal?1:0;job.error=code;job.nextAttemptAt=Date.parse(s.clock())+Math.min(60000,1000*2**job.attempts);delete job.owner;await t.put('organizerJobs',job);});return {pending:true,error:code};}
 }
}
