import {validateMemoryRow,memoryRange,key,DEFAULT_PROFILE} from './memory/model.js';
import {BACKUP_VERSION,BACKUP_SCHEMA,BACKUP_SECTIONS,BACKUP_LIMITS,BackupValidator,backupMetaAllowed,backupHash,backupError,projectBackupEntity,projectImportEvidence,validateBackupItem} from './backup-format.js';
import {recordIndex,blockIndex,chatOf} from './idb-repository.js';
import {refreshEntryIndex,ENTRY_FIELDS,FAMILY_BY_TYPE,prefix} from './thought-model.js';
import {identify,hashText} from './dedupe.js';
import {STORAGE_KEY} from './constants.js';
import {validatePreferences,defaults} from './workspace.js';
const stores={sources:'records',inputDocuments:'documents',inputs:'blocks',inputStates:'inputStates',removals:'inputRemovals',timeEvidence:'times',filterIntents:'filterIntents',filterStates:'filterInputs',entries:'thoughts',topics:'topics',sections:'sections',placements:'placements',evidence:'provenance',dependencies:'dependencies',revisions:'revisions',suppressions:'thoughtSuppressions',relations:'entryRelations',completedLayouts:'organizerJobs',receipts:'operationReceipts',deletionFences:'tombstones',organizationState:'meta'};
const sections=Object.keys(BACKUP_SECTIONS),plain=value=>value&&typeof value==='object'&&!Array.isArray(value),activeRequest=row=>['prepared','sent','response_received','validated'].includes(row?.state);
const normalize=value=>JSON.parse(JSON.stringify(value));
async function busy(t){for(const key of ['originalProviderRequest','aiPresentationRequest']){const p=await t.get('meta',key+'Current');if(p&&activeRequest(await t.get('meta',key+':'+p.requestId)))return true;}const p=await t.get('meta','boundedOrganizerCurrent');if(p&&(await t.get('meta','boundedOrganizerAction:'+p.actionId))?.state==='running')return true;return (await t.all('topics')).some(x=>x.layoutJobId);}
function sourceIds(value,out=new Set()){if(!value||typeof value!=='object')return out;if(Array.isArray(value)){for(const v of value)sourceIds(v,out);return out;}for(const [key,v]of Object.entries(value)){if(key==='sourceRecordIds'&&Array.isArray(v))for(const id of v)out.add(id);else if(['sourceRecordId','originalTextReference'].includes(key)&&typeof v==='string')out.add(v);else if(typeof v==='object')sourceIds(v,out);}return out;}
export class BackupService {
 constructor(store,{appVersion='0.8.1'}={}){this.s=store;this.appVersion=appVersion;this.exports=new Map();this.restores=new Map();}
 expire(){for(const map of [this.exports,this.restores])for(const [id,row]of map)if(Date.now()-row.lastAt>15*60*1000)map.delete(id);}
 session(map,id){this.expire();const row=map.get(id);if(!row)backupError('BACKUP_SESSION_EXPIRED');row.lastAt=Date.now();return row;}
 async beginExport(){this.expire();await this.s.finishFoundation();await this.s.drainPurgeCleanup();await this.s.drainInvalidations();const state=await this.s.run(()=>this.s.repository.transaction(false,async t=>{if(await busy(t))backupError('BACKUP_BUSY');const c=await this.s.control(t);return {generation:(await t.get('meta','backup-data-generation'))?.value||0,settings:projectBackupEntity('settings',{id:'preferences',preferences:c.preferences,memoryAccessPolicy:c.memoryAccessPolicy,classificationRules:c.classificationRules,filterRules:c.filterRules})};}));
  const sessionId=crypto.randomUUID(),header={type:'header',format:'PAIA Backup',formatVersion:BACKUP_VERSION,appVersion:this.appVersion,createdAt:this.s.clock(),schemaVersion:BACKUP_SCHEMA,contentSections:sections,privacy:{localOnly:true,credentialsIncluded:false,sourceDeletionFences:true}},hash=await backupHash('',header);this.exports.clear();this.exports.set(sessionId,{...state,header,hash,section:0,after:null,sequence:0,count:0,counts:Object.fromEntries(sections.map(k=>[k,0])),lastAt:Date.now()});return {sessionId,header};
 }
 async project(t,section,row){let value=row,extra={};
  if(section==='sources'){value=row.value;const imported=value.sourceKey&&await t.get('importSources',value.sourceKey);if(imported)value={...value,importEvidence:projectImportEvidence(imported)};if(!await this.s.sourcePresent(t,[row.id]))return null;extra.order=(await t.get('recordIndex',row.id)).sequence;}
  if(section==='inputDocuments'){value=row.value;extra={order:row.sequence,working:projectBackupEntity(section,(await t.get('libraryDocuments',row.id))?.value||row.value)};}
  if(section==='inputs'){value=row.value;if(!await this.s.sourcePresent(t,[...sourceIds(value)]))return null;extra.order=(await t.get('blockIndex',row.id)).sequence;}
  if(section==='entries'){if(row.lifecycle==='quarantined'){if(row.quarantineSealed||!await this.s.sourcePresent(t,row.sourceRecordIds))return null;}else{row=await this.s.readableEntry(t,row.id);if(row.lifecycle==='invalidated'&&!row.hasHumanAction)return null;}value={...row,body:row.thoughtText};delete value.thoughtText;}
  if(['topics','sections'].includes(section))value=await this.s.safeOrganization(t,section==='topics'?'topic':'section',row);
  if(section==='completedLayouts'&&(row.kind!=='library_layout'||row.state!=='complete'))return null;
  if(section==='organizationState'){if(!backupMetaAllowed(row.id))return null;if(row.id.startsWith('memory:')){if(!validateMemoryRow(row))backupError('BACKUP_INVALID');if(row.kind==='topic'&&!await t.get('topics',row.topicId)||row.kind==='entry'&&(!await t.get('thoughts',row.entryId)||!await this.project(t,'entries',await t.get('thoughts',row.entryId)))||row.kind==='input'&&(!await t.get('inputStates',row.inputId)||!await t.get('blocks',row.inputId))||row.kind==='section'&&!await t.get('topics',row.topicId))return null;}value={id:row.id,data:row};}
  if(['evidence','dependencies','revisions','relations'].includes(section)&&!await this.s.sourcePresent(t,[...sourceIds(value)]))return null;
  if(section==='timeEvidence'&&await t.get('tombstones','source:'+row.id))return null;
  // Export explicit domain fields; transient indexes, caches, jobs and secrets
  // outside the suppression key are never selected from any database table.
  const item=normalize({type:'item',section,value:projectBackupEntity(section,value),...extra});validateBackupItem(item);return item;
 }
 async checkExportState(sessionId,state){if(this.exports.get(sessionId)!==state)backupError('BACKUP_SESSION_EXPIRED');await this.s.run(()=>this.s.repository.transaction(false,async t=>{if(((await t.get('meta','backup-data-generation'))?.value||0)!==state.generation)backupError('BACKUP_CHANGED');},['meta']));}
 async exportPage({sessionId,sequence}){const state=this.session(this.exports,sessionId);if(state.inflight){if(sequence===state.inflightSequence)return state.inflight;backupError('BACKUP_BUSY');}state.inflightSequence=sequence;state.inflight=this.exportChunk(sessionId,sequence,state).finally(()=>{state.inflight=null;});return state.inflight;}
 async exportChunk(sessionId,sequence,state){await this.checkExportState(sessionId,state);if(sequence===state.sequence-1&&state.lastPage)return state.lastPage;if(sequence!==state.sequence)backupError('BACKUP_INVALID');if(state.done)return {items:[],done:true};
  const result=await this.s.run(()=>this.s.repository.transaction(false,async t=>{if(((await t.get('meta','backup-data-generation'))?.value||0)!==state.generation)backupError('BACKUP_CHANGED');const items=[];let section=state.section,after=state.after,totalBytes=0;
   while(section<sections.length&&items.length<BACKUP_LIMITS.chunkItems){const name=sections[section];if(name==='settings'){items.push({type:'item',section:name,value:state.settings});section++;continue;}const page=await t.page(stores[name],{after:after??undefined,limit:BACKUP_LIMITS.chunkItems-items.length});for(const raw of page.rows){const item=await this.project(t,name,raw.value);if(item){const size=new TextEncoder().encode(JSON.stringify(item)).length;if(size>BACKUP_LIMITS.lineBytes)backupError('BACKUP_TOO_LARGE');if(items.length&&totalBytes+size>1024*1024)return {items,section,after};items.push(item);totalBytes+=size;}after=raw.key;}if(!page.next){section++;after=null;}}
   return {items,section,after};
  }));
  for(const item of result.items){state.hash=await backupHash(state.hash,item);state.count++;state.counts[item.section]++;}state.section=result.section;state.after=result.after;state.sequence++;state.done=result.section>=sections.length;if(state.done)result.items.push({type:'footer',itemCount:state.count,sectionCounts:state.counts,integrity:{algorithm:'SHA-256-chain',root:state.hash}});state.lastPage={items:result.items,done:state.done};await this.checkExportState(sessionId,state);return state.lastPage;
 }
 async beginRestore(){this.expire();this.restores.clear();const sessionId=crypto.randomUUID();this.restores.set(sessionId,{validator:new BackupValidator(),items:[],lastAt:Date.now(),validated:false});return {sessionId};}
 async stageRestore({sessionId,items}){const state=this.session(this.restores,sessionId);if(state.staging)backupError('BACKUP_BUSY');if(!Array.isArray(items)||items.length>50||state.validated)backupError('BACKUP_INVALID');state.staging=true;try{for(const item of items){await state.validator.add(item);if(item.type==='item')state.items.push(structuredClone(item));}return {received:state.validator.count};}catch(e){this.restores.delete(sessionId);throw e;}finally{state.staging=false;}}
 async validateReferences(state){const bySection=Object.fromEntries(sections.map(k=>[k,new Map(state.items.filter(x=>x.section===k).map(x=>[x.value.id,x]))]));state.bySection=bySection;const records=bySection.sources,inputs=bySection.inputs,entries=bySection.entries,topics=bySection.topics;
  const required=(condition)=>{if(!condition)backupError('BACKUP_INVALID');};
  for(const item of records.values()){const r=item.value;if(r.chatId&&r.sourceMessageId){const identity=await identify(r.chatId,r.sourceMessageId,r.originalText);required(r.contentHash===identity.contentHash&&(!r.sourceKey||r.sourceKey===identity.sourceKey));if(r.sourceKey)required(r.dedupeKey===identity.dedupeKey);item.derivedSourceKey=identity.sourceKey;}else required(r.contentHash===await hashText(r.originalText));}
  const importEvidence=new Map();for(const {value:r}of records.values())if(r.importEvidence){const key=r.importEvidence.sourceKey,serialized=JSON.stringify(projectImportEvidence(r.importEvidence));required(!importEvidence.has(key)||importEvidence.get(key)===serialized);importEvidence.set(key,serialized);}
  for(const {value:b}of inputs.values()){required(bySection.inputDocuments.has(b.documentId));for(const id of sourceIds(b))required(records.has(id));required(bySection.inputStates.has(b.id));}
  for(const {value:e}of entries.values()){required(Number.isSafeInteger(e.revision)&&e.revision>=0&&Object.hasOwn(FAMILY_BY_TYPE,e.type)&&['active','removed','invalidated','quarantined'].includes(e.lifecycle));for(const field of ENTRY_FIELDS)required(plain(e.protections[field])&&typeof e.protections[field].locked==='boolean'&&Number.isSafeInteger(e.fieldRevisions?.[field]));for(const id of e.sourceRecordIds)required(records.has(id));}
  for(const {value:t}of topics.values()){required(typeof t.name==='string'&&t.name.length<=300&&Number.isSafeInteger(t.activeLayoutGeneration)&&Number.isSafeInteger(t.organizationRevision)&&/^\d{12}$/.test(t.pinRank));if(t.redirectTo)required(topics.has(t.redirectTo)&&t.redirectTo!==t.id);const seen=new Set([t.id]);let row=t;while(row.redirectTo){required(!seen.has(row.redirectTo));seen.add(row.redirectTo);row=topics.get(row.redirectTo).value;}}
  for(const {value:p}of bySection.placements.values()){required(topics.has(p.topicId)&&entries.has(p.entryId)&&bySection.sections.has(JSON.stringify([p.topicId,p.layoutGeneration,p.sectionId]))&&/^\d{12}$/.test(p.rank)&&/^\d{12}$/.test(p.sectionRank));}
  for(const {value:e}of bySection.evidence.values()){required(entries.has(e.ownerId)&&bySection.inputStates.has(e.inputId));for(const id of e.sourceRecordIds||[])required(records.has(id));}
  for(const {value:r}of bySection.revisions.values()){required(typeof r.entityKey==='string'&&Number.isSafeInteger(r.sequence)&&Number.isFinite(Date.parse(r.at)));for(const id of sourceIds(r))required(records.has(id));}
  for(const {value:row}of bySection.organizationState.values()){if(row.id==='organizer-controls'){const c=row.data;required(Number.isInteger(c.dailyRequests)&&c.dailyRequests>=1&&c.dailyRequests<=200&&['compact','recommended'].includes(c.batchMode));}if(row.id==='thought-suppression-key')required(Array.isArray(row.data.value)&&row.data.value.length===32&&row.data.value.every(x=>Number.isInteger(x)&&x>=0&&x<=255));}
  const memoryRows=[...bySection.organizationState.values()].map(x=>x.value.data).filter(x=>x.id.startsWith('memory:'));for(const row of memoryRows){required(validateMemoryRow(row));if(row.kind==='profile')required(bySection.organizationState.has('memory:config'));if(row.profileId&&row.kind!=='activity')required(bySection.organizationState.has(key('profile',row.profileId)));if(row.kind==='topic')required(topics.has(row.topicId));if(row.kind==='entry')required(entries.has(row.entryId));if(row.kind==='input')required(inputs.has(row.inputId)&&bySection.inputStates.has(row.inputId));if(row.kind==='section')required(topics.has(row.topicId)&&[...bySection.sections.values()].some(x=>x.value.topicId===row.topicId&&x.value.sectionId===row.sectionId));}if(memoryRows.length)required(bySection.organizationState.has(key('profile',DEFAULT_PROFILE)));
  const preferences=bySection.settings.get('preferences')?.value.preferences;if(preferences){validatePreferences({timeDisplay:preferences.timeDisplay,timeEmphasis:preferences.timeEmphasis});for(const [key,value]of Object.entries(defaults()))if(!['timeDisplay','timeEmphasis'].includes(key))required(preferences[key]===value);required(Object.keys(preferences).every(k=>Object.hasOwn(defaults(),k)));}state.validated=true;
 }
 async targetSafety(t,state){if(await busy(t))return 'BACKUP_BUSY';for(const item of state.bySection.sources.values()){const r=item.value;if(await t.get('tombstones','source:'+(item.derivedSourceKey||r.sourceKey))||await t.get('tombstones','snapshot:'+r.dedupeKey)||state.bySection.deletionFences.has('source:'+(item.derivedSourceKey||r.sourceKey))||state.bySection.deletionFences.has('snapshot:'+r.dedupeKey))return 'BACKUP_PURGE_CONFLICT';}if((await t.get('meta','memory:config'))?.userTouched)return 'BACKUP_TARGET_NOT_EMPTY';for(const name of ['records','blocks','thoughts','topics','revisions','inputRemovals','thoughtSuppressions'])if(await t.count(name))return 'BACKUP_TARGET_NOT_EMPTY';return null;}
 async previewRestore({sessionId}){const state=this.session(this.restores,sessionId);if(state.staging)backupError('BACKUP_BUSY');const preview=state.validator.preview();await this.s.finishFoundation();if(!state.validated)await this.validateReferences(state);const reason=await this.s.run(()=>this.s.repository.transaction(false,t=>this.targetSafety(t,state)));return {...preview,canRestore:!reason,reason,restoreScope:'empty-library-only'};}
 async restore({sessionId,confirmation}){const state=this.session(this.restores,sessionId),preview=await this.previewRestore({sessionId});if(confirmation!==preview.integrity)backupError('BACKUP_CONFIRMATION_REQUIRED');if(!preview.canRestore)backupError(preview.reason);
  const result=await this.s.run(()=>this.s.repository.transaction(true,async t=>{const reason=await this.targetSafety(t,state);if(reason)backupError(reason);const max={records:0,blocks:0,documents:0};for(const row of await t.all('meta',null,memoryRange()))await t.delete('meta',row.id);
   for(const item of state.items){const {section,value,order}=item,row=structuredClone(value);if(section==='settings'){await t.put('meta',{id:'backup-recovery-settings',value:row});continue;}
    if(section==='sources'){if(row.importEvidence){await t.put('importSources',row.importEvidence);delete row.importEvidence;}await t.put('records',{id:row.id,value:row});await t.put('recordIndex',recordIndex(row,order));max.records=Math.max(max.records,order+1);continue;}
    if(section==='inputDocuments'){await t.put('documents',{id:row.id,value:row,sequence:order,chatKey:row.sourceConversationId?'chatgpt:'+row.sourceConversationId:undefined,displayKey:[-(Date.parse(row.lastSourceSentAt)||0),row.id]});await t.put('libraryDocuments',{id:row.id,value:item.working});max.documents=Math.max(max.documents,order+1);continue;}
    if(section==='inputs'){await t.put('blocks',{id:row.id,value:row});const record=row.sourceRecordId?state.bySection.sources.get(row.sourceRecordId)?.value:null;await t.put('blockIndex',blockIndex(row,order,record?[record]:[]));max.blocks=Math.max(max.blocks,order+1);continue;}
    if(section==='entries'){row.thoughtText=row.body;delete row.body;refreshEntryIndex(row);}
    if(section==='topics'){row.nameKey=row.name.toLocaleLowerCase();row.activeKey=row.lifecycle==='active'?0:1;row.countVersion=1;}
    if(['sections','placements'].includes(section))row.activeKey=row.lifecycle==='active'?0:1;
    if(section==='organizationState'){const data=row.data;if(row.id==='originalOrganizerBootstrap'&&data.state==='running')data.state='paused';await t.put('meta',data);continue;}
    await t.put(stores[section],row);
   }
   await t.put('meta',{id:'sequence',...max});
   // Rebuild derived indexes from the explicit entities. No imported index or
   // runnable worker job is trusted, and no Provider is invoked on restore.
   const sourcesByDocument=new Map(),documentsByChat=new Map();
   const add=(id,r)=>{if(!r)return;let keys=sourcesByDocument.get(id);if(!keys){keys=new Set();sourcesByDocument.set(id,keys);}keys.add(r.sourceKey||'legacy:'+r.id);};
   for(const {value:d}of state.bySection.inputDocuments.values())if(d.sourceConversationId){const key=(d.platform||'chatgpt')+':'+d.sourceConversationId,list=documentsByChat.get(key)||[];list.push(d.id);documentsByChat.set(key,list);}
   for(const {value:b}of state.bySection.inputs.values())for(const p of b.provenance)add(b.documentId,state.bySection.sources.get(p.sourceRecordId)?.value);
   // Original chat ownership survives moving its last working Input elsewhere.
   for(const {value:r}of state.bySection.sources.values())for(const id of documentsByChat.get((r.platform||'chatgpt')+':'+r.chatId)||[])add(id,r);
   for(const {value:doc}of state.bySection.inputDocuments.values()){this.s.changedSources=sourcesByDocument.get(doc.id)||new Set();await this.s.refreshDoc(t,doc.id);}
   await t.put('meta',{id:'library-search-rebuild',phase:0,cursor:null,complete:false});await t.put('meta',{id:'backup-last-restore',integrity:preview.integrity,createdAt:this.s.clock(),counts:preview.counts});
   // AI cache purge fences are reconstructed from evidence, not imported jobs.
   for(const {value:row}of state.bySection.organizationState.values())if(row.id.startsWith('aiPresentation:')){const p=row.data,sourceRecordIds=[...new Set((p.evidenceEntryIds||[]).flatMap(id=>state.bySection.entries.get(id)?.value.sourceRecordIds||[]))];await t.put('libraryMigrationItems',{id:'ai-presentation-fence:'+p.topicId,entityKind:'ai_presentation',ownerKind:'ai_presentation',ownerId:p.topicId,statusKey:1,sourceRecordIds});}
   return {restored:true,counts:preview.counts};
  }));this.restores.delete(sessionId);await this.recoverSettings();return result;
 }
 async recoverSettings(){const pending=await this.s.run(()=>this.s.repository.transaction(false,t=>t.get('meta','backup-recovery-settings'),['meta']));if(!pending)return;await this.s.finishFoundation();await this.s.write(async t=>{const c=await this.s.control(t);for(const key of ['preferences','memoryAccessPolicy','classificationRules','filterRules'])if(pending.value[key]!==undefined)c[key]=pending.value[key];await this.s.saveControl(t,c);});await this.s.run(()=>this.s.repository.transaction(true,t=>t.delete('meta','backup-recovery-settings'),['meta']));}
 cancel({sessionId}){this.exports.delete(sessionId);this.restores.delete(sessionId);return {cancelled:true};}
}
