export const ADAPTER_VERSION = '0.3.0';
export const CONSENT_VERSION = 1;
export const STORAGE_KEY = 'personalAIArchive';
export const QUOTA_BYTES = 10 * 1024 * 1024;
export const MAX_MESSAGE_LENGTH = 200000;
export const MAX_BATCH_SIZE = 200;
export const STATUS_CODES = new Set([
  'MEMORY_PROFILE_CONFLICT','MEMORY_NAME_EXISTS','MEMORY_INVALID','MEMORY_EXTERNAL_DISABLED', 'MEMORY_STALE','MEMORY_CONFIRM_REQUIRED','MEMORY_UNAVAILABLE','MEMORY_DENIED','MEMORY_LIMIT','MEMORY_EMPTY',
  'INTEGRITY_SESSION_EXPIRED',
  'BACKUP_BUSY','BACKUP_CHANGED','BACKUP_INVALID','BACKUP_VERSION_UNSUPPORTED','BACKUP_INTEGRITY_FAILED','BACKUP_INCOMPLETE','BACKUP_TOO_LARGE','BACKUP_SESSION_EXPIRED','BACKUP_TARGET_NOT_EMPTY','BACKUP_PURGE_CONFLICT','BACKUP_CONFIRMATION_REQUIRED',
  'CAPTURING', 'WAITING_CHAT', 'TEMPORARY_CHAT', 'NO_MESSAGES',
  'ADAPTER_MISMATCH', 'ADAPTER_VERSION_MISMATCH', 'UNSTABLE_PAGE', 'PAUSED', 'CONSENT_REQUIRED',
  'CAPTURE_FAILED', 'MESSAGE_TOO_LARGE', 'CONTEXT_INVALIDATED',
  'STORAGE_FULL', 'STORAGE_FAILED', 'INVALID_REQUEST', 'FORBIDDEN', 'STALE_CAPTURE',
  'CREDENTIAL_FAILURE', 'RATE_LIMIT', 'TIMEOUT', 'CANCELLED', 'UNAVAILABLE',
  'INVALID_CREDENTIAL', 'RATE_LIMITED', 'PROVIDER_TIMEOUT', 'NETWORK_ERROR', 'INVALID_PROVIDER_OUTPUT',
  'PROVIDER_BAD_REQUEST', 'MODEL_NOT_AVAILABLE', 'PROVIDER_UNAVAILABLE', 'RESPONSE_BODY_READ_FAILED',
  'INVALID_JSON', 'INVALID_SCHEMA', 'SPAN_VALIDATION_FAILED', 'COMMIT_FAILED',
  'REQUEST_ALREADY_IN_FLIGHT', 'OUTCOME_UNKNOWN', 'MESSAGE_CHANNEL_INTERRUPTED', 'MESSAGE_RESPONSE_TIMEOUT',
  'PREPARE_LEDGER_WRITE_FAILED', 'BATCH_STATE_WRITE_FAILED', 'SINGLE_FLIGHT_ACQUIRE_FAILED',
  'TRACE_WRITE_FAILED', 'BOOTSTRAP_STATE_WRITE_FAILED', 'LIBRARY_COMMIT_FAILED', 'BUDGET_RESERVATION_FAILED','HOST_PERMISSION_MISSING','HOST_PERMISSION_NOT_GRANTED','CSP_BLOCKED','WRONG_FETCH_CONTEXT','INTERNAL_RUNTIME_ERROR'
]);
export const ERROR_CODES = new Set([
  'ADAPTER_MISMATCH', 'ADAPTER_VERSION_MISMATCH', 'CAPTURE_FAILED', 'MESSAGE_TOO_LARGE',
  'CONTEXT_INVALIDATED', 'STORAGE_FULL', 'STORAGE_FAILED'
]);

export class ArchiveError extends Error {
  constructor(code) { super(code); this.code = code; }
}

export function safeErrorCode(error) {
  if (error instanceof ArchiveError && STATUS_CODES.has(error.code)) return error.code;
  // Only the classification survives; never log or persist browser exception text.
  if (/quota|QUOTA_BYTES/i.test(String(error?.message || ''))) return 'STORAGE_FULL';
  return 'STORAGE_FAILED';
}
