import {keys,fail,idOK,revisionOK,ENTRY_FIELDS,validateFields,keyedHash,markHuman,FAMILY_BY_TYPE,refreshEntryIndex,entrySnapshot} from './thought-model.js';
import {journal,nextSequence} from './thought-journal.js';
export async function editLibraryBatch(store,r){
 keys(r,['operationId','entries','reason'],['operationId','entries']);if(!Array.isArray(r.entries)||!r.entries.length||r.entries.length>40||new Set(r.entries.map(e=>e.id)).size!==r.entries.length||new TextEncoder().encode(JSON.stringify(r)).length>1024*1024||r.reason!==undefined&&!['edit','undo','redo','restore'].includes(r.reason))fail();
 for(const e of r.entries){keys(e,['id','expectedRevision','expectedFieldRevisions','changes'],['id','expectedRevision','expectedFieldRevisions','changes']);if(!idOK(e.id)||!revisionOK(e.expectedRevision))fail();validateFields(e.changes);keys(e.expectedFieldRevisions,ENTRY_FIELDS);for(const f of Object.keys(e.changes))if(!revisionOK(e.expectedFieldRevisions[f]))fail();}
 const prior=await store.priorOperation(r);if(prior)return prior;
 const initial=await store.run(()=>store.repository.transaction(false,async t=>{const secret=(await t.get('meta','thought-suppression-key')).value,rows=[];for(const e of r.entries){const row=await t.get('thoughts',e.id);if(!row||row.storageSchema!==2)fail();rows.push(row);}return {secret,rows};}));
 const signatures=await Promise.all(r.entries.map((e,i)=>keyedHash(initial.secret,['body',e.changes.type??initial.rows[i].type,e.changes.body??initial.rows[i].thoughtText])));
 return store.operation(r,async t=>{
  const rows=[];for(const [i,e]of r.entries.entries()){const row=await t.get('thoughts',e.id);if(!row||row.lifecycle!=='active'||!await store.sourcePresent(t,row.sourceRecordIds))return {conflict:true,unavailable:true};const fields=Object.keys(e.changes).filter(f=>row.fieldRevisions[f]!==e.expectedFieldRevisions[f]);if(fields.length||row.thoughtText!==initial.rows[i].thoughtText||row.type!==initial.rows[i].type)return {conflict:true,entryId:e.id,fields};rows.push(row);}
  const items=[];for(const [i,e]of r.entries.entries()){const row=rows[i],before=entrySnapshot(row),baseRevision=row.revision,fields=[];for(const [f,v]of Object.entries(e.changes)){const k=f==='body'?'thoughtText':f;if(row[k]===v)continue;row[k]=v;row.fieldRevisions[f]++;markHuman(row,f,r.operationId,store.clock());fields.push(f);}if(fields.length){if(fields.includes('body')||fields.includes('title'))row.contentRevision++;row.family=FAMILY_BY_TYPE[row.type];row.types=['type:'+row.type];row.revision++;row.meaningfulContentAt=fields.includes('body')?store.clock():(row.meaningfulContentAt||row.updatedAt||row.createdAt);row.updatedAt=store.clock();row.updatedSequence=await nextSequence(t);row.exactSignature=signatures[i];delete row.exactKey;refreshEntryIndex(row);await t.put('thoughts',row);await journal(store,t,{kind:'library_entry',entityId:row.id,before,after:entrySnapshot(row),fieldMask:fields,actor:'user',reason:r.reason||'edit',important:!!r.reason&&r.reason!=='edit',operationId:r.operationId,baseRevision,afterRevision:row.revision,sourceRecordIds:row.sourceRecordIds});}items.push({id:row.id,revision:row.revision,fieldRevisions:row.fieldRevisions});}return {items};
 });
}
