import {timestamp} from './topic-reading-order.js';
import {inputProjection} from './thought-evidence.js';
import {prefix} from './thought-model.js';
export async function countBatch(store){
 const task=await store.run(()=>store.repository.transaction(false,t=>t.edge('libraryMigrationItems','byStatus',prefix([0,'count']))));if(!task)return {pending:false};
 const snapshot=await store.run(()=>store.repository.transaction(false,async t=>{const topic=await t.get('topics',task.ownerId),epoch=(await t.get('meta','thought-epoch'))?.value||0;return {topic,epoch,page:await t.rangePage('placements','byTopicOrder',prefix([topic.id,topic.activeLayoutGeneration,0]),task.cursor,200)};}));
 let meaningfulContentAt=task.meaningfulContentAt||0;
 let count=task.count;count+=await store.run(()=>store.repository.transaction(false,async t=>{let n=0;for(const {value:p}of snapshot.page.rows){try{const e=await store.readableEntry(t,p.entryId);if(e.lifecycle!=='active')continue;const meaningful=()=>{if((e.thoughtText||e.body||'').trim())meaningfulContentAt=Math.max(meaningfulContentAt,timestamp(e.meaningfulContentAt||e.updatedAt||e.createdAt));};if(e.hasHumanAction||e.origin!=='ai'){n++;meaningful();continue;}const deps=await t.all('dependencies','byTarget',prefix(['entry',e.id]));for(const d of deps){if(!d.roles?.some(x=>x!=='context_only'))continue;const input=await inputProjection(store,t,d.inputId);if(input&&(input.lastRemovalSequence||0)<=(d.eligibilityEpochAtUse||0)){n++;meaningful();break;}}}catch{}}return n;}));
 return store.libraryMaintenanceWrite(async t=>{const current=await t.get('libraryMigrationItems',task.id),topic=await t.get('topics',task.ownerId),epoch=(await t.get('meta','thought-epoch'))?.value||0;if(!current||current.key!==task.key||JSON.stringify(current.cursor)!==JSON.stringify(task.cursor))return {pending:true};const key=`reading1:${topic.activeLayoutGeneration}:${topic.countVersion||0}:${epoch}`;if(key!==task.key){await t.put('libraryMigrationItems',{...current,key,cursor:null,count:0,meaningfulContentAt:0});return {pending:true};}topic.countCache={key,count,meaningfulContentAt,complete:!snapshot.page.next};await t.put('topics',topic);if(!snapshot.page.next)await t.delete('libraryMigrationItems',task.id);else await t.put('libraryMigrationItems',{...current,cursor:snapshot.page.next,count,meaningfulContentAt});return {pending:true};});
}
