import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {LifetimeNetworkLedger} from './proof-oracles.mjs';import {HUMAN_WITNESS_CASES,HUMAN_WITNESS_INVOCATIONS,HUMAN_WITNESS_PATHS,HUMAN_WITNESS_PROOF_PATHS,assertHumanBranchWitnessReceipt as validate} from './human-branch-witness-receipt.mjs';
// These synthetic objects test rejection logic only; they are not native evidence.
const hashes=async paths=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(await readFile(new URL('../../'+p,import.meta.url))).digest('hex')])));
const expected={head:'a'.repeat(40),tree:'b'.repeat(40),variant:'source',expectedHashes:await hashes(HUMAN_WITNESS_PATHS),expectedProofHashes:await hashes(HUMAN_WITNESS_PROOF_PATHS)};
function fixture(){const ledger=new LifetimeNetworkLedger(),identity={lifetime:'synthetic-one',nativeFactory:true,networkAttempts:[],databases:['paia-archive','bns-human-witness-1']};ledger.observe(identity,'opened');ledger.finish(identity);return {schema:1,head:expected.head,tree:expected.tree,variant:'source',scope:'private-readonly-human-branch-semantic-witness',result:'PASS',productionActivation:false,retentionImplemented:true,writeCapability:false,fullRecovery:false,providerActivation:false,browserVersion:'154.0.8037.99',hashes:structuredClone(expected.expectedHashes),proofHashes:structuredClone(expected.expectedProofHashes),cases:HUMAN_WITNESS_CASES.map((name,index)=>({name,observations:HUMAN_WITNESS_INVOCATIONS[index].map(signature=>{const[kind,result]=signature.split(':');return {caseIndex:index,kind,result,code:result==='resolved'?null:'BNS_HUMAN_BRANCH_UNAVAILABLE',transactions:kind==='capture'?2:1,nonNativeTransactions:0,readwriteTransactions:0,foreignTransactions:0,writes:0,factoryOpens:0,initializations:0,controlWrites:0,storeNative:true,factoryNative:true,databaseNative:true,repositoryMatches:true,journalMatches:true};})})),isolation:{nativeFactory:true,networkAttempts:0,httpRequests:0,databases:identity.databases,networkLedger:ledger.evidence}};}
const rejects=mutations=>{for(const mutate of mutations){const r=fixture();mutate(r);assert.throws(()=>validate(r,expected));}};
test('native witness receipt binds exact current runtime and proof hashes with all original and native-specific cases',()=>{assert.equal(validate(fixture(),expected).result,'PASS');for(const v of [undefined,{},Object.fromEntries(HUMAN_WITNESS_PATHS.map(p=>[p,'c'.repeat(64)]))])assert.throws(()=>validate(fixture(),{...expected,expectedHashes:v}));assert.throws(()=>validate(fixture(),{...expected,expectedProofHashes:{}}));});
test('native witness receipt refuses stale heads, incomplete cases, widened product claims and fabricated success',()=>{rejects([r=>r.retentionImplemented=false,r=>r.head='c'.repeat(40),r=>r.tree='c'.repeat(40),r=>r.result='FAIL',r=>r.result='CANCELLED',r=>r.cases.pop(),r=>r.cases.reverse(),r=>r.cases[0].name='other',r=>r.cases[0].observations=[],r=>r.isolation.networkAttempts=1,r=>r.isolation.httpRequests=1,r=>r.isolation.databases.push('other-user-db'),r=>r.isolation.networkLedger.observations[0].networkAttempts.push('denied')]);for(const k of ['productionActivation','writeCapability','fullRecovery','providerActivation'])rejects([r=>r[k]=true]);});
test('native witness receipt rejects any write, initialization, opening, foreign transaction or non-native successful call',()=>{for(const k of ['nonNativeTransactions','readwriteTransactions','foreignTransactions','writes','factoryOpens','initializations','controlWrites'])rejects([r=>r.cases[0].observations[0][k]=1]);for(const k of ['storeNative','factoryNative','databaseNative','repositoryMatches','journalMatches'])rejects([r=>r.cases[0].observations[0][k]=false]);rejects([r=>r.cases[0].observations[0].transactions=0,r=>r.cases[0].observations[0].code='unexpected',r=>r.cases[0].observations[0].caseIndex=1,r=>r.cases[0].observations[0].kind='fake',r=>r.cases[0].observations[0].result='skipped']);});
test('native witness strict shapes reject missing fields and added body-bearing evidence',()=>{for(const select of [r=>r,r=>r.hashes,r=>r.proofHashes,r=>r.cases[0],r=>r.cases[0].observations[0],r=>r.isolation,r=>r.isolation.networkLedger,r=>r.isolation.networkLedger.observations[0]]){rejects([r=>select(r).body='forbidden']);for(const k of Object.keys(select(fixture())))rejects([r=>delete select(r)[k]]);}});

test('native witness receipt requires every original rejection in exact invocation order',()=>{rejects([r=>{for(const c of r.cases)for(const o of c.observations){o.result='resolved';o.code=null;}},r=>r.cases[0].observations.pop(),r=>r.cases[3].observations.reverse(),r=>r.cases[14].observations[1].result='resolved',r=>r.cases[15].observations[0].kind='revalidate']);});
