import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp,rm,cp} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {instrumentedExtension,root,startNative} from './storage-harness.mjs';import {nativeHumanLibraryFixture} from './human-library-fixture.mjs';import {assertWorkerLifecycle,assertNetworkLedger} from './proof-oracles.mjs';
const files=['core/idb-repository.js','core/ia-store.js','core/thought-store.js','core/thought-model.js','core/thought-journal.js','core/library-documents-store.js','core/thought-organization.js','core/topic-governance.js','core/topic-identity.js','core/topic-intent.js','core/thought-read-index.js','core/library-search.js','core/browser-native-sync/core.js','core/browser-native-sync/codecs.js','core/browser-native-sync/human-library-plan.js','core/browser-native-sync/human-library-allocation.js','core/browser-native-sync/human-library-identity.js','core/browser-native-sync/human-library-codec.js','core/browser-native-sync/human-library-journal.js','core/browser-native-sync/publications.js','core/browser-native-sync/segments.js','core/browser-native-sync/group-checkpoint-plan.js','core/browser-native-sync/group-checkpoint-scope.js','core/browser-native-sync/group-checkpoint.js'];
const head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),tree=execFileSync('git',['rev-parse','HEAD^{tree}'],{cwd:root,encoding:'utf8'}).trim();let sourceProof;
for(const variant of ['source','release'])test('BNS private Human named owners and receiver native '+variant,{timeout:180000},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'paia-human-library-')),output=join(root,'work/qa-bns-human-library'),receipt={schema:1,head,tree,variant,scope:'private-local-human-named-owners-and-single-commit-receiver',result:'IN_PROGRESS',productionActivation:false,fullRecovery:false,groupCheckpointImplemented:false};let extension,browser;await mkdir(output,{recursive:true});
 try{
  if(variant==='release')execFileSync('python3',['scripts/build_current_release.py',join(directory,'release')],{cwd:root,stdio:'pipe'});
  const frozen=join(root,'tests/fixtures/human-library-old-reader'),manifest=JSON.parse(await readFile(join(frozen,'manifest.json'),'utf8'));assert.equal(manifest.commit,'eece4e42bafb4e0be19531bb487f06d7bfd46fe9');assert.equal(Object.keys(manifest.files).length,38);for(const [path,proof]of Object.entries(manifest.files)){const bytes=await readFile(join(frozen,'extension',path));assert.equal(createHash('sha256').update(bytes).digest('hex'),proof.sha256);assert.equal(createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex'),proof.gitBlob);}
  extension=await instrumentedExtension(variant==='source'?root:join(directory,'release'));await cp(frozen,join(extension.path,'background/bns-human-frozen'),{recursive:true});await writeFile(join(extension.path,'background/bns-human-fixture.mjs'),nativeHumanLibraryFixture(await readFile(join(root,'tests/browser-native-sync-human-library-journal.test.mjs'),'utf8')));
  const worker=join(extension.path,'background/service-worker.js'),text=await readFile(worker,'utf8');assert.ok(text.includes("import './bns-native-storage-fixture.mjs';"));await writeFile(worker,text.replace("import './bns-native-storage-fixture.mjs';","import './bns-native-storage-fixture.mjs';\nimport './bns-human-fixture.mjs';"));
  receipt.hashes=Object.fromEntries(await Promise.all(files.map(async file=>[file,createHash('sha256').update(await readFile(join(extension.path,file))).digest('hex')])));
  browser=await startNative(extension.path);receipt.browserVersion=browser.browserVersion;receipt.cases=await browser.call('human-library-matrix');assert.equal(receipt.cases.length,10);assert.equal(new Set(receipt.cases).size,10);
  const before=await browser.call('human-library-durable-create');receipt.restart=await browser.restart();receipt.durable=await browser.call('human-library-durable-ack',before);assert.equal(receipt.durable.duplicate,true);assert.equal(receipt.durable.noEcho,true);
  receipt.isolation=await browser.isolation();assert.equal(receipt.isolation.nativeFactory,true);assert.equal(receipt.isolation.networkAttempts,0);assert.equal(receipt.isolation.httpRequests,0);assertWorkerLifecycle(receipt.restart);assertNetworkLedger(receipt.isolation.networkLedger,[receipt.restart]);const paused=receipt.isolation.networkLedger.observations.filter(row=>row.point==='paused-before-stop'&&row.lifetime===receipt.restart.beforeLifetime);assert.equal(paused.length,1);assert.deepEqual(receipt.restart.pausedNetwork,paused[0]);
  const proof={cases:receipt.cases,hashes:receipt.hashes};if(variant==='source')sourceProof=proof;else assert.deepEqual(proof,sourceProof);receipt.result='PASS';
 }catch(error){receipt.result='FAIL';receipt.error=error.message;throw error;}
 finally{await writeFile(join(output,variant+'.json'),JSON.stringify(receipt,null,2));await browser?.close();await extension?.cleanup();await rm(directory,{recursive:true,force:true});}
});
