import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp,rm,cp} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {instrumentedExtension,root,startNative} from './storage-harness.mjs';import {nativeHumanLibraryFixture} from './human-library-fixture.mjs';import {assertWorkerLifecycle,assertNetworkLedger} from './proof-oracles.mjs';
import {HUMAN_LIBRARY_PATHS,assertHumanLibraryReceipt} from './human-library-receipt.mjs';
const files=HUMAN_LIBRARY_PATHS;
const head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),tree=execFileSync('git',['rev-parse','HEAD^{tree}'],{cwd:root,encoding:'utf8'}).trim();let sourceProof;
for(const variant of ['source','release'])test('BNS private Human named owners and receiver native '+variant,{timeout:180000},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'paia-human-library-')),output=join(root,'work/qa-bns-human-library'),receipt={schema:1,head,tree,variant,scope:'private-local-human-named-owners-and-bounded-partial-grouped-recovery',result:'IN_PROGRESS',productionActivation:false,fullRecovery:false,groupCheckpointImplemented:true,derivedProjectionRecovery:false};let extension,browser;await mkdir(output,{recursive:true});
 try{
  if(variant==='release')execFileSync('python3',['scripts/build_current_release.py',join(directory,'release')],{cwd:root,stdio:'pipe'});
  const frozen=join(root,'tests/fixtures/human-library-old-reader'),manifest=JSON.parse(await readFile(join(frozen,'manifest.json'),'utf8'));assert.equal(manifest.commit,'eece4e42bafb4e0be19531bb487f06d7bfd46fe9');assert.equal(Object.keys(manifest.files).length,38);for(const [path,proof]of Object.entries(manifest.files)){const bytes=await readFile(join(frozen,'extension',path));assert.equal(createHash('sha256').update(bytes).digest('hex'),proof.sha256);assert.equal(createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex'),proof.gitBlob);}
  extension=await instrumentedExtension(variant==='source'?root:join(directory,'release'));await cp(frozen,join(extension.path,'background/bns-human-frozen'),{recursive:true});for(const [name,destination,count]of [['human-library-pre-role-reader','bns-human-pre-role-frozen',41],['human-index-old-owner','bns-human-index-frozen',3]]){const dir=join(root,'tests/fixtures',name),proof=JSON.parse(await readFile(join(dir,'manifest.json'),'utf8'));assert.equal(Object.keys(proof.files).length,count);for(const [path,hash]of Object.entries(proof.files)){const bytes=await readFile(join(dir,name==='human-index-old-owner'?'':'extension',path));assert.equal(createHash('sha256').update(bytes).digest('hex'),hash.sha256);assert.equal(createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex'),hash.gitBlob);}await cp(dir,join(extension.path,'background',destination),{recursive:true});}await writeFile(join(extension.path,'background/bns-human-fixture.mjs'),nativeHumanLibraryFixture(await readFile(join(root,'tests/browser-native-sync-human-library-journal.test.mjs'),'utf8'),await readFile(join(root,'tests/human-graph-allocation-portability.test.mjs'),'utf8'),await readFile(join(root,'tests/browser-native-sync-human-library-group.test.mjs'),'utf8'),await readFile(join(root,'tests/human-graph-request-order.test.mjs'),'utf8'),await readFile(join(root,'tests/browser-native-sync-human-library-indexed-journal.test.mjs'),'utf8'),await readFile(join(root,'tests/browser-native-sync-human-library-derived-refusal.test.mjs'),'utf8')));
  const worker=join(extension.path,'background/service-worker.js'),text=await readFile(worker,'utf8');assert.ok(text.includes("import './bns-native-storage-fixture.mjs';"));await writeFile(worker,text.replace("import './bns-native-storage-fixture.mjs';","import './bns-native-storage-fixture.mjs';\nimport './bns-human-fixture.mjs';"));
  receipt.hashes=Object.fromEntries(await Promise.all(files.map(async file=>[file,createHash('sha256').update(await readFile(join(extension.path,file))).digest('hex')])));
  browser=await startNative(extension.path);receipt.browserVersion=browser.browserVersion;receipt.cases=await browser.call('human-library-matrix');assert.equal(receipt.cases.length,24);assert.equal(new Set(receipt.cases).size,24);
  const before=await browser.call('human-library-durable-create');receipt.restart=await browser.restart();receipt.durable=await browser.call('human-library-durable-ack',before);assert.equal(receipt.durable.duplicate,true);assert.equal(receipt.durable.noEcho,true);
  const grouped=await browser.call('human-library-group-durable-create');receipt.groupRestart=await browser.restart();receipt.groupDurable=await browser.call('human-library-group-durable-ack',grouped);assert.equal(receipt.groupDurable.duplicate,true);assert.equal(receipt.groupDurable.noEcho,true);assert.equal(receipt.groupDurable.allStoresPreserved,true);const groupedEntries=grouped.canonical.thoughts.filter(row=>row.id===grouped.entryId);assert.equal(groupedEntries.length,1);assert.equal(groupedEntries[0].revision,3);receipt.groupDurable.entryRevision=groupedEntries[0].revision;assertWorkerLifecycle(receipt.groupRestart);
  receipt.isolation=await browser.isolation();assert.equal(receipt.isolation.nativeFactory,true);assert.equal(receipt.isolation.networkAttempts,0);assert.equal(receipt.isolation.httpRequests,0);assertWorkerLifecycle(receipt.restart);assertNetworkLedger(receipt.isolation.networkLedger,[receipt.restart,receipt.groupRestart]);const paused=receipt.isolation.networkLedger.observations.filter(row=>row.point==='paused-before-stop'&&row.lifetime===receipt.restart.beforeLifetime);assert.equal(paused.length,1);assert.deepEqual(receipt.restart.pausedNetwork,paused[0]);
  const proof={cases:receipt.cases,hashes:receipt.hashes};if(variant==='source')sourceProof=proof;else assert.deepEqual(proof,sourceProof);receipt.result='PASS';const expectedHashes=Object.fromEntries(await Promise.all(files.map(async file=>[file,createHash('sha256').update(await readFile(join(root,file))).digest('hex')])));assertHumanLibraryReceipt(receipt,{head,tree,variant,expectedHashes});
 }catch(error){receipt.result='FAIL';receipt.error=error.message;throw error;}
 finally{await writeFile(join(output,variant+'.json'),JSON.stringify(receipt,null,2));await browser?.close();await extension?.cleanup();await rm(directory,{recursive:true,force:true});}
});
