import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {LifetimeNetworkLedger} from './proof-oracles.mjs';
import {assertInputWorkingReceiveReceipt as validate,INPUT_WORKING_RECEIVE_CASES as cases,INPUT_WORKING_RECEIVE_PATHS as paths,INPUT_WORKING_INBOX_CASES as inboxCases,INPUT_WORKING_INBOX_PATHS as inboxPaths} from './input-working-receive-receipt.mjs';
const expected={head:'a'.repeat(40),tree:'b'.repeat(40),variant:'source'};
function fixture(){
 const before={lifetime:'synthetic-before',nativeFactory:true,networkAttempts:[]},after={...before,lifetime:'synthetic-after'},ledger=new LifetimeNetworkLedger();ledger.observe(before,'opened');ledger.observe(before,'before-stop');const pausedNetwork=ledger.observe(before,'paused-before-stop');ledger.restarted(before,after);ledger.finish(after);
 const restart={beforeLifetime:before.lifetime,afterLifetime:after.lifetime,phase:{name:'restart-boundary',lifetime:before.lifetime,hasNativeTransaction:false},stopped:true,restarted:true,interruptedCall:'returned',completedNoopValue:true,pausedNetwork};
 const isolation={nativeFactory:true,networkAttempts:0,httpRequests:0,networkLedger:structuredClone(ledger.evidence)};
 const third={...before,lifetime:'synthetic-third'};ledger.observe(after,'before-stop');const inboxPaused=ledger.observe(after,'paused-before-stop');ledger.restarted(after,third);ledger.finish(third);
 const inboxRestart={...restart,beforeLifetime:after.lifetime,afterLifetime:third.lifetime,phase:{...restart.phase,lifetime:after.lifetime},pausedNetwork:inboxPaused};
 return {inboxCases:[...inboxCases],inboxHashes:Object.fromEntries(inboxPaths.map(p=>[p,'c'.repeat(64)])),inboxRestart,inboxIsolation:{...isolation,networkLedger:ledger.evidence},schema:1,...expected,result:'PASS',scope:'optional-local-Input-Working-receive',productionActivation:false,remoteMaterializer:true,fullRecovery:false,cases:[...cases],hashes:Object.fromEntries(paths.map(p=>[p,'c'.repeat(64)])),browserVersion:'154.0 synthetic fixture',restart,isolation};
}
function rejected(mutations){for(const change of mutations){const r=fixture();change(r);assert.throws(()=>validate(r,expected));}}
test('receive receipt accepts both explicit variants with complete strict evidence',()=>{for(const variant of ['source','release']){const r={...fixture(),variant};assert.equal(validate(r,{...expected,variant}),r);}});
test('receive receipt refuses invalid or stale expected identity and mismatched receipt identity',()=>{for(const change of [{head:undefined},{tree:''},{head:'not-a-sha'},{variant:'other'}])assert.throws(()=>validate(fixture(),{...expected,...change}));rejected([r=>r.head='d'.repeat(40),r=>r.tree='d'.repeat(40),r=>r.variant='release',r=>r.schema=2,r=>r.result='IN_PROGRESS']);});
test('receive receipt refuses publication scope and false activation or recovery claims',()=>{rejected([r=>r.scope='optional-local-Input-Working-publication',r=>r.productionActivation=true,r=>delete r.productionActivation,r=>r.remoteMaterializer=false,r=>r.fullRecovery=true,r=>r.fullRecovery=undefined]);});
test('receive receipt requires exact case names and order and all seven runtime paths',()=>{rejected([r=>r.cases.pop(),r=>r.cases[0]='substitute',r=>r.cases[1]=r.cases[0],r=>r.cases.reverse(),r=>delete r.hashes[paths[0]],r=>r.hashes.extra='c'.repeat(64),r=>r.hashes[paths[0]]='bad',r=>r.browserVersion='']);});
test('receive receipt rejects false worker restart and an open native transaction',()=>{rejected([r=>r.restart.stopped=false,r=>r.restart.restarted=false,r=>r.restart.afterLifetime=r.restart.beforeLifetime,r=>r.restart.phase.lifetime='other',r=>r.restart.phase.name='other',r=>r.restart.phase.hasNativeTransaction=true,r=>r.restart.completedNoopValue=false,r=>r.restart.interruptedCall='unknown']);});
test('receive receipt rejects erased paused evidence and network activity in any lifetime',()=>{rejected([r=>r.isolation.nativeFactory=false,r=>r.isolation.networkAttempts=1,r=>r.isolation.httpRequests=1,r=>r.isolation.networkLedger.complete=false,r=>r.isolation.networkLedger.observations[1].networkAttempts.push('https://synthetic.invalid/denied'),r=>r.isolation.networkLedger.observations.splice(2,1),r=>r.isolation.networkLedger.transitions=[],r=>r.restart.pausedNetwork={},r=>r.isolation.networkLedger.observations.splice(2,0,structuredClone(r.restart.pausedNetwork))]);});
test('both receipt variants must retain identical production evidence in the CI pair comparison',()=>{const a=fixture(),b={...fixture(),variant:'release'};validate(a,expected);validate(b,{...expected,variant:'release'});assert.deepEqual(a.cases,b.cases);assert.deepEqual(a.hashes,b.hashes);b.hashes[paths[0]]='d'.repeat(64);b.inboxHashes[paths[0]]=b.hashes[paths[0]];validate(b,{...expected,variant:'release'});assert.throws(()=>assert.deepEqual(a.hashes,b.hashes));});
test('native whole file uses the same strict validator without changing original budget or cases',async()=>{const source=await readFile(new URL('./input-working-receive-chrome.test.mjs',import.meta.url),'utf8');assert.ok(source.includes("from './input-working-receive-receipt.mjs'"));assert.ok(source.includes('assertInputWorkingReceiveReceipt(receipt,{head,tree,variant})'));assert.ok(source.includes('timeout:240000'));assert.ok(source.includes("for(const variant of ['source','release'])"));assert.ok(source.includes('assert.deepEqual(await browser.call(\'working-receive-durable-read\'),before)'));});

test('inbox receipt refuses absent, reordered or substituted cases and missing or divergent runtime hashes',()=>{rejected([r=>delete r.inboxCases,r=>r.inboxCases.pop(),r=>r.inboxCases.reverse(),r=>r.inboxCases[0]='substitute',r=>r.inboxCases[1]=r.inboxCases[0],r=>delete r.inboxHashes,r=>delete r.inboxHashes[inboxPaths.at(-1)],r=>r.inboxHashes.extra='c'.repeat(64),r=>r.inboxHashes[inboxPaths.at(-1)]='bad',r=>r.inboxHashes[paths[0]]='d'.repeat(64)]);});
test('inbox receipt requires the second actual consecutive restart with closed transaction',()=>{rejected([r=>delete r.inboxRestart,r=>r.inboxRestart=structuredClone(r.restart),r=>r.inboxRestart.stopped=false,r=>r.inboxRestart.restarted=false,r=>r.inboxRestart.beforeLifetime='unrelated',r=>r.inboxRestart.afterLifetime=r.inboxRestart.beforeLifetime,r=>r.inboxRestart.phase.name='other',r=>r.inboxRestart.phase.hasNativeTransaction=true,r=>r.inboxRestart.completedNoopValue=false]);});
test('inbox receipt rejects omitted earlier lifetimes, paused evidence and late network attempts',()=>{rejected([r=>delete r.inboxIsolation,r=>r.inboxIsolation.nativeFactory=false,r=>r.inboxIsolation.networkAttempts=1,r=>r.inboxIsolation.httpRequests=1,r=>r.inboxIsolation.networkLedger.complete=false,r=>r.inboxIsolation.networkLedger=structuredClone(r.isolation.networkLedger),r=>r.inboxIsolation.networkLedger.observations.at(-1).networkAttempts.push('denied'),r=>r.inboxRestart.pausedNetwork={},r=>r.inboxIsolation.networkLedger.observations.splice(2,1)]);});

test('native receive publishes PASS only after inbox restart and final exact scope validation',async()=>{
 const source=await readFile(new URL('./input-working-receive-chrome.test.mjs',import.meta.url),'utf8');
 assert.equal(source.split("receipt.result='PASS'").length,2);
 assert.ok(source.indexOf("receipt.result='PASS'")>source.indexOf('receipt.inboxRestart=await browser.restart()'));
 assert.ok(source.indexOf('assertInputWorkingReceiveReceipt(receipt,{head,tree,variant})')>source.indexOf('receipt.inboxHashes='));
});
