import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,realpath,readdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {root,instrumentedExtension,startNative} from './storage-harness.mjs';
import {assertNetworkLedger} from './proof-oracles.mjs';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const proof=['tests/native-sync/source-working-native-cleanup-fault-native-fixture.mjs','tests/native-sync/source-working-native-cleanup-fault-native.test.mjs','tests/native-sync/source-working-native-cleanup-fault-prelude.mjs','tests/native-sync/storage-harness.mjs','tests/native-sync/storage-worker-fixture.mjs','tests/native-sync/immutable-objects.mjs','tests/native-sync/proof-oracles.mjs','tests/harness/fake-chatgpt.mjs','manifest.json','package.json'];
async function snapshot(){const paths=[...proof];async function walk(name){for(const entry of await readdir(join(root,name),{withFileTypes:true})){const path=name+'/'+entry.name;if(entry.isDirectory())await walk(path);else paths.push(path);}}await walk('core');await walk('background');const git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim(),hashes={};for(const path of paths.sort()){const source=await readFile(join(root,path)),tracked=execFileSync('git',['show','HEAD:extension/'+path],{cwd:root});assert.deepEqual(source,tracked,'actual tracked proof '+path);hashes[path]=hash(source);}return {head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),dirty:git('status','--porcelain','--untracked-files=all'),hashes};}
let common;
for(const variant of ['source','release'])test('actual MV3 original Source Working native cleanup fault '+variant,{timeout:180000},async()=>{
 const before=await snapshot();assert.equal(before.dirty,'');let extension,browser;const receipt={schema:1,variant,...before,result:'IN_PROGRESS',claim:'SYNTHETIC_SOURCE_NATIVE_LISTENER_CLEANUP_FAULT_ONLY'};
 try{
  extension=await instrumentedExtension(variant==='source'?root:await realpath(join(root,'work/current-release')));receipt.runtimeHashes={};for(const [path,digest]of Object.entries(before.hashes))if(path.startsWith('core/')||path.startsWith('background/')&&path!=='background/service-worker.js'){const loaded=hash(await readFile(join(extension.path,path)));assert.equal(loaded,digest,path);receipt.runtimeHashes[path]=loaded;}
  const source=await readFile(join(root,'tests/native-sync/source-working-native-cleanup-fault-native-fixture.mjs'),'utf8');assert.equal(/\bimport\s*\(/.test(source),false,'fixed static fixture imports only');
  const generated=source.replaceAll('../../core/','../core/')+"\nconst originalRun=globalThis.__bnsNative.run;globalThis.__bnsNative.run=(command,args)=>command==='source-working-native-cleanup-fault'?runSourceWorkingNativeCleanupFault():originalRun(command,args);\n";await writeFile(join(extension.path,'background/bns-source-working-native-cleanup-fault.mjs'),generated);receipt.generatedSha256=hash(generated);
  const faultPrelude=await readFile(join(root,'tests/native-sync/source-working-native-cleanup-fault-prelude.mjs'),'utf8');await writeFile(join(extension.path,'background/bns-source-working-cleanup-prelude.mjs'),faultPrelude);receipt.faultPreludeSha256=hash(faultPrelude);const faultImport="import './bns-source-working-cleanup-prelude.mjs';\n";
  const worker=join(extension.path,'background/service-worker.js'),original=await readFile(worker,'utf8'),prelude="import './bns-native-storage-fixture.mjs';\n",loaded=faultImport+original.replace(prelude,prelude+"import './bns-source-working-native-cleanup-fault.mjs';\n");assert.ok(original.startsWith(prelude));await writeFile(worker,loaded);
  const sourceWorker=await readFile(join(root,'background/service-worker.js'),'utf8'),omission="    case 'FILTER_DIAGNOSTICS': return store.filterDiagnostics();\n";assert.equal(sourceWorker.split(omission).length,2);const expected=variant==='source'?sourceWorker:sourceWorker.replace(omission,'');assert.equal(original,prelude+expected);assert.equal(loaded,faultImport+prelude+"import './bns-source-working-native-cleanup-fault.mjs';\n"+expected);receipt.originalWorkerSha256=hash(expected);receipt.instrumentedWorkerSha256=hash(loaded);
  browser=await startNative(extension.path,{closeArchivePage:true});receipt.browserVersion=browser.browserVersion;receipt.archivePageClosed=true;receipt.cases=await browser.call('source-working-native-cleanup-fault');assert.equal(receipt.cases.status,'SYNTHETIC_SOURCE_NATIVE_CLEANUP_QUARANTINE_HELD_NOT_REFUNDED');assert.equal(receipt.cases.cases.length,1);assert.equal(receipt.cases.cases.every(row=>row.result==='PASS'&&row.assertions>0),true);assert.equal(receipt.cases.workQuarantineHeld,true);assert.equal(receipt.cases.retainedBorrowedFrameHeld,true);assert.equal(receipt.cases.automaticCleanupSucceeded,false);assert.ok(receipt.cases.listenerCleanupFaultCalls>=2);
  receipt.isolation=await browser.isolation();assert.equal(receipt.isolation.nativeFactory,true);assert.equal(receipt.isolation.networkAttempts,0);assert.equal(receipt.isolation.httpRequests,0);assertNetworkLedger(receipt.isolation.networkLedger,[]);assert.equal(receipt.cases.genuineNative,true);assert.equal(receipt.cases.allStores,37);assert.equal(receipt.cases.workerRestart,false);assert.equal(receipt.cases.provider,false);assert.deepEqual(await snapshot(),before);
  const paired={sourceHashes:before.hashes,runtimeHashes:receipt.runtimeHashes,generatedSha256:receipt.generatedSha256,faultPreludeSha256:receipt.faultPreludeSha256,cases:receipt.cases};if(variant==='source')common=paired;else assert.deepEqual(paired,common);receipt.result='PASS';
 }catch(error){receipt.result='FAIL';receipt.failure={name:error.name,message:error.message,stack:error.stack};throw error;}
 finally{const out=join(root,'work/qa-source-working-native-cleanup-fault');await mkdir(out,{recursive:true});await writeFile(join(out,variant+'.json'),JSON.stringify(receipt,null,2)+'\n');await browser?.close();await extension?.cleanup();}
});
