import {allowed,checkStop,fail,limits} from './errors.js';
import {JsonTokens} from './json-tokens.js';
const utf8=b=>{try{return new TextDecoder('utf-8',{fatal:true}).decode(b);}catch{fail('UTF8_INVALID');}};
const n16=(b,i)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint16(i,true);
const n32=(b,i)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(i,true);
async function bytes(file,start,count,o){checkStop(o);if(start<0||count<0||start+count>file.size||count>65557)fail('ZIP_INVALID');return new Uint8Array(await file.slice(start,start+count).arrayBuffer());}
const crcNext=(crc,b)=>{for(const v of b){crc^=v;for(let k=0;k<8;k++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return crc;};
export async function fingerprintFile(file,o={}){allowed(file,o);let chain=new Uint8Array(32);const prefix=new TextEncoder().encode('paia-file-chain-v1');for(let at=0;at<file.size;at+=65536){const b=await bytes(file,at,Math.min(65536,file.size-at),o),input=new Uint8Array(prefix.length+chain.length+b.length);input.set(prefix);input.set(chain,prefix.length);input.set(b,prefix.length+chain.length);chain=new Uint8Array(await crypto.subtle.digest('SHA-256',input));o.onProgress?.({phase:'fingerprint',bytes:Math.min(at+65536,file.size)});}const end=new Uint8Array(40);end.set(chain);new DataView(end.buffer).setBigUint64(32,BigInt(file.size));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',end))].map(v=>v.toString(16).padStart(2,'0')).join('');}
async function directory(file,o,l){const tail=await bytes(file,Math.max(0,file.size-65557),Math.min(file.size,65557),o);let end=-1;for(let i=tail.length-22;i>=0;i--)if(n32(tail,i)===0x06054b50&&i+22+n16(tail,i+20)===tail.length){end=i;break;}if(end<0)fail('ZIP_INVALID');if(n16(tail,end+4)||n16(tail,end+6)||n16(tail,end+8)!==n16(tail,end+10))fail('ZIP_MULTIDISK');const count=n16(tail,end+10),size=n32(tail,end+12),offset=n32(tail,end+16);if(count===65535||size===0xffffffff||offset===0xffffffff)fail('ZIP64_UNSUPPORTED');if(count>l.entries||size>l.directoryBytes)fail('RESOURCE_LIMIT');if(offset+size!==file.size-tail.length+end)fail('ZIP_INVALID');let at=offset;const selected=[],all=[],names=new Set(),ranges=[];let declaredTotal=0;
 for(let i=0;i<count;i++){const h=await bytes(file,at,46,o);if(n32(h,0)!==0x02014b50)fail('ZIP_INVALID');const nl=n16(h,28),extra=n16(h,30),comment=n16(h,32);if(nl>256||at+46+nl+extra+comment>offset+size)fail('ZIP_INVALID');const name=utf8(await bytes(file,at+46,nl,o));if(!name||name.includes('\\')||name.startsWith('/')||name.includes('\0')||name.split('/').some(p=>p==='..'||p==='.')||/^[A-Za-z]:/.test(name))fail('ZIP_PATH');if(names.has(name))fail('ZIP_DUPLICATE_ENTRY');names.add(name);const entry={flags:n16(h,8),method:n16(h,10),crc:n32(h,16),compressed:n32(h,20),size:n32(h,24),offset:n32(h,42),name};if(n16(h,34))fail('ZIP_MULTIDISK');if([entry.compressed,entry.size,entry.offset].includes(0xffffffff))fail('ZIP64_UNSUPPORTED');if(entry.offset>=offset)fail('ZIP_INVALID');
 // All entries receive metadata/header guards; only JSON candidates are decoded.
 all.push(entry);declaredTotal+=entry.size;if(declaredTotal>l.totalBytes)fail('RESOURCE_LIMIT');if(/\.zip$/i.test(name))fail('ZIP_NESTED');
 // Names narrow the scan only. The adapter independently validates structure.
 if(/(?:^|\/)conversations(?:[-_]?\d+)?\.json$/i.test(name)||o.candidateMode==='structural'&&/\.json$/i.test(name)&&!/(?:^|\/)(?:user|account|settings|message_feedback|model_comparisons)\.json$/i.test(name)){if(selected.length>=l.candidates)fail('RESOURCE_LIMIT');selected.push(entry);}at+=46+nl+extra+comment;}
 if(at!==offset+size)fail('ZIP_INVALID');if(!selected.length)fail('ZIP_NO_CONVERSATIONS');
 for(const e of all){if(e.flags&1)fail('ZIP_ENCRYPTED');if(e.flags&~(8|2048|2|4))fail('ZIP_INVALID');if(![0,8].includes(e.method))fail('ZIP_COMPRESSION');if(e.size>l.entryBytes)fail('RESOURCE_LIMIT');if(e.size>Math.max(1,e.compressed)*l.ratio)fail('ZIP_RATIO');const h=await bytes(file,e.offset,30,o);if(n32(h,0)!==0x04034b50||n16(h,6)!==e.flags||n16(h,8)!==e.method||n16(h,26)>256)fail('ZIP_INVALID');if(utf8(await bytes(file,e.offset+30,n16(h,26),o))!==e.name)fail('ZIP_INVALID');if((e.flags&8)&&[[14,e.crc],[18,e.compressed],[22,e.size]].some(([at,value])=>n32(h,at)!==0&&n32(h,at)!==value))fail('ZIP_INTEGRITY');if(!(e.flags&8)&&(n32(h,14)!==e.crc||n32(h,18)!==e.compressed||n32(h,22)!==e.size))fail('ZIP_INTEGRITY');e.start=e.offset+30+n16(h,26)+n16(h,28);if(e.start+e.compressed>offset)fail('ZIP_INVALID');let finish=e.start+e.compressed;if(e.flags&8){const d=await bytes(file,finish,Math.min(16,offset-finish),o);if(d.length<12)fail('ZIP_INTEGRITY');const s=n32(d,0)===0x08074b50?4:0;if(d.length<s+12||n32(d,s)!==e.crc||n32(d,s+4)!==e.compressed||n32(d,s+8)!==e.size)fail('ZIP_INTEGRITY');finish+=s+12;}ranges.push([e.offset,finish]);delete e.name;}
 ranges.sort((a,b)=>a[0]-b[0]);for(let i=1;i<ranges.length;i++)if(ranges[i][0]<ranges[i-1][1])fail('ZIP_INVALID');return selected;}
async function* stream(file,e,o,l){if(e.method===0){for(let at=e.start;at<e.start+e.compressed;at+=l.chunkBytes)yield await bytes(file,at,Math.min(l.chunkBytes,e.start+e.compressed-at),o);return;}let reader;try{reader=file.slice(e.start,e.start+e.compressed).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader();}catch{fail('ZIP_COMPRESSION');}try{while(true){checkStop(o);let item;try{item=await reader.read();}catch{fail('ZIP_INTEGRITY');}if(item.done)break;for(let i=0;i<item.value.length;i+=l.chunkBytes){checkStop(o);yield item.value.subarray(i,i+l.chunkBytes);}}}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}
export async function inspectFile(file,o={}){allowed(file,o);const l=limits(o.limits),head=await bytes(file,0,Math.min(4,file.size),o),isZip=head.length===4&&n32(head,0)===0x04034b50;if(head[0]===80&&head[1]===75&&!isZip)fail('ZIP_INVALID');const entries=isZip?await directory(file,o,l):[{start:0,compressed:file.size,size:file.size,method:0}];let total=0,maxBufferedChars=0;for(let index=0;index<entries.length;index++){const e=entries[index],p=new JsonTokens(o),decoder=new TextDecoder('utf-8',{fatal:true});let size=0,crc=0xffffffff;await o.onEntry?.(index);
 for await(const chunk of stream(file,e,o,l)){checkStop(o);size+=chunk.length;total+=chunk.length;if(size>l.entryBytes||total>l.totalBytes)fail('RESOURCE_LIMIT');if(size>e.size)fail('ZIP_INTEGRITY');if(isZip&&size>Math.max(1,e.compressed)*l.ratio)fail('ZIP_RATIO');crc=crcNext(crc,chunk);let text;try{text=decoder.decode(chunk,{stream:true});}catch{fail('UTF8_INVALID');}for(const event of p.feed(text)){checkStop(o);await o.onEvent?.(event,index);}o.onProgress?.({phase:'reading',bytes:total,entries:index});}
 let rest;try{rest=decoder.decode();}catch{fail('UTF8_INVALID');}for(const event of p.feed(rest)){checkStop(o);await o.onEvent?.(event,index);}for(const event of p.finish()){checkStop(o);await o.onEvent?.(event,index);}if(isZip&&(size!==e.size||((crc^0xffffffff)>>>0)!==e.crc))fail('ZIP_INTEGRITY');maxBufferedChars=Math.max(maxBufferedChars,p.maxBufferedChars);await o.onEntryEnd?.(index);}
 return {container:isZip?'zip':'json',candidateEntries:entries.length,bytes:total,integrityVerified:true,schemaVerified:false,maxBufferedChars};}
