import {request,element} from './common.js';
const $=id=>document.getElementById(id);
const labels={dangling_memory_authorization:'AI Context 授权引用',missing_memory_topic:'AI Context 主题引用',excluded_missing_entry:'AI Context 单条排除引用',invalid_memory_profile_ref:'AI Context Profile 配置',orphan_entries:'思想内容引用',orphan_topics:'主题归属',broken_provenance:'来源引用',missing_revision_refs:'版本引用',duplicate_stable_identity:'来源身份索引',invalid_organizer_checkpoint:'整理进度',dangling_redirects:'合并后的跳转'};
export class IntegrityPanel {
 constructor(){this.epoch=0;this.sessionId=null;$('integrity-check').addEventListener('click',()=>void this.run());$('integrity-cancel').addEventListener('click',()=>void this.cancel());}
 state(state,text){$('integrity-status').dataset.state=state;$('integrity-status').textContent=text;$('integrity-check').disabled=state==='loading';$('integrity-cancel').hidden=state!=='loading';}
 async cancel(){this.epoch++;const sessionId=this.sessionId;this.sessionId=null;this.state('paused','检查已停止，没有修改数据。');if(sessionId)await request('PAIA_INTEGRITY_CANCEL',{options:{sessionId}}).catch(()=>{});}
 async run(){const epoch=++this.epoch;this.state('loading','正在分段检查本机数据关系…');$('integrity-results').replaceChildren();let sessionId;try{let result=await request('PAIA_INTEGRITY_BEGIN');sessionId=result.sessionId;this.sessionId=sessionId;while(result.state==='loading'){if(epoch!==this.epoch)return;result=await request('PAIA_INTEGRITY_PAGE',{options:{sessionId}});if(epoch!==this.epoch)return;this.state('loading',`正在检查 · ${result.checked} / ${result.total} 项`);await new Promise(r=>setTimeout(r,0));}if(result.state==='stale'){this.state('stale','检查期间内容发生变化，结果已作废。请待编辑或整理结束后重新检查；未修改数据。');return;}const total=Object.values(result.counts).reduce((a,b)=>a+b,0);this.state('ready',total?`检查完成 · ${total} 处关系需要核对。原有数据未修改。`:'检查完成，未发现异常的数据关系。原有数据未修改。');for(const [key,count]of Object.entries(result.counts))$('integrity-results').append(element('p','muted',`${labels[key]}：${count} 处`));}catch{if(epoch===this.epoch)this.state('failed','检查中断，未修改数据。请重新点击检查；若持续中断，可先创建备份。');}finally{if(sessionId)await request('PAIA_INTEGRITY_CANCEL',{options:{sessionId}}).catch(()=>{});if(epoch===this.epoch)this.sessionId=null;}}
}
