import {productAction,beginLoading} from './product-state.js';
import {request,element} from './common.js';
const $=id=>document.getElementById(id);
const button=(label,run)=>{const b=element('button','',label);b.type='button';b.addEventListener('click',productAction(run));return b;};
export class LibraryUpdates {
 constructor(refresh,onEntry){this.refresh=refresh;this.onEntry=onEntry;$('library-updates').addEventListener('click',productAction(()=>this.open()));$('library-updates-close').addEventListener('click',()=>{$('library-updates-drawer').hidden=true;$('library-updates').focus();});$('library-updates-more').addEventListener('click',productAction(()=>this.open(this.cursor)));$('library-organizer-jobs').addEventListener('click',()=>void this.jobs());}
 async count(){try{const p=await request('LIBRARY_UPDATES',{options:{limit:1}});$('library-updates').textContent='待确认建议 '+p.count;$('library-updates').parentElement.hidden=p.count===0;}catch{}}
 async open(cursor=null){const p=await request('LIBRARY_UPDATES',{options:{cursor}}),root=$('library-updates-items');if(!cursor){root.replaceChildren();$('library-updates-result').replaceChildren();}$('library-updates-drawer').hidden=false;for(const item of p.items){const row=element('article','library-update'),body=element('p','',item.body),status=element('p','muted',item.reason==='PROTECTED_REFRESH'?'来源有更新，你编辑过的内容保持原样。':'请确认这条整理建议。');row.append(body,status);for(const [action,label]of [['accept','接受'],['reject','不采用']])row.append(button(label,async()=>{for(const b of row.querySelectorAll('button'))b.disabled=true;try{const r=await request('RESOLVE_LIBRARY_UPDATE',{edit:{id:item.id,baseRevision:item.baseRevision,action,operationId:crypto.randomUUID()}});if(r.expired){status.textContent='来源或内容已更新，这条建议已过期。';}else{row.remove();const feedback=$('library-updates-result');feedback.replaceChildren(element('span','',action==='accept'?'已接受建议，内容已更新。':'已不采用，现有内容保留。'));if(action==='accept'&&r.entryId&&this.onEntry)feedback.append(button('查看对应内容',async()=>{$('library-updates-drawer').hidden=true;await this.onEntry(r.entryId);}));}await this.count();await this.refresh();}catch{status.textContent='尚未完成，请重读后重试。';for(const b of row.querySelectorAll('button'))b.disabled=false;}}));root.append(row);}if(!p.items.length&&!cursor)root.append(element('p','muted','暂无待确认更新'));this.cursor=p.nextCursor;$('library-updates-more').hidden=!p.nextCursor;}
 async jobs(){const p=await request('LIBRARY_ORGANIZER_JOBS'),root=$('library-management-list');root.replaceChildren(element('p','muted','当前未连接整理服务。Input Archive 和已有内容可以继续使用。'));const states={queued:'等待中',running:'整理中',retry:'等待重试',paused:'已暂停',failed:'未完成',completed:'已完成',cancelled:'已取消'};for(const j of p.items){const row=element('p','',states[j.state]||'未完成');if(!['completed','cancelled'].includes(j.state))row.append(button('取消',async()=>{await request('CONTROL_LIBRARY_ORGANIZER_JOB',{edit:{id:j.id,action:'cancel'}});await this.jobs();}));root.append(row);}}
}
