import {request,element} from './common.js';
const c=(zh,en)=>document.documentElement.lang.startsWith('en')?en:zh;
const button=(zh,en,fn)=>{const b=element('button','',c(zh,en));b.type='button';b.addEventListener('click',()=>void Promise.resolve().then(fn).catch(e=>current?.feedback(message(e))));return b;};
const message=e=>({MEMORY_EXPIRED:c('本次预览已失效，请重新选择材料。','This preview expired. Select the materials again.'),MEMORY_DENIED:c('此项已设为不用于 AI，请核对来源限制。','A source restriction blocks this material.'),MEMORY_STALE:c('材料已变化，请核对后重新准备。','Materials changed. Review and prepare again.'),MEMORY_LIMIT:c('本次材料达到保护上限。请手动分批，内容没有被截断。','This selection reached the safety limit. Split it manually; nothing was truncated.')}[e.code]||c('本机操作未完成，选择与草稿仍保留。请重试。','The local action failed. Your selection and draft are retained. Retry.'));
let current=null;
export const getMaterialTray=()=>current;
export class MaterialTray {
 constructor({onInput,onThought,onHome,onMemory,legacy}={}){
  current=this;Object.assign(this,{onInput,onThought,onHome,onMemory,legacyRoot:legacy});this.data=null;this.mode='tray';this.drafts=new Map();this.busy=false;this.serial=Promise.resolve();this.sourceEpoch=0;this.rechecking=false;this.root=element('section','material-workbench');this.root.id='material-workbench';this.root.hidden=true;this.panel=document.getElementById('memory-panel');this.panel.prepend(this.root);this.drawer=element('aside','material-drawer');this.drawer.hidden=true;this.drawer.setAttribute('aria-label',c('本次材料','Selected materials'));document.body.append(this.drawer);
  document.addEventListener('paia:material-add',e=>void this.add(e.detail.refs));
  chrome.runtime.onMessage.addListener(m=>{if(m.type==='ARCHIVE_CHANGED'&&m.cause&&!['UPDATE_PREFERENCES','RECORD_TOPIC_READ'].includes(m.cause)){const epoch=++this.sourceEpoch;this.rechecking=!!this.data&&!this.expired;this.invalidateOutput();if(this.rechecking){this.root.querySelector('#material-output-text')?.remove();this.root.querySelector('.material-output-actions')?.remove();}void this.refresh(epoch);}});
  window.addEventListener('resize',()=>{if(this.drawer.hidden)return;document.querySelector('.app-shell').inert=innerWidth<=600;if(innerWidth<=600&&!this.drawer.contains(document.activeElement)){const h=this.root.querySelector('h2');h.tabIndex=-1;h.focus();}});
  window.addEventListener('beforeunload',e=>{if(this.drafts.size||this.data?.items.some(i=>i.edited)){e.preventDefault();e.returnValue='';}});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden&&this.data)void this.refresh(this.sourceEpoch);});
  const localizeSettings=()=>{for(const [id,zh,en,helpZh,helpEn]of [['memory-local-only','仅在本机使用（Local-only）','Local-only','阻止 PAIA 主动云端处理与连接访问；手动复制和文件导出仍可用。关闭此限制不会自动重启任务。','Blocks PAIA cloud processing and connection access. Manual copy and file export remain available. Disabling this restriction never restarts tasks.'],['memory-external-access','允许已授权的外部连接访问','Allow authorized connection access','关闭后保留连接禁止。你明确选择的本次材料仍可手动复制或导出；禁止用于 AI 的规则继续生效。','Connections remain blocked when disabled. Explicitly selected materials can still be copied or exported manually; AI restrictions continue to apply.']]){const box=document.getElementById(id);if(box){box.parentElement.firstChild.textContent=c(zh,en);box.parentElement.nextElementSibling.textContent=c(helpZh,helpEn);}}};localizeSettings();new MutationObserver(()=>{localizeSettings();if(!this.drafts.size&&!this.composing?.size)this.render();}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
 }
 async rpc(action,options={}){const epoch=this.sourceEpoch,result=await request('PAIA_CONTEXT_MANUAL',{options:{action,...(action==='create'?{}:{selectionId:this.data.selectionId,generation:this.data.generation}),...options}});if(action!=='create'&&epoch!==this.sourceEpoch){const error=new Error('stale material response');error.code='MATERIAL_RESPONSE_STALE';throw error;}return result;}
 async ensure(){if(!this.data)this.data=await this.rpc('create');}
 perform(fn){const job=this.serial.then(async()=>{this.busy=true;try{await this.ensure();return await fn();}catch(e){if(e.code==='MATERIAL_RESPONSE_STALE')return null;if(e.code==='MEMORY_EXPIRED'){this.expired=true;this.rechecking=false;this.invalidateOutput();this.render();}this.feedback(message(e));return null;}finally{this.busy=false;}});this.serial=job.catch(()=>{});return job;}
 feedback(text){if(this.status)this.status.textContent=text;}
 invalidateOutput(){this.root.querySelector('#material-output-text')?.replaceChildren();for(const b of this.root.querySelectorAll('[data-output]'))b.disabled=true;this.root.querySelector('.material-copy-fallback')?.remove();}
 async refresh(epoch=this.sourceEpoch){if(!this.data||this.expired)return;await this.perform(async()=>{const previous=this.data,wasRechecking=this.rechecking,next=await this.rpc('read');if(epoch!==this.sourceEpoch)return null;this.data=next;this.rechecking=false;for(const i of this.data.items)if(i.state==='blocked')this.drafts.delete(i.itemId);const editing=this.root.querySelector('textarea:focus');if(editing){for(const i of this.data.items)if(i.state==='blocked'){const field=[...this.root.querySelectorAll('[data-material-edit]')].find(n=>n.dataset.materialEdit===i.itemId);if(field){field.value='';field.readOnly=true;}}this.feedback(this.data.state==='blocked'||this.data.state==='stale'?message({code:'MEMORY_STALE'}):c('本次改写仍保留。','Your output edits are retained.'));}else if(wasRechecking||this.visibleChanged(previous,next))this.render();return true;});}
 visibleChanged(a,b){if(!a||!b||a.state!==b.state||a.note!==b.note||a.text!==b.text||a.characters!==b.characters||a.items.length!==b.items.length)return true;return b.items.some((item,index)=>{const old=a.items[index];return !old||old.itemId!==item.itemId||old.state!==item.state||old.body!==item.body||old.title!==item.title||old.edited!==item.edited||JSON.stringify(old.ref)!==JSON.stringify(item.ref)||JSON.stringify(old.restriction)!==JSON.stringify(item.restriction);});}
 activate(active){this.active=active;if(active){this.advanced=false;this.drawer.hidden=true;document.querySelector('.app-shell').inert=false;this.panel.prepend(this.root);this.root.hidden=false;this.legacyRoot.hidden=true;void this.perform(async()=>{const previous=this.data,next=await this.rpc('read');this.data=next;this.rechecking=false;if(!this.root.firstChild||this.visibleChanged(previous,next))this.render();});}else if(!this.drawer.hidden){this.root.hidden=false;}else this.root.hidden=true;}
 legacy(){this.advanced=true;this.root.hidden=true;this.legacyRoot.hidden=false;this.drawer.hidden=true;}
 openDrawer(){if(this.drawer.hidden)this.originFocus=document.activeElement;this.root.hidden=false;this.drawer.append(this.root);this.drawer.hidden=false;this.render();if(innerWidth<=600){document.querySelector('.app-shell').inert=true;this.root.querySelector('#material-title').tabIndex=-1;this.root.querySelector('#material-title').focus();}}
 closeDrawer(){this.drawer.hidden=true;document.querySelector('.app-shell').inert=false;this.originFocus?.focus?.({preventScroll:true});this.panel.prepend(this.root);this.root.hidden=!this.active;}
 async add(refs){return this.perform(async()=>{await this.flush();this.data=await this.rpc('add',{refs});this.mode='tray';if(this.active&&!document.querySelector('.workspace').classList.contains('search-task'))this.render();else this.openDrawer();document.dispatchEvent(new CustomEvent('paia:materials-changed',{detail:{refs:this.data.items.map(i=>i.ref)}}));});}
 async flush(){if(this.composing?.size)throw Object.assign(new Error('composition pending'),{code:'COMPOSING'});for(const [id,text]of [...this.drafts]){this.data=await this.rpc(id==='note'?'note':'edit',id==='note'?{text}:{itemId:id,text});this.drafts.delete(id);}}
 async change(action,options={}){return this.perform(async()=>{await this.flush();this.data=await this.rpc(action,options);this.render();document.dispatchEvent(new CustomEvent('paia:materials-changed',{detail:{refs:this.data.items.map(i=>i.ref)}}));});}
 async preview(){const prepared=await this.perform(async()=>{await this.flush();this.data=await this.rpc('preview');this.mode='preview';this.editing=false;this.render();return true;});if(!prepared)return;if(!this.drawer.hidden){this.closeDrawer();document.dispatchEvent(new Event('paia:search-close'));await this.onMemory();}}
 field(id,value,label){const wrap=element('label','material-field',label),area=element('textarea');area.value=this.drafts.get(id)??value;area.dataset.materialEdit=id;area.setAttribute('aria-label',label);area.rows=Math.min(18,Math.max(3,area.value.split('\n').length+2));area.addEventListener('compositionstart',()=>{(this.composing??=new Set()).add(id);});area.addEventListener('compositionend',()=>{this.composing?.delete(id);});area.addEventListener('input',()=>{this.drafts.set(id,area.value);this.invalidateOutput();this.feedback(c('这些修改只影响本次输出，请确认后复制。','These edits affect only this output. Confirm before copying.'));});wrap.append(area);return {wrap,area};}
 render(){
  if(this.advanced||!this.data)return;const focus=document.activeElement?.dataset.materialEdit,start=document.activeElement?.selectionStart,end=document.activeElement?.selectionEnd,scroll=this.drawer.hidden?window.scrollY:this.drawer.scrollTop;
  this.root.replaceChildren();const header=element('header','material-header'),title=element('h2','',c(this.mode==='preview'?'这次准备给 AI 的内容':'这次想让 AI 知道什么？',this.mode==='preview'?'Content for this AI task':'What should AI know this time?'));title.id='material-title';header.append(title);
  if(!this.drawer.hidden)header.append(button('关闭材料盘','Close tray',()=>this.closeDrawer()));this.root.append(header);
  this.status=element('p','material-status');this.status.setAttribute('role','status');this.root.append(this.status);this.feedback(this.expired?message({code:'MEMORY_EXPIRED'}):c('只在本机准备，尚未发送。','Prepared on this device. Not sent.'));
  if(this.expired){this.root.append(button('重新选择材料','Start a new selection',async()=>{this.sourceEpoch++;this.rechecking=false;this.data=null;this.expired=false;this.drafts.clear();await this.perform(async()=>{this.mode='tray';this.render();});}));return;}
  if(this.rechecking){this.feedback(c('材料已变化，正在重新核对。旧预览暂不可见，也不能输出。','Materials changed and are being rechecked. The old preview is hidden and cannot be output.'));this.root.append(element('p','material-blocked',c('请等本机核对当前来源与限制后再继续。','Continue after the current sources and restrictions are revalidated on this device.')));return;}
  if(this.mode==='tray')this.renderTray();else this.renderPreview();
  if(focus){const area=[...this.root.querySelectorAll('textarea')].find(n=>n.dataset.materialEdit===focus);if(area){area.focus({preventScroll:true});area.setSelectionRange(start,end);}}if(!this.drawer.hidden)this.drawer.scrollTop=scroll;
 }
 renderTray(){
  const count=element('h3','',c('你选的 '+this.data.items.length+' 项',this.data.items.length+' selected materials'));count.id='material-count';this.root.append(count);
  const choose=element('div','material-actions');choose.append(button('从档案选择','Choose from Archive',()=>{this.closeDrawer();document.dispatchEvent(new CustomEvent('paia:search-open',{detail:{types:['input']}}));}),button('从主题选择','Choose from Topics',async()=>{this.closeDrawer();await this.onHome();}),button('清空本次材料','Clear selection',()=>this.change('clear')));this.root.append(choose);
  if(!this.data.items.length)this.root.append(element('p','',c('先选择具体文字；不需要创建主题或配置 Profile。','Choose specific text. A Topic or Profile is not required.')));
  const list=element('div','material-list');for(const [index,item]of this.data.items.entries()){
   const row=element('article','material-row');row.dataset.materialId=item.itemId;row.append(element('strong','',item.title),element('p','material-snippet',item.body),element('small','',item.ref.kind==='ai'?c('AI 整理','AI-generated'):item.ref.kind==='source'?c('当时记录','Source snapshot'):c('当前工作文字','Current working text')));
   if(this.data.items.some(i=>i!==item&&i.ref.kind===item.ref.kind&&i.ref.id===item.ref.id))row.append(element('p','',c('同一材料的另一版本或选段；保留各自选择。','Another version or selection of this material is retained separately.')));
   if(item.state!=='ready'){row.classList.add('material-blocked');row.append(element('p','',item.state==='stale'?message({code:'MEMORY_STALE'}):c('此项受阻，不能进入输出。','Blocked: excluded from output.')),button(item.restriction?'修改此项限制':'重新选择材料',item.restriction?'Review this restriction':'Reselect material',()=>item.restriction?this.restriction(item):this.openSource(item)));}
   const controls=element('div','material-actions');controls.append(button('移除','Remove',()=>this.change('remove',{itemId:item.itemId})),button('查看来源','Open source',()=>this.openSource(item)));
   for(const [delta,zh,en]of [[-1,'上移','Move up'],[1,'下移','Move down']]){const b=button(zh,en,()=>{const ids=this.data.items.map(i=>i.itemId);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];return this.change('order',{itemIds:ids});});b.disabled=index+delta<0||index+delta>=this.data.items.length;controls.append(b);}row.append(controls);list.append(row);
  }this.root.append(list);
  this.root.append(this.field('note',this.data.note,c('你准备问什么？（可不填）','Your question or note (optional)')).wrap);
  const more=element('details','material-suggestions'),summary=element('summary','',c('找相关补充','Find related additions'));more.append(summary,element('p','',c('只检索已有允许范围；建议默认未选，明确禁止继续生效。','Search existing allowed scopes. Suggestions remain unselected and restrictions still apply.')));
  more.append(button('检查允许范围','Review allowed scopes',()=>{this.legacy();this.onLegacy?.();}),button('查找补充','Find additions',()=>this.perform(async()=>{await this.flush();const result=await this.rpc('suggest',{query:this.data.note});this.suggestions=result.suggestions;this.data=result;const results=element('div');for(const item of this.suggestions){const row=element('article');row.append(element('p','',item.body),button('加入本次材料','Add to selection',()=>this.add([item.ref])));results.append(row);}if(!this.suggestions.length)results.append(element('p','',c('允许范围内没有找到补充，已选材料仍可预览。','No additions found in the allowed scope. You can preview your selection.')));more.querySelector('.material-suggestion-results')?.remove();results.className='material-suggestion-results';more.append(results);})));this.root.append(more);
  const preview=button('预览这份内容','Preview this content',()=>this.preview());preview.id='material-preview';preview.className='primary';this.root.append(preview);
 }
 renderPreview(){
  this.root.append(button('返回材料','Back to materials',()=>{this.mode='tray';this.render();}),element('p','',c('这些修改只影响本次输出。请检查所有文字，包括间接身份线索。','Edits affect only this output. Review all text, including indirect identifying details.')));
  if(this.data.state!=='ready')this.root.append(element('p','material-blocked',this.data.state==='blocked'?c('受阻材料已从可输出正文移除。请返回材料盘处理。','Blocked materials were removed from the output. Resolve them in the tray.'):message({code:'MEMORY_STALE'})));
  if(this.editing||this.data.state==='dirty'){
   this.root.append(this.field('note',this.data.note,c('本次说明（不是历史表达）','Task note (not historical expression)')).wrap);
   for(const item of this.data.items){if(item.state!=='ready')continue;const {wrap,area}=this.field(item.itemId,item.body,c('本次材料文字','Material text for this output'));wrap.append(button('遮去所选文字','Redact selected text',()=>{const start=area.selectionStart,end=area.selectionEnd;return this.change('redact',{itemId:item.itemId,start,end});}));this.root.append(wrap);}
   this.root.append(button('确认本次修改','Confirm these edits',()=>this.preview()));
  }else{
   const text=element('pre','material-output',this.data.text);text.id='material-output-text';this.root.append(element('p','',c('实际字数：','Characters: ')+this.data.characters),text,button('修改本次输出','Edit this output',()=>{this.editing=true;this.render();}));
  }
  const actions=element('div','material-actions material-output-actions');for(const [format,zh,en]of [['copy','复制这份内容','Copy this content'],['markdown','导出 Markdown','Export Markdown']]){const b=button(zh,en,()=>this.share(format));b.dataset.output=format;b.disabled=this.rechecking||this.data.state!=='ready'||this.editing||this.drafts.size>0;actions.append(b);}this.root.append(actions);
 }
 async openSource(item){this.closeDrawer();if(['input','source'].includes(item.ref.kind))await this.onInput(item.ref.id);else if(item.ref.kind==='thought'){const paths=await request('GET_LIBRARY_PATHS',{id:item.ref.id});await this.onThought(paths.items?.[0]?.topicId||paths[0]?.topicId,item.ref.id);}else await this.onThought(item.ref.id,null);}
 async restriction(item){const rule=item.restriction;if(!rule)return;const dialog=element('dialog','topic-action-dialog');dialog.append(element('h2','',c('修改这项限制','Change this restriction')),element('p','',rule.kind==='topic'?c('这是继承的主题级禁止。撤销会影响该主题关联的材料，其他禁止仍然有效。','This is an inherited Topic restriction. Removing it affects related materials; other restrictions remain.'):rule.kind==='section'?c('这是章节级排除。撤销仅改变这个章节的规则。','This exclusion belongs to a section. Only that section rule will change.'):c('只撤销这一条材料的持久排除；其他禁止继续有效。','Remove only this item exclusion. All other restrictions remain.')));const cancel=button('取消','Cancel',()=>dialog.close()),confirm=button('确认撤销这项限制','Remove this restriction',()=>this.perform(async()=>{if(rule.kind==='topic')await request('PAIA_MEMORY_AUTHORIZE',{options:{profileId:rule.profileId,topicIds:[rule.topicId],decision:'default'}});else{const {kind,...target}=rule;await request('PAIA_MEMORY_EXCLUDE',{options:{...target,excluded:false}});}dialog.close();this.feedback(c('已撤销指定规则。请移除此受阻项，再从来源重新选择并核对。','The specified rule was removed. Remove this blocked item, then reselect and review its source.'));}));dialog.append(cancel,confirm);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);dialog.showModal();cancel.focus();}
 async share(format){if(this.busy||this.rechecking)return;await this.perform(async()=>{await this.flush();const result=await this.rpc('share',{format});if(format==='markdown'){const url=URL.createObjectURL(new Blob([result.text],{type:'text/markdown;charset=utf-8'})),a=element('a');a.href=url;a.download='PAIA-Context.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);this.feedback(c('已导出，尚未发送。','Exported. Not sent.'));}else{try{await navigator.clipboard.writeText(result.text);this.feedback(c('已复制，尚未发送。','Copied. Not sent.'));}catch{const fallback=element('textarea','material-copy-fallback');fallback.readOnly=true;fallback.value=result.text;fallback.setAttribute('aria-label',c('已核验的完整文字，可全选复制','Verified full text for manual copying'));this.root.append(fallback);fallback.focus();fallback.select();this.feedback(c('剪贴板写入失败，可全选这份已核验文字复制。','Clipboard failed. Select and copy this verified text.'));}}});}
}
