import {request,element,dateLabel} from './common.js';
import {setProductState} from './product-state.js';
import {contextText,estimatedTokens,memoryTypeLabel,contextStateLabel,contextWarnings} from '../core/memory/retrieval.js';
const $=id=>document.getElementById(id), labels={allowed:'允许 AI 使用',default:'未授权',denied:'不允许 AI 使用',never:'永不提供给 AI'};
const option=(value,label)=>{const e=element('option','',label);e.value=value;return e;};
const action=(label,fn)=>{const b=element('button','',label);b.type='button';b.addEventListener('click',()=>void fn());return b;};
const messages={MEMORY_EXTERNAL_DISABLED:'对外提供 AI 上下文已关闭。请前往 Settings 开启后，再明确选择复制或导出。',MEMORY_PROFILE_CONFLICT:'此 Profile 已在其他页面修改。你的草稿仍保留，请重新读取已保存设置后再编辑。',MEMORY_NAME_EXISTS:'这个 Profile 名称已存在，请使用不同名称。',MEMORY_STALE:'授权或思想内容已变化，旧预览已停用。请重新生成预览；没有修改你的授权设置。',MEMORY_DENIED:'此主题已明确禁止使用。请先将长期设置改为“未授权”，再选择仅本次允许。',MEMORY_CONFIRM_REQUIRED:'请确认本次所选主题的授权范围。',MEMORY_UNAVAILABLE:'主题已删除、合并或正在更新。请重新打开授权列表核对。',MEMORY_LIMIT:'最多可保留 20 个 Profile。请先整理已有 Profile。',MEMORY_EMPTY:'当前预览没有可以分享的内容。请检查授权或换一个问题。',MEMORY_INVALID:'本次设置未保存，请检查名称、详细度和授权范围后重试。'};
export class MemoryPanel {
 constructor({onThought,onInput,onHome,onMemory}={}){this.onThought=onThought;this.onInput=onInput;this.onHome=onHome;this.onMemory=onMemory;this.profileId='default';this.page='home';this.active=false;this.cursor=0;this.expanded=new Set();this.profileDirty=false;this.selected=new Set();this.removed=new Set();this.serial=0;this.busy=false;
  this.bind('memory-start',()=>this.perform(async()=>{await this.rpc('SETTINGS',{onboarded:true});await this.open('authorizations');}));
  for(const id of ['memory-manage','memory-builder-manage','memory-preview-manage'])this.bind(id,()=>this.open('authorizations'));
  this.bind('memory-prepare',()=>this.open('builder'));this.bind('memory-home-back',()=>this.open('home'));this.bind('memory-rebuild',()=>this.open('builder'));this.bind('memory-to-thoughts',()=>this.onHome());
  $('memory-build-form').addEventListener('submit',e=>{e.preventDefault();void this.build();});
  this.bind('memory-copy',()=>this.share('copy'));this.bind('memory-markdown',()=>this.share('markdown'));
  for(const id of ['memory-profile-name','memory-instruction'])$(id).addEventListener('input',()=>{this.profileDirty=true;});
  for(const id of ['memory-profile','memory-auth-profile'])$(id).addEventListener('change',()=>{if(this.profileDirty&&!window.confirm('放弃尚未保存的 Profile 名称或使用偏好？')){$(id).value=this.profileId;return;}this.profileDirty=false;this.lastProfile=null;this.profileId=$(id).value;this.cursor=0;this.selected.clear();this.invalidate(false);void this.perform(()=>this.refresh());});
  $('memory-auth-search').addEventListener('input',()=>{clearTimeout(this.searchTimer);this.cursor=0;this.selected.clear();this.selectionCount();this.searchTimer=setTimeout(()=>void this.perform(()=>this.refresh()),180);});
  $('memory-select-page').addEventListener('change',()=>{this.selected.clear();if($('memory-select-page').checked)for(const row of this.data?.items||[])this.selected.add(row.id);this.renderTopics();});
  this.bind('memory-auth-next',()=>{this.cursor=this.data?.nextCursor??0;this.selected.clear();return this.perform(()=>this.refresh());});
  this.bind('memory-select-results',()=>this.selectResults());this.bind('memory-profile-reload',()=>this.perform(async()=>{if(this.profileDirty&&!window.confirm('放弃当前草稿并重新读取已保存的 Profile 设置？'))return;this.profileDirty=false;this.lastProfile=null;await this.refresh();this.feedback('已重新读取保存的 Profile。');}));
  this.bind('memory-bulk-allow',()=>this.bulk('allowed'));this.bind('memory-bulk-deny',()=>this.bulk('denied'));
  this.bind('memory-clear-session',()=>this.perform(async()=>{await this.rpc('SETTINGS',{clearTemporary:true});this.invalidate(false);await this.refresh();this.feedback('所有临时授权已撤销。');}));
  this.bind('memory-clear-activity',()=>this.perform(async()=>{await this.rpc('SETTINGS',{clearActivity:true});await this.refresh();this.feedback('活动记录已清除，思想与授权保持不变。');}));
  $('memory-profile-form').addEventListener('submit',e=>{e.preventDefault();void this.saveProfile('edit');});this.bind('memory-profile-create',()=>this.saveProfile('create'));this.bind('memory-profile-delete',()=>this.saveProfile('delete'));
  this.bind('memory-settings-open',async()=>{await this.onMemory();await this.open('authorizations');});this.bind('memory-settings-save',()=>this.perform(async()=>{await this.rpc('SETTINGS',{budget:$('memory-default-budget').value,retentionDays:Number($('memory-retention').value),externalAccess:$('memory-external-access').checked,includeUnorganizedInputs:$('memory-include-unorganized-inputs').checked});$('memory-settings-status').textContent='AI Context 设置已保存。';await this.refreshSettings();}));this.bind('memory-input-exclusions-clear',()=>this.perform(async()=>{if(!window.confirm('恢复所有已长期排除的未整理 Input？它们仍需满足智能过滤、移除状态和未被 Thought 表示等条件，才可能进入后续上下文。'))return;await this.rpc('SETTINGS',{clearInputExclusions:true});await this.refreshSettings();$('memory-settings-status').textContent='已恢复所有直接 Input 排除。';}));
 }
 bind(id,fn){$(id).addEventListener('click',()=>void fn());}
 rpc(name,options={}){return request('PAIA_MEMORY_'+name,{options});}
 feedback(text,state='ready'){const el=this.active?$('memory-status'):$('memory-settings-status');setProductState(el,state);el.textContent=text;}
 async perform(fn){try{return await fn();}catch(e){if(e.code==='MEMORY_STALE')this.invalidate(false);this.feedback(messages[e.code]||'本机操作未完成，请重试。已保存的思想内容不会因此改变。','failed');if(this.active&&this.data&&!this.busy)await this.refresh().catch(()=>{});return null;}}
 leave(){if(this.profileDirty&&!window.confirm('Profile 使用偏好尚未保存。放弃这些修改并离开？'))return false;this.profileDirty=false;return true;}
 async activate(active){if(this.active===active)return;this.active=active;if(active){this.lastProfile=null;await this.perform(()=>this.open('home'));}else{this.serial++;clearTimeout(this.searchTimer);this.invalidate(false);this.page='home';}}
 invalidate(message=true){if(!this.preview)return;this.preview=null;this.removed.clear();$('memory-preview-body').replaceChildren();$('memory-copy').disabled=true;$('memory-markdown').disabled=true;if(message&&this.page==='preview'){this.feedback(messages.MEMORY_STALE,'stale');$('memory-size').textContent='旧预览已停用，请重新生成。';}}
 fillProfile(profile){for(const id of ['memory-profile-name','memory-instruction','memory-profile-create','memory-profile-reload'])$(id).disabled=!profile;if(!profile)return;this.draftRevision=profile.revision;$('memory-profile-name').value=profile.name;$('memory-instruction').value=profile.instruction;if(this.lastProfile!==this.profileId){$('memory-budget').value=profile.budget;this.lastProfile=this.profileId;}}
 async open(page){this.serial++;this.page=page;if(page==='builder'&&!this.profileDirty)this.fillProfile(this.data?.profiles.find(p=>p.profileId===this.profileId));if(page!=='preview')this.invalidate(false);for(const name of ['home','authorizations','builder','preview'])$('memory-'+name).hidden=name!==page;$('memory-trail').hidden=page==='home';$('memory-location').textContent={authorizations:'AI Context / 管理授权',builder:'AI Context / 准备上下文',preview:'AI Context / 上下文预览'}[page]||'';this.feedback('');if(page==='builder')$('memory-query').focus();if(page==='authorizations')$('memory-auth-search').focus();await this.perform(()=>this.refresh());}
 async refresh(){if(!this.active)return;const seq=++this.serial,d=await this.rpc('STATUS',{profileId:this.profileId,query:this.page==='authorizations'?$('memory-auth-search').value:'',cursor:this.page==='authorizations'?this.cursor:0});if(!this.active||seq!==this.serial)return;this.data=d;if(this.preview&&this.preview.generation!==d.generation)this.invalidate();$('memory-onboarding').hidden=d.config.onboarded||this.page!=='home';$('memory-no-authorization').hidden=d.allowed>0||d.config.includeUnorganizedInputs;$('memory-external-notice').hidden=d.config.externalAccess!==false;for(const id of ['memory-profile','memory-auth-profile'])$(id).parentElement.hidden=d.profiles.length===1;$('memory-allowed').textContent=d.allowed+' 个主题';$('memory-denied').textContent=d.denied+' 个主题';$('memory-empty').hidden=d.total>0;$('memory-prepare').disabled=d.total===0&&!d.config.includeUnorganizedInputs;$('memory-manage').disabled=d.total===0;for(const id of ['memory-profile','memory-auth-profile']){const select=$(id);select.replaceChildren(...d.profiles.map(p=>option(p.profileId,p.name)));select.value=this.profileId;}const profile=d.profiles.find(p=>p.profileId===this.profileId);if(this.page==='builder'&&profile&&!this.profileDirty&&document.activeElement!==$('memory-profile-name')&&document.activeElement!==$('memory-instruction')){this.fillProfile(profile);}$('memory-profile-delete').disabled=this.profileId==='default';if(this.page==='authorizations')this.renderTopics();this.renderActivity();}
 selectionCount(){$('memory-selection-count').textContent=this.selected.size?'已选 '+this.selected.size+' 个主题':'';}
 renderTopics(){this.selectionCount();const d=this.data,list=$('memory-topic-list');list.replaceChildren();$('memory-select-page').checked=d.items.length>0&&d.items.every(x=>this.selected.has(x.id));for(const item of d.items){const row=element('section','memory-topic-row');row.dataset.memoryTopic=item.id;const label=element('label','memory-topic-label'),check=element('input');check.type='checkbox';check.checked=this.selected.has(item.id);check.setAttribute('aria-label','选择 '+item.name);check.addEventListener('change',()=>{if(check.checked)this.selected.add(item.id);else this.selected.delete(item.id);this.selectionCount();});label.append(check,element('strong','',item.name));const controls=element('div','memory-topic-controls'),select=element('select');select.setAttribute('aria-label',item.name+' · 长期授权');select.replaceChildren(...Object.entries(labels).map(([v,l])=>option(v,l)));select.value=item.permanentDecision;select.addEventListener('change',()=>void this.perform(async()=>{await this.rpc('AUTHORIZE',{profileId:this.profileId,topicIds:[item.id],decision:select.value});this.invalidate(false);await this.refresh();this.feedback('授权已保存。');}));const temporary=action(item.temporary?'撤销本次允许':'仅本次允许',()=>this.perform(async()=>{await this.rpc('AUTHORIZE',{profileId:this.profileId,topicIds:[item.id],decision:item.temporary?'default':'allowed',scope:'session'});this.invalidate(false);await this.refresh();this.feedback(item.temporary?'临时授权已撤销。':'仅本次允许，Chrome 会话结束后失效。');}));temporary.disabled=['denied','never'].includes(item.decision)||item.permanentDecision==='allowed';const details=element('details','memory-entry-controls');details.append(element('summary','','管理单条排除'));details.open=this.expanded.has(item.id);let loaded=false;details.addEventListener('toggle',()=>{if(!details.isConnected)return;if(details.open)this.expanded.add(item.id);else this.expanded.delete(item.id);if(details.open&&!loaded){loaded=true;void this.perform(()=>this.renderEntries(details,item.id)).then(result=>{if(result===null)loaded=false;});}});controls.append(select,temporary);row.append(label,controls,element('small','muted',item.temporary?'本次会话允许':labels[item.decision]+(item.neverProfiles?.length?' · 在 '+item.neverProfiles.join(' / ')+' 中设为永不提供，可切换到该 Profile 撤销。':'')),details);list.append(row);}if(!d.items.length)list.append(element('p','muted','没有找到匹配的主题。'));$('memory-auth-next').hidden=d.nextCursor===null;if(this.cursor>0)list.append(action('返回第一页',()=>{this.cursor=0;this.selected.clear();return this.perform(()=>this.refresh());}));}
 async renderEntries(root,topicId,cursor=null){const result=await this.rpc('ENTRIES',{topicId,profileId:this.profileId,cursor});for(const section of result.sections||[]){if([...root.querySelectorAll('[data-memory-section]')].some(el=>el.dataset.memorySection===section.id))continue;const label=element('label','memory-entry-rule'),box=element('input');label.dataset.memorySection=section.id;box.type='checkbox';box.checked=section.excluded;box.setAttribute('aria-label','排除整个章节：'+(section.title||'默认章节'));box.addEventListener('change',()=>void this.perform(async()=>{await this.rpc('EXCLUDE',{topicId,sectionId:section.id,excluded:box.checked});this.invalidate(false);this.feedback(box.checked?'此章节已排除，对所有 Profile 生效。':'章节排除已撤销，单条排除仍然有效。');}));label.append(box,element('strong','','排除整个章节：'+(section.title||'默认章节')));root.append(label);}for(const e of result.items){const label=element('label','memory-entry-rule'),check=element('input');check.type='checkbox';check.checked=e.excluded;check.setAttribute('aria-label','长期排除此条：'+(e.title||e.body.slice(0,40)));check.addEventListener('change',()=>void this.perform(async()=>{await this.rpc('EXCLUDE',{entryId:e.id,excluded:check.checked});this.invalidate(false);this.feedback(check.checked?'此条已长期排除，对所有 Profile 生效。':'此条排除已撤销；仍需主题授权才能使用。');}));label.append(check,element('span','',e.body),element('small','muted','勾选：长期不提供给 AI'));root.append(label);}if(result.nextCursor){const more=action('更多内容',async()=>{more.remove();await this.perform(()=>this.renderEntries(root,topicId,result.nextCursor));});root.append(more);}return true;}
 async selectResults(){clearTimeout(this.searchTimer);await this.perform(async()=>{const query=$('memory-auth-search').value,profileId=this.profileId,selected=new Set();let cursor=0,generation=null;do{const d=await this.rpc('STATUS',{profileId,query,cursor,limit:100});if(d.resultCount>1000){this.feedback('匹配超过 1000 个主题，请缩小搜索范围后选择。');return;}if(generation!==null&&generation!==d.generation){this.feedback('主题列表已变化，请重新选择。');return;}generation=d.generation;for(const item of d.items)selected.add(item.id);cursor=d.nextCursor;}while(cursor!==null);if(profileId!==this.profileId||query!==$('memory-auth-search').value||this.page!=='authorizations')return;this.selected=selected;this.cursor=0;await this.refresh();this.feedback('已选中当前搜索匹配的 '+selected.size+' 个主题，尚未更改授权。');});}
 async bulk(decision){if(!this.selected.size){this.feedback('请先选择要更改的主题。');return;}if(decision==='allowed'&&!window.confirm('允许当前所选 '+this.selected.size+' 个主题用于本地 AI 上下文？分享仍需要你明确点击。'))return;await this.perform(async()=>{await this.rpc('AUTHORIZE',{profileId:this.profileId,topicIds:[...this.selected],decision,confirmed:true});this.selected.clear();this.invalidate(false);await this.refresh();this.feedback('所选主题的授权已保存。');});}
 async saveProfile(actionName){if(actionName==='delete'&&!window.confirm('删除此 Profile 及其主题授权？思想内容和全局单条排除保留。'))return;await this.perform(async()=>{const current=this.data.profiles.find(p=>p.profileId===this.profileId);const result=await this.rpc('PROFILE',{action:actionName,profileId:this.profileId,expectedRevision:actionName==='delete'?current.revision:this.draftRevision,name:$('memory-profile-name').value,budget:$('memory-budget').value,instruction:$('memory-instruction').value});this.profileDirty=false;this.profileId=actionName==='delete'?'default':result.profileId;this.lastProfile=null;this.invalidate(false);await this.refresh();this.feedback(actionName==='delete'?'Profile 已删除。':'Profile 已保存。新 Profile 的主题默认未授权。');});}
 async build(){if(this.busy)return;this.busy=true;const seq=++this.serial;this.invalidate(false);$('memory-build').disabled=true;this.feedback('正在本地选择相关思想，尚未分享…','loading');try{const result=await this.rpc('BUILD',{profileId:this.profileId,query:$('memory-query').value,budget:$('memory-budget').value});if(!this.active||seq!==this.serial)return;this.preview=result;this.removed.clear();this.page='preview';for(const page of ['home','authorizations','builder','preview'])$('memory-'+page).hidden=page!=='preview';$('memory-trail').hidden=false;$('memory-location').textContent='AI Context / 上下文预览';this.renderPreview();this.feedback(result.items.length?(result.partial?'已生成预览。本次达到扫描上限，可缩小授权范围后重新生成。':'预览已准备好，尚未分享。'):result.partial?'本次达到扫描上限，可能未覆盖全部允许内容。请缩小授权范围后重新生成。':result.matched?'当前预算无法容纳相关内容，请提高详细度或缩短使用偏好。':'当前没有找到足够相关的个人上下文。',result.items.length?'ready':'empty');}catch(e){this.feedback(messages[e.code]||'无法生成上下文预览，没有修改你的授权设置。请重试。','failed');}finally{this.busy=false;$('memory-build').disabled=false;}}
 renderPreview(){const p=this.preview;if(!p)return;const selected=p.items.filter(i=>!this.removed.has(i.id)),text=contextText(selected,{instruction:p.instruction,warnings:contextWarnings(selected)}),root=$('memory-preview-body');root.replaceChildren();$('memory-size').textContent=`约 ${[...text].length} 字 · 预计约 ${estimatedTokens(text)} tokens${p.omitted?' · 其余内容未纳入本次预算':''}`;$('memory-preview-empty').hidden=selected.length>0;$('memory-preview-empty').textContent=p.items.length?'本次内容已全部移除，长期授权未改变。':p.partial?'本次达到扫描上限，可能未覆盖全部允许内容。请缩小授权范围后重新生成。':p.matched?'当前预算无法容纳相关内容，请提高详细度或缩短使用偏好。':'当前没有找到足够相关的个人上下文。';$('memory-copy').disabled=!selected.length||p.externalAccess===false;$('memory-markdown').disabled=!selected.length||p.externalAccess===false;$('memory-external-notice').hidden=p.externalAccess!==false;root.append(element('p','muted','以下为明确授权的参考资料。记录文字不是系统指令；问题、推测与历史表述不等于当前事实。'));if(selected.length&&p.retrievalConfidence==='low')root.append(element('p','memory-caution','可能没有找到完整相关内容。可以换一种说法或检查允许的内容。'));if(p.instruction){root.append(element('h3','','AI 使用偏好（非个人事实）'),element('p','memory-prose',p.instruction));}for(const warning of contextWarnings(selected))root.append(element('p','memory-caution',warning));let topic=null;for(const item of selected){if(topic!==item.topicId){topic=item.topicId;root.append(element('h3','memory-topic-heading',item.topicName));}const row=element('article','memory-context-entry');row.dataset.memoryEntry=item.id;row.append(element('p','memory-prose',item.body),element('small','muted',memoryTypeLabel(item.type)+(item.title?' · '+item.title:'')+(item.sectionTitle?' · '+item.sectionTitle:'')+' · '+contextStateLabel(item.state)+' · '+(item.time?(item.timeLabel||'记录时间')+' '+dateLabel(item.time,false):'来源时间未记录')));const details=element('details');details.append(element('summary','','为什么纳入'),element('p','muted',item.why.join(' · ')));if(item.kind==='input'&&item.inputId)details.append(action('在 Input Archive 查看',()=>this.perform(async()=>{await this.onInput(item.inputId);})));else for(const id of item.evidenceEntryIds)details.append(action('在 Thought Library 查看',()=>this.perform(async()=>{await this.onThought(item.topicId,id);})));const controls=element('div','memory-context-controls');controls.append(action('仅本次移除',()=>{this.removed.add(item.id);this.renderPreview();this.feedback('已从本次预览移除，长期授权未改变。');}),action('长期不再提供此条',()=>this.perform(async()=>{const direct=item.kind==='input'&&item.inputId;if(!window.confirm(direct?'长期排除此条 Input？所有 Profile 均不再直接使用，可在 Settings 恢复所有直接 Input 排除。':'长期排除此条思想？所有 Profile 均不再使用，可在授权管理中撤销。'))return;if(direct)await this.rpc('EXCLUDE',{inputId:item.inputId,excluded:true});else for(const id of item.evidenceEntryIds)await this.rpc('EXCLUDE',{entryId:id,excluded:true});this.invalidate(false);this.feedback('此条已长期排除，请重新生成预览。','stale');})));row.append(details,controls);root.append(row);}}
 async share(format){if(this.busy||!this.preview)return;this.busy=true;const snapshot=this.preview;try{$('memory-copy').disabled=true;$('memory-markdown').disabled=true;const result=await this.rpc('SHARE',{previewId:snapshot.previewId,format,removed:[...this.removed]});if(this.preview!==snapshot)return;if(format==='copy'){await navigator.clipboard.writeText(result.text);this.feedback('上下文已复制。请粘贴到你选择的 AI；PAIA 没有自动发送。','saved');}else{const url=URL.createObjectURL(new Blob([result.text],{type:'text/markdown;charset=utf-8'})),a=element('a');a.href=url;a.download='PAIA-Context.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);this.feedback('上下文已导出为 Markdown。','saved');}snapshot.generation=result.generation;}catch(e){if(e.code==='MEMORY_STALE')this.invalidate(false);this.feedback(messages[e.code]||(format==='copy'?'未能写入剪贴板，未自动发送任何内容。请重试或导出 Markdown。':'导出未完成，请重试。'),'failed');}finally{this.busy=false;$('memory-copy').disabled=!this.preview||this.preview.externalAccess===false;$('memory-markdown').disabled=!this.preview||this.preview.externalAccess===false;}}
 renderActivity(){const root=$('memory-activity-list');root.replaceChildren();const names={build:'准备上下文',copy:'准备复制',markdown:'准备导出 Markdown',permission:'修改授权',profile:'修改 Profile',settings:'修改设置'};for(const row of this.data.activity){root.append(element('p','muted',dateLabel(row.createdAt)+' · '+(names[row.action]||'本机操作')+' · '+row.profileName+(row.topicNames.length?' · '+row.topicNames.join(' / '):'')));}if(!this.data.activity.length)root.append(element('p','muted','尚无活动记录。这里不保存上下文正文。'));}
 async refreshSettings(){const result=await this.rpc('STATUS');if(document.activeElement!==$('memory-external-access'))$('memory-external-access').checked=result.config.externalAccess!==false;if(document.activeElement!==$('memory-include-unorganized-inputs'))$('memory-include-unorganized-inputs').checked=result.config.includeUnorganizedInputs===true;if(document.activeElement!==$('memory-default-budget'))$('memory-default-budget').value=result.config.budget;if(document.activeElement!==$('memory-retention'))$('memory-retention').value=String(result.config.retentionDays);$('memory-input-exclusions-clear').hidden=!result.excludedInputs;$('memory-input-exclusions-status').textContent=result.excludedInputs?`已长期排除 ${result.excludedInputs} 条直接 Input。`:'没有长期排除的直接 Input。';}
}
