import {request} from './common.js';
import {copyReadingText} from './reading-actions.js';
const $=id=>document.getElementById(id);
let snapshot=null,memoryStatus=null,packagePreview=null,busy=false;
const pct=value=>Number.isFinite(value)?Math.round(value*100)+'%':'0%';
const labels={consumer:{chatgpt:'ChatGPT',claude:'Claude',gemini:'Gemini',coding_agent:'Coding Agent',other_ai:'其他 AI'},purpose:{general:'通用协助',research:'研究',coding:'编程',career:'职业 / 求职',writing:'写作'},duration:{once:'仅一次', '7d':'7 天','30d':'30 天'},state:{active:'有效',revoked:'已撤销',expired:'已过期',consumed:'已使用'},action:{copy:'复制',markdown:'导出 Markdown',manual_copy:'手动复制',manual_markdown:'手动导出 Markdown'}};
const option=(value,text)=>{const o=document.createElement('option');o.value=value;o.textContent=text;return o;};
const fmt=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('zh-CN'):'—';
// Static labels + numeric values only. No product signal body is ever rendered as HTML.
function metricNode(value,label){const root=document.createElement('div');root.className='metric';const strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=String(value);span.textContent=label;root.append(strong,span);return root;}
function group(title,items){const root=document.createElement('section');root.className='group';const h=document.createElement('h3');h.textContent=title;const grid=document.createElement('div');grid.className='metric-grid';for(const [value,label]of items)grid.append(metricNode(value,label));root.append(h,grid);return root;}
function row(label,value){const root=document.createElement('div');root.className='loop-row';const a=document.createElement('span'),b=document.createElement('span');a.textContent=label;b.textContent=String(value);root.append(a,b);return root;}
function profileName(id){return memoryStatus?.profiles?.find(p=>p.profileId===id)?.name||id;}
function activeGrants(){return (snapshot?.passport?.grants||[]).filter(g=>g.state==='active');}
function clearPackage(){packagePreview=null;$('package-meta').hidden=true;$('package-preview').hidden=true;$('package-actions').hidden=true;$('package-meta').textContent='';$('package-preview').textContent='';}
function renderPassport(data){const passport=data.passport||{grants:[],audits:[]},grants=$('passport-grants');grants.replaceChildren();for(const g of passport.grants){const card=document.createElement('div');card.className='grant-card';const info=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('p'),usage=document.createElement('p'),state=document.createElement('span');title.textContent=`${labels.consumer[g.consumer]||g.consumer} · ${labels.purpose[g.purpose]||g.purpose}`;meta.textContent=`Profile：${profileName(g.profileId)} · ${labels.duration[g.duration]||g.duration}${g.expiresAt?' · 到期 '+fmt(g.expiresAt):''}`;usage.textContent=`使用 ${g.useCount} 次${g.lastUsedAt?' · 最近 '+fmt(g.lastUsedAt):''}`;state.className='grant-state '+g.state;state.textContent=labels.state[g.state]||g.state;info.append(title,meta,usage,state);card.append(info);if(g.state==='active'){const revoke=document.createElement('button');revoke.type='button';revoke.className='danger';revoke.textContent='撤销';revoke.addEventListener('click',()=>void revokeGrant(g.grantId));card.append(revoke);}grants.append(card);}if(!passport.grants.length){const p=document.createElement('p');p.className='muted';p.textContent='还没有 Passport Grant。';grants.append(p);}const audit=$('passport-audit-list');audit.replaceChildren();for(const a of passport.audits||[]){const item=document.createElement('div');item.className='audit-row';const time=document.createElement('span'),text=document.createElement('span');time.textContent=fmt(a.createdAt);text.textContent=`${labels.consumer[a.consumer]||a.consumer} · ${labels.purpose[a.purpose]||a.purpose} · ${profileName(a.profileId)} · ${labels.action[a.action]||a.action}`;item.append(time,text);audit.append(item);}if(!passport.audits?.length){const p=document.createElement('p');p.className='muted';p.textContent='尚无访问审计。';audit.append(p);}const select=$('package-grant'),previous=select.value,active=activeGrants();select.replaceChildren(...active.map(g=>option(g.grantId,`${labels.consumer[g.consumer]||g.consumer} · ${labels.purpose[g.purpose]||g.purpose} · ${profileName(g.profileId)} · ${labels.duration[g.duration]||g.duration}`)));if(active.some(g=>g.grantId===previous))select.value=previous;$('package-build').disabled=!active.length;}
function render(data){snapshot=data;$('signals-enabled').checked=data.enabled;$('signals-range').textContent=`最多保留 ${data.retentionDays} 天 · 最近 30 天有 ${data.activeDaysLast30} 个记录日`;const s=$('signals-summary');s.replaceChildren();const i=data.last30Days.input,t=data.last30Days.thought,c=data.last30Days.context;s.append(group('Input Archive',[[i.searches,'搜索'],[i.searchHits,'搜索命中'],[pct(i.searchHitRate),'搜索命中率'],[i.searchOpens,'搜索结果打开'],[i.searchCopies,'搜索落点成功复制'],[i.old180DayOpens,'打开 ≥180 天旧内容']]));s.append(group('Thought Library',[[t.searches,'搜索'],[t.searchHits,'搜索命中'],[t.topicOpens,'主题打开'],[t.repeatTopicOpens,'重复主题访问'],[t.aiViewOpens,'打开 AI整理'],[t.aiSavedEdits,'保存 AI整理修改']]));s.append(group('AI Context',[[c.builds,'生成预览'],[c.nonEmptyBuilds,'生成有效内容'],[pct(c.buildHitRate),'有效预览比例'],[c.customProfileBuilds,'使用自定义 Profile'],[c.copies,'发起复制上下文'],[c.markdownExports,'发起导出 Markdown']]));const loops=$('signals-loops');loops.replaceChildren(row('Input 搜索命中率',pct(i.searchHitRate)),row('Input 搜索落点成功复制 / 搜索结果打开',pct(i.searchCopyPerOpen)),row('Thought 重复访问 / 主题打开',pct(t.repeatOpenShare)),row('AI整理：打开 / 切回原文 / 保存编辑',`${t.aiViewOpens} / ${t.returnsToOriginal} / ${t.aiSavedEdits}`),row('Context 分享动作 / 预览生成',pct(c.sharePerBuild)),row('最近 30 天有使用信号的天数',data.activeDaysLast30));renderPassport(data);}
function renderProfiles(){const select=$('passport-profile'),profiles=memoryStatus?.profiles||[];select.replaceChildren(...profiles.map(p=>option(p.profileId,p.name)));$('passport-form').querySelector('button[type=submit]').disabled=!profiles.length;if(!profiles.length){select.append(option('','请先启用 PAIA / AI Context'));select.disabled=true;}else select.disabled=false;}
async function load(){if(busy)return;busy=true;$('signals-status').textContent='正在读取本机聚合统计…';$('signals-status').dataset.state='';try{const [data,memory]=await Promise.all([request('PAIA_PRODUCT_STATUS'),request('PAIA_MEMORY_STATUS',{options:{profileId:'default',query:'',cursor:0,limit:1}}).catch(()=>null)]);memoryStatus=memory;renderProfiles();render(data);$('signals-status').textContent=snapshot.enabled?'统计已开启，只保存在本机。':'统计当前关闭；历史聚合仍保留，除非你主动清空。';$('passport-status').textContent=memoryStatus?'Passport 只引用 AI Context Profile，不复制其中内容。':'需要先启用 PAIA，才能创建引用 AI Context Profile 的 Grant。';}catch{$('signals-status').textContent='无法读取本机工具状态。';$('signals-status').dataset.state='failed';}finally{busy=false;}}
async function revokeGrant(grantId){if(!confirm('撤销这个 Grant？以后使用它导出 Context Package 会被拒绝。'))return;try{await request('PAIA_PRODUCT_SETTINGS',{settings:{passport:{action:'revoke',grantId}}});$('passport-status').textContent='Grant 已撤销。';$('passport-status').dataset.state='saved';clearPackage();await load();}catch{$('passport-status').textContent='Grant 未能撤销，请重试。';$('passport-status').dataset.state='failed';}}
$('passport-form').addEventListener('submit',async e=>{e.preventDefault();const profileId=$('passport-profile').value;if(!profileId)return;try{await request('PAIA_PRODUCT_SETTINGS',{settings:{passport:{action:'create',consumer:$('passport-consumer').value,purpose:$('passport-purpose').value,profileId,duration:$('passport-duration').value}}});$('passport-status').textContent='Grant 已创建。它只控制 Context Package 外发，不扩大 Profile 可读取内容。';$('passport-status').dataset.state='saved';clearPackage();await load();}catch{$('passport-status').textContent='Grant 未创建。请确认 Profile 仍存在并重试。';$('passport-status').dataset.state='failed';}});
$('passport-clear-audits').addEventListener('click',async()=>{if(!confirm('清空 Passport 访问审计？Grant 本身不会被删除。'))return;try{await request('PAIA_PRODUCT_SETTINGS',{settings:{passport:{action:'clear_audits'}}});$('passport-status').textContent='访问审计已清空。';$('passport-status').dataset.state='saved';await load();}catch{$('passport-status').textContent='访问审计未清空，请重试。';$('passport-status').dataset.state='failed';}});
$('package-grant').addEventListener('change',()=>{clearPackage();$('package-status').textContent='';});
$('package-build').addEventListener('click',async()=>{const grant=activeGrants().find(g=>g.grantId===$('package-grant').value);if(!grant){$('package-status').textContent='请先创建并选择一个有效 Grant。';$('package-status').dataset.state='failed';return;}$('package-build').disabled=true;$('package-status').textContent='正在本机生成 Context Package 预览…';$('package-status').dataset.state='';try{const result=await request('PAIA_MEMORY_BUILD',{options:{profileId:grant.profileId,query:$('package-query').value,budget:$('package-budget').value}});packagePreview={...result,grantId:grant.grantId};$('package-meta').textContent=JSON.stringify(result.contextPackage,null,2);$('package-meta').hidden=false;$('package-preview').textContent=result.text||'';$('package-preview').hidden=false;$('package-actions').hidden=!result.items?.length;$('package-status').textContent=result.items?.length?'预览已生成。正文尚未导出；真正复制/导出时会再次校验 Grant。':'当前 Profile 范围内没有找到相关内容。';$('package-status').dataset.state=result.items?.length?'saved':'';}catch(e){clearPackage();$('package-status').textContent=e.code==='CONSENT_REQUIRED'?'请先启用 PAIA。':'Context Package 预览未生成，请重试。';$('package-status').dataset.state='failed';}finally{$('package-build').disabled=!activeGrants().length;}});
async function sharePackage(format){if(!packagePreview)return;const grant=activeGrants().find(g=>g.grantId===packagePreview.grantId);if(!grant){$('package-status').textContent='这个 Grant 已失效，请重新选择有效 Grant。';$('package-status').dataset.state='failed';return;}for(const id of ['package-copy','package-markdown'])$(id).disabled=true;try{const result=await request('PAIA_MEMORY_SHARE',{options:{previewId:packagePreview.previewId,format,removed:[],grantId:grant.grantId}});if(result.permissionDenied){$('package-status').textContent=result.permissionError==='MEMORY_STALE'?'预览已过期或内容已变化，请重新生成。':'Grant 已撤销、过期、被消费，或与当前 Profile 不匹配。没有向页面返回 Context 正文。';$('package-status').dataset.state='failed';await load();return;}$('package-meta').textContent=JSON.stringify(result.contextPackage,null,2);if(format==='copy'){const copied=await copyReadingText(result.text);$('package-status').textContent=copied?'Context Package 已按 Grant 复制。':'Grant 已使用；浏览器未允许直接写入剪贴板，已打开手动复制窗口。';}else{const url=URL.createObjectURL(new Blob([result.text],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='PAIA-Context-Package.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('package-status').textContent='Context Package 已按 Grant 导出为 Markdown。';}$('package-status').dataset.state='saved';await load();}catch(e){$('package-status').textContent=e.code==='MEMORY_STALE'?'预览已过期或内容已变化，请重新生成。':'导出未完成，请重试。';$('package-status').dataset.state='failed';}finally{for(const id of ['package-copy','package-markdown'])$(id).disabled=false;}}
$('package-copy').addEventListener('click',()=>void sharePackage('copy'));$('package-markdown').addEventListener('click',()=>void sharePackage('markdown'));
$('signals-enabled').addEventListener('change',async()=>{const enabled=$('signals-enabled').checked;$('signals-enabled').disabled=true;try{await request('PAIA_PRODUCT_SETTINGS',{settings:{enabled}});$('signals-status').textContent=enabled?'已开启本机聚合统计。':'已关闭本机聚合统计；既有统计仍保留。';$('signals-status').dataset.state='saved';await load();}catch{$('signals-enabled').checked=!enabled;$('signals-status').textContent='设置未保存，请重试。';$('signals-status').dataset.state='failed';}finally{$('signals-enabled').disabled=false;}});
$('signals-refresh').addEventListener('click',()=>void load());
$('signals-clear').addEventListener('click',async()=>{if(!confirm('清空本机产品统计？不会删除任何档案、思想、AI Context 设置或 Passport Grant。'))return;try{await request('PAIA_PRODUCT_CLEAR',{confirm:true});$('signals-status').textContent='本机产品统计已清空。';$('signals-status').dataset.state='saved';await load();}catch{$('signals-status').textContent='未能清空统计，请重试。';$('signals-status').dataset.state='failed';}});
$('signals-export').addEventListener('click',async()=>{try{const data=await request('PAIA_PRODUCT_STATUS'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='PAIA-local-tools-status.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('signals-status').textContent='本机状态已导出为 JSON。';$('signals-status').dataset.state='saved';}catch{$('signals-status').textContent='导出未完成，请重试。';$('signals-status').dataset.state='failed';}});
void load();
