import {request} from './common.js';
const $=id=>document.getElementById(id);
let snapshot=null,busy=false;
const pct=value=>Number.isFinite(value)?Math.round(value*100)+'%':'0%';
// Static labels + numeric values only. No product signal body is ever rendered as HTML.
function metricNode(value,label){const root=document.createElement('div');root.className='metric';const strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=String(value);span.textContent=label;root.append(strong,span);return root;}
function group(title,items){const root=document.createElement('section');root.className='group';const h=document.createElement('h3');h.textContent=title;const grid=document.createElement('div');grid.className='metric-grid';for(const [value,label]of items)grid.append(metricNode(value,label));root.append(h,grid);return root;}
function row(label,value){const root=document.createElement('div');root.className='loop-row';const a=document.createElement('span'),b=document.createElement('span');a.textContent=label;b.textContent=String(value);root.append(a,b);return root;}
function render(data){snapshot=data;$('signals-enabled').checked=data.enabled;$('signals-range').textContent=`最多保留 ${data.retentionDays} 天 · 最近 30 天有 ${data.activeDaysLast30} 个记录日`;const s=$('signals-summary');s.replaceChildren();const i=data.last30Days.input,t=data.last30Days.thought,c=data.last30Days.context;s.append(group('Input Archive',[[i.searches,'搜索'],[i.searchHits,'搜索命中'],[pct(i.searchHitRate),'搜索命中率'],[i.searchOpens,'搜索结果打开'],[i.searchCopies,'搜索落点成功复制'],[i.old180DayOpens,'打开 ≥180 天旧内容']]));s.append(group('Thought Library',[[t.searches,'搜索'],[t.searchHits,'搜索命中'],[t.topicOpens,'主题打开'],[t.repeatTopicOpens,'重复主题访问'],[t.aiViewOpens,'打开 AI整理'],[t.aiSavedEdits,'保存 AI整理修改']]));s.append(group('AI Context',[[c.builds,'生成预览'],[c.nonEmptyBuilds,'生成有效内容'],[pct(c.buildHitRate),'有效预览比例'],[c.customProfileBuilds,'使用自定义 Profile'],[c.copies,'发起复制上下文'],[c.markdownExports,'发起导出 Markdown']]));const loops=$('signals-loops');loops.replaceChildren(row('Input 搜索命中率',pct(i.searchHitRate)),row('Input 搜索落点成功复制 / 搜索结果打开',pct(i.searchCopyPerOpen)),row('Thought 重复访问 / 主题打开',pct(t.repeatOpenShare)),row('AI整理：打开 / 切回原文 / 保存编辑',`${t.aiViewOpens} / ${t.returnsToOriginal} / ${t.aiSavedEdits}`),row('Context 分享动作 / 预览生成',pct(c.sharePerBuild)),row('最近 30 天有使用信号的天数',data.activeDaysLast30));}
async function load(){if(busy)return;busy=true;$('signals-status').textContent='正在读取本机聚合统计…';$('signals-status').dataset.state='';try{render(await request('PAIA_PRODUCT_STATUS'));$('signals-status').textContent=snapshot.enabled?'统计已开启，只保存在本机。':'统计当前关闭；历史聚合仍保留，除非你主动清空。';}catch{$('signals-status').textContent='无法读取本机产品统计。';$('signals-status').dataset.state='failed';}finally{busy=false;}}
$('signals-enabled').addEventListener('change',async()=>{const enabled=$('signals-enabled').checked;$('signals-enabled').disabled=true;try{await request('PAIA_PRODUCT_SETTINGS',{settings:{enabled}});$('signals-status').textContent=enabled?'已开启本机聚合统计。':'已关闭本机聚合统计；既有统计仍保留。';$('signals-status').dataset.state='saved';await load();}catch{$('signals-enabled').checked=!enabled;$('signals-status').textContent='设置未保存，请重试。';$('signals-status').dataset.state='failed';}finally{$('signals-enabled').disabled=false;}});
$('signals-refresh').addEventListener('click',()=>void load());
$('signals-clear').addEventListener('click',async()=>{if(!confirm('清空本机产品统计？不会删除任何档案、思想或 AI Context 设置。'))return;try{await request('PAIA_PRODUCT_CLEAR',{confirm:true});$('signals-status').textContent='本机产品统计已清空。';$('signals-status').dataset.state='saved';await load();}catch{$('signals-status').textContent='未能清空统计，请重试。';$('signals-status').dataset.state='failed';}});
$('signals-export').addEventListener('click',async()=>{try{const data=await request('PAIA_PRODUCT_STATUS'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='PAIA-local-product-signals.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('signals-status').textContent='聚合统计已导出为 JSON。';$('signals-status').dataset.state='saved';}catch{$('signals-status').textContent='导出未完成，请重试。';$('signals-status').dataset.state='failed';}});
void load();
