import {request} from './common.js';

const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const signal=(name,dimensions={})=>request('PAIA_PRODUCT_SIGNAL',{signal:{name,dimensions}}).catch(()=>{});
const button=(text,className='')=>{const b=document.createElement('button');b.type='button';b.className=className;b.textContent=text;return b;};
async function waitFor(read,{attempts=80,delay=50}={}){for(let i=0;i<attempts;i++){const value=read();if(value)return value;await sleep(delay);}return null;}
const date=value=>value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric'}).format(new Date(value)):'时间未知';
const queryFor=item=>[...String(item.snippet||item.title||'').replace(/\s+/g,' ').trim()].slice(0,72).join('');

export function installRevisit(){
 if($('revisit-open'))return;const header=document.querySelector('.workspace-header');if(!header)return;
 if(!document.querySelector('link[data-revisit]')){const link=document.createElement('link');link.rel='stylesheet';link.href=chrome.runtime.getURL('ui/revisit.css');link.dataset.revisit='true';document.head.append(link);}
 const open=button('回访');open.id='revisit-open';open.setAttribute('aria-haspopup','dialog');const global=$('universal-search-open');(global||$('workspace-heading'))?.after(open);
 const dialog=document.createElement('dialog');dialog.id='revisit-dialog';dialog.setAttribute('aria-labelledby','revisit-title');const shell=document.createElement('div');shell.className='revisit-shell';
 const head=document.createElement('header'),title=document.createElement('h2'),close=button('×','revisit-close');title.id='revisit-title';title.textContent='回访';close.setAttribute('aria-label','关闭回访');head.append(title,close);
 const intro=document.createElement('p');intro.className='revisit-intro';const body=document.createElement('div');body.className='revisit-body';const footer=document.createElement('footer'),mark=button('已读到这里','primary'),status=document.createElement('span');status.className='revisit-status';status.setAttribute('role','status');footer.append(mark,status);shell.append(head,intro,body,footer);dialog.append(shell);document.body.append(dialog);
 let snapshot=null,busy=false;
 close.addEventListener('click',()=>dialog.close());dialog.addEventListener('cancel',()=>dialog.close());open.addEventListener('click',()=>void show());mark.addEventListener('click',()=>void markSeen());
 void refreshBadge();
 async function refreshBadge(){try{const s=await request('GET_STATUS');if(!s.consented){open.textContent='回访';return;}const data=await request('PAIA_REVISIT_STATUS');snapshot=data;const count=data.firstRun?0:data.newInputs.count;open.textContent=count?`回访 · ${data.newInputs.truncated?count+'+':count}`:'回访';}catch{open.textContent='回访';}}
 async function show(){if(busy)return;busy=true;status.textContent='正在读取本机变化…';try{snapshot=await request('PAIA_REVISIT_STATUS');render();if(!dialog.open)dialog.showModal();const state=snapshot.firstRun?'first':snapshot.newInputs.count||snapshot.topicUpdates.length?'new':'quiet';void signal('revisit_open',{state});status.textContent='';}catch(e){if(!dialog.open)dialog.showModal();body.replaceChildren();intro.textContent=e.code==='CONSENT_REQUIRED'?'请先完成 PAIA 的本机保存授权。':'暂时无法读取回访内容。';status.textContent='';}finally{busy=false;}}
 function render(){body.replaceChildren();if(snapshot.firstRun){intro.textContent='这是第一次打开回访。PAIA 不会把现有历史全部标成“未读”；点击“从现在开始记录”后，只计算之后新增的 Input。';mark.textContent='从现在开始记录';}else{intro.textContent=`上次记录到 ${date(snapshot.lastSeenAt)}。这里只呈现本机事实，不调用 AI，也不推断你的观点变化。`;mark.textContent='已读到这里';}
  renderNew();renderTopics();renderOld();
 }
 function section(titleText,noteText=''){const s=document.createElement('section');s.className='revisit-section';const h=document.createElement('h3');h.textContent=titleText;s.append(h);if(noteText){const p=document.createElement('p');p.className='muted';p.textContent=noteText;s.append(p);}body.append(s);return s;}
 function card(item,kind){const row=document.createElement('article');row.className='revisit-card';const main=button('','revisit-card-open'),strong=document.createElement('strong'),snippet=document.createElement('p'),small=document.createElement('small');strong.textContent=item.title||item.name||'未命名内容';snippet.textContent=item.snippet||'';small.textContent=kind==='topic'?(item.hasPresentation?`当前整理之后有 ${item.pendingEntryCount} 条思想依据新增或变化`:`有 ${item.pendingEntryCount} 条思想材料可继续阅读或整理`):`${date(item.sourceSentAt)}${item.meaningful?' · 曾被你编辑或成为 Thought 依据':''}`;main.append(strong,snippet,small);main.addEventListener('click',()=>void openItem(item,kind));row.append(main);return row;}
 function renderNew(){if(snapshot.firstRun)return;const count=snapshot.newInputs.count;if(!count)return;const s=section(`自上次回访后 · ${snapshot.newInputs.truncated?count+'+':count} 条新收录 Input`,'只计算之后新增并仍可见的 Input；轻度过滤内容不会在这里制造提醒。');for(const item of snapshot.newInputs.items)s.append(card(item,'new_input'));}
 function renderTopics(){if(!snapshot.topicUpdates.length)return;const s=section('思想主题有了新材料','这里依据现有 Thought / AI整理差异状态，不会为了回访额外调用 AI。');for(const topic of snapshot.topicUpdates)s.append(card(topic,'topic'));}
 function renderOld(){if(!snapshot.resurface.length)return;const s=section('重新看看','优先选择 90 天以上、曾被你编辑过或已经成为 Thought 依据的原始 Input；同一天保持稳定，不做随机刺激。');for(const item of snapshot.resurface)s.append(card(item,'old_input'));}
 async function markSeen(){if(!snapshot||busy)return;busy=true;mark.disabled=true;try{await request('PAIA_REVISIT_MARK',{anchor:snapshot.anchor});void signal('revisit_mark',{});status.textContent='已记录到这里。之后新增的 Input 会在下次回访显示。';await refreshBadge();snapshot=await request('PAIA_REVISIT_STATUS');render();}catch{status.textContent='未能保存回访位置，请重试。';}finally{busy=false;mark.disabled=false;}}
 async function openItem(item,kind){void signal('revisit_item_open',{kind});dialog.close();if(kind==='topic'){document.querySelector('[data-view="thoughts"]')?.click();const field=await waitFor(()=>{const el=$('thought-search');return el&&!$('thought-panel')?.hidden?el:null;});if(!field)return;field.value=item.name;field.dispatchEvent(new Event('input',{bubbles:true}));const target=await waitFor(()=>[...document.querySelectorAll('#thought-list [data-render-key]')].find(node=>{try{return JSON.parse(node.dataset.renderKey||'[]').includes(item.topicId);}catch{return false;}}),{attempts:120});target?.click();return;}
  const q=queryFor(item);if(!q)return;document.querySelector('[data-view="library"]')?.click();const field=await waitFor(()=>{const el=$('search');return el&&!$('collection-panel')?.hidden?el:null;});if(!field)return;field.value=q;field.dispatchEvent(new Event('input',{bubbles:true}));let target=null;for(let page=0;page<8&&!target;page++){target=await waitFor(()=>[...document.querySelectorAll('#document-list .search-input[data-input-id]')].find(node=>node.dataset.inputId===item.id),{attempts:25});if(target)break;const next=[...document.querySelectorAll('.pagination button')].find(node=>node.textContent.includes('下一部分')&&!node.disabled&&node.getClientRects().length);if(!next)break;next.click();await sleep(120);}target?.click();}
 }
