import {SettingsNextState} from './settings-next-state.js';
import {withSettingsControlFocus} from './settings-local-state.js';
const owners=new WeakMap();
export function mountSettingsNext(host,{send,language,storage,runtime}){
 if(owners.has(host))return owners.get(host);
 const row=document.createElement('label'),name=document.createElement('span'),toggle=document.createElement('input'),note=document.createElement('p'),status=document.createElement('p'),dialog=document.createElement('dialog'),title=document.createElement('h2'),explanation=document.createElement('p'),confirm=document.createElement('button'),cancel=document.createElement('button');
 row.className='setting';toggle.type='checkbox';toggle.id='settings-next-enabled';row.htmlFor=toggle.id;row.append(name,toggle);note.className=status.className='ux-settings-note';note.id='settings-next-explanation';status.id='settings-next-status';status.setAttribute('role','status');toggle.setAttribute('aria-describedby',note.id);dialog.id='settings-next-consent';title.id='settings-next-consent-title';dialog.setAttribute('aria-labelledby',title.id);confirm.id='settings-next-confirm';cancel.id='settings-next-cancel';confirm.type=cancel.type='button';dialog.append(title,explanation,confirm,cancel);host.prepend(row,note,status);host.append(dialog);
 const state=new SettingsNextState({send,changed:()=>sync()});
 function sync(){const zh=language()==='zh-CN',copy=(a,b)=>zh?a:b;name.textContent=copy('下一句建议','Next-input suggestions');toggle.checked=state.value?.enabled===true;toggle.disabled=!state.editable;toggle.setAttribute('aria-busy',String(state.busy));note.textContent=copy('默认关闭，仅限本次浏览器会话；与收录暂停独立。','Off by default, for this browser session only; independent of capture pause.');title.textContent=copy('开启下一句建议？','Enable next-input suggestions?');explanation.textContent=copy('仅在本机临时读取开启后新完成的当前 AI 回复。不会保存整条回复、上传或调用模型。点击建议只填入输入框，不会发送。','Temporarily read only the current AI reply completed after enabling, on this device. No full reply is saved, uploaded or sent to a model. A suggestion only fills the composer; it never sends.');confirm.textContent=copy('本次会话开启','Enable for this session');cancel.textContent=copy('取消','Cancel');const messages={'saving':['正在保存…','Saving…'],'saved':['设置已确认。','Setting confirmed.'],'read-error':['暂时无法读取。重新打开可重试。','Could not read status. Reopen to retry.'],'save-error':['保存未获确认，已重新核对状态。','Save was not confirmed. Status was checked again.'],'save-unknown':['结果无法确认。重新打开核对后再试。','Result is unknown. Reopen to check before retrying.']};status.textContent=messages[state.feedback]?.[zh?0:1]||(!state.value?copy('正在读取…','Reading…'):'');}
 toggle.addEventListener('change',e=>{const enabled=toggle.checked;sync();if(!e.isTrusted||!state.editable)return;if(enabled){dialog.showModal();cancel.focus();}else void withSettingsControlFocus(toggle,()=>state.configure(false));});
 confirm.addEventListener('click',e=>{if(!e.isTrusted)return;dialog.close();void withSettingsControlFocus(toggle,()=>state.configure(true));});cancel.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>toggle.focus({preventScroll:true}));
 storage?.onChanged?.addListener((changes,area)=>{if(area==='session'&&changes.promptNextAuthorizationV1)void state.load();});runtime?.onMessage?.addListener(message=>{if(message?.type==='PAIA_PROMPT_NEXT_CHANGED')void state.load();});
 const owner={state,sync,refresh:()=>state.load()};owners.set(host,owner);sync();void state.load();return owner;
}
