import {createLegacyTopic} from './harness/reading-closure.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
test('v092 product action hunt: keyboard dialogs, rename revision, Entry delete/Undo, Topic delete/restore and local failure',{timeout:90000},async()=>{
 const h=await FakeChatGPT.start({headless:false}),p=h.archive,consoleCounts={error:0,warning:0};p.on('console',m=>{if(m.type() in consoleCounts)consoleCounts[m.type()]++;});try{
 await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await p.locator('[data-view=thoughts]').click();await createLegacyTopic(p,'虚构操作验收');const topic=(await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'all'}})).items[0];
 await p.locator('#create-entry').click();await p.locator('[data-entry-field=body]').waitFor();const entry=p.locator('[data-entry-field=body]');await entry.fill('必须保留的合成内容');await p.locator('#topic-heading').click();const id=await entry.evaluate(el=>el.closest('[data-entry-id]').dataset.entryId);await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).body==='必须保留的合成内容');
 await p.locator('#topic-menu summary').click();await p.locator('#topic-menu').getByRole('button',{name:'重命名',exact:true}).click();await p.getByRole('textbox',{name:'主题名称',exact:true}).fill('重命名后的合成主题');await p.keyboard.press('Tab');assert.equal(await p.locator('#library-dialog').evaluate(el=>el.contains(document.activeElement)),true);await p.locator('#library-form [type=submit]').click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).name==='重命名后的合成主题');await p.locator('#revision-history').click();await p.locator('#library-dialog .revision-row').first().waitFor();await p.locator('#library-dialog .revision-row details').first().locator('summary').click();assert.match(await p.locator('#library-dialog .revision-row pre').first().textContent(),/主题|组织/);assert.doesNotMatch(await p.locator('#library-dialog .revision-row pre').first().textContent(),/sourceRecordIds|organizationRevision|fieldRevisions/);await p.keyboard.press('Escape');assert.equal(await p.locator('#library-dialog').isVisible(),false);
 const row=p.locator('[data-entry-id="'+id+'"]');await row.locator('.library-actions summary').click({timeout:5000});await row.getByRole('button',{name:'删除内容',exact:true}).click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).lifecycle==='removed');await p.locator('#notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).lifecycle==='active');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id})).body,'必须保留的合成内容');
 await p.locator('#topic-menu summary').click();await p.locator('#topic-menu').getByRole('button',{name:'删除主题',exact:true}).click();assert.match(await p.locator('#library-dialog-content').textContent(),/原始来源和版本不会删除/);await p.keyboard.press('Escape');assert.equal((await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).lifecycle,'active');await p.locator('#topic-menu summary').click();await p.locator('#topic-menu').getByRole('button',{name:'删除主题',exact:true}).click();await p.locator('#library-form [type=submit]').click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).lifecycle==='removed');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id})).body,'必须保留的合成内容');await p.locator('.sidebar [data-view=settings]').click();await p.locator('#library-management>summary').click();await p.locator('#library-removed-topics').click();await p.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).lifecycle==='active');
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);chrome.runtime.sendMessage=q=>q.type==='REBUILD_LIBRARY_SEARCH'?Promise.resolve({ok:false,error:'STORAGE_FAILURE'}):send(q);});await p.locator('#library-rebuild-search').click();await eventually(()=>p.locator('#error').isVisible());assert.match(await p.locator('#error').textContent(),/重试/);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);assert.deepEqual(consoleCounts,{error:0,warning:0});await mkdir('work/hardening-v092',{recursive:true});await writeFile('work/hardening-v092/actions.json',JSON.stringify({syntheticOnly:true,entryUndo:true,topicRestore:true,revisionReadable:true,dialogKeyboard:true,actionFailure:true,requests:0,consoleCounts,errors:h.errors},null,2));
 }catch(error){await mkdir('work/hardening-v092',{recursive:true});await p.screenshot({path:'work/hardening-v092/actions-failure.png',fullPage:true});await writeFile('work/hardening-v092/actions-failure.json',JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('.library-actions')].map(el=>{const r=el.getBoundingClientRect(),s=el.querySelector('summary'),q=s.getBoundingClientRect();return {html:el.outerHTML,rect:r.toJSON(),summary:q.toJSON(),hit:document.elementFromPoint(q.x+q.width/2,q.y+q.height/2)?.outerHTML,style:{pointer:getComputedStyle(s).pointerEvents,position:getComputedStyle(s).position},inert:!!el.closest('[inert]')};})),null,2));throw error;}finally{await h.close();}
});
