import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {AssistReplyLease} from '../background/assist-reply-lease.js';
import {LocalAssistSession} from '../core/ai-usage/local-assist-session.js';
import {validateAssistResponse} from '../core/ai-usage/assist-response.js';
import {ContextCardsService} from '../core/context-cards.js';
import {readDomainCommitEvidence} from '../core/ai-usage/domain-commit-evidence.js';
import {invalidateSemanticJobs} from '../core/ai-usage/semantic-invalidation.js';
const authority=async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_ASSIST'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}});
const suggestion=JSON.stringify({version:1,kind:'SUGGESTION',text:'Explain the next step.',condition:''});
const all=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].map(async n=>[n,await t.all(n)]))));
async function fixture({ids=[],output=suggestion}={}){
 const {s}=await setup(OrganizerStore);await s.finishFoundation();let now=1000,calls=0;
 const sender={id:'synthetic-extension',tab:{id:1},frameId:0,documentId:'synthetic-document',documentLifecycle:'active',url:'https://chatgpt.com/c/synthetic'};
 const binding={url:sender.url,conversation:'/c/synthetic',cycle:1,replyId:'reply-one',revision:1};
 const snapshot={completed:true,text:'Synthetic current completed answer.',blocks:1,excluded:false};
 const live={binding,snapshot};
 const lease=new AssistReplyLease({runtimeId:sender.id,tabs:{get:async()=>({url:sender.url,incognito:false,active:true})},probe:async(_host,{snapshot:read})=>({ready:true,binding:structuredClone(live.binding),...(read?{snapshot:structuredClone(live.snapshot)}:{})}),current:(_host,b)=>JSON.stringify(b)===JSON.stringify(live.binding),clock:()=>now});
 lease.configure({replyAccess:true,remoteProcessing:true});
 const provider={describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>{calls++;return output;}};
 const session=new LocalAssistSession(s,{lease,provider,resolveAuthority:authority,contextSelector:()=>ids,clock:()=>now});
 const cap=await lease.observe(sender);return {s,lease,session,cap,sender,live,provider,ids,calls:()=>calls,time:x=>now=x};
}
test('reply-only actual Foundation plan/dispatch/atomic result and ten activations share one result without fake Source',async()=>{const f=await fixture(),before=await all(f.s),handles=await Promise.all(Array.from({length:10},()=>f.session.prepare({lease:f.cap})));assert.equal(new Set(handles).size,1);const results=await Promise.all(handles.map(h=>f.session.run(h)));assert.equal(f.calls(),1);assert.equal(results[0].text,'Explain the next step.');const rows=await all(f.s),job=rows.organizerJobs[0];assert.equal(job.kind,'ai_assist_result_v1');assert.deepEqual(job.items,[]);assert.deepEqual(job.coverage,[]);assert.equal(job.resultCommitted,true);assert.equal(rows.organizerUsage[0].attemptCount,1);assert.equal(rows.organizerWorkItems[0].outcome,'SUGGESTION');for(const n of ['records','blocks','inputStates','thoughts','placements','documents','libraryDocuments']){assert.ok(Object.hasOwn(rows,n),n+' exists');assert.deepEqual(rows[n],before[n]);}assert.ok(!JSON.stringify(rows).includes(f.live.snapshot.text));assert.ok(!JSON.stringify(rows).includes('Explain the next step.'));assert.equal((await readDomainCommitEvidence(f.session.foundation,job.id)).status,'UNSUPPORTED');});
test('remote consent separate from reply access and caller metadata cannot mint a lease',async()=>{const f=await fixture();f.lease.configure({replyAccess:true,remoteProcessing:false});await assert.rejects(f.lease.observe(f.sender),{code:'UNAVAILABLE'});await assert.rejects(f.session.prepare({lease:{}}));f.lease.configure({replyAccess:true,remoteProcessing:true});for(const change of [{frameId:1},{documentId:''},{tab:{id:1,incognito:true}},{id:'other'},{url:'https://chatgpt.com/'}])await assert.rejects(f.lease.observe({...f.sender,...change}));assert.equal(f.calls(),0);});
test('DEFER reused and expiry/dismiss/new session cannot redispatch settled evaluation',async()=>{const f=await fixture({output:JSON.stringify({version:1,kind:'DEFER',reason:'NO_USEFUL_SUGGESTION'})}),h=await f.session.prepare({lease:f.cap});for(let i=0;i<10;i++)assert.equal((await f.session.run(h)).kind,'DEFER');assert.equal(f.calls(),1);f.session.dismiss(h);const h2=await f.session.prepare({lease:f.cap});await assert.rejects(f.session.run(h2),{code:'UNAVAILABLE'});assert.equal(f.calls(),1);f.time(301001);await assert.rejects(f.lease.observe(f.sender),{code:'STALE_BASE'});assert.equal(f.calls(),1);});
test('unknown provider outcome and malformed response never produce result or a second attempt',async()=>{for(const output of ['not JSON',JSON.stringify({version:1,kind:'SUGGESTION',text:'x'.repeat(121),condition:''})]){const f=await fixture({output}),h=await f.session.prepare({lease:f.cap});await assert.rejects(f.session.run(h),{code:'OUTCOME_UNKNOWN'});await assert.rejects(f.session.run(h),{code:'OUTCOME_UNKNOWN'});await assert.rejects(f.session.result(h),{code:'UNAVAILABLE'});assert.equal(f.calls(),1);}});
test('strict response and Unicode/aggregate byte limits reject before useful result',()=>{for(const v of [{version:1,kind:'SUGGESTION',text:'ok',condition:'',extra:true},{version:1,kind:'SUGGESTION',text:'\ud800',condition:''},{version:1,kind:'DEFER',reason:'UNKNOWN'}])assert.throws(()=>validateAssistResponse(JSON.stringify(v)));assert.equal(validateAssistResponse(JSON.stringify({version:1,kind:'SUGGESTION',text:'你'.repeat(120),condition:''})).text.length,120);});
test('newer reply and consent ABA invalidate old prepared/current results',async()=>{const f=await fixture(),h=await f.session.prepare({lease:f.cap});f.live.binding={...f.live.binding,revision:2};await assert.rejects(async()=>f.session.run(h));assert.equal(f.calls(),0);f.live.binding={...f.live.binding,revision:1};f.lease.configure({replyAccess:false,remoteProcessing:false});f.lease.configure({replyAccess:true,remoteProcessing:true});await assert.rejects(async()=>f.session.run(h));assert.equal(f.calls(),0);});
test('actual relevant Context permission/text changes invalidate, unrelated edit preserves result',async()=>{const f=await fixture(),c=new ContextCardsService(f.s),a=crypto.randomUUID(),b=crypto.randomUUID();for(const id of [a,b])await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:id,expectedRevision:0,body:'synthetic '+id,section:'Synthetic'});for(const key of ['global','info'])await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key,expectedRevision:0,enabled:true});f.ids.push(a);const h=await f.session.prepare({lease:f.cap});await f.session.run(h);await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:b,expectedRevision:1,body:'unrelated changed',section:'Synthetic'});assert.equal((await f.session.result(h)).kind,'SUGGESTION');await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:a,expectedRevision:1,body:'relevant changed',section:'Synthetic'});await assert.rejects(f.session.result(h));assert.equal(f.calls(),1);});
test('actual ACK abort rolls metadata back, same private response settles without another dispatch',async()=>{const f=await fixture(),h=await f.session.prepare({lease:f.cap}),write=f.s.foundationWrite.bind(f.s);let reject=true;f.s.foundationWrite=fn=>write(async t=>{const put=t.put.bind(t);t.put=async(n,row)=>{if(reject&&n==='organizerWorkItems'&&row.id.startsWith('aiu:assist-result:'))throw Error('synthetic ACK abort');return put(n,row);};return fn(t);});await assert.rejects(async()=>f.session.run(h));assert.equal(f.calls(),1);assert.equal((await all(f.s)).organizerWorkItems.length,0);await assert.rejects(f.session.result(h));reject=false;assert.equal((await f.session.run(h)).kind,'SUGGESTION');assert.equal(f.calls(),1);});
test('dispose during final ACK await rolls result/job settlement back',async()=>{const f=await fixture(),h=await f.session.prepare({lease:f.cap}),write=f.s.foundationWrite.bind(f.s);f.s.foundationWrite=fn=>write(async t=>{const put=t.put.bind(t);t.put=async(n,row)=>{const r=await put(n,row);if(n==='organizerWorkItems'&&row.id.startsWith('aiu:assist-result:'))f.session.dispose();return r;};return fn(t);});await assert.rejects(async()=>f.session.run(h));const rows=await all(f.s);assert.equal(rows.organizerWorkItems.length,0);assert.equal(rows.organizerUsage[0].state,'RESPONSE_RECORDED');assert.equal(rows.organizerUsage[0].attemptCount,1);});
test('generic facet and local resolution reject new kind, restore epoch denies result',async()=>{const f=await fixture(),h=await f.session.prepare({lease:f.cap}),rows=await all(f.s),j=rows.organizerJobs[0];await assert.rejects(f.session.foundation.resolveLocal(j.id,{facet:'assist',units:[]}),{code:'INVALID_REQUEST'});await assert.rejects(f.session.foundation.commitFacet(j.id,j.childIds[0],{facet:'assist',units:[]}),{code:'INVALID_REQUEST'});await f.session.run(h);await f.s.foundationWrite(t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic-restore'}));await assert.rejects(f.session.result(h));});
test('oversized complete reply is rejected rather than truncated, before a job or attempt',async()=>{const f=await fixture(),before=await all(f.s);f.live.snapshot.text='你'.repeat(3000);await assert.rejects(f.session.prepare({lease:f.cap}),{code:'RESOURCE_LIMIT'});assert.deepEqual(await all(f.s),before);assert.equal(f.calls(),0);});
test('reply access revocation during an external probe denies capability publication',async()=>{const f=await fixture(),probe=f.lease.probe;f.lease.probe=async(...args)=>{const r=await probe(...args);f.lease.configure({replyAccess:false,remoteProcessing:true});return r;};await assert.rejects(f.lease.observe(f.sender));assert.equal(f.calls(),0);});
test('clock rollback invalidates leases rather than extending private lifetime',async()=>{const f=await fixture();f.time(1);await assert.rejects(f.session.prepare({lease:f.cap}));assert.equal(f.calls(),0);});
test('scope permission revocation after settlement denies sensitive cached text',async()=>{const f=await fixture(),c=new ContextCardsService(f.s),id=crypto.randomUUID();await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:id,expectedRevision:0,body:'private context',section:'Synthetic'});for(const key of ['global','info'])await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key,expectedRevision:0,enabled:true});f.ids.push(id);const h=await f.session.prepare({lease:f.cap});await f.session.run(h);await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key:'info',expectedRevision:1,enabled:false});await assert.rejects(f.session.result(h));assert.equal(f.calls(),1);});
test('missing actual authority stays unavailable despite lease consent, and no local result is a financial claim',async()=>{const f=await fixture();f.session.foundation.resolveAuthority=null;await assert.rejects(f.session.prepare({lease:f.cap}),{code:'UNAVAILABLE'});assert.equal((await all(f.s)).organizerJobs.length,0);assert.equal(f.calls(),0);});
test('three job kinds share one bounded semantic scan; 101 rows cause zero writes',async()=>{const f=await fixture(),h=await f.session.prepare({lease:f.cap}),ai=f.session.foundation,j=(await all(f.s)).organizerJobs[0];await f.s.foundationWrite(async t=>{for(let i=0;i<100;i++)await t.put('organizerJobs',{...j,id:'synthetic-bound-'+i,dedupeKey:'synthetic-bound-'+i,kind:i<50?'ai_usage_v1':'ai_organize_atomic_v1'});await t.put('meta',{id:'gate',enabled:false,epoch:999});});const before=await all(f.s),result=await f.s.foundationWrite(t=>invalidateSemanticJobs(t));assert.equal(result.reason,'SCAN_BOUND');assert.deepEqual(await all(f.s),before);await assert.rejects(async()=>f.session.run(h));});
test('reply-only planned job is cancelled by actual gate fence despite zero dependencies',async()=>{const f=await fixture();await f.session.prepare({lease:f.cap});await f.s.foundationWrite(async t=>{const g=await t.get('meta','gate');await t.put('meta',{...g,enabled:false,epoch:g.epoch+1});await invalidateSemanticJobs(t);});assert.equal((await all(f.s)).organizerJobs[0].state,'CANCELLED_BEFORE_DISPATCH');});
test('lost private output after RESPONSE_RECORDED abort is not a free retry',async()=>{const f=await fixture(),h=await f.session.prepare({lease:f.cap}),write=f.s.foundationWrite.bind(f.s);f.s.foundationWrite=fn=>write(async t=>{const put=t.put.bind(t);t.put=async(n,row)=>{if(n==='organizerWorkItems'&&row.id.startsWith('aiu:assist-result:'))throw Error('Synthetic abort');return put(n,row);};return fn(t);});await assert.rejects(async()=>f.session.run(h));f.session.dispose();f.s.foundationWrite=write;const cold=new LocalAssistSession(f.s,{lease:f.lease,provider:f.provider,resolveAuthority:authority});const next=await cold.prepare({lease:f.cap});await assert.rejects(cold.run(next),{code:'OUTCOME_UNKNOWN'});assert.equal(f.calls(),1);assert.equal((await all(f.s)).organizerUsage[0].attemptCount,1);});
test('nine concurrent distinct reply leases are bounded after asynchronous probes',async()=>{const f=await fixture();let release;const hold=new Promise(r=>release=r);const lease=new AssistReplyLease({runtimeId:'synthetic-extension',clock:()=>1000,tabs:{get:async id=>({url:'https://chatgpt.com/c/synthetic-'+id,active:true,incognito:false})},probe:async(host)=>{await hold;return {ready:true,binding:{url:host.url,conversation:new URL(host.url).pathname,cycle:1,replyId:'reply',revision:1}};},current:()=>true});lease.configure({replyAccess:true,remoteProcessing:true});const pending=Array.from({length:9},(_,i)=>lease.observe({...f.sender,tab:{id:i},documentId:'document-'+i,url:'https://chatgpt.com/c/synthetic-'+i}));release();const results=await Promise.allSettled(pending);assert.equal(results.filter(r=>r.status==='fulfilled').length,8);assert.equal(results.find(r=>r.status==='rejected').reason.code,'RESOURCE_LIMIT');});
test('session capacity rechecked at publication for concurrent real selected Context scopes',async()=>{const f=await fixture(),c=new ContextCardsService(f.s),ids=[];for(let i=0;i<9;i++){const id=crypto.randomUUID();ids.push(id);await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:id,expectedRevision:0,body:'scope '+i,section:'Synthetic'});}for(const key of ['global','info'])await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key,expectedRevision:0,enabled:true});let index=0;const session=new LocalAssistSession(f.s,{lease:f.lease,provider:f.provider,resolveAuthority:authority,contextSelector:()=>[ids[index++]]});const results=await Promise.allSettled(Array.from({length:9},()=>session.prepare({lease:f.cap})));assert.equal(results.filter(r=>r.status==='fulfilled').length,8);assert.equal(results.find(r=>r.status==='rejected').reason.code,'RESOURCE_LIMIT');assert.equal((await all(f.s)).organizerJobs.length,8);assert.equal(f.calls(),0);});

test('revocation during tab qualification stops the next metadata or sensitive reply probe',async()=>{for(const method of ['observe','snapshot'])for(const mode of ['reply','remote','dispose']){const f=await fixture();let probes=0;const get=f.lease.tabs.get,probe=f.lease.probe;f.lease.tabs.get=async(...args)=>{const result=await get(...args);if(mode==='dispose')f.lease.dispose();else f.lease.configure({replyAccess:mode!=='reply',remoteProcessing:mode!=='remote'});return result;};f.lease.probe=async(...args)=>{probes++;return probe(...args);};await assert.rejects(method==='observe'?f.lease.observe(f.sender):f.lease.snapshot(f.cap));assert.equal(probes,0,method+' '+mode+' must deny before any next probe');assert.equal(f.calls(),0);}});

test('postcommit status await cannot publish after actual selected Context revocation',async()=>{const f=await fixture(),c=new ContextCardsService(f.s),id=crypto.randomUUID();await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:id,expectedRevision:0,body:'private selected context',section:'Synthetic'});for(const key of ['global','info'])await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key,expectedRevision:0,enabled:true});f.ids.push(id);const h=await f.session.prepare({lease:f.cap}),status=f.session.foundation.status.bind(f.session.foundation);f.session.foundation.status=async(...args)=>{const out=await status(...args);if(out.state==='COMMITTED')await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key:'info',expectedRevision:1,enabled:false});return out;};await assert.rejects(f.session.run(h));await assert.rejects(f.session.result(h));assert.equal(f.calls(),1);assert.equal((await all(f.s)).organizerUsage[0].state,'COMMITTED');});
test('actual backup replace clears Assist transient metadata and denies old private result',async()=>{const {BackupService}=await import('./harness/historical-backup.mjs'),{exported,prepared}=await import('./harness/backup-v081.mjs');const f=await fixture(),service=new BackupService(f.s),copy=await exported(service),h=await f.session.prepare({lease:f.cap});await f.session.run(h);const stage=await prepared(service,copy),preview=await service.previewRestore({sessionId:stage.sessionId,mode:'replace'});assert.equal(preview.canRestore,true);await service.restore({sessionId:stage.sessionId,confirmation:preview.integrity,mode:'replace',targetGeneration:preview.targetGeneration,confirmReplace:true});const rows=await all(f.s);assert.equal(rows.organizerJobs.length,0);assert.equal(rows.organizerUsage.length,0);await assert.rejects(f.session.result(h));await assert.rejects(f.session.run(h));assert.equal(f.calls(),1);});

test('Assist leaves real pre-existing Source, Working and human Entry bodies byte-for-byte unchanged',async()=>{const f=await fixture();await f.s.capture({epoch:(await f.s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'assist-protected-source',url:'https://chatgpt.com/c/assist-protected-source',title:'Synthetic'},messages:[{sourceMessageId:'protected-user-one',pageOrder:1,originalText:'SYNTHETIC_SOURCE_MUST_STAY'}]});await f.s.createEntry({actor:'user',body:'SYNTHETIC_HUMAN_MUST_STAY',type:'idea',formation:'explicit',evidence:[],operationId:crypto.randomUUID()});const before=await all(f.s);assert.equal(before.records.length,2);assert.equal(before.blocks.length,2);assert.equal(before.thoughts.length,1);assert.ok(before.thoughts.some(x=>x.thoughtText==='SYNTHETIC_HUMAN_MUST_STAY'));const handle=await f.session.prepare({lease:f.cap});await f.session.run(handle);const after=await all(f.s);for(const name of ['records','blocks','inputStates','thoughts','placements','documents','libraryDocuments']){assert.ok(Object.hasOwn(after,name));assert.deepEqual(after[name],before[name]);}assert.deepEqual(after.organizerJobs[0].sourceRecordIds,[]);assert.equal(f.calls(),1);});

test('actual selected Context deletion and restore ABA never revive a prepared result handle',async()=>{const f=await fixture(),c=new ContextCardsService(f.s),id=crypto.randomUUID();await c.change({kind:'put',operationId:crypto.randomUUID(),epoch:'initial',itemId:id,expectedRevision:0,body:'Synthetic relevant card',section:'Synthetic'});for(const key of ['global','info'])await c.change({kind:'access',operationId:crypto.randomUUID(),epoch:'initial',key,expectedRevision:0,enabled:true});f.ids.push(id);const handle=await f.session.prepare({lease:f.cap});await f.session.run(handle);const deletion=crypto.randomUUID();await c.change({kind:'delete',operationId:deletion,epoch:'initial',itemId:id,expectedRevision:1});await assert.rejects(f.session.result(handle));await c.change({kind:'restore',operationId:crypto.randomUUID(),epoch:'initial',itemId:id,expectedRevision:2,deletedBy:deletion});await assert.rejects(f.session.result(handle));assert.equal(f.calls(),1);});

test('inactive host tab refuses metadata/body probes even with both private consents',async()=>{for(const method of ['observe','snapshot']){const f=await fixture();let reads=0;f.lease.tabs.get=async()=>({url:f.sender.url,incognito:false,active:false});const probe=f.lease.probe;f.lease.probe=async(...args)=>{reads++;return probe(...args);};await assert.rejects(method==='observe'?f.lease.observe(f.sender):f.lease.snapshot(f.cap));assert.equal(reads,0);}});

test('host tab becoming inactive during provider await denies settlement and private publication',async()=>{const f=await fixture(),handle=await f.session.prepare({lease:f.cap}),execute=f.provider.execute;f.provider.execute=async(...args)=>{const response=await execute(...args);f.lease.tabs.get=async()=>({url:f.sender.url,incognito:false,active:false});return response;};await assert.rejects(f.session.run(handle));const rows=await all(f.s);assert.equal(rows.organizerWorkItems.length,0,'inactive tab cannot ACK a current result');assert.equal(rows.organizerUsage[0].state,'RESPONSE_RECORDED');assert.equal(rows.organizerUsage[0].attemptCount,1);await assert.rejects(f.session.result(handle));assert.equal(f.calls(),1);});
