import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,inputEdit,capture} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {AIUsageFoundation} from '../core/ai-usage/foundation.js';
const read=(s,table)=>s.repository.transaction(false,t=>t.all(table));
async function fixture(){const f=await setup(OrganizerStore),ai=new AIUsageFoundation(f.s);
 ai.resolveAuthority=async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_MAINTENANCE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}});
 const {items}=await ai.collect(),job=await ai.plan({type:'AI_MAINTENANCE',intent:'maintenance',items,coverage:items.map(i=>({key:i.key,facet:'topic',scope:'synthetic'})),contractVersion:'synthetic',routeVersion:'synthetic'});return {...f,ai,job,input:items[0].descriptor.entityId};}
test('actual Working Input edit cancels the existing never-dispatched job atomically',async()=>{const f=await fixture();await inputEdit(f.s,f.input,{libraryText:'Synthetic genuinely changed'});assert.equal((await f.ai.status(f.job.id)).state,'CANCELLED_BEFORE_DISPATCH');assert.equal((await read(f.s,'organizerWorkItems')).some(x=>x.state==='ACKNOWLEDGED'),false);});
test('dispatched synthetic attempt remains unknown and retains reservation after real edit',async()=>{const f=await fixture();await f.ai.reserve(f.job.id,{reservationId:'synthetic'});await f.ai.dispatch(f.job.id,f.job.childIds[0],{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>({accepted:true,operationReceiptId:'synthetic'})});await inputEdit(f.s,f.input,{libraryText:'Synthetic changed after response'});const r=await f.ai.status(f.job.id);assert.equal(r.state,'EXPIRED_UNCOMMITTED');assert.equal(r.attempts[0].spendState,'RESERVATION_RETAINED');assert.equal(r.attempts[0].attemptCount,1);});
test('duplicate capture and unrelated metadata do not change an existing job',async()=>{const f=await fixture(),before=await f.ai.status(f.job.id);await f.s.capture(capture((await f.s.status()).epoch));await f.s.foundationWrite(t=>t.put('meta',{id:'synthetic-cosmetic',value:1}));assert.deepEqual(await f.ai.status(f.job.id),before);});

import {invalidateSemanticJobs} from '../core/ai-usage/semantic-invalidation.js';
test('101 active jobs overflow leaves every job and receipt untouched and current still rejects stale work',async()=>{const f=await fixture(),original=(await read(f.s,'organizerJobs')).find(x=>x.id===f.job.id);await f.s.foundationWrite(async t=>{for(let i=0;i<100;i++)await t.put('organizerJobs',{...original,id:'synthetic-job-'+i,dedupeKey:'synthetic-'+i});});const before=await read(f.s,'organizerJobs');await inputEdit(f.s,f.input,{libraryText:'Synthetic overflow changed'});assert.deepEqual(await read(f.s,'organizerJobs'),before);const result=await f.s.repository.transaction(false,invalidateSemanticJobs);assert.deepEqual(result,{status:'INCOMPLETE',reason:'SCAN_BOUND',checked:0,cancelled:0});await assert.rejects(f.ai.reserve(f.job.id,{reservationId:'synthetic'}),e=>e.code==='STALE_BASE');});
test('at most 100 actual indexed jobs are examined; ordinary zero-job capture has no job writes',async()=>{const f=await fixture(),original=(await read(f.s,'organizerJobs')).find(x=>x.id===f.job.id);await f.s.foundationWrite(async t=>{for(let i=0;i<99;i++)await t.put('organizerJobs',{...original,id:'synthetic-job-'+i,dedupeKey:'synthetic-'+i});});const before={...f.s.repository.metrics},start=performance.now();await inputEdit(f.s,f.input,{libraryText:'Synthetic maximum changed'});const after=f.s.repository.metrics;assert.equal((await read(f.s,'organizerJobs')).filter(j=>j.state==='CANCELLED_BEFORE_DISPATCH').length,100);console.log('SYNTHETIC_INVALIDATION_COST',JSON.stringify({jobs:100,reads:after.reads-before.reads,writes:after.writes-before.writes,elapsedMs:performance.now()-start}));const g=await setup(OrganizerStore);await g.s.finishFoundation();const b={...g.s.repository.metrics},time=performance.now();await g.s.capture(capture((await g.s.status()).epoch,'synthetic-next','Synthetic new capture'));console.log('SYNTHETIC_CAPTURE_COST',JSON.stringify({jobs:0,reads:g.s.repository.metrics.reads-b.reads,writes:g.s.repository.metrics.writes-b.writes,elapsedMs:performance.now()-time}));assert.equal((await read(g.s,'organizerJobs')).filter(j=>j.kind==='ai_usage_v1').length,0);});
test('semantic cancellation write failure rolls the real canonical edit and all jobs back',async()=>{const f=await fixture(),rows=await read(f.s,'inputStates'),jobs=await read(f.s,'organizerJobs');await assert.rejects(f.s.foundationWrite(async t=>{const put=t.put.bind(t);t.put=async(table,row)=>{if(table==='organizerJobs')throw Error('synthetic cancellation failure');return put(table,row);};await t.put('inputStates',{...rows[0],contentRevision:rows[0].contentRevision+1});}));assert.deepEqual(await read(f.s,'inputStates'),rows);assert.deepEqual(await read(f.s,'organizerJobs'),jobs);});
test('trusted restore epoch changes cancel a never-dispatched job without provider authority',async()=>{const f=await fixture();await f.s.foundationWrite(t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic-new-restore'}));assert.equal((await f.ai.status(f.job.id)).state,'CANCELLED_BEFORE_DISPATCH');});
test('missing known rows and unavailable authority are not proof of semantic invalidation',async()=>{const f=await fixture(),job=(await read(f.s,'organizerJobs')).find(j=>j.id===f.job.id);await f.s.foundationWrite(t=>t.delete('meta','aiu:delta:known:'+job.items[0].key));const result=await f.s.repository.transaction(false,invalidateSemanticJobs);assert.equal(result.cancelled,0);assert.equal((await f.ai.status(job.id)).state,'PLANNED');});
test('a true unknown outcome retains reservation and is not repeatedly recancelled',async()=>{const f=await fixture();await f.ai.reserve(f.job.id,{reservationId:'synthetic'});await f.ai.dispatch(f.job.id,f.job.childIds[0],{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>{throw Error('synthetic interrupted');}});await inputEdit(f.s,f.input,{libraryText:'Synthetic unknown edit'});const before=await f.ai.status(f.job.id);assert.equal(before.state,'OUTCOME_UNKNOWN');assert.equal(before.attempts[0].spendState,'RESERVATION_RETAINED');await inputEdit(f.s,f.input,{libraryText:'Synthetic newer edit'});assert.deepEqual(await f.ai.status(f.job.id),before);});
test('unrelated and duplicate writes never scan the active job index',async()=>{const f=await fixture(),original=f.s.repository.transaction.bind(f.s.repository);let scans=0;f.s.repository.transaction=(write,fn,...rest)=>original(write,async t=>{const range=t.rangePage.bind(t);t.rangePage=async(...args)=>{if(args[0]==='organizerJobs'&&args[1]==='byMaintenance')scans++;return range(...args);};return fn(t);},...rest);await f.s.capture(capture((await f.s.status()).epoch));await f.s.foundationWrite(t=>t.put('meta',{id:'synthetic-display',value:true}));assert.equal(scans,0);await inputEdit(f.s,f.input,{libraryText:'Synthetic real semantic edit'});assert.equal(scans,2);});
test('invalidation read error is propagated and cannot become a successful canonical mutation',async()=>{const f=await fixture(),before=await read(f.s,'inputStates');await assert.rejects(f.s.foundationWrite(async t=>{const get=t.get.bind(t);t.get=async(table,id)=>{if(table==='meta'&&id==='recovery-restore-epoch')throw Error('synthetic read failure');return get(table,id);};await t.put('inputStates',{...before[0],contentRevision:before[0].contentRevision+1});}));assert.deepEqual(await read(f.s,'inputStates'),before);assert.equal((await f.ai.status(f.job.id)).state,'PLANNED');});
test('a committed local child receipt survives cancellation of an unfinished sibling',async()=>{const f=await setup(OrganizerStore),ai=new AIUsageFoundation(f.s,{resolveAuthority:async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_MAINTENANCE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}}),committers:{topic:async(_t,r)=>({committed:true,coverage:r.units})}}),{items}=await ai.collect(),topic=items.map(i=>({key:i.key,facet:'topic',scope:'synthetic'})),context=items.map(i=>({key:i.key,facet:'context',scope:'synthetic'})),job=await ai.plan({type:'AI_MAINTENANCE',intent:'maintenance',items,coverage:[...topic,...context],children:[topic,context],contractVersion:'synthetic',routeVersion:'synthetic'});await ai.resolveLocal(job.id,{facet:'topic',units:topic});const before=(await ai.status(job.id)).attempts.find(r=>r.state==='COMMITTED');assert.ok(before);await inputEdit(f.s,items[0].descriptor.entityId,{libraryText:'Synthetic changed after local child'});const after=await ai.status(job.id);assert.deepEqual(after.attempts.find(r=>r.id===before.id),before);assert.equal(after.state,'CANCELLED_BEFORE_DISPATCH');assert.deepEqual(after.committedCoverage,(await read(f.s,'organizerWorkItems')).filter(r=>r.state==='ACKNOWLEDGED').map(r=>JSON.stringify([r.unit.key,r.unit.facet,r.unit.scope])));});
test('a durable dispatch fence with missing receipt is not proof of a never-dispatched child',async()=>{const f=await fixture();await f.s.foundationWrite(t=>t.put('meta',{id:'aiu:dispatched:'+f.job.childIds[0],version:1,jobId:f.job.id,childId:f.job.childIds[0]}));const before=await f.ai.status(f.job.id);await inputEdit(f.s,f.input,{libraryText:'Synthetic changed incomplete receipt'});assert.deepEqual(await f.ai.status(f.job.id),before);const result=await f.s.repository.transaction(false,async t=>{const key=(await t.get('organizerJobs',f.job.id)).items[0].key;return invalidateSemanticJobs(t,new Map([[key,await t.get('meta','aiu:delta:known:'+key)]]));});assert.equal(result.status,'INCOMPLETE');assert.equal(result.unsupported,1);});
test('100 legitimate scoped Organize plans do not reread unchanged evidence for each job on capture',async()=>{const f=await setup(OrganizerStore),epoch=(await f.s.status()).epoch;for(let i=1;i<100;i++)await f.s.capture(capture(epoch,'synthetic-bound-'+i,'Synthetic distinct evidence '+i));const ai=new AIUsageFoundation(f.s,{resolveAuthority:async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_ORGANIZE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}})}),{items}=await ai.collect({limit:100});assert.equal(items.length,100);for(let i=0;i<100;i++)await ai.plan({type:'AI_ORGANIZE',intent:'explicit',items,coverage:items.map(item=>({key:item.key,facet:'organize',scope:'synthetic-scope-'+i})),contractVersion:'synthetic',routeVersion:'synthetic'});const before=await read(f.s,'organizerJobs'),base=f.s.repository.metrics.reads;await f.s.capture(capture(epoch,'synthetic-unrelated','Synthetic new unrelated evidence'));assert.ok(f.s.repository.metrics.reads-base<500,'a capture must not perform 100x100 unrelated evidence reads');assert.deepEqual(await read(f.s,'organizerJobs'),before);await inputEdit(f.s,items[0].descriptor.entityId,{libraryText:'Synthetic shared evidence changed'});assert.equal((await read(f.s,'organizerJobs')).filter(j=>j.state==='CANCELLED_BEFORE_DISPATCH').length,100);});
