import test from 'node:test';import assert from 'node:assert/strict';
import {FixtureAtomicReservation} from '../core/ai-usage/atomic-reservation.js';
import {ROUTE_FIELDS} from '../core/ai-usage/ratebook.js';
import {evaluateAdmission} from '../core/ai-usage/admission-policy.js';
// Synthetic shared transactional service; no real signed entitlement or billing.
function fixture(){let data=new Map(),queue=Promise.resolve(),abort=false,now=100000;
 const transact=fn=>{const run=queue.then(async()=>{const pending=structuredClone(data),value=await fn({get:async k=>structuredClone(pending.get(k)),put:async(k,v)=>pending.set(k,structuredClone(v))});if(abort){abort=false;throw Error('SYNTHETIC_ABORT');}data=pending;return value;});queue=run.catch(()=>{});return run;};
 const route=Object.fromEntries(ROUTE_FIELDS.map(k=>[k,'SYNTHETIC_'+k]));route.currency='USD';
 const controls={authorized:true,verifiedServiceFacts:true,tier:'free',routeQualified:true,thinkingBoundQualified:true,inputBoundQualified:true,global:{dayLimitMicros:15000,monthLimitMicros:15000}};
 const verify=async(request,time)=>({...controls,request,route,book:{route,rates:{standardInput:1000000,cachedReadInput:1000000,cacheCreateInput:1000000,completion:1000000},effectiveAt:0,verifiedAt:time,expiresAt:time+1000,source:'SYNTHETIC tariff',verified:true,inputBand:{minInclusive:0,maxInclusive:16000}}});
 const make=()=>new FixtureAtomicReservation({transact,verify,clock:()=>now});return {make,controls,transact,verify,clock:()=>now,setNow:v=>now=v,abort:()=>abort=true,rows:()=>structuredClone([...data.values()].flatMap(x=>x.rows))};}
const request=(id='one',patch={})=>({operationId:id,jobId:'job-'+id,principalId:'principal',libraryId:'library',scopeFingerprint:'opaque-scope',contractVersion:'contract1',routeVersion:'route1',consentEpoch:'epoch1',jobType:'AI_ORGANIZE',childIndex:0,childCount:1,inputTokens:1000,outputCap:6000,maxCompletionTokens:5990,...patch});
test('missing verifier, forged authority and wrong request proof fail closed',async()=>{const f=fixture();await assert.rejects(new FixtureAtomicReservation({transact:f.transact,clock:f.clock}).reserve(request()));for(const patch of [{authorized:false},{verifiedServiceFacts:false},{tier:'forged'}]){Object.assign(f.controls,patch);await assert.rejects(f.make().reserve(request()));Object.assign(f.controls,{authorized:true,verifiedServiceFacts:true,tier:'free'});}await assert.rejects(new FixtureAtomicReservation({transact:f.transact,clock:f.clock,verify:async(r,n)=>({...await f.verify(r,n),request:{...r,principalId:'other'}})}).reserve(request()));assert.equal(f.rows().length,0);});
test('independent instances atomically compete across principals without overselling',async()=>{const f=fixture(),out=await Promise.allSettled([f.make().reserve(request('a')),f.make().reserve(request('b')),f.make().reserve(request('c',{principalId:'other'}))]);assert.equal(out.filter(x=>x.status==='fulfilled').length,2);assert.equal(f.rows().reduce((n,r)=>n+r.reservationMicros,0),14000);assert.ok(out.filter(x=>x.status==='fulfilled').every(x=>x.value.dispatchAllowed===false));});
test('concurrent operation replay and reconstructed owner reserve exactly once',async()=>{const f=fixture(),r=request(),out=await Promise.all([f.make().reserve(r),f.make().reserve(r)]);assert.deepEqual(out[0],out[1]);assert.deepEqual(await f.make().reserve(r),out[0]);assert.equal(f.rows().length,1);await assert.rejects(f.make().reserve({...r,inputTokens:1001}),/OPERATION_REBOUND/);});
test('transaction abort rolls back reservation and clock watermark',async()=>{const f=fixture();f.abort();await assert.rejects(f.make().reserve(request()),/SYNTHETIC_ABORT/);assert.equal(f.rows().length,0);f.setNow(99999);await f.make().reserve(request());assert.equal(f.rows().length,1);});
test('trusted clock rollback fails after reconstructed owner without mutation',async()=>{const f=fixture();await f.make().reserve(request());const before=f.rows();f.setNow(99999);await assert.rejects(f.make().reserve(request('two')),/CLOCK_ROLLBACK/);assert.deepEqual(f.rows(),before);});
test('unknown survives 24h and 30d and blocks replacement/sibling attempts',async()=>{const f=fixture(),r=request('one',{childCount:2});await f.make().reserve(r);await f.make().record(r,'DISPATCHED');await f.make().record(r,'OUTCOME_UNKNOWN');f.setNow(100000+31*86400000);assert.equal((await f.make().reserve(r)).state,'OUTCOME_UNKNOWN');await assert.rejects(f.make().reserve({...r,operationId:'replacement'}),/CHILD_ALREADY_RESERVED/);await assert.rejects(f.make().reserve({...r,operationId:'sibling',childIndex:1}),/OUTCOME_OR_ATTEMPT_PENDING/);await f.make().reserve(request('two'));await assert.rejects(f.make().reserve(request('three')),/BUDGET_OR_QUOTA/);assert.equal(f.rows()[0].reservationMicros,7000);});
test('pre-dispatch cancel releases occupancy but cannot remint same child',async()=>{const f=fixture(),r=request();await f.make().reserve(r);await f.make().record(r,'CANCELLED_BEFORE_DISPATCH');assert.equal((await f.make().reserve(r)).state,'CANCELLED_BEFORE_DISPATCH');await assert.rejects(f.make().reserve({...r,operationId:'replacement'}),/CHILD_ALREADY_RESERVED/);await f.make().reserve(request('two'));await f.make().reserve(request('three'));assert.equal(f.rows().length,3);});
test('post-dispatch cancel and unknown-to-dispatch/settlement cannot release spend',async()=>{const f=fixture(),r=request();await f.make().reserve(r);await f.make().record(r,'DISPATCHED');await assert.rejects(f.make().record(r,'CANCELLED_BEFORE_DISPATCH'));await f.make().record(r,'OUTCOME_UNKNOWN');await assert.rejects(f.make().record(r,'DISPATCHED'));await assert.rejects(f.make().record(r,'SETTLED'));assert.equal(f.rows()[0].state,'OUTCOME_UNKNOWN');});
test('child slots bind job authority and share one provisional result',async()=>{const f=fixture();f.controls.global={dayLimitMicros:1000000,monthLimitMicros:1000000};const a=request('a',{childCount:4});await f.make().reserve(a);for(const patch of [{principalId:'other'},{libraryId:'other'},{consentEpoch:'other'},{scopeFingerprint:'other'},{childCount:2}])await assert.rejects(f.make().reserve({...a,operationId:'b',childIndex:1,...patch}),/JOB_REBOUND/);for(let childIndex=1;childIndex<4;childIndex++)await f.make().reserve({...a,operationId:'child'+childIndex,childIndex});assert.equal(f.rows().length,4);await assert.rejects(f.make().reserve({...a,operationId:'overflow',childIndex:4}));});
test('new operation/library does not evade result cap; local/cache still work',async()=>{const f=fixture();f.controls.global={dayLimitMicros:1000000,monthLimitMicros:1000000};for(let i=0;i<3;i++)await f.make().reserve(request('r'+i));await assert.rejects(f.make().reserve(request('r3',{libraryId:'other'})),/BUDGET_OR_QUOTA/);assert.equal(evaluateAdmission({authorized:true,intent:'local'}).decision,'local');assert.equal(evaluateAdmission({authorized:true,intent:'cache',exactCurrentCache:true}).decision,'cache_hit');});
test('unset allowance and unqualified bounds leave no reservation',async()=>{for(const patch of [{global:{dayLimitMicros:0,monthLimitMicros:15000}},{routeQualified:false},{inputBoundQualified:false},{thinkingBoundQualified:false}]){const f=fixture();Object.assign(f.controls,patch);await assert.rejects(f.make().reserve(request()));assert.equal(f.rows().length,0);}});
test('receipt stores exact metadata/quote and rejects bodies; caller mutation cannot rebind',async()=>{const f=fixture(),r=request();await f.make().reserve(r);r.principalId='mutated';const row=f.rows()[0];assert.equal(row.request.principalId,'principal');assert.equal(row.quote.pricingVersion,'SYNTHETIC_pricingVersion');assert.equal(row.quote.nativeMicros,7000);await assert.rejects(f.make().reserve({...request('two'),promptBody:'not allowed'}));});

test('already reserved sibling cannot dispatch past an unknown child',async()=>{const f=fixture(),a=request('a',{childCount:2}),b={...a,operationId:'b',childIndex:1};await f.make().reserve(a);await f.make().reserve(b);await f.make().record(a,'DISPATCHED');await f.make().record(a,'OUTCOME_UNKNOWN');await assert.rejects(f.make().record(b,'DISPATCHED'),/OUTCOME_OR_ATTEMPT_PENDING/);assert.equal(f.rows()[1].state,'RESERVED');});
