import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {readDomainCommitEvidence} from '../core/ai-usage/domain-commit-evidence.js';
import {AIUsageFoundation} from '../core/ai-usage/foundation.js';
const rows=(s,table)=>s.repository.transaction(false,t=>t.all(table));
async function fixture(){const {s}=await setup(OrganizerStore);const ai=new AIUsageFoundation(s,{resolveAuthority:async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_ORGANIZE','AI_MAINTENANCE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}}),committers:{organize:async(_t,r)=>({committed:true,coverage:r.units})}});const {items}=await ai.collect();const request={type:'AI_ORGANIZE',intent:'explicit',items,coverage:items.map(i=>({key:i.key,facet:'organize',scope:'synthetic-topic'})),contractVersion:'synthetic',routeVersion:'synthetic'};return {s,ai,request};}
async function style(s,value){const p=await s.aiStylePreference();await s.updatePreferences({aiOrganizeStyle:{version:1,value,expectedRevision:p.revision,expectedEpoch:p.epoch}});return binding(s);}
async function binding(s){const p=await s.aiStylePreference();return {version:1,value:p.value,policyVersion:'AIOS-1.0',expectedRevision:p.revision,expectedEpoch:p.epoch};}
test('actual plan admits explicit current style and persists separate semantic and execution binding',async()=>{const {s,ai,request}=await fixture();const organizeStyle=await style(s,'original'),j=await ai.plan({...request,organizeStyle}),saved=(await rows(s,'organizerJobs')).find(r=>r.id===j.id);assert.deepEqual(saved.organizeStyle,organizeStyle);assert.equal(typeof saved.organizeSemanticKey,'string');});
test('A to B to A cannot revive the first job but preserves semantic equality',async()=>{const {s,ai,request}=await fixture();const a=await ai.plan({...request,organizeStyle:await style(s,'original')});await style(s,'concise');await style(s,'original');await assert.rejects(ai.reserve(a.id,{reservationId:'synthetic'}),e=>e.code==='STALE_BASE');const next=await ai.plan({...request,organizeStyle:await binding(s)});assert.notEqual(next.id,a.id);const jobs=await rows(s,'organizerJobs');assert.equal(jobs.find(j=>j.id===a.id).organizeSemanticKey,jobs.find(j=>j.id===next.id).organizeSemanticKey);});
test('A acknowledgement never satisfies B and legacy acknowledgement is not overwritten',async()=>{const {s,ai,request}=await fixture();const legacy=await ai.plan(request);await ai.resolveLocal(legacy.id,{facet:'organize',units:request.coverage});const originalRows=await rows(s,'organizerWorkItems');for(const value of ['original','concise']){const j=await ai.plan({...request,organizeStyle:await style(s,value)});assert.equal(j.state,'PLANNED');await ai.resolveLocal(j.id,{facet:'organize',units:request.coverage});}const all=await rows(s,'organizerWorkItems');assert.equal(all.length,originalRows.length+2);assert.deepEqual(all.find(r=>r.id===originalRows[0].id),originalRows[0]);});
test('real preference update between preparation and write rejects without creating a job',async()=>{const {s,ai,request}=await fixture(),organizeStyle=await binding(s),write=ai.write.bind(ai);ai.write=async fn=>{await style(s,'concise');return write(fn);};await assert.rejects(ai.plan({...request,organizeStyle}),e=>e.code==='STALE_BASE');assert.deepEqual(await rows(s,'organizerJobs'),[]);});
test('real restore epoch change between preparation and write rejects',async()=>{const {s,ai,request}=await fixture(),organizeStyle=await binding(s),write=ai.write.bind(ai);ai.write=async fn=>{await s.foundationWrite(t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic-restored'}));return write(fn);};await assert.rejects(ai.plan({...request,organizeStyle}),e=>e.code==='STALE_BASE');assert.deepEqual(await rows(s,'organizerJobs'),[]);});
test('style change after a recorded response refuses commit without acknowledgement',async()=>{const {s,ai,request}=await fixture(),j=await ai.plan({...request,organizeStyle:await binding(s)});await ai.reserve(j.id,{reservationId:'synthetic'});await ai.dispatch(j.id,j.childIds[0],{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>({accepted:true,operationReceiptId:'synthetic'})});const before=await ai.status(j.id);await style(s,'concise');await assert.rejects(ai.commitFacet(j.id,j.childIds[0],{facet:'organize',units:request.coverage}),e=>e.code==='STALE_BASE');assert.deepEqual(await ai.status(j.id),before);assert.deepEqual(await rows(s,'organizerWorkItems'),[]);});
test('committer pending-control mutation and domain writes roll back together',async()=>{const {s,ai,request}=await fixture(),organizeStyle=await binding(s),j=await ai.plan({...request,organizeStyle}),before=await s.aiStylePreference();ai.committers={organize:async(t,r)=>{const c=await s.control(t);c.preferences.aiOrganizeStyle={version:1,value:'concise',revision:1,explicit:true};await s.saveControl(t,c);await t.put('meta',{id:'synthetic-domain-effect',value:1});return {committed:true,coverage:r.units};}};await assert.rejects(ai.resolveLocal(j.id,{facet:'organize',units:request.coverage}),e=>e.code==='STALE_BASE');assert.deepEqual(await s.aiStylePreference(),before);assert.equal((await rows(s,'meta')).some(r=>r.id==='synthetic-domain-effect'),false);assert.deepEqual((await ai.status(j.id)).attempts,[]);});
test('unknown or malformed style and non-Organize use are rejected without writes',async()=>{const {s,ai,request}=await fixture(),b=await binding(s);for(const organizeStyle of [{...b,value:'future'},{...b,version:2},{...b,policyVersion:'future'},{...b,extra:true},null])await assert.rejects(ai.plan({...request,organizeStyle}));await assert.rejects(ai.plan({...request,type:'AI_MAINTENANCE',intent:'maintenance',organizeStyle:b}));assert.deepEqual(await rows(s,'organizerJobs'),[]);});
test('style semantic identity varies by contract and route; singleflight remains Topic scoped',async()=>{const {s,ai,request}=await fixture(),organizeStyle=await binding(s),j=await ai.plan({...request,organizeStyle});await assert.rejects(ai.plan({...request,organizeStyle,routeVersion:'different'}),e=>e.code==='REQUEST_ALREADY_IN_FLIGHT');await ai.cancel(j.id);const next=await ai.plan({...request,organizeStyle,routeVersion:'different'});const all=await rows(s,'organizerJobs');assert.notEqual(all.find(r=>r.id===j.id).organizeSemanticKey,all.find(r=>r.id===next.id).organizeSemanticKey);assert.equal(all.find(r=>r.id===j.id).flightId,all.find(r=>r.id===next.id).flightId);});
test('legacy jobs remain unqualified rather than being assigned the default style',async()=>{const {s,ai,request}=await fixture(),j=await ai.plan(request),saved=(await rows(s,'organizerJobs')).find(r=>r.id===j.id);assert.equal(Object.hasOwn(saved,'organizeStyle'),false);assert.equal(Object.hasOwn(saved,'organizeSemanticKey'),false);});
test('authority await cannot hide a same-transaction preference change from current',async()=>{const {s,ai,request}=await fixture(),j=await ai.plan({...request,organizeStyle:await binding(s)}),original=ai.resolveAuthority;ai.resolveAuthority=async(t,r)=>{const c=await s.control(t);c.preferences.aiOrganizeStyle={version:1,value:'concise',revision:1,explicit:true};await s.saveControl(t,c);return original(t,r);};await assert.rejects(ai.reserve(j.id,{reservationId:'synthetic'}),e=>e.code==='STALE_BASE');assert.equal((await s.aiStylePreference()).value,'balanced');assert.deepEqual((await ai.status(j.id)).attempts,[]);});
async function response(ai,j){await ai.reserve(j.id,{reservationId:'synthetic'});await ai.dispatch(j.id,j.childIds[0],{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>({accepted:true,operationReceiptId:'synthetic'})});}
test('styled DEFER ignores legacy ACK and archives only after matching styled ACK',async()=>{const {s,ai,request}=await fixture(),legacy=await ai.plan(request);await ai.resolveLocal(legacy.id,{facet:'organize',units:request.coverage});const j=await ai.plan({...request,organizeStyle:await binding(s)});await response(ai,j);await ai.commitFacet(j.id,j.childIds[0],{facet:'organize',units:request.coverage,outcome:'DEFER',retryCondition:'synthetic'});assert.equal((await ai.archiveObsoleteDeferred()).archived,0);await ai.commitFacet(j.id,j.childIds[0],{facet:'organize',units:request.coverage});assert.equal((await ai.archiveObsoleteDeferred()).archived,1);});
test('B style ACK never archives A style DEFER',async()=>{const {s,ai,request}=await fixture(),a=await ai.plan({...request,organizeStyle:await style(s,'original')});await response(ai,a);await ai.commitFacet(a.id,a.childIds[0],{facet:'organize',units:request.coverage,outcome:'DEFER',retryCondition:'synthetic'});await ai.cancel(a.id);const b=await ai.plan({...request,organizeStyle:await style(s,'concise')});await ai.resolveLocal(b.id,{facet:'organize',units:request.coverage});assert.equal((await ai.archiveObsoleteDeferred()).archived,0);});

test('domain evidence reader uses styled acknowledgement namespace after local completion',async()=>{const {s,ai,request}=await fixture(),j=await ai.plan({...request,organizeStyle:await binding(s)});await ai.resolveLocal(j.id,{facet:'organize',units:request.coverage});assert.equal((await readDomainCommitEvidence(ai,j.id)).status,'NO_EFFECTIVE_RESULT');});
