import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {LocalOrganizeSession} from '../core/organizer/local-organize-session.js';
import {aiPresentationStatus} from '../core/organizer/ai-presentation.js';
import {aiCandidateKey} from '../core/organizer/ai-candidate.js';
import {qualifiedCoverageId} from '../core/ai-usage/assist-intent-binding.js';
import {validIncrementalV3} from '../core/organizer/ai-incremental-v3.js';
import {applyPreferenceChanges} from '../core/workspace.js';
import {readAIStyle} from '../core/ai-organize-style-preference.js';
const profile={contractVersion:'synthetic-multi-cache',modelVersion:'synthetic-no-model',promptVersion:'synthetic-multi-cache'};
const authority=async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_ORGANIZE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}});
const rows=(s,name)=>s.run(()=>s.repository.transaction(false,t=>t.all(name)));
const state=f=>aiPresentationStatus(f.s,{topicId:f.topic.id},profile).then(x=>x.topics[0]);
const saved=f=>f.s.run(()=>f.s.repository.transaction(false,t=>t.get('meta','aiPresentation:'+f.topic.id)));
const reopen=(f,options={})=>new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3,...options});
async function fixture(children=2,style='balanced',{beforeRun=null,afterFailure=null}={}){
 const {s,storage,indexedDB}=await setup(OrganizerStore),topic=await s.createTopic({name:'SYNTHETIC multi cache',operationId:crypto.randomUUID()});
 if(style!=='balanced'){const p=await s.aiStylePreference();await s.updatePreferences({aiOrganizeStyle:{version:1,value:style,expectedRevision:p.revision,expectedEpoch:p.epoch}});}
 const entries=[];for(let i=0;i<children*20;i++){const e=await s.createEntry({actor:'user',operationId:crypto.randomUUID(),body:'SYNTHETIC exact evidence '+i,type:'idea',formation:'explicit',evidence:[]});await s.placeEntry({topicId:topic.id,entryId:e.id,expectedEntryRevision:e.revision,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision,operationId:crypto.randomUUID()});entries.push(e);}
 const f={s,storage,indexedDB,topic,entries,children,calls:0};f.session=reopen(f);f.handle=await f.session.prepare({topicId:topic.id,children});
 f.provider={describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async r=>{f.calls++;return {version:2,blocks:r.inputs.map(i=>({field:'currentView',text:i.text,evidenceEntryIds:[i.ref],sourceSpans:[{entryId:i.ref,revision:i.revision,start:0,end:i.text.length}]}))};}};
 if(beforeRun)await beforeRun(f);
 if(afterFailure){await assert.rejects(f.session.run(f.handle,f.provider),{code:'STORAGE_FAILED'});await afterFailure(f);}else assert.equal((await f.session.run(f.handle,f.provider)).state,'COMMITTED');
 f.candidate=(await state(f)).candidate;assert.equal(f.candidate.schemaVersion,4);assert.equal(f.candidate.baseKind,'none');return f;
}
function edit(f,decisions=Object.fromEntries(f.candidate.changedFields.map(k=>[k,'adopt']))){return {topicId:f.topic.id,expectedRevision:f.candidate.expectedRevision,expectedCandidateKey:aiCandidateKey(f.candidate),candidateDecisions:decisions,operationId:crypto.randomUUID()};}
const adopt=(f,decisions)=>f.s.editAIPresentation(edit(f,decisions));
const counters=f=>f.s.run(()=>f.s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(f.s.repository.stores.map(async n=>[n,await t.all(n)])))));
function intercept(s,{get=null,put=null}={}){const original=s.repository.transaction.bind(s.repository);s.repository.transaction=(write,run,...rest)=>original(write,async t=>run(new Proxy(t,{get(target,key){if(key==='get'&&get)return async(table,id)=>get({write,table,id,value:await target.get(table,id),target});if(key==='put'&&put)return async(table,row,...args)=>{await put({write,table,row,target});return target.put(table,row,...args);};const v=target[key];return typeof v==='function'?v.bind(target):v;}})),...rest);return ()=>{s.repository.transaction=original;};}

test('actual 40/60/80 Entry first full V3 atomic adoption reads twenty times through fresh cache sessions with zero new jobs or provider calls',async()=>{
 for(const [children,style]of [[2,'original'],[3,'balanced'],[4,'concise']]){
  const f=await fixture(children,style);try{await adopt(f);assert.equal((await state(f)).cacheQualification.state,'exact');const row=await saved(f),job=(await rows(f.s,'organizerJobs')).find(x=>x.id===f.handle.jobId);assert.equal(Object.keys(row.manifest.generations).length,1);assert.equal(job.childIds.length,children);assert.equal(job.committedCoverage.length,children*20);assert.equal(f.calls,children);const before=await counters(f);
   for(let i=0;i<20;i++){const session=reopen(f);try{const h=await session.prepare({topicId:f.topic.id});assert.equal(h.state,'CACHED');const result=await session.run(h,f.provider);assert.equal(result.state,'CACHED');assert.equal(result.presentation.cacheQualification.reusable,true);assert.equal(result.presentation.presentation.currentView,row.projection.currentView);}finally{session.dispose();}}
   assert.equal(f.calls,children);assert.deepEqual(await counters(f),before);
  }finally{f.session.dispose();}
 }
});
test('earlier ACK hole and earlier UNKNOWN child after confirmed closure cannot stamp cache during ordinary original adoption',async()=>{
 for(const mode of ['ack-hole','unknown']){const f=await fixture();try{const job=(await rows(f.s,'organizerJobs')).find(x=>x.id===f.handle.jobId);await f.s.foundationWrite(async t=>{if(mode==='ack-hole')await t.delete('organizerWorkItems',qualifiedCoverageId(job.childCoverage[0][0],job));else{const r=await t.get('organizerUsage','aiu:attempt:'+job.childIds[0]);await t.put('organizerUsage',{...r,state:'OUTCOME_UNKNOWN'});}});if(mode==='ack-hole'){const a=(await rows(f.s,'organizerWorkItems')).filter(x=>x.jobId===job.id&&x.state==='ACKNOWLEDGED');assert.equal(a.length,39);assert.equal(Math.max(...a.map(x=>x.sequence)),1);assert.equal(job.committedCoverage.length,40);}assert.equal((await f.session.run(f.handle,f.provider)).state,'COMMITTED');await adopt(f);assert.equal((await state(f)).cacheQualification.reusable,false);assert.ok((await state(f)).presentation);assert.equal(Object.hasOwn(await saved(f),'cacheBinding'),false);assert.equal(f.calls,2);}finally{f.session.dispose();}}
});

test('existing cacheBinding key roundtrips V3 through original validator; unknown row extra and malformed binding never grant exact',async()=>{
 const f=await fixture();try{await adopt(f);const row=await saved(f);assert.equal(validIncrementalV3(row,new Set(row.evidenceEntryIds)),true);assert.equal(validIncrementalV3({...row,syntheticUnknownExtra:true},new Set(row.evidenceEntryIds)),false);
  for(const patch of [{version:2},{topicId:'synthetic-other-topic'},{presentationRevision:row.revision+1},{profile:{...profile,modelVersion:'synthetic-other-model'}},{style:{value:'concise',policyVersion:'AIOS-1.0'}},{evidenceVersion:'synthetic-other-evidence'},{syntheticUnknownExtra:true}]){const next={...row,cacheBinding:{...row.cacheBinding,...patch}};await f.s.foundationWrite(t=>t.put('meta',next));assert.equal(validIncrementalV3(next,new Set(row.evidenceEntryIds)),true);const actual=await state(f);assert.ok(actual.presentation);assert.equal(actual.cacheQualification.reusable,false);const session=reopen(f);try{assert.notEqual((await session.prepare({topicId:f.topic.id})).state,'CACHED');}finally{session.dispose();}}
 }finally{f.session.dispose();}
});
test('every child attempt and exact ACK partition are required; earlier bad records never hide behind last child or max sequence',async()=>{
 for(const mode of ['receipt-foreign','duplicate-operation','provider-drift','sequence','ack-signature','ack-outcome','ack-unit','job-partition']){const f=await fixture();try{const job=(await rows(f.s,'organizerJobs')).find(x=>x.id===f.handle.jobId);await f.s.foundationWrite(async t=>{
   if(mode==='job-partition'){await t.put('organizerJobs',{...job,childCoverage:[job.childCoverage[1],job.childCoverage[0]]});return;}
   if(mode.startsWith('ack-')){const id=qualifiedCoverageId(job.childCoverage[0][0],job),a=await t.get('organizerWorkItems',id);await t.put('organizerWorkItems',{...a,...(mode==='ack-signature'?{signature:'synthetic-wrong'}:mode==='ack-outcome'?{outcome:'NO_CHANGE'}:{unit:{...a.unit,scope:'synthetic-wrong'}})});return;}
   const r=await t.get('organizerUsage','aiu:attempt:'+job.childIds[0]);await t.put('organizerUsage',{...r,...(mode==='receipt-foreign'?{jobId:'synthetic-foreign'}:mode==='duplicate-operation'?{operationReceiptId:job.childIds[1]}:mode==='provider-drift'?{provider:{...r.provider,version:'synthetic-drift'}}:{sequence:1})});
  });await adopt(f);assert.equal((await state(f)).cacheQualification.reusable,false);assert.ok((await state(f)).presentation);assert.equal(Object.hasOwn(await saved(f),'cacheBinding'),false);assert.equal(f.calls,2);}finally{f.session.dispose();}}
});
test('partial and allKeep plus disposed/cross-store/cold proof remain readable without stamping; old exact retry cannot regenerate authority',async()=>{
 for(const mode of ['partial','kept','disposed','other-store']){const f=await fixture();try{if(mode==='disposed')f.session.dispose();if(mode==='other-store')f.s=new OrganizerStore(f.storage,{indexedDB:f.indexedDB});const decisions=Object.fromEntries(f.candidate.changedFields.map((k,i)=>[k,mode==='kept'||mode==='partial'&&i>0?'keep':'adopt'])),op=edit(f,decisions),out=await f.s.editAIPresentation(op);assert.deepEqual(await f.s.editAIPresentation(op),out);assert.equal((await state(f)).cacheQualification.reusable,false);assert.equal(Object.hasOwn(await saved(f),'cacheBinding'),false);assert.equal(f.calls,2);}finally{f.session.dispose();}}
});
test('adoption receipt abort rolls back every actual store and same operation retry binds once without dispatch',async()=>{
 const f=await fixture(),op=edit(f),before=await counters(f);let armed=true;const restore=intercept(f.s,{put:async({table,row})=>{if(armed&&table==='operationReceipts'&&row.namespace==='thought-library')throw Error('SYNTHETIC adoption final receipt abort');}});
 try{await assert.rejects(f.s.editAIPresentation(op),{code:'STORAGE_FAILED'});assert.deepEqual(await counters(f),before);armed=false;const result=await f.s.editAIPresentation(op);assert.equal((await state(f)).cacheQualification.state,'exact');const after=await counters(f);assert.deepEqual(await f.s.editAIPresentation(op),result);assert.deepEqual(await counters(f),after);assert.equal(f.calls,2);}finally{restore();f.session.dispose();}
});
test('registry disposal at last ACK/control await prevents stamping and disposal during final adoption receipt rolls back all stores',async()=>{
 for(const phase of ['ack','control','receipt']){const f=await fixture(),before=await counters(f);let disposed=false;const originalControl=f.s.control.bind(f.s),restore=intercept(f.s,{get:async({write,table,value})=>{if(phase==='ack'&&write&&!disposed&&table==='organizerWorkItems'&&value?.state==='ACKNOWLEDGED'){disposed=true;f.session.dispose();}return value;},put:async({table,row})=>{if(phase==='receipt'&&!disposed&&table==='operationReceipts'&&row.namespace==='thought-library'){disposed=true;f.session.dispose();}}});if(phase==='control')f.s.control=async(...args)=>{const c=await originalControl(...args);if(!disposed){disposed=true;f.session.dispose();}return c;};
  try{if(phase==='receipt'){await assert.rejects(adopt(f),{code:'STALE_BASE'});assert.deepEqual(await counters(f),before);}else{await adopt(f);assert.equal((await state(f)).cacheQualification.reusable,false);assert.ok((await state(f)).presentation);}assert.equal(disposed,true);assert.equal(f.calls,2);}finally{restore();f.s.control=originalControl;f.session.dispose();}
 }
});
test('pending local style/control change during final receipt rejects stamped write rather than publishing a stale binding',async()=>{
 const f=await fixture(),before=await counters(f);let changed=false;const restore=intercept(f.s,{put:async({table,row,target})=>{if(!changed&&table==='operationReceipts'&&row.namespace==='thought-library'){const c=await f.s.control(target),p=readAIStyle(c.preferences,'initial');assert.equal(applyPreferenceChanges(c.preferences,{aiOrganizeStyle:{version:1,value:'concise',expectedRevision:p.revision,expectedEpoch:p.epoch}},'initial').ok,true);f.s.pendingControl=c;changed=true;}}});try{await assert.rejects(adopt(f),{code:'STALE_BASE'});assert.equal(changed,true);assert.deepEqual(await counters(f),before);assert.equal(f.calls,2);}finally{restore();f.session.dispose();}
});
test('actual cached full-scope authority rejects revoke, principal replacement, owner edit/restore and final style drift without a new attempt',async()=>{
 for(const mode of ['denied','principal','edit','manual','remove','restore','style']){const f=await fixture();await adopt(f);let armed=false,n=0;const session=reopen(f,{resolveAuthority:async(t,r)=>{const a=await authority(t,r);assert.equal(r.evidenceKeys.length,40);assert.equal(r.coverage.length,40);if(armed&&mode==='style'&&++n===2){const c=await f.s.control(t),p=readAIStyle(c.preferences,'initial');assert.equal(applyPreferenceChanges(c.preferences,{aiOrganizeStyle:{version:1,value:'concise',expectedRevision:p.revision,expectedEpoch:p.epoch}},'initial').ok,true);f.s.pendingControl=c;}return armed&&mode==='denied'?{...a,allowed:false}:armed&&mode==='principal'?{...a,principalId:'synthetic-other'}:a;}});try{const h=await session.prepare({topicId:f.topic.id});assert.equal(h.state,'CACHED');armed=true;if(mode==='edit'){const e=await f.s.entry(f.entries[0].id);const result=await f.s.editEntry({id:e.id,expectedRevision:e.revision,changes:{body:'SYNTHETIC actual edited qualifier'},operationId:crypto.randomUUID()});assert.equal(result.revision,e.revision+1);assert.notEqual((await f.s.entry(e.id)).thoughtText,e.thoughtText);}if(mode==='manual'){const row=await saved(f);await f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:row.revision,field:'currentView',value:'SYNTHETIC protected human text',operationId:crypto.randomUUID()});assert.equal((await state(f)).cacheQualification.reason,'human_owned');}if(mode==='remove'){const e=await f.s.entry(f.entries[0].id);await f.s.removeEntry({id:e.id,expectedRevision:e.revision,operationId:crypto.randomUUID()});assert.equal((await f.s.entry(e.id)).lifecycle,'removed');}if(mode==='restore')await f.s.foundationWrite(t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic-changed'}));const before=await counters(f);await assert.rejects(session.run(h,f.provider),e=>['STALE_BASE','UNAVAILABLE','CANCELLED'].includes(e.code));assert.deepEqual(await counters(f),before);assert.equal(f.calls,2);}finally{session.dispose();f.session.dispose();}}
});

test('lost actual COMMITTED confirmation read leaves readable candidate and no authority; retry cannot mint a replacement private proof',async()=>{
 let restore,failed=false;const f=await fixture(2,'balanced',{beforeRun:f=>{restore=intercept(f.s,{get:async({write,table,value})=>{if(!write&&!failed&&table==='organizerJobs'&&value?.state==='COMMITTED'){failed=true;throw Error('SYNTHETIC lost confirmation read');}return value;}});},afterFailure:async f=>{restore();assert.equal((await rows(f.s,'organizerJobs')).find(x=>x.id===f.handle.jobId).state,'COMMITTED');}});
 try{assert.equal(failed,true);assert.equal((await f.session.run(f.handle,f.provider)).state,'COMMITTED');assert.equal(f.calls,2);await adopt(f);assert.ok((await state(f)).presentation);assert.equal((await state(f)).cacheQualification.reusable,false);assert.equal(f.calls,2);}finally{restore();f.session.dispose();}
});
test('candidate, earlier/final ACK and last receipt abort preserve private responses for whole-transaction exact retry, never provider replay',async()=>{
 for(const phase of ['candidate','earlier-ack','last-ack','last-receipt']){let restore,failed=false,armed=true;const f=await fixture(2,'balanced',{beforeRun:f=>{restore=intercept(f.s,{put:async({table,row})=>{if(armed&&((phase==='candidate'&&table==='meta'&&row.candidate)||(phase==='earlier-ack'&&table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED'&&row.sequence===0)||(phase==='last-ack'&&table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED'&&row.sequence===1)||(phase==='last-receipt'&&table==='organizerUsage'&&row.state==='COMMITTED'&&row.sequence===1))){failed=true;throw Error('SYNTHETIC atomic closure abort');}}});},afterFailure:async f=>{assert.equal(failed,true);assert.equal(await saved(f),undefined);assert.equal((await rows(f.s,'organizerWorkItems')).filter(x=>x.state==='ACKNOWLEDGED').length,0);assert.deepEqual((await rows(f.s,'organizerUsage')).filter(x=>x.jobId===f.handle.jobId).map(x=>[x.state,x.attemptCount]),[['RESPONSE_RECORDED',1],['RESPONSE_RECORDED',1]]);armed=false;assert.equal((await f.session.run(f.handle,f.provider)).state,'COMMITTED');restore();}});
  try{await adopt(f);assert.equal((await state(f)).cacheQualification.state,'exact');assert.equal(f.calls,2);}finally{restore();f.session.dispose();}
 }
});
test('style A-B-A reuses existing qualified A without dispatch but old cached handle cannot survive preference revision changes',async()=>{
 const f=await fixture();try{await adopt(f);const session=reopen(f),h=await session.prepare({topicId:f.topic.id});const before=await counters(f);for(const value of ['concise','balanced']){const p=await f.s.aiStylePreference();await f.s.updatePreferences({aiOrganizeStyle:{version:1,value,expectedRevision:p.revision,expectedEpoch:p.epoch}});assert.equal((await state(f)).cacheQualification.reusable,value==='balanced');}await assert.rejects(session.run(h,f.provider),{code:'STALE_BASE'});session.dispose();const again=reopen(f),next=await again.prepare({topicId:f.topic.id});assert.equal(next.state,'CACHED');assert.equal((await again.run(next,f.provider)).state,'CACHED');again.dispose();assert.equal(f.calls,2);const after=await counters(f);for(const name of ['organizerJobs','organizerUsage','organizerWorkItems','thoughts','revisions','records','blocks'])assert.deepEqual(after[name],before[name]);}finally{f.session.dispose();}
});
test('atomic private proofs share the original global32 bound; eviction permits ordinary adoption but never synthetic replacement authority',async()=>{
 const all=[];try{for(let i=0;i<33;i++)all.push(await fixture());await adopt(all[0]);assert.ok((await state(all[0])).presentation);assert.equal((await state(all[0])).cacheQualification.reusable,false);await adopt(all.at(-1));assert.equal((await state(all.at(-1))).cacheQualification.state,'exact');assert.ok(all.every(f=>f.calls===2));}finally{for(const f of all)f.session.dispose();}
});
test('real control mutation immediately after final asynchronous cached controls cannot cross the last synchronous return fence',async()=>{
 const f=await fixture();await adopt(f);const session=reopen(f),h=await session.prepare({topicId:f.topic.id}),control=f.s.control.bind(f.s);let changed=false;
 f.s.control=async(...args)=>{const final=new Error().stack.includes('assertLocalOrganizeCacheControls'),c=await control(...args);if(final&&!changed){queueMicrotask(()=>queueMicrotask(()=>{const p=readAIStyle(c.preferences,'initial');assert.equal(applyPreferenceChanges(c.preferences,{aiOrganizeStyle:{version:1,value:'concise',expectedRevision:p.revision,expectedEpoch:p.epoch}},'initial').ok,true);f.s.pendingControl=c;changed=true;}));}return c;};
 try{await assert.rejects(session.run(h,f.provider),{code:'STALE_BASE'});assert.equal(changed,true);assert.equal(f.calls,2);}finally{f.s.control=control;session.dispose();f.session.dispose();}
});
