import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {LocalOrganizeSession} from '../core/organizer/local-organize-session.js';
import {aiCandidateKey} from '../core/organizer/ai-candidate.js';
const profile={contractVersion:'local-incremental-v2',modelVersion:'synthetic',promptVersion:'synthetic'},authority=async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_ORGANIZE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}});
async function fixture(style='original'){const {s}=await setup(OrganizerStore),topic=await s.createTopic({name:'Incremental',operationId:crypto.randomUUID()}),pref=await s.aiStylePreference();if(style)await s.updatePreferences({aiOrganizeStyle:{version:1,value:style,expectedRevision:pref.revision,expectedEpoch:pref.epoch}});return {s,topic,ids:[],payloads:[]};}
async function add(f,n){for(let i=0;i<n;i++){const e=await f.s.createEntry({actor:'user',operationId:crypto.randomUUID(),body:'e'+f.ids.length,type:'idea',formation:'explicit',evidence:[]});await f.s.placeEntry({topicId:f.topic.id,entryId:e.id,expectedEntryRevision:e.revision,expectedTopicRevision:(await f.s.topic(f.topic.id)).organizationRevision,operationId:crypto.randomUUID()});f.ids.push(e.id);}}
async function refresh(f,{holdCandidate=false,answer=null,version=2,refreshStyle=false,children=1}={}){const session=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:version}),h=await session.prepare({topicId:f.topic.id,refreshStyle,children});if(h.state==='NO_DELTA'){session.dispose();return h;}const result=await session.run(h,{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async r=>{f.payloads.push(structuredClone(r));if(answer)return answer(r);return {version:2,blocks:r.inputs.map(i=>({field:'currentView',text:i.text,evidenceEntryIds:[i.ref],sourceSpans:[{entryId:i.ref,revision:i.revision,start:0,end:i.text.length}]}))};}});const status=(await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0],candidate=status.candidate;assert.ok(candidate);if(holdCandidate){session.dispose();return candidate;}await f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:candidate.expectedRevision,expectedCandidateKey:aiCandidateKey(candidate),candidateDecisions:Object.fromEntries(candidate.changedFields.map(k=>[k,'adopt'])),operationId:crypto.randomUUID()});session.dispose();return result;}

const saved=f=>f.s.run(()=>f.s.repository.transaction(false,t=>t.get('meta','aiPresentation:'+f.topic.id)));
async function style(f,value){const p=await f.s.aiStylePreference();await f.s.updatePreferences({aiOrganizeStyle:{version:1,value,expectedRevision:p.revision,expectedEpoch:p.epoch}});}
async function choose(f,c,decisions){return f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:c.expectedRevision,expectedCandidateKey:aiCandidateKey(c),candidateDecisions:decisions,operationId:crypto.randomUUID()});}
test('actual V2 explicit different style adopts v3 even same visible bytes; next same-style delta retains generations',async()=>{
 const f=await fixture();await add(f,2);await refresh(f);const old=await saved(f);await style(f,'concise');const c=await refresh(f,{version:3,refreshStyle:true,holdCandidate:true});assert.equal(c.schemaVersion,4);assert.equal(c.proposal.currentView,old.projection.currentView);assert.equal(c.changedFields.length,8);await choose(f,c,Object.fromEntries(c.changedFields.map(k=>[k,'adopt'])));const row=await saved(f);assert.equal(row.presentationVersion,3);assert.equal(row.manifest.fields.currentView.style,'concise');await add(f,1);await refresh(f,{version:3});const after=await saved(f);assert.equal(f.payloads.at(-1).inputs.length,1);assert.deepEqual(after.manifest.blocks.slice(0,2),row.manifest.blocks);assert.equal(Object.keys(after.manifest.generations).length,2);assert.equal((await refresh(f,{version:3})).state,'NO_DELTA');
});
test('mixed field decisions keep exact old style/provenance and do not claim uniform cache or whole checkpoint',async()=>{
 const f=await fixture();await add(f,1);await refresh(f);const old=await saved(f);await style(f,'concise');const c=await refresh(f,{version:3,refreshStyle:true,holdCandidate:true});await choose(f,c,Object.fromEntries(c.changedFields.map(k=>[k,k==='currentView'?'keep':'adopt'])));const r=await saved(f);assert.equal(r.manifest.fields.currentView.style,'original');assert.equal(r.manifest.fields.blockSummary.style,'concise');assert.equal(r.projection.currentView,old.projection.currentView);assert.equal(r.needsUpdate,true);assert.equal((await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0].cacheQualification.reusable,false);const s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3});await assert.rejects(s.prepare({topicId:f.topic.id}),{code:'STALE_BASE'});s.dispose();await refresh(f,{version:3,refreshStyle:true});assert.equal((await saved(f)).manifest.fields.currentView.style,'concise');
});
test('all Keep does not convert the accepted V2 or change its projection/provenance',async()=>{
 const f=await fixture();await add(f,1);await refresh(f);const old=await saved(f);await style(f,'concise');const c=await refresh(f,{version:3,refreshStyle:true,holdCandidate:true});await choose(f,c,Object.fromEntries(c.changedFields.map(k=>[k,'keep'])));const r=await saved(f);assert.equal(r.presentationVersion,2);assert.equal(r.revision,old.revision+1);assert.deepEqual(r.manifest,old.manifest);assert.deepEqual(r.projection,old.projection);
});
test('uniform v3 roundtrip is zero-write NO_DELTA but old prepared handle rejects preference revision changes',async()=>{
 const f=await fixture();await add(f,2);await refresh(f);await style(f,'concise');await refresh(f,{version:3,refreshStyle:true});const before=await saved(f);await style(f,'original');await style(f,'concise');assert.equal((await refresh(f,{version:3})).state,'NO_DELTA');assert.deepEqual(await saved(f),before);await add(f,1);const s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3}),h=await s.prepare({topicId:f.topic.id});await style(f,'original');await style(f,'concise');let calls=0;await assert.rejects(s.run(h,{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>{calls++;return {};}}),{code:'STALE_BASE'});assert.equal(calls,0);s.dispose();
});
test('v3 manual field remains indivisible and actual recovery preserves protected projection',async()=>{
 const f=await fixture();await add(f,1);await refresh(f);await style(f,'concise');await refresh(f,{version:3,refreshStyle:true});const r=await saved(f);await f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:r.revision,field:'currentView',value:'Human 👩🏽‍💻 exact text',operationId:crypto.randomUUID()});const edited=await saved(f);assert.equal(edited.manifest.blocks.filter(b=>b.field==='currentView').length,1);assert.equal(edited.manifest.blocks.find(b=>b.field==='currentView').manual,true);const s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3});await assert.rejects(s.prepare({topicId:f.topic.id,refreshStyle:true}),{code:'STALE_BASE'});s.dispose();const out=await f.s.recoverAIDraft({topicId:f.topic.id,expectedRevision:edited.revision,operationId:crypto.randomUUID()}),entry=await f.s.entry(out.id);assert.ok(entry.body.includes('Human 👩🏽‍💻 exact text'));assert.deepEqual(entry.sourceRecordIds,[]);assert.equal(await saved(f),undefined);
});
test('actual four-child style closure records exact ordered committed receipt provenance',async()=>{
 const f=await fixture();for(let i=0;i<4;i++){await add(f,20);await refresh(f);}await style(f,'concise');await refresh(f,{version:3,refreshStyle:true,children:4});const row=await saved(f),g=Object.values(row.manifest.generations)[0];assert.equal(g.children.length,4);const j=await f.s.run(()=>f.s.repository.transaction(false,t=>t.get('organizerJobs',g.jobId)));assert.equal(j.state,'COMMITTED');assert.deepEqual(g.children.map(x=>x.childId),j.childIds);for(const c of g.children){const r=await f.s.run(()=>f.s.repository.transaction(false,t=>t.get('organizerUsage','aiu:attempt:'+c.childId)));assert.equal(r.state,'COMMITTED');assert.equal(r.operationReceiptId,c.operationReceiptId);assert.match(c.payloadDigest,/^[a-f0-9]{64}$/);}assert.deepEqual(f.payloads.slice(-4).map(p=>p.inputs.length),[20,20,20,20]);
});
test('current backup preserves v3; immutable old backup reader refuses new saved envelope before restore',async()=>{
 const {BackupService}=await import('./harness/historical-backup.mjs'),{exported,prepared}=await import('./harness/backup-v081.mjs'),{local:storage}=await import('./harness/thought-m1.mjs'),{IDBFactory}=await import('./vendor/fake-indexeddb/build/esm/index.js');const f=await fixture();await add(f,1);await refresh(f);await style(f,'concise');await refresh(f,{version:3,refreshStyle:true});const before=await saved(f),items=await exported(new BackupService(f.s)),target=new OrganizerStore(storage(),{indexedDB:new IDBFactory()}),service=new BackupService(target),stage=await prepared(service,items);assert.equal(stage.preview.canRestore,true);await service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});const after=await target.run(()=>target.repository.transaction(false,t=>t.get('meta','aiPresentation:'+f.topic.id)));assert.deepEqual(after.manifest,before.manifest);assert.deepEqual(after.projection,before.projection);assert.equal((await target.aiPresentationStatus({topicId:f.topic.id})).topics[0].cacheQualification.reusable,false);
 const {readFile}=await import('node:fs/promises'),{createHash}=await import('node:crypto'),base=new URL('./fixtures/ai-style-v2-reader/',import.meta.url),manifest=JSON.parse(await readFile(new URL('manifest.json',base),'utf8'));
 for(const item of manifest.files){const data=await readFile(new URL(item.path,base));assert.equal(createHash('sha256').update(data).digest('hex'),item.sha256);assert.equal(createHash('sha1').update('blob '+data.length+'\0').update(data).digest('hex'),item.gitBlob);}
 const {BackupService:Old}=await import('./fixtures/ai-style-v2-reader/core/backup-service.js'),other=new OrganizerStore(storage(),{indexedDB:new IDBFactory()});await assert.rejects(prepared(new Old(other),items));assert.equal(await other.run(()=>other.repository.transaction(false,t=>t.get('meta','aiPresentation:'+f.topic.id))),undefined);
});

test('existing Source purge clears v3 generated bytes and blocks old recovery authority and backup resurrection',async()=>{const {derived,local:storage}=await import('./harness/thought-m1.mjs'),{admitPreGatePurgeFixture}=await import('./harness/pre-gate-purge-fixture.mjs'),{BackupService}=await import('./harness/historical-backup.mjs'),{exported,prepared}=await import('./harness/backup-v081.mjs'),{IDBFactory}=await import('./vendor/fake-indexeddb/build/esm/index.js');const f=await fixture(),input=(await f.s.snapshot()).library.blocks[0],e=await derived(f.s,[input.id]);await f.s.placeEntry({topicId:f.topic.id,entryId:e.id,expectedEntryRevision:e.revision,expectedTopicRevision:(await f.s.topic(f.topic.id)).organizationRevision,operationId:crypto.randomUUID()});f.ids.push(e.id);await refresh(f,{version:3});const before=await saved(f),operation={type:'AI_RECOVERY_SNAPSHOT',topicId:f.topic.id,baseRevision:before.revision,generation:before.recoveryGeneration},draft={kind:'ai_presentation',ownerId:f.topic.id,operation};assert.deepEqual(await f.s.recoveryDraftSourceIds(draft),[input.sourceRecordId]);const old=await exported(new BackupService(f.s));await admitPreGatePurgeFixture(f.s,input.sourceRecordId);await f.s.drainPurgeCleanup();await assert.rejects(f.s.recoveryDraftSourceIds(draft));assert.equal(await saved(f),undefined);assert.equal((await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0].presentation,null);const target=new OrganizerStore(storage(),{indexedDB:new IDBFactory()});await target.finishFoundation();const tombstones=await f.s.run(()=>f.s.repository.transaction(false,t=>t.all('tombstones')));await target.foundationWrite(async t=>{for(const r of tombstones)await t.put('tombstones',r);});const service=new BackupService(target),stage=await prepared(service,old);assert.equal(stage.preview.reason,'BACKUP_PURGE_CONFLICT');await assert.rejects(service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity}));});

const adopt=(f,candidate,decisions=null)=>f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:candidate.expectedRevision,expectedCandidateKey:aiCandidateKey(candidate),candidateDecisions:decisions||Object.fromEntries(candidate.changedFields.map(k=>[k,'adopt'])),operationId:crypto.randomUUID()});
test('v3 strict decoder rejects forged or incomplete provenance, unknown keys and broken projection/support',async()=>{
 const {validIncrementalV3}=await import('../core/organizer/ai-incremental-v3.js'),f=await fixture();await add(f,1);await refresh(f,{version:3});const good=await saved(f),allowed=new Set(f.ids);assert.equal(validIncrementalV3(good,allowed),true);for(const mutate of [
 r=>r.manifest.fields.currentView.style='original-guess',r=>delete r.manifest.fields.preferences,r=>r.manifest.fields.currentView.generations.push('0'.repeat(64)),r=>r.manifest.blocks[0].generation='0'.repeat(64),r=>r.manifest.blocks[0].extra=true,r=>r.manifest.generations[Object.keys(r.manifest.generations)[0]].sessionCounter=1,r=>Object.values(r.manifest.generations)[0].children.push(Object.values(r.manifest.generations)[0].children[0]),r=>Object.values(r.manifest.generations)[0].children[0].payloadDigest='unknown',r=>Object.values(r.manifest.generations)[0].children[0].body='private',r=>Object.values(r.manifest.generations)[0].commitIdentity='0'.repeat(64),r=>r.evidenceEntryIds.push('extra'),r=>r.projection.currentView+='uncovered',r=>r.manifest.fields.currentView.generations=[],r=>r.manifest.blocks[0].support[0].id='foreign',r=>r.currentView='legacy bypass'
 ]){const row=structuredClone(good);mutate(row);assert.equal(validIncrementalV3(row,allowed),false);}
});
test('v3 actual ACK abort rolls provenance/candidate back; same private response retry and lost adoption ACK retain identity',async()=>{
 const f=await fixture();await add(f,1);await refresh(f);await style(f,'concise');const before=await saved(f),s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3}),h=await s.prepare({topicId:f.topic.id,refreshStyle:true}),original=f.s.repository.transaction.bind(f.s.repository);let abort=true,calls=0;
 f.s.repository.transaction=(write,run,...rest)=>original(write,async t=>{const put=t.put.bind(t);t.put=async(table,row)=>{if(abort&&table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED')throw Error('synthetic ACK rollback');return put(table,row);};return run(t);},...rest);
 const p={describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async r=>{calls++;return {version:2,blocks:r.inputs.map(i=>({field:'currentView',text:i.text,evidenceEntryIds:[i.ref],sourceSpans:[{entryId:i.ref,revision:i.revision,start:0,end:i.text.length}]}))};}};
 try{await assert.rejects(s.run(h,p),{code:'STORAGE_FAILED'});assert.deepEqual(await saved(f),before);abort=false;assert.equal((await s.run(h,p)).state,'COMMITTED');assert.equal(calls,1);const c=(await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0].candidate,request={topicId:f.topic.id,expectedRevision:c.expectedRevision,expectedCandidateKey:aiCandidateKey(c),candidateDecisions:Object.fromEntries(c.changedFields.map(k=>[k,'adopt'])),operationId:crypto.randomUUID()};const result=await f.s.editAIPresentation(request),r=await saved(f);assert.deepEqual(await f.s.editAIPresentation(request),result);assert.deepEqual(await saved(f),r);assert.equal(calls,1);}finally{f.s.repository.transaction=original;s.dispose();}
});
test('candidate manifest digest binds style/provenance and actual current style holds adoption fence',async()=>{
 for(const mode of ['style','manifest']){const f=await fixture();await add(f,1);await refresh(f);await style(f,'concise');const c=await refresh(f,{version:3,refreshStyle:true,holdCandidate:true}),old=await saved(f);if(mode==='style')await style(f,'balanced');else await f.s.foundationWrite(async t=>{const r=await t.get('meta','aiPresentation:'+f.topic.id);Object.values(r.candidate.proposal.manifest.generations)[0].children[0].payloadDigest='0'.repeat(64);await t.put('meta',r);});await assert.rejects(choose(f,c,Object.fromEntries(c.changedFields.map(k=>[k,'adopt']))),{code:'STALE_BASE'});assert.deepEqual((await saved(f)).projection,old.projection);}
});
test('V2 same-style default reads and delta keep their old format; new owner cannot silently migrate them',async()=>{const f=await fixture();await add(f,1);await refresh(f);await add(f,1);const before=await saved(f),s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3});for(const refreshStyle of [false,true])await assert.rejects(s.prepare({topicId:f.topic.id,refreshStyle}),{code:'STALE_BASE'});s.dispose();assert.deepEqual(await saved(f),before);await refresh(f);assert.equal((await saved(f)).presentationVersion,2);});
test('restored v3 remains readable but old control and profile cannot authorize incremental execution',async()=>{
 const f=await fixture();await add(f,1);await refresh(f,{version:3});const before=await saved(f);await f.s.foundationWrite(t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic-new-restore'}));const s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3});await assert.rejects(s.prepare({topicId:f.topic.id}),{code:'STALE_BASE'});assert.deepEqual((await saved(f)).projection,before.projection);s.dispose();
});

test('review baseGeneration cannot change between digest capture and adoption transaction',async()=>{
 const f=await fixture();await add(f,1);await refresh(f);await style(f,'concise');const c=await refresh(f,{version:3,refreshStyle:true,holdCandidate:true});
 const original=f.s.foundationWrite.bind(f.s);let inject=true;
 f.s.foundationWrite=async fn=>{if(inject){inject=false;await original(async t=>{const r=await t.get('meta','aiPresentation:'+f.topic.id);r.candidate.baseGeneration.profile.modelVersion='forged-model';await t.put('meta',r);});}return original(fn);};
 await assert.rejects(choose(f,c,Object.fromEntries(c.changedFields.map(k=>[k,k==='currentView'?'keep':'adopt']))),{code:'STALE_BASE'});
});

test('review disposed single V3 owner cannot publish candidate during final ACK write',async()=>{
 const f=await fixture();await add(f,1);const s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:3}),h=await s.prepare({topicId:f.topic.id});
 const original=f.s.repository.transaction.bind(f.s.repository);let disposed=false;
 f.s.repository.transaction=(w,fn,...rest)=>original(w,async t=>{const put=t.put.bind(t);t.put=async(table,row)=>{if(!disposed&&table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED'){disposed=true;s.dispose();}return put(table,row);};return fn(t);},...rest);
 await assert.rejects(s.run(h,{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async r=>({version:2,blocks:r.inputs.map(i=>({field:'currentView',text:i.text,evidenceEntryIds:[i.ref],sourceSpans:[{entryId:i.ref,revision:i.revision,start:0,end:i.text.length}]}))})}));
 assert.equal(await saved(f),undefined);
});

test('existing V2 private owner also rolls back disposal during final ACK write',async()=>{
 const f=await fixture();await add(f,1);const s=new LocalOrganizeSession(f.s,{resolveAuthority:authority,profile,routeVersion:'synthetic',incrementalVersion:2}),h=await s.prepare({topicId:f.topic.id});
 const original=f.s.repository.transaction.bind(f.s.repository);let disposed=false;
 f.s.repository.transaction=(w,fn,...rest)=>original(w,async t=>{const put=t.put.bind(t);t.put=async(table,row)=>{if(!disposed&&table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED'){disposed=true;s.dispose();}return put(table,row);};return fn(t);},...rest);
 await assert.rejects(s.run(h,{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async r=>({version:2,blocks:r.inputs.map(i=>({field:'currentView',text:i.text,evidenceEntryIds:[i.ref],sourceSpans:[{entryId:i.ref,revision:i.revision,start:0,end:i.text.length}]}))})}));
 assert.equal(await saved(f),undefined);
});
test('optional trusted committer fence rejects promises/nonfunctions and preserves absent legacy behavior',async()=>{
 const {AIUsageFoundation}=await import('../core/ai-usage/foundation.js');for(const mode of ['absent','true','false','promise','nonfunction','undefined']){const {s}=await setup(OrganizerStore),ai=new AIUsageFoundation(s,{resolveAuthority:async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_MAINTENANCE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}}),committers:{topic:async(t,r)=>{await t.put('meta',{id:'synthetic-guard-domain',written:true});return {committed:true,coverage:r.units,...(mode==='absent'?{}:{isCurrent:mode==='true'?()=>true:mode==='false'?()=>false:mode==='promise'?()=>Promise.resolve(true):mode==='nonfunction'?true:undefined})};}}}),items=(await ai.collect()).items,coverage=items.map(i=>({key:i.key,facet:'topic',scope:'library'})),j=await ai.plan({type:'AI_MAINTENANCE',items,coverage,contractVersion:'synthetic',routeVersion:'synthetic',intent:'maintenance'});await ai.reserve(j.id,{reservationId:'synthetic'});await ai.dispatch(j.id,j.childIds[0],{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async()=>({accepted:true,operationReceiptId:'synthetic'})});const action=ai.commitFacet(j.id,j.childIds[0],{facet:'topic',units:coverage});if(['absent','true'].includes(mode)){assert.equal((await action).state,'COMMITTED');}else{await assert.rejects(action,{code:'STALE_BASE'});assert.equal(await s.run(()=>s.repository.transaction(false,t=>t.get('meta','synthetic-guard-domain'))),undefined);assert.equal((await ai.status(j.id)).attempts[0].state,'RESPONSE_RECORDED');}}
});

test('three explicit style refresh/allKeep cycles preserve accepted bytes but save each choice revision exactly once',async()=>{
 const f=await fixture();await add(f,1);await refresh(f);const before=await saved(f);await style(f,'concise');for(let cycle=0;cycle<3;cycle++){const c=await refresh(f,{version:3,refreshStyle:true,holdCandidate:true}),op={topicId:f.topic.id,expectedRevision:c.expectedRevision,expectedCandidateKey:aiCandidateKey(c),candidateDecisions:Object.fromEntries(c.changedFields.map(k=>[k,'keep'])),operationId:crypto.randomUUID()},out=await f.s.editAIPresentation(op);assert.deepEqual(await f.s.editAIPresentation(op),out);const r=await saved(f);assert.equal(r.revision,before.revision+cycle+1);assert.equal(r.presentationVersion,2);assert.deepEqual(r.projection,before.projection);assert.deepEqual(r.manifest,before.manifest);assert.deepEqual(r.protections,before.protections);}assert.equal(f.payloads.length,4);
});
test('single V3 final authority disposal rolls publication back after candidate put',async()=>{
 const f=await fixture();await add(f,1);let s,disposed=false;s=new LocalOrganizeSession(f.s,{resolveAuthority:async(t,r)=>{const result=await authority(t,r);if((await t.get('meta','aiPresentation:'+f.topic.id))?.candidate){disposed=true;s.dispose();}return result;},profile,routeVersion:'synthetic',incrementalVersion:3});const h=await s.prepare({topicId:f.topic.id});await assert.rejects(s.run(h,{describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute:async r=>({version:2,blocks:r.inputs.map(i=>({field:'currentView',text:i.text,evidenceEntryIds:[i.ref],sourceSpans:[{entryId:i.ref,revision:i.revision,start:0,end:i.text.length}]}))})}),{code:'STALE_BASE'});assert.equal(disposed,true);assert.equal(await saved(f),undefined);const usage=await f.s.run(()=>f.s.repository.transaction(false,t=>t.all('organizerUsage')));assert.deepEqual(usage.map(r=>[r.state,r.attemptCount]),[['RESPONSE_RECORDED',1]]);
});

test('review none-base V3 allKeep keeps no Current and exact operation is idempotent',async()=>{
 const f=await fixture();await add(f,1);const c=await refresh(f,{version:3,holdCandidate:true});assert.equal(c.baseKind,'none');const op={topicId:f.topic.id,expectedRevision:c.expectedRevision,expectedCandidateKey:aiCandidateKey(c),candidateDecisions:Object.fromEntries(c.changedFields.map(k=>[k,'keep'])),operationId:crypto.randomUUID()};
 const out=await f.s.editAIPresentation(op),r=await saved(f);assert.equal(out.hasCurrent,false);assert.equal(out.revision,0);assert.equal(r.revision,0);assert.equal(r.candidate,undefined);assert.equal(r.presentationVersion,undefined);assert.deepEqual(await f.s.editAIPresentation(op),out);assert.deepEqual(await saved(f),r);assert.equal((await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0].presentation,null);
});
