import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,derived,inputEdit} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {aiCandidateKey} from '../core/organizer/ai-candidate.js';
const module=()=>import('../core/organizer/local-organize-session.js');
const authority=async(_t,r)=>({allowed:true,principalId:'synthetic',libraryId:'synthetic',consentEpoch:'synthetic',jobTypes:['AI_ORGANIZE'],scope:{evidenceKeys:r.evidenceKeys,coverage:r.coverage}});
async function fixture(){const {s}=await setup(OrganizerStore),input=(await s.snapshot()).library.blocks[0],made=await derived(s,[input.id]),topic=await s.createTopic({name:'Synthetic local Organize',operationId:crypto.randomUUID()});await s.placeEntry({topicId:topic.id,entryId:made.id,expectedEntryRevision:(await s.entry(made.id)).revision,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision,operationId:crypto.randomUUID()});return {s,input,made,topic};}
const rows=(s,table)=>s.run(()=>s.repository.transaction(false,t=>t.all(table)));
const options={resolveAuthority:authority,profile:{contractVersion:'local-synthetic-v1',modelVersion:'synthetic',promptVersion:'synthetic'},routeVersion:'local-synthetic'};
const provider=(execute)=>({describe:()=>({providerId:'synthetic',version:'1',executionKind:'fixture'}),execute});
const answer=request=>({presentation:{topicId:request.topicId,currentView:request.inputs[0].text,evidenceEntryIds:request.inputs.map(x=>x.ref)},sourceSpans:[{field:'currentView',index:null,entryId:request.inputs[0].ref,revision:request.inputs[0].revision,start:0,end:request.inputs[0].text.length}]});
test('actual local session commits candidate and coverage atomically, then existing adoption/history/status consume it',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),handle=await session.prepare({topicId:f.topic.id});let calls=0;const result=await session.run(handle,provider(async request=>{calls++;return answer(request);}));assert.equal(result.state,'COMMITTED');assert.equal(calls,1);const status=await f.s.aiPresentationStatus({topicId:f.topic.id}),candidate=status.topics[0].candidate;assert.ok(candidate);assert.equal(status.topics[0].presentation,null);const receipts=await rows(f.s,'organizerWorkItems');assert.ok(receipts.some(x=>x.state==='ACKNOWLEDGED'));await f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:0,expectedCandidateKey:aiCandidateKey(candidate),candidateDecisions:Object.fromEntries(candidate.changedFields.map(k=>[k,'adopt'])),operationId:crypto.randomUUID()});assert.equal((await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0].presentation.currentView,'Synthetic conclusion');assert.ok((await rows(f.s,'revisions')).length);assert.equal((await session.run(handle,provider(()=>{throw Error('must not retry');}))).state,'COMMITTED');});

test('multiple children explicitly defer without jobs; absent trusted profile/authority does not activate',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module();assert.deepEqual(await new LocalOrganizeSession(f.s,options).prepare({topicId:f.topic.id,children:2}),{state:'DEFER',reason:'multiple_children_not_supported'});await assert.rejects(new LocalOrganizeSession(f.s).prepare({topicId:f.topic.id}),{code:'UNAVAILABLE'});await assert.rejects(new LocalOrganizeSession(f.s,{...options,resolveAuthority:null}).prepare({topicId:f.topic.id}),{code:'UNAVAILABLE'});assert.deepEqual(await rows(f.s,'organizerJobs'),[]);});
test('held response after actual Input exclusion refuses candidate and coverage',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});assert.equal((await session.run(h,provider(async r=>{await inputEdit(f.s,f.input.id,{excluded:true});return answer(r);}))).state,'OUTCOME_UNKNOWN');assert.equal((await f.s.input(f.input.id)).excluded,true);assert.equal((await rows(f.s,'meta')).some(x=>x.id==='aiPresentation:'+f.topic.id&&x.candidate),false);assert.equal((await rows(f.s,'organizerWorkItems')).some(x=>x.state==='ACKNOWLEDGED'),false);});
test('actual style A-B-A invalidates prepared execution and does not dispatch',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});for(const value of ['concise','balanced']){const p=await f.s.aiStylePreference();await f.s.updatePreferences({aiOrganizeStyle:{version:1,value,expectedRevision:p.revision,expectedEpoch:p.epoch}});}let calls=0;await assert.rejects(session.run(h,provider(()=>{calls++;})),{code:'STALE_BASE'});assert.equal(calls,0);});
test('restore epoch and current human body changes reject prepared bodies before provider',async()=>{for(const mutate of [f=>f.s.foundationWrite(t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic-new-epoch'})),f=>inputEdit(f.s,f.input.id,{libraryText:'SYNTHETIC changed evidence'})]){const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});await mutate(f);await assert.rejects(session.assemble(h),e=>['STALE_BASE','CANCELLED'].includes(e.code));}});
test('invalid exact spans and absent original-mode spans never ACK or produce a candidate',async()=>{for(const corrupt of [r=>({...answer(r),sourceSpans:[]}),r=>{const a=answer(r);a.sourceSpans[0].revision='forged';return a;},r=>{const a=answer(r);a.sourceSpans[0].end--;return a;}]){const f=await fixture(),p=await f.s.aiStylePreference();await f.s.updatePreferences({aiOrganizeStyle:{version:1,value:'original',expectedRevision:p.revision,expectedEpoch:p.epoch}});const {LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});assert.equal((await session.run(h,provider(corrupt))).state,'OUTCOME_UNKNOWN');assert.equal((await rows(f.s,'organizerWorkItems')).some(x=>x.state==='ACKNOWLEDGED'),false);assert.equal((await rows(f.s,'meta')).some(x=>x.candidate),false);}});
test('original, balanced and concise use actual bound style and existing candidate projection',async()=>{for(const value of ['original','balanced','concise']){const f=await fixture(),p=await f.s.aiStylePreference();await f.s.updatePreferences({aiOrganizeStyle:{version:1,value,expectedRevision:p.revision,expectedEpoch:p.epoch}});const {LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});assert.equal((await session.run(h,provider(r=>{assert.equal(r.style.value,value);assert.equal(r.usage.organizeStyle.value,value);return answer(r);}))).state,'COMMITTED');}});
test('real candidate transaction abort rolls back candidate/checkpoint/coverage; retry uses same response without another call',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id}),original=f.s.repository.transaction.bind(f.s.repository);let inject=true,calls=0;f.s.repository.transaction=(write,run,...rest)=>original(write,async t=>run(new Proxy(t,{get(target,key){if(key==='put')return async(table,row,...args)=>{if(inject&&table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED')throw Error('synthetic acknowledgement write abort');return target.put(table,row,...args);};const value=target[key];return typeof value==='function'?value.bind(target):value;}})),...rest);try{await assert.rejects(session.run(h,provider(r=>{calls++;return answer(r);})),{code:'STORAGE_FAILED'});assert.equal((await rows(f.s,'meta')).some(x=>x.candidate),false);assert.equal((await rows(f.s,'meta')).some(x=>x.id==='aiOrganizerCheckpoint'),false);inject=false;assert.equal((await session.run(h,provider(()=>{throw Error('retry must not dispatch');}))).state,'COMMITTED');assert.equal(calls,1);}finally{f.s.repository.transaction=original;}});
test('unknown response survives session disposal and cannot remint an attempt',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});assert.equal((await session.run(h,provider(()=>{throw Error('synthetic lost result');}))).state,'OUTCOME_UNKNOWN');session.dispose();await assert.rejects(session.assemble(h),{code:'UNAVAILABLE'});const again=new LocalOrganizeSession(f.s,options),same=await again.prepare({topicId:f.topic.id});assert.equal(same.jobId,h.jobId);await assert.rejects(again.run(same,provider(()=>{throw Error('must not dispatch');})),{code:'OUTCOME_UNKNOWN'});const attempts=await rows(f.s,'organizerUsage');assert.equal(attempts.length,1);assert.equal(attempts[0].attemptCount,1);});
test('provider cannot rewrite private source material or revision to authorize its response',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});assert.equal((await session.run(h,provider(r=>{r.inputs[0].text='FORGED';return answer(r);}))).state,'OUTCOME_UNKNOWN');assert.equal((await rows(f.s,'meta')).some(x=>x.candidate),false);});
test('forged/cross-session handles cannot assemble source bodies',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),a=new LocalOrganizeSession(f.s,options),b=new LocalOrganizeSession(f.s,options),h=await a.prepare({topicId:f.topic.id});await assert.rejects(b.assemble(h),{code:'UNAVAILABLE'});await assert.rejects(a.assemble({...h}),{code:'UNAVAILABLE'});});
test('original literal spans preserve complete graphemes and reject splitting combining text',async()=>{const f=await fixture(),entry=await f.s.entry(f.made.id);await f.s.editEntry({id:f.made.id,expectedRevision:entry.revision,expectedInputRevision:entry.currentInputRevision,changes:{body:'SYNTHETIC e\u0301😀 content'},operationId:crypto.randomUUID()});const p=await f.s.aiStylePreference();await f.s.updatePreferences({aiOrganizeStyle:{version:1,value:'original',expectedRevision:p.revision,expectedEpoch:p.epoch}});const {LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id});assert.equal((await session.run(h,provider(r=>{const start=r.inputs[0].text.indexOf('e\u0301');return {presentation:{topicId:r.topicId,currentView:'e',evidenceEntryIds:[r.inputs[0].ref]},sourceSpans:[{field:'currentView',index:null,entryId:r.inputs[0].ref,revision:r.inputs[0].revision,start,end:start+1}]};}))).state,'OUTCOME_UNKNOWN');});
test('human edit to existing accepted projection while response is held remains intact',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),first=new LocalOrganizeSession(f.s,options),h=await first.prepare({topicId:f.topic.id});await first.run(h,provider(answer));let candidate=(await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0].candidate;await f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:0,expectedCandidateKey:aiCandidateKey(candidate),candidateDecisions:Object.fromEntries(candidate.changedFields.map(k=>[k,'adopt'])),operationId:crypto.randomUUID()});await inputEdit(f.s,f.input.id,{libraryText:'SYNTHETIC changed but still readable'});const next=new LocalOrganizeSession(f.s,options),handle=await next.prepare({topicId:f.topic.id});await assert.rejects(next.run(handle,provider(async r=>{const status=(await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0];await f.s.editAIPresentation({topicId:f.topic.id,expectedRevision:status.presentation.revision,field:'currentView',value:'SYNTHETIC human protected value',operationId:crypto.randomUUID()});return answer(r);})),e=>['STALE_BASE','CANCELLED'].includes(e.code));const status=(await f.s.aiPresentationStatus({topicId:f.topic.id})).topics[0];assert.equal(status.presentation.currentView,'SYNTHETIC human protected value');assert.equal(status.presentation.protections.currentView,true);assert.equal(status.candidate,null);});
test('final request byte bound includes exact Foundation usage metadata before the actual provider call',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id}),assembled=await session.assemble(h),limit=new TextEncoder().encode(JSON.stringify(assembled)).length+1;f.s.organizerBudget={limits:{...f.s.organizerBudget.limits,maxRequestBytes:limit}};let calls=0;const result=await session.run(h,provider(r=>{calls++;return answer(r);}));assert.equal(calls,0);assert.equal(result.state,'OUTCOME_UNKNOWN');assert.equal((await rows(f.s,'organizerWorkItems')).some(x=>x.state==='ACKNOWLEDGED'),false);assert.equal((await rows(f.s,'meta')).some(x=>x.candidate),false);});
test('recorded response whose commit aborted cannot be redispatched after private session disposal',async()=>{const f=await fixture(),{LocalOrganizeSession}=await module(),session=new LocalOrganizeSession(f.s,options),h=await session.prepare({topicId:f.topic.id}),original=f.s.repository.transaction.bind(f.s.repository);let calls=0;f.s.repository.transaction=(write,run,...rest)=>original(write,async t=>run(new Proxy(t,{get(target,key){if(key==='put')return async(table,row,...args)=>{if(table==='organizerWorkItems'&&row.state==='ACKNOWLEDGED')throw Error('synthetic final ACK abort');return target.put(table,row,...args);};const value=target[key];return typeof value==='function'?value.bind(target):value;}})),...rest);try{await assert.rejects(session.run(h,provider(r=>{calls++;return answer(r);})),{code:'STORAGE_FAILED'});}finally{f.s.repository.transaction=original;}assert.equal((await rows(f.s,'organizerUsage'))[0].state,'RESPONSE_RECORDED');session.dispose();const next=new LocalOrganizeSession(f.s,options),same=await next.prepare({topicId:f.topic.id});assert.equal(same.jobId,h.jobId);await assert.rejects(next.run(same,provider(r=>{calls++;return answer(r);})),{code:'OUTCOME_UNKNOWN'});assert.equal(calls,1);assert.equal((await rows(f.s,'organizerUsage'))[0].attemptCount,1);assert.equal((await rows(f.s,'meta')).some(x=>x.candidate),false);});
