import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,response,success,rows,meta} from './harness/original-complete.mjs';
import {DeepSeekOrganizerProvider} from '../core/organizer/deepseek.js';
import {AIPresentationRunner,aiPresentationStatus,editAIPresentation,validateAIPresentation} from '../core/organizer/ai-presentation.js';
import {inputEdit} from './harness/thought-m1.mjs';
export function synthesis(request){const ids=request.inputs.map(x=>x.ref);return {topicId:request.topicCandidates[0].id,blockSummary:'虚构主题的理解逐步清晰',currentView:'用小实验验证想法，保留变化过程。',keyInformation:[{text:'这是有原文依据的虚构信息。',evidenceEntryIds:ids}],preferences:[],decisions:[{text:'先保留证据。',evidenceEntryIds:ids}],judgments:[],openQuestions:[],possibleEvolution:[],evidenceEntryIds:ids};}
export async function aiFixture({fetchImpl,timeoutMs=1000}={}){const f=await completeFixture({texts:['虚构主题 A：保留输入证据。','虚构主题 B：文学创作。','虚构主题 C：职业选择。'],fetchImpl:async(_url,init)=>success(init,items=>items.map((r,i)=>({...r,topic:{proposedName:'主题 '+['A','B','C'][i]}})))});await f.runner.wake({userActionId:'original-baseline'});const calls=[];const provider=new DeepSeekOrganizerProvider({limits:f.s.organizerBudget.limits,timeoutMs,fetchImpl:async(url,init)=>{const request=JSON.parse(JSON.parse(init.body).messages[1].content);calls.push(request);return fetchImpl?fetchImpl(request):response({choices:[{message:{content:JSON.stringify(synthesis(request))}}]});}});return {...f,calls,ai:new AIPresentationRunner(f.s,{provider,credentials:f.credentials})};}
const action=()=>({userActionId:crypto.randomUUID()});
test('three Topic full chain: cached B, A/C delta, one click updates only first affected Topic without changing source layer',async()=>{const f=await aiFixture(),state=await f.s.aiPresentationStatus(),b=state.topics[1];const all=await rows(f.s,'topics'),bRow=all.find(x=>x.id===b.topicId),placements=(await rows(f.s,'placements')).filter(x=>x.topicId===b.topicId),entry=(await rows(f.s,'thoughts')).find(x=>x.id===placements[0].entryId),deps=(await rows(f.s,'dependencies')).filter(x=>x.targetId===entry.id);const versions={[entry.id]:JSON.stringify([entry.revision,entry.dependencyRevision||0,await Promise.all(deps.map(async d=>{const i=(await rows(f.s,'inputStates')).find(x=>x.id===d.inputId);return [d.inputId,i.contentRevision,i.lastRemovalSequence||0];}))])};await f.s.foundationWrite(async t=>{await t.put('meta',{id:'aiOrganizerCheckpoint',topicVersions:{[bRow.id]:versions},inputVersions:{}});await t.put('meta',{id:'aiPresentation:'+bRow.id,...synthesis({inputs:[{ref:entry.id}],topicCandidates:[{id:bRow.id}]}),revision:1,schemaVersion:1,protections:{},updatedAt:f.s.clock()});});const before=await Promise.all(['thoughts','records','inputStates','topics','sections','placements'].map(n=>rows(f.s,n)));assert.equal((await aiPresentationStatus(f.s)).pendingTopics,2);const result=await f.ai.wake(action());assert.equal(result.completed,true);assert.equal(f.calls.length,1);assert.notEqual(f.calls[0].topicCandidates[0].id,b.topicId);assert.equal(f.calls[0].inputs.length,1);assert.equal((await aiPresentationStatus(f.s)).pendingTopics,1);assert.deepEqual(await Promise.all(['thoughts','records','inputStates','topics','sections','placements'].map(n=>rows(f.s,n))),before);assert.ok((await aiPresentationStatus(f.s)).topics.find(x=>x.topicId===result.topicId).presentation.currentView);});
test('cached status reads and worker startup do not call provider; next Topic requires explicit click',async()=>{const f=await aiFixture();await f.ai.wake(action());for(let i=0;i<3;i++)await aiPresentationStatus(f.s);await new AIPresentationRunner(f.s,{provider:f.ai.provider,credentials:f.credentials}).reconcileInterrupted();assert.equal(f.calls.length,1);await f.ai.wake(action());assert.equal(f.calls.length,2);assert.notEqual(f.calls[0].topicCandidates[0].id,f.calls[1].topicCandidates[0].id);});
for(const [code,implementation]of [['INVALID_CREDENTIAL',()=>response({},401)],['RATE_LIMITED',()=>response({},429)],['PROVIDER_UNAVAILABLE',()=>response({},500)],['NETWORK_ERROR',()=>{throw Error('private');}],['PROVIDER_TIMEOUT',()=>new Promise(()=>{})],['INVALID_JSON',()=>response({choices:[{message:{content:'bad'}}]})],['INVALID_SCHEMA',r=>response({choices:[{message:{content:JSON.stringify({...synthesis(r),topicId:'wrong-topic'})}}]})]])test(code+' leaves checkpoint/results untouched with one request and no retry',async()=>{const f=await aiFixture({fetchImpl:implementation,timeoutMs:30}),before=await meta(f.s,'aiOrganizerCheckpoint');const result=await f.ai.wake(action());assert.equal(result.error,code);assert.equal(f.calls.length,1);assert.deepEqual(await meta(f.s,'aiOrganizerCheckpoint'),before);assert.equal((await aiPresentationStatus(f.s)).topics.filter(t=>t.presentation).length,0);await aiPresentationStatus(f.s);assert.equal(f.calls.length,1);});
test('protected presentation fields survive a later model update; successful checkpoint clears only delta',async()=>{const f=await aiFixture();for(let i=0;i<3;i++)await f.ai.wake(action());const status=await aiPresentationStatus(f.s),p=status.topics[0].presentation;await editAIPresentation(f.s,{topicId:p.topicId,field:'currentView',value:'用户亲自写下的理解',expectedRevision:p.revision});const entry=(await rows(f.s,'thoughts')).find(e=>e.id===p.evidenceEntryIds[0]);await f.s.editEntry({id:entry.id,expectedRevision:entry.revision,changes:{body:entry.thoughtText+' 新的用户修正'},operationId:crypto.randomUUID()});assert.equal((await aiPresentationStatus(f.s)).pendingTopics,1);await f.ai.wake(action());const next=(await aiPresentationStatus(f.s)).topics.find(t=>t.topicId===p.topicId).presentation;assert.equal(next.currentView,'用户亲自写下的理解');assert.equal(next.protections.currentView,true);assert.equal((await aiPresentationStatus(f.s)).pendingTopics,0);assert.equal(f.calls[3].inputs.length,1);});
test('removed Inputs are excluded; old AI evidence is hidden and unrelated Topic never sent',async()=>{const f=await aiFixture();await f.ai.wake(action());const p=(await aiPresentationStatus(f.s)).topics.find(t=>t.presentation).presentation,dep=(await rows(f.s,'dependencies')).find(d=>d.targetId===p.evidenceEntryIds[0]);await inputEdit(f.s,dep.inputId,{excluded:true});const status=await aiPresentationStatus(f.s);assert.equal(status.topics.find(t=>t.topicId===p.topicId).presentation,null);await f.ai.wake(action());assert.equal(f.calls.length,1);assert.equal(await meta(f.s,'aiPresentation:'+p.topicId),undefined);assert.equal((await f.s.dualViewStatus()).ai.counts.removedInput,0);});
test('same action cannot send twice and repeated clicks during flight send once',async()=>{let release;const f=await aiFixture({fetchImpl:r=>new Promise(resolve=>{release=()=>resolve(response({choices:[{message:{content:JSON.stringify(synthesis(r))}}]}));})}),a=action(),pending=f.ai.wake(a);while(!release)await new Promise(r=>setTimeout(r,5));assert.equal((await f.ai.wake(action())).error,'REQUEST_ALREADY_IN_FLIGHT');release();await pending;assert.equal((await f.ai.wake(a)).error,'REQUEST_ALREADY_IN_FLIGHT');assert.equal(f.calls.length,1);});
test('worker dies after send: old response cannot commit and restart never resends',async()=>{let release;const f=await aiFixture({fetchImpl:r=>new Promise(resolve=>{release=()=>resolve(response({choices:[{message:{content:JSON.stringify(synthesis(r))}}]}));})}),pending=f.ai.wake(action());while(!release)await new Promise(r=>setTimeout(r,5));await new AIPresentationRunner(f.s,{provider:f.ai.provider,credentials:f.credentials}).reconcileInterrupted();release();assert.equal((await pending).error,'OUTCOME_UNKNOWN');assert.equal(f.calls.length,1);assert.equal((await aiPresentationStatus(f.s)).topics.filter(t=>t.presentation).length,0);});
test('credential clear aborts AI request without retry or checkpoint write',async()=>{const f=await aiFixture({fetchImpl:()=>new Promise(()=>{})}),pending=f.ai.wake(action());while(!f.calls.length)await new Promise(r=>setTimeout(r,5));await f.ai.stop();await f.credentials.disable();assert.equal((await pending).error,'CANCELLED');assert.equal(f.calls.length,1);assert.equal(await meta(f.s,'aiOrganizerCheckpoint'),undefined);});
test('AI field edit during request forces CAS failure and preserves the human edit',async()=>{const f=await aiFixture();await f.ai.wake(action());const topic=(await aiPresentationStatus(f.s)).topics.find(t=>t.presentation),p=topic.presentation,e=await f.s.entry(p.evidenceEntryIds[0]);await f.s.editEntry({id:e.id,expectedRevision:e.revision,changes:{body:e.body+' 变化'},operationId:crypto.randomUUID()});f.ai.provider.fetchImpl=async(_url,init)=>{await editAIPresentation(f.s,{topicId:p.topicId,field:'blockSummary',value:'人工维护',expectedRevision:p.revision});return response({choices:[{message:{content:JSON.stringify(synthesis(JSON.parse(JSON.parse(init.body).messages[1].content)))}}]});};const before=await meta(f.s,'aiOrganizerCheckpoint');assert.equal((await f.ai.wake(action())).error,'STALE_BASE');assert.deepEqual(await meta(f.s,'aiOrganizerCheckpoint'),before);assert.equal((await meta(f.s,'aiPresentation:'+p.topicId)).blockSummary,'人工维护');});
test('ledger failure is fail-closed with zero requests',async()=>{const f=await aiFixture(),write=f.s.foundationWrite.bind(f.s);f.s.foundationWrite=fn=>write(async t=>{const put=t.put.bind(t);t.put=(name,value)=>{if(name==='meta'&&String(value.id).startsWith('aiPresentationRequest:'))throw {code:'STORAGE_FAILED'};return put(name,value);};return fn(t);});assert.equal((await f.ai.wake(action())).error,'STORAGE_FAILED');assert.equal(f.calls.length,0);});
test('commit failure rolls back presentation, receipt and checkpoint together',async()=>{const f=await aiFixture(),write=f.s.foundationWrite.bind(f.s);f.s.foundationWrite=fn=>write(async t=>{const put=t.put.bind(t);t.put=(name,value)=>{if(name==='operationReceipts'&&value.namespace==='ai-presentation')throw {code:'STORAGE_FAILED'};return put(name,value);};return fn(t);});assert.equal((await f.ai.wake(action())).error,'STORAGE_FAILED');assert.equal(f.calls.length,1);assert.equal(await meta(f.s,'aiOrganizerCheckpoint'),undefined);assert.equal((await aiPresentationStatus(f.s)).topics.filter(t=>t.presentation).length,0);});
test('a removed Input stays excluded after dependency cleanup even when its Thought was human-edited',async()=>{const f=await aiFixture(),entry=(await f.s.entryPage()).items[0],dep=(await rows(f.s,'dependencies')).find(d=>d.targetId===entry.id);await f.s.editEntry({id:entry.id,expectedRevision:entry.revision,changes:{body:'保留人工内容但不允许发送已移除来源'},operationId:crypto.randomUUID()});await inputEdit(f.s,dep.inputId,{excluded:true});await f.s.drainInvalidations();for(let i=0;i<3;i++)await f.ai.wake(action());assert.ok(f.calls.every(r=>r.inputs.every(x=>x.ref!==entry.id)));});
test('bounded delta chunks never send the entire large Topic in one request',async()=>{const f=await completeFixture({texts:Array.from({length:15},(_,i)=>'虚构共同主题的第 '+i+' 条想法。')});for(let i=0;i<3;i++)await f.runner.wake({userActionId:'original-'+i});const calls=[],provider=new DeepSeekOrganizerProvider({limits:f.s.organizerBudget.limits,fetchImpl:async(_url,init)=>{const r=JSON.parse(JSON.parse(init.body).messages[1].content);calls.push(r);return response({choices:[{message:{content:JSON.stringify(synthesis(r))}}]});}}),ai=new AIPresentationRunner(f.s,{provider,credentials:f.credentials});await ai.wake(action());assert.equal(calls[0].inputs.length,8);assert.equal((await aiPresentationStatus(f.s)).pendingTopics,1);await ai.wake(action());assert.equal(calls[1].inputs.length,7);assert.equal((await aiPresentationStatus(f.s)).pendingTopics,0);});
test('AI and Original share a durable in-flight cost gate',async()=>{const f=await aiFixture();await f.s.foundationWrite(async t=>{await t.put('meta',{id:'originalProviderRequestCurrent',requestId:'other-profile'});await t.put('meta',{id:'originalProviderRequest:other-profile',state:'sent'});});assert.equal((await f.ai.wake(action())).error,'REQUEST_ALREADY_IN_FLIGHT');assert.equal(f.calls.length,0);});
test('all statements reject evidence outside selected/cached approved entries',()=>{const request={inputs:[{ref:'approved'}],context:[],topicCandidates:[{id:'topic'}]},base=synthesis(request);for(const field of ['keyInformation','preferences','decisions','judgments','openQuestions','possibleEvolution'])assert.deepEqual(validateAIPresentation({...base,[field]:[{text:'invented',evidenceEntryIds:['outside']}]},request)[field],[]);assert.throws(()=>validateAIPresentation({...base,topicId:'other-topic'},request));});
test('budget exceeded prevents AI fetch without altering baseline',async()=>{const f=await aiFixture();const budget=await meta(f.s,'organizer-budget');await f.s.foundationWrite(t=>t.put('meta',{...budget,daily:{...budget.daily,requests:512}}));assert.equal((await f.ai.wake(action())).error,'BUDGET_EXCEEDED');assert.equal(f.calls.length,0);assert.equal(await meta(f.s,'aiOrganizerCheckpoint'),undefined);});
test('missing credential fails locally and never dispatches',async()=>{const f=await aiFixture();await f.credentials.disable();assert.equal((await f.ai.wake(action())).error,'CREDENTIAL_FAILURE');assert.equal(f.calls.length,0);});
