import {tmpdir} from 'node:os';
import {join} from 'node:path';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,cp,rm,readFile,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
const out=new URL('../work/v081-backup-e2e/',import.meta.url).pathname;
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
async function invariants(h){const worker=h.context.serviceWorkers().find(w=>w.url().includes('/background/service-worker.js'));return worker.evaluate(async()=>{const s=globalThis.v081Synthetic.store;await s.finishFoundation();const values=await s.run(()=>s.repository.transaction(false,async t=>{const out={};for(const n of ['records','blocks','thoughts','topics','sections','placements','provenance','revisions','tombstones','inputRemovals','thoughtSuppressions'])out[n]=await t.all(n);return out;}));const digest=async value=>{const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('');};return {counts:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,v.length])),entries:await digest(values.thoughts.map(x=>[x.id,x.thoughtText,x.title?.trim()?x.title:undefined,x.note,x.revision,x.protections,x.sourceRecordIds])),evidence:await digest(values.provenance),revisions:await digest(values.revisions.map(x=>[x.id,x.before,x.after,x.reason,x.important]))};});}
test('visible long-term Settings backup → validation preview → isolated empty-library restore',{timeout:240000},async()=>{
 await mkdir(out,{recursive:true});const root=new URL('../',import.meta.url).pathname,dir=await mkdtemp(join(tmpdir(),'paia-v081-backup-'));await cp(root,dir,{recursive:true,filter:path=>{const rel=path.startsWith(root)?path.slice(root.length):path;return !/^(?:\.git|work|outputs)(?:\/|$)/.test(rel);}});const workerPath=join(dir,'background/service-worker.js');await writeFile(workerPath,(await readFile(workerPath,'utf8'))+`\nimport {seedLongTerm} from '../tests/fixtures/long-term-v081.mjs';globalThis.v081Synthetic={store,seed:()=>seedLongTerm(store)};\n`);let h=await FakeChatGPT.start({headless:false,extensionPath:dir}),before,fixture;
 try{let p=h.archive;await p.setViewportSize({width:1440,height:1000});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();const worker=h.context.serviceWorkers().find(w=>w.url().includes('/background/service-worker.js'));
  fixture=await worker.evaluate(async()=>{return globalThis.v081Synthetic.seed();});before=await invariants(h);assert.equal(before.counts.records,499);assert.equal(before.counts.thoughts,360);
  await p.locator('[data-view=thoughts]').click();await eventually(async()=>await p.locator('.topic-tile').count()===30);await p.screenshot({path:out+'01-long-term-grid.png',fullPage:true});await p.locator('[data-topic-id="'+fixture.topicIds[0]+'"]').click();await p.locator('#topic-outline>summary').click();await eventually(async()=>await p.locator('#topic-section-nav').isVisible());await p.locator('#topic-section-nav button').filter({hasText:'后续修正'}).click();await p.screenshot({path:out+'02-section-navigation.png',fullPage:true});await p.locator('#topic-search').fill('合成备注');await eventually(async()=>/1 条匹配内容/.test(await p.locator('#topic-search-count').textContent()));await p.screenshot({path:out+'03-local-note-search.png',fullPage:true});
  await p.locator('.sidebar [data-view=settings]').click();await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-backup-key-must-not-export'}});const download=p.waitForEvent('download');await p.locator('#backup-create').click();const file=await download;await file.saveAs(out+'synthetic.paia-backup');await eventually(async()=>/已生成/.test(await p.locator('#backup-status').textContent()));const content=await readFile(out+'synthetic.paia-backup','utf8');assert.doesNotMatch(content,/synthetic-backup-key-must-not-export|apiKey|recordIndex/);await p.screenshot({path:out+'04-backup-created.png',fullPage:true});
  await p.locator('#backup-file').setInputFiles(out+'synthetic.paia-backup');await eventually(async()=>await p.locator('#backup-preview').isVisible());assert.match(await p.locator('#backup-preview-content').innerText(),/499 条 Input/);assert.equal(await p.locator('#backup-restore').isDisabled(),true);await p.screenshot({path:out+'05-nonempty-protection.png',fullPage:true});assert.deepEqual((await invariants(h)).counts,before.counts);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);await h.close();
  h=await FakeChatGPT.start({headless:false,extensionPath:dir});p=h.archive;await p.setViewportSize({width:1440,height:1000});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await p.locator('.sidebar [data-view=settings]').click();await p.locator('#backup-file').setInputFiles(out+'synthetic.paia-backup');await eventually(async()=>await p.locator('#backup-preview').isVisible(),'full backup preview',60000);assert.equal(await p.locator('#backup-restore').isEnabled(),true);assert.match(await p.locator('#backup-preview-content').innerText(),/360 条思想内容/);await p.screenshot({path:out+'06-empty-restore-preview.png',fullPage:true});await p.locator('#backup-restore').click();await eventually(async()=>/恢复已完成/.test(await p.locator('#backup-status').textContent()),'atomic restore',60000);const after=await invariants(h);assert.deepEqual(after,before);assert.equal((await rpc(p,'GET_DEEPSEEK_STATUS')).hasCredential,false);await p.screenshot({path:out+'07-restore-complete.png',fullPage:true});
  await h.restartWorker();await p.reload();await p.locator('[data-view=thoughts]').click();await eventually(async()=>await p.locator('.topic-tile').count()===30);await p.screenshot({path:out+'08-restored-grid-after-restart.png',fullPage:true});await p.locator('#thought-search').fill('明确维护的产品原则');await eventually(async()=>await p.locator('.topic-index-row').count()>0,'restored local search',60000);assert.equal(h.deepSeekRequests.length,0);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);await writeFile(out+'acceptance.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,capturedInputs:500,...before.counts,backupBytes:Buffer.byteLength(content),invariantsEqual:true,nonemptyRefused:true,keyExcluded:true,restoreAfterRestart:true,externalRequests:h.externalRequests,providerRequests:0,errors:h.errors},null,2));
 }catch(e){await h.archive.screenshot({path:out+'failure.png',fullPage:true}).catch(()=>{});await writeFile(out+'failure.json',JSON.stringify({message:e.message,errors:h.errors,status:await h.archive.locator('#backup-status').textContent().catch(()=>null)},null,2));throw e;}finally{await h.close();await rm(dir,{recursive:true,force:true});}
});
