import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,rows,meta} from './harness/original-complete.mjs';
import {BackupService} from '../core/backup-service.js';
import {BackupValidator,backupHash} from '../core/backup-format.js';
const op=()=>crypto.randomUUID();
export async function exported(service){const {sessionId,header}=await service.beginExport(),items=[header];let sequence=0;for(;;){const p=await service.exportPage({sessionId,sequence:sequence++});items.push(...p.items);if(p.done)break;}return items;}
export async function prepared(service,items){const {sessionId}=await service.beginRestore();for(let i=0;i<items.length;i+=30)await service.stageRestore({sessionId,items:items.slice(i,i+30)});return {sessionId,preview:await service.previewRestore({sessionId})};}
test('formal backup round trip preserves working text, provenance, human edits and important revisions',async()=>{
 const f=await completeFixture();await f.runner.wake({userActionId:op()});const e=(await rows(f.s,'thoughts'))[0];await f.s.editEntry({id:e.id,expectedRevision:e.revision,changes:{body:e.thoughtText+' 人工维护的独立内容'},operationId:op()});await f.s.setOrganizerControls({readingSort:'desc',libraryView:'ai'});await f.s.drainLibraryMaintenance();const items=await exported(new BackupService(f.s,{appVersion:'0.8.1'}));assert.equal(items[0].format,'PAIA Backup');assert.doesNotMatch(JSON.stringify(items),/synthetic-test-key|apiKey|deepseek-api-key|recordIndex|blockIndex/);const validator=new BackupValidator();for(const item of items)await validator.add(item);assert.equal(validator.preview().counts.entries,5);
 const target=await completeFixture({texts:[]}),service=new BackupService(target.s,{appVersion:'0.8.1'}),stage=await prepared(service,items);assert.equal(stage.preview.canRestore,true);const result=await service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});assert.equal(result.restored,true);assert.equal((await rows(target.s,'records')).length,5);assert.equal((await target.s.entry(e.id)).body,e.thoughtText+' 人工维护的独立内容');assert.deepEqual(await rows(target.s,'provenance'),await rows(f.s,'provenance'));assert.deepEqual((await rows(target.s,'revisions')).map(r=>[r.id,r.before,r.after,r.important]),(await rows(f.s,'revisions')).map(r=>[r.id,r.before,r.after,r.important]));assert.equal((await target.s.organizerControls()).readingSort,'desc');assert.equal((await target.s.originalOrganizerStatus()).pendingInput,(await f.s.originalOrganizerStatus()).pendingInput);assert.equal(target.requests.length,0);assert.equal((await target.s.libraryIndexPage()).items.length,1);
});
test('backup validates corruption/truncation/unknown schema and never accepts credentials',async()=>{const f=await completeFixture(),items=await exported(new BackupService(f.s,{appVersion:'0.8.1'}));const changed=structuredClone(items);changed[1].value.id+='tampered';const service=new BackupService(f.s,{appVersion:'0.8.1'});await assert.rejects(()=>prepared(service,changed));await assert.rejects(()=>prepared(service,items.slice(0,-1)));const bad=structuredClone(items);bad[0].schemaVersion=999;await assert.rejects(()=>prepared(service,bad));const key=structuredClone(items);key[1].value.apiKey='forbidden';await assert.rejects(()=>prepared(service,key));});
test('existing user work is never silently overwritten, even after valid preview',async()=>{const f=await completeFixture(),items=await exported(new BackupService(f.s,{appVersion:'0.8.1'})),s=new BackupService(f.s,{appVersion:'0.8.1'}),stage=await prepared(s,items);assert.equal(stage.preview.canRestore,false);assert.equal(stage.preview.reason,'BACKUP_TARGET_NOT_EMPTY');await assert.rejects(()=>s.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity}));assert.equal((await rows(f.s,'records')).length,5);});
test('purge fences exclude deleted text and reject resurrection from an older external backup',async()=>{const f=await completeFixture();await f.runner.wake({userActionId:op()});const service=new BackupService(f.s,{appVersion:'0.8.1'}),old=await exported(service),source=(await rows(f.s,'records'))[0];await f.s.permanentDelete(source.id);await f.s.drainPurgeCleanup();const after=await exported(service);assert.ok(!JSON.stringify(after).includes(source.value.originalText));const target=await completeFixture({texts:[]});const fences=await rows(f.s,'tombstones');await target.s.foundationWrite(async t=>{for(const row of fences)await t.put('tombstones',row);});const recovery=new BackupService(target.s,{appVersion:'0.8.1'}),stage=await prepared(recovery,old);assert.equal(stage.preview.reason,'BACKUP_PURGE_CONFLICT');await assert.rejects(()=>recovery.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity}));assert.equal((await rows(target.s,'records')).length,0);});
test('export detects data edits between chunks and refuses inconsistent snapshot',async()=>{const f=await completeFixture(),service=new BackupService(f.s,{appVersion:'0.8.1'}),session=await service.beginExport();const source=(await rows(f.s,'records'))[0];await f.s.update(source.id,{note:'合成并发备注'});await assert.rejects(()=>service.exportPage({sessionId:session.sessionId,sequence:0}),e=>e.code==='BACKUP_CHANGED');});
test('restore failure rolls back all content and a worker loss leaves no persisted staging',async()=>{const f=await completeFixture();await f.runner.wake({userActionId:op()});const items=await exported(new BackupService(f.s,{appVersion:'0.8.1'})),target=await completeFixture({texts:[]}),service=new BackupService(target.s,{appVersion:'0.8.1'}),stage=await prepared(service,items),transaction=target.s.repository.transaction.bind(target.s.repository);target.s.repository.transaction=(write,fn,stores)=>transaction(write,async t=>{if(write){const put=t.put.bind(t);t.put=(name,row)=>{if(name==='thoughts')throw {code:'STORAGE_FAILED'};return put(name,row);};}return fn(t);},stores);await assert.rejects(()=>service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity}));assert.equal((await rows(target.s,'records')).length,0);assert.equal((await rows(target.s,'blocks')).length,0);assert.equal((await rows(target.s,'topics')).length,0);assert.equal((await rows(target.s,'importBatches')).length,0);await assert.rejects(()=>new BackupService(target.s).previewRestore({sessionId:stage.sessionId}));});


test('concurrent page delivery is idempotent and a cached page cannot bypass a later purge fence',async()=>{
 const f=await completeFixture(),service=new BackupService(f.s),session=await service.beginExport(),options={sessionId:session.sessionId,sequence:0};const [a,b]=await Promise.all([service.exportPage(options),service.exportPage(options)]);assert.deepEqual(a,b);const source=(await rows(f.s,'records'))[0];await f.s.permanentDelete(source.id);await assert.rejects(()=>service.exportPage(options),e=>e.code==='BACKUP_CHANGED');
});
test('restore staging cannot be interleaved by concurrent message calls',async()=>{
 const f=await completeFixture(),service=new BackupService(f.s),items=await exported(service),session=await service.beginRestore();const first=service.stageRestore({sessionId:session.sessionId,items:[items[0]]});await assert.rejects(()=>service.stageRestore({sessionId:session.sessionId,items:[items[1]]}),e=>e.code==='BACKUP_BUSY');await first;for(let i=1;i<items.length;i+=30)await service.stageRestore({sessionId:session.sessionId,items:items.slice(i,i+30)});assert.equal((await service.previewRestore(session)).itemCount,items.length-2);
});

test('settings interruption after atomic data commit is recovered idempotently after restart',async()=>{
 const source=await completeFixture();await source.s.updatePreferences({timeEmphasis:'standard',timeDisplay:'date_and_seconds'});const items=await exported(new BackupService(source.s)),target=await completeFixture({texts:[]}),service=new BackupService(target.s),stage=await prepared(service,items),save=target.storage.set;
 target.storage.set=async()=>{throw new Error('Synthetic local settings write interruption');};await assert.rejects(()=>service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity}));assert.equal((await rows(target.s,'records')).length,5);assert.ok(await meta(target.s,'backup-recovery-settings'));target.storage.set=save;await target.s.repository.close();const restarted=new target.s.constructor(target.storage,{indexedDB:target.indexedDB}),recovery=new BackupService(restarted);await recovery.recoverSettings();assert.equal((await restarted.snapshot()).preferences.timeEmphasis,'standard');assert.equal((await restarted.snapshot()).preferences.timeDisplay,'date_and_seconds');assert.equal(await meta(restarted,'backup-recovery-settings'),undefined);await recovery.recoverSettings();assert.equal((await rows(restarted,'records')).length,5);assert.equal(target.requests.length,0);
});
