import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
import {productHistory,productReply} from './fixtures/product-history-v080.mjs';
const out=new URL('../work/v081-bounded-e2e/',import.meta.url).pathname;
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
async function setup(h){const p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await rpc(p,'FILTER_MODE',{mode:'off'});await h.open({id:'bounded-v081',title:'完全虚构的连续整理验收',base:1785542400,messages:productHistory});await eventually(async()=>(await h.state()).records.length===50);await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-bounded-only'}});await p.locator('[data-view=thoughts]').click();return p;}
async function start(p){await p.locator('[data-view=settings]').click();await p.locator('#bounded-original-start').click();await p.locator('[name=requests]').selectOption('3');await p.locator('[name=inputs]').selectOption('50');await p.locator('#library-form button[type=submit]').click();}
test('visible continuous authorization stops at the second response error, preserving first batch',{timeout:90000},async()=>{await mkdir(out,{recursive:true});let n=0;const h=await FakeChatGPT.start({headless:false,deepSeekFixture:body=>++n===2?{choices:[{message:{content:'invalid json'}}]}:productReply(body)});try{const p=await setup(h);await start(p);await eventually(async()=>(await rpc(p,'GET_BOUNDED_ORGANIZER'))?.state==='failed');const state=await rpc(p,'GET_BOUNDED_ORGANIZER');assert.equal(n,2);assert.equal(state.completedInputs,20);assert.equal(state.requestsReserved,2);assert.equal((await rpc(p,'GET_ORIGINAL_ORGANIZER_STATUS')).bootstrap.processed,20);await pause(250);assert.equal(n,2);assert.match(await p.locator('#ai-update-feedback').textContent(),/返回格式异常/);assert.equal(await p.locator('#library-update-diagnostic').isVisible(),false);await p.screenshot({path:out+'01-second-error-stop.png',fullPage:true});assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);await writeFile(out+'second-error.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,maxRequests:3,actualRequests:n,completedInputs:20,nextBatchStopped:true,errors:h.errors},null,2));}finally{await h.close();}});
test('visible worker interruption never resumes an authorized multi-request action',{timeout:90000},async()=>{await mkdir(out,{recursive:true});let release;const held=new Promise(r=>release=r),h=await FakeChatGPT.start({headless:false,deepSeekFixture:async body=>{await held;return productReply(body);}});try{const p=await setup(h);await start(p);await eventually(()=>h.deepSeekRequests.length===1);await h.restartWorker();release();await p.reload();await p.locator('[data-view=thoughts]').click();const state=await rpc(p,'GET_BOUNDED_ORGANIZER');assert.equal(state.state,'outcome_unknown');assert.equal(state.requestsReserved,1);await pause(300);assert.equal(h.deepSeekRequests.length,1);assert.equal((await rpc(p,'GET_ORIGINAL_ORGANIZER_STATUS')).bootstrap.processed,0);await p.screenshot({path:out+'02-restart-stopped.png',fullPage:true});assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);await writeFile(out+'restart.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,actualRequests:1,noResume:true,completedInputs:0,errors:h.errors},null,2));}finally{release();await h.close();}});
test('closing the authorizing page aborts current work and forbids later batches',{timeout:90000},async()=>{let release;const held=new Promise(r=>release=r),h=await FakeChatGPT.start({headless:false,deepSeekFixture:async body=>{await held;return productReply(body);}});try{const p=await setup(h);await start(p);await eventually(()=>h.deepSeekRequests.length===1);await p.close();release();h.archive=await h.context.newPage();await h.archive.goto(`chrome-extension://${h.extensionId}/ui/archive.html`);await eventually(async()=>(await rpc(h.archive,'GET_BOUNDED_ORGANIZER'))?.state==='stopped');await pause(250);assert.equal(h.deepSeekRequests.length,1);assert.equal((await rpc(h.archive,'GET_BOUNDED_ORGANIZER')).completedInputs,0);assert.equal(h.externalRequests,0);await writeFile(out+'page-close.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,actualRequests:1,stoppedOnPageClose:true},null,2));}finally{release();await h.close();}});
