import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {FilterIntentSyncJournal} from '../core/browser-native-sync/filter-intent-journal.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';

test('actual Keep owner must atomically journal a bound existing Source intent',async()=>{
 const {s}=await setup();await s.finishFoundation();
 const core=new BrowserNativeSyncCore(s.repository,{datasetId:'synthetic_filter_intent',deviceId:'synthetic_filter_device'});
 const input=(await s.snapshot()).library.blocks[0];
 const record=await s.repository.transaction(false,async t=>(await t.all('recordIndex'))[0]);
 // Explicit optional injection; default product construction remains unchanged.
 s.filterIntentJournal=new FilterIntentSyncJournal(core);
 await s.keepInput(input.id);
 const intent=await s.repository.transaction(false,t=>t.get('filterIntents',record.sourceKey));
 assert.equal(intent.keep,true,'actual Keep canonical owner saved intent');
 assert.ok(await core.read('head','filterIntent',record.sourceKey),'saved Keep has a portable head in the same bound owner');
});

import {inputEdit,capture} from './harness/thought-m1.mjs';
import {validateEntity,validateCoverage} from '../core/browser-native-sync/codecs.js';
const stores=['meta','records','recordIndex','blocks','inputStates','filterInputs','filterIntents','inputRemovals','revisions','operationReceipts','tombstones'];
const snapshot=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(stores.map(async name=>[name,await t.all(name)]))));
async function device(){const f=await setup();await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_filter_intent',deviceId:crypto.randomUUID()}),journal=new FilterIntentSyncJournal(core);f.s.filterIntentJournal=journal;const b=(await f.s.snapshot()).library.blocks[0],index=await f.s.repository.transaction(false,async t=>(await t.all('recordIndex'))[0]);return {...f,core,journal,b,index};}
const operation=async f=>(await f.core.read('revision',(await f.core.read('head','filterIntent',f.index.sourceKey)).revisions[0])).operation;
async function pair(){const a=await device(),b=await device();await a.s.keepInput(a.b.id);return {a,b,op:await operation(a)};}
test('remote Keep on the exact existing Source changes only protection and protocol, duplicate is idempotent',async()=>{const {a,b,op}=await pair(),old=await snapshot(b.s);await b.journal.receive(op);const after=await snapshot(b.s);assert.equal(after.filterIntents[0].keep,true);for(const name of stores.filter(x=>!['meta','filterIntents'].includes(x)))assert.deepEqual(after[name],old[name],name);await b.journal.receive(op);assert.deepEqual(await snapshot(b.s),after);assert.equal((await a.s.input(a.b.id)).libraryText,null);});
test('outbox failure atomically rolls back actual Keep and filter projection',async()=>{const f=await device(),before=await snapshot(f.s),commit=f.journal.commit.bind(f.journal);f.journal.commit=async(...args)=>{await commit(...args);throw Error('synthetic abort after outbox');};await assert.rejects(f.s.keepInput(f.b.id));assert.deepEqual(await snapshot(f.s),before);});
for(const kind of ['edit','purge','legacy'])test('bound unsupported '+kind+' owner rejects without partial data changes',async()=>{const f=await device();if(kind==='legacy')await f.s.repository.transaction(true,t=>t.put('filterIntents',{id:'legacy:'+f.index.id,keep:true,reason:'user_edit',at:new Date().toISOString()}));const before=await snapshot(f.s);if(kind==='edit')await assert.rejects(inputEdit(f.s,f.b.id,{libraryText:'Synthetic human edit'}));if(kind==='purge')await assert.rejects(f.s.permanentDelete(f.index.id));if(kind==='legacy')await assert.rejects(f.s.changeRecord(f.index.id,r=>{r.hidden=true;}));assert.deepEqual(await snapshot(f.s),before);});
for(const mutate of ['source-tombstone','snapshot-tombstone','digest','missing','legacy-key'])test('existing Source qualifier rejects '+mutate+' without protocol effects',async()=>{const {b,op}=await pair();await b.s.repository.transaction(true,async t=>{if(mutate.includes('tombstone'))await t.put('tombstones',{id:mutate==='source-tombstone'?'source:'+b.index.sourceKey:'snapshot:'+b.index.dedupeKey});else if(mutate==='missing')await t.delete('records',b.index.id);else if(mutate==='digest'){const r=await t.get('records',b.index.id);r.value.originalText+=' corrupt';await t.put('records',r);}else{const r=await t.get('recordIndex',b.index.id);delete r.sourceKey;await t.put('recordIndex',r);}});const before=await snapshot(b.s);await assert.rejects(b.journal.receive(op));assert.deepEqual(await snapshot(b.s),before);});
for(const kind of ['generation','epoch','namespace'])test('prepared Keep rejects changed '+kind+' atomically',async()=>{const f=await device(),prepare=f.journal.prepareKeep.bind(f.journal);f.journal.prepareKeep=async(...args)=>{const p=await prepare(...args);await f.s.repository.transaction(true,t=>t.put('meta',kind==='generation'?{id:'backup-data-generation',value:999}:kind==='epoch'?{id:'recovery-restore-epoch',value:'synthetic_changed_epoch'}:{id:f.core.prefix+'active',namespace:'synthetic_changed_namespace'}));return p;};let before;const write=f.s.write.bind(f.s);f.s.write=async(...args)=>{before=await snapshot(f.s);return write(...args);};await assert.rejects(f.s.keepInput(f.b.id));assert.deepEqual(await snapshot(f.s),before);});
test('unmanaged local human intent refuses remote overwrite',async()=>{const {b,op}=await pair();b.s.filterIntentJournal=null;await inputEdit(b.s,b.b.id,{libraryText:'Synthetic retained edit'});const before=await snapshot(b.s);await assert.rejects(b.journal.receive(op),{code:'BNS_OWNER_CHANGED'});assert.deepEqual(await snapshot(b.s),before);});
test('simultaneous Keep retains conflict and does not overwrite local intent',async()=>{const {a,b,op}=await pair();await b.s.keepInput(b.b.id);const local=(await snapshot(b.s)).filterIntents;await b.journal.receive(op);assert.equal((await b.core.read('head','filterIntent',b.index.sourceKey)).revisions.length,2);assert.deepEqual((await snapshot(b.s)).filterIntents,local);await assert.rejects(b.s.keepInput(b.b.id));});
test('false, unknown reason, legacy identity and unsupported old-reader coverage reject',async()=>{const {op}=await pair();for(const delta of [{keep:false},{reason:'user_edit'},{id:'legacy:synthetic'},{at:'yesterday'}])assert.throws(()=>validateEntity('filterIntent',{...op.value,...delta}));assert.throws(()=>validateCoverage([{type:'filterIntent',version:1,count:1}],{source:1}),{code:'BNS_REQUIRED_CODEC_UNSUPPORTED'});});
test('default null original edit and purge remain usable',async()=>{const f=await device();f.s.filterIntentJournal=null;await inputEdit(f.s,f.b.id,{libraryText:'Synthetic local edit'});assert.equal((await f.s.input(f.b.id)).libraryText,'Synthetic local edit');await assert.rejects(f.s.permanentDelete(f.index.id),{code:'SOURCE_PURGE_OWNER_GATE'});assert.equal((await f.s.snapshot()).records.length,1);const clean=await device();clean.s.filterIntentJournal=null;await clean.s.permanentDelete(clean.index.id);assert.equal((await clean.s.snapshot()).records.length,0);});
for(const kind of ['provenance','source-body','index-key'])test('exact transient owner proof rejects same-generation '+kind+' mutation',async()=>{const f=await device(),prepare=f.journal.prepareKeep.bind(f.journal);f.journal.prepareKeep=async(...args)=>{const p=await prepare(...args);const tx=f.s.repository.db.transaction(kind==='provenance'?['blocks']:kind==='source-body'?['records']:['recordIndex'],'readwrite');const name=kind==='provenance'?'blocks':kind==='source-body'?'records':'recordIndex',store=tx.objectStore(name),request=store.get(kind==='provenance'?f.b.id:f.index.id);request.onsuccess=()=>{const row=request.result;if(kind==='provenance')row.value.provenance=[];else if(kind==='source-body')row.value.originalText+=' same-hash mutation';else row.sourceKey='b'.repeat(64);store.put(row);};await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);});return p;};let before;const write=f.s.write.bind(f.s);f.s.write=async(...args)=>{before=await snapshot(f.s);return write(...args);};await assert.rejects(f.s.keepInput(f.b.id));assert.deepEqual(await snapshot(f.s),before);});
test('receive advances existing canonical generation and invalidates qualified search snapshot, duplicate does not',async()=>{const {b,op}=await pair(),options={query:'Synthetic',qualified:true,ranked:false,limit:1},page=await b.s.searchInputs(options);await b.journal.receive(op);const changed=await b.s.searchInputs({...options,cursor:page.nextCursor,searchSnapshot:page.searchSnapshot});assert.equal(changed.changed,true);assert.deepEqual(changed.items,[]);const generation=(await snapshot(b.s)).meta.find(x=>x.id==='backup-data-generation').value;await b.journal.receive(op);assert.equal((await snapshot(b.s)).meta.find(x=>x.id==='backup-data-generation').value,generation);assert.equal((await b.s.filterDiagnostics()).userProtected,1);});
test('paged diagnostics restarts after external Keep receive instead of mixing generations',async()=>{const {b,op}=await pair(),packet=capture((await b.s.status()).epoch);packet.messages=Array.from({length:101},(_,i)=>({sourceMessageId:'extra-'+i,pageOrder:i+2,originalText:'Synthetic extra '+i}));await b.s.capture(packet);await b.s.finishFoundation();const transaction=b.s.repository.transaction.bind(b.s.repository);let delivered=false;b.s.repository.transaction=async(write,fn,...rest)=>{let paged=false;const result=await transaction(write,async t=>{const page=t.page.bind(t);t.page=(name,...args)=>{if(name==='blockIndex')paged=true;return page(name,...args);};return fn(t);},...rest);if(!write&&paged&&!delivered){delivered=true;await b.journal.receive(op);}return result;};const result=await b.s.filterDiagnostics();assert.equal(delivered,true);assert.equal(result.userProtected,1);assert.equal(result.active,102);});
