import test from 'node:test';import assert from 'node:assert/strict';
import {setup,inputEdit} from './harness/thought-m1.mjs';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {InputWorkingSyncJournal} from '../core/browser-native-sync/input-working-journal.js';
import {FilterIntentSyncJournal} from '../core/browser-native-sync/filter-intent-journal.js';
import {PreparedPublicationJournal} from '../core/browser-native-sync/publications.js';
import {readSegmentDescriptor} from '../core/browser-native-sync/segments.js';
import {InputWorkingCommitReceiver} from '../core/browser-native-sync/input-working-commit.js';
async function sender(){const f=await setup();await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_working_receive',deviceId:'synthetic_working_sender'});f.s.filterIntentJournal=new FilterIntentSyncJournal(core);f.s.inputWorkingJournal=new InputWorkingSyncJournal(core,{filterJournal:f.s.filterIntentJournal,logicalCommits:true});const input=(await f.s.snapshot()).library.blocks[0],initial=await f.s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].map(async name=>[name,await t.all(name)]))));await inputEdit(f.s,input.id,{note:'SYNTHETIC atomic remote human note'});return {...f,core,input,initial};}
async function publish(f,maxOperations=1){const objects=new Map(),transport={async putImmutable(ref,data){objects.set(ref.id,data.slice());},async get(ref){return objects.get(ref.id)?.slice();}},journal=new PreparedPublicationJournal(f.core),decoded=[],descriptors=[];for(let i=0;i<128;i++){const p=await journal.prepare({target:64*1024,maxOperations});if(p.state==='nothing_to_prepare')break;const result=await journal.run(p.publicationId,transport);for(const ref of result.descriptors){descriptors.push(ref);decoded.push(...await readSegmentDescriptor(ref,r=>transport.get(r),{datasetId:f.core.datasetId}));}}return{decoded,descriptors,transport,objects};}
async function receiver(f,provided=null){const r=provided||await setup();await r.s.finishFoundation();await r.s.repository.transaction(true,async t=>{const migration=await t.get('meta','migration');for(const [name,rows]of Object.entries(f.initial)){await new Promise((resolve,reject)=>{const req=t.tx.objectStore(name).clear();req.onsuccess=resolve;req.onerror=()=>reject(req.error);});for(const row of rows)await t.put(name,row);}if(migration)await t.put('meta',migration);});const core=new BrowserNativeSyncCore(r.s.repository,{datasetId:f.core.datasetId,deviceId:'synthetic_receiver_device'}),filter=new FilterIntentSyncJournal(core);return {...r,core,owner:new InputWorkingCommitReceiver(r.s,core,{filterJournal:filter})};}
const all=async core=>{const rows=[];for await(const op of core.outbox())rows.push(op);return rows;};
const state=r=>r.s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(['blocks','inputStates','revisions','filterIntents','filterInputs','meta'].map(async name=>[name,await t.all(name)]))));
const pendingRows=r=>r.core.transaction(false,async t=>(await t.primaryRangePage('meta',{prefix:r.core.prefix+'workingInbox:',limit:100})).rows.map(x=>x.value),['meta']);
test('inbox actual one-operation publications survive receiver recreation and commit without echo',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await r.owner.receiveSegment(p.descriptors[0],ref=>p.transport.get(ref));assert.equal((await r.s.input(f.input.id)).note,'');assert.equal(await r.core.read('receipt',p.decoded[0].operationId),undefined);r.owner=new InputWorkingCommitReceiver(r.s,r.core,{filterJournal:new FilterIntentSyncJournal(r.core)});for(const ref of p.descriptors.slice(1))await r.owner.receiveSegment(ref,key=>p.transport.get(key));assert.equal((await r.owner.resume({get:key=>p.transport.get(key)})).state,'applied');assert.equal((await r.s.input(f.input.id)).note,'SYNTHETIC atomic remote human note');assert.equal((await pendingRows(r)).length,0);assert.deepEqual(await all(r.core),[]);});
test('inbox held decoder cannot stamp an old download with a newer restore epoch',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);let enter,release;const entered=new Promise(resolve=>enter=resolve),held=new Promise(resolve=>release=resolve);const operation=r.owner.receiveSegment(p.descriptors[0],async ref=>{enter();await held;return p.transport.get(ref);});await entered;await r.s.repository.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic_changed_epoch'}));const before=await state(r);release();await assert.rejects(operation,{code:'BNS_INBOX_FENCE_CHANGED'});assert.deepEqual(await state(r),before);});
const feed=async(r,p)=>{for(const ref of p.descriptors)await r.owner.receiveSegment(ref,key=>p.transport.get(key));};
test('inbox retains only body-free references and no canonical acknowledgement for partial transfer',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f),before=await state(r);await r.owner.receiveSegment(p.descriptors[0],key=>p.transport.get(key));const after=await state(r);for(const field of ['blocks','inputStates','revisions','filterIntents','filterInputs'])assert.deepEqual(after[field],before[field]);assert.deepEqual(after.meta.filter(x=>!x.id.startsWith(r.core.prefix+'workingInbox')),before.meta);for(const row of await pendingRows(r))assert.deepEqual(Object.keys(row).sort(),['datasetId','epoch','groups','id','namespace','ref','version']);assert.equal(JSON.stringify(after.meta).includes('SYNTHETIC atomic remote human note'),false);assert.equal((await r.owner.resume({get:key=>p.transport.get(key)})).state,'waiting_for_members');});
test('inbox corrupt accounting refuses admission without repairing or losing pending rows',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await r.owner.receiveSegment(p.descriptors[0],key=>p.transport.get(key));await r.core.transaction(true,async t=>{const row=await t.get('meta',r.core.prefix+'workingInboxBudget');row.bytes--;await t.put('meta',row);});const before=await state(r);await assert.rejects(r.owner.receiveSegment(p.descriptors[1],key=>p.transport.get(key)),{code:'BNS_INBOX_ACCOUNTING'});assert.deepEqual(await state(r),before);});
test('inbox canonical failure retains all references and rolls back Core receipt and derived rows',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);const before=await state(r),write=r.s.applyRemoteWorking.bind(r.s);r.s.applyRemoteWorking=async(...args)=>{await write(...args);throw Error('SYNTHETIC canonical failure');};await assert.rejects(r.owner.resume({get:key=>p.transport.get(key)}));assert.deepEqual(await state(r),before);});
test('inbox finalizer failure rolls back canonical data and receipt with unchanged pending metadata',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);const before=await state(r),transaction=r.core.transaction.bind(r.core);r.core.transaction=(write,fn,stores)=>transaction(write,async t=>{const put=t.put.bind(t);t.put=async(name,row)=>{if(name==='meta'&&row.id===r.core.prefix+'workingInboxBudget'&&row.count===0)throw Error('SYNTHETIC finalizer failure');return put(name,row);};return fn(t);},stores);await assert.rejects(r.owner.resume({get:key=>p.transport.get(key)}));assert.deepEqual(await state(r),before);});
test('inbox exact old ACK cleans transfer metadata without reapplying a committed body',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);await r.owner.receive(p.decoded);const before=await r.s.input(f.input.id);r.s.applyRemoteWorking=async()=>{throw Error('must not repeat canonical write');};assert.equal((await r.owner.resume({get:key=>p.transport.get(key)})).state,'duplicate');assert.deepEqual(await r.s.input(f.input.id),before);assert.equal((await pendingRows(r)).length,0);});
test('inbox lost remote object stays pending and does not imply completed recovery',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);const before=await state(r);await assert.rejects(r.owner.resume({get:async()=>undefined}));assert.deepEqual(await state(r),before);});
test('inbox namespace changes during download cannot publish pending references',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);let changed=false;const before=await state(r);await assert.rejects(r.owner.receiveSegment(p.descriptors[0],async key=>{if(!changed){changed=true;await r.core.transaction(true,t=>t.put('meta',{id:r.core.prefix+'active',namespace:'synthetic_other_namespace'}));}return p.transport.get(key);}),{code:'BNS_INBOX_FENCE_CHANGED'});assert.equal((await pendingRows(r)).length,0);assert.deepEqual((await state(r)).blocks,before.blocks);});
test('inbox proven epoch invalidation permits bounded local reference cleanup only',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);const before=await r.s.input(f.input.id),count=(await pendingRows(r)).length;await r.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic_new_epoch'}));let gets=0;assert.equal((await r.owner.resume({get:async key=>{gets++;return p.transport.get(key);}})).state,'nothing_pending');assert.equal(gets,0);assert.equal((await r.owner.cleanupInbox({limit:1})).removed,1);assert.equal((await pendingRows(r)).length,count-1);assert.deepEqual(await r.s.input(f.input.id),before);assert.deepEqual(await all(r.core),[]);});
test('inbox permission revoked after decode refuses all pending writes',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);let changed=false;await assert.rejects(r.owner.receiveSegment(p.descriptors[0],async key=>{if(!changed){changed=true;await r.s.setEnabled(false);}return p.transport.get(key);}),{code:'BNS_WORKING_PERMISSION_REQUIRED'});assert.equal((await pendingRows(r)).length,0);});
test('inbox shared descriptor retains the next logical commit until its own exact application',async()=>{const f=await sender(),r=await receiver(f);const first=await all(f.core),firstId=first.find(x=>x.type==='inputWorkingCommit').entityId;await inputEdit(f.s,f.input.id,{note:'SYNTHETIC shared segment second'});const p=await publish(f,512);assert.equal(p.descriptors.length,1);await feed(r,p);const groups=(await pendingRows(r))[0].groups,target=f.core.deviceId+'/'+firstId,index=groups.indexOf(target);assert.equal((await r.owner.resume({get:key=>p.transport.get(key),after:index?groups[index-1]:null})).state,'applied');assert.equal((await pendingRows(r))[0].groups.length,1);assert.equal((await r.owner.resume({get:key=>p.transport.get(key)})).state,'applied');assert.equal((await pendingRows(r)).length,0);assert.equal((await r.s.input(f.input.id)).note,'SYNTHETIC shared segment second');});
test('inbox stale Source or local human edits cannot be overwritten after references arrived',async()=>{for(const change of ['source','local']){const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);if(change==='local')await inputEdit(r.s,f.input.id,{note:'SYNTHETIC local priority'});else await r.s.purge((await r.s.repository.transaction(false,t=>t.all('records')))[0].id,true);const before=await state(r);await assert.rejects(r.owner.resume({get:key=>p.transport.get(key)}));assert.deepEqual(await state(r),before);}});
import {WorkingReceiveInbox,WORKING_INBOX_LIMITS} from '../core/browser-native-sync/input-working-inbox.js';
import {bytes} from '../core/browser-native-sync/value.js';
test('inbox exact metadata window counts all group IDs and the accounting row before overflow',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await r.owner.receiveSegment(p.descriptors[0],key=>p.transport.get(key));const original=(await pendingRows(r))[0],inbox=new WorkingReceiveInbox(r.core),rows=[];for(let n=0;n<4;n++){const id=(n+1).toString(16).padStart(64,'0');rows.push({...original,id:inbox.prefix+id,ref:{...original.ref,id,digest:id},groups:Array.from({length:512},(_,i)=>'synthetic_device/'+('g'+String(n*512+i).padStart(7,'0')+'x'.repeat(100)))});}const size=rs=>{const sum=rs.reduce((n,x)=>n+bytes(x).length,0);return sum+bytes({id:inbox.budgetId,version:1,generation:1,count:rs.length,bytes:sum}).length;};while(size(rows)>WORKING_INBOX_LIMITS.metadataBytes)rows.at(-1).groups.pop();const gap=WORKING_INBOX_LIMITS.metadataBytes-size(rows);assert.ok(gap>=0);if(gap){const group=rows.at(-1).groups.at(-1),available=128-group.split('/')[1].length;let remaining=gap;for(const row of rows)for(let i=0;i<row.groups.length&&remaining;i++){const room=128-row.groups[i].split('/')[1].length,add=Math.min(room,remaining);row.groups[i]+='y'.repeat(add);remaining-=add;}assert.equal(remaining,0);for(const row of rows)row.groups.sort();}assert.equal(size(rows),WORKING_INBOX_LIMITS.metadataBytes);await r.core.transaction(true,async t=>{const old=await inbox.read(t);for(const x of old.rows)await t.delete('meta',x.id);const sum=rows.reduce((n,x)=>n+bytes(x).length,0);for(const row of rows)await t.put('meta',row);await t.put('meta',{id:inbox.budgetId,version:1,generation:1,count:rows.length,bytes:sum});});await r.core.transaction(false,t=>inbox.read(t));const before=await state(r);await assert.rejects(r.owner.receiveSegment(p.descriptors[1],key=>p.transport.get(key)),{code:'BNS_INBOX_LIMIT'});assert.deepEqual(await state(r),before);});
test('inbox descriptor count corruption is bounded and never treated as empty accounting',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await r.owner.receiveSegment(p.descriptors[0],key=>p.transport.get(key));const original=(await pendingRows(r))[0],inbox=new WorkingReceiveInbox(r.core);await r.core.transaction(true,async t=>{await t.delete('meta',original.id);for(let n=0;n<513;n++){const id=(n+1).toString(16).padStart(64,'0');await t.put('meta',{...original,id:inbox.prefix+id,ref:{...original.ref,id,digest:id}});}});const before=await state(r);await assert.rejects(r.owner.cleanupInbox({limit:1}),{code:'BNS_INBOX_CORRUPT'});assert.deepEqual(await state(r),before);});
test('inbox corrupt downloaded objects create no pending or canonical writes',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f),before=await state(r);await assert.rejects(r.owner.receiveSegment(p.descriptors[0],async key=>{const data=await p.transport.get(key);data[0]^=1;return data;}));assert.deepEqual(await state(r),before);});
import {BackupService as HistoricalBackup} from './harness/historical-backup.mjs';
import {BackupService} from '../core/backup-service.js';
async function sameValueRestore(s){const legacy=new HistoricalBackup(s),opened=await legacy.beginExport(),items=[opened.header];for(let sequence=0;;sequence++){const page=await legacy.exportPage({sessionId:opened.sessionId,sequence});items.push(...page.items);if(page.done)break;}const service=new BackupService(s),{sessionId}=await service.beginRestore();for(let i=0;i<items.length;i+=30)await service.stageRestore({sessionId,items:items.slice(i,i+30)});const preview=await service.previewRestore({sessionId,mode:'replace'});assert.equal(preview.canRestore,true);await service.restore({sessionId,confirmation:preview.integrity,mode:'replace',targetGeneration:preview.targetGeneration,confirmReplace:true});}
test('inbox actual same-value Backup restore during download refuses admission before a new epoch is stamped',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f),before=await r.s.input(f.input.id);let once=false;await assert.rejects(r.owner.receiveSegment(p.descriptors[0],async key=>{if(!once){once=true;await sameValueRestore(r.s);}return p.transport.get(key);}),{code:'BNS_INBOX_FENCE_CHANGED'});assert.deepEqual(await r.s.input(f.input.id),before);assert.equal((await pendingRows(r)).length,0);});
test('inbox partial claim changed during retrieval cannot report an obsolete waiting cursor',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await r.owner.receiveSegment(p.descriptors[0],key=>p.transport.get(key));let once=false;await assert.rejects(r.owner.resume({get:async key=>{if(!once){once=true;await r.owner.receiveSegment(p.descriptors[1],ref=>p.transport.get(ref));}return p.transport.get(key);}}),{code:'BNS_INBOX_CHANGED'});assert.equal((await pendingRows(r)).length,2);assert.equal((await r.s.input(f.input.id)).note,'');});
test('inbox complete claim changed before final commit rolls back the body and keeps new references',async()=>{const f=await sender(),r=await receiver(f),p=await publish(f);await feed(r,p);let once=false;await assert.rejects(r.owner.resume({get:async key=>{if(!once){once=true;await r.owner.receiveSegment(p.descriptors[0],ref=>p.transport.get(ref));}return p.transport.get(key);}}),{code:'BNS_INBOX_CHANGED'});assert.equal((await r.s.input(f.input.id)).note,'');});
test('inbox default cursor reports missing predecessor and permits the earlier causal group after restart',async()=>{const f=await setup();await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_working_receive',deviceId:'synthetic_working_sender'});f.s.filterIntentJournal=new FilterIntentSyncJournal(core);f.s.inputWorkingJournal=new InputWorkingSyncJournal(core,{filterJournal:f.s.filterIntentJournal,logicalCommits:true});const input=(await f.s.snapshot()).library.blocks[0],initial=await f.s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].map(async name=>[name,await t.all(name)])))) ,producer={...f,core,input,initial};for(const [operationId,note]of [['ffffffff-ffff-4fff-8fff-ffffffffffff','SYNTHETIC predecessor'],['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','SYNTHETIC successor']]){const b=await f.s.input(input.id);await f.s.editDocument({operationId,documentId:b.documentId,blocks:[{id:b.id,expectedRevision:b.revision,libraryText:b.libraryText,note,excluded:b.excluded}]});}const r=await receiver(producer),p=await publish(producer,512);await feed(r,p);r.owner=new InputWorkingCommitReceiver(r.s,r.core,{filterJournal:new FilterIntentSyncJournal(r.core)});const blocked=await r.owner.resume({get:key=>p.transport.get(key)});assert.equal(blocked.state,'waiting_for_parents');assert.equal((await r.s.input(input.id)).note,'');assert.equal((await r.owner.resume({get:key=>p.transport.get(key),after:blocked.nextCursor})).state,'applied');assert.equal((await r.owner.resume({get:key=>p.transport.get(key)})).state,'applied');assert.equal((await r.s.input(input.id)).note,'SYNTHETIC successor');assert.equal((await pendingRows(r)).length,0);});
