import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,inputEdit,capture} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {ContextCardsService,CONTEXT_CARDS_ROW,validContextCards} from '../core/context-cards.js';
import {ContextMaintenanceService,validateContextMaintenanceChange} from '../core/context-maintenance.js';
import {readContextTopicScope,readContextProcessingPreflight,CONTEXT_PROCESSING_PREFLIGHT_LIMITS} from '../core/context-topic-scope.js';
import {inputProjection} from '../core/thought-evidence.js';
import {hashText} from '../core/dedupe.js';

const op=()=>crypto.randomUUID();
const raw=(s,name,id)=>s.repository.transaction(false,t=>t.get(name,id));
const row=f=>raw(f.s,'meta',CONTEXT_CARDS_ROW);
const snapshot=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(['meta','records','recordIndex','blocks','inputStates','thoughts','topics','sections','placements','dependencies','provenance','revisions','operationReceipts','tombstones'].map(async n=>[n,await t.all(n)]))));
function authority(s){
 const caller=Object.freeze({handle:op()}),controller=new AbortController(),state={accountId:'synthetic-account',processorId:'synthetic-processor',generation:1,processing:true,expiresAt:Date.now()+600000,hook:null,currentHook:null,scope:null};
 const verifier={async verify(actual,store,scope){state.scope=structuredClone(scope);if(state.hook)await state.hook();if(actual!==caller||store!==s)return null;return {version:1,store:s,accountId:state.accountId,processorId:state.processorId,authorizationGeneration:state.generation,scope,processing:state.processing,expiresAt:state.expiresAt,revocationSignal:controller.signal};},isCurrent(actual,r,store){state.currentHook?.();return actual===caller&&store===s&&r.accountId===state.accountId&&r.processorId===state.processorId&&r.authorizationGeneration===state.generation;}};
 return {caller,controller,state,verifier,service:new ContextMaintenanceService(s,{processingVerifier:verifier})};
}
async function fixture({body='SYNTHETIC eligible source body'}={}){
 const f=await setup(OrganizerStore);await f.s.finishFoundation();await f.s.setFilterMode('off');const input=(await f.s.snapshot()).library.blocks[0],topic=await f.s.createTopic({operationId:op(),name:'SYNTHETIC processing Topic'});
 await inputEdit(f.s,input.id,{libraryText:body,note:'SYNTHETIC eligible note'});
 const current=await f.s.input(input.id);await f.s.addToTopics({operationId:op(),kind:'input',id:input.id,expectedRevision:current.revision,topicIds:[topic.id]});
 return {...f,input,topic,cards:new ContextCardsService(f.s),...authority(f.s)};
}
async function request(f,{card='info',fields=['body'],...extra}={}){
 const scope=await readContextTopicScope(f.s,{topicId:f.topic.id});assert.equal(scope.available,true,scope.reason);
 const input=await f.s.repository.transaction(false,t=>inputProjection(f.s,t,f.input.id)),fieldDigests={};for(const field of fields)fieldDigests[field]=await hashText(input[field]);
 return {operationId:op(),epoch:scope.binding.epoch,itemId:op(),card,expectedRevision:0,body:'SYNTHETIC extracted candidate',section:'SYNTHETIC section',associationIds:[op()],evidence:[{topicId:f.topic.id,inputId:f.input.id,selectedFields:fields,fieldDigests,expectedTopicBinding:scope.binding,expectedRemovalSequence:input.lastRemovalSequence}],...extra};
}
const put=(f,c)=>f.service.maintain(f.caller,c);
const manual=(c,body='SYNTHETIC human takeover')=>({kind:'put',operationId:op(),epoch:c.epoch,itemId:c.itemId,card:c.card,expectedRevision:1,body,section:'SYNTHETIC human section'});

import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {ContextManualSyncJournal,ContextInfoSyncJournal} from '../core/browser-native-sync/context-journal.js';
import {readCanonicalReadiness} from '../core/browser-native-sync/canonical-readiness.js';
async function journaled(f){const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_coexist',deviceId:op()}),journal=new ContextManualSyncJournal(core);return {...f,core,journal,localCards:f.cards,cards:new ContextCardsService(f.s,{syncJournal:journal})};}
const protocol=f=>f.s.repository.transaction(false,async t=>(await t.all('meta')).filter(x=>x.id.startsWith('bns:')));
for(const key of ['global','info','rules','now','inputs'])test('optional manual journal preserves actual local '+key+' access toggle and receipt',async()=>{const f=await journaled(await fixture()),before=await protocol(f),c={kind:'access',key,enabled:true,expectedRevision:0,epoch:'initial',operationId:op()};const result=await f.cards.change(c);assert.deepEqual(result,{ok:true,key,revision:1,enabled:true});assert.deepEqual(await f.cards.change(c),result);assert.equal((await row(f)).access[key].enabled,true);assert.deepEqual(await protocol(f),before);assert.equal((await readCanonicalReadiness(f.core)).fullCanonicalReady,false);});
for(const card of ['info','rules','now'])test('optional journal retains automatic '+card+' origin and lineage through actual human edit/remove/restore',async()=>{const f=await journaled(await fixture()),c=await request(f,{card});await put(f,c);const before=(await row(f)).items[0],bns=await protocol(f);assert.equal(before.origin,'automatic');const edit=manual(c);assert.equal((await f.cards.change(edit)).ok,true);let item=(await row(f)).items[0];assert.equal(item.origin,'automatic');assert.equal(item.protected,true);assert.equal(item.userEdited,true);assert.deepEqual(item.maintenance,before.maintenance);const removal={kind:'delete',operationId:op(),epoch:'initial',itemId:c.itemId,expectedRevision:2};await f.cards.change(removal);await f.cards.change({kind:'restore',operationId:op(),epoch:'initial',itemId:c.itemId,expectedRevision:3,deletedBy:removal.operationId});item=(await row(f)).items[0];assert.equal(item.lifecycle,'active');assert.equal(item.revision,4);assert.equal(item.origin,'automatic');assert.deepEqual(item.maintenance,before.maintenance);assert.deepEqual(await protocol(f),bns);assert.equal((await readCanonicalReadiness(f.core)).fullCanonicalReady,false);});
test('manual writes still require actual outbox commit and a journal failure rolls canonical and receipt back',async()=>{const f=await journaled(await fixture()),c={kind:'put',card:'rules',itemId:op(),operationId:op(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC manual',section:'SYNTHETIC'};const before=await snapshot(f.s),commit=f.journal.commit.bind(f.journal);f.journal.commit=async(t,p)=>{await commit(t,p);throw Error('synthetic after outbox');};await assert.rejects(f.cards.change(c));assert.deepEqual(await snapshot(f.s),before);f.journal.commit=commit;await f.cards.change(c);assert.equal((await protocol(f)).filter(x=>x.state==='queued').length,1);});
for(const automatic of [false,true])test('local-only '+(automatic?'automatic':'access')+' receipt failure preserves canonical and all protocol state',async()=>{const f=await journaled(await fixture()),c=automatic?await request(f,{card:'rules'}):null;if(c)await put(f,c);const change=c?manual(c):{kind:'access',key:'global',enabled:true,expectedRevision:0,epoch:'initial',operationId:op()},before=await snapshot(f.s),write=f.s.write.bind(f.s);f.s.write=fn=>write(t=>{const save=t.put.bind(t);t.put=(name,value)=>{if(name==='operationReceipts'&&value.namespace==='context-cards')throw Error('synthetic receipt failure');return save(name,value);};return fn(t);});await assert.rejects(f.cards.change(change));assert.deepEqual(await snapshot(f.s),before);});
test('a concurrent local access write during local-only preparation still rejects stale whole-row apply',async()=>{const f=await journaled(await fixture()),prepare=f.journal.prepare.bind(f.journal);f.journal.prepare=async(...args)=>{await f.localCards.change({kind:'access',key:'info',enabled:true,expectedRevision:0,epoch:'initial',operationId:op()});return prepare(...args);};await assert.rejects(f.cards.change({kind:'access',key:'global',enabled:true,expectedRevision:0,epoch:'initial',operationId:op()}),e=>e.code==='CONTEXT_INVALIDATED');assert.equal((await row(f)).access.info.enabled,true);assert.equal((await row(f)).access.global.enabled,false);assert.deepEqual(await protocol(f),[]);});
test('undefined preparation is not a local-only fallback and old Info journal remains strict',async()=>{const f=await journaled(await fixture()),c={kind:'access',key:'info',enabled:true,expectedRevision:0,epoch:'initial',operationId:op()};const info=new ContextCardsService(f.s,{syncJournal:new ContextInfoSyncJournal(f.core)});await assert.rejects(info.change(c),e=>e.code==='BNS_CONTEXT_SCOPE_UNAVAILABLE');const before=await snapshot(f.s);f.journal.prepare=async()=>undefined;await assert.rejects(f.cards.change(c));assert.deepEqual(await snapshot(f.s),before);});
