import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {ContextCardsService,readContextCards} from '../core/context-cards.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
import {ContextDesiredSyncJournal,contextDesiredMaterializer,contextDesiredConflictOwner} from '../core/browser-native-sync/context-desired-journal.js';
const op=()=>crypto.randomUUID(),datasetId='synthetic_context_desired';
async function device(options={}){const f=await setup(OrganizerStore);await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId,deviceId:op(),...options});return {...f,core,cards:new ContextCardsService(f.s,{syncJournal:new ContextDesiredSyncJournal(core)})};}
const access=(key='info',enabled=true,expectedRevision=0)=>({kind:'access',key,enabled,expectedRevision,epoch:'initial',operationId:op()});
const collect=async iterable=>{const rows=[];for await(const row of iterable)rows.push(row);return rows;};
const row=f=>f.core.transaction(false,t=>readContextCards(t));
test('actual card access writer records desired head and outbox atomically',async()=>{const f=await device(),c=access();assert.equal((await f.cards.change(c)).ok,true);assert.deepEqual((await row(f)).access.info,{enabled:true,revision:1});assert.ok(await f.core.read('head','contextDesired','info'));assert.equal((await collect(f.core.rows('outbox'))).length,1);});
test('registered desired conflict owner is invoked for the real concurrent off branch',async()=>{let called=0;const a=await device(),b=await device({conflictOwners:{contextDesired:async()=>called++}});const first=(await a.core.prepare([{type:'contextDesired',value:{id:'info',enabled:true,revision:1}}]));await a.core.commit(first);await b.core.receive(first.operations[0]);const left=await a.core.prepare([{type:'contextDesired',value:{id:'info',enabled:false,revision:2}}]),right=await b.core.prepare([{type:'contextDesired',value:{id:'info',enabled:true,revision:2}}]);await a.core.commit(left);await b.core.commit(right);assert.equal((await b.core.receive(left.operations[0])).state,'conflict');assert.equal(called,1);});
async function boundDevice(){let core;const f=await device({conflictOwners:{contextDesired:(t,s)=>contextDesiredConflictOwner(core)(t,s)}});core=f.core;core.materialize=contextDesiredMaterializer(core);return {...f,plain:new ContextCardsService(f.s)};}
const snapshot=async f=>f.core.transaction(false,async t=>({meta:await t.all('meta'),receipts:await t.all('operationReceipts')}));
async function sent(f,c){await f.cards.change(c);const out=(await collect(f.core.rows('outbox'))).find(x=>x.operationId===c.operationId);return (await f.core.read('revision',out.revisionId)).operation;}
for(const key of ['info','rules','now','inputs'])test(key+' exact access retry, remote restore and global remain independent',async()=>{const a=await boundDevice(),b=await boundDevice(),c=access(key),r=await a.cards.change(c);assert.deepEqual(await a.cards.change(c),r);const operation=(await a.core.read('revision',(await collect(a.core.rows('outbox')))[0].revisionId)).operation;await b.core.receive(operation);assert.deepEqual((await row(b)).access[key],{enabled:true,revision:1});assert.deepEqual((await row(b)).access.global,{enabled:false,revision:0});assert.equal((await collect(a.core.rows('outbox'))).length,1);const before=await collect(a.core.rows('outbox'));await a.cards.change(access('global'));assert.deepEqual(await collect(a.core.rows('outbox')),before);assert.equal(await a.core.read('head','contextDesired','global'),undefined);});
test('remote enable never expands global-on scope and exact operation can retry after local pause',async()=>{const a=await boundDevice(),b=await boundDevice();await b.cards.change(access('global'));const op1=await sent(a,access()),before=await snapshot(b);await assert.rejects(b.core.receive(op1),e=>e.code==='BNS_CONTEXT_ACCESS_CONFIRMATION_REQUIRED');assert.deepEqual(await snapshot(b),before);await b.cards.change(access('global',false,1));await b.core.receive(op1);assert.equal((await row(b)).access.info.enabled,true);assert.equal((await row(b)).access.global.enabled,false);});
test('unmanaged local denial is not overwritten by imported enable',async()=>{const a=await boundDevice(),b=await boundDevice();await b.plain.change(access('info',false));const before=await snapshot(b);await assert.rejects(b.core.receive(await sent(a,access())),e=>e.code==='BNS_RESTORE_UNMANAGED_OWNER');assert.deepEqual(await snapshot(b),before);});
test('concurrent off preserves both heads while restricting only the affected card',async()=>{const a=await boundDevice(),b=await boundDevice();const start=await sent(a,access());await b.core.receive(start);await b.cards.change(access('global'));await b.cards.change(access('rules'));const left=await sent(a,access('info',false,1));await sent(b,access('info',true,1));const before=await row(b),result=await b.core.receive(left),after=await row(b);assert.equal(result.state,'conflict');assert.equal(result.revisions.length,2);assert.equal(after.access.info.enabled,false);assert.equal(after.access.info.revision,2);assert.deepEqual(after.access.global,before.access.global);assert.deepEqual(after.access.rules,before.access.rules);assert.deepEqual(after.items,before.items);await assert.rejects(b.cards.change(access('info',true,2)),e=>e.code==='BNS_CONFLICT_REQUIRES_RESOLUTION');const stable=await snapshot(b);assert.equal((await b.core.receive(left)).state,'duplicate');assert.deepEqual(await snapshot(b),stable);});
test('unregistered conflict retains existing Core semantics and no canonical materialization',async()=>{const a=await device(),b=await device(),start=await sent(a,access());await b.core.receive(start);const off=await sent(a,access('info',false,1));await b.core.commit(await b.core.prepare([{type:'contextDesired',value:{id:'info',enabled:true,revision:2}}]));const before=await row(b);assert.equal((await b.core.receive(off)).state,'conflict');assert.deepEqual(await row(b),before);});
for(const phase of ['journal','receipt'])test(phase+' failure rolls back card, protocol and local receipt',async()=>{const f=await boundDevice(),before=await snapshot(f);if(phase==='journal')f.cards.syncJournal.commit=async()=>{throw Error('synthetic abort');};else{const write=f.s.write.bind(f.s);f.s.write=fn=>write(t=>{const put=t.put.bind(t);t.put=(store,value)=>{if(store==='operationReceipts'&&value.namespace==='context-cards')throw Error('synthetic abort');return put(store,value);};return fn(t);});}await assert.rejects(f.cards.change(access()));assert.deepEqual(await snapshot(f),before);});
test('conflict owner failure rolls back even protocol receipts and generation',async()=>{const a=await boundDevice(),b=await boundDevice(),start=await sent(a,access());await b.core.receive(start);const off=await sent(a,access('info',false,1));await sent(b,access('info',true,1));b.core.conflictOwners={contextDesired:async()=>{throw Error('synthetic conflict abort');}};const before=await snapshot(b);await assert.rejects(b.core.receive(off));assert.deepEqual(await snapshot(b),before);});
test('restore epoch invalidates even a negative remote change without partial acknowledgements',async()=>{const a=await boundDevice(),b=await boundDevice();await b.core.receive(await sent(a,access()));const off=await sent(a,access('info',false,1));await b.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:op()}));const before=await snapshot(b);await assert.rejects(b.core.receive(off),e=>e.code==='BNS_RESTORE_EPOCH_CHANGED');assert.deepEqual(await snapshot(b),before);});
test('unregistered local edit prevents remote restrictive owner replacement too',async()=>{const a=await boundDevice(),b=await boundDevice();await b.core.receive(await sent(a,access()));await b.plain.change(access('info',false,1));const before=await snapshot(b);await assert.rejects(b.core.receive(await sent(a,access('info',false,1))),e=>e.code==='BNS_OWNER_CHANGED');assert.deepEqual(await snapshot(b),before);});

test('valid resolution can leave a restrictive conflict projection without consumed revision',async()=>{const a=await boundDevice(),b=await boundDevice();await b.core.receive(await sent(a,access()));const off=await sent(a,access('info',false,1));await sent(b,access('info',true,1));await b.core.receive(off);const resolution=await b.core.prepare([{type:'contextDesired',resolve:true,value:{id:'info',enabled:true,revision:3}}]);await b.core.commit(resolution);assert.deepEqual((await row(b)).access.info,{enabled:true,revision:3});assert.equal((await b.core.read('head','contextDesired','info')).revisions.length,1);});
test('existing local card desired state can bootstrap without changing local authority or receipts',async()=>{const a=await boundDevice(),b=await boundDevice();await a.plain.change(access('info',false));await a.plain.change(access('info',true,1));await a.plain.change(access('global'));const before=await row(a),receipts=(await snapshot(a)).receipts;await a.cards.syncJournal.bootstrapAccess('info');assert.deepEqual(await row(a),before);assert.deepEqual((await snapshot(a)).receipts,receipts);const operation=(await a.core.read('revision',(await collect(a.core.rows('outbox')))[0].revisionId)).operation;assert.equal(operation.actor,'bootstrap');await b.core.receive(operation);assert.deepEqual((await row(b)).access.info,before.access.info);assert.equal((await row(b)).access.global.enabled,false);await assert.rejects(a.cards.syncJournal.bootstrapAccess('global'),e=>e.code==='BNS_CONTEXT_SCOPE_UNAVAILABLE');});
test('first materialization binds a real non-null local restore epoch; changed epoch rejects later',async()=>{const a=await boundDevice(),b=await boundDevice(),epoch=op();await b.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:epoch}));await b.core.receive(await sent(a,access()));assert.equal((await b.core.read('contextDesiredOwner','info')).epoch,epoch);await b.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:op()}));const before=await snapshot(b);await assert.rejects(b.core.receive(await sent(a,access('info',false,1))),e=>e.code==='BNS_RESTORE_EPOCH_CHANGED');assert.deepEqual(await snapshot(b),before);});
test('long legal per-step card changes retain bounded verified ancestry rather than stopping at 129',async()=>{const a=await boundDevice(),b=await boundDevice();for(let i=0;i<130;i++)await b.core.receive(await sent(a,access('info',i%2===0,i)));assert.deepEqual((await row(a)).access.info,(await row(b)).access.info);});
test('conflict projection does not advance on additional stale ancestry delivery',async()=>{const a=await boundDevice(),b=await boundDevice(),first=await sent(a,access());await b.core.receive(first);await sent(b,access('info',true,1));const off=await sent(a,access('info',false,1));await b.core.receive(off);const before=await row(b);await b.core.receive(first);await b.core.receive(off);assert.deepEqual(await row(b),before);});
test('global-on conflict cannot resolve to expanded effective scope, but explicit off resolution succeeds',async()=>{const a=await boundDevice(),b=await boundDevice();await b.core.receive(await sent(a,access()));await b.cards.change(access('global'));await sent(b,access('info',true,1));await b.core.receive(await sent(a,access('info',false,1)));const before=await snapshot(b),on=await b.core.prepare([{type:'contextDesired',resolve:true,value:{id:'info',enabled:true,revision:3}}]);await assert.rejects(b.core.commit(on),e=>e.code==='BNS_CONTEXT_ACCESS_CONFIRMATION_REQUIRED');assert.deepEqual(await snapshot(b),before);await b.core.commit(await b.core.prepare([{type:'contextDesired',resolve:true,value:{id:'info',enabled:false,revision:3}}]));assert.equal((await row(b)).access.info.enabled,false);assert.equal((await row(b)).access.global.enabled,true);});
for(const enabled of [true,false])test('prepared local enable refuses concurrent restriction even when prior local enabled='+enabled,async()=>{const a=await boundDevice(),b=await boundDevice();await b.core.receive(await sent(a,access()));await sent(b,access('info',enabled,1));const off=await sent(a,access('info',false,1));let release,prepared;const gate=new Promise(r=>release=r),ready=new Promise(r=>prepared=r),prepare=b.cards.syncJournal.prepare.bind(b.cards.syncJournal);b.cards.syncJournal.prepare=async(...args)=>{const result=await prepare(...args);prepared();await gate;return result;};let commitCode=null;const commit=b.cards.syncJournal.commit.bind(b.cards.syncJournal);b.cards.syncJournal.commit=async(...args)=>{try{return await commit(...args);}catch(e){commitCode=e.code;throw e;}};const command=access('info',true,2),pending=b.cards.change(command);await ready;await b.core.receive(off);const before=await snapshot(b);release();await assert.rejects(pending,e=>e.code===(enabled?'CONTEXT_INVALIDATED':'STORAGE_FAILED'));if(!enabled)assert.equal(commitCode,'BNS_PREPARATION_STALE');assert.deepEqual(await snapshot(b),before);assert.equal((await row(b)).access.info.enabled,false);assert.equal((await snapshot(b)).receipts.some(x=>x.id==='context:'+command.operationId),false);});
test('optional journal leaves the existing nonjournal access owner unchanged',async()=>{const f=await boundDevice();await f.plain.change(access());assert.equal((await row(f)).access.info.enabled,true);assert.equal((await collect(f.core.rows('outbox'))).length,0);assert.equal(await f.core.read('head','contextDesired','info'),undefined);});

function transport(){const objects=new Map();return {async putImmutable(ref,bytes){objects.set(ref.id,bytes.slice());},async get(ref){return objects.get(ref.id).slice();}};}
function restore(f){const r=new StagedSyncRestore(f.core);r.owners={contextDesired:contextDesiredMaterializer(r.stage)};return r;}
test('actual staged desired activation restores four choices but no global grant and rolls back atomically',async()=>{const a=await boundDevice(),b=await boundDevice();for(const key of ['info','rules','now','inputs'])await sent(a,access(key));await a.cards.change(access('global'));const cloud=transport(),checkpoint=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(checkpoint.ref,ref=>cloud.get(ref));const before=await snapshot(b);r.checkpoint=async phase=>{if(phase==='after-activation')throw Error('synthetic activation abort');};await assert.rejects(r.activate());assert.deepEqual(await snapshot(b),before);r.checkpoint=async()=>{};await r.activate();for(const key of ['info','rules','now','inputs'])assert.deepEqual((await row(b)).access[key],{enabled:true,revision:1});assert.equal((await row(b)).access.global.enabled,false);});
test('stage cannot borrow live anchor to accept an otherwise over-bound desired ancestry',async()=>{const a=await boundDevice(),b=await boundDevice();for(let i=0;i<129;i++)await b.core.receive(await sent(a,access('info',i%2===0,i)));const cloud=transport(),checkpoint=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(checkpoint.ref,ref=>cloud.get(ref));const before=await snapshot(b);await assert.rejects(r.activate(),e=>e.code==='BNS_CONTEXT_ANCESTRY_LIMIT');assert.deepEqual(await snapshot(b),before);});
