import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {LibraryFoundationStore} from '../core/thought-store.js';
import {local,capture,inputEdit} from './harness/thought-m1.mjs';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {SourceBootstrapJournal} from '../core/browser-native-sync/source-bootstrap-journal.js';
globalThis.IDBKeyRange=IDBKeyRange;
async function fresh(device){const s=new LibraryFoundationStore(local(),{indexedDB:new IDBFactory()});await s.consent(true);await s.finishFoundation();const core=new BrowserNativeSyncCore(s.repository,{datasetId:'synthetic_source_bootstrap',deviceId:device});return {s,core};}
async function all(core){const rows=[];for await(const op of core.outbox())rows.push(op);return rows;}
test('actual opt-in capture atomically publishes a complete required Source bootstrap',async()=>{const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);const request=capture((await a.s.status()).epoch);request.chat.url='https://chatgpt.com/g/synthetic_gpt/c/'+request.chat.id;const result=await a.s.capture(request);assert.equal((await a.s.snapshot()).records[0].chatUrl,request.chat.url);assert.equal(result.timeChanged,true);const ops=await all(a.core);assert.equal(ops.length,7,'canonical capture must not succeed without its complete portable bootstrap');assert.equal(ops.filter(x=>x.type==='sourceBootstrapCommit').length,1);const diagnostics=await a.s.repository.transaction(false,async t=>(await a.s.control(t)).diagnostics);assert.deepEqual(diagnostics.ingestion,{schemaVersion:1,kind:'capture',attempted:1,added:1,duplicates:0,ignored:0,unresolved:0,knownTimes:0,unknownTimes:1});assert.equal(diagnostics.status,'CAPTURING');});
import {SourceBootstrapReceiver} from '../core/browser-native-sync/source-bootstrap-receive.js';
import {PreparedPublicationJournal} from '../core/browser-native-sync/publications.js';
import {readSegmentDescriptor} from '../core/browser-native-sync/segments.js';
import {InputWorkingSyncJournal} from '../core/browser-native-sync/input-working-journal.js';
import {InputWorkingCommitReceiver} from '../core/browser-native-sync/input-working-commit.js';
import {FilterIntentSyncJournal} from '../core/browser-native-sync/filter-intent-journal.js';
async function publish(f,maxOperations=1){const objects=new Map(),transport={async putImmutable(ref,data){objects.set(ref.id,data.slice());},async get(ref){return objects.get(ref.id)?.slice();}},journal=new PreparedPublicationJournal(f.core),decoded=[],descriptors=[];for(let i=0;i<128;i++){const p=await journal.prepare({target:64*1024,maxOperations});if(p.state==='nothing_to_prepare')break;const result=await journal.run(p.publicationId,transport);for(const ref of result.descriptors){descriptors.push(ref);decoded.push(...await readSegmentDescriptor(ref,r=>transport.get(r),{datasetId:f.core.datasetId}));}}return{decoded,descriptors,transport};}
async function source(){const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);await a.s.capture(capture((await a.s.status()).epoch));return a;}
function working(f){f.s.filterIntentJournal=new FilterIntentSyncJournal(f.core);f.s.inputWorkingJournal=new InputWorkingSyncJournal(f.core,{filterJournal:f.s.filterIntentJournal,logicalCommits:true});return new InputWorkingCommitReceiver(f.s,f.core,{filterJournal:f.s.filterIntentJournal});}
const snapshot=f=>f.s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].map(async name=>[name,await t.all(name)]))));
test('real publication creates empty receiver Source and preserves exact baseline identity/time with local sequences',async()=>{const a=await source(),p=await publish(a),b=await fresh('synthetic_bootstrap_receiver');await b.s.repository.transaction(true,async t=>{await t.put('meta',{id:'sequence',records:500,documents:500,blocks:500});await t.put('meta',{id:'revision-sequence',value:700});await t.put('meta',{id:'input-delta-sequence',value:800});});const owner=new SourceBootstrapReceiver(b.s,b.core);assert.equal((await owner.receive(p.decoded.reverse())).state,'applied');const from=await snapshot(a),to=await snapshot(b);assert.deepEqual(to.records[0].value,from.records[0].value);assert.deepEqual(to.times,from.times);const h=from.revisions[0],local=to.revisions[0];assert.equal(local.sequence,701);assert.deepEqual(local,{...h,sequence:701,listKey:[h.entityKey,701],documentList:[h.documentId,701]});assert.equal(to.inputStates[0].deltaSequence,801);assert.deepEqual(await all(b.core),[]);const before=await snapshot(b);assert.equal((await new SourceBootstrapReceiver(b.s,b.core).receive(p.decoded)).state,'duplicate');assert.deepEqual(await snapshot(b),before);});
for(const first of ['A','B'])test('actual '+first+' first Working edit follows bootstrap, roundtrips and coalesces without copied canonical rows',async()=>{const a=await source(),p=await publish(a),b=await fresh('synthetic_bootstrap_receiver');await b.s.repository.transaction(true,t=>t.put('meta',{id:'revision-sequence',value:300}));await new SourceBootstrapReceiver(b.s,b.core).receive(p.decoded);const aa=working(a),bb=working(b),id=(await a.s.snapshot()).library.blocks[0].id;for(const f of first==='A'?[a,b,a]:[b,a,b]){const target=f===a?b:a,owner=f===a?bb:aa,text='SYNTHETIC '+f.core.deviceId+' '+crypto.randomUUID();await inputEdit(f.s,id,{note:text});await owner.receive((await publish(f)).decoded.reverse());assert.equal((await target.s.input(id)).note,text);}const before=await snapshot(b);assert.equal((await new SourceBootstrapReceiver(b.s,b.core).receive(p.decoded)).state,'duplicate');assert.deepEqual(await snapshot(b),before);});
import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
test('every real one-operation publication is rejected by frozen old reader before descriptor arrives',async()=>{const a=await source(),p=await publish(a),base=new URL('./fixtures/input-working-old-reader/',import.meta.url),manifest=JSON.parse(await readFile(new URL('manifest.json',base),'utf8'));assert.equal(manifest.commit,'7b638b81c1b20efd79814f2a520db477a2c6832d');for(const [path,proof]of Object.entries(manifest.files)){assert.match(path,/^(?:core\/[a-z0-9/-]+\.js|package\.json)$/);const data=await readFile(new URL('extension/'+path,base));assert.equal(createHash('sha256').update(data).digest('hex'),proof.sha256);assert.equal(createHash('sha1').update('blob '+data.length+'\0').update(data).digest('hex'),proof.gitBlob);}const old=await import(new URL('extension/core/browser-native-sync/segments.js',base)),oldCore=await import(new URL('extension/core/browser-native-sync/core.js',base));assert.equal(p.descriptors.length,7);for(const ref of p.descriptors)await assert.rejects(old.readSegmentDescriptor(ref,r=>p.transport.get(r),{datasetId:a.core.datasetId}),{code:'BNS_REQUIRED_CODEC_UNSUPPORTED'});for(const op of p.decoded)await assert.rejects(oldCore.validateOperation(op),{code:'BNS_OPERATION_INVALID'});});
test('incomplete, generic and applyPending bootstrap refuse with all stores unchanged',async()=>{const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),owner=new SourceBootstrapReceiver(b.s,b.core),before=await snapshot(b);for(const op of ops){await assert.rejects(b.core.receive(op),{code:'BNS_SOURCE_BOOTSTRAP_REQUIRED'});await assert.rejects(b.core.applyPending({operation:op}),{code:'BNS_SOURCE_BOOTSTRAP_REQUIRED'});assert.deepEqual(await snapshot(b),before);}for(let i=0;i<7;i++){await assert.rejects(owner.receive(ops.filter((_,n)=>i!==n)),{code:'BNS_SOURCE_BOOTSTRAP_INVALID'});assert.deepEqual(await snapshot(b),before);}});
test('receiver exception after Source/canonical writes rolls back every store and protocol receipt with no echo',async()=>{const a=await source(),b=await fresh('synthetic_bootstrap_receiver'),ops=(await publish(a)).decoded,before=await snapshot(b),write=b.s.applyInitialSource.bind(b.s);b.s.applyInitialSource=async(...args)=>{await write(...args);throw Error('SYNTHETIC rollback after canonical write');};await assert.rejects(new SourceBootstrapReceiver(b.s,b.core).receive(ops));assert.deepEqual(await snapshot(b),before);assert.deepEqual(await all(b.core),[]);});
test('producer exception after outbox write rolls back canonical and protocol together',async()=>{const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);const before=await snapshot(a),commit=a.core.commitPrepared.bind(a.core);a.core.commitPrepared=async(...args)=>{await commit(...args);throw Error('SYNTHETIC outbox failure');};await assert.rejects(a.s.capture(capture((await a.s.status()).epoch)));assert.deepEqual(await snapshot(a),before);});
test('actual initial time ledger survives publication exactly and does not substitute capture time for Source time',async()=>{const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);const q=capture((await a.s.status()).epoch);q.messages[0].sourceTime={state:'valid',createTime:1609459200,updateTime:null};await a.s.capture(q);const b=await fresh('synthetic_bootstrap_receiver');await new SourceBootstrapReceiver(b.s,b.core).receive((await publish(a)).decoded);const aa=await snapshot(a),bb=await snapshot(b);assert.equal(aa.records[0].value.sourceSentAt,'2021-01-01T00:00:00.000Z');assert.notEqual(aa.records[0].value.sourceSentAt,aa.records[0].value.capturedAt);assert.deepEqual(bb.times,aa.times);assert.deepEqual(bb.records[0].value,aa.records[0].value);});
test('committed duplicate capture, enrichment and multi-message bound requests refuse without half writes',async()=>{const a=await source(),before=await snapshot(a),q=capture((await a.s.status()).epoch);await assert.rejects(a.s.capture(q),{code:'BNS_SOURCE_BOOTSTRAP_UNAVAILABLE'});await assert.rejects(a.s.enrich({...q,chat:{id:q.chat.id,url:q.chat.url},messages:[{sourceMessageId:q.messages[0].sourceMessageId,pageOrder:1,sourceTime:{state:'valid',createTime:1609459200,updateTime:null}}]}),{code:'BNS_SOURCE_BOOTSTRAP_UNSUPPORTED'});await assert.rejects(a.s.capture({...q,messages:[...q.messages,{...q.messages[0],sourceMessageId:'synthetic_second_message'}]}),{code:'BNS_SOURCE_BOOTSTRAP_UNSUPPORTED'});assert.deepEqual(await snapshot(a),before);});
for(const mutation of ['permission','restore','namespace'])test('receive first-await '+mutation+' race rejects without admitting protocol or canonical rows',async()=>{const a=await source(),b=await fresh('synthetic_bootstrap_receiver'),ops=(await publish(a)).decoded,prepare=b.core.prepareSourceBootstrapReceive.bind(b.core);let before;b.core.prepareSourceBootstrapReceive=async x=>{const result=await prepare(x);if(mutation==='permission')await b.s.setEnabled(false);else await b.s.repository.transaction(true,t=>t.put('meta',mutation==='restore'?{id:'recovery-restore-epoch',value:'synthetic_new_restore'}:{id:b.core.prefix+'active',namespace:'synthetic_other_namespace'}));before=await snapshot(b);return result;};await assert.rejects(new SourceBootstrapReceiver(b.s,b.core).receive(ops),{code:'BNS_SOURCE_BOOTSTRAP_'+(mutation==='permission'?'PERMISSION':'CHANGED')});assert.deepEqual(await snapshot(b),before);});
import {identify} from '../core/dedupe.js';
import {initialSourceObjects} from '../core/source-initial.js';
import {sealOperation} from '../core/browser-native-sync/core.js';
async function reseal(ops,type,change){const next=structuredClone(ops),member=next.find(x=>x.type==='sourceBootstrapMember'&&x.value.entityType===type),old=member.revisionId;change(member.value.entity);const sealed=await sealOperation(member);next[next.indexOf(member)]=sealed;const descriptor=next.find(x=>x.type==='sourceBootstrapCommit');descriptor.value.members.find(x=>x.revisionId===old).revisionId=sealed.revisionId;next[next.indexOf(descriptor)]=await sealOperation(descriptor);return next;}
async function reshapeInitialClosure(ops,mutate){
 const next=structuredClone(ops),members=next.filter(x=>x.type==='sourceBootstrapMember'),e=Object.fromEntries(members.map(x=>[x.value.entityType,x.value.entity]));mutate(e.source);Object.assign(e.source,await identify(e.source.chatId,e.source.sourceMessageId,e.source.originalText));e.timeEvidence.id=e.source.sourceKey;
 const formed=initialSourceObjects(e.source),source={...formed.document,titleRevision:0};delete source.sourceRecordIds;const working=structuredClone(source);delete working.titleRevision;e.inputDocument={id:source.id,source,working};e.input={...formed.block,revision:0,provenanceSignature:JSON.stringify(formed.block.provenance)};
 const snapshot={libraryText:e.input.libraryText,note:e.input.note,excluded:e.input.excluded,originalTextReference:e.input.originalTextReference,provenanceSignature:e.input.provenanceSignature};e.baselineRevision.before=structuredClone(snapshot);e.baselineRevision.after=structuredClone(snapshot);
 const sealed=[];for(const op of members){op.value.entity=e[op.value.entityType];op.value.id=op.value.entityType+':'+op.value.entity.id;op.entityId=op.value.id;sealed.push(await sealOperation(op));}const descriptor=next.find(x=>x.type==='sourceBootstrapCommit');descriptor.value.sourceKey=e.source.sourceKey;descriptor.value.members=sealed.map(x=>({type:x.type,entityId:x.entityId,revisionId:x.revisionId}));return [...sealed,await sealOperation(descriptor)];
}
async function assertCaptureShapeClosures(ops){const accepted=[];for(const mutate of [r=>{r.originalText=' ';},r=>{r.originalText='x'.repeat(200001);},r=>{r.chatTitle='x'.repeat(501);},r=>{r.pageOrder=1000001;r.conversationOrder=r.pageOrder;},r=>{r.sourceMessageId='synthetic invalid message';}]){const target=await fresh('synthetic_shape_receiver'),before=await snapshot(target);try{await new SourceBootstrapReceiver(target.s,target.core).receive(await reshapeInitialClosure(ops,mutate));accepted.push(true);}catch(error){assert.equal(error.code,'BNS_SOURCE_BOOTSTRAP_INVALID');accepted.push(false);assert.deepEqual(await snapshot(target),before);}}assert.deepEqual(accepted,[false,false,false,false,false],'initial capture shape must reject every self-consistent impossible producer closure');}
test('re-sealed internally inconsistent Source time, document, and baseline closures reject every store atomically',async()=>{const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),owner=new SourceBootstrapReceiver(b.s,b.core),before=await snapshot(b);await assertCaptureShapeClosures(ops);const original=ops.find(x=>x.type==='sourceBootstrapMember'&&x.value.entityType==='source').value.entity;assert.deepEqual(initialSourceObjects({...original,conversationOrder:original.pageOrder+1}),initialSourceObjects(original),'all dependent initial objects remain self-consistent for the forged order');for(const [type,change] of [['source',r=>{r.conversationOrder=r.pageOrder+1;}],['source',r=>{r.originalText+=' SYNTHETIC forged';}],['source',r=>{r.timeSource='chatgpt_response_create_time';r.timeConfidence='high';r.sourceSentAt='2021-01-01T00:00:00.000Z';}],['inputDocument',r=>{r.source.title='SYNTHETIC different title';}],['baselineRevision',r=>{r.at='2020-01-01T00:00:00.000Z';}],['baselineRevision',r=>{r.after.note='SYNTHETIC hidden earlier edit';}]]){await assert.rejects(async()=>owner.receive(await reseal(ops,type,change)));assert.deepEqual(await snapshot(b),before);}});
test('valid separate captures cannot lend members or descriptors to one another',async()=>{const a=await source(),c=await source(),one=(await publish(a)).decoded,two=(await publish(c)).decoded,b=await fresh('synthetic_bootstrap_receiver'),before=await snapshot(b),owner=new SourceBootstrapReceiver(b.s,b.core);for(const op of one){const replacement=two.find(x=>x.type===op.type&&(x.type==='sourceBootstrapCommit'||x.value.entityType===op.value.entityType));await assert.rejects(owner.receive(one.map(x=>x===op?replacement:x)));assert.deepEqual(await snapshot(b),before);}});
test('deleted Source cannot be recreated by exact acknowledged bootstrap replay',async()=>{const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),owner=new SourceBootstrapReceiver(b.s,b.core);await owner.receive(ops);const id=(await b.s.snapshot()).records[0].id;await b.s.purge(id,true);const before=await snapshot(b);await assert.rejects(owner.receive(ops),{code:'BNS_SOURCE_BOOTSTRAP_CHANGED'});assert.deepEqual(await snapshot(b),before);});
test('old acknowledged bootstrap is refused after same-value restore epoch changes',async()=>{const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),owner=new SourceBootstrapReceiver(b.s,b.core);await owner.receive(ops);await b.s.repository.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:'synthetic_replaced_epoch'}));const before=await snapshot(b);await assert.rejects(owner.receive(ops),{code:'BNS_RESTORE_EPOCH_CHANGED'});assert.deepEqual(await snapshot(b),before);});
test('existing conversation or local capture is not silently merged into initial bootstrap scope',async()=>{const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver');await b.s.capture(capture((await b.s.status()).epoch,'synthetic_other_message'));const before=await snapshot(b);await assert.rejects(new SourceBootstrapReceiver(b.s,b.core).receive(ops),{code:'BNS_SOURCE_BOOTSTRAP_UNAVAILABLE'});assert.deepEqual(await snapshot(b),before);});
test('malformed descriptor refs and unknown member fields reject as typed codec errors',async()=>{const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),before=await snapshot(b),owner=new SourceBootstrapReceiver(b.s,b.core);for(const bad of [null,1,{type:'sourceBootstrapMember'},'bad']){const next=structuredClone(ops);next.find(x=>x.type==='sourceBootstrapCommit').value.members[0]=bad;await assert.rejects(owner.receive(next),{code:'BNS_SOURCE_BOOTSTRAP_INVALID'});assert.deepEqual(await snapshot(b),before);}const next=structuredClone(ops);next.find(x=>x.type==='sourceBootstrapMember').value.extra=true;await assert.rejects(owner.receive(next),{code:'BNS_SOURCE_BOOTSTRAP_INVALID'});assert.deepEqual(await snapshot(b),before);});
test('default null keeps ordinary capture duplicates and enrichment without bootstrap wire publication',async()=>{const a=await fresh('synthetic_unbound_capture'),q=capture((await a.s.status()).epoch);assert.equal(a.s.sourceBootstrapJournal,null);await a.s.capture(q);assert.equal((await a.s.capture(q)).duplicates,1);await a.s.enrich({...q,chat:{id:q.chat.id,url:q.chat.url},messages:[{sourceMessageId:q.messages[0].sourceMessageId,pageOrder:1,sourceTime:{state:'valid',createTime:1609459200,updateTime:null}}]});assert.equal((await a.s.snapshot()).records[0].sourceSentAt,'2021-01-01T00:00:00.000Z');assert.deepEqual(await all(a.core),[]);});
import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
test('actual checkpoint staging refuses the required bootstrap family and cannot activate partial canonical Source',async()=>{const a=await source(),b=await fresh('synthetic_bootstrap_receiver'),objects=new Map(),transport={async putImmutable(ref,data){objects.set(ref.id,data.slice());},async get(ref){return objects.get(ref.id)?.slice();}},checkpoint=await buildCheckpoint(a.core,transport),before=await snapshot(b),owner=new StagedSyncRestore(b.core);await assert.rejects(owner.stageCheckpoint(checkpoint.ref,ref=>transport.get(ref)),{code:'BNS_SOURCE_BOOTSTRAP_REQUIRED'});await assert.rejects(owner.activate(),{code:'BNS_RESTORE_NOT_READY'});const after=await snapshot(b);for(const name of Object.keys(before).filter(x=>x!=='meta'))assert.deepEqual(after[name],before[name]);assert.equal(await b.core.namespace(),'initial');assert.deepEqual(await b.core.state(),[]);assert.deepEqual(await all(b.core),[]);});
test('canonical refresh mutation cannot slip into committed outbox despite a valid prepared Source plan',async()=>{const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);const before=await snapshot(a),refresh=a.s.refreshDoc.bind(a.s);a.s.refreshDoc=async(t,id)=>{await refresh(t,id);const row=await t.get('libraryDocuments',id);row.value.userTitle='SYNTHETIC unexpected mutation';await t.put('libraryDocuments',row);};await assert.rejects(a.s.capture(capture((await a.s.status()).epoch)),{code:'BNS_SOURCE_BOOTSTRAP_CHANGED'});assert.deepEqual(await snapshot(a),before);});
test('Source ledger cannot carry a createTime inconsistent with its qualified response candidate',async()=>{const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);const q=capture((await a.s.status()).epoch);q.messages[0].sourceTime={state:'valid',createTime:1609459200,updateTime:null};await a.s.capture(q);const ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),before=await snapshot(b),bad=await reseal(ops,'timeEvidence',x=>{x.value.createTime+=1;});await assert.rejects(new SourceBootstrapReceiver(b.s,b.core).receive(bad),{code:'BNS_SOURCE_TIME_MISMATCH'});assert.deepEqual(await snapshot(b),before);});
test('actual DOM/response conflict and blocked time remain qualified, while fabricated empty or historical conflict ledgers refuse',async()=>{for(const kind of ['conflict','blocked']){const a=await fresh('synthetic_bootstrap_sender');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);const q=capture((await a.s.status()).epoch);q.messages[0].sourceTime=kind==='blocked'?{state:'blocked',createTime:null,updateTime:null}:{state:'valid',createTime:1609459200,updateTime:null};if(kind==='conflict')q.messages[0].domTime={source:'chatgpt_dom',timestamp:'2021-01-02T00:00:00.000Z',identity:{chatId:q.chat.id,sourceMessageId:q.messages[0].sourceMessageId}};await a.s.capture(q);const b=await fresh('synthetic_bootstrap_receiver'),ops=(await publish(a)).decoded;await new SourceBootstrapReceiver(b.s,b.core).receive(ops);assert.deepEqual((await snapshot(b)).times,(await snapshot(a)).times);assert.equal((await b.s.snapshot()).records[0].sourceSentAt,null);}const a=await source(),ops=(await publish(a)).decoded,b=await fresh('synthetic_bootstrap_receiver'),before=await snapshot(b);for(const ledger of [{blocked:false,createTime:null,candidates:{}},{blocked:false,createTime:null,candidates:{},domConflict:true}]){const bad=await reseal(ops,'timeEvidence',x=>{x.value=ledger;});await assert.rejects(new SourceBootstrapReceiver(b.s,b.core).receive(bad),{code:'BNS_SOURCE_TIME_MISMATCH'});assert.deepEqual(await snapshot(b),before);}});
