import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {ContextCardsService,readContextCards} from '../core/context-cards.js';
import {PromptReuseService} from '../core/prompt-reuse-service.js';
import {readPromptPreferences} from '../core/prompt-reuse-preferences.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {ContextManualSyncJournal} from '../core/browser-native-sync/context-journal.js';
import {PromptSyncJournal} from '../core/browser-native-sync/prompt-journal.js';
import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
import {projectEntity} from '../core/browser-native-sync/codecs.js';
import {readCanonicalReadiness} from '../core/browser-native-sync/canonical-readiness.js';
import {manualSyncOwners as binding} from '../core/browser-native-sync/manual-owners.js';
const uid=()=>crypto.randomUUID();
async function mixedDevice(){const f=await setup(OrganizerStore);await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_mixed',deviceId:uid()});core.materialize=binding(core).materialize;return {...f,core,cards:new ContextCardsService(f.s,{syncJournal:new ContextManualSyncJournal(core)}),prompts:new PromptReuseService(f.s,{syncJournal:new PromptSyncJournal(core)})};}
const allMeta=f=>f.s.repository.transaction(false,t=>t.all('meta'));
const cardRow=f=>f.s.repository.transaction(false,readContextCards);
const prefs=f=>f.s.repository.transaction(false,readPromptPreferences);
async function operations(f){const rows=[];for await(const r of f.core.rows('outbox'))rows.push((await f.core.read('revision',r.revisionId)).operation);return rows.sort((a,b)=>a.sequence-b.sequence);}
async function populate(f){await f.prompts.change({action:'create',revision:0,text:'SYNTHETIC saved Prompt'});for(const card of ['info','rules','now'])await f.cards.change({kind:'put',card,itemId:uid(),operationId:uid(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC '+card,section:'Synthetic section'});}
async function stageMixed(a,b){const objects=new Map(),transport={async putImmutable(r,bytes){objects.set(r.id,bytes.slice());},async get(r){return objects.get(r.id).slice();}},cp=await buildCheckpoint(a.core,transport),r=new StagedSyncRestore(b.core);r.owners=binding(r.stage).owners;await r.stageCheckpoint(cp.ref,x=>transport.get(x));return r;}
async function equalOwners(a,b){assert.deepEqual((await cardRow(b)).items.sort((x,y)=>x.order-y.order),(await cardRow(a)).items);assert.deepEqual((await prefs(b)).overrides,(await prefs(a)).overrides);assert.equal((await cardRow(b)).access.global.enabled,false);}
test('one Core dispatches four real owners with one sequence and conservative readiness',async()=>{const a=await mixedDevice(),b=await mixedDevice();await populate(a);const ops=await operations(a);assert.deepEqual(ops.map(x=>x.sequence),[1,2,3,4]);assert.deepEqual(ops.map(x=>x.type),['promptPreferences','contextItem','contextRulesItem','contextNowItem']);for(const operation of ops)await b.core.receive(operation);await equalOwners(a,b);assert.equal((await readCanonicalReadiness(b.core)).fullCanonicalReady,false);});
test('mixed staged restore rolls all canonical domains and active namespace back together',async()=>{const a=await mixedDevice(),b=await mixedDevice();await populate(a);const r=await stageMixed(a,b),before=await allMeta(b);r.checkpoint=async phase=>{if(phase==='after-activation')throw Error('SYNTHETIC abort');};await assert.rejects(r.activate());assert.deepEqual(await allMeta(b),before);r.checkpoint=async()=>{};await r.activate();await equalOwners(a,b);});
for(const domain of ['prompt','context'])test('mixed activation refuses unmanaged '+domain+' and preserves every meta row',async()=>{const a=await mixedDevice(),b=await mixedDevice();await populate(a);if(domain==='prompt')await new PromptReuseService(b.s).change({action:'create',revision:0,text:'SYNTHETIC private local'});else{const item=(await cardRow(a)).items[0];await new ContextCardsService(b.s).change({kind:'put',card:'info',itemId:item.id,operationId:uid(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC private local',section:'Synthetic section'});}const r=await stageMixed(a,b),before=await allMeta(b);await assert.rejects(r.activate(),e=>e.code==='BNS_RESTORE_UNMANAGED_OWNER');assert.deepEqual(await allMeta(b),before);});
test('shared Core rejects concurrent prepared state from another domain without partial owner write',async()=>{const a=await mixedDevice();await populate(a);const prepared=await a.core.prepare([{type:'promptPreferences',value:projectEntity('promptPreferences',await prefs(a))}]);const item=(await cardRow(a)).items[0];await a.cards.change({kind:'put',card:'info',itemId:item.id,operationId:uid(),epoch:'initial',expectedRevision:1,body:'SYNTHETIC current edit',section:'Synthetic section'});const before=await allMeta(a);await assert.rejects(a.core.commit(prepared),e=>e.code==='BNS_PREPARATION_STALE');assert.deepEqual(await allMeta(a),before);});
test('mixed receive rolls earlier Prompt materialization back when a Context owner rejects',async()=>{const a=await mixedDevice(),b=await mixedDevice();await populate(a);const item=(await cardRow(a)).items[0];await new ContextCardsService(b.s).change({kind:'put',card:'info',itemId:item.id,operationId:uid(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC local collision',section:'Synthetic section'});const before=await allMeta(b);await assert.rejects(b.core.receiveBatch(await operations(a)),e=>e.code==='BNS_RESTORE_UNMANAGED_OWNER');assert.deepEqual(await allMeta(b),before);});
test('dispatcher refuses non-admitted types without invoking any transaction write',async()=>{const a=await mixedDevice();for(const type of ['source','contextDesired','toString','unknown'])await assert.rejects(binding(a.core).materialize({put(){throw Error('must not write');}},{operation:{type}}),e=>e.code==='BNS_MATERIALIZER_UNSUPPORTED');assert.deepEqual(Object.keys(binding(a.core).owners),['promptPreferences','contextItem','contextRulesItem','contextNowItem']);});
