import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {ContextCardsService,readContextCards} from '../core/context-cards.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {ContextManualSyncJournal,contextManualMaterializer} from '../core/browser-native-sync/context-journal.js';
import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
import {validateEntity,validateCoverage} from '../core/browser-native-sync/codecs.js';
import {readCanonicalReadiness} from '../core/browser-native-sync/canonical-readiness.js';
for(const card of ['rules','now']){
const type=card==='rules'?'contextRulesItem':'contextNowItem';
const op=()=>crypto.randomUUID(),collect=async iterable=>{const all=[];for await(const x of iterable)all.push(x);return all;};
async function device(){const f=await setup(OrganizerStore);await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_context',deviceId:op()}),journal=new ContextManualSyncJournal(core);core.materialize=contextManualMaterializer(core);return {...f,core,journal,cards:new ContextCardsService(f.s,{syncJournal:journal}),plain:new ContextCardsService(f.s)};}
const change=(extra={})=>({kind:'put',card,itemId:op(),operationId:op(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC immutable human '+card,section:'Synthetic section',...extra});
const row=f=>f.s.repository.transaction(false,readContextCards);
const meta=f=>f.s.repository.transaction(false,t=>t.all('meta'));
const out=f=>collect(f.core.rows('outbox'));
async function sent(f,c){await f.cards.change(c);const ref=(await out(f)).find(x=>x.operationId===c.operationId);return (await f.core.read('revision',ref.revisionId)).operation;}
function transport(){const objects=new Map();return {async putImmutable(r,b){objects.set(r.id,b.slice());},async get(r){return objects.get(r.id).slice();}};}
function restore(f){const r=new StagedSyncRestore(f.core);r.owners=Object.fromEntries(['contextItem','contextRulesItem','contextNowItem'].map(type=>[type,contextManualMaterializer(r.stage)]));return r;}
test(card+' actual optional owner commits Item, local receipt and outbox once; default owner unchanged',async()=>{const f=await device(),c=change(),result=await f.cards.change(c);assert.equal(result.ok,true);assert.deepEqual(await f.cards.change(c),result);assert.equal((await out(f)).length,1);assert.equal((await row(f)).items[0].revision,1);const g=await device();await g.plain.change(change({card:'rules'}));assert.equal((await out(g)).length,0);});
test(card+' real edit delete restore chain retains revisions/deletedBy and old delivery cannot resurrect',async()=>{const a=await device(),b=await device(),c=change();const first=await sent(a,c);await b.core.receive(first);const edit=change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC edited Info'});await b.core.receive(await sent(a,edit));const del={kind:'delete',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:2};await b.core.receive(await sent(a,del));assert.equal((await row(b)).items[0].lifecycle,'removed');await b.core.receive(first);assert.equal((await row(b)).items[0].lifecycle,'removed');await assert.rejects(a.cards.change({kind:'restore',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:3,deletedBy:op()}),e=>e.code==='CONTEXT_INVALIDATED');const undo={kind:'restore',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:3,deletedBy:del.operationId};await b.core.receive(await sent(a,undo));assert.deepEqual((await row(b)).items,(await row(a)).items);});
for(const phase of ['journal','receipt'])test(card+' actual '+phase+' abort rolls back canonical, outbox and command receipt',async()=>{const f=await device(),before=await meta(f),receipts=await f.s.repository.transaction(false,t=>t.all('operationReceipts'));if(phase==='journal')f.journal.commit=async()=>{throw Error('synthetic abort');};else{const write=f.s.write.bind(f.s);f.s.write=fn=>write(t=>{const put=t.put.bind(t);t.put=(store,value)=>{if(store==='operationReceipts'&&value.namespace==='context-cards')throw Error('synthetic abort');return put(store,value);};return fn(t);});}await assert.rejects(f.cards.change(change()));assert.deepEqual(await meta(f),before);assert.deepEqual(await f.s.repository.transaction(false,t=>t.all('operationReceipts')),receipts);});
for(const kind of ['unmanaged','edited','deleted-same-body'])test(card+' receive refuses '+kind+' canonical owner without protocol side effects',async()=>{const a=await device(),b=await device(),c=change(),first=await sent(a,c);if(kind==='unmanaged')await b.plain.change(c);else{await b.core.receive(first);await b.plain.change(kind==='edited'?change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC private local edit'}):{kind:'delete',itemId:c.itemId,operationId:op(),expectedRevision:1,epoch:'initial'});}const remote=kind==='unmanaged'?first:await sent(a,change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC remote edit'})),before=await meta(b);await assert.rejects(b.core.receive(remote),e=>e.code===(kind==='unmanaged'?'BNS_RESTORE_UNMANAGED_OWNER':'BNS_OWNER_CHANGED'));assert.deepEqual(await meta(b),before);});
test(card+' remote receive preserves unrelated Item and enabled local access exactly',async()=>{const a=await device(),b=await device();await b.plain.change(change({card:'rules'}));for(const key of ['global','info'])await b.plain.change({kind:'access',key,enabled:true,expectedRevision:0,epoch:'initial',operationId:op()});const before=await row(b);await b.core.receive(await sent(a,change()));const after=await row(b);assert.deepEqual(after.access,before.access);assert.deepEqual(after.items[0],before.items[0]);});
test(card+' staged restore proves whole chain and activation abort leaves old generation untouched',async()=>{const a=await device(),b=await device(),c=change();await sent(a,c);await sent(a,{kind:'delete',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:1});const cloud=transport(),cp=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(cp.ref,x=>cloud.get(x));const before=await meta(b);r.checkpoint=async phase=>{if(phase==='after-activation')throw Error('synthetic abort');};await assert.rejects(r.activate());assert.deepEqual(await meta(b),before);r.checkpoint=async()=>{};await r.activate();assert.deepEqual((await row(b)).items,(await row(a)).items);assert.equal((await row(b)).access.global.enabled,false);});
test(card+' invalid restore transition cannot smuggle a different body through a removed predecessor',async()=>{const a=await device(),b=await device(),c=change(),first=await sent(a,c);await b.core.receive(first);const d=await sent(a,{kind:'delete',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:1});await b.core.receive(d);const value={...d.value,body:'SYNTHETIC forged restore body',revision:3,lifecycle:'active',deletedBy:null},prepared=await a.core.prepare([{type,value}]);const before=await meta(b);await assert.rejects(b.core.receive(prepared.operations[0]),e=>e.code==='BNS_CONTEXT_TRANSITION_INVALID');assert.deepEqual(await meta(b),before);});
test(card+' bootstrap preserves existing manual Context and supports fresh exact restore',async()=>{const a=await device(),b=await device(),c=change();await a.plain.change(c);await assert.rejects(a.cards.change(change({...c,operationId:op(),expectedRevision:1})),e=>e.code==='BNS_BOOTSTRAP_REQUIRED');await a.journal.bootstrap(c.itemId);const cloud=transport(),cp=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(cp.ref,x=>cloud.get(x));await r.activate();assert.deepEqual((await row(b)).items,(await row(a)).items);});

test(card+' bootstrap rejects a concurrent same-value head installed between owner validation and prepare',async()=>{const f=await device(),c=change();await f.plain.change(c);const prepare=f.core.prepare.bind(f.core);let once=true;f.core.prepare=async(...args)=>{if(once){once=false;await f.journal.bootstrap(c.itemId);}return prepare(...args);};await assert.rejects(f.journal.bootstrap(c.itemId),e=>e.code==='BNS_HEAD_CHANGED');assert.equal((await out(f)).length,1);assert.equal((await row(f)).items[0].revision,1);});
test(card+' manual Context unmaterialized ancestry still rejects 129 atomically',async()=>{const a=await device(),b=await device(),c=change();b.core.materialize=null;for(let revision=0;revision<128;revision++)await b.core.receive(await sent(a,change({...c,operationId:op(),expectedRevision:revision})));assert.equal((await row(b)).items.length,0);b.core.materialize=contextManualMaterializer(b.core);const next=await sent(a,change({...c,operationId:op(),expectedRevision:128})),before=await meta(b);await assert.rejects(b.core.receive(next),e=>e.code==='BNS_CONTEXT_ANCESTRY_LIMIT');assert.deepEqual(await meta(b),before);});
test(card+' existing Item change rejects same-value head advancement after validation before prepare',async()=>{const f=await device(),c=change();await f.cards.change(c);const prepare=f.core.prepare.bind(f.core);let once=true;f.core.prepare=async(...args)=>{if(once){once=false;const item=(await row(f)).items[0],p=await prepare([{type,value:item}]);await f.core.transaction(true,t=>f.core.commitPrepared(t,p,{materialize:false}));}return prepare(...args);};const beforeRow=await row(f),beforeReceipts=await f.s.repository.transaction(false,t=>t.all('operationReceipts'));await assert.rejects(f.cards.change(change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC must not commit'})),e=>e.code==='BNS_HEAD_CHANGED');assert.deepEqual(await row(f),beforeRow);assert.deepEqual(await f.s.repository.transaction(false,t=>t.all('operationReceipts')),beforeReceipts);assert.equal((await out(f)).length,2,'only the original and injected head exist; rejected owner writes no outbox');});

test(card+' exact codec scope and old reader coverage remain conservative',async()=>{const f=await device(),c=change();await f.cards.change(c);const item=(await row(f)).items[0];assert.deepEqual(validateEntity(type,item),item);for(const delta of [{card:'info'},{card:card==='rules'?'now':'rules'},{origin:'automatic'},{protected:false},{maintenance:{}}])assert.throws(()=>validateEntity(type,{...item,...delta}),{code:'BNS_CODEC_UNSUPPORTED'});assert.throws(()=>validateEntity('contextItem',item),{code:'BNS_CODEC_UNSUPPORTED'});assert.throws(()=>validateCoverage([{type,version:1,count:1}],{contextItem:1,contextDesired:1,promptPreferences:1,source:1}),{code:'BNS_REQUIRED_CODEC_UNSUPPORTED'});const ready=await readCanonicalReadiness(f.core);assert.equal(ready.families.find(x=>x.type===type).count,1);assert.equal(ready.fullCanonicalReady,false);assert.equal(ready.families.find(x=>x.type===type).ready,false);});
test(card+' access stays local; purge and cross-card same ID never overwrite owner',async()=>{const a=await device(),b=await device(),c=change();await b.core.receive(await sent(a,c));const before=await meta(b);const otherCard=card==='rules'?'now':'rules',otherType=card==='rules'?'contextNowItem':'contextRulesItem';const x=await device(),replacement=await sent(x,change({...c,card:otherCard,operationId:op()}));assert.equal(replacement.type,otherType);await assert.rejects(b.core.receive(replacement),e=>e.code==='BNS_RESTORE_UNMANAGED_OWNER');assert.deepEqual(await meta(b),before);const p=await a.core.prepare([{type,entityId:c.itemId,kind:'purge'}]);await assert.rejects(b.core.receive(p.operations[0]),e=>e.code==='BNS_CONTEXT_PURGE_SCOPE_UNAVAILABLE');assert.deepEqual(await meta(b),before);const localProtocol=(await meta(a)).filter(x=>x.id.startsWith('bns:'));assert.equal((await a.cards.change({kind:'access',key:card,enabled:true,expectedRevision:0,epoch:'initial',operationId:op()})).ok,true);assert.deepEqual((await meta(a)).filter(x=>x.id.startsWith('bns:')),localProtocol);});

test(card+' mixed Info Rules Now checkpoint restores all exact Items with local access off',async()=>{const a=await device(),b=await device();for(const card of ['info','rules','now'])await sent(a,change({card}));const cloud=transport(),cp=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(cp.ref,x=>cloud.get(x));await r.activate();const restored=(await row(b)).items.sort((a,b)=>a.order-b.order);assert.deepEqual(restored,(await row(a)).items);assert.deepEqual(restored.map(x=>x.card),['info','rules','now']);assert.equal((await row(b)).access.global.enabled,false);});

}
