import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {ContextCardsService,readContextCards} from '../core/context-cards.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {ContextInfoSyncJournal,contextInfoMaterializer} from '../core/browser-native-sync/context-journal.js';
import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
const op=()=>crypto.randomUUID(),collect=async iterable=>{const all=[];for await(const x of iterable)all.push(x);return all;};
async function device(){const f=await setup(OrganizerStore);await f.s.finishFoundation();const core=new BrowserNativeSyncCore(f.s.repository,{datasetId:'synthetic_context',deviceId:op()}),journal=new ContextInfoSyncJournal(core);core.materialize=contextInfoMaterializer(core);return {...f,core,journal,cards:new ContextCardsService(f.s,{syncJournal:journal}),plain:new ContextCardsService(f.s)};}
const change=(extra={})=>({kind:'put',card:'info',itemId:op(),operationId:op(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC immutable human Info',section:'Synthetic section',...extra});
const row=f=>f.s.repository.transaction(false,readContextCards);
const meta=f=>f.s.repository.transaction(false,t=>t.all('meta'));
const out=f=>collect(f.core.rows('outbox'));
async function sent(f,c){await f.cards.change(c);const ref=(await out(f)).find(x=>x.operationId===c.operationId);return (await f.core.read('revision',ref.revisionId)).operation;}
function transport(){const objects=new Map();return {async putImmutable(r,b){objects.set(r.id,b.slice());},async get(r){return objects.get(r.id).slice();}};}
function restore(f){const r=new StagedSyncRestore(f.core);r.owners={contextItem:contextInfoMaterializer(r.stage)};return r;}
test('actual optional owner commits Item, local receipt and outbox once; default owner unchanged',async()=>{const f=await device(),c=change(),result=await f.cards.change(c);assert.equal(result.ok,true);assert.deepEqual(await f.cards.change(c),result);assert.equal((await out(f)).length,1);assert.equal((await row(f)).items[0].revision,1);const g=await device();await g.plain.change(change({card:'rules'}));assert.equal((await out(g)).length,0);});
test('real edit delete restore chain retains revisions/deletedBy and old delivery cannot resurrect',async()=>{const a=await device(),b=await device(),c=change();const first=await sent(a,c);await b.core.receive(first);const edit=change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC edited Info'});await b.core.receive(await sent(a,edit));const del={kind:'delete',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:2};await b.core.receive(await sent(a,del));assert.equal((await row(b)).items[0].lifecycle,'removed');await b.core.receive(first);assert.equal((await row(b)).items[0].lifecycle,'removed');await assert.rejects(a.cards.change({kind:'restore',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:3,deletedBy:op()}),e=>e.code==='CONTEXT_INVALIDATED');const undo={kind:'restore',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:3,deletedBy:del.operationId};await b.core.receive(await sent(a,undo));assert.deepEqual((await row(b)).items,(await row(a)).items);});
for(const phase of ['journal','receipt'])test('actual '+phase+' abort rolls back canonical, outbox and command receipt',async()=>{const f=await device(),before=await meta(f),receipts=await f.s.repository.transaction(false,t=>t.all('operationReceipts'));if(phase==='journal')f.journal.commit=async()=>{throw Error('synthetic abort');};else{const write=f.s.write.bind(f.s);f.s.write=fn=>write(t=>{const put=t.put.bind(t);t.put=(store,value)=>{if(store==='operationReceipts'&&value.namespace==='context-cards')throw Error('synthetic abort');return put(store,value);};return fn(t);});}await assert.rejects(f.cards.change(change()));assert.deepEqual(await meta(f),before);assert.deepEqual(await f.s.repository.transaction(false,t=>t.all('operationReceipts')),receipts);});
for(const kind of ['unmanaged','edited','deleted-same-body'])test('receive refuses '+kind+' canonical owner without protocol side effects',async()=>{const a=await device(),b=await device(),c=change(),first=await sent(a,c);if(kind==='unmanaged')await b.plain.change(c);else{await b.core.receive(first);await b.plain.change(kind==='edited'?change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC private local edit'}):{kind:'delete',itemId:c.itemId,operationId:op(),expectedRevision:1,epoch:'initial'});}const remote=kind==='unmanaged'?first:await sent(a,change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC remote edit'})),before=await meta(b);await assert.rejects(b.core.receive(remote),e=>e.code===(kind==='unmanaged'?'BNS_RESTORE_UNMANAGED_OWNER':'BNS_OWNER_CHANGED'));assert.deepEqual(await meta(b),before);});
test('remote receive preserves unrelated Item and enabled local access exactly',async()=>{const a=await device(),b=await device();await b.plain.change(change({card:'rules'}));for(const key of ['global','info'])await b.plain.change({kind:'access',key,enabled:true,expectedRevision:0,epoch:'initial',operationId:op()});const before=await row(b);await b.core.receive(await sent(a,change()));const after=await row(b);assert.deepEqual(after.access,before.access);assert.deepEqual(after.items[0],before.items[0]);});
test('staged restore proves whole chain and activation abort leaves old generation untouched',async()=>{const a=await device(),b=await device(),c=change();await sent(a,c);await sent(a,{kind:'delete',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:1});const cloud=transport(),cp=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(cp.ref,x=>cloud.get(x));const before=await meta(b);r.checkpoint=async phase=>{if(phase==='after-activation')throw Error('synthetic abort');};await assert.rejects(r.activate());assert.deepEqual(await meta(b),before);r.checkpoint=async()=>{};await r.activate();assert.deepEqual((await row(b)).items,(await row(a)).items);assert.equal((await row(b)).access.global.enabled,false);});
test('invalid restore transition cannot smuggle a different body through a removed predecessor',async()=>{const a=await device(),b=await device(),c=change(),first=await sent(a,c);await b.core.receive(first);const d=await sent(a,{kind:'delete',itemId:c.itemId,operationId:op(),epoch:'initial',expectedRevision:1});await b.core.receive(d);const value={...d.value,body:'SYNTHETIC forged restore body',revision:3,lifecycle:'active',deletedBy:null},prepared=await a.core.prepare([{type:'contextItem',value}]);const before=await meta(b);await assert.rejects(b.core.receive(prepared.operations[0]),e=>e.code==='BNS_CONTEXT_TRANSITION_INVALID');assert.deepEqual(await meta(b),before);});
test('bootstrap preserves existing manual Info and supports fresh exact restore',async()=>{const a=await device(),b=await device(),c=change();await a.plain.change(c);await assert.rejects(a.cards.change(change({...c,operationId:op(),expectedRevision:1})),e=>e.code==='BNS_BOOTSTRAP_REQUIRED');await a.journal.bootstrap(c.itemId);const cloud=transport(),cp=await buildCheckpoint(a.core,cloud),r=restore(b);await r.stageCheckpoint(cp.ref,x=>cloud.get(x));await r.activate();assert.deepEqual((await row(b)).items,(await row(a)).items);});
test('scope refuses access, Rules, Now and permanent purge without inventing owners',async()=>{const f=await device();for(const c of [change({card:'rules'}),change({card:'now'}),{kind:'access',key:'global',enabled:true,expectedRevision:0,epoch:'initial',operationId:op()}])await assert.rejects(f.cards.change(c));const a=await device(),c=change();await f.core.receive(await sent(a,c));const p=await a.core.prepare([{type:'contextItem',entityId:c.itemId,kind:'purge'}]),before=await meta(f);await assert.rejects(f.core.receive(p.operations[0]),e=>e.code==='BNS_CONTEXT_PURGE_SCOPE_UNAVAILABLE');assert.deepEqual(await meta(f),before);});

test('bootstrap rejects a concurrent same-value head installed between owner validation and prepare',async()=>{const f=await device(),c=change();await f.plain.change(c);const prepare=f.core.prepare.bind(f.core);let once=true;f.core.prepare=async(...args)=>{if(once){once=false;await f.journal.bootstrap(c.itemId);}return prepare(...args);};await assert.rejects(f.journal.bootstrap(c.itemId),e=>e.code==='BNS_HEAD_CHANGED');assert.equal((await out(f)).length,1);assert.equal((await row(f)).items[0].revision,1);});
test('manual Info causal bound accepts 128 and rejects 129 atomically',async()=>{const a=await device(),b=await device(),c=change();for(let revision=0;revision<128;revision++)await b.core.receive(await sent(a,change({...c,operationId:op(),expectedRevision:revision})));assert.equal((await row(b)).items[0].revision,128);const next=await sent(a,change({...c,operationId:op(),expectedRevision:128})),before=await meta(b);await assert.rejects(b.core.receive(next),e=>e.code==='BNS_CONTEXT_ANCESTRY_LIMIT');assert.deepEqual(await meta(b),before);});
test('existing Item change rejects same-value head advancement after validation before prepare',async()=>{const f=await device(),c=change();await f.cards.change(c);const prepare=f.core.prepare.bind(f.core);let once=true;f.core.prepare=async(...args)=>{if(once){once=false;const item=(await row(f)).items[0],p=await prepare([{type:'contextItem',value:item}]);await f.core.transaction(true,t=>f.core.commitPrepared(t,p,{materialize:false}));}return prepare(...args);};const beforeRow=await row(f),beforeReceipts=await f.s.repository.transaction(false,t=>t.all('operationReceipts'));await assert.rejects(f.cards.change(change({...c,operationId:op(),expectedRevision:1,body:'SYNTHETIC must not commit'})),e=>e.code==='BNS_HEAD_CHANGED');assert.deepEqual(await row(f),beforeRow);assert.deepEqual(await f.s.repository.transaction(false,t=>t.all('operationReceipts')),beforeReceipts);assert.equal((await out(f)).length,2,'only the original and injected head exist; rejected owner writes no outbox');});
