import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {LibraryFoundationStore} from '../core/thought-store.js';
import {local,capture,inputEdit} from './harness/thought-m1.mjs';
import {BrowserNativeSyncCore,sealOperation,CORE_LIMITS} from '../core/browser-native-sync/core.js';
import {SourceBootstrapJournal} from '../core/browser-native-sync/source-bootstrap-journal.js';
import {FilterIntentSyncJournal} from '../core/browser-native-sync/filter-intent-journal.js';
import {InputWorkingSyncJournal} from '../core/browser-native-sync/input-working-journal.js';
import {prepareGroupCheckpointPlan,requireOriginalGroupCheckpointPlan} from '../core/browser-native-sync/group-checkpoint-plan.js';
globalThis.IDBKeyRange=IDBKeyRange;
async function setup(){const s=new LibraryFoundationStore(local(),{indexedDB:new IDBFactory()});await s.consent(true);await s.finishFoundation();const core=new BrowserNativeSyncCore(s.repository,{datasetId:'synthetic_group_dataset',deviceId:'synthetic_group_device'});s.sourceBootstrapJournal=new SourceBootstrapJournal(core);await s.capture(capture((await s.status()).epoch));return {s,core};}
async function ops(core){const out=[];for await(const row of core.rows('revision'))out.push(row.operation);return out;}
test('native compilation identity rejects a clone, foreign Core and changed binding without altering portable plan bytes',async()=>{
 const {s,core}=await setup(),rows=await ops(core),plan=await prepareGroupCheckpointPlan(core,rows),copy=structuredClone(plan),original=bytes(plan);
 requireOriginalGroupCheckpointPlan(core,plan);assert.deepEqual(bytes(copy),original);
 assert.throws(()=>requireOriginalGroupCheckpointPlan(core,copy),{code:'BNS_GROUP_SCOPE_PROOF_REQUIRED'});
 const other=new BrowserNativeSyncCore(s.repository,{datasetId:core.datasetId,deviceId:core.deviceId});
 assert.throws(()=>requireOriginalGroupCheckpointPlan(other,plan),{code:'BNS_GROUP_SCOPE_PROOF_REQUIRED'});
 const dataset=core.datasetId;try{core.datasetId='synthetic_changed_dataset';assert.throws(()=>requireOriginalGroupCheckpointPlan(core,plan),{code:'BNS_GROUP_SCOPE_PROOF_REQUIRED'});}finally{core.datasetId=dataset;}
 requireOriginalGroupCheckpointPlan(core,plan);assert.deepEqual(bytes(plan),original);
});
test('actual Source append and sequential Working groups form a complete causal plan regardless of arrival order',async()=>{const {s,core}=await setup(),q=capture((await s.status()).epoch);q.messages[0].sourceMessageId='second-message';q.messages[0].originalText='synthetic second';q.messages[0].pageOrder=2;await s.capture(q);s.filterIntentJournal=new FilterIntentSyncJournal(core);s.inputWorkingJournal=new InputWorkingSyncJournal(core,{filterJournal:s.filterIntentJournal,logicalCommits:true});const id=(await s.snapshot()).library.blocks[0].id;await inputEdit(s,id,{note:'first'});await inputEdit(s,id,{note:'second'});const rows=await ops(core),a=await prepareGroupCheckpointPlan(core,rows),b=await prepareGroupCheckpointPlan(core,[...rows].reverse());assert.equal(a.digest,b.digest);assert.equal(a.operationCount,rows.length);assert.equal(a.groups.length,4);assert.equal(a.groups[0].type,'sourceBootstrapCommit');const seen=new Set();for(const group of a.groups){assert.ok(group.dependencies.every(id=>seen.has(id)));seen.add(group.id);}assert.ok(Object.isFrozen(a.groups));});
test('missing member, descriptor and required bootstrap ancestor cannot be treated as a partial plan',async()=>{const {core}=await setup(),rows=await ops(core);for(let i=0;i<rows.length;i++)await assert.rejects(prepareGroupCheckpointPlan(core,rows.filter((_,n)=>n!==i)),{code:'BNS_GROUP_INCOMPLETE'});await assert.rejects(prepareGroupCheckpointPlan(core,[...rows,rows[0]]),{code:'BNS_GROUP_DUPLICATE'});});
test('operation budget counts all ancestry rather than current heads',async()=>{const {core}=await setup(),rows=await ops(core);await assert.rejects(prepareGroupCheckpointPlan(core,Array.from({length:CORE_LIMITS.batch+1},()=>rows[0])),{code:'BNS_GROUP_RESOURCE_LIMIT'});});
import {prepareGroupScope,requireGroupScope} from '../core/browser-native-sync/group-checkpoint-scope.js';
test('actual canonical inventory binds bootstrap plus Working and rejects an unjournaled human title',async()=>{const {s,core}=await setup();s.filterIntentJournal=new FilterIntentSyncJournal(core);s.inputWorkingJournal=new InputWorkingSyncJournal(core,{filterJournal:s.filterIntentJournal,logicalCommits:true});const id=(await s.snapshot()).library.blocks[0].id;await inputEdit(s,id,{note:'human note'});const plan=await prepareGroupCheckpointPlan(core,await ops(core)),scope=await prepareGroupScope(plan);await s.run(()=>core.transaction(false,t=>requireGroupScope(s,t,scope)));s.inputWorkingJournal=null;await s.updateDocument((await s.input(id)).documentId,{userTitle:'unjournaled title'});await assert.rejects(s.run(()=>core.transaction(false,t=>requireGroupScope(s,t,scope))),{code:'BNS_GROUP_CANONICAL_UNREPRESENTED'});});
import {bytes} from '../core/browser-native-sync/value.js';
test('fourMiB operation bytes include all retained payloads, not only final current text',async()=>{const {core}=await setup(),rows=[],id='prompt-reuse:v1',manual='manual:'+crypto.randomUUID();let previous=null;for(let i=0;i<22;i++){const op=await sealOperation({protocol:1,datasetId:core.datasetId,deviceId:core.deviceId,operationId:crypto.randomUUID(),sequence:i+1,type:'promptPreferences',entityId:id,codecVersion:1,kind:'put',actor:'user',parents:previous?[previous]:[],value:{id,version:1,pins:[],overrides:[{id:manual,text:'SYNTHETIC '+('x'.repeat(199950)),hidden:false}],splits:[]}});rows.push(op);previous=op.revisionId;}const under=rows.slice(0,20);assert.ok(under.reduce((n,x)=>n+bytes(x).length,0)<=CORE_LIMITS.batchBytes);assert.equal((await prepareGroupCheckpointPlan(core,under)).operationCount,20);const base={...rows[20],value:{...rows[20].value,overrides:[{...rows[20].value.overrides[0],text:'x'}]}};const length=CORE_LIMITS.batchBytes-under.reduce((n,x)=>n+bytes(x).length,0)-bytes(base).length+1;assert.ok(length>0&&length<200000);base.value.overrides[0].text='x'.repeat(length);const exact=await sealOperation(base);assert.equal((await prepareGroupCheckpointPlan(core,[...under,exact])).operationBytes,CORE_LIMITS.batchBytes);base.value.overrides[0].text+='x';await assert.rejects(prepareGroupCheckpointPlan(core,[...under,await sealOperation(base)]),{code:'BNS_GROUP_RESOURCE_LIMIT'});assert.ok(rows.reduce((n,x)=>n+bytes(x).length,0)>CORE_LIMITS.batchBytes);await assert.rejects(prepareGroupCheckpointPlan(core,rows),{code:'BNS_GROUP_RESOURCE_LIMIT'});});
import {ContextCardsService} from '../core/context-cards.js';
for(const kind of ['note','Context','Topic','AI-metadata','preferences'])test('full inventory rejects actual unjournaled '+kind+' rather than claiming protocol coverage',async()=>{const {s,core}=await setup();if(kind==='note')await inputEdit(s,(await s.snapshot()).library.blocks[0].id,{note:'SYNTHETIC unjournaled note'});if(kind==='Context')await new ContextCardsService(s).change({kind:'put',card:'rules',itemId:crypto.randomUUID(),operationId:crypto.randomUUID(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC unjournaled',section:'Synthetic'});if(kind==='Topic')await s.createTopic({name:'SYNTHETIC unmanaged Topic',operationId:crypto.randomUUID()});if(kind==='AI-metadata')await s.repository.transaction(true,t=>t.put('meta',{id:'aiPresentation:SYNTHETIC',saved:true}));if(kind==='preferences')await s.updatePreferences({language:'en'});const scope=await prepareGroupScope(await prepareGroupCheckpointPlan(core,await ops(core)));await assert.rejects(s.run(()=>core.transaction(false,t=>requireGroupScope(s,t,scope))),{code:'BNS_GROUP_CANONICAL_UNREPRESENTED'});});
