import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {LibraryFoundationStore} from '../core/thought-store.js';
import {local,capture} from './harness/thought-m1.mjs';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {SourceBootstrapJournal} from '../core/browser-native-sync/source-bootstrap-journal.js';
globalThis.IDBKeyRange=IDBKeyRange;
async function fresh(device){const s=new LibraryFoundationStore(local(),{indexedDB:new IDBFactory()});await s.consent(true);await s.finishFoundation();const core=new BrowserNativeSyncCore(s.repository,{datasetId:'synthetic_source_bootstrap',deviceId:device});return {s,core};}
async function all(core){const rows=[];for await(const op of core.outbox())rows.push(op);return rows;}

import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
async function producer(){const a=await fresh('checkpoint_producer');a.s.sourceBootstrapJournal=new SourceBootstrapJournal(a.core);await a.s.capture(capture((await a.s.status()).epoch));return a;}
const cloud=()=>{const rows=new Map();return {async putImmutable(ref,bytes){rows.set(ref.id,bytes.slice());},async get(ref){return rows.get(ref.id)?.slice();}};};
const canonical=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].filter(name=>name!=='meta').map(async name=>[name,await t.all(name)]))));
test('grouped checkpoint restores actual journaled Source into an empty target atomically',async()=>{
 const a=await producer(),b=await fresh('checkpoint_receiver'),transport=cloud();
 const cp=await buildCheckpoint(a.core,transport,{grouped:{store:a.s}}),restore=new StagedSyncRestore(b.core,{grouped:{store:b.s}});
 await restore.stageCheckpoint(cp.ref,ref=>transport.get(ref));
 assert.equal((await b.s.snapshot()).records.length,0);
 assert.equal((await restore.activate()).state,'activated');
 assert.deepEqual((await b.s.snapshot()).records,(await a.s.snapshot()).records);
});
import {InputWorkingSyncJournal} from '../core/browser-native-sync/input-working-journal.js';
import {FilterIntentSyncJournal} from '../core/browser-native-sync/filter-intent-journal.js';
import {ContextDesiredSyncJournal} from '../core/browser-native-sync/context-desired-journal.js';
import {ContextCardsService,readContextCards} from '../core/context-cards.js';
import {PromptSyncJournal} from '../core/browser-native-sync/prompt-journal.js';
import {PromptReuseService} from '../core/prompt-reuse-service.js';
import {readPromptPreferences} from '../core/prompt-reuse-preferences.js';
import {inputEdit} from './harness/thought-m1.mjs';
async function portfolio(){const a=await producer(),q=capture((await a.s.status()).epoch);q.messages[0].sourceMessageId='second-source';q.messages[0].originalText='SYNTHETIC second';q.messages[0].pageOrder=2;await a.s.capture(q);a.s.filterIntentJournal=new FilterIntentSyncJournal(a.core);a.s.inputWorkingJournal=new InputWorkingSyncJournal(a.core,{filterJournal:a.s.filterIntentJournal,logicalCommits:true});const blocks=(await a.s.snapshot()).library.blocks,id=blocks[0].id;await a.s.keepInput(blocks[1].id);await inputEdit(a.s,id,{note:'SYNTHETIC note1'});await inputEdit(a.s,id,{note:'SYNTHETIC note2'});const cards=new ContextCardsService(a.s,{syncJournal:new ContextDesiredSyncJournal(a.core)});for(const card of ['info','rules','now'])await cards.change({kind:'put',card,itemId:crypto.randomUUID(),operationId:crypto.randomUUID(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC '+card,section:'Synthetic section'});for(const key of ['info','rules','now','inputs'])await cards.change({kind:'access',key,enabled:true,expectedRevision:0,epoch:'initial',operationId:crypto.randomUUID()});await new PromptReuseService(a.s,{syncJournal:new PromptSyncJournal(a.core)}).change({action:'create',revision:0,text:'SYNTHETIC saved Prompt'});return a;}
test('complete admitted portfolio activates Source append, Working history, manual Prompt and all manual cards together',async()=>{const a=await portfolio(),b=await fresh('checkpoint_receiver'),transport=cloud();await b.s.repository.transaction(true,t=>t.put('meta',{id:'revision-sequence',value:1000}));const cp=await buildCheckpoint(a.core,transport,{grouped:{store:a.s}}),restore=new StagedSyncRestore(b.core,{grouped:{store:b.s}});await restore.stageCheckpoint(cp.ref,r=>transport.get(r));assert.equal((await b.s.snapshot()).records.length,0);await restore.activate();const x=await a.s.snapshot(),y=await b.s.snapshot();assert.deepEqual(y.records,x.records);assert.deepEqual(y.library.blocks,x.library.blocks);const cardA=await a.core.transaction(false,readContextCards),cardB=await b.core.transaction(false,readContextCards);cardA.items.sort((a,b)=>a.order-b.order);cardB.items.sort((a,b)=>a.order-b.order);assert.deepEqual(cardB,cardA);assert.deepEqual((await b.core.transaction(false,readPromptPreferences)).overrides,(await a.core.transaction(false,readPromptPreferences)).overrides);const before=await canonical(b.s);await restore.activate();assert.deepEqual(await canonical(b.s),before);assert.equal((await all(b.core)).length,0);});
const groupMeasurements=[];
const everything=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].map(async name=>[name,await t.all(name)]))));
async function staged(a=undefined,options={}){a??=await portfolio();const b=await fresh('checkpoint_receiver'),transport=cloud(),cp=await buildCheckpoint(a.core,transport,{grouped:{store:a.s}}),restore=new StagedSyncRestore(b.core,{grouped:{store:b.s},...options});await restore.stageCheckpoint(cp.ref,r=>transport.get(r));return {a,b,transport,cp,restore};}
for(const phase of ['applied-group','before-activation','after-activation'])test('failure at '+phase+' rolls every canonical row, protocol row and active pointer back',async()=>{let abort=true;const f=await staged(undefined,{checkpoint:async at=>{if(abort&&at===phase)throw Error('SYNTHETIC rollback');}}),before=await everything(f.b.s);await assert.rejects(f.restore.activate(),{code:'STORAGE_FAILED'});assert.deepEqual(await everything(f.b.s),before);abort=false;await f.restore.activate();assert.equal((await f.b.s.snapshot()).records.length,2);});
for(const change of ['local-capture','restore-epoch','permission','namespace'])test('prepared grouped activation rejects '+change+' without clobbering the new state',async()=>{const {b,restore}=await staged();if(change==='local-capture')await b.s.capture(capture((await b.s.status()).epoch));if(change==='restore-epoch')await b.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:crypto.randomUUID()}));if(change==='permission')await b.s.setEnabled(false);if(change==='namespace')await b.core.transaction(true,t=>t.put('meta',{id:b.core.prefix+'active',namespace:crypto.randomUUID()}));const before=await everything(b.s);await assert.rejects(restore.activate(),e=>['BNS_RESTORE_LOCAL_CHANGED','BNS_GROUP_PERMISSION'].includes(e.code));assert.deepEqual(await everything(b.s),before);});
test('existing unjournaled Source and existing manual content block construction or target activation',async()=>{const a=await fresh('checkpoint_producer');await a.s.capture(capture((await a.s.status()).epoch));await assert.rejects(buildCheckpoint(a.core,cloud(),{grouped:{store:a.s}}),{code:'BNS_GROUP_CANONICAL_UNREPRESENTED'});const f=await staged();await new PromptReuseService(f.b.s).change({action:'create',revision:0,text:'SYNTHETIC local'});const before=await everything(f.b.s);await assert.rejects(f.restore.activate(),{code:'BNS_RESTORE_LOCAL_CHANGED'});assert.deepEqual(await everything(f.b.s),before);});
test('unknown activation acknowledgement after restart is idempotent but cannot cross a subsequent restore epoch',async()=>{const {b,restore}=await staged();await restore.activate();await inputEdit(b.s,(await b.s.snapshot()).library.blocks[0].id,{note:'SYNTHETIC legal edit after activation'});const before=await everything(b.s),reopened=new StagedSyncRestore(b.core,{restoreId:restore.restoreId,grouped:{store:b.s}});await reopened.activate();assert.deepEqual(await everything(b.s),before);await b.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:crypto.randomUUID()}));const changed=await everything(b.s);await assert.rejects(reopened.activate(),{code:'BNS_RESTORE_LOCAL_CHANGED'});assert.deepEqual(await everything(b.s),changed);});
test('successor full-scope manifest binds an exact tail and rejects proofless/missing/extra operations',async()=>{const a=await producer(),f=await staged(a),old=[];for await(const row of a.core.rows('revision'))old.push(row.operation.revisionId);a.s.filterIntentJournal=new FilterIntentSyncJournal(a.core);a.s.inputWorkingJournal=new InputWorkingSyncJournal(a.core,{filterJournal:a.s.filterIntentJournal,logicalCommits:true});await inputEdit(a.s,(await a.s.snapshot()).library.blocks[0].id,{note:'SYNTHETIC verified tail'});const next=await buildCheckpoint(a.core,f.transport,{grouped:{store:a.s},parents:[f.cp.ref.id]}),delta=[];for await(const row of a.core.rows('revision'))if(!old.includes(row.operation.revisionId))delta.push(row.operation);const proof={ref:next.ref,get:r=>f.transport.get(r)},before=await everything(f.b.s);await assert.rejects(f.restore.reconcileTail(delta),{code:'BNS_GROUP_SCOPE_PROOF_REQUIRED'});for(const bad of [delta.slice(1),[...delta,delta[0]]]){await assert.rejects(f.restore.reconcileTail(bad,proof),{code:'BNS_GROUP_TAIL_INVALID'});assert.deepEqual(await everything(f.b.s),before);}await f.restore.reconcileTail([...delta].reverse(),proof);assert.equal((await f.b.s.snapshot()).records.length,0);await f.restore.activate();assert.deepEqual((await f.b.s.snapshot()).library.blocks,(await a.s.snapshot()).library.blocks);});
test('same-value restore during first object fetch cannot bind stale checkpoint content to a new epoch',async()=>{const a=await producer(),b=await fresh('checkpoint_receiver'),transport=cloud(),cp=await buildCheckpoint(a.core,transport,{grouped:{store:a.s}}),restore=new StagedSyncRestore(b.core,{grouped:{store:b.s}});let first=true,changed;await assert.rejects(restore.stageCheckpoint(cp.ref,async ref=>{const bytes=await transport.get(ref);if(first){first=false;await b.core.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:crypto.randomUUID()}));changed=await everything(b.s);}return bytes;}),{code:'BNS_RESTORE_LOCAL_CHANGED'});assert.deepEqual(await everything(b.s),changed);});
test('bounded cleanup preserves active replay and exact no-op ACK, while abandoned partial stage cannot activate',async()=>{for(const activated of [false,true]){const {b,restore}=await staged();if(activated)await restore.activate();const before=await canonical(b.s),active=await b.core.namespace();let result;for(let i=0;i<200;i++){result=await restore.cleanup({abandon:!activated,limit:3});assert.ok(result.deleted<=3);if(result.complete)break;}assert.equal(result.complete,true);assert.deepEqual(await canonical(b.s),before);assert.equal(await b.core.namespace(),active);if(activated)await restore.activate();else await assert.rejects(restore.activate(),{code:'BNS_RESTORE_NOT_READY'});assert.equal((await restore.cleanup({limit:1})).deleted,0);}});
test('exact128 retained operations restore, the129th refuses, and bounded transaction work is measured',async()=>{const a=await producer(),prompts=new PromptReuseService(a.s,{syncJournal:new PromptSyncJournal(a.core)});await prompts.change({action:'create',revision:0,text:'SYNTHETIC 0'});for(let i=1;i<121;i++){const row=await a.core.transaction(false,readPromptPreferences);await prompts.change({action:'edit',id:row.overrides[0].id,revision:row.revision,text:'SYNTHETIC '+i});}let n=0;for await(const _ of a.core.rows('revision'))n++;assert.equal(n,128);const f=await staged(a),metrics={...f.b.s.repository.metrics},start=performance.now();await f.restore.activate();const elapsedMs=performance.now()-start;const measurement={operations:128,activationMs:elapsedMs,reads:f.b.s.repository.metrics.reads-metrics.reads,writes:f.b.s.repository.metrics.writes-metrics.writes};groupMeasurements.push(measurement);console.log(JSON.stringify({syntheticGroupProfile:measurement}));assert.deepEqual((await f.b.core.transaction(false,readPromptPreferences)).overrides,(await a.core.transaction(false,readPromptPreferences)).overrides);const row=await a.core.transaction(false,readPromptPreferences);await prompts.change({action:'edit',id:row.overrides[0].id,revision:row.revision,text:'SYNTHETIC 129'});await assert.rejects(buildCheckpoint(a.core,cloud(),{grouped:{store:a.s}}),{code:'BNS_GROUP_RESOURCE_LIMIT'});});
test('producer scope requires committed protocol receipts, not matching canonical bytes plus a retained revision alone',async()=>{const a=await producer(),op=(await all(a.core))[0];await a.core.transaction(true,async t=>t.delete('meta',await a.core.idIn(t,'receipt',op.operationId)));await assert.rejects(buildCheckpoint(a.core,cloud(),{grouped:{store:a.s}}),{code:'BNS_GROUP_COMMIT_UNPROVEN'});});
for(const kind of ['document','Prompt','Context'])test('final transport publication cannot advertise stale '+kind+' inventory',async()=>{const a=await producer(),transport=cloud(),put=transport.putImmutable;let manifests=0,changed=false;transport.putImmutable=async(ref,raw)=>{await put(ref,raw);if(ref.kind==='checkpoint-manifest'&&++manifests===2){if(kind==='document')await a.s.updateDocument((await a.s.input((await a.s.snapshot()).library.blocks[0].id)).documentId,{userTitle:'SYNTHETIC post publication title'});if(kind==='Prompt')await new PromptReuseService(a.s).change({action:'create',revision:0,text:'SYNTHETIC post publication Prompt'});if(kind==='Context')await new ContextCardsService(a.s).change({kind:'put',card:'rules',itemId:crypto.randomUUID(),operationId:crypto.randomUUID(),epoch:'initial',expectedRevision:0,body:'SYNTHETIC post publication Context',section:'Synthetic'});changed=true;}};await assert.rejects(buildCheckpoint(a.core,transport,{grouped:{store:a.s}}),e=>['BNS_SNAPSHOT_CHANGED','BNS_GROUP_CANONICAL_UNREPRESENTED'].includes(e.code));assert.equal(changed,true);});
test('final transport publication rechecks receipt proof even without a generation change',async()=>{const a=await producer(),transport=cloud(),put=transport.putImmutable;let manifests=0;transport.putImmutable=async(ref,raw)=>{await put(ref,raw);if(ref.kind==='checkpoint-manifest'&&++manifests===2){const op=(await all(a.core))[0];await a.core.transaction(true,async t=>t.delete('meta',await a.core.idIn(t,'receipt',op.operationId)));}};await assert.rejects(buildCheckpoint(a.core,transport,{grouped:{store:a.s}}),{code:'BNS_GROUP_COMMIT_UNPROVEN'});});
