import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(m=>chrome.runtime.sendMessage(m),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const windowButton=p=>p.locator('.archive-navigator-window').filter({hasText:'SYNTHETIC consumer archive'}).first();
for(const variant of ['source','release'])test('consumer retirement: blank Archive, saved edits/history, local search, privacy and responsive '+variant,{timeout:180000},async t=>{
 const h=await FakeChatGPT.start({extensionPath:resolve(variant==='source'?'.':'work/current-release'),headless:true}),p=h.archive;t.after(()=>h.close());
 await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented,'consent');if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 assert.equal(await p.locator('#document-title').textContent(),'');assert.equal(await p.locator('#document-body').textContent(),'');assert.equal(await p.locator('.archive-navigator-window[aria-current]').count(),0);
 await h.open({id:'consumer-synthetic',title:'SYNTHETIC consumer archive',base:1609459200,messages:[{id:'consumer-message',text:'SYNTHETIC 原始长表达：保留输入并在档案中阅读、编辑和复用。'}]},{arrival:'dom-first'});
 await eventually(()=>p.locator('.archive-navigator-group-toggle').count().then(n=>n>0),'navigator groups');
 const groups=p.locator('.archive-navigator-group-toggle');for(let i=0;i<await groups.count();i++)if(await groups.nth(i).getAttribute('aria-expanded')==='false')await groups.nth(i).click();await eventually(()=>windowButton(p).isVisible(),'captured window');
 assert.equal(await p.locator('#onboarding-history-step').isVisible(),false,'root reader has no import onboarding card');const rootGeometry=await p.locator('#archive-reader-navigator-slot').boundingBox();assert.ok(rootGeometry.width>=220&&rootGeometry.width<=280,'root is a narrow directory');
 assert.equal(await p.locator('#document-title').textContent(),'');assert.equal(await p.locator('#document-body').textContent(),'');
 await windowButton(p).click();await eventually(()=>p.locator('.library-prose').isVisible(),'reader opens');const id=await p.locator('.library-prose').first().getAttribute('data-edit-id');
 await p.locator('.library-prose').first().fill('SYNTHETIC 人工编辑保留搜索用的星河词');await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText?.includes('星河词'),'durable edit');
 const input=await rpc(p,'GET_INPUT',{id});const revisionOptions={documentId:input.documentId,entityId:id,kind:'input'};const revisions=await rpc(p,'GET_REVISIONS',{options:revisionOptions});assert.ok(revisions.items?.length>0||revisions.length>0,'edit retains version history');
 await p.reload();await eventually(()=>p.locator('.library-prose').filter({hasText:'星河词'}).isVisible(),'explicit reader route reload restores edited content');
 const after=await rpc(p,'GET_REVISIONS',{options:revisionOptions});assert.deepEqual(after,revisions);
 await p.locator('#back').click();await eventually(async()=>(await p.locator('#document-body').textContent())==='','root clears reading body');assert.equal(await p.locator('#document-title').textContent(),'');await eventually(async()=>await p.locator('.archive-navigator-window[aria-current]').count()===0,'root clears directory selection');assert.equal(await windowButton(p).isVisible(),true,'root preserves directory expansion');
 await p.locator('#scope-search-host input').fill('星河词');await eventually(()=>p.locator('#document-list').getByText('星河词',{exact:false}).count().then(n=>n>0),'local search finds edited input');await p.locator('#scope-search-host input').fill('');await eventually(()=>windowButton(p).isVisible(),'search clear retains directory');
 for(const type of ['PAIA_BACKUP_BEGIN_EXPORT','PAIA_MEMORY_PROFILE','PAIA_CONTEXT_MANUAL','PAIA_PRODUCT_SIGNAL']){const r=await p.evaluate(type=>chrome.runtime.sendMessage({type}),type);assert.equal(r.error,'FEATURE_UNAVAILABLE');}
 const ai=await p.evaluate(()=>chrome.runtime.sendMessage({type:'SAVE_DEEPSEEK_CREDENTIAL',config:{apiKey:'SYNTHETIC'}}));assert.equal(ai.error,'AI_SERVICE_UNAVAILABLE');
 await p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js');const s=new OrganizerStore(chrome.storage.local);await s.finishFoundation();const now=new Date().toISOString();await s.foundationWrite(t=>t.put('meta',{id:'passport:grant:synthetic-legacy',kind:'grant',version:1,grantId:'synthetic-legacy',consumer:'chatgpt',purpose:'general',resourceScope:'profile',profileId:'default',permission:'context_export',duration:'once',createdAt:now,expiresAt:null,revokedAt:null,consumedAt:null,lastUsedAt:null,useCount:0}));});
 await p.locator('.sidebar [data-view="settings"]').click();await eventually(()=>p.locator('#ux-settings-title').isVisible(),'settings');await p.locator('[data-settings-group="privacy"]').click();await p.locator('#memory-clear-session').click();await eventually(async()=>(await rpc(p,'PAIA_PASSPORT_STATUS')).grants.every(x=>x.state==='revoked'),'actual legacy grants revoked');
 assert.equal(await p.locator('#settings-panel a[href*="product-signals"]').count(),0);assert.equal(await p.locator('#product-diagnostics').isVisible(),false);await p.locator('[data-settings-group="ai"]').click();assert.match(await p.locator('#membership-ai-service').textContent(),/尚未上线/);assert.equal(await p.locator('#membership-ai-service button').count(),0);
 const evidence=process.env.PAIA_CONSUMER_EVIDENCE_DIR||'work/consumer-cleanup';await mkdir(evidence,{recursive:true});
 for(const theme of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:theme}});await eventually(()=>p.evaluate(theme=>document.documentElement.dataset.paiaTheme===theme,theme),'real theme');
  for(const width of [1440,768,320]){await p.setViewportSize({width,height:900});await p.screenshot({path:resolve(evidence,variant+'-settings-'+theme+'-'+width+'.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'settings reflow '+width);}
 }
 await p.setViewportSize({width:1440,height:900});await p.locator('#ux-settings-back').click();await eventually(()=>windowButton(p).isVisible(),'return to blank Archive');
 for(const theme of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:theme}});await eventually(()=>p.evaluate(theme=>document.documentElement.dataset.paiaTheme===theme,theme),'theme');for(const width of [1440,768,320]){await p.setViewportSize({width,height:900});await p.screenshot({path:resolve(evidence,variant+'-archive-'+theme+'-'+width+'.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'archive reflow');}}
 const popup=await h.context.newPage();await popup.goto(`chrome-extension://${h.extensionId}/ui/popup.html`);await eventually(()=>popup.locator('#enabled-state').textContent().then(x=>x&&!x.includes('读取')),'popup status');assert.equal(await popup.locator('#popup-internal-tools').count(),0);await popup.setViewportSize({width:320,height:560});
 for(const theme of ['light','dark']){await rpc(popup,'UPDATE_PREFERENCES',{changes:{appearance:theme}});await popup.reload();await eventually(()=>popup.evaluate(theme=>document.documentElement.dataset.paiaTheme===theme,theme),'popup saved theme');await popup.screenshot({path:resolve(evidence,variant+'-popup-'+theme+'-320.png'),fullPage:true});assert.ok(await popup.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));const quiet=await popup.locator('#toggle-capture').boundingBox(),primary=await popup.locator('#open-archive').boundingBox();assert.ok(quiet.height<primary.height,'secondary control is visibly smaller');}await popup.close();
 const favicon=await p.evaluate(async()=>{const url=document.querySelector('link[rel="icon"]').href;const r=await fetch(url);return {url,ok:r.ok,hash:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await r.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('')};});assert.match(favicon.url,/icons\/icon32.png$/);assert.equal(favicon.ok,true);assert.equal(favicon.hash,'6e487abdab45de5f5dbec02f2a05098797616e949c409c93082a4e0488194065','actual tab resource matches main new favicon');assert.equal(h.extensionNetworkRequests,0);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);
});
