import test from 'node:test';import assert from 'node:assert/strict';
import {assemble,rankCandidate,compareCandidates,semanticState,contextExcerpt,contextWarnings} from '../core/memory/retrieval.js';
import {contextBenchmark} from './fixtures/context-benchmark-v0101.mjs';
const e=(id,body,extra={})=>({id,entryId:id,topicId:'topic',topicName:'长期计划',sectionTitle:'计划',title:'',body,kind:'entry',type:'decision',human:false,current:true,fresh:true,pinned:false,confidence:1,time:'2026-09-01T00:00:00Z',sequence:1,evidenceEntryIds:[id],sourceLabel:'Thought Library',...extra});
test('Relevance before trust/time: direct Entry remains eligible outside Topic match, no unrelated pinned result',()=>{const data=[e('direct','地铁通勤路线与雨天换乘'),e('other','完全无关的烹饪记录',{human:true,pinned:true,time:'2030-01-01T00:00:00Z'}),e('topic','周末散步',{topicName:'地铁'})],p=assemble(data,{query:'地铁通勤路线'});assert.equal(p.items[0].id,'direct');assert.ok(!p.items.some(x=>x.id==='other'));assert.ok(p.items.every(x=>!('score'in x)));});
test('Currentness is explicit wording, never fresh/newer/human; quoted past and questions stay uncertain',()=>{for(const body of ['我认为先做产品经理。','今天写：以前我认为应该先做产品经理。','如果我现在决定做产品经理会怎样？','他说：“现在决定做产品经理。”','现在决定做产品经理吗？'])assert.equal(semanticState(e('a',body,{human:true,time:'2099-01-01T00:00:00Z'})),'uncertain');assert.equal(semanticState(e('a','以前我认为应该先做产品经理。')),'historical');assert.equal(semanticState(e('a','现在决定先做工程师。')),'current');assert.equal(semanticState(e('a','不再考虑产品经理岗位。')),'current');assert.equal(semanticState(e('a','现在决定先做工程师。',{fresh:false})),'uncertain');});
test('Conflicting expressions preserve time and uncertainty; reliable explicit present precedes equally relevant history',()=>{const p=assemble([e('old','以前选择工程师路线。',{time:'2026-09-09T00:00:00Z'}),e('now','现在选择工程师路线。',{time:'2026-01-01T00:00:00Z'})],{query:'工程师路线'});assert.equal(p.items[0].id,'now');assert.equal(p.items.find(i=>i.id==='old').state,'historical');assert.equal(p.items.find(i=>i.id==='now').state,'current');const q=assemble([e('a','工程师路线适合我。'),e('b','工程师路线不适合我。',{time:'2026-09-09T00:00:00Z'})],{query:'工程师路线'});assert.ok(q.items.every(i=>i.state==='uncertain'));assert.match(q.text,/当前状态未完全确认/);assert.deepEqual(contextWarnings(q.items.slice(0,1)),[]);});
test('Exact duplication consolidates evidence, preserves distinct conditions, negation and dated stages',()=>{const p=assemble([e('a','预算足够时选择方案甲。',{human:true}),e('dup','预算足够时选择方案甲。'),e('condition','预算不足时选择方案甲。'),e('not','预算足够时不选择方案甲。'),e('dated','预算足够时选择方案甲。',{time:'2020-01-01T00:00:00Z'})],{query:'方案甲',budget:'detailed'});assert.equal(p.items.length,4);assert.deepEqual(p.items.find(i=>i.id==='a').evidenceEntryIds,['a','dup']);assert.ok(p.items.some(i=>i.id==='condition'));assert.ok(p.items.some(i=>i.id==='not'));assert.ok(p.items.some(i=>i.id==='dated'));});
test('Original Unicode excerpts preserve rare tail matches under all budgets and never exceed item cap',()=>{const body='㍿😀普通前言'.repeat(800)+'精确匹配TAIL_MARKER最后证据'+'尾声'.repeat(800);for(const cap of [450,900,1600]){const excerpt=contextExcerpt(body,'TAIL_MARKER',cap);assert.match(excerpt,/TAIL_MARKER/);assert.ok([...excerpt].length<=cap);assert.doesNotMatch(excerpt,/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/);}});
test('Fixed 60/1200/240 corpus quality has no excluded items, budget overflow or incomplete provenance',()=>{const data=contextBenchmark();assert.equal(data.entries.length,1200);assert.equal(data.queries.length,240);for(const query of data.queries){const p=assemble(data.entries.filter(e=>e.eligible),{query:query.query});assert.ok(p.characters<=p.limits.characters&&p.tokens<=p.limits.tokens);assert.ok(p.items.every(e=>e.eligible&&e.entryId&&e.topicId&&e.time&&e.evidenceEntryIds.length));assert.ok(p.items.every(e=>e.state!=='current'),'freshness in fixture cannot mean Current');}assert.deepEqual(assemble(data.entries,{query:'ZZZZ_UNMATCHED_QUERY'}).items,[]);});

test('Section conditions survive composition; cropped long records never merge and human duplicates own provenance',()=>{const p=assemble([e('rain','选择地铁。',{sectionTitle:'雨天'}),e('sun','选择地铁。',{sectionTitle:'晴天'})],{query:'地铁'});assert.equal(p.items.length,2);const titles=assemble([e('one','选择地铁。',{title:'雨天'}),e('two','选择地铁。',{title:'晴天'})],{query:'地铁'});assert.equal(titles.items.length,2);assert.match(titles.text,/条目：雨天/);assert.match(titles.text,/条目：晴天/);assert.match(p.text,/章节：雨天/);assert.match(p.text,/章节：晴天/);const cropped=assemble([e('a','共同的选中窗口。',{excerpted:true}),e('b','共同的选中窗口。',{excerpted:true})],{query:'窗口'});assert.equal(cropped.items.length,2);const duplicate=assemble([e('faithful','共同内容',{title:'共同内容',relatedScore:400,sourceLabel:'来源依据'}),e('human','共同内容',{title:'共同内容',human:true,sourceLabel:'用户编辑'})],{query:'共同内容'});assert.equal(duplicate.items.length,1);assert.equal(duplicate.items[0].id,'human');assert.equal(duplicate.items[0].sourceLabel,'用户编辑');assert.deepEqual(new Set(duplicate.items[0].evidenceEntryIds),new Set(['faithful','human']));});
