import {assertRetiredContext,retainedContextFixture} from './harness/retired-context.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {setup,local} from './harness/thought-m1.mjs';import {OrganizerStore} from '../core/organizer/store.js';import {MemoryService} from '../core/memory/service.js';import {configDefault,validateMemoryRow} from '../core/memory/model.js';import {BackupService} from './harness/historical-backup.mjs';import {exported,prepared} from './harness/backup-v081.mjs';import {assertLocalNetworkAllowed} from '../core/local-network-policy.js';
async function fixture(){const f=await retainedContextFixture();return {...f,m:f.memory,entry:f.entry};}
test("Current retirement / historical scenario: External off blocks connection access but keeps explicit local copy/Markdown, scope and Backup intact",async()=>{
 await assertRetiredContext({"owner": "memory", "method": "build", "action": "create", "variant": "local-only"});
});
test('v0100 missing optional switch migration is atomic/idempotent and cannot silently grant external access',async()=>{const {s,m}=await fixture();await m.settings({externalAccess:false});const old=await s.repository.transaction(false,t=>t.get('meta','memory:config'));delete old.externalAccess;assert.equal(validateMemoryRow(old),true);await s.repository.transaction(true,t=>t.put('meta',old));const original=s.repository.transaction.bind(s.repository);let crash=true;s.repository.transaction=(write,fn,stores)=>original(write,t=>{const put=t.put.bind(t);t.put=(n,r)=>{if(crash&&r.id==='memory:config')throw Error('synthetic crash');return put(n,r);};return fn(t);},stores);await assert.rejects(m.status(),{code:'STORAGE_FAILED'});assert.deepEqual(await original(false,t=>t.get('meta','memory:config')),old);crash=false;const first=await m.status(),again=await new MemoryService(s,{session:m.session}).status();assert.equal(first.config.externalAccess,false);assert.deepEqual(first,again);assert.equal(first.allowed,1);assert.equal(s.repository.db.version,5);await new MemoryService(s).ready();assert.equal((await m.status()).config.externalAccess,false);});
test('Switch false survives fresh backup restore, rejects malformed value and cannot loosen exclusions',async()=>{const {s,m,entry}=await fixture();await m.exclude({entryId:entry.id,excluded:true});await m.settings({externalAccess:false});for(const externalAccess of [null,1,'true',{}]){assert.equal(validateMemoryRow({...configDefault(),externalAccess}),false);await assert.rejects(m.settings({externalAccess}),{code:'MEMORY_INVALID'});}const rows=await exported(new BackupService(s,{appVersion:'0.10.1'})),{IDBFactory}=await import('./vendor/fake-indexeddb/build/esm/index.js'),empty=new OrganizerStore(local(),{indexedDB:new IDBFactory()});await empty.consent(true);await empty.finishFoundation();const b=new BackupService(empty,{appVersion:'0.10.1'}),staged=await prepared(b,rows);await b.restore({sessionId:staged.sessionId,confirmation:staged.preview.integrity});const next=new MemoryService(empty);assert.equal((await next.status()).config.externalAccess,false);await assert.rejects(next.settings({externalAccess:true}),{code:'FEATURE_UNAVAILABLE'});await assert.rejects(next.build({query:'Context'}),{code:'FEATURE_UNAVAILABLE'});assert.equal((await next.status()).excluded,1);});

test("Current retirement / historical scenario: Long Thought candidates remain bounded while relevant tail survives small context budget",async()=>{
 await assertRetiredContext({"owner": "memory", "method": "candidates", "action": "create", "variant": "allowed", "long": true});
});