import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(m=>chrome.runtime.sendMessage(m),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const read=p=>rpc(p,'PAIA_CONTEXT_CARDS_SNAPSHOT');
const capture=async(p,path)=>{await p.mouse.move(1,1);await p.waitForFunction(()=>document.querySelector('.sidebar [data-view="memory"]')?.getAttribute('aria-current')==='page'&&[...document.querySelectorAll('#memory-panel .context-access')].every(x=>!x.disabled));await p.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{})));});assert.equal(await p.locator('.workspace').evaluate(el=>getComputedStyle(el).paddingBottom),p.viewportSize().width<768?'48px':'64px','production Context retains the approved shell bottom inset');await p.screenshot({path,fullPage:true});};
const field=p=>p.locator('#memory-panel .item-text').first();
const protectedSnapshot=p=>p.evaluate(async()=>{const req=indexedDB.open('paia-archive');const db=await new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=reject;});const names=['records','blocks','thoughts','topics','inputStates','tombstones','revisions','provenance'],tx=db.transaction(names);const result=Object.fromEntries(await Promise.all(names.map(async name=>[name,await new Promise((resolve,reject)=>{const r=tx.objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=reject;})])));db.close();return result;});
async function failCommits(h){const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));await worker.evaluate(()=>{const put=IDBObjectStore.prototype.put;globalThis.__ctx4Restore=()=>{IDBObjectStore.prototype.put=put;};IDBObjectStore.prototype.put=function(row,...args){if(this.name==='operationReceipts'&&row.namespace==='context-cards')throw new DOMException('Synthetic Context write failure','UnknownError');return put.call(this,row,...args);};});return ()=>worker.evaluate(()=>globalThis.__ctx4Restore());}
for(const variant of ['source','release'])test('CTX4 real four-card durable edit/delete/undo, failure, IME, concurrency and shell '+variant,{timeout:180000},async t=>{
 if(variant==='release')execFileSync('python3',['scripts/build_current_release.py'],{stdio:'pipe'});
 const h=await FakeChatGPT.start({extensionPath:resolve(variant==='release'?'work/current-release':'.'),headless:true}),p=h.archive;
 t.after(async()=>{try{const evidenceDir=`work/ctx4-01/${variant}`;await mkdir(evidenceDir,{recursive:true});await p.screenshot({path:`${evidenceDir}/last-state.png`,fullPage:true});await writeFile(`${evidenceDir}/last-state.json`,JSON.stringify(await p.evaluate(()=>({route:history.state,space:document.body.dataset.paiaSpace,headings:[...document.querySelectorAll('#memory-panel h1')].map(x=>x.textContent),items:document.querySelectorAll('#memory-panel .item-text').length,fields:[...document.querySelectorAll('#memory-panel .item-text')].map(el=>({textContent:el.textContent,innerText:el.innerText,html:el.innerHTML,inert:!!el.closest('[inert]')})),navigation:[...document.querySelectorAll('.sidebar [data-view]')].map(x=>({view:x.dataset.view,current:x.getAttribute('aria-current'),background:getComputedStyle(x).backgroundColor,color:getComputedStyle(x).color})),text:document.getElementById('memory-panel').innerText})),null,2));}catch{}await h.close();});
 await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented,'consent');if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 await h.open({id:'ctx4-synthetic',title:'SYNTHETIC Context invariants',base:1609459200,messages:[{id:'ctx4-input-001',text:'SYNTHETIC Source is immutable and independent.'}]},{arrival:'dom-first'});await eventually(async()=>(await rpc(p,'GET_STATE')).records.length===1,'source capture');
 const working=(await rpc(p,'GET_STATE')).library.blocks[0];await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:working.documentId,blocks:[{id:working.id,expectedRevision:working.revision,libraryText:'SYNTHETIC preexisting user-edited Working Input',note:'SYNTHETIC existing note',excluded:false}]}});
 const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC protected Topic',operationId:crypto.randomUUID()}});await rpc(p,'CONTINUE_THINKING',{thought:{topicId:topic.id,body:'SYNTHETIC preexisting independent human Thought',operationId:crypto.randomUUID()}});
 // Settle the real derived-index owner before the exact no-write oracle. Do not
 // strip its fields or disable its background work to make this comparison pass.
 await eventually(async()=>{const index=await rpc(p,'SEARCH_LIBRARY',{options:{query:'SYNTHETIC protected Topic',limit:40}});return index.complete&&index.items.some(x=>x.topicId===topic.id);},'existing library search work finishes before the protected baseline');
 await eventually(async()=>{const filter=await rpc(p,'FILTER_STATUS');return filter.pending===0&&filter.taskState==='idle';},'capture/filter work finishes before the protected baseline');const original=await protectedSnapshot(p);assert.ok(original.thoughts.length>0);assert.equal(original.blocks[0].value.libraryText,'SYNTHETIC preexisting user-edited Working Input');
 await p.locator('.sidebar [data-view="memory"]').click();await p.locator('.context-card').first().waitFor();assert.equal(await p.locator('.context-card').count(),4);assert.equal(await p.locator('.sidebar [data-view="memory"]').getAttribute('aria-current'),'page');assert.equal(await p.locator('.sidebar [data-view="library"]').getAttribute('aria-current'),'false');assert.ok(Object.values((await read(p)).access).every(x=>!x.enabled));
 const dir=`work/ctx4-01/${variant}`;await mkdir(dir,{recursive:true});await capture(p,`${dir}/15-empty.png`);
 await p.locator('.context-card[data-card="info"] .context-access').click();await eventually(async()=>(await read(p)).access.info.enabled,'card setting commits');assert.equal((await read(p)).access.global.enabled,false);assert.equal(await p.locator('.context-card').count(),4,'capsule never navigates');assert.equal(await p.locator('.context-card[data-card="info"] .context-access').getAttribute('data-paused'),'true');
 for(const card of ['rules','now','inputs']){await p.locator(`.context-card[data-card="${card}"] .context-access`).click();await eventually(async()=>(await read(p)).access[card].enabled);}await p.locator('.context-access.global').click();await eventually(async()=>(await read(p)).access.global.enabled);await capture(p,`${dir}/01-home.png`);await p.locator('.context-access.global').click();await eventually(async()=>!(await read(p)).access.global.enabled);await capture(p,`${dir}/03-global-off.png`);await p.locator('.context-access.global').click();await eventually(async()=>(await read(p)).access.global.enabled,'Info visual states use the approved global-on setting');
 await p.locator('.context-card[data-card="info"] .card-link').click();await p.locator('.add-item').click();await field(p).fill('SYNTHETIC erased before first commit');await eventually(async()=>(await rpc(p,'PAIA_CONTEXT_CARDS_DRAFTS')).length===1,'new draft protected');await field(p).fill('');await eventually(async()=>(await rpc(p,'PAIA_CONTEXT_CARDS_DRAFTS')).length===0,'erased draft cleared');await p.locator('.context-back').click();await p.locator('.context-card[data-card="info"] .card-link').click();assert.equal(await p.locator('.item-text').count(),0,'erased new item never resurrects');await p.locator('.add-item').click();await field(p).fill('SYNTHETIC 第一条独立信息。');await field(p).press('Control+Enter');await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC 第一条独立信息。','real first commit');await eventually(()=>p.locator('.item-feedback').first().textContent().then(x=>x==='已保存'));
 const id=(await read(p)).items[0].id;await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await p.evaluate(()=>history.back());await field(p).waitFor();assert.equal(await field(p).innerText(),'SYNTHETIC 第一条独立信息。','browser Back restores information detail');await p.evaluate(()=>history.forward());await p.locator('.context-card').first().waitFor();await p.locator('.context-card[data-card="info"] .card-link').click();await field(p).waitFor();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&history.state.paiaReader.contextCard==='info');await p.reload();const persistedAfterReload=await read(p);assert.equal(persistedAfterReload.items[0]?.id,id,'reload retains the durable item before any route assertion');assert.equal(persistedAfterReload.items[0]?.body,'SYNTHETIC 第一条独立信息。');await field(p).waitFor();assert.equal(await field(p).innerText(),'SYNTHETIC 第一条独立信息。');await eventually(()=>p.locator('.context-head h1').evaluate(el=>el===document.activeElement&&getComputedStyle(el).outlineStyle==='none'),'route heading retains semantic focus without an interactive outline');await h.restartWorker();assert.equal((await read(p)).items[0].id,id);assert.equal((await read(p)).access.info.enabled,true);
 // Hold the real outer navigation read. Accepted leave must make the outgoing
 // editor inert before an actual late pointer/keyboard attempt, including failure.
 for(const outcome of ['success','failure']){
  const savedBody=await field(p).innerText();
  await p.evaluate(outcome=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);let release;const held=new Promise(resolve=>{release=resolve;});window.__ctxNavEntered=false;window.__ctxNavRelease=()=>{chrome.runtime.sendMessage=send;release();};let armed=true;chrome.runtime.sendMessage=(message,...args)=>{if(armed&&message.type==='GET_PAGE'&&message.page?.view==='settings'){armed=false;window.__ctxNavEntered=true;return held.then(()=>outcome==='failure'?{ok:false,error:'STORAGE_FAILED'}:send(message,...args));}return send(message,...args);};},outcome);
  const target=await field(p).boundingBox();await p.locator('.context-back').click();await p.waitForFunction(()=>window.__ctxNavEntered);
  assert.equal(await p.locator('.context-page').evaluate(el=>el.inert),true,'outgoing Info is locked while outer GET_PAGE is unresolved');
  await p.mouse.click(target.x+20,target.y+15);await p.keyboard.type('LATE_TEXT_MUST_NOT_ENTER');
  assert.equal(await field(p).innerText(),savedBody);assert.equal((await read(p)).items[0].body,savedBody);
  await p.evaluate(()=>window.__ctxNavRelease());
  if(outcome==='failure'){await p.locator('.context-load-failed').waitFor();assert.equal(await p.locator('.item-text').count(),0,'failed Home route cannot expose outgoing Info');await p.locator('.context-load-failed').getByRole('button',{name:'重试',exact:true}).click();}
  await p.locator('.context-card').first().waitFor();assert.equal(await p.locator('.context-page').evaluate(el=>el.inert),false);
  await p.locator('.context-card[data-card="info"] .card-link').click();await field(p).waitFor();assert.equal(await field(p).innerText(),savedBody);
 }
 await field(p).fill('SYNTHETIC 第二次修改，保留稳定身份。');await field(p).press('Control+Enter');await eventually(async()=>(await read(p)).items[0]?.body.includes('第二次修改'));await capture(p,`${dir}/05-editing.png`);
 await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''})));await field(p).evaluate(el=>{el.textContent='SYNTHETIC 中文组合输入';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText',data:'中文'}));});await pause(1000);assert.match((await read(p)).items[0].body,/第二次修改/,'IME intermediate body is never committed');await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文'})));await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC 中文组合输入');
 const restore=await failCommits(h);await field(p).fill('SYNTHETIC 写入失败仍保留的草稿');await field(p).press('Control+Enter');await eventually(()=>p.locator('.item-feedback.error').isVisible(),'failed transaction retains draft');assert.equal((await read(p)).items[0].body,'SYNTHETIC 中文组合输入');await capture(p,`${dir}/16-save-failed.png`);await p.locator('.context-back').click();assert.equal(await field(p).innerText(),'SYNTHETIC 写入失败仍保留的草稿','leave guard retains failed edit');
 await restore();await p.locator('.item-feedback').getByRole('button',{name:'重试',exact:true}).click();await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC 写入失败仍保留的草稿');
 // A genuine independent page uses the same worker/revision owner.
 const second=await h.context.newPage();await second.goto(p.url());const snapshot=await read(second),item=snapshot.items[0];await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await field(p).evaluate(el=>{el.textContent='SYNTHETIC protected conflicting draft';});await rpc(second,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',operationId:crypto.randomUUID(),epoch:snapshot.epoch,itemId:id,expectedRevision:item.revision,body:'SYNTHETIC concurrent saved body',section:item.section}});await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await field(p).press('Control+Enter');await eventually(()=>p.locator('.item-feedback.error').isVisible(),'concurrent conflict');assert.equal(await field(p).innerText(),'SYNTHETIC protected conflicting draft');assert.equal((await read(p)).items[0].body,'SYNTHETIC concurrent saved body');p.once('dialog',d=>d.accept());const viewSaved=p.locator('.item-feedback').getByRole('button',{name:'查看已保存内容'});if(variant==='release'){await field(p).focus();await p.keyboard.press('Tab');await p.keyboard.press('Tab');await p.keyboard.press('Tab');assert.equal(await viewSaved.evaluate(el=>document.activeElement===el),true,'native Tab reaches conflict recovery action');await p.keyboard.press('Enter');}else await viewSaved.click();await eventually(()=>field(p).innerText().then(x=>x==='SYNTHETIC concurrent saved body'));await second.close();
 await field(p).hover();await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'删除',exact:true}).click();await eventually(async()=>(await read(p)).items.length===0,'real delete');await p.locator('.context-notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC concurrent saved body','real undo restores exact body');assert.equal((await read(p)).items[0].id,id);await p.reload();await eventually(()=>field(p).innerText().then(x=>x==='SYNTHETIC concurrent saved body'));await capture(p,`${dir}/04-info-journey.png`);
 assert.deepEqual(await protectedSnapshot(p),original,'Context edits never mutate Source/Input/Thought data');for(const type of ['PAIA_CONTEXT_MANUAL','PAIA_CONTEXT_BIND','PAIA_MEMORY_BUILD','PAIA_MEMORY_SHARE','PAIA_BACKUP_BEGIN_EXPORT'])assert.equal((await p.evaluate(type=>chrome.runtime.sendMessage({type}),type)).error,'FEATURE_UNAVAILABLE');assert.equal((await p.evaluate(()=>chrome.runtime.sendMessage({type:'SAVE_DEEPSEEK_CREDENTIAL'}))).error,'AI_SERVICE_UNAVAILABLE');
 for(const text of ['合成信息二：检查中间条目的撤销位置。','合成信息三：保持末尾条目的原有顺序。']){await p.locator('.add-item').click();await p.locator('.item-text').last().fill(text);await p.locator('.item-text').last().press('Control+Enter');await eventually(async()=>(await read(p)).items.some(x=>x.body===text));}
 const ordered=(await read(p)).items.map(x=>x.id),middle=p.locator(`[data-item="${ordered[1]}"]`);await middle.locator('.item-text').hover();await middle.locator('.item-menu summary').click();await middle.getByRole('button',{name:'删除',exact:true}).click();await eventually(async()=>(await read(p)).items.length===2);await p.locator('.context-notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(()=>p.locator('.context-item').count().then(n=>n===3));assert.deepEqual(await p.locator('.context-item').evaluateAll(nodes=>nodes.map(n=>n.dataset.item)),ordered,'middle-item Undo restores its canonical place without reload');
 const visual=await read(p);for(let i=0;i<5;i++)await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',operationId:crypto.randomUUID(),epoch:visual.epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`合成信息 ${i+1}：用于核对独立资料的阅读、编辑与保存。`,section:i<3?'语言与习惯':'长期领域'}});await eventually(()=>p.locator('.item-text').count().then(n=>n===8));await capture(p,`${dir}/04-info-eight-items.png`);
 // Preserve the focused Undo evidence above, then capture a genuinely resting
 // eight-item detail through the normal navigation owner, without CSS overrides.
 const restingItems=(await read(p)).items;
 await p.locator('.context-back').click();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&!history.state.paiaReader.contextCard);await p.locator('.context-card[data-card="info"] .card-link').click();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&history.state.paiaReader.contextCard==='info'&&document.querySelector('.context-head h1')===document.activeElement);
 assert.equal(await p.locator('.item-text').count(),8);assert.deepEqual((await read(p)).items,restingItems,'resting visual reentry preserves all confirmed items');await capture(p,`${dir}/04-info-resting.png`);
 await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await field(p).waitFor();assert.equal(await p.locator('.item-text').count(),8,'Settings returns to the same Context detail');
 await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'dark'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='dark'));await capture(p,`${dir}/13-dark.png`);await p.setViewportSize({width:390,height:844});await capture(p,`${dir}/12-compact-dark.png`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'light'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='light'));await capture(p,`${dir}/12-compact.png`);await p.locator('.context-card[data-card="info"] .card-link').click();await field(p).waitFor();await capture(p,`${dir}/19-compact-info.png`);await p.setViewportSize({width:320,height:740});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await field(p).focus();await field(p).press('Tab');assert.equal(await p.locator('.item-menu summary').first().evaluate(el=>el===document.activeElement),true);await p.keyboard.press('Enter');await p.keyboard.press('Escape');assert.equal(await p.locator('.item-menu').first().getAttribute('open'),null);
 assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);await writeFile(`${dir}/evidence.json`,JSON.stringify({variant,sourceInputThoughtUnchanged:true,workerRestart:true,commitReloadEditDeleteUndo:true,syntheticIme:true,physicalIme:'NOT_VERIFIED',saveFailure:true,concurrency:true,externalConnections:false,screenshots:'synthetic production extension',network:h.extensionNetworkRequests},null,2));
});

for(const variant of ['source','release'])test('CTX4-02 all local cards, isolated recovery, access and page return '+variant,{timeout:180000},async t=>{
 if(variant==='release')execFileSync('python3',['scripts/build_current_release.py'],{stdio:'pipe'});
 const h=await FakeChatGPT.start({extensionPath:resolve(variant==='release'?'work/current-release':'.'),headless:true}),p=h.archive;
 const dir=`work/ctx4-01/${variant}/ctx4-02`;await mkdir(dir,{recursive:true});
 // Keep the case budget unchanged; an individual hung action must produce its
 // own failing stack and current phase rather than consuming the whole case.
 p.setDefaultTimeout(14000);const started=Date.now(),phases=[];
 const phase=async label=>{const entry={label,elapsedMs:Date.now()-started};phases.push(entry);console.info('CTX4-02 '+variant+' '+JSON.stringify(entry));await writeFile(`${dir}/phases.json`,JSON.stringify(phases,null,2));};
 t.after(async()=>{try{await writeFile(`${dir}/last-state.json`,JSON.stringify(await p.evaluate(()=>({route:history.state,space:document.body.dataset.paiaSpace,workspace:document.querySelector('.workspace')?.dataset.state,scrollY,inert:document.querySelector('.context-page')?.inert,heading:document.querySelector('#memory-panel h1')?.textContent,active:document.activeElement?.outerHTML,transitionHeld:globalThis.__ctx402Transition?.held,fields:[...document.querySelectorAll('#memory-panel .item-text')].map(el=>({textContent:el.textContent,innerText:el.innerText,html:el.innerHTML})),notice:document.querySelector('.context-notice')?.innerText})),null,2));await p.screenshot({path:`${dir}/last-state.png`,fullPage:true});}catch{}await h.close();});
 await phase('setup');
 await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 await h.open({id:'ctx4-02-synthetic',title:'SYNTHETIC three-card preserved owners',base:1609459200,messages:[{id:'ctx4-02-input',text:'SYNTHETIC Source remains independent of all three Context cards.'}]},{arrival:'dom-first'});await eventually(async()=>(await rpc(p,'GET_STATE')).records.length===1);
 const working=(await rpc(p,'GET_STATE')).library.blocks[0];await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:working.documentId,blocks:[{id:working.id,expectedRevision:working.revision,libraryText:'SYNTHETIC protected Working Input for all three cards',note:'SYNTHETIC protected note',excluded:false}]}});
 const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC CTX4-02 preserved Topic',operationId:crypto.randomUUID()}});await rpc(p,'CONTINUE_THINKING',{thought:{topicId:topic.id,body:'SYNTHETIC existing independent human Thought for three-card checks',operationId:crypto.randomUUID()}});
 await eventually(async()=>{const index=await rpc(p,'SEARCH_LIBRARY',{options:{query:'SYNTHETIC CTX4-02 preserved Topic',limit:40}});return index.complete&&index.items.some(item=>item.topicId===topic.id);});await eventually(async()=>{const status=await rpc(p,'FILTER_STATUS');return status.pending===0&&status.taskState==='idle';});
 // Source capture opened another tab. Exercise native editing in the actual
 // foreground page rather than waiting through background animation throttling.
 await p.bringToFront();assert.equal(await p.evaluate(()=>document.visibilityState),'visible');
 await p.locator('.sidebar [data-view="memory"]').click();await p.locator('.context-card').first().waitFor();const before=await protectedSnapshot(p),ids={};
 const settled=card=>p.waitForFunction(card=>document.body.dataset.paiaSpace==='memory'&&history.state?.paiaReader?.view==='memory'&&(history.state.paiaReader.contextCard??null)===card&&document.querySelector('.workspace')?.dataset.state==='ready'&&document.querySelector('.context-page')?.inert===false,card);
 const open=async card=>{await phase('open '+card);await p.locator(`.context-card[data-card="${card}"] .card-link`).click();await p.locator('.add-item').waitFor();await settled(card);await phase('opened '+card);};
 const home=async()=>{await phase('home click');await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await settled(null);await phase('home ready');};
 const items=async card=>(await read(p)).items.filter(x=>x.card===card);
 await phase('three-card creation');
 for(const card of ['info','rules','now']){
  await open(card);assert.equal(await p.locator('.item-text').count(),0);await p.locator('.add-item').click();const text=`SYNTHETIC ${card} natural-language item`;
  await field(p).fill(text);await field(p).press('Enter');await p.keyboard.insertText('Second line');await field(p).press('Control+Enter');await eventually(async()=>(await items(card))[0]?.body===text+'\nSecond line','Enter retains a real newline and shortcut commits '+card);
  ids[card]=(await items(card))[0].id;assert.equal(await p.locator('.item-text').count(),1);await home();assert.equal(await p.locator(`[data-count="${card}"]`).textContent(),'1 项');
 }
 assert.deepEqual((await read(p)).counts,{info:1,rules:1,now:1,inputs:0});
 await phase('editing undo deletion IME failure');
 for(const card of ['rules','now']){
  await open(card);await field(p).fill(`SYNTHETIC ${card} manual edit`);await field(p).press('Control+Enter');await eventually(async()=>(await items(card))[0]?.body.endsWith('manual edit'));
  await field(p).hover();await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'查看依据',exact:true}).click();assert.match(await p.locator('.item-evidence').textContent(),/由你添加/);
  await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'撤销上次修改',exact:true}).click();await eventually(async()=>(await items(card))[0]?.body.includes('Second line'),'saved undo stays in '+card);
  await field(p).hover();await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'删除',exact:true}).click();await eventually(async()=>(await items(card)).length===0);await eventually(()=>p.locator('.item-text').count().then(n=>n===0));
  await p.locator('.context-notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(async()=>(await items(card))[0]?.id===ids[card]);await field(p).waitFor();assert.equal(await p.locator('.item-text').count(),1);
  // No cross-card update may remount the focused editor or expose another body.
  await field(p).focus();const opposite=card==='rules'?'now':'rules',other=(await items(opposite))[0];await field(p).evaluate(el=>{el.dataset.nativeIdentity='retained';el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.textContent='SYNTHETIC 正在组合 '+el.getAttribute('aria-label');});
  const snap=await read(p);await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',card:opposite,operationId:crypto.randomUUID(),epoch:snap.epoch,itemId:other.id,expectedRevision:other.revision,section:other.section,body:other.body+' [other card]'}});await pause(850);
  assert.equal(await p.locator('.item-text').count(),1);assert.equal(await field(p).getAttribute('data-native-identity'),'retained');assert.equal(await field(p).evaluate(el=>el===document.activeElement),true);assert.equal((await items(card))[0].body.includes('正在组合'),false);
  await field(p).press('Control+Enter');assert.equal((await items(card))[0].body.includes('正在组合'),false,'shortcut does not commit IME');await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await field(p).press('Control+Enter');await eventually(async()=>(await items(card))[0]?.body.includes('正在组合'));
  const restore=await failCommits(h);await field(p).fill(`SYNTHETIC ${card} failed draft`);await field(p).press('Control+Enter');await eventually(()=>p.locator('.item-feedback.error').isVisible());await p.locator('.context-back').click();assert.equal(await field(p).innerText(),`SYNTHETIC ${card} failed draft`);await restore();await p.locator('.item-feedback').getByRole('button',{name:'重试',exact:true}).click();await eventually(async()=>(await items(card))[0]?.body===`SYNTHETIC ${card} failed draft`);await home();
 }
 // Persist actual source-free draft envelopes through the worker; the UI must
 // recover only its own card, including old omitted-card Info payloads.
 await phase('recovery');
 const epoch=(await read(p)).epoch,drafts=[];for(const card of ['info','rules','now']){const change={kind:'put',operationId:crypto.randomUUID(),epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`SYNTHETIC recovered ${card}`,section:'SYNTHETIC recovered group',...(card==='info'?{}:{card})};drafts.push(change);await rpc(p,'PAIA_RECOVERY_DRAFT_SAVE',{draft:{kind:'context_item',ownerId:change.itemId,epoch,token:change.operationId,sourceRecordIds:[],operation:{type:'PAIA_CONTEXT_CARDS_CHANGE',change}}});}
 for(const card of ['info','rules','now']){await open(card);await eventually(()=>p.locator('.item-text').count().then(n=>n===2));const recovered=p.locator('.item-text').filter({hasText:`SYNTHETIC recovered ${card}`});assert.equal(await recovered.count(),1);assert.equal(await p.locator('.item-text').filter({hasText:'SYNTHETIC recovered'}).count(),1);await recovered.press('Control+Enter');await eventually(async()=>(await items(card)).length===2);await home();}
 for(const card of ['info','rules','now']){await p.locator(`.context-card[data-card="${card}"] .context-access`).click();await eventually(async()=>(await read(p)).access[card].enabled);await eventually(()=>p.locator(`.context-card[data-card="${card}"] .context-access`).getAttribute('data-paused').then(value=>value==='true')); }
 await phase('access and connections');
 await capture(p,`${dir}/03-all-local-paused.png`);await p.locator('.context-access.global').click();await eventually(async()=>(await read(p)).access.global.enabled);await capture(p,`${dir}/01-local-home.png`);
 await p.locator('.context-card[data-card="rules"] .context-access').click();await eventually(async()=>!(await read(p)).access.rules.enabled);assert.equal((await read(p)).access.info.enabled,true);assert.equal((await read(p)).access.now.enabled,true);assert.deepEqual((await read(p)).counts,{info:2,rules:2,now:2,inputs:0});
 await p.locator('.connections-link').click();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));assert.equal(await p.locator('#memory-panel .context-access').count(),0);assert.match(await p.locator('#memory-panel').innerText(),/外部连接目前不可用/);await capture(p,`${dir}/connections-empty.png`);
 await p.waitForFunction(()=>history.state?.paiaReader?.contextCard==='connections');await p.reload();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));await home();await p.goBack();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));await p.goForward();await p.locator('.context-card').first().waitFor();
 // Long, real persisted card content exercises the existing per-page scroll
 // owner, groups, dark/narrow layouts and retained reading preferences.
 await phase('visual and long fixtures');
 const groups={rules:['回答方式','表达偏好','工作方式'],now:['当前项目','阶段重点','最近关注']},visualSections={rules:[0,0,0,1,1,2,2],now:[0,0,1,2]};
 await p.locator('.context-card[data-card="rules"] .context-access').click();await eventually(async()=>(await read(p)).access.rules.enabled);
 for(const card of ['rules','now']){
  for(const item of await items(card))await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'delete',operationId:crypto.randomUUID(),epoch,itemId:item.id,expectedRevision:item.revision}});
  for(const [i,section]of visualSections[card].entries())await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',card,operationId:crypto.randomUUID(),epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`合成${card==='rules'?'规则':'状态'} ${i+1}：保留完整表达，说明重点与适用条件。`,section:groups[card][section]}});
  await open(card);await capture(p,`${dir}/${card==='rules'?'06-rules-seven':'07-now-four'}.png`);await home();
  for(let i=visualSections[card].length;i<16;i++)await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',card,operationId:crypto.randomUUID(),epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`SYNTHETIC ${card} ${i+1}：保留自然语言、多行内容与当前人工修改。\n第二行验证完整正文。`,section:groups[card][i%3]}});
 }

 await phase('scroll and history');
 for(const card of ['rules','now']){await open(card);await eventually(()=>p.locator('.item-text').count().then(n=>n===16));await p.evaluate(()=>window.scrollTo(0,460));await eventually(()=>p.evaluate(()=>scrollY>=450),'settled Context page reaches the unchanged 460px scroll target');const at=await p.evaluate(()=>scrollY);assert.ok(at>=450);await p.goBack();await p.locator('.context-card').first().waitFor();await settled(null);assert.ok(await p.evaluate(()=>scrollY)<30,'home retains its own anchor');await p.goForward();await p.locator('.add-item').waitFor();await settled(card);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Back restores '+card+' anchor');await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await settled(card);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Settings returns to '+card+' anchor');await p.evaluate(()=>scrollTo(0,0));await capture(p,`${dir}/${card}-detail.png`);await home();}
 // Native attempts after accepted leave cannot modify outgoing text or Add
 // controls while the destination's actual worker snapshot is held.
 for(const fail of [false,true]){
  await phase('held transition '+fail);await open('rules');const originalText=await field(p).innerText(),originalItems=(await read(p)).items;
  await p.evaluate(fail=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__ctx402Transition={held:false,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='PAIA_CONTEXT_CARDS_SNAPSHOT'&&!__ctx402Transition.held){__ctx402Transition.held=true;return new Promise(resolve=>{__ctx402Transition.release=()=>resolve(fail?{ok:false,error:'STORAGE_FAILED'}:result);});}return result;};},fail);
  try{
   await p.locator('.context-back').click();await eventually(()=>p.evaluate(()=>__ctx402Transition.held));await phase('snapshot held '+fail);assert.equal(await p.locator('.context-page').evaluate(node=>node.inert),true,'entire outgoing page is inert during admitted navigation');
   await field(p).click({force:true});await p.keyboard.type('LATE_TRANSITION_TEXT');await p.locator('.add-item').click({force:true});assert.equal(await field(p).innerText(),originalText);assert.equal(await p.locator('.item-text').count(),16,'late Add cannot create under a different route');
   await phase('release snapshot '+fail);await p.evaluate(()=>__ctx402Transition.release());if(fail){await p.locator('.context-load-failed').waitFor();assert.equal(await p.locator('.item-text').count(),0);await p.locator('.context-load-failed').getByRole('button',{name:'重试',exact:true}).click();}
   await p.locator('.context-card').first().waitFor();assert.equal(await p.locator('.context-page').evaluate(node=>node.inert),false);assert.deepEqual((await read(p)).items,originalItems);
  }finally{await p.evaluate(()=>{__ctx402Transition.release?.();__ctx402Transition.restore();});}
 }
 await phase('failed target retry');
 // A failed root-to-card read has its own target title and retry path.
 // Keep the synthetic outage active through the failed target. An unrelated
 // periodic refresh must not consume a one-shot failure before navigation reads.
 await settled(null);await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__ctx402ReadFailure={calls:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=message=>{if(message.type==='PAIA_CONTEXT_CARDS_SNAPSHOT'){__ctx402ReadFailure.calls++;return Promise.resolve({ok:false,error:'STORAGE_FAILED'});}return send(message);};});
 try{
  await p.locator('.context-card[data-card="now"] .card-link').click();await p.locator('.context-load-failed').waitFor();await settled('now');assert.equal(await p.locator('.item-text').count(),0);assert.equal(await p.locator('.context-head h1').textContent(),'我的现在');assert.ok(await p.evaluate(()=>__ctx402ReadFailure.calls)>0);
  // Repair only at the real Retry activation, before its production handler.
  // This keeps a timer refresh from silently replacing the Retry under test.
  const retry=p.locator('.context-load-failed').getByRole('button',{name:'重试',exact:true});await retry.evaluate(button=>button.addEventListener('click',()=>__ctx402ReadFailure.restore(),{capture:true,once:true}));await retry.click();await eventually(()=>p.locator('.item-text').count().then(n=>n===16));assert.equal(await p.locator('.item-text').filter({hasText:'SYNTHETIC rules'}).count(),0);await home();
 }finally{await p.evaluate(()=>__ctx402ReadFailure.restore());}
 await phase('dark and reflow');
 await open('rules');await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'dark',fontSize:'xlarge',readingWidth:'wide'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='dark'));await eventually(()=>field(p).evaluate(el=>getComputedStyle(el).fontSize==='21px'));await capture(p,`${dir}/rules-dark-large.png`);
 for(const width of [768,390,320]){await p.setViewportSize({width,height:900});await capture(p,`${dir}/rules-dark-${width}.png`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 // Emulate 200% text-only enlargement at the same narrow CSS viewport. This is
 // synthetic reflow evidence, not a claim of OS/browser zoom or physical IME.
 await p.evaluate(()=>document.documentElement.style.setProperty('--paia-prose-size','42px'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/rules-320-text-200.png`);
 await phase('final invariants');
 assert.deepEqual(await protectedSnapshot(p),before);assert.equal((await read(p)).capabilities.automatic,false);assert.equal((await read(p)).connections,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
 await writeFile(`${dir}/evidence.json`,JSON.stringify({variant,threeCardIsolation:true,workerRecovery:true,legacyInfoRecovery:true,accessPreferencesOnly:true,connections:'unavailable',scrollAndHistory:true,sourceInputThoughtUnchanged:true,readingPreferences:true,syntheticTextScaling:true,physicalIme:'NOT_VERIFIED',externalClient:'NOT_AVAILABLE'},null,2));
});

for(const variant of ['source','release'])test('CTX4-03 real Topic choices, complete directory, keyboard, failure and history '+variant,{timeout:180000},async t=>{
 if(variant==='release')execFileSync('python3',['scripts/build_current_release.py'],{stdio:'pipe'});
 const h=await FakeChatGPT.start({extensionPath:resolve(variant==='release'?'work/current-release':'.'),headless:true}),p=h.archive,dir=`work/ctx4-01/${variant}/ctx4-03`,phases=[],directoryReads=[];let expectedInputsScroll=null;
 p.setDefaultTimeout(14000);await mkdir(dir,{recursive:true});
 const phase=async name=>{phases.push({name,at:new Date().toISOString()});await writeFile(`${dir}/phases.json`,JSON.stringify(phases,null,2));};
 t.after(async()=>{try{await writeFile(`${dir}/directory-reads.json`,JSON.stringify(directoryReads,null,2));await p.screenshot({path:`${dir}/last-state.png`,fullPage:true});await writeFile(`${dir}/last-state.json`,JSON.stringify(await p.evaluate(expected=>({route:history.state,scrollY,expectedInputsScroll:expected,space:document.body.dataset.paiaSpace,heading:document.querySelector('.context-head h1')?.textContent,busy:document.querySelector('.context-inputs')?.getAttribute('aria-busy'),count:document.querySelectorAll('.topic-access').length,active:document.activeElement?.outerHTML,status:document.querySelector('.context-inputs .context-notice')?.innerText}),expectedInputsScroll),null,2));}catch{}await h.close();});
 const readDirectory=async()=>{const rows=[],seen=new Set();let cursor=null,authority=null,epoch=null,selectedCount=null,pages=0;do{assert.ok(++pages<=41,'bounded Topic directory traversal');const page=await rpc(p,'PAIA_CONTEXT_TOPICS_PAGE',{options:{cursor,limit:100}});if(page.available===false&&page.reason==='stale_authority'){directoryReads.push({state:'stale_authority',offset:cursor?.offset||0,capturedAuthority:authority,discardedRows:rows.length});return null;}assert.equal(page.available,true,JSON.stringify(page));assert.equal(typeof page.authority,'string');assert.equal(typeof page.epoch,'string');if(authority!==null)assert.deepEqual([page.authority,page.epoch,page.selectedCount],[authority,epoch,selectedCount],'one complete read keeps the same authority and selection count');authority=page.authority;epoch=page.epoch;selectedCount=page.selectedCount;rows.push(...page.items);cursor=page.nextCursor;if(cursor===null)assert.equal(page.complete,true);else{assert.equal(page.complete,false);const key=JSON.stringify(cursor);assert.equal(seen.has(key),false,'Topic continuation progresses');seen.add(key);}}while(cursor!==null);directoryReads.push({state:'complete',authority,epoch,selectedCount,rows:rows.length});return rows;};
 const list=async({poll=false}={})=>{if(poll)return readDirectory();let rows=null;await eventually(async()=>{rows=await readDirectory();return rows!==null;},'complete Topic directory has current authority');return rows;};
 const ready=count=>eventually(async()=>await p.locator('.topic-access').count()===count&&await p.locator('.context-inputs').getAttribute('aria-busy')==='false'&&await p.evaluate(()=>history.state?.paiaReader?.contextCard==='inputs'&&document.querySelector('.context-page')?.inert===false),'complete ready Inputs page');
 const node=id=>p.locator(`.topic-access[data-topic-id="${id}"]`);
 const selected=async(id,{poll=false}={})=>(await list({poll}))?.find(row=>row.topicId===id);
 const home=async()=>{await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&!history.state.paiaReader.contextCard&&document.querySelector('.context-page')?.inert===false);};
 const open=async count=>{await p.locator('.context-card[data-card="inputs"] .card-link').click();await ready(count);};
 const settle=async()=>{await eventually(async()=>{let cursor=null;const seen=new Set();for(let pageNumber=0;pageNumber<16;pageNumber++){const page=await rpc(p,'SEARCH_LIBRARY',{options:{query:'SYNTHETIC CTX4-03',limit:40,cursor}});if(page.indexing||page.cursorInvalid)return false;if(!page.nextCursor)return page.complete===true;const key=JSON.stringify(page.nextCursor);assert.equal(seen.has(key),false,'search continuation progresses');seen.add(key);cursor=page.nextCursor;}assert.fail('bounded fixture search reaches its actual end');},'real library indexing settles');await eventually(async()=>{const f=await rpc(p,'FILTER_STATUS');return f.pending===0&&f.taskState==='idle';},'real filter work settles');};
 await phase('setup');await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 await h.open({id:'ctx4-03-synthetic',title:'SYNTHETIC CTX4-03 immutable Source',base:1609459200,messages:[{id:'ctx4-03-source',text:'SYNTHETIC Source body never enters Topic choice replies.'}]},{arrival:'dom-first'});await eventually(async()=>(await rpc(p,'GET_STATE')).records.length===1);await p.bringToFront();
 const input=(await rpc(p,'GET_STATE')).library.blocks[0];await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:input.documentId,blocks:[{id:input.id,expectedRevision:input.revision,libraryText:'SYNTHETIC human Working Input stays intact.',note:'SYNTHETIC independent note',excluded:false}]}});
 const ids=[];const seed=async count=>{while(ids.length<count){const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:`SYNTHETIC CTX4-03 主题 ${String(ids.length+1).padStart(3,'0')}`,operationId:crypto.randomUUID()}});ids.push(topic.id);}await settle();};
 await seed(20);await rpc(p,'CONTINUE_THINKING',{thought:{topicId:ids[0],body:'SYNTHETIC independent human Thought remains unchanged by Topic choices.',operationId:crypto.randomUUID()}});await settle();let before=await protectedSnapshot(p);
 await p.locator('.sidebar [data-view="memory"]').click();await p.locator('.context-card').first().waitFor();assert.equal((await read(p)).capabilities.inputs,true);await open(20);assert.ok((await list()).every(row=>!row.enabled&&!row.policyAllowed&&row.externalAllowed===false));const order=await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId));assert.equal(new Set(order).size,20);
 await phase('native keyboard and paused choices');
 await p.locator('.context-head .context-access').focus();await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[0]);
 await p.keyboard.press('Space');await eventually(async()=>(await selected(order[0],{poll:true}))?.enabled);await ready(20);await eventually(()=>node(order[0]).evaluate(el=>el===document.activeElement),'acknowledged choice retains native focus');assert.equal(await node(order[0]).getAttribute('data-paused'),'true');
 await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[1]);await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[19]);await p.keyboard.press('ArrowLeft');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[18]);await p.keyboard.press('Home');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[0]);await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await eventually(async()=>(await selected(order[1],{poll:true}))?.enabled);await ready(20);assert.deepEqual(await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId)),order,'selection never reorders the directory');
 await node(order[1]).evaluate(el=>{el.dataset.nativeIdentity='same-topic-node';});await node(order[1]).focus();await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>!!document.activeElement.closest('.topic-field')),false,'Tab leaves the capsule group');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[1]);
 await capture(p,`${dir}/14-inputs-paused.png`);await p.locator('.context-head .context-access').click();await eventually(async()=>(await read(p)).access.inputs.enabled);await ready(20);assert.equal(await p.locator('.context-back').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),true,'ordinary header Back is on screen');await home();assert.equal((await read(p)).topicChoices.selectedNames.length,2);await capture(p,`${dir}/home-topic-summary-paused.png`);await p.locator('.context-access.global').click();let globalAccessAck;await eventually(async()=>{globalAccessAck=await read(p);return globalAccessAck.access.global.enabled;});directoryReads.push({state:'global_access_ack',revision:globalAccessAck.access.global.revision});assert.match(await p.locator('[data-count="inputs"]').textContent(),/2/);await open(20);await capture(p,`${dir}/08-inputs-20.png`);
 assert.equal(await node(order[1]).getAttribute('data-on'),'true');assert.equal((await selected(order[1])).policyAllowed,true);assert.deepEqual(await protectedSnapshot(p),before);
 await phase('failure retry and unknown outcome');
 const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));
 await worker.evaluate(()=>{const put=IDBObjectStore.prototype.put;globalThis.__ctx403Restore=()=>{IDBObjectStore.prototype.put=put;};IDBObjectStore.prototype.put=function(row,...args){if(this.name==='operationReceipts'&&row.namespace==='context-topic-access')throw new DOMException('Synthetic choice receipt failure','UnknownError');return put.call(this,row,...args);};});
 await node(order[2]).click();await p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true}).waitFor();assert.equal((await selected(order[2])).enabled,false,'aborted receipt rolls back the choice');await capture(p,`${dir}/choice-save-failed.png`);await worker.evaluate(()=>globalThis.__ctx403Restore());await p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true}).click();await eventually(async()=>(await selected(order[2],{poll:true}))?.enabled);await ready(20);
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx403Lost={calls:[],restore:()=>{chrome.runtime.sendMessage=send;}};let armed=true;chrome.runtime.sendMessage=async message=>{if(message.type==='PAIA_CONTEXT_TOPICS_CHANGE'){__ctx403Lost.calls.push(message.change.operationId);if(armed){armed=false;await send(message);throw Error('Synthetic lost choice acknowledgment');}}if(message.type==='PAIA_CONTEXT_TOPICS_OUTCOME')return {ok:true,data:{state:'unknown',externalAllowed:false}};return send(message);};});
 try{await node(order[3]).click();await p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true}).waitFor();await p.locator('.context-back').click();assert.equal(await p.locator('.context-inputs').count(),1,'unknown choice outcome blocks leave');await node(order[4]).click();assert.equal(await p.evaluate(()=>__ctx403Lost.calls.length),1,'unknown attempt cannot retarget another Topic');assert.equal((await selected(order[4])).enabled,false);const committed=(await selected(order[3])).revision;const retry=p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true});await retry.evaluate(el=>el.addEventListener('click',()=>__ctx403Lost.restore(),{capture:true,once:true}));await retry.click();await ready(20);assert.equal((await selected(order[3])).revision,committed,'exact receipt reconciliation does not write twice');}finally{await p.evaluate(()=>__ctx403Lost.restore());}
 await p.reload();await ready(20);assert.equal((await selected(order[3])).enabled,true);await h.restartWorker();assert.equal((await selected(order[3])).enabled,true);assert.deepEqual(await protectedSnapshot(p),before);
 await phase('home selected-name summary and 50/144 real Topics');
 await home();const preview=(await read(p)).topicChoices;assert.equal(preview.selectedCount,4);assert.equal(preview.selectedNames.length,3);assert.equal(preview.remainingSelectedCount,1);assert.equal(await p.locator('.input-summary').textContent(),preview.selectedNames.join(' · ')+' +1');await capture(p,`${dir}/01-home-topic-summary.png`);await p.setViewportSize({width:390,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/home-topic-summary-390.png`);await p.setViewportSize({width:1440,height:900});await seed(50);before=await protectedSnapshot(p);await open(50);await capture(p,`${dir}/09-inputs-50.png`);assert.deepEqual(await protectedSnapshot(p),before);await home();await seed(144);before=await protectedSnapshot(p);await open(144);assert.equal((await list()).length,144);await capture(p,`${dir}/10-inputs-144.png`);
 const allIds=await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId));assert.equal(new Set(allIds).size,144);await node(allIds[0]).focus();await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),allIds.at(-1),'End reaches the actual 144th Topic');await p.keyboard.press('Space');await eventually(async()=>(await selected(allIds.at(-1),{poll:true}))?.enabled);await ready(144);assert.deepEqual(await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId)),allIds);
 await phase('Inputs return anchors and failed read');
 await p.evaluate(()=>scrollTo(0,600));await eventually(()=>p.evaluate(()=>scrollY>=590));const at=await p.evaluate(()=>scrollY);expectedInputsScroll=at;
 await p.locator('.context-back').evaluate(el=>el.addEventListener('click',()=>{window.__ctx403HeaderDeparture=scrollY;},{capture:true,once:true}));await home();const headerDeparture=await p.evaluate(()=>window.__ctx403HeaderDeparture);assert.ok(Number.isFinite(headerDeparture));const anchorTrace={target:at,headerDeparture};await writeFile(`${dir}/anchor-trace.json`,JSON.stringify(anchorTrace,null,2));expectedInputsScroll=headerDeparture;await p.goBack();await ready(144);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,headerDeparture),'header Back restores the actual captured departure');anchorTrace.headerReturn=await p.evaluate(()=>scrollY);await writeFile(`${dir}/anchor-trace.json`,JSON.stringify(anchorTrace,null,2));
 await p.evaluate(y=>scrollTo(0,y),at);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'fixed Inputs scroll target is restored before browser history');expectedInputsScroll=at;await p.goBack();await p.locator('.context-card').first().waitFor();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&!history.state.paiaReader.contextCard&&document.querySelector('.context-page')?.inert===false);assert.ok(await p.evaluate(()=>scrollY)<30);await p.goForward();await ready(144);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Inputs Back/Forward restores its own anchor');await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await ready(144);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Settings restores Inputs anchor');anchorTrace.settingsReturn=await p.evaluate(()=>scrollY);await writeFile(`${dir}/anchor-trace.json`,JSON.stringify(anchorTrace,null,2));
 await home();await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx403Read={calls:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=message=>{if(message.type==='PAIA_CONTEXT_TOPICS_PAGE'){__ctx403Read.calls++;return Promise.resolve({ok:false,error:'STORAGE_FAILED'});}return send(message);};});
 try{await p.locator('.context-card[data-card="inputs"] .card-link').click();const retry=p.locator('.context-inputs .context-notice').getByRole('button',{name:'重试',exact:true});await retry.waitFor();assert.equal(await p.locator('.item-text').count(),0);assert.ok(await p.evaluate(()=>__ctx403Read.calls)>0);await retry.evaluate(el=>el.addEventListener('click',()=>__ctx403Read.restore(),{capture:true,once:true}));await retry.click();await ready(144);}finally{await p.evaluate(()=>__ctx403Read.restore());}
 assert.deepEqual(await protectedSnapshot(p),before);await home();await seed(145);before=await protectedSnapshot(p);await open(145);assert.equal((await selected(ids.at(-1))).enabled,false,'a real new Topic is off by default');
 await phase('dark narrow and enlarged controls');await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'dark',fontSize:'xlarge',readingWidth:'wide'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='dark'));await ready(145);await p.evaluate(()=>scrollTo(0,0));await capture(p,`${dir}/18-inputs-dark.png`);
 for(const width of [768,390,320]){await p.setViewportSize({width,height:900});await ready(145);await capture(p,`${dir}/inputs-dark-${width}.png`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await p.evaluate(()=>{for(const node of document.querySelectorAll('.topic-access')){node.style.fontSize='26px';node.style.lineHeight='44px';}});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/inputs-320-text-200.png`);
 assert.deepEqual(await protectedSnapshot(p),before);assert.equal((await read(p)).capabilities.external,false);assert.equal((await read(p)).connections,0);assert.ok((await list()).every(row=>row.externalAllowed===false));assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
 await writeFile(`${dir}/evidence.json`,JSON.stringify({variant,realTopicCounts:[20,50,144,145],nativeKeyboard:true,stableOrderAndFocus:true,pausePreservesChoices:true,persistenceAndWorkerRestart:true,atomicFailureAndExactRetry:true,unknownOutcomeBlocksLeave:true,newIdentityOff:true,inputsHistoryAndSettings:true,sourceInputThoughtUnchanged:true,syntheticControlTextScaling:true,externalClient:'NOT_AVAILABLE',physicalIme:'NOT_VERIFIED'},null,2));
});
