import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
import {installContextInputsTrace,readContextInputsTrace} from './harness/context-inputs-trace.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(m=>chrome.runtime.sendMessage(m),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const read=p=>rpc(p,'PAIA_CONTEXT_CARDS_SNAPSHOT');
const capture=async(p,path)=>{await p.mouse.move(1,1);await p.waitForFunction(()=>document.querySelector('.sidebar [data-view="memory"]')?.getAttribute('aria-current')==='page'&&[...document.querySelectorAll('#memory-panel .context-access')].every(x=>!x.disabled));await p.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{})));});assert.equal(await p.locator('.workspace').evaluate(el=>getComputedStyle(el).paddingBottom),p.viewportSize().width<768?'48px':'64px','production Context retains the approved shell bottom inset');await p.screenshot({path,fullPage:true});};
const field=p=>p.locator('#memory-panel .item-text').first();
const protectedSnapshot=p=>p.evaluate(async()=>{const req=indexedDB.open('paia-archive');const db=await new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=reject;});const names=['records','blocks','thoughts','topics','inputStates','tombstones','revisions','provenance'],tx=db.transaction(names);const result=Object.fromEntries(await Promise.all(names.map(async name=>[name,await new Promise((resolve,reject)=>{const r=tx.objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=reject;})])));db.close();return result;});
async function failCommits(h){const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));await worker.evaluate(()=>{const put=IDBObjectStore.prototype.put;globalThis.__ctx4Restore=()=>{IDBObjectStore.prototype.put=put;};IDBObjectStore.prototype.put=function(row,...args){if(this.name==='operationReceipts'&&row.namespace==='context-cards')throw new DOMException('Synthetic Context write failure','UnknownError');return put.call(this,row,...args);};});return ()=>worker.evaluate(()=>globalThis.__ctx4Restore());}
for(const variant of ['source','release'])test('CTX4 real four-card durable edit/delete/undo, failure, IME, concurrency and shell '+variant,{timeout:180000},async t=>{
 const releaseDir=variant==='release'?await mkdtemp(join(tmpdir(),'paia-ctx-native-')):null;
 if(releaseDir){t.after(()=>rm(releaseDir,{recursive:true,force:true}));execFileSync('python3',['scripts/build_current_release.py',releaseDir],{stdio:'pipe'});}
 const h=await FakeChatGPT.start({extensionPath:releaseDir||resolve('.'),headless:true}),p=h.archive;
 t.after(async()=>{try{const evidenceDir=`work/ctx4-01/${variant}`;await mkdir(evidenceDir,{recursive:true});await writeFile(`${evidenceDir}/erase-save-trace.json`,JSON.stringify(await p.evaluate(()=>window.__ctxEraseTrace??[]),null,2));await p.screenshot({path:`${evidenceDir}/last-state.png`,fullPage:true});await writeFile(`${evidenceDir}/last-state.json`,JSON.stringify(await p.evaluate(()=>({route:history.state,space:document.body.dataset.paiaSpace,headings:[...document.querySelectorAll('#memory-panel h1')].map(x=>x.textContent),items:document.querySelectorAll('#memory-panel .item-text').length,fields:[...document.querySelectorAll('#memory-panel .item-text')].map(el=>({textContent:el.textContent,innerText:el.innerText,html:el.innerHTML,inert:!!el.closest('[inert]')})),navigation:[...document.querySelectorAll('.sidebar [data-view]')].map(x=>({view:x.dataset.view,current:x.getAttribute('aria-current'),background:getComputedStyle(x).backgroundColor,color:getComputedStyle(x).color})),text:document.getElementById('memory-panel').innerText})),null,2));}catch{}await h.close();});
 await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented,'consent');if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 await h.open({id:'ctx4-synthetic',title:'SYNTHETIC Context invariants',base:1609459200,messages:[{id:'ctx4-input-001',text:'SYNTHETIC Source is immutable and independent.'}]},{arrival:'dom-first'});await eventually(async()=>(await rpc(p,'GET_STATE')).records.length===1,'source capture');
 const working=(await rpc(p,'GET_STATE')).library.blocks[0];await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:working.documentId,blocks:[{id:working.id,expectedRevision:working.revision,libraryText:'SYNTHETIC preexisting user-edited Working Input',note:'SYNTHETIC existing note',excluded:false}]}});
 const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC protected Topic',operationId:crypto.randomUUID()}});await rpc(p,'CONTINUE_THINKING',{thought:{topicId:topic.id,body:'SYNTHETIC preexisting independent human Thought',operationId:crypto.randomUUID()}});
 // Settle the real derived-index owner before the exact no-write oracle. Do not
 // strip its fields or disable its background work to make this comparison pass.
 await eventually(async()=>{const index=await rpc(p,'SEARCH_LIBRARY',{options:{query:'SYNTHETIC protected Topic',limit:40}});return index.complete&&index.items.some(x=>x.topicId===topic.id);},'existing library search work finishes before the protected baseline');
 await eventually(async()=>{const filter=await rpc(p,'FILTER_STATUS');return filter.pending===0&&filter.taskState==='idle';},'capture/filter work finishes before the protected baseline');const original=await protectedSnapshot(p);assert.ok(original.thoughts.length>0);assert.equal(original.blocks[0].value.libraryText,'SYNTHETIC preexisting user-edited Working Input');
 await p.locator('.sidebar [data-view="memory"]').click();await p.locator('.context-card').first().waitFor();assert.equal(await p.locator('.context-card').count(),4);assert.equal(await p.locator('.sidebar [data-view="memory"]').getAttribute('aria-current'),'page');assert.equal(await p.locator('.sidebar [data-view="library"]').getAttribute('aria-current'),'false');assert.ok(Object.values((await read(p)).access).every(x=>!x.enabled));
 const dir=`work/ctx4-01/${variant}`;await mkdir(dir,{recursive:true});await capture(p,`${dir}/15-empty.png`);
 await p.locator('.context-card[data-card="info"] .context-access').click();await eventually(async()=>(await read(p)).access.info.enabled,'card setting commits');assert.equal((await read(p)).access.global.enabled,false);assert.equal(await p.locator('.context-card').count(),4,'capsule never navigates');assert.equal(await p.locator('.context-card[data-card="info"] .context-access').getAttribute('data-paused'),'true');
 for(const card of ['rules','now','inputs']){await p.locator(`.context-card[data-card="${card}"] .context-access`).click();await eventually(async()=>(await read(p)).access[card].enabled);}await p.locator('.context-access.global').click();await eventually(async()=>(await read(p)).access.global.enabled);await capture(p,`${dir}/01-home.png`);await p.locator('.context-access.global').click();await eventually(async()=>!(await read(p)).access.global.enabled);await capture(p,`${dir}/03-global-off.png`);await p.locator('.context-access.global').click();await eventually(async()=>(await read(p)).access.global.enabled,'Info visual states use the approved global-on setting');
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctxEraseTrace=[];window.__ctxEraseRestore=()=>{chrome.runtime.sendMessage=send;};chrome.runtime.sendMessage=async(m,...args)=>{const watch=m.type==='PAIA_CONTEXT_CARDS_CHANGE'&&m.change?.kind==='put';if(watch)__ctxEraseTrace.push({phase:'dispatch',at:performance.now(),length:m.change.body?.length,revision:m.change.expectedRevision});try{const r=await send(m,...args);if(watch)__ctxEraseTrace.push({phase:'ack',at:performance.now(),ok:r.ok,error:r.error??null});return r;}catch(error){if(watch)__ctxEraseTrace.push({phase:'error',at:performance.now(),code:error.code??null});throw error;}};});
 await p.locator('.context-card[data-card="info"] .card-link').click();await p.locator('.add-item').click();const eraseClockAt=Date.now();await p.clock.install({time:eraseClockAt});await p.clock.pauseAt(eraseClockAt+1000);try{await field(p).fill('SYNTHETIC erased before first commit');await eventually(async()=>(await rpc(p,'PAIA_CONTEXT_CARDS_DRAFTS')).length===1,'new draft protected');assert.equal(await p.evaluate(()=>__ctxEraseTrace.length),0,'paused UI autosave has not dispatched a first commit');assert.equal((await read(p)).items.length,0);await field(p).fill('');await eventually(async()=>(await rpc(p,'PAIA_CONTEXT_CARDS_DRAFTS')).length===0,'erased draft cleared');assert.equal(await p.evaluate(()=>__ctxEraseTrace.length),0);assert.equal((await read(p)).items.length,0);}finally{await p.clock.resume();await p.evaluate(()=>__ctxEraseRestore());}await p.locator('.context-back').click();await p.locator('.context-card[data-card="info"] .card-link').click();assert.equal(await p.locator('.item-text').count(),0,'erased new item never resurrects');await p.locator('.add-item').click();await field(p).fill('SYNTHETIC 第一条独立信息。');await field(p).press('Control+Enter');await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC 第一条独立信息。','real first commit');await eventually(()=>p.locator('.item-feedback').first().textContent().then(x=>x==='已保存'));
 const id=(await read(p)).items[0].id;await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await p.evaluate(()=>history.back());await field(p).waitFor();assert.equal(await field(p).innerText(),'SYNTHETIC 第一条独立信息。','browser Back restores information detail');await p.evaluate(()=>history.forward());await p.locator('.context-card').first().waitFor();await p.locator('.context-card[data-card="info"] .card-link').click();await field(p).waitFor();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&history.state.paiaReader.contextCard==='info');await p.reload();const persistedAfterReload=await read(p);assert.equal(persistedAfterReload.items[0]?.id,id,'reload retains the durable item before any route assertion');assert.equal(persistedAfterReload.items[0]?.body,'SYNTHETIC 第一条独立信息。');await field(p).waitFor();assert.equal(await field(p).innerText(),'SYNTHETIC 第一条独立信息。');await eventually(()=>p.locator('.context-head h1').evaluate(el=>el===document.activeElement&&getComputedStyle(el).outlineStyle==='none'),'route heading retains semantic focus without an interactive outline');await h.restartWorker();assert.equal((await read(p)).items[0].id,id);assert.equal((await read(p)).access.info.enabled,true);
 // Hold the real outer navigation read. Accepted leave must make the outgoing
 // editor inert before an actual late pointer/keyboard attempt, including failure.
 for(const outcome of ['success','failure']){
  const savedBody=await field(p).innerText();
  await p.evaluate(outcome=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);let release;const held=new Promise(resolve=>{release=resolve;});window.__ctxNavEntered=false;window.__ctxNavRelease=()=>{chrome.runtime.sendMessage=send;release();};let armed=true;chrome.runtime.sendMessage=(message,...args)=>{if(armed&&message.type==='GET_PAGE'&&message.page?.view==='settings'){armed=false;window.__ctxNavEntered=true;return held.then(()=>outcome==='failure'?{ok:false,error:'STORAGE_FAILED'}:send(message,...args));}return send(message,...args);};},outcome);
  const target=await field(p).boundingBox();await p.locator('.context-back').click();await p.waitForFunction(()=>window.__ctxNavEntered);
  assert.equal(await p.locator('.context-page').evaluate(el=>el.inert),true,'outgoing Info is locked while outer GET_PAGE is unresolved');
  await p.mouse.click(target.x+20,target.y+15);await p.keyboard.type('LATE_TEXT_MUST_NOT_ENTER');
  assert.equal(await field(p).innerText(),savedBody);assert.equal((await read(p)).items[0].body,savedBody);
  await p.evaluate(()=>window.__ctxNavRelease());
  if(outcome==='failure'){await p.locator('.context-load-failed').waitFor();assert.equal(await p.locator('.item-text').count(),0,'failed Home route cannot expose outgoing Info');await p.locator('.context-load-failed').getByRole('button',{name:'重试',exact:true}).click();}
  await p.locator('.context-card').first().waitFor();assert.equal(await p.locator('.context-page').evaluate(el=>el.inert),false);
  await p.locator('.context-card[data-card="info"] .card-link').click();await field(p).waitFor();assert.equal(await field(p).innerText(),savedBody);
 }
 // CTX4-07 state 05: a real protected edit before dispatch, not a saved ACK.
 const editingBefore=(await read(p)).items[0],editingText='SYNTHETIC 第二次修改，保留稳定身份。';
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx405={node:document.querySelector('#memory-panel .item-text'),dispatches:0,acks:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=async(message,...args)=>{const put=message.type==='PAIA_CONTEXT_CARDS_CHANGE'&&message.change?.kind==='put';if(put)__ctx405.dispatches++;const reply=await send(message,...args);if(put)__ctx405.acks++;return reply;};});
 // The earlier erase fixture already advanced this installed browser clock.
 // Anchor in that same clock, then pause in its future before changing the draft.
 const editingClockAt=await p.evaluate(()=>Date.now());await p.clock.pauseAt(editingClockAt+1000);
 try{
  await field(p).fill(editingText);await eventually(async()=>(await rpc(p,'PAIA_CONTEXT_CARDS_DRAFTS')).some(d=>d.ownerId===id&&d.operation.change.body===editingText),'state 05 real draft is protected before save');
  assert.deepEqual((await read(p)).items[0],editingBefore);assert.equal(await field(p).evaluate(el=>el===__ctx405.node&&el===document.activeElement),true);assert.equal(await field(p).innerText(),editingText);
  await capture(p,`${dir}/05-inline-unsaved-editing.png`);
  const evidence=await p.evaluate(()=>({dispatches:__ctx405.dispatches,acks:__ctx405.acks,sameNode:__ctx405.node===document.querySelector('#memory-panel .item-text'),focused:document.activeElement===__ctx405.node,viewport:{width:innerWidth,height:innerHeight}}));assert.equal(evidence.dispatches,0);assert.equal(evidence.acks,0);assert.equal(evidence.sameNode,true);assert.equal(evidence.focused,true);assert.deepEqual((await read(p)).items[0],editingBefore);await writeFile(`${dir}/05-inline-unsaved-editing.json`,JSON.stringify({...evidence,variant,itemId:id,savedRevision:editingBefore.revision,uiClock:'paused fixture; production autosave unchanged'},null,2));
 }finally{await p.clock.resume();await p.evaluate(()=>__ctx405.restore());}
 await field(p).press('Control+Enter');await eventually(async()=>(await read(p)).items[0]?.body.includes('第二次修改'));await capture(p,`${dir}/05-editing.png`);
 await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''})));await field(p).evaluate(el=>{el.textContent='SYNTHETIC 中文组合输入';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText',data:'中文'}));});await pause(1000);assert.match((await read(p)).items[0].body,/第二次修改/,'IME intermediate body is never committed');await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文'})));await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC 中文组合输入');
 const restore=await failCommits(h);await field(p).fill('SYNTHETIC 写入失败仍保留的草稿');await field(p).press('Control+Enter');await eventually(()=>p.locator('.item-feedback.error').isVisible(),'failed transaction retains draft');assert.equal((await read(p)).items[0].body,'SYNTHETIC 中文组合输入');await capture(p,`${dir}/16-save-failed.png`);await p.locator('.context-back').click();assert.equal(await field(p).innerText(),'SYNTHETIC 写入失败仍保留的草稿','leave guard retains failed edit');
 await restore();await p.locator('.item-feedback').getByRole('button',{name:'重试',exact:true}).click();await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC 写入失败仍保留的草稿');
 // A genuine independent page uses the same worker/revision owner.
 const second=await h.context.newPage();await second.goto(p.url());const snapshot=await read(second),item=snapshot.items[0];await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})));await field(p).evaluate(el=>{el.textContent='SYNTHETIC protected conflicting draft';});await rpc(second,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',operationId:crypto.randomUUID(),epoch:snapshot.epoch,itemId:id,expectedRevision:item.revision,body:'SYNTHETIC concurrent saved body',section:item.section}});await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await field(p).press('Control+Enter');await eventually(()=>p.locator('.item-feedback.error').isVisible(),'concurrent conflict');assert.equal(await field(p).innerText(),'SYNTHETIC protected conflicting draft');assert.equal((await read(p)).items[0].body,'SYNTHETIC concurrent saved body');p.once('dialog',d=>d.accept());const viewSaved=p.locator('.item-feedback').getByRole('button',{name:'查看已保存内容'});if(variant==='release'){await field(p).focus();await p.keyboard.press('Tab');await p.keyboard.press('Tab');await p.keyboard.press('Tab');assert.equal(await viewSaved.evaluate(el=>document.activeElement===el),true,'native Tab reaches conflict recovery action');await p.keyboard.press('Enter');}else await viewSaved.click();await eventually(()=>field(p).innerText().then(x=>x==='SYNTHETIC concurrent saved body'));await second.close();
 await field(p).hover();await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'删除',exact:true}).click();await eventually(async()=>(await read(p)).items.length===0,'real delete');await p.locator('.context-notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(async()=>(await read(p)).items[0]?.body==='SYNTHETIC concurrent saved body','real undo restores exact body');assert.equal((await read(p)).items[0].id,id);await p.reload();await eventually(()=>field(p).innerText().then(x=>x==='SYNTHETIC concurrent saved body'));await capture(p,`${dir}/04-info-journey.png`);
 assert.deepEqual(await protectedSnapshot(p),original,'Context edits never mutate Source/Input/Thought data');for(const type of ['PAIA_CONTEXT_MANUAL','PAIA_CONTEXT_BIND','PAIA_MEMORY_BUILD','PAIA_MEMORY_SHARE','PAIA_BACKUP_BEGIN_EXPORT'])assert.equal((await p.evaluate(type=>chrome.runtime.sendMessage({type}),type)).error,'FEATURE_UNAVAILABLE');assert.equal((await p.evaluate(()=>chrome.runtime.sendMessage({type:'SAVE_DEEPSEEK_CREDENTIAL'}))).error,'AI_SERVICE_UNAVAILABLE');
 for(const text of ['合成信息二：检查中间条目的撤销位置。','合成信息三：保持末尾条目的原有顺序。']){await p.locator('.add-item').click();await p.locator('.item-text').last().fill(text);await p.locator('.item-text').last().press('Control+Enter');await eventually(async()=>(await read(p)).items.some(x=>x.body===text));}
 const ordered=(await read(p)).items.map(x=>x.id),middle=p.locator(`[data-item="${ordered[1]}"]`);await middle.locator('.item-text').hover();await middle.locator('.item-menu summary').click();await middle.getByRole('button',{name:'删除',exact:true}).click();await eventually(async()=>(await read(p)).items.length===2);await p.locator('.context-notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(()=>p.locator('.context-item').count().then(n=>n===3));assert.deepEqual(await p.locator('.context-item').evaluateAll(nodes=>nodes.map(n=>n.dataset.item)),ordered,'middle-item Undo restores its canonical place without reload');
 const visual=await read(p);for(let i=0;i<5;i++)await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',operationId:crypto.randomUUID(),epoch:visual.epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`合成信息 ${i+1}：用于核对独立资料的阅读、编辑与保存。`,section:i<3?'语言与习惯':'长期领域'}});await eventually(()=>p.locator('.item-text').count().then(n=>n===8));await capture(p,`${dir}/04-info-eight-items.png`);
 // Preserve the focused Undo evidence above, then capture a genuinely resting
 // eight-item detail through the normal navigation owner, without CSS overrides.
 const restingItems=(await read(p)).items;
 await p.locator('.context-back').click();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&!history.state.paiaReader.contextCard);await p.locator('.context-card[data-card="info"] .card-link').click();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&history.state.paiaReader.contextCard==='info'&&document.querySelector('.context-head h1')===document.activeElement);
 assert.equal(await p.locator('.item-text').count(),8);assert.deepEqual((await read(p)).items,restingItems,'resting visual reentry preserves all confirmed items');await capture(p,`${dir}/04-info-resting.png`);
 await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await field(p).waitFor();assert.equal(await p.locator('.item-text').count(),8,'Settings returns to the same Context detail');
 await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'dark'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='dark'));await capture(p,`${dir}/13-dark.png`);await p.setViewportSize({width:390,height:844});await capture(p,`${dir}/12-compact-dark.png`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'light'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='light'));await capture(p,`${dir}/12-compact.png`);await p.locator('.context-card[data-card="info"] .card-link').click();await field(p).waitFor();await capture(p,`${dir}/19-compact-info.png`);await p.setViewportSize({width:320,height:740});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await field(p).focus();await field(p).press('Tab');assert.equal(await p.locator('.item-menu summary').first().evaluate(el=>el===document.activeElement),true);await p.keyboard.press('Enter');await p.keyboard.press('Escape');assert.equal(await p.locator('.item-menu').first().getAttribute('open'),null);
 assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);await writeFile(`${dir}/evidence.json`,JSON.stringify({variant,sourceInputThoughtUnchanged:true,workerRestart:true,commitReloadEditDeleteUndo:true,syntheticIme:true,physicalIme:'NOT_VERIFIED',saveFailure:true,concurrency:true,externalConnections:false,screenshots:'synthetic production extension',network:h.extensionNetworkRequests},null,2));
});

for(const variant of ['source','release'])test('CTX4-02 all local cards, isolated recovery, access and page return '+variant,{timeout:180000},async t=>{
 const releaseDir=variant==='release'?await mkdtemp(join(tmpdir(),'paia-ctx4-locale-')):null;
 if(releaseDir){t.after(()=>rm(releaseDir,{recursive:true,force:true}));execFileSync('python3',['scripts/build_current_release.py',releaseDir],{stdio:'pipe'});}
 const h=await FakeChatGPT.start({extensionPath:releaseDir||resolve('.'),headless:true}),p=h.archive;
 const dir=`work/ctx4-01/${variant}/ctx4-02`;await mkdir(dir,{recursive:true});
 // Keep the case budget unchanged; an individual hung action must produce its
 // own failing stack and current phase rather than consuming the whole case.
 p.setDefaultTimeout(14000);const started=Date.now(),phases=[];
 const phase=async label=>{const entry={label,elapsedMs:Date.now()-started};phases.push(entry);console.info('CTX4-02 '+variant+' '+JSON.stringify(entry));await writeFile(`${dir}/phases.json`,JSON.stringify(phases,null,2));};
 t.after(async()=>{try{await writeFile(`${dir}/last-state.json`,JSON.stringify(await p.evaluate(()=>({route:history.state,space:document.body.dataset.paiaSpace,workspace:document.querySelector('.workspace')?.dataset.state,coarse:matchMedia('(pointer: coarse)').matches,touchPoints:navigator.maxTouchPoints,scrollY,inert:document.querySelector('.context-page')?.inert,heading:document.querySelector('#memory-panel h1')?.textContent,active:document.activeElement?.outerHTML,transitionHeld:globalThis.__ctx402Transition?.held,fields:[...document.querySelectorAll('#memory-panel .item-text')].map(el=>({textContent:el.textContent,innerText:el.innerText,html:el.innerHTML})),notice:document.querySelector('.context-notice')?.innerText})),null,2));await p.screenshot({path:`${dir}/last-state.png`,fullPage:true});}catch{}await h.close();});
 await phase('setup');
 await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 await h.open({id:'ctx4-02-synthetic',title:'SYNTHETIC three-card preserved owners',base:1609459200,messages:[{id:'ctx4-02-input',text:'SYNTHETIC Source remains independent of all three Context cards.'}]},{arrival:'dom-first'});await eventually(async()=>(await rpc(p,'GET_STATE')).records.length===1);
 const working=(await rpc(p,'GET_STATE')).library.blocks[0];await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:working.documentId,blocks:[{id:working.id,expectedRevision:working.revision,libraryText:'SYNTHETIC protected Working Input for all three cards',note:'SYNTHETIC protected note',excluded:false}]}});
 const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC CTX4-02 preserved Topic',operationId:crypto.randomUUID()}});await rpc(p,'CONTINUE_THINKING',{thought:{topicId:topic.id,body:'SYNTHETIC existing independent human Thought for three-card checks',operationId:crypto.randomUUID()}});
 await eventually(async()=>{const index=await rpc(p,'SEARCH_LIBRARY',{options:{query:'SYNTHETIC CTX4-02 preserved Topic',limit:40}});return index.complete&&index.items.some(item=>item.topicId===topic.id);});await eventually(async()=>{const status=await rpc(p,'FILTER_STATUS');return status.pending===0&&status.taskState==='idle';});
 // Source capture opened another tab. Exercise native editing in the actual
 // foreground page rather than waiting through background animation throttling.
 await p.bringToFront();assert.equal(await p.evaluate(()=>document.visibilityState),'visible');
 await p.locator('.sidebar [data-view="memory"]').click();await p.locator('.context-card').first().waitFor();const before=await protectedSnapshot(p),ids={};
 const settled=card=>p.waitForFunction(card=>document.body.dataset.paiaSpace==='memory'&&history.state?.paiaReader?.view==='memory'&&(history.state.paiaReader.contextCard??null)===card&&document.querySelector('.workspace')?.dataset.state==='ready'&&document.querySelector('.context-page')?.inert===false,card);
 const open=async card=>{await phase('open '+card);await p.locator(`.context-card[data-card="${card}"] .card-link`).click();await p.locator('.add-item').waitFor();await settled(card);await phase('opened '+card);};
 const home=async()=>{await phase('home click');await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await settled(null);await phase('home ready');};
 const items=async card=>(await read(p)).items.filter(x=>x.card===card);
 await phase('three-card creation');
 for(const card of ['info','rules','now']){
  await open(card);assert.equal(await p.locator('.item-text').count(),0);await p.locator('.add-item').click();const text=`SYNTHETIC ${card} natural-language item`;
  await field(p).fill(text);await field(p).press('Enter');await p.keyboard.insertText('Second line');await field(p).press('Control+Enter');await eventually(async()=>(await items(card))[0]?.body===text+'\nSecond line','Enter retains a real newline and shortcut commits '+card);
  ids[card]=(await items(card))[0].id;assert.equal(await p.locator('.item-text').count(),1);await home();assert.equal(await p.locator(`[data-count="${card}"]`).textContent(),'1 项');
 }
 assert.deepEqual((await read(p)).counts,{info:1,rules:1,now:1,inputs:0});
 // CTX4-07: hold only delivery of a real committed acknowledgement. The
 // worker/IDB owner runs unchanged; UI must remain truthful until delivery.
 await phase('compact committed acknowledgement pending');await p.setViewportSize({width:320,height:900});await open('info');
 const pendingText='SYNTHETIC compact pending 👩‍💻 é 中文 draft',pendingBefore=(await items('info'))[0];
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx407Ack={node:document.querySelector('#memory-panel .item-text'),held:false,delivered:false,calls:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=async(message,...args)=>{if(message.type==='PAIA_CONTEXT_CARDS_CHANGE'&&message.change?.kind==='put'&&message.change.card==='info')__ctx407Ack.calls++;const result=await send(message,...args);if(message.type==='PAIA_CONTEXT_CARDS_CHANGE'&&message.change?.kind==='put'&&message.change.card==='info'&&!__ctx407Ack.held){__ctx407Ack.held=true;__ctx407Ack.result=result;return new Promise(resolve=>{__ctx407Ack.release=()=>{__ctx407Ack.delivered=true;resolve(result);};});}return result;};});
 try{
  await field(p).fill(pendingText);await field(p).press('Control+Enter');await eventually(()=>p.evaluate(()=>__ctx407Ack.held));
  const pendingSaved=(await items('info'))[0];assert.equal(pendingSaved.body,pendingText);assert.equal(pendingSaved.id,pendingBefore.id);assert.equal(pendingSaved.revision,pendingBefore.revision+1,'real commit precedes held ACK delivery');
  assert.equal(await p.locator('.item-feedback').first().textContent(),'正在保存…');assert.equal(await field(p).evaluate(el=>el===__ctx407Ack.node),true);assert.equal(await field(p).innerText(),pendingText);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/07-compact-saving-real-ack-held.png`);
  await p.locator('.context-back').click();assert.equal(await p.evaluate(()=>history.state.paiaReader.contextCard),'info','pending leave does not switch route before acknowledgement');assert.equal(await field(p).evaluate(el=>el===__ctx407Ack.node),true);assert.equal(await field(p).innerText(),pendingText);assert.equal(await p.evaluate(()=>__ctx407Ack.delivered),false);
  await p.evaluate(()=>__ctx407Ack.release());await p.locator('.context-card').first().waitFor();await settled(null);await open('info');assert.equal(await field(p).innerText(),pendingText);assert.equal((await items('info'))[0].revision,pendingSaved.revision);assert.equal(await p.evaluate(()=>__ctx407Ack.calls),1,'leave joins the single real save');await home();
 }finally{await p.evaluate(()=>{__ctx407Ack.release?.();__ctx407Ack.restore();});}
 await p.setViewportSize({width:1440,height:900});
 await phase('editing undo deletion IME failure');
 for(const card of ['rules','now']){
  await open(card);await field(p).fill(`SYNTHETIC ${card} manual edit`);await field(p).press('Control+Enter');await eventually(async()=>(await items(card))[0]?.body.endsWith('manual edit'));
  await field(p).hover();await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'查看依据',exact:true}).click();assert.match(await p.locator('.item-evidence').textContent(),/由你添加/);
  await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'撤销上次修改',exact:true}).click();await eventually(async()=>(await items(card))[0]?.body.includes('Second line'),'saved undo stays in '+card);
  await field(p).hover();await p.locator('.item-menu summary').first().click();await p.locator('.item-menu').getByRole('button',{name:'删除',exact:true}).click();await eventually(async()=>(await items(card)).length===0);await eventually(()=>p.locator('.item-text').count().then(n=>n===0));
  await p.locator('.context-notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(async()=>(await items(card))[0]?.id===ids[card]);await field(p).waitFor();assert.equal(await p.locator('.item-text').count(),1);
  // No cross-card update may remount the focused editor or expose another body.
  await field(p).focus();const opposite=card==='rules'?'now':'rules',other=(await items(opposite))[0];await field(p).evaluate(el=>{el.dataset.nativeIdentity='retained';el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.textContent='SYNTHETIC 正在组合 '+el.getAttribute('aria-label');});
  const snap=await read(p);await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',card:opposite,operationId:crypto.randomUUID(),epoch:snap.epoch,itemId:other.id,expectedRevision:other.revision,section:other.section,body:other.body+' [other card]'}});await pause(850);
  assert.equal(await p.locator('.item-text').count(),1);assert.equal(await field(p).getAttribute('data-native-identity'),'retained');assert.equal(await field(p).evaluate(el=>el===document.activeElement),true);assert.equal((await items(card))[0].body.includes('正在组合'),false);
  // A preference refresh must translate chrome without replacing the live IME body.
  await field(p).evaluate(el=>{globalThis.__ctxLocaleNode=el;const range=document.createRange();range.setStart(el.firstChild,10);range.setEnd(el.firstChild,14);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);globalThis.__ctxLocaleText=selection.toString();});
  await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'en'}});
  await eventually(()=>p.locator('#memory-panel h1').textContent().then(value=>value===(card==='rules'?'My Rules':'My Now')),'Context chrome follows preferences');
  assert.equal(await field(p).evaluate(el=>el===globalThis.__ctxLocaleNode&&getSelection().anchorNode===el.firstChild&&getSelection().toString()===globalThis.__ctxLocaleText),true,'locale preserves the exact body node and selected Unicode range');
  assert.equal((await items(card))[0].body.includes('正在组合'),false,'locale does not commit composition');
  await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN'}});
  await eventually(()=>p.locator('#memory-panel h1').textContent().then(value=>value===(card==='rules'?'我的规则':'我的现在')),'Context chrome returns to Chinese');
  await field(p).press('Control+Enter');assert.equal((await items(card))[0].body.includes('正在组合'),false,'shortcut does not commit IME');await field(p).evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await field(p).press('Control+Enter');await eventually(async()=>(await items(card))[0]?.body.includes('正在组合'));
  const restore=await failCommits(h);await field(p).fill(`SYNTHETIC ${card} failed draft`);await field(p).press('Control+Enter');await eventually(()=>p.locator('.item-feedback.error').isVisible());await p.locator('.context-back').click();assert.equal(await field(p).innerText(),`SYNTHETIC ${card} failed draft`);await restore();await p.locator('.item-feedback').getByRole('button',{name:'重试',exact:true}).click();await eventually(async()=>(await items(card))[0]?.body===`SYNTHETIC ${card} failed draft`);await home();
 }
 // Persist actual source-free draft envelopes through the worker; the UI must
 // recover only its own card, including old omitted-card Info payloads.
 await phase('recovery');
 const epoch=(await read(p)).epoch,drafts=[];for(const card of ['info','rules','now']){const change={kind:'put',operationId:crypto.randomUUID(),epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`SYNTHETIC recovered ${card}`,section:'SYNTHETIC recovered group',...(card==='info'?{}:{card})};drafts.push(change);await rpc(p,'PAIA_RECOVERY_DRAFT_SAVE',{draft:{kind:'context_item',ownerId:change.itemId,epoch,token:change.operationId,sourceRecordIds:[],operation:{type:'PAIA_CONTEXT_CARDS_CHANGE',change}}});}
 for(const card of ['info','rules','now']){await open(card);await eventually(()=>p.locator('.item-text').count().then(n=>n===2));const recovered=p.locator('.item-text').filter({hasText:`SYNTHETIC recovered ${card}`});assert.equal(await recovered.count(),1);assert.equal(await p.locator('.item-text').filter({hasText:'SYNTHETIC recovered'}).count(),1);await recovered.press('Control+Enter');await eventually(async()=>(await items(card)).length===2);await home();}
 for(const card of ['info','rules','now']){await p.locator(`.context-card[data-card="${card}"] .context-access`).click();await eventually(async()=>(await read(p)).access[card].enabled);await eventually(()=>p.locator(`.context-card[data-card="${card}"] .context-access`).getAttribute('data-paused').then(value=>value==='true')); }
 await phase('access and connections');
 await capture(p,`${dir}/03-all-local-paused.png`);await p.locator('.context-access.global').click();await eventually(async()=>(await read(p)).access.global.enabled);await capture(p,`${dir}/01-local-home.png`);
 await p.locator('.context-card[data-card="rules"] .context-access').click();await eventually(async()=>!(await read(p)).access.rules.enabled);assert.equal((await read(p)).access.info.enabled,true);assert.equal((await read(p)).access.now.enabled,true);assert.deepEqual((await read(p)).counts,{info:2,rules:2,now:2,inputs:0});
 // Populated cards-off is distinct from global pause or the empty screen.
 await phase('populated cards off and responsive Home');const allOffBefore=await read(p);
 for(const card of ['info','rules','now','inputs'])if((await read(p)).access[card].enabled){await p.locator(`.context-card[data-card="${card}"] .context-access`).click();await eventually(async()=>!(await read(p)).access[card].enabled);}
 assert.equal((await read(p)).access.global.enabled,true);assert.deepEqual((await read(p)).items,allOffBefore.items);assert.deepEqual((await read(p)).counts,allOffBefore.counts);
 for(const width of [1440,768,320]){
  await p.setViewportSize({width,height:900});await capture(p,`${dir}/07-populated-cards-off-${width}.png`);
  assert.equal(await p.locator('.context-card').count(),4);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const overview=await p.locator('#memory-panel').innerText();for(const item of allOffBefore.items)assert.equal(overview.includes(item.body),false,'Home never exposes independent Item bodies');
  for(const card of ['info','rules','now','inputs']){const capsule=p.locator(`.context-card[data-card="${card}"] .context-access`);assert.equal(await capsule.isVisible(),true);assert.equal(await capsule.isEnabled(),true);assert.match(await capsule.textContent(),/仅自己/);}
 }
 await p.locator('.context-card[data-card="info"] .context-access').click();await eventually(async()=>(await read(p)).access.info.enabled);assert.equal(await p.locator('.context-card').count(),4,'compact capsule does not open detail');await open('info');assert.equal(await p.locator('.item-text').count(),2);await home();
 // Browser touch emulation verifies existing tablet rules, not physical hardware.
 await phase('tablet coarse controls');await p.setViewportSize({width:768,height:900});
 const touchBefore=await read(p),touchProtected=await protectedSnapshot(p),cdp=await p.context().newCDPSession(p),touchEvidence={variant,device:'browser touch emulation',width:768,targets:[]};
 const coarse=async card=>{await settled(card);await phase('coarse setup '+(card??'home'));await cdp.send('Emulation.setEmitTouchEventsForMouse',{enabled:true,configuration:'mobile'});await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});await p.waitForFunction(()=>matchMedia('(pointer: coarse)').matches===true);assert.equal(await p.evaluate(()=>matchMedia('(pointer: coarse)').matches),true,'settled owner exposes actual coarse media before touch');await phase('coarse ready '+(card??'home'));};
 const tap=async(locator,{height44=false,menu=false,card=false}={})=>{
  await locator.scrollIntoViewIfNeeded();const geometry=await locator.evaluate((node,{menu,card})=>{const r=node.getBoundingClientRect(),css=getComputedStyle(node);window.__ctxTouch=[];node.addEventListener('touchstart',event=>window.__ctxTouch.push({trusted:event.isTrusted,type:event.type}),{once:true});return {x:r.x+r.width/2,y:card?r.bottom-20:r.y+r.height/2,width:r.width,height:r.height,opacity:css.opacity,visibility:css.visibility,coarse:matchMedia('(pointer: coarse)').matches};},{menu,card});
  assert.equal(geometry.coarse,true,'touch target measured under actual coarse media');if(height44)assert.ok(geometry.height>=44,JSON.stringify(geometry));if(menu){assert.ok(geometry.width>=44);assert.equal(geometry.opacity,'1');}assert.equal(geometry.visibility,'visible');
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:geometry.x,y:geometry.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.deepEqual(await p.evaluate(()=>window.__ctxTouch),[{trusted:true,type:'touchstart'}]);touchEvidence.targets.push(geometry);
 };
 try{
  await coarse(null);
  const capsuleSizes=await p.locator('#memory-panel .context-access').evaluateAll(nodes=>nodes.map(node=>({className:node.className,height:node.getBoundingClientRect().height,minHeight:getComputedStyle(node).minHeight})));await writeFile(`${dir}/07-tablet-coarse-sizes.json`,JSON.stringify(capsuleSizes,null,2));for(const size of capsuleSizes)assert.ok(size.height>=44,JSON.stringify(size));
  const infoCapsule=p.locator('.context-card[data-card="info"] .context-access');await tap(infoCapsule,{height44:true});await eventually(async()=>!(await read(p)).access.info.enabled);assert.equal(await p.locator('.context-card').count(),4,'tablet capsule does not activate overlaid card link');
  for(const card of ['global','rules','now','inputs'])assert.equal((await read(p)).access[card].enabled,touchBefore.access[card].enabled);
  await tap(p.locator('.context-card[data-card="info"] .card-link'),{card:true});await field(p).waitFor();assert.equal(await p.locator('.item-text').count(),2);await coarse('info');
  const summary=p.locator('.item-menu summary').first();await tap(summary,{height44:true,menu:true});await eventually(()=>p.locator('.item-menu').first().getAttribute('open').then(value=>value!==null));await p.screenshot({path:`${dir}/07-tablet-coarse-info-menu.png`,fullPage:true});assert.equal(await p.evaluate(()=>matchMedia('(pointer: coarse)').matches),true);await tap(summary,{height44:true,menu:true});await eventually(()=>p.locator('.item-menu').first().getAttribute('open').then(value=>value===null));
  await tap(p.locator('.context-back'),{height44:true});await p.locator('.context-card').first().waitFor();await coarse(null);await tap(p.locator('.context-card[data-card="info"] .context-access'),{height44:true});await eventually(async()=>(await read(p)).access.info.enabled);
  const after=await read(p);assert.deepEqual(after.items,touchBefore.items);assert.deepEqual(after.counts,touchBefore.counts);for(const card of ['global','info','rules','now','inputs'])assert.equal(after.access[card].enabled,touchBefore.access[card].enabled);assert.deepEqual(await protectedSnapshot(p),touchProtected);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await capture(p,`${dir}/07-tablet-coarse-home.png`);await writeFile(`${dir}/07-tablet-coarse.json`,JSON.stringify(touchEvidence,null,2));
 }finally{try{await cdp.send('Emulation.setEmitTouchEventsForMouse',{enabled:false});await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});}finally{await cdp.detach();}}
 // Restore the exact existing desired access values for the remaining journey.
 for(const card of ['info','rules','now','inputs'])if((await read(p)).access[card].enabled!==allOffBefore.access[card].enabled){await p.locator(`.context-card[data-card="${card}"] .context-access`).click();await eventually(async()=>(await read(p)).access[card].enabled===allOffBefore.access[card].enabled);}
 assert.deepEqual((await read(p)).items,allOffBefore.items);await p.setViewportSize({width:1440,height:900});
 await p.locator('.connections-link').click();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));assert.equal(await p.locator('#memory-panel .context-access').count(),0);assert.match(await p.locator('#memory-panel').innerText(),/外部连接目前不可用/);await capture(p,`${dir}/connections-empty.png`);
 await p.waitForFunction(()=>history.state?.paiaReader?.contextCard==='connections');await p.reload();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));await home();await p.goBack();await eventually(()=>p.locator('.context-head h1').textContent().then(x=>x==='已连接的 AI'));await p.goForward();await p.locator('.context-card').first().waitFor();
 // Long, real persisted card content exercises the existing per-page scroll
 // owner, groups, dark/narrow layouts and retained reading preferences.
 await phase('visual and long fixtures');
 const groups={rules:['回答方式','表达偏好','工作方式'],now:['当前项目','阶段重点','最近关注']},visualSections={rules:[0,0,0,1,1,2,2],now:[0,0,1,2]};
 await p.locator('.context-card[data-card="rules"] .context-access').click();await eventually(async()=>(await read(p)).access.rules.enabled);
 for(const card of ['rules','now']){
  for(const item of await items(card))await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'delete',operationId:crypto.randomUUID(),epoch,itemId:item.id,expectedRevision:item.revision}});
  for(const [i,section]of visualSections[card].entries())await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',card,operationId:crypto.randomUUID(),epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`合成${card==='rules'?'规则':'状态'} ${i+1}：保留完整表达，说明重点与适用条件。`,section:groups[card][section]}});
  await open(card);await capture(p,`${dir}/${card==='rules'?'06-rules-seven':'07-now-four'}.png`);await home();
  for(let i=visualSections[card].length;i<16;i++)await rpc(p,'PAIA_CONTEXT_CARDS_CHANGE',{change:{kind:'put',card,operationId:crypto.randomUUID(),epoch,itemId:crypto.randomUUID(),expectedRevision:0,body:`SYNTHETIC ${card} ${i+1}：保留自然语言、多行内容与当前人工修改。\n第二行验证完整正文。`,section:groups[card][i%3]}});
 }

 await phase('scroll and history');
 for(const card of ['rules','now']){await open(card);await eventually(()=>p.locator('.item-text').count().then(n=>n===16));await p.evaluate(()=>window.scrollTo(0,460));await eventually(()=>p.evaluate(()=>scrollY>=450),'settled Context page reaches the unchanged 460px scroll target');const at=await p.evaluate(()=>scrollY);assert.ok(at>=450);await p.goBack();await p.locator('.context-card').first().waitFor();await settled(null);assert.ok(await p.evaluate(()=>scrollY)<30,'home retains its own anchor');await p.goForward();await p.locator('.add-item').waitFor();await settled(card);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Back restores '+card+' anchor');await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await settled(card);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Settings returns to '+card+' anchor');await p.evaluate(()=>scrollTo(0,0));await capture(p,`${dir}/${card}-detail.png`);await home();}
 // Native attempts after accepted leave cannot modify outgoing text or Add
 // controls while the destination's actual worker snapshot is held.
 for(const fail of [false,true]){
  await phase('held transition '+fail);await open('rules');const originalText=await field(p).innerText(),originalItems=(await read(p)).items;
  await p.evaluate(fail=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__ctx402Transition={held:false,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='PAIA_CONTEXT_CARDS_SNAPSHOT'&&!__ctx402Transition.held){__ctx402Transition.held=true;return new Promise(resolve=>{__ctx402Transition.release=()=>resolve(fail?{ok:false,error:'STORAGE_FAILED'}:result);});}return result;};},fail);
  try{
   await p.locator('.context-back').click();await eventually(()=>p.evaluate(()=>__ctx402Transition.held));await phase('snapshot held '+fail);assert.equal(await p.locator('.context-page').evaluate(node=>node.inert),true,'entire outgoing page is inert during admitted navigation');
   await field(p).click({force:true});await p.keyboard.type('LATE_TRANSITION_TEXT');await p.locator('.add-item').click({force:true});assert.equal(await field(p).innerText(),originalText);assert.equal(await p.locator('.item-text').count(),16,'late Add cannot create under a different route');
   await phase('release snapshot '+fail);await p.evaluate(()=>__ctx402Transition.release());if(fail){await p.locator('.context-load-failed').waitFor();assert.equal(await p.locator('.item-text').count(),0);await p.locator('.context-load-failed').getByRole('button',{name:'重试',exact:true}).click();}
   await p.locator('.context-card').first().waitFor();assert.equal(await p.locator('.context-page').evaluate(node=>node.inert),false);assert.deepEqual((await read(p)).items,originalItems);
  }finally{await p.evaluate(()=>{__ctx402Transition.release?.();__ctx402Transition.restore();});}
 }
 await phase('failed target retry');
 // A failed root-to-card read has its own target title and retry path.
 // Keep the synthetic outage active through the failed target. An unrelated
 // periodic refresh must not consume a one-shot failure before navigation reads.
 await settled(null);await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__ctx402ReadFailure={calls:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=message=>{if(message.type==='PAIA_CONTEXT_CARDS_SNAPSHOT'){__ctx402ReadFailure.calls++;return Promise.resolve({ok:false,error:'STORAGE_FAILED'});}return send(message);};});
 try{
  await p.locator('.context-card[data-card="now"] .card-link').click();await p.locator('.context-load-failed').waitFor();await settled('now');assert.equal(await p.locator('.item-text').count(),0);assert.equal(await p.locator('.context-head h1').textContent(),'我的现在');assert.ok(await p.evaluate(()=>__ctx402ReadFailure.calls)>0);
  // Repair only at the real Retry activation, before its production handler.
  // This keeps a timer refresh from silently replacing the Retry under test.
  const retry=p.locator('.context-load-failed').getByRole('button',{name:'重试',exact:true});await retry.evaluate(button=>button.addEventListener('click',()=>__ctx402ReadFailure.restore(),{capture:true,once:true}));await retry.click();await eventually(()=>p.locator('.item-text').count().then(n=>n===16));assert.equal(await p.locator('.item-text').filter({hasText:'SYNTHETIC rules'}).count(),0);await home();
 }finally{await p.evaluate(()=>__ctx402ReadFailure.restore());}
 await phase('dark and reflow');
 await open('rules');await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'dark',fontSize:'xlarge',readingWidth:'wide'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='dark'));await eventually(()=>field(p).evaluate(el=>getComputedStyle(el).fontSize==='21px'));await capture(p,`${dir}/rules-dark-large.png`);
 for(const width of [768,390,320]){await p.setViewportSize({width,height:900});await capture(p,`${dir}/rules-dark-${width}.png`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 // Emulate 200% text-only enlargement at the same narrow CSS viewport. This is
 // synthetic reflow evidence, not a claim of OS/browser zoom or physical IME.
 await p.evaluate(()=>document.documentElement.style.setProperty('--paia-prose-size','42px'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/rules-320-text-200.png`);
 await phase('final invariants');
 assert.deepEqual(await protectedSnapshot(p),before);assert.equal((await read(p)).capabilities.automatic,false);assert.equal((await read(p)).connections,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
 await writeFile(`${dir}/evidence.json`,JSON.stringify({variant,threeCardIsolation:true,workerRecovery:true,legacyInfoRecovery:true,accessPreferencesOnly:true,connections:'unavailable',scrollAndHistory:true,sourceInputThoughtUnchanged:true,readingPreferences:true,syntheticTextScaling:true,physicalIme:'NOT_VERIFIED',externalClient:'NOT_AVAILABLE'},null,2));
});

for(const variant of ['source','release'])test('CTX4-03 real Topic choices, complete directory, keyboard, failure and history '+variant,{timeout:180000},async t=>{
 const releaseDir=variant==='release'?await mkdtemp(join(tmpdir(),'paia-ctx-native-')):null;
 if(releaseDir){t.after(()=>rm(releaseDir,{recursive:true,force:true}));execFileSync('python3',['scripts/build_current_release.py',releaseDir],{stdio:'pipe'});}
 const h=await FakeChatGPT.start({extensionPath:releaseDir||resolve('.'),headless:true}),p=h.archive,dir=`work/ctx4-01/${variant}/ctx4-03`,phases=[],directoryReads=[],uiTraces=[],headerTraces=[];let expectedInputsScroll=null;
 p.setDefaultTimeout(14000);await mkdir(dir,{recursive:true});
 const phase=async name=>{phases.push({name,at:new Date().toISOString()});await p.evaluate(label=>globalThis.__ctx403UiTrace?.checkpoint(label),name.toLowerCase().replace(/[^a-z0-9]+/g,'_'));await writeFile(`${dir}/phases.json`,JSON.stringify(phases,null,2));};
 const retainUiTrace=async label=>{let trace;try{trace=await readContextInputsTrace(p);}catch{trace={unavailable:true};}uiTraces.push({label,trace});await writeFile(`${dir}/ui-read-focus-trace.json`,JSON.stringify(uiTraces,null,2));};
 const retainHeaderTrace=async label=>{let trace;try{trace=await p.evaluate(()=>{const trace=globalThis.__ctx403HeaderTrace;if(!trace)return {unavailable:true};document.removeEventListener('pointerdown',trace.listener,true);document.removeEventListener('click',trace.listener,true);return {capacity:32,events:trace.events};});}catch{trace={unavailable:true};}headerTraces.push({label,trace});await writeFile(`${dir}/header-navigation.json`,JSON.stringify(headerTraces,null,2));return trace;};
 t.after(async()=>{try{await writeFile(`${dir}/choice-acknowledgments.json`,JSON.stringify(await p.evaluate(()=>window.__ctx403Acks||[]),null,2));await writeFile(`${dir}/synthetic-write-keys.json`,JSON.stringify(await h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js')).evaluate(()=>globalThis.__ctx403Writes||[]),null,2));}catch{}try{await retainHeaderTrace('final');}catch{}try{await retainUiTrace('final');}catch{}try{await writeFile(`${dir}/directory-reads.json`,JSON.stringify(directoryReads,null,2));await p.screenshot({path:`${dir}/last-state.png`,fullPage:true});await writeFile(`${dir}/last-state.json`,JSON.stringify(await p.evaluate(expected=>({route:history.state,scrollY,expectedInputsScroll:expected,space:document.body.dataset.paiaSpace,heading:document.querySelector('.context-head h1')?.textContent,busy:document.querySelector('.context-inputs')?.getAttribute('aria-busy'),count:document.querySelectorAll('.topic-access').length,enabledCount:document.querySelectorAll('.topic-access:not(:disabled)').length,rovingCount:[...document.querySelectorAll('.topic-access')].filter(node=>!node.disabled&&node.tabIndex===0).length,active:document.activeElement?.outerHTML,status:document.querySelector('.context-inputs .context-notice')?.innerText}),expectedInputsScroll),null,2));}catch{}try{await p.evaluate(()=>globalThis.__ctx403UiTrace?.restore());}catch{}await h.close();});
 await installContextInputsTrace(p);
 // Bounded synthetic diagnostics, never request bodies or automatic retries.
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx403Acks=[];chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='PAIA_CONTEXT_TOPICS_CHANGE'){if(__ctx403Acks.length===32)__ctx403Acks.shift();__ctx403Acks.push({at:Date.now(),ok:result?.ok,result:result?.data?{ok:result.data.ok,reason:result.data.reason,conflict:result.data.conflict,revision:result.data.revision,enabled:result.data.enabled}:null});}return result;};});
 await h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js')).evaluate(()=>{const put=IDBObjectStore.prototype.put;globalThis.__ctx403Writes=[];IDBObjectStore.prototype.put=function(value,...args){if(__ctx403Writes.length===512)__ctx403Writes.shift();__ctx403Writes.push({at:Date.now(),store:this.name,key:typeof value?.id==='string'?value.id:null,...(this.name==='meta'&&value?.id==='backup-data-generation'?{generation:value.value}:{})});return put.call(this,value,...args);};});
 // Capture the actual native header gesture without preventing or retrying it.
 const installHeaderTrace=()=>p.evaluate(()=>{const events=[],listener=event=>{const target=event.target?.closest?.('.context-back,.context-access');if(!target)return;const header=document.querySelector('.context-head .context-access');if(events.length===32)events.shift();events.push({event:event.type,trusted:event.isTrusted,target:target.classList.contains('context-back')?'back':'access',headerDisabled:header?.disabled??null,headerPressed:header?.getAttribute('aria-pressed')??null,inputsBusy:document.querySelector('.context-inputs')?.getAttribute('aria-busy')??null,pageInert:document.querySelector('.context-page')?.inert??null});};document.addEventListener('pointerdown',listener,true);document.addEventListener('click',listener,true);globalThis.__ctx403HeaderTrace={events,listener};});
 await installHeaderTrace();
 const readDirectory=async()=>{const rows=[],seen=new Set();let cursor=null,authority=null,epoch=null,selectedCount=null,pages=0;do{assert.ok(++pages<=41,'bounded Topic directory traversal');const page=await rpc(p,'PAIA_CONTEXT_TOPICS_PAGE',{options:{cursor,limit:100}});if(page.available===false&&page.reason==='stale_authority'){directoryReads.push({state:'stale_authority',offset:cursor?.offset||0,capturedAuthority:authority,discardedRows:rows.length});return null;}assert.equal(page.available,true,JSON.stringify(page));assert.equal(typeof page.authority,'string');assert.equal(typeof page.epoch,'string');if(authority!==null)assert.deepEqual([page.authority,page.epoch,page.selectedCount],[authority,epoch,selectedCount],'one complete read keeps the same authority and selection count');authority=page.authority;epoch=page.epoch;selectedCount=page.selectedCount;rows.push(...page.items);cursor=page.nextCursor;if(cursor===null)assert.equal(page.complete,true);else{assert.equal(page.complete,false);const key=JSON.stringify(cursor);assert.equal(seen.has(key),false,'Topic continuation progresses');seen.add(key);}}while(cursor!==null);directoryReads.push({state:'complete',authority,epoch,selectedCount,rows:rows.length});return rows;};
 const list=async({poll=false}={})=>{if(poll)return readDirectory();let rows=null;await eventually(async()=>{rows=await readDirectory();return rows!==null;},'complete Topic directory has current authority');return rows;};
 // A failed read deliberately retains the old nodes and clears aria-busy.
 // These fixtures have eligible Topics, so count alone cannot certify readiness.
 // Header access owns a separate pending operation: durable access and old
 // usable Topic rows do not prove its acknowledgement/refresh has settled.
 // Never recover a failure here: the explicit failure journey owns real Retry.
 const ready=count=>eventually(()=>p.evaluate(expected=>{const root=document.querySelector('.context-inputs'),header=document.querySelector('.context-head .context-access'),nodes=[...document.querySelectorAll('.topic-access')];return history.state?.paiaReader?.contextCard==='inputs'&&document.querySelector('.context-page')?.inert===false&&header?.disabled===false&&root?.getAttribute('aria-busy')==='false'&&!root.querySelector('.context-notice button')&&nodes.length===expected&&nodes.every(node=>!node.disabled)&&nodes.filter(node=>node.tabIndex===0).length===(expected?1:0);},count),'complete usable Inputs page and settled header access');
 const node=id=>p.locator(`.topic-access[data-topic-id="${id}"]`);
 const selected=async(id,{poll=false}={})=>(await list({poll}))?.find(row=>row.topicId===id);
 const home=async()=>{await p.locator('.context-back').click();await p.locator('.context-card').first().waitFor();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&!history.state.paiaReader.contextCard&&document.querySelector('.context-page')?.inert===false);};
 const open=async count=>{await p.locator('.context-access.global:not(:disabled)').waitFor();await p.locator('.context-card[data-card="inputs"] .card-link').click();await ready(count);};
 const settle=async()=>{await eventually(async()=>{let cursor=null;const seen=new Set();for(let pageNumber=0;pageNumber<16;pageNumber++){const page=await rpc(p,'SEARCH_LIBRARY',{options:{query:'SYNTHETIC CTX4-03',limit:40,cursor}});if(page.indexing||page.cursorInvalid)return false;if(!page.nextCursor)return page.complete===true;const key=JSON.stringify(page.nextCursor);assert.equal(seen.has(key),false,'search continuation progresses');seen.add(key);cursor=page.nextCursor;}assert.fail('bounded fixture search reaches its actual end');},'real library indexing settles');await eventually(async()=>{const f=await rpc(p,'FILTER_STATUS');return f.pending===0&&f.taskState==='idle';},'real filter work settles');};
 await phase('setup');await p.setViewportSize({width:1440,height:900});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
 const sourceHost=await h.open({id:'ctx4-03-synthetic',title:'SYNTHETIC CTX4-03 immutable Source',base:1609459200,messages:[{id:'ctx4-03-source',text:'SYNTHETIC Source body never enters Topic choice replies.'}]},{arrival:'dom-first'});await eventually(async()=>(await rpc(p,'GET_STATE')).records.length===1);
 // Capture saves its Source before the optional presence projection finishes.
 // Complete that real setup stage and close its polling host before choices.
 await eventually(()=>p.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('paia-archive');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('filterInputs','readonly'),read=tx.objectStore('filterInputs').getAll();read.onsuccess=()=>{const rows=read.result;resolve(rows.length===1&&rows[0].presence?.version===1);};read.onerror=()=>reject(read.error);tx.oncomplete=()=>db.close();};})),'synthetic capture presence projection is actually stored');
 await sourceHost.close();assert.equal(sourceHost.isClosed(),true);await p.bringToFront();
 const input=(await rpc(p,'GET_STATE')).library.blocks[0];await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:input.documentId,blocks:[{id:input.id,expectedRevision:input.revision,libraryText:'SYNTHETIC human Working Input stays intact.',note:'SYNTHETIC independent note',excluded:false}]}});
 const ids=[];const seed=async count=>{while(ids.length<count){const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:`SYNTHETIC CTX4-03 主题 ${String(ids.length+1).padStart(3,'0')}`,operationId:crypto.randomUUID()}});ids.push(topic.id);}await settle();};
 await seed(20);await rpc(p,'CONTINUE_THINKING',{thought:{topicId:ids[0],body:'SYNTHETIC independent human Thought remains unchanged by Topic choices.',operationId:crypto.randomUUID()}});await settle();let before=await protectedSnapshot(p);
 await p.locator('.sidebar [data-view="memory"]').click();await p.locator('.context-card').first().waitFor();assert.equal((await read(p)).capabilities.inputs,true);await open(20);assert.ok((await list()).every(row=>!row.enabled&&!row.policyAllowed&&row.externalAllowed===false));const order=await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId));assert.equal(new Set(order).size,20);
 await phase('native keyboard and paused choices');
 await p.locator('.context-head .context-access').focus();await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[0]);
 await p.keyboard.press('Space');await eventually(async()=>(await selected(order[0],{poll:true}))?.enabled);await ready(20);await eventually(()=>node(order[0]).evaluate(el=>el===document.activeElement),'acknowledged choice retains native focus');assert.equal(await node(order[0]).getAttribute('data-paused'),'true');
 await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[1]);await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[19]);await p.keyboard.press('ArrowLeft');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[18]);await p.keyboard.press('Home');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[0]);await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await eventually(async()=>(await selected(order[1],{poll:true}))?.enabled);await ready(20);assert.deepEqual(await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId)),order,'selection never reorders the directory');
 await node(order[1]).evaluate(el=>{el.dataset.nativeIdentity='same-topic-node';});await node(order[1]).focus();assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[1],'usable selected Topic receives native focus before Tab');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>!!document.activeElement.closest('.topic-field')),false,'Tab leaves the capsule group');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),order[1]);
 await capture(p,`${dir}/14-inputs-paused.png`);await p.locator('.context-head .context-access').click();await eventually(async()=>(await read(p)).access.inputs.enabled);await ready(20);assert.equal(await p.locator('.context-back').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),true,'ordinary header Back is on screen');await home();assert.equal((await read(p)).topicChoices.selectedNames.length,2);await capture(p,`${dir}/home-topic-summary-paused.png`);await p.locator('.context-access.global').click();let globalAccessAck;await eventually(async()=>{globalAccessAck=await read(p);return globalAccessAck.access.global.enabled;});directoryReads.push({state:'global_access_ack',revision:globalAccessAck.access.global.revision});assert.match(await p.locator('[data-count="inputs"]').textContent(),/2/);await open(20);await capture(p,`${dir}/08-inputs-20.png`);
 assert.equal(await node(order[1]).getAttribute('data-on'),'true');assert.equal((await selected(order[1])).policyAllowed,true);assert.deepEqual(await protectedSnapshot(p),before);
 await phase('failure retry and unknown outcome');
 const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));
 await worker.evaluate(()=>{const put=IDBObjectStore.prototype.put;globalThis.__ctx403Restore=()=>{IDBObjectStore.prototype.put=put;};IDBObjectStore.prototype.put=function(row,...args){if(this.name==='operationReceipts'&&row.namespace==='context-topic-access')throw new DOMException('Synthetic choice receipt failure','UnknownError');return put.call(this,row,...args);};});
 await node(order[2]).click();await p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true}).waitFor();assert.equal((await selected(order[2])).enabled,false,'aborted receipt rolls back the choice');await capture(p,`${dir}/choice-save-failed.png`);await worker.evaluate(()=>globalThis.__ctx403Restore());await p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true}).click();await eventually(async()=>(await selected(order[2],{poll:true}))?.enabled);await ready(20);
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx403Lost={calls:[],restore:()=>{chrome.runtime.sendMessage=send;}};let armed=true;chrome.runtime.sendMessage=async message=>{if(message.type==='PAIA_CONTEXT_TOPICS_CHANGE'){__ctx403Lost.calls.push(message.change.operationId);if(armed){armed=false;await send(message);throw Error('Synthetic lost choice acknowledgment');}}if(message.type==='PAIA_CONTEXT_TOPICS_OUTCOME')return {ok:true,data:{state:'unknown',externalAllowed:false}};return send(message);};});
 try{await node(order[3]).click();await p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true}).waitFor();await p.locator('.context-back').click();assert.equal(await p.locator('.context-inputs').count(),1,'unknown choice outcome blocks leave');await node(order[4]).click();assert.equal(await p.evaluate(()=>__ctx403Lost.calls.length),1,'unknown attempt cannot retarget another Topic');assert.equal((await selected(order[4])).enabled,false);const committed=(await selected(order[3])).revision;const retry=p.locator('.context-inputs .context-notice').getByRole('button',{name:'核对上次操作',exact:true});await retry.evaluate(el=>el.addEventListener('click',()=>__ctx403Lost.restore(),{capture:true,once:true}));await retry.click();await ready(20);assert.equal((await selected(order[3])).revision,committed,'exact receipt reconciliation does not write twice');}finally{await p.evaluate(()=>__ctx403Lost.restore());}
 await writeFile(`${dir}/before-reload-choice-acknowledgments.json`,JSON.stringify(await p.evaluate(()=>window.__ctx403Acks||[]),null,2));await writeFile(`${dir}/before-reload-synthetic-write-keys.json`,JSON.stringify(await worker.evaluate(()=>globalThis.__ctx403Writes||[]),null,2));
 await retainUiTrace('before_reload');const beforeReloadHeader=await retainHeaderTrace('before_reload');assert.ok(beforeReloadHeader.events?.some(event=>event.event==='click'&&event.target==='back'),'header evidence is retained before document replacement');assert.ok(beforeReloadHeader.events.length<=32);await p.reload();await installContextInputsTrace(p);await installHeaderTrace();await ready(20);assert.equal((await selected(order[3])).enabled,true);await h.restartWorker();assert.equal((await selected(order[3])).enabled,true);assert.deepEqual(await protectedSnapshot(p),before);
 await phase('home selected-name summary and 50/144 real Topics');
 await home();const preview=(await read(p)).topicChoices;assert.equal(preview.selectedCount,4);assert.equal(preview.selectedNames.length,3);assert.equal(preview.remainingSelectedCount,1);assert.equal(await p.locator('.input-summary').textContent(),preview.selectedNames.join(' · ')+' +1');await capture(p,`${dir}/01-home-topic-summary.png`);await p.setViewportSize({width:390,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/home-topic-summary-390.png`);await p.setViewportSize({width:1440,height:900});await seed(50);before=await protectedSnapshot(p);await open(50);await capture(p,`${dir}/09-inputs-50.png`);assert.deepEqual(await protectedSnapshot(p),before);await home();await seed(144);before=await protectedSnapshot(p);await open(144);assert.equal((await list()).length,144);await capture(p,`${dir}/10-inputs-144.png`);
 const allIds=await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId));assert.equal(new Set(allIds).size,144);await node(allIds[0]).focus();await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.dataset.topicId),allIds.at(-1),'End reaches the actual 144th Topic');await p.keyboard.press('Space');await eventually(async()=>(await selected(allIds.at(-1),{poll:true}))?.enabled);await ready(144);assert.deepEqual(await p.locator('.topic-access').evaluateAll(nodes=>nodes.map(node=>node.dataset.topicId)),allIds);
 await phase('Inputs return anchors and failed read');
 await p.evaluate(()=>scrollTo(0,600));await eventually(()=>p.evaluate(()=>scrollY>=590));const at=await p.evaluate(()=>scrollY);expectedInputsScroll=at;
 await p.locator('.context-back').evaluate(el=>el.addEventListener('click',()=>{window.__ctx403HeaderDeparture=scrollY;},{capture:true,once:true}));await home();const headerDeparture=await p.evaluate(()=>window.__ctx403HeaderDeparture);assert.ok(Number.isFinite(headerDeparture));const anchorTrace={target:at,headerDeparture};await writeFile(`${dir}/anchor-trace.json`,JSON.stringify(anchorTrace,null,2));expectedInputsScroll=headerDeparture;await p.goBack();await ready(144);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,headerDeparture),'header Back restores the actual captured departure');anchorTrace.headerReturn=await p.evaluate(()=>scrollY);await writeFile(`${dir}/anchor-trace.json`,JSON.stringify(anchorTrace,null,2));
 await p.evaluate(y=>scrollTo(0,y),at);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'fixed Inputs scroll target is restored before browser history');expectedInputsScroll=at;await p.goBack();await p.locator('.context-card').first().waitFor();await p.waitForFunction(()=>history.state?.paiaReader?.view==='memory'&&!history.state.paiaReader.contextCard&&document.querySelector('.context-page')?.inert===false);assert.ok(await p.evaluate(()=>scrollY)<30);await p.goForward();await ready(144);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Inputs Back/Forward restores its own anchor');await p.locator('.sidebar [data-view="settings"]').click();await p.locator('#ux-settings-back').click();await ready(144);await eventually(()=>p.evaluate(y=>Math.abs(scrollY-y)<3,at),'Settings restores Inputs anchor');anchorTrace.settingsReturn=await p.evaluate(()=>scrollY);await writeFile(`${dir}/anchor-trace.json`,JSON.stringify(anchorTrace,null,2));
 await home();await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx403Read={calls:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=message=>{if(message.type==='PAIA_CONTEXT_TOPICS_PAGE'){__ctx403Read.calls++;return Promise.resolve({ok:false,error:'STORAGE_FAILED'});}return send(message);};});
 try{await p.locator('.context-card[data-card="inputs"] .card-link').click();const retry=p.locator('.context-inputs .context-notice').getByRole('button',{name:'重试',exact:true});await retry.waitFor();assert.equal(await p.locator('.item-text').count(),0);assert.ok(await p.evaluate(()=>__ctx403Read.calls)>0);await retry.evaluate(el=>el.addEventListener('click',()=>__ctx403Read.restore(),{capture:true,once:true}));await retry.click();await ready(144);}finally{await p.evaluate(()=>__ctx403Read.restore());}
 assert.deepEqual(await protectedSnapshot(p),before);await home();await seed(145);before=await protectedSnapshot(p);await open(145);assert.equal((await selected(ids.at(-1))).enabled,false,'a real new Topic is off by default');
 // State 17: reveal the actual new directory identity without choosing it.
 const newTopicId=ids.at(-1),newTopicBefore=await selected(newTopicId),choicesBefore=await list();
 await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.__ctx417={writes:0,restore:()=>{chrome.runtime.sendMessage=send;}};chrome.runtime.sendMessage=(message,...args)=>{if(message.type==='PAIA_CONTEXT_TOPICS_CHANGE')__ctx417.writes++;return send(message,...args);};});
 try{
  const target=node(newTopicId);await target.scrollIntoViewIfNeeded();await target.focus();assert.equal(await target.getAttribute('data-topic-id'),newTopicId);assert.equal(await target.getAttribute('data-on'),'false');assert.equal(await target.getAttribute('aria-pressed'),'false');assert.match(await target.innerText(),/主题 145/);
  assert.equal(await target.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&el===document.activeElement;}),true,'new Topic is actually visible and keyboard focused without activation');await capture(p,`${dir}/17-new-topic-off.png`);
  assert.deepEqual(await selected(newTopicId),newTopicBefore);assert.deepEqual(await list(),choicesBefore);assert.equal(await p.evaluate(()=>__ctx417.writes),0);assert.deepEqual(await protectedSnapshot(p),before);await writeFile(`${dir}/17-new-topic-off.json`,JSON.stringify({variant,topicId:newTopicId,enabled:false,choiceWrites:0,visible:true,focused:true,viewport:p.viewportSize()},null,2));
 }finally{await p.evaluate(()=>__ctx417.restore());}
 await phase('dark narrow and enlarged controls');await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'dark',fontSize:'xlarge',readingWidth:'wide'}});await eventually(()=>p.evaluate(()=>document.documentElement.dataset.paiaTheme==='dark'));await ready(145);await p.evaluate(()=>scrollTo(0,0));await capture(p,`${dir}/18-inputs-dark.png`);
 for(const width of [768,390,320]){await p.setViewportSize({width,height:900});await ready(145);await capture(p,`${dir}/inputs-dark-${width}.png`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await p.evaluate(()=>{for(const node of document.querySelectorAll('.topic-access')){node.style.fontSize='26px';node.style.lineHeight='44px';}});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await capture(p,`${dir}/inputs-320-text-200.png`);
 assert.equal(await p.evaluate(()=>{const events=globalThis.__ctx403HeaderTrace?.events;return Array.isArray(events)&&events.length<=32&&events.some(event=>event.event==='click'&&event.target==='back');}),true,'the new document records its own bounded header gestures');
 assert.deepEqual(await protectedSnapshot(p),before);assert.equal((await read(p)).capabilities.external,false);assert.equal((await read(p)).connections,0);assert.ok((await list()).every(row=>row.externalAllowed===false));assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
 await writeFile(`${dir}/evidence.json`,JSON.stringify({variant,realTopicCounts:[20,50,144,145],nativeKeyboard:true,stableOrderAndFocus:true,pausePreservesChoices:true,persistenceAndWorkerRestart:true,atomicFailureAndExactRetry:true,unknownOutcomeBlocksLeave:true,newIdentityOff:true,inputsHistoryAndSettings:true,sourceInputThoughtUnchanged:true,syntheticControlTextScaling:true,externalClient:'NOT_AVAILABLE',physicalIme:'NOT_VERIFIED'},null,2));
});
