import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,derived} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {initializeTopicIdentity,identityMetadata,topicNameToken,topicNameFence,setTopicLifecycle,resolveTopicIdentity,topicIdentitiesSeparate} from '../core/topic-identity.js';
import {automaticMembershipAllowed} from '../core/topic-intent.js';
const op=()=>crypto.randomUUID();
const rows=(s,name)=>s.repository.transaction(false,t=>t.all(name));
const raw=(s,name,id)=>s.repository.transaction(false,t=>t.get(name,id));
const topic=(s,name='Synthetic independent object')=>s.createTopic({name,operationId:op()});
const entry=s=>s.createEntry({actor:'user',operationId:op(),body:'Single canonical synthetic body',type:'idea',formation:'explicit',evidence:[]});
async function place(s,e,a,extra={}){const current=await s.entry(e.id),owner=await s.topic(a.id),old=await s.libraryPlacement(a.id,e.id);return s.placeEntry({entryId:e.id,topicId:a.id,expectedEntryRevision:current.revision,expectedTopicRevision:owner.organizationRevision,...(old?{expectedPlacementRevision:old.revision}:{}),operationId:op(),...extra});}
async function autoPlace(s,e,a){return s.foundationWrite(async t=>{const row=await s.readableEntry(t,e.id);await s.libraryCommit.organize(t,row,{topicRef:'t0'},{topicMap:{t0:{id:a.id}},sectionMap:{}},'ai',op());await t.put('thoughts',row);});}
async function merge(s,a,b){return s.startLayout({kind:'topic_merge',topicId:a.id,survivorId:b.id,expectedTopicRevision:(await s.topic(a.id)).organizationRevision,expectedSurvivorRevision:(await s.topic(b.id)).organizationRevision,operationId:op()});}

test('TOPIC-01 starts empty and allocates independent IDs only at explicit creation',async()=>{
 const {s}=await setup(OrganizerStore);assert.equal((await rows(s,'topics')).length,0);const a=await topic(s,'Same human label'),b=await topic(s,'Same human label');assert.notEqual(a.id,b.id);assert.equal((await s.topic(a.id)).identity.origin,'user');assert.equal((await rows(s,'sections')).length,2);
 assert.equal((await raw(s,'meta','context-cards:v1')),undefined);assert.equal((await rows(s,'topics')).some(x=>x.systemTopicId||x.domainId),false);
});
test('TOPIC-01 UI edit and foundation rename retain AI identity and body-free alias history',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Synthetic original label');await s.foundationWrite(async t=>{const row=await t.get('topics',a.id);row.createdBy='ai';row.protections.name={locked:false};initializeTopicIdentity(row,'ai');await t.put('topics',row);});
 await s.editTopic({id:a.id,expectedRevision:0,changes:{name:'Synthetic human label'},operationId:op()});await s.renameTopic({id:a.id,expectedRevision:1,name:'Synthetic final label',operationId:op()});
 const now=await s.topic(a.id);assert.equal(now.id,a.id);assert.equal(now.createdBy,'ai');assert.equal(now.identity.origin,'ai');assert.equal(now.identity.aliases.length,2);assert.equal(now.protections.name.locked,true);assert.equal(now.identity.aliases[0].actor,'ai');assert.equal(now.identity.aliases[1].actor,'user');assert.ok(!JSON.stringify(now.identity).includes('Synthetic'));
 const token=await topicNameToken(s,'Synthetic original label');assert.deepEqual(await s.repository.transaction(false,t=>topicNameFence(t,token)),{ids:[a.id],blocked:false});
 const history=(await s.revisions({kind:'topic',entityId:a.id})).items;assert.ok(history.some(x=>x.before?.name==='Synthetic original label'));assert.equal((await rows(s,'topics')).length,1);
});
test('TOPIC-01 name protection does not freeze new automatic membership or another edge',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s),b=await topic(s,'Other independent object'),e=await entry(s);await s.renameTopic({id:a.id,name:'Human rename',expectedRevision:0,operationId:op()});await place(s,e,b);await autoPlace(s,e,a);
 const current=await s.entry(e.id);assert.deepEqual(new Set(current.topics),new Set([a.id,b.id]));assert.equal((await s.libraryPlacement(a.id,e.id)).membershipAuthorship,'ai');assert.equal((await s.libraryPlacement(b.id,e.id)).membershipAuthorship,'user');assert.equal(current.body,'Single canonical synthetic body');assert.equal((await rows(s,'thoughts')).length,1);
 await assert.rejects(autoPlace(s,e,b));
});
test('TOPIC-01 atomic move persists include and exclude across restart; AI cannot reverse it',async()=>{
 const f=await setup(OrganizerStore),a=await topic(f.s),b=await topic(f.s,'Destination object'),e=await entry(f.s);await place(f.s,e,a);const req={entryId:e.id,sourceTopicId:a.id,targetTopicId:b.id,expectedEntryRevision:(await f.s.entry(e.id)).revision,expectedSourceRevision:(await f.s.topic(a.id)).organizationRevision,expectedTargetRevision:(await f.s.topic(b.id)).organizationRevision,operationId:op()};const result=await f.s.moveMembership(req);
 await f.s.repository.close();const s=new OrganizerStore(f.storage,{indexedDB:f.indexedDB});assert.deepEqual(await s.moveMembership(req),result);const now=await s.entry(e.id);assert.deepEqual(now.organizationIntents.included,[b.id]);assert.deepEqual(now.organizationIntents.excluded,[a.id]);assert.equal(now.organizationIntents.edges[a.id].actor,'user');await assert.rejects(autoPlace(s,e,a));assert.equal((await s.libraryPlacement(a.id,e.id)).lifecycle,'removed');assert.equal(now.body,'Single canonical synthetic body');
});
test('TOPIC-01 fixed membership set denies new AI edges but later user intent can change it',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s),b=await topic(s,'Other object'),e=await entry(s);await place(s,e,a);await s.fixMembershipSet({entryId:e.id,expectedRevision:(await s.entry(e.id)).revision,operationId:op()});await assert.rejects(autoPlace(s,e,b));await place(s,e,b);assert.deepEqual(new Set((await s.entry(e.id)).organizationIntents.fixed.topicIds),new Set([a.id,b.id]));await place(s,e,a,{remove:true});assert.deepEqual((await s.entry(e.id)).organizationIntents.fixed.topicIds,[b.id]);
});
test('TOPIC-01 keep-separate survives rename, redirected lookup and third-identity merge',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Alpha object'),b=await topic(s,'Beta object'),c=await topic(s,'Survivor object');await s.keepTopicsSeparate({sourceId:a.id,targetId:b.id});await s.renameTopic({id:a.id,name:'Alpha renamed',expectedRevision:0,operationId:op()});await assert.rejects(merge(s,a,b));await merge(s,a,c);await s.drainLibraryMaintenance();assert.equal((await s.topic(a.id)).id,c.id);assert.equal(await s.repository.transaction(false,t=>topicIdentitiesSeparate(t,a.id,b.id)),true);await assert.rejects(merge(s,b,c));assert.equal((await s.topic(b.id)).id,b.id);
});
test('TOPIC-01 merge Undo preserves constraints and redo cannot collapse a new keep-separate pair',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Source'),b=await topic(s,'Survivor');await merge(s,a,b);await s.drainLibraryMaintenance();const rev=(await s.revisions({kind:'topic',entityId:b.id})).items.find(x=>x.reason==='merge');await s.restoreRevision({id:rev.id,side:'before',expectedRevision:(await s.topic(b.id)).revision,operationId:op()});await s.keepTopicsSeparate({sourceId:a.id,targetId:b.id});await assert.rejects(s.restoreRevision({id:rev.id,side:'after',expectedRevision:(await s.topic(b.id)).revision,operationId:op()}));assert.equal((await s.topic(a.id)).id,a.id);assert.equal((await s.topic(a.id)).protections.organization.reason,'restore');const restored=await s.topic(a.id);assert.equal(restored.pinKey,1);assert.throws(()=>setTopicLifecycle(restored,'dormant',{actor:'ai'}));
});
test('TOPIC-01 removed aliases are no-recreation fences; restore keeps identity and protected placement',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Original object label'),e=await entry(s);await place(s,e,a);await s.editTopic({id:a.id,expectedRevision:0,changes:{name:'Renamed object label'},operationId:op()});await s.removeTopic({id:a.id,expectedRevision:(await s.topic(a.id)).revision,operationId:op()});const token=await topicNameToken(s,'Original object label');assert.equal((await s.repository.transaction(false,t=>topicNameFence(t,token))).blocked,true);
 const state=await raw(s,'topics',a.id);assert.equal(state.identity.noRecreation,true);await assert.rejects(place(s,e,a));await s.restoreTopicContainer({id:a.id,expectedRevision:state.revision,operationId:op()});assert.equal((await s.topic(a.id)).id,a.id);assert.equal((await s.libraryPlacement(a.id,e.id)).membershipAuthorship,'user');assert.equal((await s.entry(e.id)).organizationIntents.edges[a.id].reason,'restore');await assert.rejects(autoPlace(s,e,a));
});
test('TOPIC-01 removed old name blocks actual automatic commit without creating a Topic',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Original label'),e=await entry(s);await s.renameTopic({id:a.id,expectedRevision:0,name:'New label',operationId:op()});await s.removeTopic({id:a.id,expectedRevision:1,operationId:op()});const token=await topicNameToken(s,'Original label');await s.foundationWrite(async t=>{const row=await s.readableEntry(t,e.id);await s.libraryCommit.organize(t,row,{newTopic:'Original label'},{topicMap:{},sectionMap:{}},'ai',op(),token,null);});assert.equal((await rows(s,'topics')).length,1);assert.equal((await rows(s,'placements')).length,0);
});
test('TOPIC-01 stale CAS and failed multi-placement transaction preserve old body and organization',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s),b=await topic(s,'Other object'),e=await entry(s);await place(s,e,a);const before=await rows(s,'thoughts');assert.equal((await s.moveMembership({entryId:e.id,sourceTopicId:a.id,targetTopicId:b.id,expectedEntryRevision:0,expectedSourceRevision:(await s.topic(a.id)).organizationRevision,expectedTargetRevision:0,operationId:op()})).conflict,true);assert.deepEqual(await rows(s,'thoughts'),before);
 const snapshot=await Promise.all(['thoughts','topics','placements'].map(x=>rows(s,x)));const original=s.placeEntryInTransaction.bind(s);let calls=0;s.placeEntryInTransaction=async(...args)=>{if(++calls===2)throw Error('synthetic failed target write');return original(...args);};await assert.rejects(s.moveMembership({entryId:e.id,sourceTopicId:a.id,targetTopicId:b.id,expectedEntryRevision:(await s.entry(e.id)).revision,expectedSourceRevision:(await s.topic(a.id)).organizationRevision,expectedTargetRevision:0,operationId:op()}));assert.deepEqual(await Promise.all(['thoughts','topics','placements'].map(x=>rows(s,x))),snapshot);
});
test('TOPIC-01 compatibility mapping is bounded, restart-safe and never invents aliases/authorship',async()=>{
 const f=await setup(OrganizerStore),a=await topic(f.s),b=await topic(f.s,'Legacy unknown');await f.s.foundationWrite(async t=>{for(const id of [a.id,b.id]){const row=await t.get('topics',id);delete row.identity;if(id===b.id)delete row.createdBy;await t.put('topics',row);}});const source=await rows(f.s,'records'),before=await rows(f.s,'topics');const first=await f.s.mapTopicIdentityBatch({limit:1});assert.equal(first.complete,false);assert.equal(first.mapped,1);await f.s.repository.close();const s=new OrganizerStore(f.storage,{indexedDB:f.indexedDB});const second=await s.mapTopicIdentityBatch({limit:1});assert.equal(second.complete,true);assert.equal(second.mapped,2);const after=await rows(s,'topics');assert.deepEqual(after.map(({identity,...row})=>row),before);assert.equal(after.find(x=>x.id===b.id).identity.origin,'unknown');assert.deepEqual(after.find(x=>x.id===b.id).identity.aliases,[]);assert.deepEqual(await s.mapTopicIdentityBatch(),second);assert.deepEqual(await rows(s,'topics'),after);assert.deepEqual(await rows(s,'records'),source);
});
test('TOPIC-01 unknown legacy organization remains protected while known AI body is unchanged',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s),e=await entry(s);await s.foundationWrite(async t=>{const row=await t.get('thoughts',e.id);delete row.organizationIntents.version;delete row.origin;await t.put('thoughts',row);});const before=await raw(s,'thoughts',e.id);await assert.rejects(autoPlace(s,e,a));assert.deepEqual(await raw(s,'thoughts',e.id),before);
});
test('TOPIC-01 valid lifecycle mechanics retain ID and reject AI removal/restoration or pinned dormancy',async()=>{
 const row={id:'synthetic-topic',createdBy:'ai',lifecycle:'active',pinKey:1};initializeTopicIdentity(row,'ai');setTopicLifecycle(row,'dormant',{actor:'ai',operationId:'synthetic-operation'});assert.equal(row.id,'synthetic-topic');setTopicLifecycle(row,'active',{actor:'ai'});assert.throws(()=>setTopicLifecycle(row,'removed',{actor:'ai'}));row.pinKey=0;assert.throws(()=>setTopicLifecycle(row,'dormant',{actor:'ai'}));setTopicLifecycle(row,'removed',{actor:'user'});assert.throws(()=>setTopicLifecycle(row,'active',{actor:'ai'}));setTopicLifecycle(row,'active',{actor:'user'});assert.equal(row.identity.noRecreation,false);assert.equal(row.id,'synthetic-topic');row.pinKey=1;assert.throws(()=>setTopicLifecycle(row,'dormant',{actor:'ai'}));assert.throws(()=>identityMetadata({identity:{version:9}}));
});
test('TOPIC-01 redirect cycles and malformed identities fail closed',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s),b=await topic(s,'Other');await s.foundationWrite(async t=>{for(const [id,to]of [[a.id,b.id],[b.id,a.id]]){const row=await t.get('topics',id);row.lifecycle='merged';row.redirectTo=to;await t.put('topics',row);}});await assert.rejects(s.topic(a.id));
});
test('TOPIC-01 local identity work preserves all Source/Input rows and authorization metadata with zero network',async()=>{
 const {s}=await setup(OrganizerStore),tables=['records','recordIndex','blocks','inputStates','tombstones'];const before=await Promise.all(tables.map(x=>rows(s,x))),auth=(await rows(s,'meta')).filter(x=>/passport|memory|context|consent|gate/i.test(x.id));let calls=0;const old=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw Error('network forbidden');};try{const a=await topic(s),b=await topic(s,'Other'),e=await entry(s);await s.renameTopic({id:a.id,expectedRevision:0,name:'Renamed',operationId:op()});await place(s,e,a);await autoPlace(s,e,b);await s.keepTopicsSeparate({sourceId:a.id,targetId:b.id});await s.mapTopicIdentityBatch();assert.deepEqual(await Promise.all(tables.map(x=>rows(s,x))),before);assert.deepEqual((await rows(s,'meta')).filter(x=>/passport|memory|context|consent|gate/i.test(x.id)),auth);assert.equal(calls,0);}finally{globalThis.fetch=old;}
});

test('TOPIC-01 dormant identity and missing old proposal token cannot create a replacement',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Sleeping object'),e=await entry(s);await s.foundationWrite(async t=>{const row=await t.get('topics',a.id);setTopicLifecycle(row,'dormant',{actor:'ai',operationId:op(),at:s.clock()});await t.put('topics',row);});const token=await topicNameToken(s,'Sleeping object');
 await s.foundationWrite(async t=>{await s.libraryCommit.organize(t,await s.readableEntry(t,e.id),{newTopic:'Sleeping object'},{topicMap:{},sectionMap:{}},'ai',op(),token,null);});assert.equal((await rows(s,'topics')).length,1);assert.equal((await raw(s,'topics',a.id)).lifecycle,'dormant');await assert.rejects(s.foundationWrite(async t=>s.libraryCommit.organize(t,await s.readableEntry(t,e.id),{newTopic:'Forged replacement'},{topicMap:{},sectionMap:{}},'ai',op())));
});

test('TOPIC-01 legacy remove records its current normalized name before any compatibility mapping',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Alpha　Object'),e=await entry(s);await s.foundationWrite(async t=>{const row=await t.get('topics',a.id);delete row.identity;await t.put('topics',row);for(const meta of await t.all('meta'))if(meta.id.startsWith('personalTopicName:'))await t.delete('meta',meta.id);});await s.removeTopic({id:a.id,expectedRevision:0,operationId:op()});const token=await topicNameToken(s,'Alpha Object');assert.equal((await s.repository.transaction(false,t=>topicNameFence(t,token))).blocked,true);await s.foundationWrite(async t=>s.libraryCommit.organize(t,await s.readableEntry(t,e.id),{newTopic:'Alpha Object'},{topicMap:{},sectionMap:{}},'ai',op(),token,null));assert.equal((await rows(s,'topics')).length,1);
});
test('TOPIC-01 legacy merge registers the old normalized name and survives Undo/redo',async()=>{
 const {s}=await setup(OrganizerStore),a=await topic(s,'Alpha　Object'),b=await topic(s,'Survivor');await s.foundationWrite(async t=>{const row=await t.get('topics',a.id);delete row.identity;await t.put('topics',row);for(const meta of await t.all('meta'))if(meta.id.startsWith('personalTopicName:')&&meta.topicIds.includes(a.id))await t.delete('meta',meta.id);});await merge(s,a,b);await s.drainLibraryMaintenance();const token=await topicNameToken(s,'Alpha Object');assert.deepEqual((await s.repository.transaction(false,t=>topicNameFence(t,token))).ids,[b.id]);const rev=(await s.revisions({kind:'topic',entityId:b.id})).items.find(x=>x.reason==='merge');await s.restoreRevision({id:rev.id,side:'before',expectedRevision:(await s.topic(b.id)).revision,operationId:op()});await s.restoreRevision({id:rev.id,side:'after',expectedRevision:(await s.topic(b.id)).revision,operationId:op()});assert.deepEqual((await s.repository.transaction(false,t=>topicNameFence(t,token))).ids,[b.id]);
});
