import test from 'node:test';
import assert from 'node:assert/strict';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const releaseRoot=mkdtempSync(join(tmpdir(),'paia-dvn-search-release-'));
test.after(()=>rmSync(releaseRoot,{recursive:true,force:true}));
console.log(execFileSync('python3',['scripts/build_current_release.py',releaseRoot],{encoding:'utf8'}));
const rpc=async(page,type,fields={})=>{const reply=await page.evaluate(message=>chrome.runtime.sendMessage(message),{type,...fields});assert.equal(reply?.ok,true,JSON.stringify(reply));return reply.data;};
for(const variant of ['source','release']){
 test(`D1 single real ScopeSearch keeps independent root/Reader query, full-domain long-text match and Back/Forward/reload boundaries (${variant})`,{timeout:120000},async()=>{
  const h=await FakeChatGPT.start(variant==='release'?{extensionPath:releaseRoot}:{}),p=h.archive;
  try{
   await p.locator('#consent-check').check();await p.locator('#enable-consent').click();
   const long='SYNTHETIC long expression 中文 👩‍💻 é. '.repeat(700)+'SYNTHETIC_TAIL_ONLY exact ending';
   await h.open({id:'dvn-search-a',title:'SYNTHETIC Archive A',base:1609459200,messages:Array.from({length:141},(_,i)=>({id:'search-a-'+i,text:i===140?long:i===0?'SYNTHETIC_ROOT_ONLY original expression':'SYNTHETIC expression '+i}))});
   await h.open({id:'dvn-search-b',title:'SYNTHETIC Archive B',base:1609459300,messages:[{id:'search-b-0',text:'SYNTHETIC_OTHER_DOCUMENT_ONLY'}]});
   await eventually(async()=>(await h.state()).records.length===142,'all real worker Inputs captured');await rpc(p,'SET_ENABLED',{enabled:false});const original=(await h.state()).records;
   await p.evaluate(()=>globalThis.__scopeSearchNode=document.getElementById('scope-search'));
   assert.equal(await p.locator('#scope-search').count(),1);assert.equal(await p.locator('#search,#document-search').count(),0,'retired Archive inputs are absent, not hidden');
   await p.locator('#scope-search').fill('SYNTHETIC_ROOT_ONLY');await eventually(()=>p.locator('.search-input').count().then(n=>n===1));
   assert.equal(await p.evaluate(()=>JSON.stringify(history.state).includes('SYNTHETIC_ROOT_ONLY')),false,'typed query is outside browser history');assert.equal(await p.evaluate(()=>location.search+location.hash),'');
   await p.locator('.search-input').click();await eventually(()=>p.locator('#document-panel').isVisible());assert.equal(await p.locator('#scope-search').inputValue(),'','Reader starts with its own query');
   const doc=await p.evaluate(()=>history.state.paiaReader.documentId);assert.ok(doc);const mounted=await p.locator('.library-prose').allTextContents();assert.equal(mounted.some(s=>s.includes('SYNTHETIC_TAIL_ONLY')),false,'tail starts unmounted');
   await p.locator('#scope-search').fill('SYNTHETIC_OTHER_DOCUMENT_ONLY');await eventually(()=>p.locator('#document-search-status').textContent().then(s=>/没有匹配|No matching/.test(s)));assert.equal(await p.locator('.document-search-hit').count(),0,'other Conversation cannot leak into this Reader');
   await p.locator('#scope-search').fill('SYNTHETIC_TAIL_ONLY');await eventually(()=>p.locator('.document-search-hit').count().then(n=>n===1));await p.locator('.document-search-hit').click();
   await eventually(()=>p.locator('.library-prose').allTextContents().then(rows=>rows.includes(long)),'full exact long Input is reachable, not a clipped result');await eventually(()=>p.evaluate(async()=>{const {firstLexicalRange}=await import('./search-experience.js');const field=[...document.querySelectorAll('.library-prose')].find(el=>el.textContent.includes('SYNTHETIC_TAIL_ONLY'));const rect=firstLexicalRange(field,'SYNTHETIC_TAIL_ONLY')?.getBoundingClientRect();return rect&&rect.top>0&&rect.bottom<innerHeight;}),'actual tail match is revealed');
   assert.equal(await p.locator('input[type="search"]:visible').count(),1);assert.equal(await p.evaluate(()=>document.getElementById('scope-search')===globalThis.__scopeSearchNode),true,'same DOM input across scope changes');
   await p.locator('#back').click();await eventually(()=>p.locator('#collection-panel').isVisible());await eventually(()=>p.locator('#scope-search').isEnabled());assert.equal(await p.locator('#scope-search').inputValue(),'SYNTHETIC_ROOT_ONLY');assert.equal(await p.locator('.document-search-hit').count(),0,'inactive Search derivatives are cleared from DOM');
   await p.evaluate(()=>history.back());await eventually(()=>p.locator('#document-panel').isVisible());await eventually(()=>p.locator('#scope-search').isEnabled());assert.equal(await p.locator('#scope-search').inputValue(),'SYNTHETIC_TAIL_ONLY');assert.equal(await p.evaluate(()=>history.state.paiaReader.documentId),doc);
   await eventually(()=>p.locator('.document-search-hit').count().then(n=>n===1),'Reader query restores with a fresh search page');assert.equal(await p.evaluate(()=>JSON.stringify(history.state).includes('SYNTHETIC_TAIL_ONLY')),false);
   await p.evaluate(()=>history.forward());await eventually(()=>p.locator('#collection-panel').isVisible());await eventually(()=>p.locator('#scope-search').isEnabled());assert.equal(await p.locator('#scope-search').inputValue(),'SYNTHETIC_ROOT_ONLY');
   await p.evaluate(()=>history.back());await eventually(()=>p.locator('#document-panel').isVisible());await eventually(()=>p.locator('#scope-search').isEnabled());
   await p.reload();await eventually(()=>p.locator('#document-panel').isVisible());await eventually(()=>p.locator('#scope-search').isEnabled());assert.equal(await p.evaluate(()=>history.state.paiaReader.documentId),doc);assert.equal(await p.locator('#scope-search').inputValue(),'','reload loses transient query, retains admitted identity');assert.deepEqual((await h.state()).records,original);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  }catch(error){console.error('D1_SCOPE_FAILURE',variant,JSON.stringify(await p.evaluate(async()=>{const {firstLexicalRange}=await import('./search-experience.js');const field=[...document.querySelectorAll('.library-prose')].find(el=>el.textContent.includes('SYNTHETIC_TAIL_ONLY')),r=firstLexicalRange(field,'SYNTHETIC_TAIL_ONLY')?.getBoundingClientRect();return {route:history.state?.paiaReader,query:document.getElementById('scope-search')?.value,busy:document.getElementById('scope-search')?.disabled,collectionHidden:document.getElementById('collection-panel').hidden,readerHidden:document.getElementById('document-panel').hidden,rootResults:document.querySelectorAll('.search-input').length,resultCount:document.getElementById('result-count').textContent,searchStatus:document.getElementById('document-search-status').textContent,pageError:document.getElementById('error').textContent,fieldClass:field?.className,fieldHeight:field?.getBoundingClientRect().height,match:r?{top:r.top,bottom:r.bottom,height:r.height}:null,scroll:scrollY,height:innerHeight,scrollHeight:document.scrollingElement.scrollHeight};})),JSON.stringify(h.errors));throw error;}finally{await h.close();}
 });
 test(`D1 search scope waits for actual navigation; late Reader response clears safely; editing/IME shortcuts retain native ownership (${variant})`,{timeout:90000},async()=>{
  const h=await FakeChatGPT.start(variant==='release'?{extensionPath:releaseRoot}:{}),p=h.archive;
  try{
   await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await h.open({id:'dvn-search-race',title:'SYNTHETIC Scope race',base:1609459200,messages:[{id:'dvn-search-race-000',text:'SYNTHETIC_RACE_ROOT source'},{id:'dvn-search-race-001',text:'SYNTHETIC_STALE source'}]});await eventually(async()=>(await h.state()).records.length===2);await p.bringToFront();await p.locator('#primary-nav [data-view="library"]').click();await eventually(()=>p.locator('#scope-search').isEnabled(),'actual Archive route is ready before Search intent');await p.locator('#scope-search').evaluate(el=>{globalThis.__beforeSearchComposition=history.state.paiaReader.sessionKey;el.value='SYNTHETIC_RACE_ROOT';el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,data:'synthetic'}));});assert.equal(await p.evaluate(()=>JSON.stringify(history.state).includes('SYNTHETIC_RACE_ROOT')),false);assert.equal(await p.locator('.search-input').count(),0,'partial Search composition does not publish a query');await p.locator('#scope-search').evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await eventually(()=>p.locator('.search-input').count().then(n=>n===1),'Search final composition is admitted even without a following input event');await p.locator('.search-input').click();await eventually(()=>p.locator('.library-prose').first().isVisible());
   const field=p.locator('.library-prose').first();await field.focus();
   assert.deepEqual(await field.evaluate(el=>['f','k','/'].map(key=>{const event=new KeyboardEvent('keydown',{key,ctrlKey:key!=='/',bubbles:true,cancelable:true});el.dispatchEvent(event);return {key,prevented:event.defaultPrevented,retained:document.activeElement===el};})),[{key:'f',prevented:false,retained:true},{key:'k',prevented:false,retained:true},{key:'/',prevented:false,retained:true}]);
   await field.evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));const event=new KeyboardEvent('keydown',{key:'k',ctrlKey:true,isComposing:true,keyCode:229,bubbles:true,cancelable:true});el.dispatchEvent(event);globalThis.__imeFindOwnership={prevented:event.defaultPrevented,retained:document.activeElement===el};el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));});assert.deepEqual(await p.evaluate(()=>globalThis.__imeFindOwnership),{prevented:false,retained:true});
   await p.evaluate(()=>{globalThis.__scopeRace={started:false,root:false,done:false};const send=chrome.runtime.sendMessage.bind(chrome.runtime);chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='SEARCH_INPUTS'&&message.options?.mode==='current'&&message.options.query==='SYNTHETIC_STALE'){__scopeRace.started=true;await new Promise(resolve=>globalThis.__releaseOldSearch=resolve);__scopeRace.done=true;}if(message.type==='GET_PAGE'&&message.page.view==='settings'&&Object.hasOwn(message.page,'documentId')&&message.page.documentId===null&&globalThis.__holdRoot&&__scopeRace.root===false){__scopeRace.root=true;await new Promise(resolve=>globalThis.__releaseRoot=resolve);}return result;};});
   await p.locator('#scope-search').fill('SYNTHETIC_STALE');await eventually(()=>p.evaluate(()=>__scopeRace.started));await p.evaluate(()=>{globalThis.__holdRoot=true;document.getElementById('back').click();});await eventually(()=>p.evaluate(()=>__scopeRace.root));assert.equal(await p.locator('#scope-search').isDisabled(),true,'same input cannot target old Reader while root navigation is pending');
   await p.evaluate(()=>__releaseRoot());await eventually(()=>p.locator('#collection-panel').isVisible());await eventually(()=>p.locator('#scope-search').isEnabled());assert.equal(await p.locator('#scope-search').inputValue(),'SYNTHETIC_RACE_ROOT');await p.locator('#scope-search').fill('SYNTHETIC_RACE_ROOT source');await eventually(()=>p.locator('.search-input').count().then(n=>n===1));
   await p.evaluate(()=>__releaseOldSearch());await eventually(()=>p.evaluate(()=>__scopeRace.done));assert.equal(await p.locator('#scope-search').inputValue(),'SYNTHETIC_RACE_ROOT source');assert.equal(await p.locator('.document-search-hit').count(),0);assert.equal(await p.locator('#document-search-tools').isVisible(),false);assert.equal(await p.locator('.search-input').count(),1);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  }catch(error){console.error('D1_SCOPE_FAILURE',variant,JSON.stringify(await p.evaluate(async()=>{const {firstLexicalRange}=await import('./search-experience.js');const field=[...document.querySelectorAll('.library-prose')].find(el=>el.textContent.includes('SYNTHETIC_TAIL_ONLY')),r=firstLexicalRange(field,'SYNTHETIC_TAIL_ONLY')?.getBoundingClientRect();return {route:history.state?.paiaReader,query:document.getElementById('scope-search')?.value,busy:document.getElementById('scope-search')?.disabled,collectionHidden:document.getElementById('collection-panel').hidden,readerHidden:document.getElementById('document-panel').hidden,rootResults:document.querySelectorAll('.search-input').length,resultCount:document.getElementById('result-count').textContent,searchStatus:document.getElementById('document-search-status').textContent,pageError:document.getElementById('error').textContent,fieldClass:field?.className,fieldHeight:field?.getBoundingClientRect().height,match:r?{top:r.top,bottom:r.bottom,height:r.height}:null,scroll:scrollY,height:innerHeight,scrollHeight:document.scrollingElement.scrollHeight};})),JSON.stringify(h.errors));throw error;}finally{await h.close();}
 });
}
