import {tmpdir} from 'node:os';
import {chooseConsumerGroup} from './harness/settings-consumer-presentation.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {join} from 'node:path';import {mkdir,writeFile,readFile,mkdtemp,rm} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';import {routeComposer,isolated} from './harness/prompt-composer.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),url='https://chatgpt.com/c/prompt-insertion-fixture',out=join(root,'work/prompt-next');
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
for(const variant of ['source','release'])test('Stage 3A-1 '+variant+' production direct loop',{timeout:180000},async t=>{
 const releasePath=variant==='release'?await mkdtemp(join(tmpdir(),'paia-next-settings-')):null;
 if(releasePath)execFileSync('python3',['scripts/build_current_release.py',releasePath],{cwd:root,stdio:'pipe'});
 const h=await FakeChatGPT.start({extensionPath:releasePath||root,headless:process.env.PAIA_HEADLESS!=='0',launchThroughPort:true,nativeTabVisibility:true});await mkdir(out,{recursive:true});let page,popup,world,failures=0;const cases=[],screens=[],diagnostics=[];
 const check=async(name,fn)=>{await t.test(name,async()=>{try{await fn();cases.push({name,status:'PASS'});}catch(e){failures++;cases.push({name,status:'FAIL'});throw e;}});if(failures)throw Error('Stage3 fixture stopped after failing '+name);};
 try{
  await h.archive.locator('#consent-check').check();await h.archive.locator('#enable-consent').click();
  popup=await h.context.newPage();await popup.goto('chrome-extension://'+h.extensionId+'/ui/popup.html');await popup.locator('#next-enabled').waitFor();
  await routeComposer(h.context,root);page=await h.context.newPage();page.on('pageerror',error=>h.errors.push(error.message));await page.exposeFunction('__traceNextNative',value=>diagnostics.push({at:Date.now(),...value}));page.on('framedetached',f=>diagnostics.push({at:Date.now(),event:'frame-detached',url:f.url()}));await page.goto(url);await page.evaluate(()=>document.addEventListener('visibilitychange',()=>void __traceNextNative({event:'visibility',hidden:document.hidden})));await page.waitForFunction(()=>!!globalThis.fixture?.view);await page.setViewportSize({width:1280,height:900});
  await page.addStyleTag({content:'body{margin:0;min-height:100vh;background:#f6f7fb}form{position:fixed;left:16px;right:16px;bottom:16px;padding:12px;border:1px solid #aaa;background:white}article{margin:16px 80px;padding:12px}#blur{position:fixed;top:8px;left:8px}@media(prefers-color-scheme:dark){body{background:#1f1f1f;color:#eee}form{background:#292929}}'});
  await page.evaluate(()=>{
   fixture.round=0;fixture.reply=(id,text,copy)=>{const article=document.createElement('article');article.dataset.testid='conversation-turn-'+id;const node=document.createElement('div');node.dataset.messageAuthorRole='assistant';node.dataset.messageId=id;const body=document.createElement('div');body.className='markdown';const p=document.createElement('p');p.textContent=text;body.append(p);node.append(body);article.append(node);if(copy){const b=document.createElement('button');b.dataset.testid='copy-turn-action-button';b.textContent='Copy';article.append(b);}document.querySelector('main').prepend(article);return article;};
   fixture.history=document.createElement('section');fixture.history.id='reply-history';document.querySelector('main').prepend(fixture.history);
   fixture.user=()=>{const n=document.createElement('div');n.dataset.messageAuthorRole='user';n.dataset.messageId='next-user-'+fixture.round;n.textContent='Synthetic user';fixture.history.append(n);};
   fixture.user();fixture.history.append(fixture.reply('old-final','回复“继续”',true));
   fixture.start=(text='回复“继续”')=>{fixture.round++;fixture.user();const stop=document.createElement('button');stop.dataset.testid='stop-button';stop.textContent='Stop';document.querySelector('form').append(stop);fixture.latest=fixture.reply('next-reply-'+fixture.round,text,false);fixture.history.append(fixture.latest);};
   fixture.finish=()=>{document.querySelector('[data-testid="stop-button"]')?.remove();const copy=document.createElement('button');copy.dataset.testid='copy-turn-action-button';copy.textContent='Copy';fixture.latest.append(copy);};
  });
  await page.locator('[data-paia-prompt-surface]').waitFor({state:'visible'});world=await isolated(page,h.extensionId);
  await world.run('globalThis.nextReads=0;globalThis.originalSnapshot=PAIAChatGPTCurrentReplyAdapter.prototype.snapshot;PAIAChatGPTCurrentReplyAdapter.prototype.snapshot=function(){nextReads++;return originalSnapshot.call(this);};');
  await world.run(`globalThis.nextTrace=[];globalThis.nextObserve=null;const oldObserve=PAIAChatGPTCurrentReplyAdapter.prototype.observe;PAIAChatGPTCurrentReplyAdapter.prototype.observe=function(...args){const out=oldObserve.apply(this,args);nextObserve={armed:this.armed,seenIdle:this.seenIdle,streaming:this.streaming,finalized:this.finalized,hasCycleReply:!!this.cycleReplyId,ready:out.ready,hasBinding:!!out.binding};return out;};const oldSend=chrome.runtime.sendMessage.bind(chrome.runtime);chrome.runtime.sendMessage=async request=>{const r=await oldSend(request);if(request.type?.startsWith('PAIA_PROMPT_NEXT_')){nextTrace.push({type:request.type,ok:r?.ok,error:r?.error,available:r?.data?.available,safe:r?.data?.safe,enabled:r?.data?.enabled,reason:r?.data?.reason});if(nextTrace.length>30)nextTrace.shift();}return r;};`);
  const capsule=()=>page.frames().find(f=>f.url().includes('/ui/prompt-surface.html#next-'));
  const card=()=>page.frames().find(f=>/\/ui\/prompt-surface\.html#[a-f0-9-]+$/.test(f.url()));
  const enable=async()=>{await popup.bringToFront();await popup.locator('#next-enabled').check();await eventually(async()=>(await rpc(popup,'PAIA_PROMPT_NEXT_STATUS')).enabled===true);await page.bringToFront();await page.waitForTimeout(150);};
  const disable=async()=>{await popup.bringToFront();await popup.locator('#next-enabled').uncheck();await eventually(async()=>(await rpc(popup,'PAIA_PROMPT_NEXT_STATUS')).enabled===false);await page.bringToFront();await eventually(()=>!capsule());};
  const cycle=async(text='回复“继续”')=>{await page.evaluate(x=>fixture.start(x),text);await page.waitForTimeout(120);await page.evaluate(()=>fixture.finish());};
  const shown=async()=>{try{await eventually(()=>!!capsule(),'new final reply produces capsule');}catch(error){throw Error(error.message+' '+JSON.stringify(await world.run('({reads:nextReads,observed:nextObserve,trace:nextTrace})')));}await capsule().locator('.next-choices button').first().waitFor();return capsule();};
  await check('OFF and enable are prospective with zero historical snapshot reads',async()=>{
   assert.equal((await rpc(popup,'PAIA_PROMPT_NEXT_STATUS')).enabled,false);await cycle();await page.waitForTimeout(1800);assert.equal(await world.run('nextReads'),0);assert.equal(capsule(),undefined);await enable();await page.waitForTimeout(1000);assert.equal(await world.run('nextReads'),0);assert.equal(capsule(),undefined);
  });
  await check('streaming silence cannot complete; direct conditional insert preserves selection and never sends',async()=>{
   await page.evaluate(()=>fixture.set('ABCDE',1,4));await page.evaluate(()=>fixture.start('登录完成后告诉我“已登录”。'));await page.waitForTimeout(1800);assert.equal(await world.run('nextReads'),0);assert.equal(capsule(),undefined);
   await page.evaluate(()=>fixture.finish());const f=await shown();assert.equal(await f.locator('.next-condition').textContent(),'登录后');const orb=await page.locator('[data-paia-prompt-surface]').boundingBox();await page.screenshot({path:join(out,variant+'-conditional-light.png')});screens.push(variant+'-conditional-light.png');
   await f.evaluate(()=>{window.__clickTrace=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,e=>__clickTrace.push({type,trusted:e.isTrusted,target:e.target.tagName,disabled:e.target.disabled,x:e.clientX,y:e.clientY}),true);const send=chrome.runtime.sendMessage.bind(chrome.runtime);chrome.runtime.sendMessage=async(...args)=>{const request=args[0],start=performance.now();const result=await send(...args);if(request.type==='PAIA_PROMPT_NEXT_RPC')await window.__traceNextNative({event:'private-rpc',command:request.command?.type,elapsed:performance.now()-start,ok:result?.ok,error:result?.error,status:result?.data?.status,verified:result?.data?.verified});return result;};const status=document.querySelector('.next-status');new MutationObserver(()=>void window.__traceNextNative({event:'status',text:status.textContent})).observe(status,{childList:true,subtree:true,characterData:true});});
   diagnostics.push({at:Date.now(),event:'before-insert',authorization:await rpc(popup,'PAIA_PROMPT_NEXT_STATUS')});
   const clickBox=await f.getByRole('button',{name:'已登录',exact:true}).boundingBox();diagnostics.push({event:'click-geometry',button:clickBox,frame:await(await f.frameElement()).boundingBox(),top:await page.evaluate(b=>{window.__topClicks=[];for(const type of ['pointerdown','pointerup','click'])document.addEventListener(type,e=>__topClicks.push({type,trusted:e.isTrusted,target:e.target.tagName,path:e.composedPath().map(n=>n.tagName||n.nodeName||'window'),x:e.clientX,y:e.clientY}),true);return {hit:document.elementFromPoint(b.x+b.width/2,b.y+b.height/2)?.outerHTML,innerWidth,innerHeight,scrollX,scrollY};},clickBox)});
   diagnostics.push({event:'frame-computed',value:await(await f.frameElement()).evaluate(n=>{const c=getComputedStyle(n),r=n.getBoundingClientRect();return {pointerEvents:c.pointerEvents,visibility:c.visibility,zIndex:c.zIndex,display:c.display,rect:{x:r.x,y:r.y,width:r.width,height:r.height},outer:n.outerHTML};})});
   const hitCDP=await h.context.newCDPSession(page);try{const hit=await hitCDP.send('DOM.getNodeForLocation',{x:Math.round(clickBox.x+clickBox.width/2),y:Math.round(clickBox.y+clickBox.height/2),includeUserAgentShadowDOM:true});const described=await hitCDP.send('DOM.describeNode',{backendNodeId:hit.backendNodeId,depth:0,pierce:true});diagnostics.push({event:'cdp-hit',hit,node:described.node,browser:await hitCDP.send('Browser.getVersion'),chromePath:process.env.CHROME_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':'harness Chromium default'),platform:process.platform});}finally{await hitCDP.detach();}
   await f.getByRole('button',{name:'已登录',exact:true}).click();diagnostics.push({at:Date.now(),event:'after-native-click',frame:await f.evaluate(()=>({events:__clickTrace,status:document.querySelector('.next-status').textContent,activeTag:document.activeElement?.tagName,body:document.body.className})),topEvents:await page.evaluate(()=>__topClicks),errors:[...h.errors]});await eventually(()=>f.locator('.next-status').textContent().then(x=>x==='已插入，未发送。'));assert.equal(await page.evaluate(()=>fixture.text()),'ABCD已登录E');assert.equal(await page.evaluate(()=>fixture.send),0);assert.equal(await page.evaluate(()=>document.activeElement.id),'prompt-textarea');assert.deepEqual(await page.locator('[data-paia-prompt-surface]').boundingBox(),orb);
   assert.equal(await f.getByRole('button',{name:'复制',exact:true}).count(),0);await eventually(()=>!capsule(),'success retracts');
  });
  await check('choice peers preserve exact option meaning and do not preselect',async()=>{
   await cycle('A. 概要\nB. 详细说明\nC. 比较\n请回复 A / B / C。');const f=await shown();assert.deepEqual(await f.locator('.next-choices button').allTextContents(),['A · 概要','B · 详细说明','C · 比较']);assert.equal(await f.locator('.next-choices button:focus').count(),0);assert.equal(await page.evaluate(()=>fixture.text()),'ABCD已登录E');await f.getByRole('button',{name:'收起本轮建议'}).click();await eventually(()=>!capsule());
   await page.locator('[data-paia-prompt-surface]').click();await eventually(()=>!!card());await card().getByRole('button',{name:'本轮建议'}).waitFor({state:'visible'});await card().getByRole('button',{name:'本轮建议'}).click();await shown();await capsule().getByRole('button',{name:'B · 详细说明',exact:true}).click();await eventually(()=>capsule()?.locator('.next-status').textContent().then(x=>x==='已插入，未发送。'));assert.equal(await page.evaluate(()=>fixture.text()),'ABCD已登录BE');await eventually(()=>!capsule());await card().locator('#close').click();await eventually(()=>!card());
  });
  await check('actual saved Family match inserts original text and rejects changed eligibility',async()=>{
   const q=await rpc(popup,'PAIA_PROMPT_QUERY',{includeHidden:true});
   const saved=await rpc(popup,'PAIA_PROMPT_CHANGE',{change:{action:'create',revision:q.revision,text:'Explain sorting'}});
   await rpc(popup,'PAIA_PROMPT_QUERY',{includeHidden:true});await page.evaluate(()=>fixture.set('FAMILY_DRAFT',12,12));
   await cycle('Next, ask me to explain sorting.');const f=await shown();
   assert.equal(await f.locator('.next-capsule').getAttribute('aria-label'),'来自常用 Prompt 的本轮建议');assert.equal(await(await f.frameElement()).getAttribute('title'),'来自常用 Prompt 的本轮建议');
   await f.getByRole('button',{name:'Explain sorting',exact:true}).click();await eventually(()=>f.locator('.next-status').textContent().then(x=>x==='已插入，未发送。'));
   assert.equal(await page.evaluate(()=>fixture.text()),'FAMILY_DRAFTExplain sorting');assert.equal(await page.evaluate(()=>fixture.send),0);await eventually(()=>!capsule());
   await rpc(popup,'PAIA_PROMPT_QUERY',{includeHidden:true});await cycle('Next, ask me to explain sorting.');const stale=await shown(),before=await page.evaluate(()=>fixture.text());
   const current=await rpc(popup,'PAIA_PROMPT_QUERY',{includeHidden:true});await rpc(popup,'PAIA_PROMPT_CHANGE',{change:{action:'hide',id:saved.id,revision:current.revision}});
   await stale.getByRole('button',{name:'Explain sorting',exact:true}).click();await eventually(()=>stale.locator('.next-status').textContent().then(x=>x.includes('未确认')||x.includes('无法安全插入')));
   assert.equal(await page.evaluate(()=>fixture.text()),before);assert.equal(await page.evaluate(()=>fixture.send),0);await stale.getByRole('button',{name:'收起本轮建议'}).click();await eventually(()=>!capsule());
  });
  await check('actual Settings revocation hides the candidate and rejects a held native insertion',async()=>{
   const settings=h.archive;await settings.bringToFront();await settings.locator('.sidebar-bottom [data-view="settings"]').click();await chooseConsumerGroup(settings,'ai');
   const toggle=settings.locator('#settings-next-enabled');await eventually(async()=>await toggle.isChecked()&&!await toggle.isDisabled(),'Settings reads the existing enabled session');
   await page.bringToFront();await page.evaluate(()=>fixture.set('SETTINGS_REVOKE_DRAFT',21,21));await cycle();const f=await shown(),before=await page.evaluate(()=>fixture.text());
   await world.run(`globalThis.settingsHeldStatus=false;globalThis.settingsInsertSeen=false;globalThis.settingsInsertTrace=r=>{if(r.type==='PAIA_PROMPT_NEXT_INSERT')settingsInsertSeen=true;};chrome.runtime.onMessage.addListener(settingsInsertTrace);globalThis.settingsInsertCompleted=false;globalThis.settingsOriginalSend=chrome.runtime.sendMessage;chrome.runtime.sendMessage=async request=>{if(request.type==='PAIA_PROMPT_NEXT_STATUS'&&!settingsHeldStatus){settingsHeldStatus=true;await new Promise(resolve=>globalThis.releaseSettingsStatus=resolve);try{return await settingsOriginalSend(request);}finally{settingsInsertCompleted=true;}}return settingsOriginalSend(request);};`);
   try{
    await f.getByRole('button',{name:'继续',exact:true}).click();await eventually(()=>world.run('settingsHeldStatus&&settingsInsertSeen'),'native insertion reaches its final authorization read');
    await settings.bringToFront();await toggle.click();await eventually(async()=>!await toggle.isChecked()&&!await toggle.isDisabled(),'actual Settings owner confirms revocation');
    assert.equal((await rpc(settings,'PAIA_PROMPT_NEXT_STATUS')).enabled,false);await eventually(()=>!capsule(),'revocation and hidden source remove the transient frame');
    await world.run('releaseSettingsStatus()');await eventually(()=>world.run('settingsInsertCompleted'),'held authorization read completes after revocation');
    await page.bringToFront();assert.equal(await page.evaluate(()=>fixture.text()),before);assert.equal(await page.evaluate(()=>fixture.send),0);assert.equal(capsule(),undefined);
   }finally{await world.run('releaseSettingsStatus?.();chrome.runtime.sendMessage=settingsOriginalSend;chrome.runtime.onMessage.removeListener(settingsInsertTrace);');}
   await enable();assert.equal(capsule(),undefined,'reenabling does not revive the revoked candidate');
  });
  await check('late availability response cannot resurrect the invalidated current-reply entry',async()=>{
   await cycle();const suggestion=await shown();await suggestion.getByRole('button',{name:'收起本轮建议'}).click();await eventually(()=>!capsule());
   await page.locator('[data-paia-prompt-surface]').click();await eventually(()=>!!card());const frame=card();await eventually(()=>frame.locator('#next-reopen').isVisible());
   const composerBefore=await page.evaluate(()=>fixture.text());
   await frame.evaluate(()=>{const original=chrome.runtime.sendMessage;globalThis.__availabilityRace={original,held:false,later:false,finished:false,release:null};chrome.runtime.sendMessage=async function(message,...args){const response=await original.call(this,message,...args);if(message.type==='PAIA_PROMPT_SURFACE_RPC'&&message.command?.type==='next_available'){if(!__availabilityRace.held&&response?.data?.available===true){__availabilityRace.held=true;await new Promise(resolve=>__availabilityRace.release=resolve);__availabilityRace.finished=true;}else if(__availabilityRace.held&&response?.data?.available===false)__availabilityRace.later=true;}return response;};});
   try{
    // A real completed reply makes the worker broadcast the trusted change.
    // This fixture's extension popup page has sender.tab and fails the UI guard.
    await cycle();await eventually(()=>frame.evaluate(()=>__availabilityRace.held),'new real candidate availability is held');
    await page.evaluate(()=>fixture.latest.querySelector('p').textContent='Synthetic changed completed reply');
    await eventually(()=>frame.evaluate(()=>__availabilityRace.later),'real newer unavailable response arrives');await eventually(()=>frame.locator('#next-reopen').isHidden());
    await frame.evaluate(async()=>{__availabilityRace.release();await new Promise(resolve=>setTimeout(resolve,0));if(!__availabilityRace.finished)throw Error('Held response was not delivered');});
    assert.equal(await frame.locator('#next-reopen').isHidden(),true,'older actual available reply cannot resurrect invalidated entry');assert.equal(card(),frame);assert.equal(await page.evaluate(()=>fixture.text()),composerBefore);assert.equal(await page.evaluate(()=>fixture.send),0);
   }finally{await frame.evaluate(()=>{__availabilityRace.release?.();chrome.runtime.sendMessage=__availabilityRace.original;});}
   await frame.locator('#close').click();await eventually(()=>!card());
  });
  await check('actual Settings position reset preserves unsaved card and respects hidden-page Next invalidation',async()=>{
   const settings=h.archive;await settings.bringToFront();await eventually(()=>settings.evaluate(()=>!document.hidden),'Settings tab is visible before its native controls are used');await settings.locator('.sidebar-bottom [data-view="settings"]').click();await chooseConsumerGroup(settings,'ai');const reset=settings.locator('#settings-prompt-position-reset');await eventually(()=>reset.isEnabled());
   await page.bringToFront();await cycle();const nextFrame=await shown();
   await page.locator('[data-paia-prompt-surface]').click();await eventually(()=>!!card());const originalCard=card();await originalCard.locator('#new').click();const edit=originalCard.getByRole('textbox',{name:'复用文本'});await edit.fill('UNSAVED_STAGE3_SETTINGS 中文🙂');
   const cdp=await h.context.newCDPSession(page);try{await edit.focus();await cdp.send('Input.imeSetComposition',{text:'汉',selectionStart:1,selectionEnd:1});await cdp.send('Input.insertText',{text:'汉'});}finally{await cdp.detach();}
   // Native composition is completed before a real cross-tab Settings click.
   // This asserts composed draft bytes, not uninterrupted cross-tab composition.
   const draft=await edit.inputValue();assert.match(draft,/UNSAVED_STAGE3_SETTINGS/);assert.match(draft,/汉/);
   const saved=()=>popup.evaluate(async()=> (await chrome.storage.local.get('promptSurfaceV1')).promptSurfaceV1);
   await eventually(async()=>(await saved())?.open===true);const before=await saved(),families=await rpc(popup,'PAIA_PROMPT_QUERY',{includeHidden:true}),composerBefore=await page.evaluate(()=>fixture.text());
   await settings.bringToFront();await eventually(()=>page.evaluate(()=>document.hidden),'source document is actually hidden before Next invalidation');diagnostics.push({event:'settings-source-hidden',value:await page.evaluate(()=>({hidden:document.hidden,focus:document.hasFocus()}))});await eventually(()=>!capsule(),'hidden source invalidates the transient Next candidate');assert.equal(nextFrame.isDetached(),true);await reset.click();await eventually(async()=>{const after=await saved();return after.position===null&&after.positionGeneration===(before.positionGeneration??0)+1;});
   assert.equal(card(),originalCard,'reset retains original unsaved editor Frame');assert.equal(await edit.inputValue(),draft);assert.equal((await saved()).open,true);assert.deepEqual(await rpc(popup,'PAIA_PROMPT_QUERY',{includeHidden:true}),families,'unsaved draft never becomes a durable Prompt');
   assert.equal(capsule(),undefined,'reset cannot resurrect the hidden-page candidate');assert.equal(await page.evaluate(()=>fixture.text()),composerBefore);assert.equal(await page.evaluate(()=>fixture.send),0);
   await page.bringToFront();await eventually(()=>page.evaluate(()=>!document.hidden),'source document is visible after returning');diagnostics.push({event:'settings-source-returned',value:await page.evaluate(()=>({hidden:document.hidden,focus:document.hasFocus()}))});assert.equal(await edit.inputValue(),draft);await originalCard.getByRole('button',{name:'取消',exact:true}).click();await eventually(async()=>!await originalCard.getByRole('button',{name:'本轮建议'}).isVisible(),'invalidated candidate cannot be reopened after returning');assert.equal(capsule(),undefined);await originalCard.locator('#close').click();await eventually(()=>!card());
  });
  await check('revision, regenerate, continue, new user and revoke invalidate stale candidates',async()=>{
   await cycle();await shown();await page.evaluate(()=>fixture.latest.querySelector('p').textContent='回复“停止”');await eventually(()=>!capsule());
   // Mutation alone cannot create a new completion cycle/recommendation.
   await page.waitForTimeout(1800);assert.equal(capsule(),undefined);
   await cycle();await shown();await page.evaluate(()=>{const button=document.createElement('button');button.dataset.testid='continue-button';button.textContent='Continue';fixture.latest.append(button);});await eventually(()=>!capsule());await page.evaluate(()=>fixture.latest.querySelector('[data-testid="continue-button"]').remove());
   await cycle();await shown();await page.evaluate(()=>{fixture.round++;fixture.user();});await eventually(()=>!capsule());
   await cycle();await shown();await disable();const count=await world.run('nextReads');await cycle();await page.waitForTimeout(1600);assert.equal(await world.run('nextReads'),count);assert.equal(capsule(),undefined);await enable();assert.equal(capsule(),undefined);
  });
  await check('IME/edit busy skip auto display; valid suggestion can reopen after user is idle',async()=>{
   await page.locator('[data-paia-prompt-surface]').click();await eventually(()=>!!card());await card().locator('#new').click();await card().getByRole('textbox',{name:'复用文本'}).fill('unsaved Stage 1/2 draft');await cycle();await page.waitForTimeout(2000);assert.equal(capsule(),undefined);assert.equal(await card().getByRole('textbox',{name:'复用文本'}).inputValue(),'unsaved Stage 1/2 draft');await card().getByRole('button',{name:'取消',exact:true}).click();await card().getByRole('button',{name:'本轮建议'}).click();await shown();await capsule().getByRole('button',{name:'收起本轮建议'}).click();await eventually(()=>!capsule());await card().locator('#close').click();await eventually(()=>!card());
   await page.locator('#prompt-textarea').focus();const cdp=await h.context.newCDPSession(page);await cdp.send('Input.imeSetComposition',{text:'汉',selectionStart:1,selectionEnd:1});await cycle();await page.waitForTimeout(1900);assert.equal(capsule(),undefined);await cdp.send('Input.insertText',{text:'汉'});await cdp.detach();await page.waitForTimeout(900);assert.equal(capsule(),undefined,'no stale automatic queue');
  });
  await check('uncertain native edit is never retried and offers only explicit recovery',async()=>{
   // A native plain input, not fixture.set(), clears Chromium's conservative IME fence.
   await page.locator('#prompt-textarea').focus();await page.keyboard.type('x');await page.evaluate(()=>fixture.set('uncertain draft',15));await cycle();const f=await shown();await world.run('globalThis.originalExec=document.execCommand.bind(document);document.execCommand=(...args)=>{originalExec(...args);return false;};');const before=await page.evaluate(()=>fixture.text());await f.getByRole('button',{name:'继续',exact:true}).click();await eventually(()=>f.locator('.next-status').textContent().then(x=>x.includes('未确认')));assert.equal(await page.evaluate(()=>fixture.text()),before+'继续');await world.run('document.execCommand=originalExec;');assert.equal(await f.getByRole('button',{name:'继续',exact:true}).isDisabled(),true);assert.equal(await f.getByRole('button',{name:'复制',exact:true}).isVisible(),true);await f.getByRole('button',{name:'收起本轮建议'}).click();await eventually(()=>!capsule());
  });
  await check('private light/dark/compact capsule, 44px targets, no stored body, no model request',async()=>{
   for(const [theme,width]of [['light',1280],['dark',1280],['dark',320],['light',320]]){
    await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});await cycle('Tell me "done" when finished');const f=await shown();await eventually(()=>f.locator('html').getAttribute('data-theme').then(x=>x===theme));
    if(width===320){await f.evaluate(()=>document.documentElement.style.fontSize='28px');await page.waitForTimeout(120);}
    assert.ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await f.locator('.next-choices button').first().evaluate(n=>n.getBoundingClientRect().height>=44));assert.ok(await f.locator('.next-condition').isVisible());
    const frameBox=await (await f.frameElement()).boundingBox();assert.ok(frameBox.x+frameBox.width<=await page.evaluate(()=>document.documentElement.clientWidth)-8,'capsule avoids the native scrollbar gutter');const form=await page.locator('form').boundingBox();assert.ok(frameBox.y+frameBox.height<=form.y-8||frameBox.x+frameBox.width<=form.x-8||frameBox.x>=form.x+form.width+8);
    const name=variant+'-'+theme+'-'+width+'.png';await page.screenshot({path:join(out,name)});screens.push(name);await f.getByRole('button',{name:'收起本轮建议'}).click();await eventually(()=>!capsule());
   }
   const durable=await popup.evaluate(async()=>{
    const {OrganizerStore}=await import('../core/organizer/store.js'),{BackupService}=await import('../core/backup-service.js');const s=new OrganizerStore(chrome.storage.local);await s.finishFoundation();const names=[...s.repository.db.objectStoreNames];
    const snapshot=async()=>({local:await chrome.storage.local.get(null),rows:await s.repository.transaction(false,async t=>{const data={};for(const name of names)data[name]=await t.all(name);return data;},names),session:await chrome.storage.session.get(null)});
    const before=await snapshot();let exportError=null;try{await new BackupService(s).beginExport();}catch(error){exportError=error.code||String(error);}
    return {before,after:await snapshot(),exportError};
   });assert.equal(durable.exportError,'FEATURE_UNAVAILABLE','retired export remains unavailable');assert.deepEqual(durable.after,durable.before,'rejected export creates no durable or session state');assert.doesNotMatch(JSON.stringify(durable),/Tell me|when finished|登录完成后/);assert.deepEqual(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length})),{local:0,session:0});assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.equal(await page.evaluate(()=>fixture.send),0);
  });
  await check('worker restart recovers prospectively; Stage 1/2 still works after Stage 3 revoke',async()=>{
   await h.restartWorker();await cycle();await page.waitForTimeout(1700);assert.equal(capsule(),undefined,'restart loses old authority and current candidate');await cycle();await shown();await disable();
   await page.locator('[data-paia-prompt-surface]').click();await eventually(()=>!!card());await card().locator('#new').click();await card().getByRole('textbox',{name:'复用文本'}).fill('ordinary Stage 1/2');await card().getByRole('button',{name:'保存',exact:true}).click();await card().getByRole('button',{name:'ordinary Stage 1/2',exact:true}).click();await eventually(()=>card().locator('#status').textContent().then(x=>x==='已插入，未发送。'));assert.equal(await page.evaluate(()=>fixture.send),0);
  });
  assert.equal(failures,0);assert.deepEqual(h.errors,[]);
 }finally{if(world)try{diagnostics.push({event:'final-world',value:await world.run('({observed:nextObserve,trace:nextTrace})')});}catch(error){diagnostics.push({event:'final-world-unavailable',error:error.message});}await writeFile(join(out,variant+'-insert-diagnostic.json'),JSON.stringify(diagnostics,null,2));await writeFile(join(out,variant+'.json'),JSON.stringify({variant,evidence:'SYNTHETIC_PRODUCTION_EXTENSION',head:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),cases,screens,failures,currentLive:'PENDING'},null,2));await world?.cdp.detach();await h.close();if(releasePath)await rm(releasePath,{recursive:true,force:true});}
});
