import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
import {openArchiveWindow} from './harness/archive-navigator.mjs';
import {ready,rpc,nav,offline,record,compareCompose,installComposeDiagnostics,composeDiagnostics} from './harness/d5-compose-workspace.mjs';
const op=()=>crypto.randomUUID();
const compose=page=>page.locator('#thought-compose-panel');
const fields=page=>page.locator('#document-body [data-edit-id]');
const ids=page=>fields(page).evaluateAll(nodes=>nodes.filter(node=>!node.closest('.library-block').hidden).map(node=>node.dataset.editId));
async function withFixture(variant,name,run){
 const release=variant==='release'?await mkdtemp(join(tmpdir(),'paia-compose-route-')):null;if(release)execFileSync('python3',['scripts/build_current_release.py',release],{stdio:'pipe'});
 const h=await FakeChatGPT.start({onboarding:true,...(release?{extensionPath:release}:{})});let page,failure;const trace={variant,scenario:name,stage:'start'};
 try{page=await ready(h);await installComposeDiagnostics(page);await run(h,page,trace);offline(h);trace.stage='PASS';}
 catch(error){failure=error;trace.failure=error.message;trace.error={stack:error.stack,code:error.code,actual:error.actual,expected:error.expected,at:Date.now()};throw error;}
 finally{if(page)try{trace.diagnostics=await composeDiagnostics(page);trace.route=await page.evaluate(()=>history.state?.paiaReader);trace.visible=await compose(page).isVisible();await record(page,`${name}-${variant}`,trace);}catch(error){if(!failure)throw error;}try{await h.close();}catch(error){if(!failure)throw error;}finally{if(release)await rm(release,{recursive:true,force:true});}}
}
async function seedReader(h,page,count=125){
 await h.open({id:'synthetic-d5-return',title:'SYNTHETIC bounded Reader origin',base:1609459200,messages:Array.from({length:count},(_,index)=>({id:'synthetic-d5-input-'+index,text:`SYNTHETIC Input ${index} 原始记录 👩‍💻\n`+'这一段只属于合成浏览器回归，保存每一行。\n'.repeat(4)}))});await eventually(async()=>(await h.state()).records.length===count,'all synthetic Source captured');await page.bringToFront();await rpc(page,'SET_ORGANIZER_CONTROLS',{changes:{inputReadingSort:'asc'}});await openArchiveWindow(page,{label:'D5 compose Reader origin'});await fields(page).first().waitFor();return h.state();
}
async function reachReaderEnd(page,lastId){
 for(let step=0;step<8;step++){if((await ids(page)).includes(lastId))return;await page.evaluate(()=>{document.activeElement?.blur();getSelection().removeAllRanges();scrollTo(0,document.documentElement.scrollHeight);});await pause(200);}
 await eventually(async()=>(await ids(page)).includes(lastId),'bounded Reader reaches its final two pages');
}
async function fromReader(page,inputId){const field=page.locator(`[data-edit-id="${inputId}"]`);await field.click({button:'right'});await page.locator('#context-menu').getByRole('menuitem',{name:'接着写',exact:true}).click();await compose(page).getByRole('textbox',{name:'今天的新想法'}).waitFor();}
async function cancel(page){const draft=compose(page).getByRole('textbox',{name:'今天的新想法'});if((await draft.inputValue()).trim())page.once('dialog',dialog=>dialog.accept());await compose(page).getByRole('button',{name:'取消',exact:true}).click();await eventually(()=>compose(page).isHidden(),'compose returns through the existing history owner');}

for(const variant of ['source','release'])test(`D5 T05 workspace pixels, repeated navigation and expired references (${variant})`,{timeout:180000},()=>withFixture(variant,'workspace',async(h,page,trace)=>{
 await nav(page,'thoughts');const open=()=>page.locator('#thought-home-tools').getByRole('button',{name:'接着写',exact:true}).click();await open();const draft=compose(page).getByRole('textbox',{name:'今天的新想法'});await draft.waitFor();await compareCompose(h,variant);trace.matrix='10 paired widths/themes + actual coarse + 200% text';
 const original=await page.evaluate(()=>({route:history.state.paiaReader,historyLength:history.length}));trace.original=original;trace.stage='rejected Back';await draft.evaluate(node=>globalThis.__d5SameDraft=node);page.once('dialog',dialog=>dialog.dismiss());await page.goBack();assert.equal(await draft.evaluate(node=>node===__d5SameDraft),true);assert.equal(await draft.inputValue(),'我还没有确定结论。先把今天看到的变化留下来。');assert.equal(await compose(page).isVisible(),true);
 trace.stage='Escape return';page.once('dialog',dialog=>dialog.accept());await draft.press('Escape');await eventually(()=>compose(page).isHidden());assert.equal(await page.locator('#thought-panel').isVisible(),true);trace.stage='expired Forward';await page.goForward();await eventually(()=>page.locator('#thought-panel').isVisible());assert.equal(await compose(page).isHidden(),true);await page.getByText('这份未保存的临时草稿已关闭，请重新写下想法。',{exact:true}).waitFor();assert.equal((await rpc(page,'GET_LIBRARY_UNPLACED',{options:{}})).items.length,0);
 trace.stage='expired reload';await open();await draft.fill('SYNTHETIC unpersisted reload canary');page.once('dialog',dialog=>dialog.accept());await page.reload();await eventually(()=>page.locator('#thought-panel').isVisible());assert.equal(await compose(page).isHidden(),true);assert.equal((await rpc(page,'GET_LIBRARY_UNPLACED',{options:{}})).items.length,0);assert.equal(await page.locator('body').textContent().then(text=>text.includes('SYNTHETIC unpersisted reload canary')),false);trace.original=original;
}));

for(const variant of ['source','release'])test(`D5 deep Reader compose return uses fresh two-page authority, caret and existing Undo (${variant})`,{timeout:180000},()=>withFixture(variant,'reader-return',async(h,page,trace)=>{
 const initial=await seedReader(h,page),lastSource=initial.records.find(row=>row.sourceMessageId==='synthetic-d5-input-124'),last=initial.library.blocks.find(row=>row.sourceRecordId===lastSource.id);await reachReaderEnd(page,last.id);const beforeIds=await ids(page);assert.ok(beforeIds.length>40&&beforeIds.length<=80);const targetId=beforeIds.at(-8),otherId=beforeIds[0],target=page.locator(`[data-edit-id="${targetId}"]`),beforeTarget=await rpc(page,'GET_INPUT',{id:targetId});
 const authored='SYNTHETIC authored Reader 👩‍💻 é\nPreserve exact text and app Undo.';await target.fill(authored);await eventually(async()=>(await rpc(page,'GET_INPUT',{id:targetId})).libraryText===authored);await target.press('Control+Home');await target.press('ArrowRight');await target.press('Shift+ArrowRight');await fromReader(page,targetId);const route=await page.evaluate(()=>history.state.paiaReader);assert.equal(route.view,'thought-compose');assert.equal(JSON.stringify(route).includes(authored),false);assert.equal(await fields(page).count(),0,'accepted leave disposes the old editable DOM');
 const other=await rpc(page,'GET_INPUT',{id:otherId}),fresh='SYNTHETIC other tab changed this mounted Input';await rpc(page,'EDIT_DOCUMENT',{edit:{documentId:other.documentId,operationId:op(),blocks:[{id:other.id,expectedRevision:other.revision,libraryText:fresh,note:other.note,excluded:false}]}});
 await page.evaluate(documentId=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d5ReturnReads=[];chrome.runtime.sendMessage=async(message,...args)=>{if(message.type==='GET_PAGE'&&message.page?.documentId===documentId)__d5ReturnReads.push(structuredClone(message.page));return send(message,...args);};},beforeTarget.documentId);
 await compose(page).getByRole('textbox',{name:'今天的新想法'}).fill('SYNTHETIC saved follow-on from Reader');await compose(page).getByRole('button',{name:'保存想法',exact:true}).click();await eventually(()=>compose(page).isHidden(),'saved Thought returns to its Reader origin');await eventually(async()=>JSON.stringify(await ids(page))===JSON.stringify(beforeIds),'exact two mounted windows return');assert.equal(await page.locator(`[data-edit-id="${otherId}"]`).textContent(),fresh);assert.equal(await target.textContent(),authored);trace.stage='Reader focus after current window appears';trace.readerBusyBeforeFocus=await page.locator('.workspace').getAttribute('aria-busy');await eventually(()=>page.locator('.workspace').getAttribute('aria-busy').then(value=>value==='false'),'Reader return finishes recovery and focus restoration');assert.equal(await target.evaluate(node=>document.activeElement===node),true);assert.equal(await page.evaluate(()=>__d5ReturnReads.length),2,'return publishes exactly two fresh pages without auto-prefetch');assert.ok(await page.evaluate(()=>__d5ReturnReads[1].expectedGeneration>=0));
 // A change to a tracked history row correctly refuses its old journal; here
 // the independently changed row was never in this Input's Undo group.
 trace.stage='Reader Undo';await target.press('Control+z');await eventually(async()=>(await rpc(page,'GET_INPUT',{id:targetId})).libraryText===beforeTarget.libraryText,'existing app Undo survives safe remount');trace.stage='Reader Redo';await target.press('Control+Shift+z');await eventually(async()=>(await rpc(page,'GET_INPUT',{id:targetId})).libraryText===authored);assert.deepEqual((await h.state()).records,initial.records);trace.ids=beforeIds;trace.reads=await page.evaluate(()=>__d5ReturnReads);trace.targetId=targetId;
}));

for(const variant of ['source','release'])test(`D5 Reader held paging, failed return retry and purge cannot publish obsolete bodies (${variant})`,{timeout:180000},()=>withFixture(variant,'reader-interrupt',async(h,page,trace)=>{
 const initial=await seedReader(h,page,95);await page.evaluate(()=>{document.activeElement?.blur();getSelection().removeAllRanges();scrollTo(0,document.documentElement.scrollHeight);});await eventually(async()=>(await ids(page)).length===80,'two pages are mounted before interrupting the third');const before=await ids(page),targetId=before[50],target=await rpc(page,'GET_INPUT',{id:targetId});
 await page.evaluate(documentId=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d5ReadMode='hold';globalThis.__d5ReturnReadCount=0;chrome.runtime.sendMessage=async(message,...args)=>{if(message.type!=='GET_PAGE'||message.page?.documentId!==documentId)return send(message,...args);if(__d5ReadMode==='fail-second'&&++__d5ReturnReadCount===2)return {ok:false,error:'STORAGE_FAILED'};const response=await send(message,...args);if(__d5ReadMode==='hold'){__d5ReadMode='held';return new Promise(resolve=>globalThis.__d5ReleasePage=()=>resolve(response));}return response;};},target.documentId);
 await page.evaluate(()=>{document.activeElement?.blur();getSelection().removeAllRanges();scrollTo(0,document.documentElement.scrollHeight);});await eventually(()=>page.evaluate(()=>!!globalThis.__d5ReleasePage));await fromReader(page,targetId);await page.evaluate(()=>__d5ReleasePage());await pause(100);assert.equal(await fields(page).count(),0);assert.equal(await compose(page).isVisible(),true);
 await page.evaluate(()=>{__d5ReadMode='fail-second';__d5ReturnReadCount=0;});await cancel(page);await page.locator('#reader-return-retry').waitFor();assert.equal(await fields(page).count(),0,'first successful half is never published');assert.equal(await page.evaluate(()=>__d5ReturnReadCount),2);await page.evaluate(()=>__d5ReadMode='normal');await page.locator('#reader-return-retry').click();await eventually(async()=>JSON.stringify(await ids(page))===JSON.stringify(before));assert.equal(await page.locator('#reader-return-retry').isHidden(),true);
 // Current source-only Input has no derived owner and can be purged through
 // the same preflight/explicit-confirm contract as the existing purge journey.
 const purgeId=before[5],purge=await rpc(page,'GET_INPUT',{id:purgeId});await fromReader(page,targetId);assert.equal((await rpc(page,'PAIA_ARCHIVE_SOURCE_PURGE_PREFLIGHT',{id:purge.sourceRecordId})).state,'unambiguous');await rpc(page,'PURGE_SOURCE',{id:purge.sourceRecordId,confirm:true});await cancel(page);await eventually(()=>fields(page).count().then(count=>count>0));assert.equal((await ids(page)).includes(purgeId),false);assert.equal((await h.state()).records.some(row=>row.id===purge.sourceRecordId),false);const after=await h.state();assert.deepEqual(after.records,initial.records.filter(row=>row.id!==purge.sourceRecordId));trace.before=before;trace.purged=purgeId;
}));

for(const variant of ['source','release'])test(`D5 Thought Content, Years and standalone return retain current owners and Undo (${variant})`,{timeout:240000},()=>withFixture(variant,'thought-return',async(h,page,trace)=>{
 const topic=await rpc(page,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC return Topic',operationId:op()}}),rows=[];for(let index=0;index<65;index++)rows.push(await rpc(page,'CONTINUE_THINKING',{thought:{operationId:op(),topicId:topic.id,body:`SYNTHETIC Thought ${index} 👩‍💻\n`+'保留这段合成内容的原始顺序。\n'.repeat(3)}}));
 await nav(page,'thoughts');await page.locator(`[data-topic-id="${topic.id}"]`).click();const targetId=rows[45].id;for(let attempt=0;attempt<6&&!await page.locator(`#topic-body [data-entry-id="${targetId}"]`).count();attempt++){await page.evaluate(()=>{document.activeElement?.blur();getSelection().removeAllRanges();scrollTo(0,document.documentElement.scrollHeight);});await pause(200);}const row=page.locator(`#topic-body [data-entry-id="${targetId}"]`),body=row.locator('[data-entry-field="body"]');await body.waitFor();const before=await rpc(page,'GET_LIBRARY_ENTRY',{id:targetId}),authored='SYNTHETIC retained Thought app Undo 👩‍💻';trace.stage='Topic initial edit';await body.fill(authored);await eventually(async()=>(await rpc(page,'GET_LIBRARY_ENTRY',{id:targetId})).body===authored);trace.stage='Topic compose';await row.locator('.library-actions summary').click();await row.getByRole('button',{name:'接着写',exact:true}).click();await compose(page).waitFor();await compose(page).getByRole('textbox',{name:'今天的新想法'}).fill('SYNTHETIC saved follow-on from Topic');await compose(page).getByRole('button',{name:'保存想法',exact:true}).click();await eventually(()=>compose(page).isHidden(),'saved Thought returns to its Topic origin');await body.waitFor();assert.equal(await body.textContent(),authored);trace.stage='Topic ready return';await eventually(()=>page.locator('.workspace').getAttribute('aria-busy').then(value=>value==='false'),'Topic return installs the current reading owner');assert.equal(await body.textContent(),authored,'fresh returned Topic retains the edited origin');await page.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d5UndoCalls=0;chrome.runtime.sendMessage=async(message,...args)=>{if(message.type==='THOUGHT_EDIT_HISTORY'&&++__d5UndoCalls===1)return new Promise(resolve=>globalThis.__d5ReleaseUndo=async()=>resolve(await send(message,...args)));return send(message,...args);};});trace.stage='Topic Undo request';await page.locator('#library-undo').click();await eventually(()=>page.evaluate(()=>!!globalThis.__d5ReleaseUndo));trace.stage='pending Undo departure';await page.locator('#create-entry').click();assert.equal(await compose(page).isHidden(),true,'pending Undo refuses departure through the same Topic owner');assert.equal(await body.textContent(),authored);trace.stage='Topic Undo readback';await page.evaluate(()=>__d5ReleaseUndo());await eventually(async()=>(await rpc(page,'GET_LIBRARY_ENTRY',{id:targetId})).body===before.body);trace.stage='Topic Redo readback';await page.locator('#library-redo').click();await eventually(async()=>(await rpc(page,'GET_LIBRARY_ENTRY',{id:targetId})).body===authored);
 trace.stage='Years return';await page.locator('[data-topic-view="years"]').click();await page.locator('#topic-timeline').waitFor();await page.locator('#create-entry').click();await compose(page).waitFor();await cancel(page);assert.equal(await page.locator('[data-topic-view="years"]').getAttribute('aria-pressed'),'true');
 trace.stage='standalone return';const standalone=await rpc(page,'CONTINUE_THINKING',{thought:{operationId:op(),body:'SYNTHETIC standalone original'}});await page.locator('#back').click();await page.locator('#library-unplaced').click();await page.locator(`[data-unplaced-id="${standalone.id}"]`).click();const dialog=page.locator('#library-dialog'),standaloneBody=dialog.locator('[data-entry-field="body"]');await standaloneBody.fill('SYNTHETIC standalone changed');await eventually(async()=>(await rpc(page,'GET_LIBRARY_ENTRY',{id:standalone.id})).body==='SYNTHETIC standalone changed');await dialog.locator('.library-actions summary').click();await dialog.getByRole('button',{name:'接着写',exact:true}).click();await compose(page).waitFor();assert.equal(await dialog.isHidden(),true);await cancel(page);await standaloneBody.waitFor();assert.equal(await standaloneBody.textContent(),'SYNTHETIC standalone changed');await standaloneBody.press('Control+z');await eventually(async()=>(await rpc(page,'GET_LIBRARY_ENTRY',{id:standalone.id})).body==='SYNTHETIC standalone original');trace.topicId=topic.id;trace.targetId=targetId;trace.standaloneId=standalone.id;
}));
