import test from 'node:test';
import assert from 'node:assert/strict';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
import {openArchiveWindow} from './harness/archive-navigator.mjs';
import {auditReaderConfirmation} from './harness/d7-reader-confirmation.mjs';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const releaseRoot=mkdtempSync(join(tmpdir(),'paia-dvn-remove-release-'));
test.after(()=>rmSync(releaseRoot,{recursive:true,force:true}));
console.log(execFileSync('python3',['scripts/build_current_release.py',releaseRoot],{encoding:'utf8'}));
const rpc=async(page,type,fields={})=>{const reply=await page.evaluate(message=>chrome.runtime.sendMessage(message),{type,...fields});assert.equal(reply?.ok,true,JSON.stringify(reply));return reply.data;};
async function dump(page){return page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paia-archive');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}),names=[...db.objectStoreNames],tx=db.transaction(names,'readonly'),rows=Object.fromEntries(await Promise.all(names.map(async name=>[name,await new Promise((resolve,reject)=>{const r=tx.objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);})])));db.close();return {db:rows,local:await chrome.storage.local.get(null)};});}
async function settle(page){let previous=null,stable=0;await eventually(async()=>{const current=await dump(page),generation=current.db.meta.find(row=>row.id==='backup-data-generation')?.value||0;const pending=current.db.libraryMigrationItems.some(row=>row.entityKind==='search'&&row.statusKey===0)||current.db.invalidations.some(row=>row.stateKey===0)||current.db.organizerJobs.some(row=>row.kind==='purge_cleanup'&&row.stateKey===0);stable=!pending&&generation===previous?stable+1:0;previous=generation;return stable>=8;},'real canonical maintenance settles without hiding any changed row');}
async function fixture(extensionPath,count=1){const h=await FakeChatGPT.start(extensionPath?{extensionPath}:{}),p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await h.open({id:'dvn-remove-scope',title:'SYNTHETIC Complete Conversation',base:1609459200,messages:Array.from({length:count},(_,i)=>({id:'dvn-remove-'+i,text:'SYNTHETIC Original '+i+' 中文 👩‍💻'}))});await eventually(async()=>(await h.state()).records.length===count);await rpc(p,'SET_ENABLED',{enabled:false});await openArchiveWindow(p,{text:'SYNTHETIC Complete Conversation'});await settle(p);await eventually(async()=>!!(await dump(p)).db.meta.find(row=>row.id==='reading:v1')?.anchors?.length,'existing Reader position is durably saved before a whole-database baseline');return {h,p};}
async function review(p){await p.locator('#document-menu').click();await p.getByRole('menuitem',{name:/移出整段对话|Remove entire conversation/}).click();await p.locator('dialog[data-removal-target][open]').waitFor();}
const commit=p=>p.locator('dialog[data-removal-target][open]').getByRole('button',{name:/确认移出整段对话|Confirm entire conversation removal/}).click();
for(const variant of ['source','release']){
 const extensionPath=variant==='release'?releaseRoot:null;
 test(`D1 complete141 target review/cancel retains focus and no effects; actual commit preserves every Source/body/history and recapture negative intent (${variant})`,{timeout:120000},async()=>{
  const {h,p}=await fixture(extensionPath,141);let confirmation;try{
   await p.setViewportSize({width:1440,height:800});
   const before=await h.state(),mounted=await p.locator('.library-prose').count();assert.ok(mounted<141);const b=before.library.blocks[0];await p.locator(`[data-edit-id="${b.id}"]`).fill('SYNTHETIC human Current kept');await eventually(async()=>(await rpc(p,'GET_INPUT',{id:b.id})).libraryText==='SYNTHETIC human Current kept');await settle(p);await eventually(async()=>(await dump(p)).db.meta.find(row=>row.id==='reading:v1')?.anchors?.some(anchor=>anchor.inputId===b.id&&anchor.revision===b.revision+1),'the scheduled Reader anchor catches up with the actual edit before measuring cancel');const saved=await dump(p);
   await review(p);assert.equal(await p.locator('dialog[open]').count(),1);assert.match(await p.locator('.reader-removal-scope').textContent(),/141/);assert.doesNotMatch(await p.locator('dialog[data-removal-target]').textContent(),/SYNTHETIC Original 140|provenanceSignature|sourceRecordIds/);confirmation=await auditReaderConfirmation(h,{variant,surface:'removal'});for(const width of [1440,1024,768,390,320]){await p.setViewportSize({width,height:800});const bounds=await p.locator('dialog[data-removal-target]').boundingBox();assert.ok(bounds.width<=width-20);assert.ok(await p.locator('dialog[data-removal-target]').evaluate(el=>el.scrollWidth-el.clientWidth)<=2);}await p.setViewportSize({width:1440,height:800});mkdirSync('work/qa-dvn-removal',{recursive:true});await p.screenshot({path:`work/qa-dvn-removal/${variant}-complete-scope.png`});await p.keyboard.press('Escape');await eventually(()=>p.evaluate(()=>document.activeElement.id==='document-menu'));assert.deepEqual(await dump(p),saved,'cancel is zero-effect');
   await review(p);await p.locator('dialog[data-removal-target][open]').getByRole('button',{name:/^(取消|Cancel)$/}).click();await eventually(()=>p.evaluate(()=>!document.querySelector('dialog[open]')&&document.activeElement.id==='document-menu'),'Cancel closes through the existing owner and returns to the surviving document menu');assert.deepEqual(await dump(p),saved,'explicit Cancel also preserves every database and local-storage row');
   await review(p);await commit(p);await eventually(async()=>await p.locator('#collection-panel').isVisible());const after=await dump(p);assert.deepEqual(after.db.records,saved.db.records);assert.equal(after.db.blocks.length,141);for(const old of saved.db.blocks){const now=after.db.blocks.find(row=>row.id===old.id).value;assert.equal(now.excluded,true);assert.equal(now.libraryText,old.value.libraryText);assert.equal(now.note,old.value.note);assert.equal(now.revision,old.value.revision+1);}for(const old of saved.db.revisions)assert.ok(after.db.revisions.some(row=>row.id===old.id));assert.equal(after.db.inputRemovals.length,141);assert.equal(after.db.operationReceipts.filter(row=>row.namespace==='working-input').length,saved.db.operationReceipts.filter(row=>row.namespace==='working-input').length+1);assert.equal(after.db.tombstones.length,0);assert.equal(await p.locator('#notice').getByRole('button',{name:'撤销',exact:true}).count(),0,'no fabricated whole-Conversation Undo');
   await rpc(p,'SET_ENABLED',{enabled:true});await h.open({id:'dvn-remove-scope',title:'SYNTHETIC Complete Conversation',base:1609459200,messages:[{id:'dvn-remove-140',text:'SYNTHETIC Original 140 中文 👩‍💻'}]});await eventually(async()=>{const state=await h.state();return state.records.length===141&&state.library.blocks.every(b=>b.excluded);});assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);await confirmation.finish();
  }catch(error){await confirmation?.finish(error);throw error;}finally{await h.close();}
 });
 test(`D1 actual IME blocks whole-target review; real concurrent note edit closes the confirmation without any removal (${variant})`,{timeout:90000},async()=>{
  const {h,p}=await fixture(extensionPath,3);try{
   const field=p.locator('.library-prose').first(),id=await field.getAttribute('data-edit-id'),b=await rpc(p,'GET_INPUT',{id});await field.evaluate(el=>{globalThis.__composingNode=el;el.focus();el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.textContent='SYNTHETIC complete unfinished 中文';});await p.locator('#document-menu').click();await p.getByRole('menuitem',{name:/移出整段对话|Remove entire conversation/}).click();assert.equal(await p.locator('dialog[data-removal-target][open]').count(),0);assert.equal((await rpc(p,'GET_INPUT',{id})).libraryText,b.libraryText);assert.equal(await field.evaluate(el=>el===globalThis.__composingNode),true);await field.evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText==='SYNTHETIC complete unfinished 中文');await settle(p);
   await review(p);const other=await h.context.newPage();await other.goto(`chrome-extension://${h.extensionId}/ui/archive.html`);const current=await rpc(other,'GET_INPUT',{id});await rpc(other,'EDIT_DOCUMENT',{edit:{operationId:crypto.randomUUID(),documentId:current.documentId,blocks:[{id,expectedRevision:current.revision,libraryText:current.libraryText,note:'SYNTHETIC actual concurrent note',excluded:current.excluded}]}});await eventually(()=>p.locator('dialog[data-removal-target][open]').count().then(n=>n===0));const state=await h.state();assert.equal(state.library.blocks.every(b=>!b.excluded),true);assert.equal((await rpc(p,'GET_INPUT',{id})).note,'SYNTHETIC actual concurrent note');assert.equal((await dump(p)).db.inputRemovals.length,0);await other.close();assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  }finally{await h.close();}
 });
 test(`D1 actual aborted removal retains all rows and command; explicit same-operation retry commits the whole target once (${variant})`,{timeout:90000},async()=>{
  const {h,p}=await fixture(extensionPath,3);try{
   const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));await worker.evaluate(()=>{const put=IDBObjectStore.prototype.put;globalThis.__abortRemoval=true;IDBObjectStore.prototype.put=function(value,...args){if(this.name==='operationReceipts'&&value.namespace==='working-input'&&globalThis.__abortRemoval){this.transaction.abort();throw Error('SYNTHETIC real removal IDB abort');}return put.call(this,value,...args);};});const before=await dump(p);await review(p);await commit(p);await p.locator('#retry').waitFor();const after=await dump(p);assert.deepEqual(after.db,before.db,'the failed transaction changes no persisted row');const pending=Object.values(after.local).find(row=>row?.kind==='document'&&row.operation?.edit?.removeScope);assert.ok(pending?.operation.pendingRequest);const originalId=pending.operation.edit.operationId;assert.match(await p.locator('#save-status').textContent(),/尚未保存|not saved/);assert.equal(await p.locator('.library-prose').first().getAttribute('contenteditable'),'false');await worker.evaluate(()=>{globalThis.__abortRemoval=false;});await p.locator('#retry').click();await eventually(async()=>(await dump(p)).db.operationReceipts.some(row=>row.id===originalId));const committed=await dump(p);assert.equal(committed.db.blocks.every(row=>row.value.excluded),true);assert.deepEqual(committed.db.records,before.db.records);assert.equal(committed.db.operationReceipts.filter(row=>row.namespace==='working-input').length,1);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  }finally{await h.close();}
 });
 test(`D1 committed removal with lost acknowledgement survives actual worker/page reload and reconciles the exact receipt without another write (${variant})`,{timeout:120000},async()=>{
  const {h,p}=await fixture(extensionPath,45);try{
   const before=await h.state();await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__removeSend=send;globalThis.__removeWrites=0;chrome.runtime.sendMessage=async m=>{if(m.type==='EDIT_DOCUMENT'&&m.edit?.removeScope){globalThis.__removeWrites++;await send(m);throw Error('SYNTHETIC committed removal reply loss');}if(m.type==='PAIA_ARCHIVE_OPERATION_OUTCOME')throw Error('SYNTHETIC unavailable outcome channel');return send(m);};});await review(p);await commit(p);await p.locator('#retry').waitFor();assert.equal(await p.evaluate(()=>globalThis.__removeWrites),1);assert.match(await p.locator('#save-status').textContent(),/保存结果暂时无法确认|unknown/i);const pending=Object.values((await dump(p)).local).find(row=>row?.kind==='document'&&row.operation?.edit?.removeScope);assert.equal(pending.operation.edit.removeScope.members.length,45);assert.equal(pending.sourceRecordIds.length,45);assert.equal(JSON.parse(pending.operation.pendingRequest).operationId,pending.operation.edit.operationId);await p.locator('#retry').click();assert.equal(await p.evaluate(()=>globalThis.__removeWrites),1);
   await p.evaluate(()=>{chrome.runtime.sendMessage=globalThis.__removeSend;});await h.restartWorker();await p.reload();await eventually(async()=>{const state=await dump(p);return !Object.values(state.local).some(row=>row?.kind==='document'&&row.ownerId===pending.ownerId);},'reload reconciles durable scoped receipt before releasing Recovery');const after=await dump(p);assert.equal(after.db.operationReceipts.filter(row=>row.namespace==='working-input').length,1);assert.equal(after.db.blocks.every(row=>row.value.excluded&&row.value.revision===1),true);assert.deepEqual((await h.state()).records,before.records);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  }finally{await h.close();}
 });
}
