import test from 'node:test';
import assert from 'node:assert/strict';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openArchiveWindow} from './harness/archive-navigator.mjs';
const rpc=async(page,type,fields={})=>{const r=await page.evaluate(message=>chrome.runtime.sendMessage(message),{type,...fields});assert.equal(r?.ok,true,JSON.stringify(r));return r.data;};
async function fixture(count=1,extensionPath=null){const h=await FakeChatGPT.start(extensionPath?{extensionPath}:{}),p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);const messages=Array.from({length:count},(_,i)=>({id:'dvn-original-message-'+i,text:'SYNTHETIC Original '+i+' 中文 👩‍💻\n'+(i===count-1?'EXACT_UNMOUNTED_TAIL':'保留原话，不改写。')}));await h.open({id:'dvn-original-scope',title:'SYNTHETIC Original Conversation',base:1609459200,messages});await eventually(async()=>(await h.state()).records.length===count,'all immutable Source records captured');await openArchiveWindow(p,{text:'SYNTHETIC Original Conversation',label:'Q2 Reader opens'});await rpc(p,'SET_ENABLED',{enabled:false});return {h,p,messages};}
const releaseRoot=mkdtempSync(join(tmpdir(),'paia-dvn-original-release-'));
test.after(()=>rmSync(releaseRoot,{recursive:true,force:true}));
try{console.log(execFileSync('python3',['scripts/build_current_release.py',releaseRoot],{encoding:'utf8'}));}catch(error){console.log(String(error.stdout||''));console.error(String(error.stderr||''));throw error;}
for(const variant of ['source','release']){
 const extensionPath=variant==='release'?releaseRoot:null;
test(`D1 explicit Original reads and copies the entire Conversation, then selected Input only; History selects real owners (${variant})`,{timeout:120000},async()=>{
 const {h,p,messages}=await fixture(123,extensionPath);try{
  const field=p.locator('.library-prose').first(),id=await field.getAttribute('data-edit-id'),before=await rpc(p,'GET_INPUT',{id});await field.fill('SYNTHETIC Current rewrite');await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText==='SYNTHETIC Current rewrite');await eventually(async()=>/已保存|Saved/.test(await p.locator('#save-status').textContent()),'durable edit acknowledgement before Original');
  await p.evaluate(()=>{globalThis.__copiedOriginal=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>globalThis.__copiedOriginal.push(text)},configurable:true});});
  await p.locator('#document-menu').click();await p.getByRole('menuitem',{name:'查看原始内容',exact:true}).click();await eventually(async()=>await p.locator('#info-content .source-original').count()===40,'bounded Original page');
  assert.equal(await p.locator('#info-dialog textarea,#info-dialog [contenteditable]').count(),0);assert.equal(await p.locator('#source-time-summary').count(),0);assert.equal(await p.locator('#info-content button.danger').count(),0);assert.match(await p.locator('#info-dialog h2').textContent(),/SYNTHETIC Original Conversation/);
  await p.locator('#original-copy').click();await eventually(async()=>await p.evaluate(()=>globalThis.__copiedOriginal.length)===1,'complete Copy acknowledged');assert.equal(await p.evaluate(()=>globalThis.__copiedOriginal[0]),messages.map(m=>m.text).join('\n\n'));assert.equal(await p.locator('.library-prose').count()<123,true,'Copy includes unmounted tail');
  await p.keyboard.press('Escape');await eventually(()=>p.locator('#info-dialog').isHidden());await eventually(()=>p.evaluate(()=>document.activeElement.id==='document-menu'),'Escape returns focus after native dialog close event');assert.equal(await p.locator('#info-content').textContent(),'');
  await p.locator('[data-block-id="'+id+'"] .reader-more').click();await p.getByRole('menuitem',{name:'查看原始内容',exact:true}).click();await eventually(async()=>await p.locator('#info-content .source-original').count()===1);assert.equal(await p.locator('#info-content .source-original').textContent(),messages[0].text);await p.locator('#original-copy').click();await eventually(async()=>await p.evaluate(()=>globalThis.__copiedOriginal.length)===2);assert.equal(await p.evaluate(()=>globalThis.__copiedOriginal[1]),messages[0].text);assert.equal((await rpc(p,'GET_INPUT',{id})).revision,before.revision+1);
  for(const width of [1440,1024,768,390,320]){await p.setViewportSize({width,height:800});const bounds=await p.locator('#info-dialog').boundingBox();assert.ok(bounds.width<=width-30&&bounds.height<=752);assert.ok(Math.abs(bounds.x-(width-bounds.width)/2)<2);assert.ok(await p.locator('#info-dialog').evaluate(el=>el.scrollWidth-el.clientWidth)<=2);}
  await p.locator('#close-info').click();await p.locator('#document-menu').click();await p.getByRole('menuitem',{name:'查看修改历史',exact:true}).click();await p.getByLabel('修改历史的 Input').waitFor();await eventually(async()=>await p.getByLabel('修改历史的 Input').locator('option').count()>2);assert.match(await p.locator('#revision-list').textContent(),/不是 Conversation 的原子历史/);await p.getByLabel('修改历史的 Input').selectOption(id);await eventually(()=>p.locator('.revision-row').first().isVisible());assert.equal(await p.locator('dialog[open]').count(),1);await p.keyboard.press('Escape');assert.equal(await p.locator('#revision-list').textContent(),'');assert.deepEqual(h.errors,[]);assert.equal(h.extensionNetworkRequests,0);
 }finally{await h.close();}
});
test(`D1 late Original reads and Copy failure cannot resurrect closed or purged Source in hidden DOM (${variant})`,{timeout:90000},async()=>{
 const {h,p}=await fixture(1,extensionPath);try{
  const id=await p.locator('.library-prose').first().getAttribute('data-edit-id'),b=await rpc(p,'GET_INPUT',{id});
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__originalSend=send;globalThis.__holdOriginal=true;globalThis.__originalReads=[];chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='PAIA_ARCHIVE_ORIGINAL_PAGE'&&globalThis.__holdOriginal){await new Promise(resolve=>globalThis.__originalReads.push(resolve));}return result;};});
  await p.locator('#document-menu').click();await p.getByRole('menuitem',{name:'查看原始内容',exact:true}).click();await eventually(()=>p.evaluate(()=>globalThis.__originalReads.length===1));await p.keyboard.press('Escape');await p.evaluate(()=>{globalThis.__holdOriginal=false;globalThis.__originalReads[0]();});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await p.locator('#info-dialog').isHidden(),true);assert.equal(await p.locator('#info-content').textContent(),'');
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__holdHistory=true;globalThis.__historyReads=[];chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='GET_REVISIONS'&&globalThis.__holdHistory)await new Promise(resolve=>globalThis.__historyReads.push(resolve));return result;};});
  await p.locator('.reader-more').first().click();await p.getByRole('menuitem',{name:'版本历史',exact:true}).click();await eventually(()=>p.evaluate(()=>globalThis.__historyReads.length===1));await p.keyboard.press('Escape');await p.evaluate(()=>{globalThis.__holdHistory=false;globalThis.__historyReads[0]();});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await p.locator('#revision-dialog').isHidden(),true);assert.equal(await p.locator('#revision-list').textContent(),'');
  await p.locator('#document-menu').click();await p.getByRole('menuitem',{name:'查看原始内容',exact:true}).click();await eventually(()=>p.locator('#original-copy').isEnabled());
  await p.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise((_,reject)=>globalThis.__denyCopy=reject)}});});await p.locator('#original-copy').click();await eventually(()=>p.evaluate(()=>typeof globalThis.__denyCopy==='function'));
  await rpc(p,'PURGE_SOURCE',{id:b.sourceRecordId,confirm:true});await eventually(()=>p.locator('#info-dialog').isHidden());await p.evaluate(()=>globalThis.__denyCopy(Error('SYNTHETIC clipboard denied')));await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await p.locator('#info-content').textContent(),'');assert.equal(await p.locator('.original-copy-fallback,.reading-copy-dialog').count(),0);assert.equal((await h.state()).records.length,0);assert.deepEqual(h.errors,[]);assert.equal(h.extensionNetworkRequests,0);
 }finally{await h.close();}
});
}
