import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
const release=mkdtempSync(join(tmpdir(),'paia-d2-root-'));
test.after(()=>rmSync(release,{recursive:true,force:true}));
console.log(execFileSync('python3',['scripts/build_current_release.py',release],{encoding:'utf8'}));
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r?.ok,true,JSON.stringify(r));return r.data;};
const op=()=>crypto.randomUUID();
for(const variant of ['source','release'])test(`D2 compact Topic root migrates grid and renders exact excerpts with actual worker chronology (${variant})`,{timeout:120000},async()=>{
 const h=await FakeChatGPT.start(variant==='release'?{extensionPath:release}:{}),p=h.archive;
 try{
  await p.locator('#enable-consent').click();if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
  const name='SYNTHETIC 长主题名称 '+('长期保留原话与不确定性 '.repeat(6)),body='  SYNTHETIC 我可能更适合消费产品，但现在样本还太少。👩‍💻 é\n'+('不自动改写结论。'.repeat(30));
  const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name,operationId:op()}}),created=await rpc(p,'CONTINUE_THINKING',{thought:{operationId:op(),body,topicId:topic.id}});
  const original=await rpc(p,'GET_LIBRARY_ENTRY',{id:created.id});
  const excerpt=await rpc(p,'ADD_TO_TOPICS',{selection:{operationId:op(),kind:'thought',id:created.id,expectedRevision:original.revision,span:{start:0,end:11},topicIds:[topic.id]}});
  await p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local);await s.foundationWrite(t=>t.put('meta',{id:'thought-layout:v1',version:1,layout:'grid'}));});
  await p.reload();await p.locator('[data-view="thoughts"]').click();
  await eventually(()=>p.locator(`[data-topic-id="${topic.id}"]`).count().then(n=>n===1));
  assert.equal((await rpc(p,'GET_THOUGHT_LAYOUT')).layout,'list');
  const migration=await p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local);return s.repository.transaction(false,t=>t.get('meta','thought-layout:v1'));});
  assert.equal(migration.previousLayout,'grid');assert.equal(migration.migration,'desktop-vnext-compact');
  const root=await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'stable'}}),cue=root.items.find(x=>x.id===topic.id).rootCue;
  assert.equal(cue.text,body.slice(cue.range.start,cue.range.end));assert.equal(cue.entryId,created.id);
  const row=p.locator(`[data-topic-id="${topic.id}"]`);
  assert.equal(await row.locator('strong').textContent(),name);assert.equal(await row.locator('.summary').evaluate(el=>el.firstChild.textContent),cue.text);
  assert.equal(await p.locator('.topic-grid,.topic-tile').count(),0);
  const timeline=await rpc(p,'GET_LIBRARY_TOPIC_TIMELINE',{options:{topicId:topic.id}});
  assert.equal(timeline.overview.total,2);assert.equal(timeline.overview.unknownCount,1);
  assert.equal(timeline.items.find(x=>x.entry.id===excerpt.id).entry.expressionTime.basis,'unknown');
  mkdirSync('work/qa-dvn-topic-root',{recursive:true});const matrix=[];
  for(const appearance of ['light','dark']){
   await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});
   for(const width of [1440,1280,1024,768,390,320]){
    await p.setViewportSize({width,height:900});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(resolve)));
    const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.ok(overflow<=2,`${appearance}/${width}: ${overflow}`);
    const style=await row.evaluate(el=>({border:getComputedStyle(el).borderRadius,title:getComputedStyle(el.querySelector('strong')).webkitLineClamp}));
    assert.equal(style.border,'0px');assert.ok(!style.title||style.title==='none','complete title is not line-clamped');
    await p.screenshot({path:`work/qa-dvn-topic-root/${variant}-${appearance}-${width}.png`});matrix.push({appearance,width,overflow});
   }
  }
  await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'en'}});await eventually(()=>row.locator('small').textContent().then(x=>/Thought excerpt/.test(x)));assert.equal(await p.locator('#thought-search').getAttribute('placeholder'),'Search thoughts, topics or text…');assert.doesNotMatch(await p.locator('#thought-home-tools').innerText(),/[\u3400-\u9fff]/,'root product controls follow English locale');
  assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:created.id})).body,body);
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d2RestoreSend=()=>chrome.runtime.sendMessage=send;globalThis.__d2Held=[];chrome.runtime.sendMessage=(message,...args)=>{const result=send(message,...args);return message.type==='LIBRARY_INDEX_PAGE'?Promise.resolve(result).then(value=>new Promise(resolve=>__d2Held.push(()=>resolve(value)))):result;};});
  await p.locator('[data-view="thoughts"]').click();await eventually(()=>p.evaluate(()=>__d2Held.length>0),'root reread is held before mutation');
  const live=await rpc(p,'GET_LIBRARY_ENTRY',{id:created.id}),replacement='SYNTHETIC newer independent expression';
  await rpc(p,'EDIT_LIBRARY_FIELDS',{edit:{operationId:op(),id:live.id,expectedRevision:live.revision,expectedFieldRevisions:live.fieldRevisions,changes:{body:replacement}}});
  await eventually(()=>row.locator('.summary').textContent().then(text=>text===''),'mutation synchronously clears the old transient root cue');
  await p.evaluate(old=>{globalThis.__d2StaleRendered=false;globalThis.__d2CueObserver=new MutationObserver(()=>{if(document.getElementById('thought-list').textContent.includes(old))__d2StaleRendered=true;});__d2CueObserver.observe(document.getElementById('thought-list'),{subtree:true,childList:true,characterData:true});__d2RestoreSend();for(const finish of __d2Held)finish();},cue.text);
  await eventually(()=>row.locator('.summary').textContent().then(text=>text===replacement),'queued fresh read uses the new authoritative text');
  assert.equal(await p.evaluate(()=>__d2StaleRendered),false,'late pre-mutation root response never resurrects its excerpt');await p.evaluate(()=>__d2CueObserver.disconnect());
  await p.evaluate(()=>{globalThis.__d2ZoomRows=[...document.querySelectorAll('#thought-panel button,#thought-panel strong,#thought-panel span,#thought-panel small,#thought-panel p,#thought-panel label,#thought-panel select')].map(node=>({node,size:getComputedStyle(node).fontSize,prior:node.style.fontSize}));for(const row of __d2ZoomRows)row.node.style.fontSize=(parseFloat(row.size)*2)+'px';scrollTo(0,0);});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(resolve)));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth<=2),'200% text at320px has no page horizontal overflow');await p.screenshot({path:`work/qa-dvn-topic-root/${variant}-text200-320.png`});await p.evaluate(()=>{for(const row of __d2ZoomRows)row.node.style.fontSize=row.prior;delete globalThis.__d2ZoomRows;});
  assert.equal(h.externalRequests,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
  writeFileSync(`work/qa-dvn-topic-root/${variant}.json`,JSON.stringify({status:'PASS',headSha:process.env.PAIA_TESTED_HEAD||execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),variant,matrix,text200Reflow:true,migration:true,sourceUnchanged:true,zeroProviderCalls:true},null,2));
 }finally{await h.close();}
});

for(const variant of ['source','release'])test(`D2 actual300 Topic DTO window, exact refetch and search/Back (${variant})`,{timeout:180000},async()=>{
 const h=await FakeChatGPT.start(variant==='release'?{extensionPath:release}:{}),p=h.archive;
 try{
  await p.setViewportSize({width:1440,height:900});await p.locator('#enable-consent').click();if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
  const seed=await p.evaluate(async()=>{
   const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local),ids=[];
   for(let i=0;i<300;i++){const topic=await s.createTopic({name:'D2_DENSE_'+String(i).padStart(3,'0')+' '+(i%17===0?'这是保留完整名称的长主题，'.repeat(12):'合成主题'),operationId:crypto.randomUUID()});await s.editTopic({id:topic.id,expectedRevision:topic.revision,changes:{summary:'SYNTHETIC_DENSE_CUE_'+i+' '+('有归属的人工说明。'.repeat(300))},operationId:crypto.randomUUID()});ids.push(topic.id);}
   // Warm the existing count maintenance, never invent a UI-only root fixture.
   let cursor=null;do{const page=await s.libraryIndexPage({mode:'stable',cursor,limit:40});cursor=page.nextCursor;}while(cursor);await s.drainLibraryMaintenance();await s.repository.close();
   const {TopicController}=await import('../ui/topic-workspace.js'),create=TopicController.prototype.createHomeCollection;TopicController.prototype.createHomeCollection=function(...args){globalThis.__d2Root=this;return create.apply(this,args);};globalThis.__d2RootTrace=[];globalThis.__d2RootEvent=0;const shift=TopicController.prototype.shiftHomeWindow;TopicController.prototype.shiftHomeWindow=function(direction,options){__d2RootTrace.push({event:++__d2RootEvent,phase:'shift',direction,options,start:this.homeCollection?.windowStart,loading:this.homeCollection?.loading,error:this.homeCollection?.errorKind,shifting:this.homeWindowShifting,visible:this.thoughtRootVisible()});return shift.call(this,direction,options);};const restore=TopicController.prototype.restoreHomeAnchor;TopicController.prototype.restoreHomeAnchor=function(anchor){__d2RootTrace.push({event:++__d2RootEvent,phase:'restore',anchor,scrollY,start:this.homeCollection?.windowStart,serial:this.serial});if(__d2RootTrace.length>60)__d2RootTrace.shift();const result=restore.call(this,anchor);setTimeout(()=>__d2RootTrace.push({phase:'settled',scrollY,start:this.homeCollection?.windowStart,visible:[...document.querySelectorAll('#thought-list [data-root-key]')].filter(n=>{const r=n.getBoundingClientRect();return r.bottom>120&&r.top<innerHeight;}).map(n=>({key:n.dataset.rootKey,top:n.getBoundingClientRect().top}))}),100);return result;};return {ids};
  });
  await p.locator('[data-view="thoughts"]').click();await eventually(()=>p.locator('#thought-list [data-topic-id]').count().then(n=>n>=40));
  const sentinel=p.locator('#thought-continuous-sentinel');
  for(let i=0;i<10;i++){if(await p.evaluate(()=>__d2Root.homeCollection?.terminal))break;const before=await p.evaluate(()=>__d2Root.homeCollection.items.length);await sentinel.evaluate(node=>node.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true})));await eventually(()=>p.evaluate(n=>__d2Root.homeCollection.items.length>n||__d2Root.homeCollection.terminal,before),'all dense root pages remain reachable');}
  await eventually(()=>p.evaluate(()=>__d2Root.homeCollection.terminal),'actual root terminal');
  const audit=await p.evaluate(()=>{const w=__d2Root,r=w.homeCollection;return {ids:r.items.map(x=>x.ref.id),extent:r.items.length,retained:r.bodies.size,unique:new Set([...r.bodies.values(),...w.homePage.page.items]).size,snapshot:JSON.stringify(r.snapshot()),metadata:JSON.stringify(r.pageMeta),mounted:document.querySelectorAll('#thought-list [data-topic-id]').length};});
  assert.deepEqual([...audit.ids].sort(),[...seed.ids].sort());assert.equal(audit.extent,300);assert.ok(audit.retained<=120);assert.ok(audit.unique<=120);assert.ok(audit.mounted<=120);assert.doesNotMatch(audit.snapshot,/SYNTHETIC_DENSE_CUE|这是保留完整名称/);assert.doesNotMatch(audit.metadata,/SYNTHETIC_DENSE_CUE|summary|recent/);
  const mounted=p.locator('#thought-list [data-topic-id]'),row=mounted.nth(60),id=await row.getAttribute('data-topic-id');await row.scrollIntoViewIfNeeded();
  const anchor=await row.evaluate(node=>({id:node.dataset.topicId,top:node.getBoundingClientRect().top}));await row.click();await eventually(()=>p.locator('#thought-document').isVisible());
  assert.equal(await p.locator('#thought-list [data-topic-id]').count(),0,'hidden root holds no body-bearing nodes or old closures');assert.equal(await p.evaluate(()=>__d2Root.homeCollection.bodies.size),0,'Topic route releases root DTO bodies');assert.doesNotMatch(await p.evaluate(()=>JSON.stringify(__d2Root.homePositions.get('home'))),/SYNTHETIC_DENSE_CUE/);
  await p.locator('#back').click();await eventually(()=>p.locator(`[data-topic-id="${id}"]`).count().then(n=>n===1),'Back refetches exact prior window');await eventually(()=>p.locator(`[data-topic-id="${id}"]`).evaluate((node,a)=>Math.abs(node.getBoundingClientRect().top-a.top)<140,anchor),'Back restores stable row anchor');assert.equal(await p.evaluate(()=>__d2Root.homeCollection.items.length),300);
  await p.locator('#thought-search').fill('D2_DENSE_007');await eventually(()=>p.locator('#thought-list .topic-index-row').count().then(n=>n===1),'full root search reaches an evicted item');assert.match(await p.locator('#thought-list').innerText(),/D2_DENSE_007/);assert.doesNotMatch(await p.evaluate(()=>JSON.stringify(__d2Root.rootPreSearch)),/SYNTHETIC_DENSE_CUE/);
  await p.locator('#thought-search').fill('');await eventually(()=>p.locator(`[data-topic-id="${id}"]`).count().then(n=>n===1),'closing root search restores its body-free extent');await eventually(()=>p.locator(`[data-topic-id="${id}"]`).evaluate((node,a)=>Math.abs(node.getBoundingClientRect().top-a.top)<140,anchor),'closing root search restores the exact prior reading anchor');assert.equal(await p.evaluate(()=>__d2Root.homeCollection.items.length),300);
  const wheel=await p.evaluate(()=>{const r=__d2Root.homeCollection,node=[...document.querySelectorAll('#thought-list [data-root-key]')].find(n=>n.dataset.rootKey===r.items[r.windowStart].key);return {start:r.windowStart,delta:node.getBoundingClientRect().top-1000,focused:document.activeElement===document.getElementById('thought-search')};});assert.equal(wheel.focused,true);await p.mouse.move(800,450);await p.mouse.wheel(0,wheel.delta);await eventually(()=>p.evaluate(start=>__d2Root.homeCollection.windowStart<start&&[...document.querySelectorAll('#thought-list [data-topic-id]')].some(n=>{const r=n.getBoundingClientRect();return r.bottom>140&&r.top<innerHeight;}),wheel.start),'deliberate wheel reveals earlier rows while empty root search keeps focus');assert.equal(await p.evaluate(()=>document.activeElement===document.getElementById('thought-search')),true);
  await eventually(()=>p.evaluate(()=>!__d2Root.homeWindowShifting&&!__d2Root.homeRestoring&&!__d2Root.homeCollection.loading&&!__d2Root.homeCollection.hydration),'search restoration and any earlier replay settle before failure injection');
  // Exact backward replay at the terminal frontier fails visibly without an
  // automatic retry, then succeeds via the same explicit Retry control.
  await p.evaluate(()=>{globalThis.__d2RootSend=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d2RootFailures=0;chrome.runtime.sendMessage=(message,...args)=>{if(message.type==='LIBRARY_INDEX_PAGE'){__d2RootFailures++;return Promise.resolve({ok:false,error:'STORAGE_FAILED'});}return __d2RootSend(message,...args);};});
  const previous=p.locator('[data-root-window-action="previous"]');await previous.click();await eventually(()=>p.locator('#thought-continuous-retry').isVisible(),'failed exact prior window has Retry');assert.equal(await p.evaluate(()=>__d2Root.homeCollection.terminal),true);assert.ok(await p.evaluate(()=>__d2RootFailures>0),'the failure injector actually intercepted a new read');const failures=await p.evaluate(()=>__d2RootFailures);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>__d2RootFailures),failures,'same failed window is never automatically retried');
  await p.evaluate(()=>chrome.runtime.sendMessage=__d2RootSend);await p.locator('#thought-continuous-retry').click();await eventually(()=>p.locator('#thought-continuous-retry').isHidden(),'explicit terminal replay retry succeeds');assert.ok(await p.evaluate(()=>__d2Root.homeCollection.bodies.size<=120));try{await eventually(()=>p.evaluate(()=>[...document.querySelectorAll('#thought-list [data-topic-id]')].some(node=>{const r=node.getBoundingClientRect();return r.bottom>140&&r.top<innerHeight&&node.innerText.trim();})),'explicit retry returns usable visible rows');}finally{mkdirSync('work/qa-dvn-topic-root',{recursive:true});writeFileSync(`work/qa-dvn-topic-root/${variant}-retry-diagnostics.json`,JSON.stringify(await p.evaluate(()=>({trace:__d2RootTrace,scrollY,anchor:__d2Root.homeHydrationAnchor,restoring:__d2Root.homeRestoring,shifting:__d2Root.homeWindowShifting,start:__d2Root.homeCollection.windowStart,rows:[...document.querySelectorAll('#thought-list [data-root-key]')].map(n=>({key:n.dataset.rootKey,top:n.getBoundingClientRect().top}))})),null,2));await p.screenshot({path:`work/qa-dvn-topic-root/${variant}-dense-refetch.png`});}
  const keyboardPrevious=p.locator('[data-root-window-action="previous"]');await keyboardPrevious.focus();const keyboardBefore=await p.evaluate(()=>({start:__d2Root.homeCollection.windowStart,trace:__d2RootEvent}));await keyboardPrevious.press('Enter');await eventually(()=>p.evaluate(before=>{const trace=__d2RootTrace.filter(x=>x.event>before.trace),admitted=trace.some(x=>x.phase==='shift'&&x.options?.reveal===true),target=trace.filter(x=>x.phase==='restore'&&x.anchor?.focus).at(-1)?.anchor,node=document.activeElement?.closest('[data-root-key]'),rect=node?.getBoundingClientRect();return admitted&&__d2Root.homeCollection.windowStart<before.start&&target&&node?.dataset.rootKey===target.key&&rect.bottom>140&&rect.top<innerHeight&&Math.abs(rect.top-target.top)<140;},keyboardBefore),'Enter admits an explicit reveal and focuses its exact visible target');
  assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);
  writeFileSync(`work/qa-dvn-topic-root/${variant}-dense.json`,JSON.stringify({status:'PASS',headSha:process.env.PAIA_TESTED_HEAD||execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),variant,topics:300,retainedBodies:audit.retained,bodyFreeSnapshots:true,hiddenRootReleased:true,exactBack:true,fullRootSearch:true,explicitTerminalRetry:true,keyboardReveal:true,focusedWheel:true,zeroProviderCalls:true},null,2));
 }finally{mkdirSync('work/qa-dvn-topic-root',{recursive:true});writeFileSync(`work/qa-dvn-topic-root/${variant}-root-final-diagnostics.json`,JSON.stringify(await p.evaluate(()=>({trace:globalThis.__d2RootTrace,failures:globalThis.__d2RootFailures,scrollY,active:document.activeElement?.outerHTML?.slice(0,400),start:globalThis.__d2Root?.homeCollection?.windowStart,loading:globalThis.__d2Root?.homeCollection?.loading,error:globalThis.__d2Root?.homeCollection?.errorKind,shifting:globalThis.__d2Root?.homeWindowShifting,restoring:globalThis.__d2Root?.homeRestoring,rows:[...document.querySelectorAll('#thought-list [data-root-key]')].map(n=>({key:n.dataset.rootKey,top:n.getBoundingClientRect().top}))})),null,2));await p.screenshot({path:`work/qa-dvn-topic-root/${variant}-root-final.png`});await h.close();}
});

for(const variant of ['source','release'])test(`D2 Topic note preserves the existing recovery owner through conflict, failure and lost acknowledgement (${variant})`,{timeout:120000},async()=>{
 const h=await FakeChatGPT.start(variant==='release'?{extensionPath:release}:{}),p=h.archive,outcomes=[];let activeMode='setup';
 try{
  await p.locator('#enable-consent').click();if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();
  for(const mode of ['conflict','failure','lost-ack']){
   activeMode=mode;const topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC_NOTE_'+mode,operationId:op()}}),current=await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id}),epoch=(await rpc(p,'GET_STATE')).recoveryEpoch,summary='SYNTHETIC_RECOVERED_TOPIC_NOTE_'+mode,operationId=op(),edit={id:topic.id,expectedRevision:current.revision,changes:{summary},operationId};
   await rpc(p,'PAIA_RECOVERY_DRAFT_SAVE',{draft:{epoch,kind:'topic_metadata',ownerId:topic.id,token:operationId,operation:{type:'EDIT_LIBRARY_TOPIC',edit}}});
   if(mode==='conflict')await rpc(p,'EDIT_LIBRARY_TOPIC',{edit:{id:topic.id,expectedRevision:current.revision,changes:{summary:'SYNTHETIC_NEWER_SAVED_NOTE'},operationId:op()}});
   else await p.evaluate(({operationId,mode})=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);let held=false;globalThis.__noteRestore=()=>chrome.runtime.sendMessage=send;globalThis.__noteAttempts=[];chrome.runtime.sendMessage=async(message,...args)=>{if(message.type==='EDIT_LIBRARY_TOPIC'&&message.edit.operationId===operationId){__noteAttempts.push(message.edit.operationId);globalThis.__noteRequests??=[];__noteRequests.push(JSON.stringify(message.edit));if(!held){held=true;if(mode==='lost-ack')await send(message,...args);return {ok:false,error:'STORAGE_FAILED'};}}return send(message,...args);};},{operationId,mode});
   await p.locator('[data-view="thoughts"]').click();await eventually(()=>p.locator(`[data-topic-id="${topic.id}"]`).count().then(n=>n===1));await p.locator(`[data-topic-id="${topic.id}"]`).click();
   const note=p.locator('#topic-note-editor'),field=note.locator('textarea');await eventually(()=>field.inputValue().then(value=>value===summary),'recovered summary is visible through the same metadata owner');assert.equal(await note.isVisible(),true);
   if(mode==='conflict'){
    assert.equal((await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).summary,'SYNTHETIC_NEWER_SAVED_NOTE','recovery never silently overwrites the newer version');
    await p.locator('#topic-menu summary').click();await p.locator('#topic-menu button').filter({hasText:/^主题说明$/}).click();assert.equal(await field.inputValue(),summary,'Topic note opens the conflicted owner without a blocking save');
    const compare=note.getByRole('button',{name:'核对说明版本',exact:true});await compare.evaluate(button=>{globalThis.__noteActivation=[];for(const type of ['pointerdown','focusin','pointerup','click'])button.addEventListener(type,()=>__noteActivation.push({type,y:button.getBoundingClientRect().y}));});await compare.click();const activation=await p.evaluate(()=>__noteActivation);assert.ok(activation.some(event=>event.type==='pointerdown')&&activation.some(event=>event.type==='click'),'the original pointer activation reaches the Compare action');assert.ok(Math.max(...activation.map(event=>event.y))-Math.min(...activation.map(event=>event.y))<=2,'focusout must not move the recovery action by clearing its conflict warning');await p.locator('#library-form select[name="decision"]').selectOption('mine');await p.locator('#library-form button[type="submit"]').click();
   }else await note.getByRole('button',{name:'重试保存说明',exact:true}).click();
   await eventually(async()=>(await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).summary===summary,'explicit recovery save reaches canonical Topic');await eventually(async()=>(await rpc(p,'PAIA_RECOVERY_DRAFT_LOAD',{draft:{epoch,kind:'topic_metadata',ownerId:topic.id}}))===null,mode+' acknowledged recovery clears only its draft');
   if(mode!=='conflict'){assert.ok(await p.evaluate(()=>__noteAttempts.length>=2),mode+' reuses recovery operation on retry');assert.deepEqual(await p.evaluate(()=>[...new Set(__noteAttempts)]),[operationId]);await p.evaluate(()=>__noteRestore());}
   outcomes.push({mode,visibleDraft:true,durableSave:true,sameOwner:true});await p.locator('#back').click();
  }
  mkdirSync('work/qa-dvn-topic-root',{recursive:true});writeFileSync(`work/qa-dvn-topic-root/${variant}-note-recovery.json`,JSON.stringify({status:'PASS',headSha:process.env.PAIA_TESTED_HEAD||execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),variant,outcomes,zeroProviderCalls:true},null,2));assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
 }finally{mkdirSync('work/qa-dvn-topic-root',{recursive:true});writeFileSync(`work/qa-dvn-topic-root/${variant}-note-final-diagnostics.json`,JSON.stringify({activeMode,outcomes,details:await p.evaluate(()=>({activation:globalThis.__noteActivation,attempts:globalThis.__noteAttempts,requests:globalThis.__noteRequests,status:document.getElementById('save-status')?.textContent,summary:document.querySelector('#topic-note-editor textarea')?.value}))},null,2));await p.screenshot({path:`work/qa-dvn-topic-root/${variant}-note-final.png`});await h.close();}
});
