import test from 'node:test';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {join} from 'node:path';import {mkdir,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';import {routeComposer,isolated} from './harness/prompt-composer.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),url='https://chatgpt.com/c/prompt-insertion-fixture',receiptDir=join(root,'work/prompt-surface');
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
for(const variant of ['source','release'])test('CPV1-09 surface '+variant+' isolated native Chrome',{timeout:240000},async t=>{
 const extensionPath=variant==='source'?root:join(root,'work/current-release');if(variant==='release')execFileSync('python3',['scripts/build_current_release.py'],{cwd:root,stdio:'pipe'});
 const h=await FakeChatGPT.start({extensionPath,headless:!process.env.DISPLAY,launchThroughPort:true}),screens=[];let world;await mkdir(receiptDir,{recursive:true});
 try{
  await h.archive.locator('#consent-check').check();await h.archive.locator('#enable-consent').click();
  const engineering=await h.context.newPage();await engineering.goto('chrome-extension://'+h.extensionId+'/ui/prompt-reuse-test.html');
  const text='请保留引用。\nOnly test.🙂',secret='PRIVATE_LIBRARY_NEVER_IN_HOST';let q=await rpc(engineering,'PAIA_PROMPT_QUERY');
  const a=await rpc(engineering,'PAIA_PROMPT_CHANGE',{change:{action:'create',revision:q.revision,text}});await rpc(engineering,'PAIA_PROMPT_CHANGE',{change:{action:'create',revision:a.revision,text:secret}});
  await routeComposer(h.context,root);const page=await h.context.newPage();page.on('pageerror',e=>h.errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>!!globalThis.fixture?.view);
  const arrange=async p=>{await p.addStyleTag({content:'body{margin:0;min-height:100vh}form{position:fixed;left:16px;right:16px;bottom:16px;border:1px solid #aaa;padding:12px;background:#fafafa}#blur{position:fixed;top:8px;left:8px}'});};await arrange(page);
  const orb=page.locator('[data-paia-prompt-surface]');await orb.waitFor({state:'visible'});
  const card=()=>page.frames().find(f=>f.url().includes('/ui/prompt-surface.html#'));
  const open=async()=>{if(!card())await orb.click();await eventually(()=>!!card());await card().locator('.row').first().waitFor();return card();};
  await open();world=await isolated(page,h.extensionId);
  await t.test('private card is a cross-origin frame, prompt-only rows and one-click exact retained draft',async()=>{
   assert.equal(await page.evaluate(()=>document.querySelector('[data-paia-prompt-surface]').shadowRoot),null);
   assert.doesNotMatch(await page.locator('body').textContent(),/PRIVATE_LIBRARY_NEVER_IN_HOST|Only test/);
   assert.equal(await page.evaluate(()=>{try{return !!frames[0].document;}catch{return false;}}),false);
   await page.evaluate(()=>fixture.set('原草稿-A｜B',6));await page.waitForTimeout(60);
   await card().getByRole('button',{name:text,exact:true}).click();await eventually(()=>card().locator('#status').textContent().then(x=>x.includes('已插入，未发送')));
   assert.equal(await page.evaluate(()=>fixture.text()),'原草稿-A｜'+text+'B');assert.equal(await page.evaluate(()=>document.activeElement.id),'prompt-textarea');
   await page.keyboard.insertText('续');await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>fixture.text()),'原草稿-A｜'+text+'续B');assert.ok(card());
  });
  await t.test('edit, pin/unpin, hidden recovery, explicit independent delete and no management insertion',async()=>{
   const before=await page.evaluate(()=>fixture.text());let f=card();await f.locator('#refresh').click();const row=f.locator('.row').filter({hasText:secret});await row.locator('.more').click();await f.getByRole('button',{name:'编辑',exact:true}).click();await f.getByRole('textbox',{name:'复用文本'}).fill('edited synthetic template');await orb.click();await f.locator('#close').click();assert.equal(await f.getByRole('textbox',{name:'复用文本'}).inputValue(),'edited synthetic template');await page.evaluate(()=>{history.pushState({},'',location.pathname+'?editing=1');document.body.append(document.createElement('i'));});await page.waitForTimeout(100);assert.equal(await f.getByRole('textbox',{name:'复用文本'}).inputValue(),'edited synthetic template');await f.getByRole('button',{name:'保存',exact:true}).click();await f.getByRole('button',{name:'edited synthetic template',exact:true}).waitFor();
   await f.locator('.row').filter({hasText:'edited synthetic template'}).locator('.more').click();await f.getByRole('button',{name:'置顶',exact:true}).click();await eventually(async()=>await f.locator('.row').first().innerText()==='edited synthetic template\n⋯');
   await f.locator('.row').first().locator('.more').click();await f.getByRole('button',{name:'取消置顶',exact:true}).click();await f.locator('.row').filter({hasText:'edited synthetic template'}).locator('.more').click();await f.getByRole('button',{name:'隐藏',exact:true}).click();await eventually(()=>f.locator('.row').filter({hasText:'edited synthetic template'}).count().then(n=>n===0));
   await f.locator('#hidden').click();await f.locator('.row').filter({hasText:'edited synthetic template'}).locator('.more').click();await f.getByRole('button',{name:'恢复',exact:true}).click();await f.locator('.row').filter({hasText:'edited synthetic template'}).locator('.more').click();await f.getByRole('button',{name:'删除',exact:true}).click();await f.getByRole('button',{name:'确认删除',exact:true}).click();await eventually(()=>f.locator('.row').filter({hasText:'edited synthetic template'}).count().then(n=>n===0));
   assert.equal(await page.evaluate(()=>fixture.text()),before);assert.equal((await rpc(engineering,'PAIA_PROMPT_QUERY',{includeHidden:true})).items.some(x=>x.text==='edited synthetic template'),false);await f.locator('#hidden').click();
  });
  await t.test('new template, keyboard move controls and drag pin retain manual order without inserting',async()=>{
   const f=card(),before=await page.evaluate(()=>fixture.text());await f.locator('#new').click();await f.getByRole('textbox',{name:'复用文本'}).fill('move me synthetic');await f.getByRole('button',{name:'保存',exact:true}).click();await f.locator('.row').filter({hasText:'move me synthetic'}).locator('.more').click();await f.getByRole('button',{name:'上移',exact:true}).focus();await page.keyboard.press('Enter');
   await eventually(async()=>await f.locator('.row').first().innerText()==='move me synthetic\n⋯');assert.equal((await rpc(engineering,'PAIA_PROMPT_QUERY')).items[0].pinned,true);
   await f.locator('.row').filter({hasText:text}).locator('.more').click();const handle=f.getByRole('button',{name:'拖动到目标行之前；也可使用上移下移'}),from=await handle.boundingBox(),to=await f.locator('.row').first().boundingBox();await page.mouse.move(from.x+20,from.y+20);await page.mouse.down();await page.mouse.move(to.x+20,to.y+10,{steps:8});await page.mouse.up();
   await eventually(async()=>await f.locator('.row').first().innerText()===text+'\n⋯');const q=await rpc(engineering,'PAIA_PROMPT_QUERY');assert.equal(q.items[0].id,a.id);assert.equal(q.items[0].pinned,true);assert.equal(await page.evaluate(()=>fixture.text()),before);
  });
  await t.test('split correction uses selected historical expressions without changing archive bodies',async()=>{
   await h.archive.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js');const s=new OrganizerStore(chrome.storage.local);await s.finishFoundation();for(const [i,text]of ['解释这个算法','请解释这个算法'].entries())await s.capture({epoch:(await s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'surface-synthetic-history',url:'https://chatgpt.com/c/surface-synthetic-history',title:'Synthetic'},messages:[{sourceMessageId:'surface-'+i,pageOrder:i+1,originalText:text}]});});
   const before=(await h.state()).records;assert.equal(before.length,2);const f=card();await f.locator('#refresh').click();await f.locator('.row').filter({hasText:'解释这个算法'}).locator('.more').click();await f.getByRole('button',{name:'拆分',exact:true}).click();await f.locator('#editor input[type=checkbox]').first().check();await f.getByRole('button',{name:'拆分',exact:true}).click();await eventually(async()=>(await rpc(engineering,'PAIA_PROMPT_QUERY')).items.filter(x=>x.text.includes('解释这个算法')).length===2);assert.deepEqual((await h.state()).records,before);
  });
  await t.test('worker restart, SPA and page reload preserve durable templates without duplicate surface',async()=>{
   await h.restartWorker();await card().locator('#refresh').click();await card().locator('.row').first().waitFor();
   await page.evaluate(()=>{history.pushState({},'', '/c/prompt-insertion-fixture?route=project');document.body.append(document.createElement('i'));});await eventually(()=>card()?.url().includes('prompt-surface.html#'));await page.waitForTimeout(150);assert.equal(await orb.count(),1);
   await page.goto(url);await arrange(page);await orb.waitFor({state:'visible'});await open();assert.equal(await orb.count(),1);assert.ok((await rpc(engineering,'PAIA_PROMPT_QUERY')).items.find(x=>x.text==='move me synthetic'));
   await world.cdp.detach();world=await isolated(page,h.extensionId);
  });
  await t.test('second tab and actual tab discard restore their own surface and draft target',async()=>{
   const second=await h.context.newPage();await second.goto(url+'#second-tab');await arrange(second);await second.waitForFunction(()=>!!globalThis.fixture?.view);await second.locator('[data-paia-prompt-surface]').waitFor({state:'visible'});await page.evaluate(()=>fixture.set('first-tab-draft',15));await second.evaluate(()=>fixture.set('second-tab-draft',16));
   let sf=second.frames().find(f=>f.url().includes('prompt-surface.html#'));if(!sf){await second.locator('[data-paia-prompt-surface]').click();await eventually(()=>!!second.frames().find(f=>f.url().includes('prompt-surface.html#')));sf=second.frames().find(f=>f.url().includes('prompt-surface.html#'));}await sf.getByRole('button',{name:text,exact:true}).click();await eventually(()=>sf.locator('#status').textContent().then(x=>x.includes('已插入')));assert.equal(await page.evaluate(()=>fixture.text()),'first-tab-draft');assert.equal(await second.evaluate(()=>fixture.text()),'second-tab-draft'+text);
   await page.bringToFront();const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));const tabs=await worker.evaluate(()=>chrome.tabs.query({url:'https://chatgpt.com/*'}));const inactive=tabs.find(x=>x.url===url+'#second-tab');assert.ok(inactive&&!inactive.active);const discarded=await worker.evaluate(id=>chrome.tabs.discard(id),inactive.id);assert.equal(discarded.discarded,true);await worker.evaluate(id=>chrome.tabs.update(id,{active:true}),inactive.id);await eventually(()=>h.context.pages().some(p=>!p.isClosed()&&p.url()===url+'#second-tab'));const restored=h.context.pages().find(p=>!p.isClosed()&&p.url()===url+'#second-tab');await restored.waitForFunction(()=>!!globalThis.fixture?.view);await arrange(restored);await restored.locator('[data-paia-prompt-surface]').waitFor({state:'visible'});assert.equal(await restored.locator('[data-paia-prompt-surface]').count(),1);await restored.close();await page.bringToFront();
  });
  await t.test('current/last selection, native IME and uncertain outcome keep one-shot safety through the real card',async()=>{
   let f=card();await f.locator('#refresh').click();await page.evaluate(()=>fixture.set('ABCDE',1,4));await page.waitForTimeout(60);await f.getByRole('button',{name:text,exact:true}).click();await eventually(()=>f.locator('#status').textContent().then(x=>x.includes('已插入')));assert.equal(await page.evaluate(()=>fixture.text()),'ABCD'+text+'E');
   await f.locator('#refresh').click();await page.evaluate(()=>fixture.set(''));const cdp=await h.context.newCDPSession(page);await cdp.send('Input.imeSetComposition',{text:'汉',selectionStart:1,selectionEnd:1});await f.getByRole('button',{name:text,exact:true}).click();await eventually(()=>f.locator('#status').textContent().then(x=>!x.includes('正在插入')));assert.notEqual(await page.evaluate(()=>fixture.text()),text);await cdp.send('Input.insertText',{text:'汉'});await cdp.detach();
   await f.locator('#refresh').click();await page.evaluate(()=>fixture.set('draft',5));await world.run("globalThis.nativeCommand=document.execCommand.bind(document);document.execCommand=(...args)=>{nativeCommand(...args);return false;}");await f.getByRole('button',{name:text,exact:true}).click();await eventually(()=>f.locator('#status').textContent().then(x=>x.includes('未确认')));assert.equal(await page.evaluate(()=>fixture.text()),'draft'+text);assert.equal(await f.getByRole('button',{name:text,exact:true}).isDisabled(),true);await world.run('document.execCommand=nativeCommand;');
   await f.getByRole('button',{name:'复制',exact:true}).click();await eventually(()=>f.locator('#status').textContent().then(x=>/已复制|未能复制/.test(x)));assert.match(await f.locator('#status').textContent(),/已复制|未能复制/);
  });
  await t.test('light/dark, 320px, 200% text, coarse input, keyboard and reduced motion remain bounded',async()=>{
   for(const theme of ['light','dark'])for(const width of [1280,320]){await page.setViewportSize({width,height:800});await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});await page.waitForTimeout(120);const f=card();await f.locator('#refresh').click();await f.locator('.row').first().waitFor();assert.ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await f.evaluate(()=>document.querySelector('#list').clientHeight>0));assert.ok(await f.locator('#new').evaluate(e=>e.getBoundingClientRect().height>=44));const path=join(receiptDir,variant+'-'+theme+'-'+width+'.png');await page.screenshot({path});screens.push(path.split('/').at(-1));}
   await card().evaluate(()=>document.documentElement.style.fontSize='28px');assert.ok(await card().evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await card().locator('#close').focus();await page.keyboard.press('Enter');await eventually(()=>!card());await orb.click();await open();
   const cdp=await h.context.newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});await cdp.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await card().locator('.more').first().click();assert.equal(await card().getByRole('button',{name:'编辑',exact:true}).isVisible(),true);await cdp.detach();
  });
  await t.test('orb movement persists safely; idle CPU is bounded; no send, Provider, reply capture or site storage',async()=>{
   await card().locator('#close').click();await eventually(()=>!card());const box=await orb.boundingBox();await page.mouse.move(box.x+22,box.y+22);await page.mouse.down();await page.mouse.move(40,60,{steps:8});await page.mouse.up();await page.waitForTimeout(100);assert.equal(card(),undefined);const moved=await orb.boundingBox();assert.ok(Math.abs(moved.x-box.x)>5||Math.abs(moved.y-box.y)>5);
   await page.reload();await arrange(page);await orb.waitFor({state:'visible'});const restored=await orb.boundingBox();assert.ok(Math.abs(restored.x-moved.x)<2&&Math.abs(restored.y-moved.y)<2);
   const cdp=await h.context.newCDPSession(page);await cdp.send('Performance.enable');const metric=async()=>{const {metrics}=await cdp.send('Performance.getMetrics');return Object.fromEntries(metrics.map(x=>[x.name,x.value]));};const before=await metric();await page.waitForTimeout(1500);const after=await metric();assert.ok(after.TaskDuration-before.TaskDuration<.3,'idle 1.5s must not consume 300ms main-thread task CPU');await cdp.detach();
   assert.deepEqual(await page.evaluate(()=>({send:fixture.send,enter:fixture.enter,storage:[localStorage.length,sessionStorage.length]})),{send:0,enter:0,storage:[0,0]});assert.equal(h.deepSeekRequests.length,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.externalRequests,0);assert.equal(h.historyRequests,0);assert.equal((await h.state()).records.length,2);assert.deepEqual(h.errors,[]);
   await writeFile(join(receiptDir,variant+'.json'),JSON.stringify({head:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),variant,status:'PASS',evidence:'SYNTHETIC_NATIVE_CHROME',screens,idleTaskSeconds:after.TaskDuration-before.TaskDuration,send:0,providerRequests:0}));
  });
 }finally{await world?.cdp.detach().catch(()=>{});await h.close();}
});
