import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
import {confirmOrganizeScope} from './harness/ai-reviewed-browser.mjs';
const release=mkdtempSync(join(tmpdir(),'paia-d3-organize-'));
test.after(()=>rmSync(release,{recursive:true,force:true}));
console.log(execFileSync('python3',['scripts/build_current_release.py',release],{encoding:'utf8'}));
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r?.ok,true,JSON.stringify(r));return r.data;};
const read=async(p,topicId)=>(await rpc(p,'GET_AI_PRESENTATION_STATUS',{options:{topicId}})).topics[0];
const op=()=>crypto.randomUUID(),listFields=['keyInformation','preferences','decisions','judgments','openQuestions','possibleEvolution'];
const output=(r,index)=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({topicId:r.topicCandidates[0].id,blockSummary:`SYNTHETIC reviewed overview ${index}`,currentView:`SYNTHETIC candidate ${index}: uncertainty remains; this is not the user's quoted belief.\n`+'Long conditional explanation, without invented causation. '.repeat(15),...Object.fromEntries(listFields.map(field=>[field,[{text:`SYNTHETIC ${field} ${index}: preserve conditions and attribution.`,evidenceEntryIds:[r.inputs.at(-1).ref]}]])),evidenceEntryIds:r.inputs.map(x=>x.ref)})}}]});
async function ready(h){const p=h.archive;await p.setViewportSize({width:1440,height:900});await p.locator('#enable-consent').click();if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN',appearance:'light'}});await rpc(p,'PAIA_MEMORY_SETTINGS',{options:{externalAccess:true,localOnly:false}});await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-d3-fixture-only'}});return p;}
async function seed(p,count=160){return p.evaluate(async count=>{const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local),topic=await s.createTopic({name:'SYNTHETIC D3 保留不确定与归属',operationId:crypto.randomUUID()}),ids=[];for(let i=0;i<count;i++)ids.push((await s.continueThinking({topicId:topic.id,operationId:crypto.randomUUID(),body:`SYNTHETIC_D3_${i}：受访者说“并不愿意”。我仍不确定；保留两种可能，并未决定替代。`})).id);const other=await s.createTopic({name:'SYNTHETIC unrelated Topic',operationId:crypto.randomUUID()});await s.continueThinking({topicId:other.id,operationId:crypto.randomUUID(),body:'SYNTHETIC_OTHER_TOPIC_NEVER_SEND'});await s.repository.close();return {topicId:topic.id,ids};},count);}
async function open(p,topicId){await p.locator('[data-view="thoughts"]').click();const tile=p.locator(`[data-topic-id="${topicId}"]`);await tile.waitFor();await tile.click();await p.locator('#topic-heading h1').waitFor();await eventually(()=>p.locator('#ai-presentation-toggle').isEnabled());await p.locator('#ai-presentation-toggle').check();await p.locator('[data-ai-first-generation]').waitFor();}
async function choose(p,fn){const fields=await p.locator('[data-ai-candidate-field]').evaluateAll(nodes=>nodes.map(n=>n.dataset.aiCandidateField));for(const field of fields)await p.locator(`[data-ai-candidate-field="${field}"] input[data-candidate-decision="${fn(field)}"]`).check();}
async function update(p){await p.locator('#ai-library-update').waitFor({state:'visible'});await p.locator('#ai-library-update').click();await confirmOrganizeScope(p);await p.locator('[data-ai-candidate]').waitFor();}
for(const variant of ['source','release'])test(`D3 exact scope, first adoption and same-attempt acknowledgement (${variant})`,{timeout:240000},async()=>{
 let calls=0;const h=await FakeChatGPT.start({...variant==='release'?{extensionPath:release}:{},deepSeekFixture:async body=>output(JSON.parse(body.messages[1].content),++calls)}),p=await ready(h);
 try{
  const {topicId,ids}=await seed(p),before=await Promise.all([ids[0],ids.at(-1)].map(id=>rpc(p,'GET_LIBRARY_ENTRY',{id})));await open(p,topicId);assert.equal(calls,0);assert.equal(await p.locator('#original-reading-body').isVisible(),true);
  await p.getByRole('button',{name:'生成 AI整理',exact:true}).click();const dialog=p.locator('#library-dialog[open]');await dialog.locator('[data-organize-scope]').waitFor();assert.match(await dialog.textContent(),/160 段材料/);assert.match(await dialog.textContent(),/本次发送 8 段/);assert.match(await dialog.textContent(),/152 段待后续/);assert.equal(calls,0);await p.locator('#library-dialog-close').click();assert.equal(calls,0);assert.equal((await read(p,topicId)).presentation,null);
  await p.getByRole('button',{name:'生成 AI整理',exact:true}).click();await confirmOrganizeScope(p);await p.locator('[data-ai-candidate]').waitFor();let row=await read(p,topicId);assert.equal(row.presentation,null);assert.equal(row.candidate.baseKind,'none');assert.equal(calls,1);assert.equal(JSON.parse(h.deepSeekRequests[0].messages[1].content).inputs.length,8);assert.ok(!JSON.stringify(h.deepSeekRequests).includes('SYNTHETIC_OTHER_TOPIC_NEVER_SEND'));assert.equal(await p.locator('#ai-reading-body [data-ai-field]').count(),0);assert.equal(await p.getByRole('button',{name:'保存这些选择',exact:true}).isDisabled(),true);
  await p.getByRole('button',{name:'下一处未决定',exact:true}).click();assert.equal(await p.evaluate(()=>document.activeElement?.type),'radio');assert.equal(await p.locator('input[data-candidate-decision]:checked').count(),0);
  mkdirSync('work/qa-dvn-organize',{recursive:true});const matrix=[];
  for(const [width,appearance]of [[1440,'light'],[1024,'light'],[900,'light'],[390,'dark'],[320,'dark']]){await p.setViewportSize({width,height:900});await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});await p.locator('[data-ai-candidate]').scrollIntoViewIfNeeded();const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.ok(overflow<=2,`${variant}/${width}: overflow ${overflow}`);await p.screenshot({path:`work/qa-dvn-organize/${variant}-${appearance}-${width}.png`});matrix.push({width,appearance,overflow});}
  await p.setViewportSize({width:1440,height:900});await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'light'}});await choose(p,()=> 'keep');await p.getByRole('button',{name:'保存这些选择',exact:true}).click();await eventually(async()=>!(await read(p,topicId)).candidate,'first all-Keep commits only its receipt');row=await read(p,topicId);assert.equal(row.presentation,null);assert.equal(calls,1);
  await p.getByRole('button',{name:'生成 AI整理',exact:true}).click();await confirmOrganizeScope(p);await p.locator('[data-ai-candidate]').waitFor();assert.equal((await read(p,topicId)).presentation,null);await choose(p,field=>field==='blockSummary'?'adopt':'keep');
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d3Saves=[];globalThis.__d3LoseAck=true;chrome.runtime.sendMessage=async(message,...args)=>{if(message.type==='EDIT_AI_PRESENTATION'&&message.edit?.candidateDecisions){__d3Saves.push(structuredClone(message.edit));const result=await send(message,...args);if(__d3LoseAck){__d3LoseAck=false;return {ok:false,error:'MESSAGE_RESPONSE_TIMEOUT'};}return result;}return send(message,...args);};});
  await p.getByRole('button',{name:'保存这些选择',exact:true}).click();await eventually(async()=>!!(await read(p,topicId)).presentation,'lost acknowledgement resolves by exact receipt readback');row=await read(p,topicId);assert.equal(row.presentation.revision,1);assert.equal(row.presentation.blockSummary,'SYNTHETIC reviewed overview 2');assert.equal(row.presentation.currentView,'');assert.ok(listFields.every(field=>row.presentation[field].length===0));assert.equal(await p.evaluate(()=>__d3Saves.length),1);assert.equal(calls,2);
  await update(p);await choose(p,field=>field==='currentView'?'adopt':'keep');await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__d3BeforeCommit=true;globalThis.__d3Retries=[];chrome.runtime.sendMessage=async(message,...args)=>{if(message.type==='EDIT_AI_PRESENTATION'&&message.edit?.candidateDecisions){__d3Retries.push(structuredClone(message.edit));if(__d3BeforeCommit){__d3BeforeCommit=false;return {ok:false,error:'STORAGE_FAILED'};}}return send(message,...args);};});
  await p.getByRole('button',{name:'保存这些选择',exact:true}).click();await eventually(()=>p.evaluate(()=>__d3Retries.length===1),'first local failed attempt');assert.equal((await read(p,topicId)).presentation.revision,1);await eventually(()=>p.getByRole('button',{name:'保存这些选择',exact:true}).isEnabled(),'explicit same-attempt retry');await p.getByRole('button',{name:'保存这些选择',exact:true}).click();await eventually(async()=>(await read(p,topicId)).presentation.revision===2,'one durable retry revision');const retry=await p.evaluate(()=>__d3Retries);assert.equal(retry.length,2);assert.deepEqual(retry[0],retry[1]);assert.equal(calls,3);
  assert.deepEqual(await Promise.all([ids[0],ids.at(-1)].map(id=>rpc(p,'GET_LIBRARY_ENTRY',{id}))),before);await p.locator('#ai-presentation-toggle').uncheck();await p.locator('#ai-presentation-toggle').check();assert.equal(calls,3,'viewing saved output never generates');assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);
  writeFileSync(`work/qa-dvn-organize/${variant}.json`,JSON.stringify({status:'PASS',headSha:process.env.PAIA_TESTED_HEAD||execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),variant,intendedCount:160,batchCount:8,remainingCount:152,firstCurrentAbsent:true,firstAllKeep:true,mixedDefaults:true,afterCommitReadback:true,beforeCommitSameAttempt:true,sourceUnchanged:true,providerFixtureRequests:calls,matrix},null,2));
 }finally{await h.close();}
});
