import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture} from './harness/original-complete.mjs';
import {MetadataEditor,TopicController} from '../ui/topic-workspace.js';
const row={id:'topic',revision:3,name:'Current title',summary:'Current saved note',recoveryEpoch:'epoch'};
const draft={token:'recover-operation',operation:{type:'EDIT_LIBRARY_TOPIC',edit:{id:'topic',expectedRevision:3,changes:{summary:'SYNTHETIC_RECOVERED_NOTE'},operationId:'recover-operation'}}};
function root(){const note={hidden:true},fields=new Map([['name',{textContent:row.name,get innerText(){return this.textContent;},matches:()=>false,closest:()=>null}],['summary',{value:row.summary,matches:()=>true,closest:()=>note}]]);return {note,fields,node:{addEventListener(){},querySelector:selector=>fields.get(selector.match(/"(.*?)"/)[1]),contains:()=>false}};}
for(const mode of ['conflict','failure','success'])test(`D2 existing metadata owner paints and retains recovered Topic note (${mode})`,async()=>{
 const prior=globalThis.chrome,dom=root(),calls=[];globalThis.chrome={runtime:{sendMessage:async message=>{calls.push(message);if(message.type==='PAIA_RECOVERY_DRAFT_LOAD')return {ok:true,data:draft};if(message.type==='EDIT_LIBRARY_TOPIC')return mode==='failure'?{ok:false,error:'STORAGE_FAILED'}:{ok:true,data:mode==='conflict'?{conflict:true}:{revision:4}};return {ok:true,data:true};}}};
 let editor;try{editor=new MetadataEditor(dom.node,{...row},'topic',()=>{});assert.equal(await editor.recoveryReady,mode==='success');assert.equal(dom.fields.get('summary').value,'SYNTHETIC_RECOVERED_NOTE');assert.equal(editor.local.summary,'SYNTHETIC_RECOVERED_NOTE');assert.equal(editor.dirty(),mode!=='success');if(mode!=='success')assert.equal(dom.note.hidden,false);if(mode==='conflict')assert.equal(editor.conflicted,true);if(mode==='failure'){editor.failed=false;assert.equal(await editor.flush(),false);assert.equal(calls.filter(x=>x.type==='EDIT_LIBRARY_TOPIC').at(-1).edit.operationId,'recover-operation','unknown acknowledgement retries the same logical metadata operation');}}finally{editor?.dispose();globalThis.chrome=prior;}
});
test('D2 a late metadata recovery acknowledgement never replaces newer typing or IME',async()=>{
 for(const composing of [false,true]){const prior=globalThis.chrome,dom=root();let finish,started;const ready=new Promise(resolve=>started=resolve);globalThis.chrome={runtime:{sendMessage:message=>{if(message.type==='PAIA_RECOVERY_DRAFT_LOAD')return Promise.resolve({ok:true,data:draft});if(message.type==='EDIT_LIBRARY_TOPIC'){started();return new Promise(resolve=>finish=resolve);}return Promise.resolve({ok:true,data:true});}}};let editor;
  try{editor=new MetadataEditor(dom.node,{...row},'topic',()=>{});await ready;editor.local.summary='SYNTHETIC_NEWER_TYPING';dom.fields.get('summary').value='SYNTHETIC_NEWER_TYPING';editor.composing=composing;finish({ok:true,data:{revision:4}});assert.equal(await editor.recoveryReady,true);assert.equal(editor.local.summary,'SYNTHETIC_NEWER_TYPING');assert.equal(dom.fields.get('summary').value,'SYNTHETIC_NEWER_TYPING');assert.equal(editor.saved.summary,'SYNTHETIC_RECOVERED_NOTE');assert.equal(editor.row.revision,4);assert.equal(editor.dirty(),true);}finally{editor?.dispose();globalThis.chrome=prior;}
 }
});
test('D2 Topic note opens the existing failed/conflicted draft without requiring that draft to save first',async()=>{
 const prior=globalThis.document;let focused=0,painted=0;const note={hidden:true,querySelector:()=>({focus:()=>focused++}),scrollIntoView(){}};globalThis.document={getElementById:()=>note};const owner={composing:false,failed:true,conflicted:true,recoveryReady:Promise.resolve(false),paint:()=>painted++};const workspace=Object.assign(Object.create(TopicController.prototype),{id:'topic',view:'original',originalMode:'content',editor:{metadata:[{kind:'topic',...owner}]},flushEditors:()=>{throw Error('the failed draft must not gate its own recovery UI');}});try{await workspace.editTopicCue();assert.equal(note.hidden,false);assert.equal(focused,1);assert.equal(painted,1);}finally{globalThis.document=prior;}
});
test('D2 root row callback late-dispatches a body-free search target through the current controller method',async()=>{
 const target={kind:'entry',entryId:'entry'},path={topicId:'topic',sectionId:'section'},controller=Object.assign(Object.create(TopicController.prototype),{openSearchResult(){throw Error('obsolete callback');}}),run=controller.rootAction('openSearchResult',target,path);let received;controller.openSearchResult=(...args)=>received=args;await run();assert.deepEqual(received,[target,path]);assert.doesNotMatch(JSON.stringify(received),/body|snippet|summary/);
});

test('D2 collecting a conflicted recovered note never silently rebases its durable recovery precondition',async()=>{
 const prior=globalThis.chrome,dom=root(),calls=[];globalThis.chrome={runtime:{sendMessage:async message=>{calls.push(message);if(message.type==='PAIA_RECOVERY_DRAFT_LOAD')return {ok:true,data:draft};if(message.type==='EDIT_LIBRARY_TOPIC')return {ok:true,data:{conflict:true}};return {ok:true,data:true};}}};let editor;
 try{editor=new MetadataEditor(dom.node,{...row,revision:4},'topic',()=>{});await editor.recoveryReady;editor.collect();await editor.protectRecovery();const save=calls.filter(x=>x.type==='PAIA_RECOVERY_DRAFT_SAVE').at(-1);assert.equal(save.draft.operation.edit.expectedRevision,3,'only explicit comparison may choose a newer revision');assert.equal(save.draft.operation.edit.operationId,'recover-operation');assert.equal(editor.conflicted,true);}finally{editor?.dispose();globalThis.chrome=prior;}
});
test('D2 recovered receipt older than the displayed Topic does not overwrite its later current metadata',async()=>{
 const prior=globalThis.chrome,dom=root();globalThis.chrome={runtime:{sendMessage:async message=>message.type==='PAIA_RECOVERY_DRAFT_LOAD'?{ok:true,data:draft}:message.type==='EDIT_LIBRARY_TOPIC'?{ok:true,data:{revision:4}}:{ok:true,data:true}}};let editor;
 try{editor=new MetadataEditor(dom.node,{...row,revision:5},'topic',()=>{});assert.equal(await editor.recoveryReady,true);assert.equal(editor.row.revision,5);assert.equal(editor.saved.summary,row.summary);assert.equal(editor.local.summary,row.summary);assert.equal(dom.fields.get('summary').value,row.summary);assert.equal(editor.dirty(),false);}finally{editor?.dispose();globalThis.chrome=prior;}
});

test('D2 recovered metadata never replaces A→B→A input intent or paints a disposed owner',async()=>{
 for(const mode of ['roundtrip','disposed']){const prior=globalThis.chrome,dom=root(),events=new Map(),statuses=[];dom.node.addEventListener=(name,handler)=>events.set(name,handler);let finish,started;const ready=new Promise(resolve=>started=resolve);globalThis.chrome={runtime:{sendMessage:message=>{if(message.type==='PAIA_RECOVERY_DRAFT_LOAD')return Promise.resolve({ok:true,data:draft});if(message.type==='EDIT_LIBRARY_TOPIC'){started();return new Promise(resolve=>finish=resolve);}return Promise.resolve({ok:true,data:true});}}};let editor;
  try{editor=new MetadataEditor(dom.node,{...row},'topic',(...args)=>statuses.push(args));await ready;if(mode==='roundtrip'){for(const value of ['SYNTHETIC_TEMPORARY_B',row.summary]){dom.fields.get('summary').value=value;events.get('input')();}}else editor.dispose();const statusCount=statuses.length;finish({ok:true,data:{revision:4}});assert.equal(await editor.recoveryReady,mode!=='disposed');assert.equal(editor.local.summary,row.summary);assert.equal(dom.fields.get('summary').value,row.summary);if(mode==='disposed')assert.equal(statuses.length,statusCount);}finally{editor?.dispose();globalThis.chrome=prior;}
 }
});
test('D2 choosing saved Topic note cannot overwrite typing while its old recovery clear is held',async()=>{
 const previous={chrome:globalThis.chrome,document:globalThis.document};let finish,started;const ready=new Promise(resolve=>started=resolve),owner={kind:'topic',fields:['name','summary'],local:{name:row.name,summary:'SYNTHETIC_CONFLICTED_DRAFT'},saved:{name:row.name,summary:row.summary},editIntent:1,recovery:{currentToken:'old',clear:()=>{started();return new Promise(resolve=>finish=resolve);}},collect(){},paint(){throw Error('late comparison must not paint');}};
 globalThis.chrome={runtime:{sendMessage:async()=>({ok:true,data:{...row}})}};globalThis.document={getElementById:()=>({append(){}}),createElement:()=>({})};const w=Object.assign(Object.create(TopicController.prototype),{id:row.id,editor:{metadata:[owner]},form:async()=>({decision:'current'}),onStatus(){}});
 try{const pending=w.compareTopicNote();await ready;owner.editIntent++;owner.local.summary='SYNTHETIC_NEWER_DRAFT';owner.recovery.currentToken='new';finish(true);await pending;assert.equal(owner.local.summary,'SYNTHETIC_NEWER_DRAFT');assert.equal(owner.row,undefined);}finally{Object.assign(globalThis,previous);}
});

test('D2 Chrome-serialized metadata recovery preserves the logical operation despite dictionary key order',async()=>{
 const prior=globalThis.chrome,dom=root(),calls=[],serialized={...draft,operation:{type:draft.operation.type,edit:{changes:{summary:'SYNTHETIC_RECOVERED_NOTE',name:'SYNTHETIC_RECOVERED_NAME'},expectedRevision:3,id:'topic',operationId:'recover-operation'}}};globalThis.chrome={runtime:{sendMessage:async message=>{calls.push(message);if(message.type==='PAIA_RECOVERY_DRAFT_LOAD')return {ok:true,data:serialized};if(message.type==='EDIT_LIBRARY_TOPIC')return {ok:false,error:'STORAGE_FAILED'};return {ok:true,data:true};}}};let editor;
 try{editor=new MetadataEditor(dom.node,{...row},'topic',()=>{});await editor.recoveryReady;editor.collect();await editor.flush();const attempts=calls.filter(x=>x.type==='EDIT_LIBRARY_TOPIC');assert.deepEqual([...new Set(attempts.map(x=>x.edit.operationId))],['recover-operation']);assert.equal(JSON.stringify(attempts[1].edit),JSON.stringify(attempts[0].edit),'same-ID retry must preserve the literal request digest as well');}finally{editor?.dispose();globalThis.chrome=prior;}
});

test('D2 actual Topic ledger accepts the exact lost-ack recovery retry and clears its draft once',async()=>{
 const {s}=await completeFixture({texts:[]}),topic=await s.createTopic({name:row.name,operationId:crypto.randomUUID()}),current=await s.topic(topic.id),operationId=crypto.randomUUID(),edit={changes:{summary:'SYNTHETIC_LOST_ACK_NOTE'},expectedRevision:current.revision,id:topic.id,operationId};let stored={token:operationId,operation:{type:'EDIT_LIBRARY_TOPIC',edit}},writes=0;const prior=globalThis.chrome,dom=root();dom.fields.get('summary').value=current.summary;globalThis.chrome={runtime:{sendMessage:async message=>{if(message.type==='PAIA_RECOVERY_DRAFT_LOAD')return {ok:true,data:stored};if(message.type==='PAIA_RECOVERY_DRAFT_SAVE'){stored=structuredClone(message.draft);return {ok:true,data:stored};}if(message.type==='PAIA_RECOVERY_DRAFT_CLEAR'){if(stored?.token===message.draft.token)stored=null;return {ok:true,data:true};}if(message.type==='EDIT_LIBRARY_TOPIC'){writes++;try{const data=await s.editTopic(message.edit);return writes===1?{ok:false,error:'STORAGE_FAILED'}:{ok:true,data};}catch(error){return {ok:false,error:error.code};}}throw Error(message.type);}}};let editor;
 try{editor=new MetadataEditor(dom.node,{...current,recoveryEpoch:'epoch'},'topic',()=>{});assert.equal(await editor.recoveryReady,false);assert.equal((await s.topic(topic.id)).summary,'SYNTHETIC_LOST_ACK_NOTE');editor.collect();assert.equal(await editor.flush(),true);assert.equal(writes,2);assert.equal(stored,null);assert.equal((await s.topic(topic.id)).revision,current.revision+1,'retry returns the prior receipt without a second canonical edit');editor.noteEditIntent();editor.local.summary='SYNTHETIC_NEW_USER_INTENT';assert.equal(editor.recoveryAttempt,null);assert.notEqual(editor.buildEdit().operationId,operationId);}finally{editor?.dispose();globalThis.chrome=prior;}
});
