import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {LibraryEntryEditor} from '../ui/library-entry-editor.js';
import {TopicController} from '../ui/topic-workspace.js';
for(const intervention of ['leave','dispose','clear','composing','composition-ended'])test(`D5 pending actual Thought Undo ${intervention} cannot overwrite a returned owner`,async()=>{
 const keys=['document','chrome'],prior=new Map(keys.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
 const node={textContent:'SYNTHETIC after',matches:()=>false},row={id:'e',body:'SYNTHETIC after',note:'',type:'idea',revision:2,fieldRevisions:{body:2,note:0,type:0},currentInputRevision:null,lifecycle:'active',sourceRecordIds:[]},patches=[{id:'e',field:'body',before:'SYNTHETIC before',after:row.body}];patches.savedEdit=[{id:'e',revisionId:'rev'}];let release;const calls=[];
 globalThis.document={documentElement:{lang:'zh-CN'},getElementById:()=>({inert:false}),querySelector:()=>null};globalThis.chrome={runtime:{sendMessage:async message=>{calls.push(message.type);if(message.type==='GET_LIBRARY_ENTRY')return {ok:true,data:structuredClone(row)};if(message.type==='THOUGHT_EDIT_HISTORY')return new Promise(resolve=>release=()=>{row.body='SYNTHETIC before';row.revision=3;row.fieldRevisions.body=3;resolve({ok:true,data:{}});});throw Error(message.type);}}};
 try{
  const entry=Object.assign(Object.create(LibraryEntryEditor.prototype),{entries:new Map([['e',{saved:{body:row.body,note:'',type:'idea'},local:{body:row.body,note:'',type:'idea'},revision:2,fieldRevisions:{...row.fieldRevisions},currentInputRevision:null}]]),historyVersions:{},journal:{undo:[patches],redo:[],clear(){this.undo=[];this.redo=[];}},surface:{composing:false,dispose(){}},autosave:{cancel(){},dispose(){}},controller:{abort(){}},collect(){},field:(id,field)=>field==='body'?node:null,bindRecovery(){},onStatus(){},onSaved(){}}),active={entry,metadata:[],collect:()=>entry.collect(),flush:()=>entry.flush(),dirty:()=>entry.dirty(),get saving(){return entry.saving;},dispose:()=>entry.dispose()},page=Object.assign(Object.create(TopicController.prototype),{id:'topic',editor:active,aiEditor:null,dialogEditor:null,view:'original',serial:0,statusEpoch:0,statusReadSerial:0,readRetry:{}});
  const undo=entry.history();await new Promise(setImmediate);assert.equal(calls.at(-1),'THOUGHT_EDIT_HISTORY');assert.equal(entry.historyPending,true);await entry.history();assert.equal(calls.filter(type=>type==='THOUGHT_EDIT_HISTORY').length,1,'repeated Undo cannot duplicate the in-flight operation');
  if(intervention==='leave'){assert.equal(await page.leaveEditors({preserveHistory:true}),false);assert.notEqual(entry.disposed,true);assert.equal(node.textContent,'SYNTHETIC after');}else{if(intervention==='dispose')entry.dispose();else if(intervention==='clear')entry.journal.clear();else{entry.historyInputBoundary();entry.surface.composing=true;if(intervention==='composition-ended'){entry.historyInputBoundary();entry.surface.composing=false;}}node.textContent='SYNTHETIC newer returned body';}
  release();await undo;assert.equal(entry.historyPending,false);assert.equal(node.textContent,intervention==='leave'?'SYNTHETIC before':'SYNTHETIC newer returned body');if(intervention==='leave')assert.equal(await page.leaveEditors({preserveHistory:true}),true);else assert.equal(calls.filter(type=>type==='GET_LIBRARY_ENTRY').length,1,'obsolete Undo never reads or paints into the new owner');
 }finally{for(const key of keys){const descriptor=prior.get(key);if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}}
});
for(const change of ['none','data','new-freeze','new-navigation'])test(`D5 actual Reader return thaw handles ${change} without losing freeze ownership`,async()=>{
 const source=await readFile(new URL('../ui/archive.js',import.meta.url),'utf8'),fn=source.slice(source.indexOf('async function finishReaderReturn('),source.indexOf('\nlet state,view=')),callbacks=[],attempt={intent:3,window:{anchor:null,focus:null}},stream={frozen:true,epoch:0,freezeEpoch:0},context=vm.createContext({readerReturn:attempt,readerReturnMount:{unavailable:false},navigationIntent:3,editor:{recoveryReady:Promise.resolve(),entries:new Map()},readerStream:stream,readerLeaving:0,reader:{},restoreReaderFocus(){},$:()=>({hidden:false}),requestAnimationFrame:callback=>callbacks.push(callback),window:{}});
 vm.runInContext(fn,context);assert.equal(await context.finishReaderReturn(attempt),true);assert.equal(context.readerReturn,null);callbacks.shift()();if(change==='data')stream.epoch++;if(change==='new-freeze'){stream.epoch++;stream.freezeEpoch++;context.readerLeaving=1;}if(change==='new-navigation')context.navigationIntent++;callbacks.shift()();assert.equal(stream.frozen,['new-freeze','new-navigation'].includes(change));assert.equal(callbacks.length,0);
});
for(const outcome of ['refused','superseded','accepted'])test(`D5 success View ${outcome} cannot cross a refused or newer compose route`,async()=>{
 const source=await readFile(new URL('../ui/archive.js',import.meta.url),'utf8'),fn=source.slice(source.indexOf('async function openThoughtNotice('),source.indexOf('\ntopicActions.onAdded=')),calls=[],context=vm.createContext({navigationIntent:0,view:'thought-compose',thoughts:{openStandalone:async(id,{isCurrent})=>{assert.equal(isCurrent(),true);calls.push(id);},open:async id=>calls.push(id)}});
 context.navigate=async(view,id,ctx,options)=>{if(outcome==='refused')return false;options.navigationResult.intent=1;context.navigationIntent=outcome==='superseded'?2:1;context.view='thoughts';return true;};vm.runInContext(fn,context);await context.openThoughtNotice('entry','synthetic-created');assert.deepEqual(calls,outcome==='accepted'?['synthetic-created']:[]);
});
