import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,capture,inputEdit} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {DocumentEditor} from '../ui/library.js';
import {WorkingInputSaveSession} from '../ui/working-input-save.js';
import {RevisionSession} from '../ui/editor-primitives.js';
async function fixture(){const {s}=await setup(OrganizerStore),initial=await s.snapshot(),b=initial.library.blocks[0];await inputEdit(s,b.id,{libraryText:'SYNTHETIC working version'});const revision=(await s.revisions({documentId:b.documentId,kind:'input',entityId:b.id})).items.find(r=>r.reason!=='baseline');return {s,b,initial,revision,prepared:await s.prepareWorkingRevision({id:revision.id,documentId:b.documentId,side:'before'})};}
test('Working revision preparation is readonly, resolves actual Source for a null historical body, and commits once via existing receipt',async()=>{
 const {s,b,initial,revision,prepared}=await fixture(),before=await s.snapshot(),history=await s.revisions({documentId:b.documentId});
 assert.equal(prepared.historical.libraryText,null);assert.equal(prepared.records.find(r=>r.id===prepared.historical.originalTextReference).originalText,initial.records[0].originalText);assert.equal(prepared.current.libraryText,'SYNTHETIC working version');assert.equal(prepared.edit.blocks[0].expectedRevision,1);
 assert.deepEqual(await s.snapshot(),before);assert.deepEqual(await s.revisions({documentId:b.documentId}),history);
 const send=async(type,args)=>type==='EDIT_DOCUMENT'?s.editDocument(args.edit):s.operationOutcome(args.query),session=new WorkingInputSaveSession(send);await session.stage(prepared.edit,await s.recoveryDraftEpoch());await session.save(prepared.edit,await s.recoveryDraftEpoch());await s.editDocument(prepared.edit);
 assert.equal((await s.input(b.id)).revision,2);assert.equal((await s.input(b.id)).libraryText,null);assert.deepEqual((await s.snapshot()).records,initial.records);const later=await s.revisions({documentId:b.documentId});assert.ok(later.items.some(r=>r.id===revision.id));assert.equal(later.items.filter(r=>r.reason==='restore').length,1);
});
test('Prepared historical snapshot revalidates exact entity, side, content, provenance and fresh base at commit',async()=>{
 const {s,b,prepared,revision}=await fixture();
 for(const changed of [{restoreRevisionSide:'other'},{blocks:[{...prepared.edit.blocks[0],libraryText:'SYNTHETIC forged words'}]},{title:'Forged title'},{documentId:'different-owner'},{blocks:[...prepared.edit.blocks,prepared.edit.blocks[0]]}])await assert.rejects(s.editDocument({...prepared.edit,...changed,operationId:crypto.randomUUID()}),{code:'INVALID_REQUEST'});
 for(const request of [{id:revision.id,documentId:'other',side:'before'},{id:revision.id,documentId:b.documentId,side:'before',body:'extra'}])await assert.rejects(s.prepareWorkingRevision(request),{code:'INVALID_REQUEST'});
 await inputEdit(s,b.id,{note:'SYNTHETIC concurrent note'});assert.deepEqual(await s.editDocument({...prepared.edit,operationId:crypto.randomUUID()}),{conflict:true});assert.equal((await s.input(b.id)).libraryText,'SYNTHETIC working version');
 await s.repository.transaction(true,async t=>{const r=await t.get('revisions',revision.id);r.before.note='SYNTHETIC changed coalesced history';await t.put('revisions',r);});await assert.rejects(s.editDocument({...prepared.edit,operationId:crypto.randomUUID()}),{code:'INVALID_REQUEST'});
});
test('Removed Input and title restore prepare the actual owner, while purge cannot resurrect historical Source',async()=>{
 const {s,b}=await fixture();await inputEdit(s,b.id,{excluded:true});const removal=(await s.revisions({documentId:b.documentId})).items.find(r=>r.reason==='remove'),prepared=await s.prepareWorkingRevision({id:removal.id,documentId:b.documentId,side:'before'});assert.equal(prepared.current.excluded,true);assert.equal(prepared.edit.blocks[0].excluded,false);await s.editDocument(prepared.edit);assert.equal((await s.input(b.id)).excluded,false);
 let doc=(await s.snapshot()).conversations.find(d=>d.id===b.documentId);await s.editDocument({documentId:doc.id,title:'SYNTHETIC changed title',expectedTitleRevision:doc.titleRevision,blocks:[],operationId:crypto.randomUUID()});const rev=(await s.revisions({documentId:doc.id,kind:'title',entityId:doc.id})).items[0],title=await s.prepareWorkingRevision({id:rev.id,documentId:doc.id,side:'before'});assert.equal(title.kind,'title');assert.deepEqual(title.edit.blocks,[]);await s.editDocument(title.edit);assert.equal((await s.snapshot()).conversations.find(d=>d.id===doc.id).userTitle,'');
 await s.permanentDelete(b.sourceRecordId);await assert.rejects(s.prepareWorkingRevision({id:removal.id,documentId:b.documentId,side:'before'}),{code:'INVALID_REQUEST'});await assert.rejects(s.editDocument({...prepared.edit,operationId:crypto.randomUUID()}),{code:'INVALID_REQUEST'});
});
function editorFor(b,prepared,send,epoch){const e=Object.create(DocumentEditor.prototype),current=prepared.current;Object.assign(e,{id:b.documentId,title:'',savedTitle:'',titleRevision:0,entries:new Map([[b.id,{revision:prepared.edit.blocks[0].expectedRevision,saved:{libraryText:current.libraryText,note:current.note,excluded:current.excluded},local:{libraryText:current.libraryText,note:current.note,excluded:current.excluded},original:prepared.records[0].originalText,signature:b.provenanceSignature}]]),saveSession:new WorkingInputSaveSession(send),revisions:new RevisionSession(),autosave:{cancel(){}},collect(){},paint(){},field:()=>null,onStatus(){},onRecovered(){},recovery:{epoch,protect:async()=>{},clear:async()=>{}},admitRecoveryInputs:async()=>{}});return e;}
test('One DocumentEditor retains staged restore digest and newer draft in its existing recovery row; unknown is not a new command',async()=>{
 const {s,b,prepared}=await fixture(),epoch=await s.recoveryDraftEpoch();let writes=0,allow=false,recovery;
 const send=async(type,args)=>{if(type==='EDIT_DOCUMENT'){writes++;await s.editDocument(args.edit);throw Error('SYNTHETIC lost acknowledgement');}if(!allow)throw Error('SYNTHETIC lost readback');return s.operationOutcome(args.query);};
 const e=editorFor(b,prepared,send,epoch);e.recovery.protect=async(operation,token)=>recovery={operation,token};
 assert.equal(await e.restorePrepared(prepared),false);assert.equal(writes,1);assert.equal(e.saveSession.unresolved,true);assert.equal(e.buildEdit(),prepared.edit);assert.deepEqual(JSON.parse(recovery.operation.pendingRequest),prepared.edit);
 e.entries.get(b.id).local.libraryText='SYNTHETIC newer typing after uncertain restore';await e.protectRecovery();assert.equal(recovery.operation.edit.blocks[0].libraryText,'SYNTHETIC newer typing after uncertain restore');assert.deepEqual(JSON.parse(recovery.operation.pendingRequest),prepared.edit);assert.notEqual(recovery.operation.edit.operationId,prepared.edit.operationId);
 e.failed=false;assert.equal(await e.flush(),false);assert.equal(writes,1);allow=true;e.failed=false;assert.equal(await e.flush(),true);assert.equal(writes,2);assert.equal((await s.input(b.id)).revision,3);assert.equal((await s.input(b.id)).libraryText,'SYNTHETIC newer typing after uncertain restore');
});
test('Restarted restore recovery reconciles the original operation before saving the newer local draft',async()=>{
 const {s,b,prepared}=await fixture(),epoch=await s.recoveryDraftEpoch();await s.editDocument(prepared.edit);const latest={operationId:crypto.randomUUID(),documentId:b.documentId,blocks:[{...prepared.edit.blocks[0],libraryText:'SYNTHETIC later recovery draft'}]};let writes=0;
 const e=editorFor(b,prepared,async(type,args)=>{if(type==='EDIT_DOCUMENT'){writes++;return s.editDocument(args.edit);}return s.operationOutcome(args.query);},epoch);const stored={token:latest.operationId,operation:{type:'EDIT_DOCUMENT',edit:latest,pendingRequest:JSON.stringify(prepared.edit)}};const roundtrip=value=>Array.isArray(value)?value.map(roundtrip):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,roundtrip(value[k])])):value;e.recovery.load=async()=>roundtrip(stored);assert.equal(await e.restoreRecovery(),true);await new Promise(resolve=>setImmediate(resolve));if(e.pending)await e.pending;assert.equal(writes,1);assert.equal((await s.input(b.id)).libraryText,'SYNTHETIC later recovery draft');assert.equal((await s.input(b.id)).revision,3);
});

test('Restore transaction abort leaves Source, Current, revisions and removal intent unchanged; retry uses the same existing operation',async()=>{
 const {s,b,prepared}=await fixture(),before=await s.snapshot(),history=await s.revisions({documentId:b.documentId}),hook=s.afterInputEdit.bind(s);let abort=true,writes=0;
 s.afterInputEdit=async(...args)=>{await hook(...args);if(abort)throw Error('SYNTHETIC transaction abort after restore journal');};
 const session=new WorkingInputSaveSession(async(type,args)=>{if(type==='EDIT_DOCUMENT'){writes++;return s.editDocument(args.edit);}return s.operationOutcome(args.query);});await assert.rejects(session.save(prepared.edit,await s.recoveryDraftEpoch()));assert.equal(session.pending.state,'not_committed');const after=await s.snapshot();for(const key of ['records','library','conversations','tombstones','sourceTimes','settings','preferences'])assert.deepEqual(after[key],before[key],key);assert.ok(after.diagnostics.lastError,'the failed transaction still retains diagnostics');assert.deepEqual(await s.revisions({documentId:b.documentId}),history);assert.equal(await s.repository.transaction(false,t=>t.count('inputRemovals')),0);
 abort=false;await session.save({...prepared.edit,operationId:crypto.randomUUID()},await s.recoveryDraftEpoch());assert.equal(writes,2);assert.equal((await s.input(b.id)).revision,prepared.edit.blocks[0].expectedRevision+1);assert.equal((await s.revisions({documentId:b.documentId})).items.filter(r=>r.reason==='restore').length,1);
});
test('Restart unknown restore remains fail closed with latest human draft and no write; recovery pending source union is trusted',async()=>{
 const {s,b,prepared}=await fixture(),epoch=await s.recoveryDraftEpoch(),latest={operationId:crypto.randomUUID(),documentId:b.documentId,blocks:[{...prepared.edit.blocks[0],libraryText:'SYNTHETIC retained newer draft'}]};let writes=0;
 const e=editorFor(b,prepared,async type=>{if(type==='EDIT_DOCUMENT'){writes++;throw Error('Unexpected restore retry');}return {state:'unknown'};},epoch);e.recovery.load=async()=>({token:latest.operationId,operation:{type:'EDIT_DOCUMENT',edit:latest,pendingRequest:JSON.stringify(prepared.edit)}});assert.equal(await e.restoreRecovery(),false);assert.equal(writes,0);assert.equal(e.saveSession.unresolved,true);assert.equal(e.entries.get(b.id).local.libraryText,latest.blocks[0].libraryText);assert.equal((await s.input(b.id)).revision,1);
 const draft={kind:'document',ownerId:b.documentId,sourceRecordIds:[],operation:{type:'EDIT_DOCUMENT',edit:{...latest,blocks:[]},pendingRequest:JSON.stringify(prepared.edit)}};assert.deepEqual(await s.recoveryDraftSourceIds(draft),[b.sourceRecordId]);await assert.rejects(s.recoveryDraftSourceIds({...draft,operation:{...draft.operation,pendingRequest:JSON.stringify({...prepared.edit,documentId:'other-owner'})}}),{code:'INVALID_REQUEST'});
 await s.permanentDelete(b.sourceRecordId);await assert.rejects(s.recoveryDraftSourceIds(draft),{code:'INVALID_REQUEST'});
});
