import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {evolutionPlan,evolutionEntryIds,evolutionDateLabel,expressionTime,EVOLUTION_ENTRY_LIMIT} from '../ui/evolution-model.js';import {aiSynthesisPrompt,AI_SCHEMA_VERSION,AI_FIELDS} from '../core/organizer/ai-contract.js';
const entry=(id,body='未确认的表达',extra={})=>({id,body,lifecycle:'active',...extra});
test('Round 7 preserves complete long prose and one editable occurrence per entry',()=>{const long='长内容。'.repeat(6000),a=entry('a',long,{sourceSentAt:'2020-01-01T00:00:00Z'}),b=entry('b');const p=evolutionPlan({possibleEvolution:[{text:'提出问题',evidenceEntryIds:['a']},{text:'仍在探索',evidenceEntryIds:['a','b']}],evidenceEntryIds:['a','b']},[a,b]);assert.equal(p.stages[0].items[0].body,long);assert.deepEqual(p.stages[1].items.map(x=>x.id),['b']);assert.equal(p.stages[0].dates[0],Date.parse(a.sourceSentAt));});
test('Round 7 excludes removed/purged text and never invents stages for old caches',()=>{const p=evolutionPlan({possibleEvolution:[]},[entry('a','后',{sourceSentAt:'2024-01-01T00:00:00Z'}),entry('b','前',{sourceSentAt:'2020-01-01T00:00:00Z'}),entry('x','removed',{lifecycle:'removed'}),entry('y','purged',{staleReasons:['source_purged']})]);assert.equal(p.inferred,false);assert.deepEqual(p.stages.map(s=>s.items[0].id),['b','a']);assert.ok(p.stages.every(s=>s.text===''));});
test('Round 7 expression chronology never substitutes capture or generation time',()=>{const p=evolutionPlan({possibleEvolution:[{text:'尚未确定',evidenceEntryIds:['a']}]},[entry('a','不确定',{createdAt:'2026-09-12T00:00:00Z',capturedAt:'2026-09-12T00:00:00Z'})]);assert.deepEqual(p.stages[0].dates,[]);assert.equal(evolutionDateLabel([]),'日期未确定');assert.equal(expressionTime('yesterday'),null);assert.equal(expressionTime('2024-01-01'),null);assert.equal(expressionTime(0),0);});
test('Round 7 bounded local reads prioritize evolution references without deleting leftovers',()=>{const ids=Array.from({length:120},(_,i)=>'e'+i),r={evidenceEntryIds:ids,possibleEvolution:[{evidenceEntryIds:['stage']}]};assert.equal(evolutionEntryIds(r).length,EVOLUTION_ENTRY_LIMIT);assert.equal(evolutionEntryIds(r)[0],'stage');const p=evolutionPlan({possibleEvolution:[{text:'一段',evidenceEntryIds:['a']}]},[entry('a'),entry('b')]);assert.deepEqual(p.remaining.map(x=>x.id),['b']);});
test('Round 7 schema compatibility preserves old supported fields',()=>{assert.equal(AI_SCHEMA_VERSION,1);assert.ok(AI_FIELDS.includes('judgments'));assert.match(aiSynthesisPrompt(),/overview plus an evolution of the supplied expressions/);assert.match(aiSynthesisPrompt(),/never assert supersession/);});
test('Round 7 bounded cancellable motion contains no provider request or timer wait',async()=>{const motion=await readFile(new URL('../ui/memory-recomposition.js',import.meta.url),'utf8');assert.match(motion,/720/);assert.match(motion,/prefers-reduced-motion/);assert.match(motion,/skipTransition/);assert.doesNotMatch(motion,/fetch\(|UPDATE_AI|UPDATE_ORIGINAL|setTimeout\(/);const css=await readFile(new URL('../ui/experience.css',import.meta.url),'utf8');assert.doesNotMatch(css,/url\(/);assert.match(css,/paia-settle/);assert.match(css,/filter:blur\(0\)/);});
