import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,mkdir,writeFile,readdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';import {FakeChatGPT,eventually,conversation} from './harness/fake-chatgpt.mjs';
for(const kind of ['internal','release-structure'])test('M5 '+kind+' Foundation artifact actual Chrome capture, settings, Library and provider fence',{timeout:90000},async()=>{
 const parent=await mkdtemp(join(tmpdir(),'paia-m5-build-')),dir=join(parent,'PAIA-v0.7.0-foundation-'+kind);let h;
 try{
 execFileSync('python3',['-c',"import sys;sys.path.insert(0,'scripts');from build_foundation import build_foundation,archive_foundation;build_foundation(sys.argv[1],sys.argv[2],sys.argv[3]);archive_foundation(sys.argv[2])",process.cwd(),dir,kind]);
 assert.ok((await readFile(dir+'.zip')).length>0);assert.ok((await readFile(dir+'.zip.sha256','utf8')).includes('PAIA-v0.7.0-foundation-'+kind+'.zip'));
 const manifest=JSON.parse(await readFile(join(dir,'manifest.json'))),original=JSON.parse(await readFile('manifest.json'));for(const key of ['permissions','host_permissions','optional_permissions','content_security_policy','content_scripts'])assert.deepEqual(manifest[key],original[key]);assert.equal(manifest.version,'0.7.0');
 const paths=await readdir(dir,{recursive:true});assert.ok(!paths.some(p=>/(^|\/)(tests|fixtures|development)\//.test(p)));const workerText=await readFile(join(dir,'background/service-worker.js'),'utf8');assert.ok(!workerText.includes('DeterministicFixtureProvider'));assert.ok(!workerText.includes('m3Synthetic'));
 if(kind==='release-structure'){assert.ok(!paths.some(p=>/response-time\.(html|css)$|development-reload|structure-diagnostics|response-diagnostics/.test(p)));assert.ok(!workerText.includes('RESPONSE_ARM'));assert.ok(!workerText.includes("case 'FILTER_DIAGNOSTICS'"));}
 h=await FakeChatGPT.start({extensionPath:dir,headless:false});const p=h.archive;await p.setViewportSize({width:1280,height:960});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await h.open(conversation('m5-'+kind+'-synthetic'));await eventually(async()=>(await h.state()).records.length===3);
 const send=(type,data={})=>p.evaluate(({type,data})=>chrome.runtime.sendMessage({type,...data}),{type,data});
 assert.equal((await send('ORGANIZER_RUN')).ok,false);const created=await send('CREATE_LIBRARY_ENTRY',{entry:{operationId:crypto.randomUUID(),body:'合成验收：Foundation 已就绪，整理服务尚未配置。',type:'idea'}});assert.equal(created.ok,true);
 await p.locator('.sidebar [data-view=settings]').click();await p.getByText('Thought Library Foundation available · AI Organizer not configured / not enabled',{exact:true}).waitFor();if(kind==='internal'&&!await p.locator('#toggle-capture').isVisible())await p.locator('#diagnostics summary').click();await p.locator('#toggle-capture').click();await eventually(async()=>(await h.state()).settings.enabled===false);await p.locator('#toggle-capture').click();await eventually(async()=>(await h.state()).settings.enabled===true);
 if(kind==='release-structure'){assert.equal(await p.locator('#diagnostics,#filter-diagnostics,a[href="response-time.html"]').count(),0);assert.equal((await send('FILTER_DIAGNOSTICS')).ok,false);}
 await mkdir('work/m5-ui',{recursive:true});await p.screenshot({path:`work/m5-ui/${kind}-settings.png`,fullPage:true});await p.locator('[data-view=thoughts]').click();await p.screenshot({path:`work/m5-ui/${kind}-library.png`,fullPage:true});
 const popup=await h.context.newPage();await popup.goto(`chrome-extension://${h.extensionId}/ui/popup.html`);await popup.locator('#record-count').getByText('3',{exact:true}).waitFor();assert.equal(await popup.locator('#development-reload').count(),kind==='internal'?1:0);if(kind==='release-structure')assert.equal(await popup.locator('#diagnostic-status').count(),0);
 assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);await writeFile(`work/m5-ui/${kind}.json`,JSON.stringify({kind,version:manifest.version,syntheticOnly:true,visibleChrome:true,capture:true,pauseResume:true,manualEntry:true,productionRunRejected:true,permissionsUnchanged:true,networkRequests:h.extensionNetworkRequests,errors:h.errors},null,2));
 }finally{await h?.close();await rm(parent,{recursive:true,force:true});}
});
