import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {FakeChatGPT} from './harness/fake-chatgpt.mjs';
test('M5 actual Chrome v3/v4 full nonempty field matrix, empty/unknown Thought, crash/resume and rerun',{timeout:120000},async()=>{
 const h=await FakeChatGPT.start();try{const reports=[];for(const version of [3,4])for(const populated of [false,true])for(const phase of ['thoughts','dependencies','verify']){
 const r=await h.archive.evaluate(async({version,populated,phase})=>{
 const {IAStore}=await import('../core/ia-store.js'),{SmartFilterStore}=await import('../core/smart-filter-store.js'),{OrganizerStore}=await import('../core/organizer/store.js');let values={};const local={async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}},name=`synthetic-m5-migration-${version}-${populated}-${phase}`,Old=version===3?IAStore:SmartFilterStore,old=new Old(local,{name});await old.consent(true);await old.capture({epoch:(await old.status()).epoch,adapterVersion:'0.3.0',chat:{id:'m5-migration',url:'https://chatgpt.com/c/m5-migration',title:'Synthetic source title'},messages:[{sourceMessageId:'synthetic-kept',pageOrder:1,originalText:'Synthetic immutable original'}]});const b=(await old.snapshot()).library.blocks[0];await old.editDocument({operationId:crypto.randomUUID(),documentId:b.documentId,blocks:[{id:b.id,expectedRevision:0,libraryText:'Synthetic retained edit',note:'Synthetic retained note',excluded:false}]});await old.updateDocument(b.documentId,{userTitle:'Synthetic authored title'});
 // Explicit synthetic legacy records exercise preservation even when the reader does not interpret their schema.
 const extra=['inputRemovals','tombstones','importTasks','importBatches','importEvidence','importSources',...(version===4?['filterInputs','filterIntents']:[])];await old.repository.transaction(true,async t=>{for(const table of extra)await t.put(table,{id:'synthetic-preserve-'+table,sourceKey:'a'.repeat(64),checkpoint:17,status:'paused',version:2,decision:'keep',userWork:{note:'Synthetic preserved'},sourceSentAt:1700000000000,capturedAt:1700000001000});});
 if(populated){await old.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic legacy thought',note:'Legacy note',title:'Legacy title'});await old.repository.transaction(true,t=>t.put('thoughts',{id:'synthetic-unknown',experimentalPayload:{text:'Synthetic unknown legacy payload'}}));}
 const tables=['records','recordIndex','blocks','blockIndex','times','documents','libraryDocuments','inputStates','inputRemovals','revisions','tombstones','importTasks','importBatches','importEvidence','importSources',...(version===4?['filterInputs','filterIntents']:[])];const dump=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(tables.map(async n=>[n,await t.all(n)]))));const before=await dump(old);const controls=JSON.stringify(values);await old.repository.close();let crashed=false;const interrupted=new OrganizerStore(local,{name,checkpoint:async n=>{if(n==='thought-migration-'+phase){crashed=true;throw Error('SYNTHETIC_CRASH');}}});try{await interrupted.libraryStatus();}catch{}await interrupted.repository.close();
 const resumed=new OrganizerStore(local,{name});const marker=await resumed.libraryStatus(),after=await dump(resumed),thoughts=await resumed.repository.transaction(false,t=>t.all('thoughts'));await resumed.repository.close();const rerun=new OrganizerStore(local,{name});await rerun.libraryStatus();const twice=await rerun.repository.transaction(false,t=>t.all('thoughts'));const equality=Object.fromEntries(tables.map(n=>[n,JSON.stringify(before[n])===JSON.stringify(after[n])]));await rerun.repository.close();return {version,populated,phase,crashed,marker,equality,nonemptyTables:tables.filter(n=>before[n].length),controlEquality:controls===JSON.stringify(values),idempotent:JSON.stringify(thoughts)===JSON.stringify(twice),thoughtCount:thoughts.length,unknownSealed:!populated||thoughts.find(x=>x.id==='synthetic-unknown')?.quarantineSealed===true};
 },{version,populated,phase});assert.equal(r.crashed,true);assert.equal(r.marker.verified,true);assert.ok(Object.values(r.equality).every(Boolean));assert.equal(r.controlEquality,true);assert.equal(r.idempotent,true);assert.equal(r.unknownSealed,true);assert.equal(r.thoughtCount,populated?2:0);reports.push(r);}
 await mkdir('work',{recursive:true});await writeFile('work/v070-m5-migration.json',JSON.stringify({syntheticOnly:true,chrome:(await h.cdp.send('Browser.getVersion')).product,reports},null,2));assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
 }finally{await h.close();}
});
