import test from 'node:test';
import assert from 'node:assert/strict';
import {DocumentEditor} from '../ui/library.js';
import {NativeLineBreakTracker,editableTextSnapshot} from '../ui/editable-text.js';
import {UndoJournal} from '../ui/editor-primitives.js';

function fixture({body='OLD\n\nWORK',reverse=false,unresolved=false}={}){
 const prior=globalThis.document,metrics={scheduled:0,recovery:0,notifications:0,changes:0,status:[]};let selection,editor;
 const title={innerText:'SYNTHETIC title'},section={hidden:false},field={nodeType:1,nodeName:'DIV',dataset:{editId:'working'},isContentEditable:true,isConnected:true,childNodes:[],closest:selector=>selector==='.library-block'?section:selector==='[data-edit-id]'?field:null,contains:node=>node===field||field.childNodes.includes(node)};
 Object.defineProperties(field,{textContent:{get:()=>field.childNodes.map(node=>node.data||'').join(''),set:value=>{const previous=field.childNodes;field.childNodes=value?[{nodeType:3,nodeName:'#text',data:value,parentNode:field}]:[];if(selection&&(previous.includes(selection.anchorNode)||previous.includes(selection.focusNode)))selection.setBaseAndExtent(field,0,field,0);}},innerText:{get:()=>field.textContent}});field.textContent=body;
 let range={startContainer:field.firstChild||field.childNodes[0]||field,startOffset:0,endContainer:field.childNodes[0]||field,endOffset:body.length,intersectsNode:node=>node===field};
 Object.defineProperty(field,'firstChild',{get:()=>field.childNodes[0]||null});
 selection={rangeCount:1,isCollapsed:false,anchorNode:range.startContainer,anchorOffset:reverse?body.length:0,focusNode:range.endContainer,focusOffset:reverse?0:body.length,getRangeAt:()=>range,setBaseAndExtent(a,x,f,y){this.anchorNode=a;this.anchorOffset=x;this.focusNode=f;this.focusOffset=y;this.isCollapsed=a===f&&x===y;range={startContainer:a,startOffset:x,endContainer:f,endOffset:y,intersectsNode:node=>node===field};}};
 const fields=[field],root={contains:node=>node===root||node===title||fields.some(field=>field.contains(node)),querySelector:selector=>selector==='#document-title'?title:null,querySelectorAll:()=>fields};
 editor=Object.create(DocumentEditor.prototype);Object.assign(editor,{root,id:'document',nativeLines:new NativeLineBreakTracker(),journal:new UndoJournal(),title:'',savedTitle:'',originalTitle:'SYNTHETIC title',entries:new Map([['working',{saved:{libraryText:body,note:'KEEP NOTE',excluded:false},local:{libraryText:body,note:'KEEP NOTE',excluded:false},original:'IMMUTABLE SOURCE',revision:7}]]),saveSession:{unresolved},autosave:{schedule(){metrics.scheduled++;}},protectRecovery(){metrics.recovery++;return Promise.resolve(true);},onChange(){metrics.changes++;},onStatus(...args){metrics.status.push(args);},flush:async()=>true,composing:false,disposed:false,failed:unresolved});
 field.dispatchEvent=event=>{assert.equal(event.type,'input');assert.equal(event.isTrusted,false);metrics.notifications++;editor.collect();return true;};
 globalThis.document={getSelection:()=>selection};
 const event={type:'beforeinput',isTrusted:true,cancelable:true,defaultPrevented:false,inputType:'insertText',data:'NEW',isComposing:false,target:field,preventDefault(){this.defaultPrevented=true;}};
 return {editor,field,fields,selection,event,metrics,entry:editor.entries.get('working'),setRange:next=>{range={...range,...next};},close:()=>{if(prior===undefined)delete globalThis.document;else globalThis.document=prior;}};
}

for(const data of ['HEAD', '\n\nLEADING', '  literal <div>\t👩‍💻 é', '\nAB👩‍💻 é\n\nEND'])for(const reverse of [false,true])test('whole Input replacement preserves exact payload and one owner operation '+JSON.stringify({data,reverse}),async()=>{
 const f=fixture({reverse});try{f.event.data=data;f.editor.beforeInput(f.event);assert.equal(f.event.defaultPrevented,true);assert.equal(f.field.textContent,data);assert.equal(f.entry.local.libraryText,data);assert.equal(f.entry.local.note,'KEEP NOTE');assert.equal(f.entry.original,'IMMUTABLE SOURCE');assert.equal(f.entry.saved.libraryText,'OLD\n\nWORK');assert.equal(f.editor.undoStack.length,1);assert.equal(f.metrics.scheduled,1);assert.equal(f.metrics.recovery,1);assert.equal(f.metrics.notifications,1);assert.equal(editableTextSnapshot(f.field).offset(f.selection.anchorNode,f.selection.anchorOffset),data.length);assert.equal(f.selection.isCollapsed,true);
  f.editor.collect();assert.equal(f.editor.undoStack.length,1,'input notification cannot double-record the replacement');assert.equal(f.metrics.scheduled,1);await f.editor.history();assert.equal(f.entry.local.libraryText,'OLD\n\nWORK');assert.equal(f.field.textContent,'OLD\n\nWORK');assert.equal(editableTextSnapshot(f.field).offset(f.selection.anchorNode,f.selection.anchorOffset),0,'existing paint keeps the caret inside the same field');await f.editor.history(true);assert.equal(f.field.textContent,data);assert.equal(f.entry.local.libraryText,data);assert.equal(editableTextSnapshot(f.field).offset(f.selection.anchorNode,f.selection.anchorOffset),0);assert.equal(f.entry.original,'IMMUTABLE SOURCE');
 }finally{f.close();}
});

const refusals={'empty payload':f=>f.event.data='','one empty line':f=>f.event.data='\n','two empty lines':f=>f.event.data='\n\n','authored terminal LF':f=>f.event.data='\n\nLEADING\n','literal Unicode with terminal LF':f=>f.event.data='  literal <div>\t👩‍💻 é\n\n',untrusted:f=>f.event.isTrusted=false,uncancelable:f=>f.event.cancelable=false,prevented:f=>f.event.defaultPrevented=true,paste:f=>f.event.inputType='insertFromPaste',composition:f=>f.event.isComposing=true,'owner composition':f=>f.editor.composing=true,'null payload':f=>f.event.data=null,'partial range':f=>f.setRange({startOffset:1}),collapsed:f=>f.selection.isCollapsed=true,readonly:f=>f.field.isContentEditable=false,removed:f=>f.entry.local.excluded=true,locked:f=>f.editor.removalLocks=new Map(),disposed:f=>f.editor.disposed=true,'foreign endpoint':f=>f.setRange({startContainer:{nodeType:3,data:'outside'}}),'unsupported structure':f=>{f.field.childNodes=[{nodeType:1,nodeName:'TABLE',childNodes:[]}];}};
for(const [name,configure]of Object.entries(refusals))test('whole Input owner refuses '+name+' without replacing DOM or bypassing recovery',()=>{
 const f=fixture();try{configure(f);const nodes=f.field.childNodes,local=structuredClone(f.entry.local),prevented=f.event.defaultPrevented;f.editor.beforeInput(f.event);assert.equal(f.event.defaultPrevented,prevented);assert.equal(f.field.childNodes,nodes);assert.deepEqual(f.entry.local,local);assert.equal(f.editor.undoStack.length,0);assert.equal(f.metrics.notifications,0);assert.equal(f.metrics.scheduled,0);assert.equal(f.metrics.recovery,0);}finally{f.close();}
});
test('cross-Input replacement retains the existing boundary refusal and both bodies',()=>{
 const f=fixture();try{const other={...f.field,dataset:{editId:'other'},closest:selector=>selector==='.library-block'?{hidden:false}:other,contains:node=>node===other};f.fields.push(other);f.setRange({endContainer:other,endOffset:0,intersectsNode:node=>f.fields.includes(node)});f.editor.beforeInput(f.event);assert.equal(f.event.defaultPrevented,true);assert.equal(f.field.textContent,'OLD\n\nWORK');assert.equal(f.editor.undoStack.length,0);assert.equal(f.metrics.status.at(-1)[1],'boundary');assert.equal(f.metrics.notifications,0);}finally{f.close();}
});
test('an interrupted save retains its unresolved owner while protecting the new whole Input draft',()=>{
 const f=fixture({unresolved:true});try{f.editor.beforeInput(f.event);assert.equal(f.event.defaultPrevented,true);assert.equal(f.entry.local.libraryText,'NEW');assert.equal(f.entry.saved.libraryText,'OLD\n\nWORK');assert.equal(f.editor.saveSession.unresolved,true);assert.equal(f.editor.failed,true);assert.equal(f.metrics.scheduled,0);assert.equal(f.metrics.recovery,1);assert.equal(f.metrics.status.length,0);assert.equal(f.editor.undoStack.length,1);}finally{f.close();}
});
