import {pinLegacy} from './harness/reading-closure.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';
import {productHistory,productReply} from './fixtures/product-history-v080.mjs';
const out='work/v081-governance-e2e/',op=()=>crypto.randomUUID();
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const menu=async(p,id,label)=>{const tile=p.locator('.topic-tile').filter({has:p.locator(`[data-topic-id="${id}"]`)});await tile.locator('summary').click();await tile.getByRole('button',{name:label,exact:true}).click();};
test('visible Topic grid actions, local Markdown export, container delete/unplaced/restore and canonical merge',{timeout:120000},async()=>{
 await mkdir(out,{recursive:true});const h=await FakeChatGPT.start({headless:false,deepSeekFixture:productReply}),p=h.archive;
 try{
  await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await rpc(p,'FILTER_MODE',{mode:'off'});await h.open({id:'governance-v081',title:'虚构主题治理',base:1785542400,messages:productHistory});await eventually(async()=>(await h.state()).records.length===50);await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-governance-key'}});await rpc(p,'START_BOUNDED_ORGANIZER',{options:{kind:'original',userActionId:op(),maxRequests:3,maxInputs:50}});await p.locator('[data-view=thoughts]').click();await eventually(async()=>await p.locator('.topic-index-row').count()===5);
  const topics=(await rpc(p,'LIBRARY_INDEX_PAGE')).items,topic=topics[0],before=(await rpc(p,'TOPIC_DOCUMENT_PAGE',{options:{topicId:topic.id,sort:'asc'}})).items.map(x=>[x.entry.id,x.entry.body]);
  await pinLegacy(p,topic.id);assert.equal((await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).pinKey,0);await menu(p,topic.id,'重命名');await p.getByRole('textbox',{name:'主题名称',exact:true}).fill('我维护的合成主题');await p.locator('#library-form button[type=submit]').click();await eventually(async()=>await p.locator(`[data-topic-id="${topic.id}"] strong`).textContent()==='我维护的合成主题');await p.screenshot({path:out+'01-grid-management.png',fullPage:true});
  await menu(p,topic.id,'导出主题');assert.equal(await p.locator('[name=ai]').inputValue(),'no');const download=p.waitForEvent('download');await p.locator('#library-form button[type=submit]').click();const file=await download;await file.saveAs(out+'synthetic-topic.md');const markdown=await readFile(out+'synthetic-topic.md','utf8');assert.ok(markdown.startsWith('# 我维护的合成主题\n'));assert.match(markdown,/## /);assert.doesNotMatch(markdown,/AI整理（已保存）/);for(const [,body] of before)assert.ok(markdown.includes(body));assert.equal(h.deepSeekRequests.length,3);
  await menu(p,topic.id,'删除主题');await p.locator('#library-dialog').waitFor({state:'visible'});assert.match(await p.locator('#library-dialog-content').textContent(),/正文.*不会删除/);await p.locator('#library-form button[type=submit]').click();await eventually(async()=>await p.locator('.topic-index-row').count()===4);for(const [id,body]of before)assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id})).body,body);await p.locator('#library-unplaced').click();await eventually(async()=>await p.locator('#library-unplaced-list button').count()>0);while(await p.locator('.unplaced-more').count()){const more=p.locator('.unplaced-more');await more.click();await eventually(async()=>await more.count()===0);}assert.equal(await p.locator('[data-unplaced-id]').count(),before.length);assert.equal(new Set(await p.locator('[data-unplaced-id]').evaluateAll(ns=>ns.map(n=>n.dataset.unplacedId))).size,before.length);await p.screenshot({path:out+'02-unplaced-content.png',fullPage:true});
  await p.locator('.sidebar [data-view=settings]').click();await p.locator('#library-management > summary').click();await p.locator('#library-removed-topics').click();await eventually(async()=>await p.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).count()===1);await p.screenshot({path:out+'03-recover-topic.png',fullPage:true});await p.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_REMOVED_TOPICS')).items.length===0);assert.equal((await rpc(p,'GET_LIBRARY_UNPLACED')).items.length,0);await p.locator('[data-view=thoughts]').click();await eventually(async()=>await p.locator('.topic-index-row').count()===5);
  const canonical=topics[1];await menu(p,topic.id,'合并主题');await p.locator('[name=survivorId]').selectOption(canonical.id);await p.screenshot({path:out+'04-choose-canonical.png',fullPage:true});await p.locator('#library-form button[type=submit]').click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id})).id===canonical.id);for(const [id,body]of before)assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id})).body,body);const history=(await rpc(p,'GET_REVISIONS',{options:{kind:'topic',entityId:topic.id}})).items;assert.ok(['delete','restore','merge'].every(reason=>history.some(r=>r.reason===reason)));assert.equal(h.deepSeekRequests.length,3);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);
  await writeFile(out+'acceptance.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,inputs:50,topicsBefore:5,topicsAfter:4,pin:true,rename:true,markdown:true,containerDelete:true,unplaced:true,restore:true,canonicalMerge:true,sourceAndBodyPreserved:true,managementAPIRequests:0,externalRequests:h.externalRequests,errors:h.errors},null,2));
 }catch(e){await p.screenshot({path:out+'failure.png',fullPage:true}).catch(()=>{});await writeFile(out+'failure.json',JSON.stringify({message:e.message,errors:h.errors},null,2));throw e;}finally{await h.close();}
});
