import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {completeFixture,rows} from './harness/original-complete.mjs';import {ImportCoordinator} from '../core/import/coordinator.js';import {ImportLedger} from '../core/import/ledger.js';import {officialExportAdapter} from '../core/import/chatgpt-export.js';import {conversation,historyFile} from './fixtures/history-v090.mjs';
for(const n of [1000,10000])test(n+' synthetic historical Inputs: bounded batches, direct reading/search and idempotent repeat',{timeout:process.env.CI?240000:180000},async()=>{
 const f=await completeFixture({texts:[]}),ledger=new ImportLedger(f.s),batchTimes=[];let maxRows=0,maxBytes=0;
 const logStage=(stage,started)=>{if(process.env.CI&&n===10000)console.log('[history-performance] '+stage+' '+Math.round(performance.now()-started)+'ms');};
 const transport=async(m,q)=>{if(q.rows){maxRows=Math.max(maxRows,q.rows.length);maxBytes=Math.max(maxBytes,new TextEncoder().encode(q.rows.map(x=>x.text+x.title).join('')).length);}const at=performance.now(),r=await ledger[m](q,'performance-page');if(m==='commit')batchTimes.push(performance.now()-at);return r;};
 const controller=new ImportCoordinator({adapter:officialExportAdapter,transport}),file=historyFile(Array.from({length:n/50},(_,i)=>conversation(i+1,50)));
 const heapBefore=process.memoryUsage().heapUsed,start=performance.now();await controller.select(file,{consent:true});const preview=await controller.preflight(),preflightMs=performance.now()-start;logStage('first-preflight',start);assert.equal((await rows(f.s,'records')).length,0);assert.equal(preview.preview.added,n);assert.ok(preview.detection.maxBufferedTextChars<=4*1024*1024);
 const commitStart=performance.now(),result=await controller.commit(),commitMs=performance.now()-commitStart;logStage('first-commit',commitStart);assert.equal(result.counts.added,n);assert.equal((await rows(f.s,'inputStates')).length,n);assert.equal((await rows(f.s,'filterInputs')).length,n);assert.equal(f.requests.length,0);assert.ok(maxRows<=32&&maxBytes<=512*1024);
 const readStart=performance.now(),page=await f.s.page({view:'library',limit:50}),doc=page.documents[0],reading=await f.s.page({view:'library',documentId:doc.id,limit:40}),readingMs=performance.now()-readStart;logStage('reading',readStart);assert.equal(reading.pageItemIds.length,40);
 const searchStart=performance.now();let cursor=null,matched=false,searchPages=0;do{const r=await f.s.searchInputs({query:(n/50)+' / 50',cursor,limit:50});searchPages++;matched||=r.items.length>0;cursor=r.nextCursor;}while(cursor);const searchMs=performance.now()-searchStart;logStage('search',searchStart);assert.equal(matched,true);
 const repeatPreflightStart=performance.now();await controller.select(file,{consent:true});await controller.preflight();logStage('repeat-preflight',repeatPreflightStart);const repeatStart=performance.now(),repeat=await controller.commit(),repeatMs=performance.now()-repeatStart;logStage('repeat-commit',repeatStart);assert.equal(repeat.counts.added,0);assert.equal(repeat.counts.duplicates,n);assert.equal((await rows(f.s,'records')).length,n);
 const task=await ledger.latest();assert.equal(task.lastImport.counts.duplicates,n);
 await mkdir('work/history-v090',{recursive:true});await writeFile('work/history-v090/performance-'+n+'.json',JSON.stringify({synthetic:true,indexedDB:'fake-indexeddb',inputs:n,fileBytes:file.size,preflightMs,commitMs,repeatMs,readingMs,searchMs,searchPages,maxRows,maxBytes,maxBatchMs:Math.max(...batchTimes),adapterPeakNodes:preview.detection.maxNodes,adapterPeakTextChars:preview.detection.maxBufferedTextChars,observedHeapDeltaMiB:(process.memoryUsage().heapUsed-heapBefore)/1024/1024,heapIncludesSyntheticFixtureAndDatabase:true,automaticProviderRequests:f.requests.length},null,2));
 // The 120 s total-commit target is a controlled-machine benchmark, not a portable
 // correctness invariant for GitHub-hosted runners + fake-indexeddb. CI therefore
 // uses a wider outer watchdog while still gating bounded batch size/bytes, every
 // commit batch, idempotence, reading/search and final data-layer results. The
 // controlled local benchmark keeps the stricter 120 s commit requirement below.
 if(!process.env.CI)assert.ok(commitMs<120000,'10k fake-IDB commit must remain below 120 seconds on the controlled benchmark');
 assert.ok(Number.isFinite(commitMs)&&commitMs>=0);assert.ok(readingMs<10000);assert.ok(batchTimes.every(x=>x<10000));
});
