import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {completeFixture,rows,response,append} from './harness/original-complete.mjs';import {exported,prepared} from './harness/backup-v081.mjs';
import {ImportCoordinator} from '../core/import/coordinator.js';import {ImportLedger} from '../core/import/ledger.js';import {officialExportAdapter} from '../core/import/chatgpt-export.js';
import {OnboardingService} from '../core/onboarding.js';import {BackupService} from '../core/backup-service.js';import {BoundedOrganizerWorkflow} from '../core/organizer/bounded-workflow.js';import {AIPresentationRunner} from '../core/organizer/ai-presentation.js';
import {conversation,historyFile} from './fixtures/history-v090.mjs';import {productHistory,productReply} from './fixtures/product-history-v080.mjs';
const op=()=>crypto.randomUUID();
test('600 historical Inputs through preview, manual protections, explicit bounded Original/AI, backup and recovery',{timeout:120000},async()=>{
 const start=performance.now(),f=await completeFixture({texts:[],batchLimit:20,fetchImpl:async(_u,init)=>response(productReply(JSON.parse(init.body)))});
 await f.s.setFilterMode('off');const onboarding=new OnboardingService(f.s);await onboarding.status();await onboarding.action('start_history');
 const conversations=Array.from({length:12},(_,i)=>{const c=conversation(i+1,50);for(const [n,node]of Object.values(c.mapping).slice(1).entries()){node.message.content.parts=[productHistory[n].text];node.message.create_time+=i*86400;}return c;});
 const first=Object.values(conversations[0].mapping).slice(1,6);for(const n of first)await append(f.s,n.message.content.parts[0],n.message.id,conversations[0].id);
 let blocks=(await rows(f.s,'blocks')).map(x=>x.value),records=(await rows(f.s,'records')).map(x=>x.value);
 const authored=blocks.find(b=>b.sourceRecordId===records.find(r=>r.sourceMessageId===first[0].message.id).id),removed=blocks.find(b=>b.sourceRecordId===records.find(r=>r.sourceMessageId===first[1].message.id).id);
 await f.s.updateLibrary(authored.id,{libraryText:'虚构人工整理：PAIA 应当保留原话、来源和后续修正。',note:'虚构人工备注'});await f.s.updateDocument(authored.documentId,{userTitle:'人工维护的历史窗口'});await f.s.excludeLibrary(removed.id,true);
 await f.s.permanentDelete(records.find(r=>r.sourceMessageId===first[2].message.id).id);await f.s.drainPurgeCleanup();await f.s.drainInvalidations();
 const ledger=new ImportLedger(f.s),controller=new ImportCoordinator({adapter:officialExportAdapter,transport:(m,q)=>ledger[m](q,'long-term-page')}),file=historyFile(conversations);
 await controller.select(file,{consent:true});const preview=await controller.preflight();assert.equal((await rows(f.s,'records')).length,4);assert.equal(preview.preview.ignored,1);
 const imported=await controller.commit();assert.equal(imported.counts.added,595);assert.equal(imported.counts.duplicates,4);assert.equal(imported.counts.ignored,1);assert.equal(imported.counts.removed,1);assert.equal(f.requests.length,0);
 assert.equal((await rows(f.s,'records')).length,599);assert.equal((await f.s.input(authored.id)).libraryText,'虚构人工整理：PAIA 应当保留原话、来源和后续修正。');assert.equal((await f.s.input(removed.id)).excluded,true);
 const beforeStatus=await f.s.originalOrganizerStatus();assert.equal(beforeStatus.pendingInput,598);assert.equal((await rows(f.s,'topics')).length,0);
 const ai=new AIPresentationRunner(f.s,{provider:f.provider,credentials:f.credentials}),bounded=new BoundedOrganizerWorkflow(f.s,{original:f.runner,ai});
 const organized=await bounded.start({userActionId:op(),kind:'original',maxRequests:3,maxInputs:50});assert.equal(organized.state,'completed');assert.equal(organized.requestsReserved,3);assert.equal(organized.completedInputs,48);assert.equal(f.requests.length,3);assert.deepEqual(f.requests.map(x=>JSON.parse(JSON.parse(x.init.body).messages[1].content).inputs.length),[20,20,8]);
 const topic=(await f.s.libraryIndexPage({mode:'all'})).items[0],entry=(await f.s.topicDocumentPage({topicId:topic.id,sort:'asc'})).items[0].entry;
 await f.s.editEntry({id:entry.id,expectedRevision:entry.revision,changes:{body:entry.body+' 虚构人工补充，不能覆盖。'},operationId:op()});
 const aiResult=await ai.wake({userActionId:op(),topicId:topic.id});assert.equal(aiResult.error,undefined,JSON.stringify(aiResult));assert.equal(f.requests.length,4);
 const userEntry=await f.s.entry(entry.id),aiStatus=await f.s.aiPresentationStatus();assert.ok(aiStatus.topics.find(t=>t.topicId===topic.id).presentation);
 await controller.select(file,{consent:true});await controller.preflight();const repeated=await controller.commit();assert.equal(repeated.counts.added,0);assert.equal(f.requests.length,4);assert.deepEqual((await f.s.entry(entry.id)).protections,userEntry.protections);
 const service=new BackupService(f.s,{appVersion:'0.9.0'}),backup=await exported(service),restored=await completeFixture({texts:[]}),restore=new BackupService(restored.s,{appVersion:'0.9.0'}),stage=await prepared(restore,backup);
 await restore.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});await restored.s.drainLibraryMaintenance();
 for(const name of ['records','blocks','thoughts','topics','provenance','inputStates','inputRemovals','tombstones','revisions'])assert.equal((await rows(restored.s,name)).length,(await rows(f.s,name)).length,name);
 assert.deepEqual(await rows(restored.s,'records'),await rows(f.s,'records'));assert.deepEqual(await rows(restored.s,'importSources'),await rows(f.s,'importSources'));assert.equal((await restored.s.entry(entry.id)).body,(await f.s.entry(entry.id)).body);assert.equal(restored.requests.length,0);
 assert.equal((await rows(restored.s,'importTasks')).length,0);assert.equal((await rows(restored.s,'importBatches')).length,0);assert.equal((await rows(restored.s,'importEvidence')).length,0);
 await mkdir('work/history-v090',{recursive:true});await writeFile('work/history-v090/long-term.json',JSON.stringify({synthetic:true,historyInputs:600,sourceCount:599,permanentTombstones:1,preservedRemovedInputs:1,preservedInputEdits:true,preservedEntryEdits:true,preImportSources:4,added:595,duplicate:4,importNetworkRequests:0,explicitOriginalRequests:3,originalInputs:48,explicitAIRequests:1,backupRoundTrip:true,rawImportStagingRestored:false,elapsedMs:performance.now()-start},null,2));
});
