import test from 'node:test';import assert from 'node:assert/strict';import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';import {LibraryDocumentsStore} from '../core/library-documents-store.js';import {local} from './harness/thought-m1.mjs';import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';import * as plans from '../core/browser-native-sync/human-library-plan.js';import {ArchiveError} from '../core/constants.js';globalThis.IDBKeyRange=IDBKeyRange;
for(const kind of ['topic','section','entry','edit','remove','restore','fixed','topic-remove','topic-restore','keep'])test('named '+kind+' writer joins the supplied transaction and preserves rollback and exact plan',async()=>{let tick=0;const s=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory(),clock:()=>new Date(Date.UTC(2026,9,9)+tick++).toISOString()});await s.consent(true);await s.finishFoundation();const core=new BrowserNativeSyncCore(s.repository,{datasetId:'synthetic-named-writer',deviceId:'synthetic-owner'});let request,prepare,view,options;
 if(kind==='topic'){request={name:'SYNTHETIC new Topic',operationId:crypto.randomUUID()};prepare=plans.prepareHumanTopicPlan;view=plans.humanTopicPlan;}
 else if(kind==='keep'){const a=await s.createTopic({name:'SYNTHETIC separate A',operationId:crypto.randomUUID()}),b=await s.createTopic({name:'SYNTHETIC separate B',operationId:crypto.randomUUID()});request={sourceId:a.id,targetId:b.id};prepare=plans.prepareHumanKeepPlan;view=plans.humanKeepPlan;}
 else if(kind.startsWith('topic-')){const q=await s.createTopic({name:'SYNTHETIC lifecycle topic',operationId:crypto.randomUUID()}),e=await s.createEntry({actor:'user',body:'SYNTHETIC attached',type:'idea',formation:'explicit',evidence:[],operationId:crypto.randomUUID()});await s.placeEntry({entryId:e.id,topicId:q.id,expectedEntryRevision:0,expectedTopicRevision:0,operationId:crypto.randomUUID()});if(kind==='topic-restore'){const {changeTopicContainer}=await import('../core/topic-governance.js');await changeTopicContainer(s,{id:q.id,expectedRevision:0,operationId:crypto.randomUUID()});}request={id:q.id,expectedRevision:kind==='topic-restore'?1:0,operationId:crypto.randomUUID()};prepare=plans.prepareHumanTopicLifecyclePlan;view=plans.humanTopicLifecyclePlan;options={restore:kind==='topic-restore'};}
 else if(kind==='fixed'){const e=await s.createEntry({actor:'user',body:'SYNTHETIC fixed',type:'idea',formation:'explicit',evidence:[],operationId:crypto.randomUUID()});request={entryId:e.id,expectedRevision:0,operationId:crypto.randomUUID()};prepare=plans.prepareHumanFixedPlan;view=plans.humanFixedPlan;}
 else if(kind==='section'){const q=await s.createTopic({name:'SYNTHETIC existing',operationId:crypto.randomUUID()});request={topicId:q.id,expectedTopicRevision:0,title:'SYNTHETIC named Section',operationId:crypto.randomUUID()};prepare=plans.prepareHumanSectionPlan;view=plans.humanSectionPlan;}
 else if(kind==='entry'){request={actor:'user',body:'SYNTHETIC body',type:'idea',formation:'explicit',evidence:[],operationId:crypto.randomUUID()};prepare=plans.prepareHumanEntryPlan;view=plans.humanEntryPlan;}
 else{const e=await s.createEntry({actor:'user',body:'SYNTHETIC current body',type:'idea',formation:'explicit',evidence:[],operationId:crypto.randomUUID()});if(kind==='restore')await s.removeEntry({id:e.id,expectedRevision:0,operationId:crypto.randomUUID()});request={id:e.id,expectedRevision:kind==='restore'?1:0,operationId:crypto.randomUUID(),...(kind==='edit'?{changes:{body:'SYNTHETIC edited body'}}:{})};prepare=kind==='edit'?plans.prepareHumanEntryEditPlan:plans.prepareHumanEntryLifecyclePlan;view=kind==='edit'?plans.humanEntryEditPlan:plans.humanEntryLifecyclePlan;options={restore:kind==='restore'};}
 const cap=await prepare(s,core,request,await plans.humanPlanEntry(s,core),options),expected=view(cap),snapshot=()=>s.repository.transaction(false,async t=>({entries:await t.all('thoughts'),topics:await t.all('topics'),sections:await t.all('sections'),history:await t.all('revisions'),meta:await t.all('meta'),receipts:await t.all('operationReceipts'),suppressions:await t.all('thoughtSuppressions')})),before=await snapshot();const original=s.repository.transaction.bind(s.repository);let count=0;s.repository.transaction=(...args)=>{count++;return original(...args);};await assert.rejects(core.transaction(true,async t=>{assert.deepEqual(await plans.executeHumanPlanInTransaction(t,cap),expected.result);await t.put('meta',{id:'synthetic-coordinator-result',value:kind});throw new ArchiveError('SYNTHETIC_NAMED_ABORT');}),{code:'SYNTHETIC_NAMED_ABORT'});assert.equal(count,1);assert.deepEqual(await snapshot(),before);count=0;await core.transaction(true,t=>plans.executeHumanPlanInTransaction(t,cap));assert.equal(count,1);if(expected.pair)assert.deepEqual(await s.repository.transaction(false,t=>t.get('meta',expected.pair.id)),expected.pair);if(expected.entry)assert.deepEqual(await s.repository.transaction(false,t=>t.get('thoughts',expected.entry.id)),expected.entry);if(expected.topic)assert.deepEqual(await s.repository.transaction(false,t=>t.get('topics',expected.topic.id)),expected.topic);if(expected.section)assert.deepEqual(await s.repository.transaction(false,t=>t.get('sections',expected.section.id)),expected.section);
});
