import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';import {LibraryDocumentsStore} from '../core/library-documents-store.js';import {local} from './harness/thought-m1.mjs';import {portableHumanTopicIdentity,localHumanTopicIdentity} from '../core/browser-native-sync/human-library-identity.js';
globalThis.IDBKeyRange=IDBKeyRange;
async function fixture(){const s=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory()});await s.consent(true);await s.finishFoundation();return s;}
test('real rename history proves portable alias plaintext and maps only device-local tokens',async()=>{
 const a=await fixture(),b=await fixture(),q=await a.createTopic({name:'SYNTHETIC Old Topic',operationId:crypto.randomUUID()});await a.editTopic({id:q.id,expectedRevision:0,changes:{name:'SYNTHETIC New Topic'},operationId:crypto.randomUUID()});
 const read=s=>s.repository.transaction(false,async t=>({topic:await t.get('topics',q.id),history:await t.all('revisions'),secret:(await t.get('meta','thought-suppression-key')).value})),x=await read(a),y=await read(b),portable=await portableHumanTopicIdentity(x.topic,x.history,x.secret),mapped=await localHumanTopicIdentity(x.topic.name,portable,y.secret);
 assert.equal(portable.aliases[0].name,'SYNTHETIC Old Topic');assert.equal('token'in portable.aliases[0],false);assert.equal('nameToken'in portable,false);assert.notEqual(mapped.identity.nameToken,x.topic.identity.nameToken);assert.notEqual(mapped.identity.aliases[0].token,x.topic.identity.aliases[0].token);assert.equal(mapped.identity.aliases[0].operationId,x.topic.identity.aliases[0].operationId);assert.deepEqual((await localHumanTopicIdentity(x.topic.name,portable,x.secret)).identity,x.topic.identity);
 await assert.rejects(portableHumanTopicIdentity(x.topic,[],x.secret),{code:'BNS_HUMAN_IDENTITY_UNPROVEN'});const bad=structuredClone(x.history);for(const h of bad)if(h.kind==='topic'&&h.fieldMask.includes('name')&&h.before)h.before.name='SYNTHETIC wrong old name';await assert.rejects(portableHumanTopicIdentity(x.topic,bad,x.secret),{code:'BNS_HUMAN_IDENTITY_UNPROVEN'});
});
import {keepTopicIdentitiesSeparate,planHumanKeepSeparate,topicPairKey} from '../core/topic-identity.js';
test('actual keep-separate uses the same pair plan and repeat calls preserve identity/time without another allocation',async()=>{
 let ticks=0;const s=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory(),clock:()=>new Date(Date.UTC(2026,9,9)+ticks++).toISOString()});await s.consent(true);await s.finishFoundation();const a=await s.createTopic({name:'SYNTHETIC same',operationId:crypto.randomUUID()}),b=await s.createTopic({name:'SYNTHETIC same',operationId:crypto.randomUUID()}),before=ticks;
 assert.deepEqual(await keepTopicIdentitiesSeparate(s,{sourceId:a.id,targetId:b.id}),{kept:true});assert.equal(ticks,before+1);const row=await s.repository.transaction(false,t=>t.get('meta',topicPairKey(a.id,b.id)));assert.deepEqual(row,planHumanKeepSeparate(a.id,b.id,new Date(Date.UTC(2026,9,9)+before).toISOString()));
 assert.deepEqual(await keepTopicIdentitiesSeparate(s,{sourceId:b.id,targetId:a.id}),{kept:true});assert.equal(ticks,before+1);assert.deepEqual(await s.repository.transaction(false,t=>t.get('meta',row.id)),row);
});
test('suppression portability proves the removed body, not the restored Entry later edits',async()=>{
 const {portableHumanSuppression,localHumanSuppression}=await import('../core/browser-native-sync/human-library-identity.js');const s=await fixture(),e=await s.createEntry({actor:'user',body:'SYNTHETIC original removed body',type:'idea',formation:'explicit',evidence:[],operationId:crypto.randomUUID()});await s.removeEntry({id:e.id,expectedRevision:0,operationId:crypto.randomUUID()});await s.restoreEntry({id:e.id,expectedRevision:1,operationId:crypto.randomUUID()});await s.editEntry({id:e.id,expectedRevision:2,changes:{body:'SYNTHETIC later body'},operationId:crypto.randomUUID()});const data=await s.repository.transaction(false,async t=>({row:(await t.all('thoughtSuppressions'))[0],history:await t.all('revisions'),secret:(await t.get('meta','thought-suppression-key')).value})),portable=await portableHumanSuppression(data.row,data.history,data.secret);assert.equal(portable.signatureInput.body,'SYNTHETIC original removed body');assert.equal(Object.hasOwn(portable,'exactSignature'),false);assert.deepEqual(await localHumanSuppression(portable,data.secret),data.row);const other=await localHumanSuppression(portable,Array(32).fill(9));assert.notEqual(other.exactSignature,data.row.exactSignature);await assert.rejects(portableHumanSuppression(data.row,data.history.filter(h=>h.reason!=='remove'),data.secret),{code:'BNS_HUMAN_SUPPRESSION_UNPROVEN'});
});
test('rename identity plan matches the original owner including opaque prior token and repeated-name registration order',async()=>{
 const {prepareTopicRename,planHumanTopicRename,recordTopicRename}=await import('../core/topic-identity.js');const s=await fixture(),q=await s.createTopic({name:'SYNTHETIC Rename Before',operationId:crypto.randomUUID()}),prepared=await prepareTopicRename(s,q.id,'SYNTHETIC Rename After'),operationId=crypto.randomUUID(),at='2026-10-09T01:02:03.004Z';
 await s.repository.transaction(true,async t=>{const row=await t.get('topics',q.id),before=structuredClone(row),plan=planHumanTopicRename(row,prepared,operationId,at);assert.deepEqual(row,before);await recordTopicRename(t,row,prepared,operationId,at);assert.deepEqual(row.identity,{...plan.identity,nameToken:prepared.newToken});assert.deepEqual(plan.priorTokens,[prepared.oldToken]);for(const token of [...plan.priorTokens,prepared.newToken])assert.equal((await t.get('meta','personalTopicName:'+token)).topicIds.includes(q.id),true);assert.throws(()=>planHumanTopicRename({...before,revision:before.revision+1},prepared,operationId,at));const opaque='a'.repeat(64),old={...before,identity:{...before.identity,nameToken:opaque}},opaquePlan=planHumanTopicRename(old,prepared,operationId,at);assert.deepEqual(opaquePlan.priorTokens,[opaque,prepared.oldToken]);assert.equal(opaquePlan.identity.aliases[0].token,opaque);assert.equal(opaquePlan.identity.aliases[1].token,prepared.oldToken);});
});
