import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {LibraryDocumentsStore} from '../core/library-documents-store.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import * as current from '../core/browser-native-sync/human-library-plan.js';
import {prepareHumanAllocation,bindHumanReplayEntry} from '../core/browser-native-sync/human-library-allocation.js';
import {hashText} from '../core/dedupe.js';
import {prefix,keyedHash} from '../core/thought-model.js';
import {local} from './harness/thought-m1.mjs';
import {LibraryDocumentsStore as OriginalStore} from './fixtures/human-entry-edit-original-owner/extension/core/library-documents-store.js';
import {BrowserNativeSyncCore as OriginalCore} from './fixtures/human-entry-edit-original-owner/extension/core/browser-native-sync/core.js';
import * as original from './fixtures/human-entry-edit-original-owner/extension/core/browser-native-sync/human-library-plan.js';
globalThis.IDBKeyRange=IDBKeyRange;
const base='1fa44e4e52680f5245e34f6933c129e659d0675d',op=()=>crypto.randomUUID(),json=x=>JSON.stringify(x);
const snapshot=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all([...t.tx.objectStoreNames].map(async name=>[name,await t.all(name)]))));
function allocations(s,offset=0){let tick=offset,n=0;const calls=[];s.clock=()=>{const value=new Date(Date.UTC(2026,9,9)+tick++).toISOString();calls.push(['clock',value]);return value;};s.uuid=()=>{const value='synthetic-edit-allocation-'+offset+'-'+(++n);calls.push(['uuid',value]);return value;};return calls;}
async function pair(seed=async()=>{}){
 const a=new OriginalStore(local(),{indexedDB:new IDBFactory()}),b=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory()});allocations(a);await a.consent(true);await a.finishFoundation();await b.consent(true);await b.finishFoundation();
 const e=await a.createEntry({actor:'user',body:'SYNTHETIC original editable body 汉字',title:'SYNTHETIC title',type:'idea',formation:'explicit',evidence:[],operationId:op()});await seed(a,e);
 const ac=new OriginalCore(a.repository,{datasetId:'synthetic-original-edit',deviceId:'synthetic-owner'});await original.humanPlanEntry(a,ac);const rows=await snapshot(a);
 // A test installation clone, using actual IndexedDB object stores. Neither
 // production prepare nor the computation receives this fixture machinery.
 await b.repository.transaction(true,t=>{for(const name of t.tx.objectStoreNames){const store=t.tx.objectStore(name);store.clear();for(const row of rows[name])store.put(structuredClone(row));}});
 await b.local.set(await a.local.get('personalAIArchive'));assert.equal(json(await snapshot(b)),json(rows));const bc=new BrowserNativeSyncCore(b.repository,{datasetId:'synthetic-original-edit',deviceId:'synthetic-owner'});return {a,b,ac,bc,id:e.id};
}
function writes(s){const trace=[],transaction=s.repository.transaction.bind(s.repository);s.repository.transaction=(write,fn,...rest)=>transaction(write,async t=>{if(write)for(const name of ['put','delete','clear','putDerivedSearchRow','putDerivedTopicCount','putDerivedTopicRead']){const old=t[name]?.bind(t);if(old)t[name]=async(...args)=>{trace.push([name,structuredClone(args)]);return old(...args);};}return fn(t);},...rest);return trace;}
async function typedCapture(s,core,id){const entry=await current.humanPlanEntry(s,core);return {entry,before:await s.repository.transaction(false,async t=>{const history=await t.rangePage('revisions','byList',prefix(['library_entry:'+id]),null,129),placementRows=await t.all('placements','byEntry',prefix([id])),topics=[];assert.equal(history.next,null);for(const topicId of [...new Set(placementRows.map(p=>p.topicId))])topics.push({row:await t.get('topics',topicId)??null,index:await t.get('meta','thought-read-index:v1:topic:'+topicId)??null});return {base:structuredClone(entry),read:{row:await t.get('thoughts',id)??null,history:history.rows.map(x=>x.value),placements:placementRows.length,placementRows,topics,epoch:(await t.get('meta','thought-epoch'))?.value||0,provenance:await t.count('provenance','byOwner',prefix(['entry',id])),dependencies:await t.count('dependencies','byTarget',prefix(['entry',id]))},receipt:null};})};}
async function compare(p,request,{offset=0,commit=true}={}){
 const before=await snapshot(p.a);assert.equal(json(await snapshot(p.b)),json(before));const callsA=allocations(p.a,offset),callsB=allocations(p.b,offset),entryA=await original.humanPlanEntry(p.a,p.ac),entryB=await current.humanPlanEntry(p.b,p.bc);assert.equal(json(entryA),json(entryB));
 let ca,cb,ea,eb;try{ca=await original.prepareHumanEntryEditPlan(p.a,p.ac,request,entryA);}catch(e){ea=e.code;}try{cb=await current.prepareHumanEntryEditPlan(p.b,p.bc,request,entryB);}catch(e){eb=e.code;}
 assert.equal(ea,eb);assert.equal(json(callsA),json(callsB));assert.equal(json(await snapshot(p.a)),json(before));assert.equal(json(await snapshot(p.b)),json(before));if(ea)return {error:ea};
 if(ca.conflict||ca.duplicate){assert.equal(json(cb),json(ca));return ca;}
 const old=original.humanEntryEditPlan(ca),now=current.humanEntryEditPlan(cb);assert.equal(json(now),json(old),'full original opaque plan, key order and allocations');
 const {entry,before:read}=await typedCapture(p.b,p.bc,request.id),saved=json({entry,read,request}),domain=now.events.filter(e=>e.role==='domain').length,indices=now.events.filter(e=>e.role==='index-generation'),replay=bindHumanReplayEntry(structuredClone(entry),now.events,{domainCount:domain,indexGenerationCount:indices.length});let next=0;
 const allocation=prepareHumanAllocation({uuid:()=>indices[next++].value},replay),signature=await keyedHash(read.base.secret,['body',request.changes.type??read.read.row.type,request.changes.body??read.read.row.thoughtText]),computed=current.computeHumanEntryEditState(request,read,entry,await hashText(json(request)),signature,allocation);allocation.seal();assert.equal(json(allocation.events()),json(now.events));assert.equal(json({entry,read,request}),saved,'pure compute does not mutate typed captures');
 assert.equal(json(computed.row),json(old.entry));assert.equal(json(computed.history),json(old.history));assert.equal(json(computed.touchedTopics),json(old.topics));assert.equal(json(computed.operationReceipt),json(old.operationReceipt));
 if(commit){const wa=writes(p.a),wb=writes(p.b);assert.equal(json(await original.executeHumanPlan(ca)),json(await current.executeHumanPlan(cb)));const final=await snapshot(p.a);assert.equal(json(await snapshot(p.b)),json(final),'all original owner stores, history and counters equal');assert.equal(json(wb),json(wa),'ordered original owner writes equal');assert.equal(final.meta.find(r=>r.id==='thought-sequence').value,computed.thoughtSequence);assert.equal(final.meta.find(r=>r.id==='revision-sequence').value,computed.revisionSequence);for(const item of computed.touchedIndices)assert.equal(json(final.meta.find(r=>r.id==='thought-read-index:v1:topic:'+item.id)??null),json(item.index));}
 return {plan:now,computed,calls:callsA};
}
test('exact Git original module and entire96-module static import closure is immutable',async()=>{
 const root=new URL('./fixtures/human-entry-edit-original-owner/',import.meta.url),manifest=JSON.parse(await readFile(new URL('manifest.json',root),'utf8'));assert.equal(manifest.commit,base);assert.equal(Object.keys(manifest.files).length,96);
 for(const [path,proof]of Object.entries(manifest.files)){const bytes=await readFile(new URL(path,root));assert.equal(createHash('sha256').update(bytes).digest('hex'),proof.sha256);assert.equal(createHash('sha1').update('blob '+bytes.length+'\0').update(bytes).digest('hex'),proof.gitBlob);for(const m of bytes.toString().matchAll(/(?:import|export)\s+(?:[^;]*?\s+from\s*)?['"]([^'"]+)['"]\s*;/g)){assert.ok(m[1].startsWith('.'));const url=new URL(m[1],new URL(path,root));assert.ok(manifest.files[decodeURIComponent(url.pathname.slice(root.pathname.length))],'complete original static dependency');}}
});
test('changed Entry fields, key order, expected-field order and protected intent retain exact original plans and actual owner writes',async()=>{
 for(const reverse of [false,true]){const p=await pair(),values={body:'SYNTHETIC changed body 👨‍👩‍👧‍👦',note:'SYNTHETIC changed note',title:'SYNTHETIC changed title'},changes=Object.fromEntries((reverse?['note','title','body']:['body','title','note']).map(k=>[k,values[k]])),fields=Object.fromEntries((reverse?['body','note','title']:['title','note','body']).map(k=>[k,0]));const r=await compare(p,{id:p.id,operationId:op(),changes,expectedRevision:0,expectedFieldRevisions:fields});assert.deepEqual(r.plan.history.at(-1).fieldMask,Object.keys(changes));assert.equal(r.plan.entry.protections.body.locked,true);assert.equal(r.plan.entry.protections.body.reason,'user_edit');assert.equal(r.plan.entry.authorship.body.everHumanConfirmed,true);}
});
test('original coalescence, exact sixty-second boundary and same-value receipt preserve allocation identity and counters',async()=>{
 const p=await pair();let r=await compare(p,{id:p.id,operationId:op(),expectedRevision:0,changes:{note:'SYNTHETIC first note'}});const history=r.plan.history.at(-1),firstUUIDs=r.plan.events.filter(e=>e.kind==='uuid');assert.equal(firstUUIDs.length,1);
 r=await compare(p,{id:p.id,operationId:op(),expectedRevision:1,changes:{note:'SYNTHETIC second note'}},{offset:59999});assert.equal(r.plan.history.at(-1).id,history.id);assert.equal(r.plan.events.some(e=>e.kind==='uuid'),false);assert.equal(r.plan.history.at(-1).windowStartedAt,history.windowStartedAt);
 r=await compare(p,{id:p.id,operationId:op(),expectedRevision:2,changes:{note:'SYNTHETIC third note'}},{offset:60000});assert.notEqual(r.plan.history.at(-1).id,history.id);
 const count=r.plan.history.length;r=await compare(p,{id:p.id,operationId:op(),expectedRevision:3,changes:{note:'SYNTHETIC third note'}},{offset:60010});assert.equal(r.plan.entry.revision,3);assert.equal(r.plan.history.length,count);
});
test('active and stale-layout membership touches inherit complete index metadata and ordered domain/index roles',async()=>{
 for(const indexed of [false,true]){const p=await pair(async(s,e)=>{for(let i=0;i<2;i++){const q=await s.createTopic({name:'SYNTHETIC member '+i,operationId:op()});await s.placeEntry({entryId:e.id,topicId:q.id,expectedEntryRevision:i,expectedTopicRevision:0,operationId:op()});if(indexed)await s.repository.transaction(true,t=>t.put('meta',{id:'thought-read-index:v1:topic:'+q.id,version:6,timeRevision:17,activeGeneration:'synthetic_active',activeKey:'stale',buildingGeneration:'synthetic_old',buildingKey:'stale',sourceCursor:['synthetic_cursor'],scanned:31,indexed:23,activeCount:19,activeEarliest:'2026-10-01',activeLatest:'2026-10-02'}));}
 const placement=await s.repository.transaction(false,async t=>(await t.all('placements'))[0]);await s.repository.transaction(true,t=>t.put('placements',{...placement,id:JSON.stringify([placement.topicId,0,e.id]),layoutGeneration:0}));});
 const r=await compare(p,{id:p.id,operationId:op(),expectedRevision:2,changes:{body:'SYNTHETIC member edit'}});assert.equal(r.plan.topics.length,2);assert.equal(r.plan.events.filter(e=>e.role==='index-generation').length,indexed?2:0);for(const item of r.computed.touchedIndices)if(indexed){assert.equal(item.index.activeCount,19);assert.equal(item.index.timeRevision,17);assert.equal(item.index.activeEarliest,'2026-10-01');}
 const noDelta=await compare(p,{id:p.id,operationId:op(),expectedRevision:3,changes:{body:'SYNTHETIC member edit'}},{offset:10});assert.equal(noDelta.plan.entry.revision,3);assert.equal(noDelta.plan.topics.length,2);}
});
test('removed/restored original Entry and preserved important history remain exact; stale CAS and duplicate refuse or return before allocation',async()=>{
 const removed=await pair(async(s,e)=>{await s.removeEntry({id:e.id,expectedRevision:0,operationId:op()});});assert.equal((await compare(removed,{id:removed.id,operationId:op(),expectedRevision:1,changes:{body:'SYNTHETIC forbidden revival'}})).error,'BNS_HUMAN_UNSUPPORTED');
 const p=await pair(async(s,e)=>{await s.removeEntry({id:e.id,expectedRevision:0,operationId:op()});await s.restoreEntry({id:e.id,expectedRevision:1,operationId:op()});});const request={id:p.id,operationId:op(),expectedRevision:2,changes:{body:'SYNTHETIC after restore'}};const r=await compare(p,request);assert.equal(r.plan.history.filter(h=>h.important).length,3);assert.equal((await compare(p,request)).duplicate,true);assert.equal((await compare(p,{...request,operationId:op(),expectedRevision:0})).conflict,true);assert.equal((await compare(p,{...request,changes:{body:'SYNTHETIC operation collision'}})).error,'BNS_HUMAN_OPERATION_COLLISION');
});
test('history-retirement and final original read-set races retain fail-closed original outcomes without writes',async()=>{
 const p=await pair(async(s,e)=>{await s.editEntry({id:e.id,expectedRevision:0,changes:{note:'SYNTHETIC old note'},operationId:op()});await s.repository.transaction(true,async t=>{const row=(await t.all('revisions')).find(r=>r.reason==='edit');row.at='2026-01-01T00:00:00Z';row.windowStartedAt=row.at;await t.put('revisions',row);});});assert.equal((await compare(p,{id:p.id,operationId:op(),expectedRevision:1,changes:{note:'SYNTHETIC retirement refusal'}})).error,'BNS_HUMAN_HISTORY_RETIREMENT_UNAVAILABLE');
 const q=await pair(),request={id:q.id,operationId:op(),expectedRevision:0,changes:{body:'SYNTHETIC stale prepare'}},ea=await original.humanPlanEntry(q.a,q.ac),eb=await current.humanPlanEntry(q.b,q.bc);allocations(q.a);allocations(q.b);const ca=await original.prepareHumanEntryEditPlan(q.a,q.ac,request,ea),cb=await current.prepareHumanEntryEditPlan(q.b,q.bc,request,eb);for(const s of [q.a,q.b])await s.repository.transaction(true,async t=>{const row=await t.get('thoughts',q.id);row.note='SYNTHETIC intervening original row';await t.put('thoughts',row);});const before=await snapshot(q.a);await assert.rejects(original.executeHumanPlan(ca),{code:'BNS_HUMAN_CHANGED'});await assert.rejects(current.executeHumanPlan(cb),{code:'BNS_HUMAN_CHANGED'});assert.equal(json(await snapshot(q.a)),json(before));assert.equal(json(await snapshot(q.b)),json(before));
});
test('original permission and field-level CAS boundaries remain before computation and unbound capabilities cannot write',async()=>{
 const p=await pair();await compare(p,{id:p.id,operationId:op(),expectedRevision:0,changes:{note:'SYNTHETIC unrelated field edit'}});const r=await compare(p,{id:p.id,operationId:op(),expectedRevision:0,changes:{body:'SYNTHETIC field CAS allowed'},expectedFieldRevisions:{body:0}},{offset:10});assert.equal(r.plan.entry.revision,2);assert.equal(r.plan.history.at(-1).baseRevision,0);
 assert.equal((await compare(p,{id:p.id,operationId:op(),expectedRevision:2,changes:{body:'SYNTHETIC stale field'},expectedFieldRevisions:{body:0}})).conflict,true);
 assert.equal((await compare(p,{id:p.id,operationId:op(),expectedRevision:2,changes:{body:'SYNTHETIC foreign actor'},actor:'ai'})).error,'BNS_HUMAN_REQUEST');
 for(const s of [p.a,p.b])await s.setEnabled(false);for(const [s,core,owner]of [[p.a,p.ac,original],[p.b,p.bc,current]]){const before=await snapshot(s);await assert.rejects(owner.humanPlanEntry(s,core),{code:'BNS_HUMAN_PERMISSION'});await assert.rejects(owner.executeHumanPlan(Object.freeze({})),{code:'BNS_HUMAN_PLAN_REQUIRED'});assert.equal(json(await snapshot(s)),json(before));}
});
