import test from 'node:test';
import assert from 'node:assert/strict';
import {scanHumanSearchFieldInventory as scan} from '../core/browser-native-sync/human-search-field-inventory.js';
import {tokens} from '../core/library-search.js';
// The exact original source match expression, deliberately before normalize or
// locale case conversion. This independent native regex oracle is conditional
// source-shape evidence, never a supported-engine normalization theorem.
const matches=text=>text.match(/[\p{Script=Han}]|[\p{L}\p{N}_]+/gu)||[];
const noAuthority=x=>{assert.equal(x.state,'NOT_ADMITTED');assert.equal(x.executionProfileQualified,false);assert.equal(x.budgetAuthority,false);assert.equal(Object.isFrozen(x),true);assert.deepEqual(Object.keys(x),['version','state','reason','inputUnits','scannedUnits','sourceMatchCount','sourceMatchUnits','sourceComplete','withinSingleFieldPostingCeiling','executionProfileQualified','budgetAuthority']);};
for(const text of ['', 'alpha beta_22','abc中文','中文abc','a中b文 c国','中a中a','中_文','中文 中文','—“中文”、hello。〈世界〉','a\0中\tword\n文','中'.repeat(800),'中'.repeat(32768),'中'.repeat(32769)])test('source-shape whole match inventory '+JSON.stringify(text.slice(0,24))+' length '+text.length,()=>{const x=scan(text),expected=matches(text);noAuthority(x);assert.equal(x.sourceComplete,true);assert.equal(x.inputUnits,text.length);assert.equal(x.scannedUnits,text.length);assert.equal(x.sourceMatchCount,expected.length);assert.equal(x.sourceMatchUnits,expected.reduce((sum,word)=>sum+word.length,0));assert.equal(x.withinSingleFieldPostingCeiling,expected.length<=32768);assert.equal(x.reason,expected.length>32768?'SOURCE_POSTING_COUNT_LIMIT':'EXECUTION_PROFILE_UNQUALIFIED');});
test('ASCII-start may absorb Han while Han-first uses single matches',()=>{assert.equal(scan('abc中文').sourceMatchCount,1);assert.equal(scan('中文abc').sourceMatchCount,3);assert.equal(scan('中a中文').sourceMatchCount,2);});
test('repeated Han charges pre-dedup source matches and never unique hashes',()=>{const text='中'.repeat(32769),x=scan(text);assert.equal(tokens(text).length,1);assert.equal(x.sourceMatchCount,32769);assert.equal(x.withinSingleFieldPostingCeiling,false);noAuthority(x);});
test('entire explicit ASCII repertoire excluding uppercase is scanned',()=>{for(let point=0;point<128;point++){const x=scan(String.fromCharCode(point));noAuthority(x);assert.equal(x.sourceComplete,point<65||point>90);}});
test('entire selected CJK BMP range and19 exact punctuation are scanned',()=>{for(let point=0x4e00;point<=0x9fff;point++){const x=scan(String.fromCharCode(point));assert.equal(x.sourceComplete,true);assert.equal(x.sourceMatchCount,1);assert.equal(x.sourceMatchUnits,1);}for(const point of [0x2014,0x2018,0x2019,0x201c,0x201d,0x3001,0x3002,0x3008,0x3009,0x300a,0x300b,0x300c,0x300d,0x300e,0x300f,0x3010,0x3011,0x3014,0x3015]){const x=scan(String.fromCharCode(point));assert.equal(x.sourceComplete,true);assert.equal(x.sourceMatchCount,0);}});
test('unsupported width combining surrogate compatibility and uppercase preserve refusal with incomplete prefix',()=>{for(const suffix of ['A','，','…','\u3000','\u3012','\u4dff','\ua000','\u3400','\uf900','\ufe0f','\u0301','\ud800','\udc00','𠀀','é','ﷺ']){const x=scan('a中 '+suffix+'valid');noAuthority(x);assert.equal(x.reason,'UNSUPPORTED_SOURCE_REPERTOIRE');assert.equal(x.sourceComplete,false);assert.equal(x.scannedUnits,3);assert.equal(x.sourceMatchCount,null);assert.equal(x.sourceMatchUnits,null);assert.equal(x.withinSingleFieldPostingCeiling,null);}});
test('scanner conservative work bound accepts endpoint and refuses before reading any over-bound character',()=>{const x=scan(' '.repeat(2*1024*1024));assert.equal(x.sourceComplete,true);assert.equal(x.sourceMatchCount,0);assert.equal(x.inputUnits,2*1024*1024);const descriptor=Object.getOwnPropertyDescriptor(String.prototype,'charCodeAt');Object.defineProperty(String.prototype,'charCodeAt',{...descriptor,value(){throw Error('over-bound character read');}});try{const y=scan('a'.repeat(2*1024*1024+1));noAuthority(y);assert.equal(y.reason,'SOURCE_WORK_LIMIT');assert.equal(y.sourceComplete,false);assert.equal(y.scannedUnits,0);assert.equal(y.sourceMatchCount,null);assert.equal(y.sourceMatchUnits,null);assert.equal(y.withinSingleFieldPostingCeiling,null);}finally{Object.defineProperty(String.prototype,'charCodeAt',descriptor);}});
test('nonprimitive and extra arguments refuse without coercion or callback',()=>{for(const input of [undefined,null,2,true,{},[],new String('a'),{toString(){throw Error('must not coerce');}}])assert.throws(()=>scan(input),{code:'BNS_HUMAN_SEARCH_FIELD_INVENTORY_ARGUMENT_INVALID'});assert.throws(()=>scan(),{code:'BNS_HUMAN_SEARCH_FIELD_INVENTORY_ARGUMENT_INVALID'});assert.throws(()=>scan('a',()=>assert.fail('callback')),{code:'BNS_HUMAN_SEARCH_FIELD_INVENTORY_ARGUMENT_INVALID'});});
test('inventory does not invoke original native normalization or locale case transformations',()=>{const names=['normalize','toLocaleLowerCase'],saved=names.map(name=>Object.getOwnPropertyDescriptor(String.prototype,name));for(let i=0;i<names.length;i++)Object.defineProperty(String.prototype,names[i],{...saved[i],value(){throw Error('native transform invoked');}});try{const x=scan('abc中文 中文abc');noAuthority(x);assert.equal(x.sourceComplete,true);assert.equal(x.sourceMatchCount,4);}finally{for(let i=0;i<names.length;i++)Object.defineProperty(String.prototype,names[i],saved[i]);}});

test('fixed result never retains a body word codepoint hash or caller reference',()=>{const text='private_fixture_secret_17 中文',x=scan(text),json=JSON.stringify(x);noAuthority(x);assert.equal(json.includes('private_fixture_secret_17'),false);assert.equal(json.includes('中文'),false);assert.equal(Object.values(x).includes(text),false);for(const value of Object.values(x))assert.ok(value===null||['string','number','boolean'].includes(typeof value));});
