import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';import {LibraryDocumentsStore} from '../core/library-documents-store.js';import {local} from './harness/thought-m1.mjs';import {prepareTopicRename} from '../core/topic-identity.js';import {editSection,editSectionInTransaction} from '../core/thought-organization.js';import {ArchiveError} from '../core/constants.js';
globalThis.IDBKeyRange=IDBKeyRange;
for(const kind of ['topic-edit','topic-rename','section-edit'])test('original '+kind+' transaction writer preserves ordered allocations and rollback',async()=>{
 let ticks=0,ids=0;const s=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory(),clock:()=>new Date(Date.UTC(2026,9,9)+ticks++).toISOString(),uuid:()=>`synthetic-edit-owner-${++ids}`});await s.consent(true);await s.finishFoundation();const topic=await s.createTopic({name:'SYNTHETIC before',operationId:crypto.randomUUID()}),section=kind==='section-edit'?await s.createSection({topicId:topic.id,expectedTopicRevision:0,title:'SYNTHETIC section',operationId:crypto.randomUUID()}):null;
 const request=kind==='topic-edit'?{id:topic.id,expectedRevision:0,changes:{name:'SYNTHETIC after',summary:'SYNTHETIC note',pinned:true},operationId:crypto.randomUUID()}:kind==='topic-rename'?{id:topic.id,expectedRevision:0,name:'SYNTHETIC after',operationId:crypto.randomUUID()}:{topicId:topic.id,sectionId:section.sectionId,expectedRevision:0,title:'SYNTHETIC after',operationId:crypto.randomUUID()},rename=kind==='section-edit'?null:await prepareTopicRename(s,topic.id,'SYNTHETIC after');
 const read=()=>s.repository.transaction(false,async t=>({topics:await t.all('topics'),sections:await t.all('sections'),history:await t.all('revisions'),meta:await t.all('meta'),receipts:await t.all('operationReceipts')})),before=await read(),invoke=t=>kind==='topic-edit'?s.editTopicInTransaction(t,request,rename):kind==='topic-rename'?s.renameTopicInTransaction(t,request,rename):editSectionInTransaction(s,t,request);
 const beforeTicks=ticks,beforeIds=ids;await assert.rejects(s.operation(request,async t=>{const result=await invoke(t);assert.equal(result.revision,1);throw new ArchiveError('SYNTHETIC_EDIT_OWNER_ABORT');}),{code:'SYNTHETIC_EDIT_OWNER_ABORT'});assert.deepEqual(await read(),before);
 // A failed ordinary owner consumes its ordinary clock slots, but never writes
 // partial rows. Reset only this synthetic clock's counter to compare the same
 // original successful allocation sequence; no production clock is replaced.
 ticks=beforeTicks;ids=beforeIds;const result=kind==='topic-edit'?await s.editTopic(request):kind==='topic-rename'?await s.renameTopic(request):await editSection(s,request);assert.equal(result.revision,1);const after=await read(),history=after.history.find(x=>x.operationId===request.operationId);assert.ok(history);assert.equal(history.reason,'rename');assert.equal(after.receipts.some(x=>x.id===request.operationId),true);if(kind==='topic-edit'){const row=after.topics.find(x=>x.id===topic.id);assert.equal(row.name,'SYNTHETIC after');assert.equal(row.summary,'SYNTHETIC note');assert.equal(row.pinKey,0);assert.equal(row.identity.aliases[0].at,new Date(Date.UTC(2026,9,9)+beforeTicks).toISOString());assert.equal(row.protections.name.at,new Date(Date.UTC(2026,9,9)+beforeTicks+1).toISOString());}
});
test('public editTopic captures the validated changes object before its first await',async()=>{const s=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory()});await s.consent(true);await s.finishFoundation();const q=await s.createTopic({name:'SYNTHETIC before',operationId:crypto.randomUUID()}),request={id:q.id,expectedRevision:0,changes:{name:'SYNTHETIC captured'},operationId:crypto.randomUUID()},pending=s.editTopic(request);request.changes={summary:'SYNTHETIC late replacement'};await pending;const row=await s.repository.transaction(false,t=>t.get('topics',q.id));assert.equal(row.name,'SYNTHETIC captured');assert.notEqual(row.summary,'SYNTHETIC late replacement');});
