import test from 'node:test';
import assert from 'node:assert/strict';
import {inspectHumanUnindexedSearch as inspectOriginal} from '../core/browser-native-sync/human-library-search-proof.js';
import {ownerVersion,planSearchQueueLocator} from '../core/library-search.js';
function freeze(value){if(value&&typeof value==='object'){for(const d of Object.values(Object.getOwnPropertyDescriptors(value)))if(Object.hasOwn(d,'value'))freeze(d.value);Object.freeze(value);}return value;}
const inspect=(raw,...args)=>inspectOriginal(freeze(raw),...args);
const owner=(kind,id,lifecycle='active')=>{const row={id,lifecycle,sourceRecordIds:[],createdBy:'user',storageSchema:2,provenanceType:'user_created',origin:'user',revision:1,contentRevision:1};row.searchVersion=ownerVersion(kind,row);return row;};
function fixture(){const rows={thoughts:[owner('entry','synthetic-entry')],topics:[owner('topic','synthetic-topic')],sections:[owner('section','synthetic-section')],revisions:[],libraryMigrationItems:[],librarySearchTerms:[]};for(const [kind,name]of [['entry','thoughts'],['topic','topics'],['section','sections']])for(const row of rows[name])rows.libraryMigrationItems.push(planSearchQueueLocator(kind,row));return {rows,rebuild:null};}
const refusal=f=>assert.throws(()=>inspect(f),{code:'BNS_HUMAN_SEARCH_UNPROVEN'});
test('exact pending owners reuse original qualifier and expose only fixed nonadmission facts',()=>{const raw=fixture(),before=structuredClone(raw),x=inspect(raw);assert.deepEqual(x,{version:1,state:'NOT_ADMITTED',unindexedOwners:3,exactQueueTasks:3,postings:0,executionProfileQualified:false,budgetAuthority:false,nativeQualified:false});assert.equal(Object.isFrozen(x),true);assert.deepEqual(raw,before);assert.equal(JSON.stringify(x).includes('synthetic-entry'),false);});
test('empty and removed pending inventories retain original locator semantics',()=>{const raw=fixture();for(const [kind,name]of [['entry','thoughts'],['topic','topics'],['section','sections']]){raw.rows[name][0]=owner(kind,'synthetic-'+kind,'removed');}raw.rows.libraryMigrationItems=raw.rows.thoughts.map(r=>planSearchQueueLocator('entry',r)).concat(raw.rows.topics.map(r=>planSearchQueueLocator('topic',r)),raw.rows.sections.map(r=>planSearchQueueLocator('section',r)));assert.equal(inspect(raw).unindexedOwners,3);const empty=fixture();for(const key of Object.keys(empty.rows))empty.rows[key]=[];assert.equal(inspect(empty).unindexedOwners,0);});
test('no task per owner, duplicate task or foreign task never becomes pending qualification',()=>{for(const mutate of [r=>r.rows.libraryMigrationItems.pop(),r=>r.rows.libraryMigrationItems[1]=r.rows.libraryMigrationItems[0],r=>r.rows.libraryMigrationItems[0].ownerId='foreign']){const raw=fixture();mutate(raw);refusal(raw);}});
test('every owner with own indexed field and every posting refuse before original tokenizer',()=>{const saved=['normalize','toLocaleLowerCase'].map(k=>[k,Object.getOwnPropertyDescriptor(String.prototype,k)]);for(const [k,d]of saved)Object.defineProperty(String.prototype,k,{...d,value(){assert.fail('unqualified tokenizer executed');}});try{for(const name of ['thoughts','topics','sections'])for(const value of [undefined,null,'indexed']){const raw=fixture();raw.rows[name][0].indexedSearchVersion=value;refusal(raw);}const raw=fixture();raw.rows.librarySearchTerms.push({id:'foreign'});refusal(raw);assert.equal(inspect(fixture()).unindexedOwners,3);}finally{for(const [k,d]of saved)Object.defineProperty(String.prototype,k,d);}});
test('pending phase/progress/version/extra fields are compared with entire original locator',()=>{for(const change of [{phase:'put'},{offset:1},{version:'wrong'},{extra:true}]){const raw=fixture();Object.assign(raw.rows.libraryMigrationItems[0],change);refusal(raw);}});
test('mixed physical Root/Topic rows cannot be exempted by status or prefix',()=>{for(const row of [{id:'thought-root:synthetic',statusKey:2,entityKind:'thought_root_v1:synthetic'},{id:'thought-topic:synthetic',statusKey:3,entityKind:'thought_topic_v1:synthetic:asc'},{id:'unknown',statusKey:0,entityKind:'search',thoughtText:'synthetic body'}]){const raw=fixture();raw.rows.libraryMigrationItems.push(row);refusal(raw);}});
test('original rebuild and owner eligibility/source/version checks are not relaxed',()=>{for(const change of [{storageSchema:1},{provenanceType:'input_original'},{origin:'ai'},{lifecycle:'unknown'},{searchVersion:'wrong'},{sourceRecordIds:['foreign']}]){const raw=fixture();Object.assign(raw.rows.thoughts[0],change);refusal(raw);}const raw=fixture();raw.rebuild={id:'library-search-rebuild',phase:3,cursor:null,complete:true};assert.equal(inspect(raw).unindexedOwners,3);const invalid=fixture();invalid.rebuild={...raw.rebuild,complete:false};refusal(invalid);});
test('first-family 128 aggregate bound and original per-family bounds refuse excess',()=>{const raw=fixture();raw.rows.thoughts=Array.from({length:128},(_,i)=>owner('entry','synthetic-'+i));raw.rows.libraryMigrationItems=raw.rows.thoughts.map(r=>planSearchQueueLocator('entry',r));refusal(raw);const excess=fixture();excess.rows.thoughts=Array.from({length:129},(_,i)=>owner('entry','synthetic-'+i));assert.throws(()=>inspect(excess),{code:'BNS_HUMAN_GRAPH_LIMIT'});});
test('no missing table or extra argument can be treated as observed empty selectors',()=>{const raw=fixture();delete raw.rows.sections;assert.throws(()=>inspect(raw),{code:'BNS_HUMAN_GRAPH_LIMIT'});assert.throws(()=>inspect(fixture(),true),{code:'BNS_HUMAN_SEARCH_UNPROVEN'});});

test('ordinary getter mutation refuses before any getter or tokenizer, including selected nonenumerable accessors',()=>{for(const enumerable of [true,false]){const raw=fixture();let reads=0,calls=0;const row=raw.rows.thoughts[0],version=row.searchVersion;Object.defineProperty(row,'searchVersion',{enumerable,configurable:true,get(){reads++;row.indexedSearchVersion=version;raw.rows.libraryMigrationItems.length=0;return version;}});const d=Object.getOwnPropertyDescriptor(String.prototype,'normalize');Object.defineProperty(String.prototype,'normalize',{...d,value(){calls++;throw Error('tokenizer executed');}});try{assert.throws(()=>inspect(raw));assert.equal(reads,0);assert.equal(calls,0);}finally{Object.defineProperty(String.prototype,'normalize',d);}}});
test('supported input is deep frozen ordinary data, never caller mutation or inherited selected facts',()=>{assert.throws(()=>inspectOriginal(fixture()),{code:'BNS_HUMAN_EFFECT_CUT_REQUIRED'});const raw=fixture();Object.freeze(raw);assert.throws(()=>inspectOriginal(raw),{code:'BNS_HUMAN_EFFECT_CUT_REQUIRED'});const inherited=fixture();delete inherited.rows.thoughts[0].searchVersion;let reads=0;Object.defineProperty(Object.prototype,'searchVersion',{configurable:true,get(){reads++;return 'forged';}});try{refusal(inherited);assert.equal(reads,0);}finally{delete Object.prototype.searchVersion;}});
test('own iterators, array subclass iterators and version coercion objects are unsupported data rather than executed readers',()=>{for(const alter of [a=>Object.defineProperty(a,'0',{get(){assert.fail('array getter');},configurable:true,enumerable:true}),a=>Object.defineProperty(a,Symbol.iterator,{value:function*(){assert.fail('own iterator');}}),a=>Object.setPrototypeOf(a,{[Symbol.iterator]:function*(){assert.fail('prototype iterator');}})]){const raw=fixture();alter(raw.rows.thoughts);assert.throws(()=>inspect(raw));}const raw=fixture();raw.rows.thoughts[0].contentRevision={toString(){assert.fail('version coercion');}};refusal(raw);});
