import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {fail} from '../core/browser-native-sync/value.js';
import * as current from '../core/browser-native-sync/human-library-plan.js';
const ORIGINAL_METER="const branchOwn=Object.hasOwn,branchDescriptor=Object.getOwnPropertyDescriptor;\nfunction branchRawMeasure(value,limit=BRANCH_RAW_BYTES,stats=null,frozen=false){\n let size=0,nodes=0,slots=0,units=0;const add=n=>{size+=n;if(size>limit)fail('BNS_HUMAN_GRAPH_LIMIT');};\n const text=value=>{units+=value.length;add(2);for(let i=0;i<value.length;i++){const c=value.charCodeAt(i);if(c===34||c===92||c===8||c===9||c===10||c===12||c===13)add(2);else if(c<32)add(6);else if(c<128)add(1);else if(c<2048)add(2);else if(c>=0xd800&&c<=0xdbff){const next=value.charCodeAt(++i);if(!(next>=0xdc00&&next<=0xdfff))fail('BNS_TEXT_ENCODING');add(4);}else if(c>=0xdc00&&c<=0xdfff)fail('BNS_TEXT_ENCODING');else add(3);}};\n const visit=(v,depth)=>{\n  if(++nodes>200000||depth>32)fail('BNS_HUMAN_GRAPH_LIMIT');\n  if(v===null){add(4);return;}if(typeof v==='string'){text(v);return;}if(typeof v==='boolean'){add(v?4:5);return;}\n  if(typeof v==='number'){if(!Number.isFinite(v)||Object.is(v,-0))fail('BNS_VALUE_INVALID');add(String(v).length);return;}\n  if(!v||typeof v!=='object')fail('BNS_VALUE_INVALID');if(frozen===true&&!Object.isFrozen(v))fail('BNS_HUMAN_EFFECT_CUT_REQUIRED');\n  if(frozen==='native'&&!Array.isArray(v)&&![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail('BNS_HUMAN_EFFECT_CUT_REQUIRED');\n  add(2);\n  if(Array.isArray(v)){if(frozen==='native'){if(v.length>200000-nodes)fail('BNS_HUMAN_GRAPH_LIMIT');let own=0;for(const k in v)if(branchOwn(v,k)){if(++own>v.length||own>200000)fail('BNS_HUMAN_EFFECT_CUT_REQUIRED');}if(own!==v.length)fail('BNS_HUMAN_EFFECT_CUT_REQUIRED');}for(let i=0;i<v.length;i++){slots++;if(i)add(1);if(frozen){const d=branchDescriptor(v,String(i));if(!d||!('value'in d))fail('BNS_HUMAN_EFFECT_CUT_REQUIRED');visit(d.value,depth+1);}else visit(v[i],depth+1);}return;}\n  let first=true;const item=k=>{slots++;if(!first)add(1);first=false;text(k);add(1);if(frozen){const d=branchDescriptor(v,k);if(!d||!('value'in d))fail('BNS_HUMAN_EFFECT_CUT_REQUIRED');visit(d.value,depth+1);}else visit(v[k],depth+1);};\n  if(frozen){for(const k in v)if(branchOwn(v,k))item(k);}else{for(const k of Object.keys(v))item(k);}\n };\n visit(value,0);if(stats){stats.nodes=nodes;stats.slots=slots;stats.units=units;}return size;\n}\n";
const ORIGINAL_METER_SHA="2cbb302030061903e4e5712bccbae13b7d869f9b8b597487a9f26db19c25168e";
assert.equal(createHash('sha256').update(ORIGINAL_METER).digest('hex'),ORIGINAL_METER_SHA);
const original=Function('fail','BRANCH_RAW_BYTES',ORIGINAL_METER+'\nreturn branchRawMeasure;')(fail,4*1024*1024);
const inputs=[null,true,false,0,1,3.14,'plain','quote"\\\n中👩🏽‍💻',{z:'中',a:[1,false,null,'é']},[],{},[[],{}],Object.assign(Object.create(null),{a:'value'})];
for(const [i,input]of inputs.entries())test('original bounded meter canonical byte reference '+i,()=>{const stats={},n=original(input,4*1024*1024,stats);assert.equal(n,new TextEncoder().encode(JSON.stringify(input)).length);assert.ok(Number.isSafeInteger(stats.nodes)&&stats.nodes>0);assert.ok(Number.isSafeInteger(stats.slots)&&stats.slots>=0);assert.ok(Number.isSafeInteger(stats.units)&&stats.units>=0);});
test('original byte ceiling uses strict exact endpoint and fails one below',()=>{const input={title:'synthetic'},n=original(input);assert.equal(original(input,n),n);assert.throws(()=>original(input,n-1),{code:'BNS_HUMAN_GRAPH_LIMIT'});});
test('original invalid value encoding depth and immutable mode gates are preserved',()=>{for(const input of [-0,Infinity,NaN,undefined,Symbol('x'),1n,()=>{}])assert.throws(()=>original(input),{code:'BNS_VALUE_INVALID'});for(const input of ['\ud800','\udc00','\ud800x'])assert.throws(()=>original(input),{code:'BNS_TEXT_ENCODING'});let deep=null;for(let i=0;i<34;i++)deep={x:deep};assert.throws(()=>original(deep),{code:'BNS_HUMAN_GRAPH_LIMIT'});assert.throws(()=>original({a:1},4*1024*1024,null,true),{code:'BNS_HUMAN_EFFECT_CUT_REQUIRED'});assert.equal(original(Object.freeze({a:1}),4*1024*1024,null,true),7);});

test('exported meter is the original unchanged implementation on all valid inputs and explicit limit/stat modes',()=>{assert.equal(typeof current.branchRawMeasure,'function');for(const input of inputs)for(const statsMode of [false,true]){const oldStats=statsMode?{}:null,newStats=statsMode?{}:null;assert.equal(current.branchRawMeasure(input,4*1024*1024,newStats),original(input,4*1024*1024,oldStats));assert.deepEqual(newStats,oldStats);const n=original(input);assert.equal(current.branchRawMeasure(input,n),n);assert.throws(()=>current.branchRawMeasure(input,n-1),{code:'BNS_HUMAN_GRAPH_LIMIT'});}});
function observed(owner,value,limit=4*1024*1024,stats={},mode=false){try{return {ok:true,value:owner(value,limit,stats,mode),stats};}catch(error){return {ok:false,error:{name:error?.name??null,code:error?.code??null,message:error?.message??null},stats};}}
test('original private mutable frozen and native modes remain precisely identical without new validation',()=>{const accessor=Object.freeze({get x(){throw Error('frozen accessor must not execute');}});const plain=Object.freeze({x:Object.freeze(['中',null])}),sparse=Object.freeze(new Array(2));class Synthetic{constructor(){this.x=1;}}for(const input of [plain,accessor,sparse,new Synthetic(),Object.assign(Object.create(null),{x:1}),Object.assign([1],{extra:2}),{x:'\ud800'},[-0],undefined])for(const mode of [false,true,'native'])assert.deepEqual(observed(current.branchRawMeasure,input,4*1024*1024,{},mode),observed(original,input,4*1024*1024,{},mode));});
test('ordinary getter failure Error and null identity survive while protected modes never invoke getter',()=>{for(const value of [Error('synthetic raw getter failure'),null]){let reads=0;const input=Object.freeze({get x(){reads++;throw value;}});for(const owner of [original,current.branchRawMeasure]){let threw=false;try{owner(input);}catch(error){threw=true;assert.equal(error,value);}assert.equal(threw,true);}assert.equal(reads,2);reads=0;for(const owner of [original,current.branchRawMeasure])for(const mode of [true,'native'])assert.throws(()=>owner(input,4*1024*1024,null,mode),{code:'BNS_HUMAN_EFFECT_CUT_REQUIRED'});assert.equal(reads,0);}});
test('stats setter observation order partial failure and reference alias remain original',()=>{for(const failing of [null,'nodes','slots','units'])for(const thrown of [Error('synthetic stats setter'),null]){const run=owner=>{const trace=[],stats={};for(const name of ['nodes','slots','units'])Object.defineProperty(stats,name,{set(value){trace.push([name,value]);if(name===failing)throw thrown;}});try{return {value:owner({x:'中'},4*1024*1024,stats),trace};}catch(error){assert.equal(error,thrown);return {error,trace};}};assert.deepEqual(run(current.branchRawMeasure),run(original));}});
test('shared public computation adds only export to original function body and defaults',()=>{assert.equal(current.branchRawMeasure.toString(),original.toString());});
