import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {IndexedArchiveStore} from '../core/indexed-store.js';
import {IAStore} from '../core/ia-store.js';
globalThis.IDBKeyRange=IDBKeyRange;
const clock={now:'2026-01-01T00:00:00.000Z'};
function local(){let data={};return {async get(k){return {[k]:structuredClone(data[k])};},async set(v){Object.assign(data,structuredClone(v));}};}
const capture=(epoch,text='Synthetic source',id='synthetic-message-001')=>({epoch,adapterVersion:'0.3.0',chat:{id:'synthetic-chat-001',url:'https://chatgpt.com/c/synthetic-chat-001',title:'Synthetic chat'},messages:[{sourceMessageId:id,pageOrder:1,originalText:text,sourceTime:{state:'valid',createTime:1609459200,updateTime:null}}]});
async function setup(){const storage=local(),idb=new IDBFactory(),s=new IAStore(storage,{indexedDB:idb,clock:()=>clock.now});await s.consent(true);await s.capture(capture((await s.status()).epoch));return {s,storage,idb};}
async function edit(s,changes){const b=(await s.snapshot()).library.blocks[0];return s.editDocument({operationId:crypto.randomUUID(),documentId:b.documentId,blocks:[{id:b.id,expectedRevision:b.revision,libraryText:b.libraryText,note:b.note,excluded:b.excluded,...changes}]});}
test('IA migrates v05 authored blocks losslessly, starts empty, and resumes initialization',async()=>{
 const storage=local(),idb=new IDBFactory(),old=new IndexedArchiveStore(storage,{indexedDB:idb});await old.consent(true);await old.capture(capture((await old.status()).epoch));const b=(await old.snapshot()).library.blocks[0];await old.updateLibrary(b.id,{libraryText:'Synthetic authored input',note:'Synthetic note'});await old.excludeLibrary(b.id,true);await old.updateDocument(b.documentId,{userTitle:'Synthetic title'});const before=await old.snapshot();await old.repository.close();
 let crashed=false;const s=new IAStore(storage,{indexedDB:idb,checkpoint:async name=>{if(name==='ia-batch'&&!crashed){crashed=true;throw Error('SYNTHETIC_CRASH');}}});await assert.rejects(s.snapshot());await s.repository.close();const next=new IAStore(storage,{indexedDB:idb});const after=await next.snapshot();for(const key of ['records','library','conversations','preferences','settings'])assert.deepEqual(after[key],before[key],key);assert.deepEqual((await next.thoughtPage()).items,[]);assert.equal((await next.iaStatus()).phase,'active');assert.ok((await next.revisions({documentId:b.documentId})).items.length);await assert.rejects(old.snapshot(),{code:'STORAGE_FAILED'});
});
test('Input empty edit preserves source facts/time and explicit removal survives same-source new snapshot',async()=>{
 const {s}=await setup(),before=await s.snapshot();await edit(s,{libraryText:''});let after=await s.snapshot();assert.equal(after.library.blocks[0].excluded,false);assert.equal(after.library.blocks[0].libraryText,'');assert.deepEqual(after.records,before.records);
 await edit(s,{excluded:true});await s.capture(capture((await s.status()).epoch,'Synthetic changed source'));after=await s.snapshot();assert.equal(after.records.length,2);assert.ok(after.library.blocks.every(b=>b.excluded));await edit(s,{excluded:false});assert.equal((await s.snapshot()).library.blocks[0].excluded,false);
});
test('revision survives reopen, restores explicit removal, and source purge cannot be undone',async()=>{
 const {s,storage,idb}=await setup(),initial=await s.snapshot(),b=initial.library.blocks[0];await edit(s,{libraryText:'Synthetic user work'});await edit(s,{excluded:true});await s.repository.close();const again=new IAStore(storage,{indexedDB:idb});const history=await again.revisions({documentId:b.documentId}),deletion=history.items.find(x=>x.reason==='remove');assert.ok(deletion);let current=(await again.snapshot()).library.blocks[0];assert.equal((await again.restoreRevision({id:deletion.id,side:'before',expectedRevision:current.revision,operationId:crypto.randomUUID()})).ok,true);assert.equal((await again.snapshot()).library.blocks[0].excluded,false);await again.trash(initial.records[0].id);await again.purge(initial.records[0].id);assert.equal((await again.revisions({documentId:b.documentId})).items.filter(x=>x.entityId===b.id).length,0);await assert.rejects(again.restoreRevision({id:deletion.id,side:'before',expectedRevision:0}),{code:'INVALID_REQUEST'});await again.capture(capture((await again.status()).epoch));assert.equal((await again.snapshot()).records.length,0);
});
test('Thought dependencies are one-way, stale on Input edit, protected after user edits, and distinguish user_created',async()=>{
 const {s}=await setup(),before=await s.snapshot(),b=before.library.blocks[0];const thought=await s.createThought({provenanceType:'input_derived',inputRefs:[b.id],title:'Synthetic thought',thoughtText:'Synthetic conclusion',topics:['Design'],types:['Judgment']});assert.equal(thought.userEdited,false);await edit(s,{libraryText:'Synthetic input update'});let t=await s.thought(thought.id);assert.equal(t.freshness,'stale');await s.editThought({id:t.id,expectedRevision:t.revision,changes:{thoughtText:'Synthetic personal conclusion'}});t=await s.thought(t.id);const source=await s.snapshot();assert.equal(t.userEdited,true);assert.equal((await s.refreshThought({id:t.id,expectedRevision:t.revision,inputVersions:{[b.id]:1},thoughtText:'Should not overwrite'})).protected,true);assert.deepEqual((await s.snapshot()).records,before.records);assert.deepEqual((await s.snapshot()).library,source.library);assert.equal((await s.thought(t.id)).thoughtText,'Synthetic personal conclusion');const authored=await s.createThought({provenanceType:'user_created',inputRefs:[],thoughtText:'Standalone synthetic thought'});assert.deepEqual(authored.inputRefs,[]);await assert.rejects(s.createThought({provenanceType:'input_derived',inputRefs:[],thoughtText:'Invalid'}),{code:'INVALID_REQUEST'});
});
test('retention keeps 90 days OR latest 20 important versions, while typing coalesces',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];const original=clock.now;try{for(let i=0;i<25;i++){clock.now=new Date(Date.UTC(2026,0,i+2)).toISOString();await edit(s,{excluded:i%2===0});}clock.now='2026-09-06T00:00:00.000Z';await s.pruneRevisions();let history=await s.revisions({documentId:b.documentId});assert.equal(history.items.filter(x=>x.important).length,20);await edit(s,{libraryText:'a'});await edit(s,{libraryText:'ab'});history=await s.revisions({documentId:b.documentId});assert.equal(history.items.filter(x=>x.reason==='edit'&&!x.important).length,1);}finally{clock.now=original;}
});
test('removal invalidates single-source automatic Thoughts, preserves edited/multi-source, and purge clears detached revision payloads',async()=>{
 const {s}=await setup();await s.capture(capture((await s.status()).epoch,'Other synthetic input','synthetic-message-002'));const initial=await s.snapshot(),[a,b]=initial.library.blocks;
 const automatic=await s.createThought({provenanceType:'input_derived',inputRefs:[a.id],thoughtText:'Synthetic generated'}),edited=await s.createThought({provenanceType:'input_derived',inputRefs:[a.id],thoughtText:'Synthetic protected'}),multi=await s.createThought({provenanceType:'input_derived',inputRefs:[a.id,b.id],thoughtText:'Synthetic combined'});await s.editThought({id:edited.id,expectedRevision:0,changes:{note:'Synthetic authored note'}});await edit(s,{excluded:true});assert.equal((await s.thought(automatic.id)).lifecycle,'invalidated');assert.equal((await s.thought(edited.id)).lifecycle,'active');assert.equal((await s.thought(edited.id)).integrity,'detached');assert.equal((await s.thought(multi.id)).integrity,'partial');
 await s.permanentDelete(initial.records[0].id);await assert.rejects(s.thought(automatic.id),{code:'INVALID_REQUEST'});assert.equal((await s.thought(edited.id)).note,'Synthetic authored note');for(const id of [automatic.id,edited.id,multi.id])assert.equal((await s.revisions({documentId:id})).items.length,0);assert.equal((await s.thought(multi.id)).thoughtText,'Synthetic combined');
});
test('revision restoration rechecks purge inside commit and late refresh checks Input versions',async()=>{
 const {s}=await setup(),initial=await s.snapshot(),b=initial.library.blocks[0];const thought=await s.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic generated'});await edit(s,{libraryText:'Synthetic edited'});let t=await s.thought(thought.id);assert.equal((await s.refreshThought({id:t.id,expectedRevision:t.revision,inputVersions:{[b.id]:0},thoughtText:'Synthetic late result'})).conflict,true);assert.equal((await s.refreshThought({id:t.id,expectedRevision:t.revision,inputVersions:{[b.id]:1},thoughtText:'Synthetic current result'})).ok,true);assert.equal((await s.thought(t.id)).freshness,'current');
 const rev=(await s.revisions({documentId:b.documentId})).items[0];await s.permanentDelete(initial.records[0].id);const current=(await s.snapshot()).library.blocks[0];await assert.rejects(s.editDocument({documentId:b.documentId,restoreRevisionId:rev.id,revisionReason:'restore',blocks:[{id:b.id,expectedRevision:current.revision,libraryText:null,note:'',excluded:false}]}),{code:'INVALID_REQUEST'});
});
test('failed Input transaction rolls back suppression, journal and dependency invalidation together',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],thought=await s.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic generated'});const history=await s.revisions({documentId:b.documentId}),hook=s.afterInputEdit.bind(s);s.afterInputEdit=async(...args)=>{await hook(...args);throw new ArchiveErrorForTest();};function ArchiveErrorForTest(){return Error('SYNTHETIC_ABORT');}
 await assert.rejects(edit(s,{excluded:true}));assert.equal((await s.snapshot()).library.blocks[0].excluded,false);assert.equal((await s.thought(thought.id)).freshness,'current');assert.deepEqual(await s.revisions({documentId:b.documentId}),history);assert.equal(await s.repository.transaction(false,t=>t.count('inputRemovals')),0);
});
test('source identity, timestamps and provenance cannot be supplied in Thought or Input edits',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],t=await s.createThought({provenanceType:'user_created',inputRefs:[],thoughtText:'Synthetic own thought'}),before=await s.snapshot();for(const key of ['sourceSentAt','capturedAt','originalText','inputRefs','provenanceType','userEdited']){await assert.rejects(s.editThought({id:t.id,expectedRevision:0,changes:{[key]:'forbidden'}}),{code:'INVALID_REQUEST'});await assert.rejects(edit(s,{[key]:'forbidden'}),{code:'INVALID_REQUEST'});}assert.deepEqual((await s.snapshot()).records,before.records);
});
test('v051 task checkpoints, source evidence and settings survive IA mapping byte-for-byte',async()=>{
 const storage=local(),idb=new IDBFactory(),old=new IndexedArchiveStore(storage,{indexedDB:idb});await old.consent(true);await old.capture(capture((await old.status()).epoch));const tables=['importTasks','importBatches','importEvidence','importSources'],saved={};await old.repository.transaction(true,async t=>{for(const name of tables){saved[name]={id:'synthetic-'+name,status:'paused',checkpoint:3,sourceKey:'a'.repeat(64),digest:'b'.repeat(64)};await t.put(name,saved[name]);}});const before=await old.snapshot();await old.repository.close();const s=new IAStore(storage,{indexedDB:idb});const after=await s.snapshot();for(const key of ['records','library','settings','preferences','conversations'])assert.deepEqual(after[key],before[key]);for(const name of tables)assert.deepEqual(await s.repository.transaction(false,t=>t.get(name,saved[name].id)),saved[name]);
});
test('legacy identity enrichment transfers removal suppression before a changed snapshot arrives',async()=>{
 const storage=local(),idb=new IDBFactory(),old=new IndexedArchiveStore(storage,{indexedDB:idb});await old.consent(true);await old.capture(capture((await old.status()).epoch));const b=(await old.snapshot()).library.blocks[0];await old.excludeLibrary(b.id,true);await old.repository.transaction(true,async t=>{const r=await t.get('records',b.sourceRecordId),ix=await t.get('recordIndex',b.sourceRecordId);delete r.value.sourceKey;delete ix.sourceKey;ix.legacyChat='chatgpt:synthetic-chat-001';await t.put('records',r);await t.put('recordIndex',ix);});await old.repository.close();const s=new IAStore(storage,{indexedDB:idb});await s.snapshot();await s.capture(capture((await s.status()).epoch));await s.capture(capture((await s.status()).epoch,'Synthetic new snapshot'));assert.ok((await s.snapshot()).library.blocks.every(b=>b.excluded));
});
test('legacy compatibility user decision updates removal intent and durable history',async()=>{
 const {s}=await setup();let st=await s.snapshot();await s.update(st.records[0].id,{hidden:true});await s.resolveLegacy(st.records[0].id,false);await s.capture(capture((await s.status()).epoch,'Synthetic after legacy decision'));st=await s.snapshot();assert.ok(st.library.blocks.every(b=>b.excluded));assert.ok((await s.revisions({documentId:st.conversations[0].id})).items.some(r=>r.reason==='remove'));
});
