import test from 'node:test';import assert from 'node:assert/strict';
import {readArchiveProjectSearch,sameArchiveProjectSearch} from '../ui/archive-project-search.js';
const ref={providerKey:'chatgpt',namespace:'synthetic-account',projectId:'same-id'},subject={kind:'conversation',conversationRef:{platform:'chatgpt',sourceConversationId:'synthetic-conversation'}};
const relation=()=>({current:{membership:{state:'project',projectRef:ref},sourceStatus:'observed_active',relationshipRevision:3,lastKnownSourceProject:{name:'STALE_NAME'}}});
const project=()=>({current:{currentName:'CURRENT_NAME',sourceStatus:'observed_active',relationshipRevision:4}});
test('Project action uses current qualified membership and actual current project name',async()=>{const calls=[];const result=await readArchiveProjectSearch(async s=>{calls.push(s);return s.kind==='conversation'?relation():project();},subject);assert.deepEqual(result,{ref,title:'CURRENT_NAME',conversationRevision:3,projectRevision:4});assert.deepEqual(calls,[subject,{kind:'project',projectRef:ref},subject]);assert.equal(sameArchiveProjectSearch(result,structuredClone(result)),true);assert.equal(sameArchiveProjectSearch(result,{...result,ref:{...ref,namespace:'other-account'}}),false);assert.equal(sameArchiveProjectSearch(result,{...result,projectRevision:5}),false);});
test('unknown, unassigned, deleted, malformed or last-known-only membership cannot select Project',async()=>{for(const row of [null,{...relation().current,membership:{state:'unknown',projectRef:null}},{...relation().current,membership:{state:'unassigned',projectRef:null}},{...relation().current,sourceStatus:'confirmed_deleted'},{...relation().current,membership:{state:'project',projectRef:{...ref,namespace:'bad namespace'}}},{...relation().current,membership:{state:'project',projectRef:{...ref,providerKey:'other-provider'}}}]){let reads=0;assert.equal(await readArchiveProjectSearch(async()=>{reads++;return {current:row};},subject),null);assert.equal(reads,1);}});
test('unavailable, nameless or deleted current Project never substitutes last-known name',async()=>{for(const row of [null,{...project().current,currentName:null},{...project().current,currentName:' '},{...project().current,sourceStatus:'confirmed_deleted'}])assert.equal(await readArchiveProjectSearch(async s=>s.kind==='conversation'?relation():{current:row},subject),null);});
test('superseded reads refuse both relationship and project delivery',async()=>{for(const kind of ['conversation','project']){let current=true,calls=0;const value=await readArchiveProjectSearch(async s=>{calls++;if(s.kind===kind)current=false;return s.kind==='conversation'?relation():project();},subject,()=>current);assert.equal(value,null);assert.equal(calls,kind==='conversation'?1:2);}});

test('relationship move, deletion and namespace replacement while Project read is held cannot yield mixed-current scope',async()=>{for(const change of ['move','deleted','namespace']){let row=relation().current;const result=await readArchiveProjectSearch(async s=>{if(s.kind==='project'){row={...row,relationshipRevision:4,...(change==='deleted'?{sourceStatus:'confirmed_deleted'}:{membership:{state:'project',projectRef:{...ref,...(change==='namespace'?{namespace:'other-account'}:{projectId:'moved'})}}})};return project();}return {current:row};},subject);assert.equal(result,null,change);}});
