import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {IndexedArchiveStore} from '../core/indexed-store.js';import {ImportLedger} from '../core/import/ledger.js';
import {ImportCoordinator} from '../core/import/coordinator.js';import {syntheticAdapter,syntheticRow} from './fixtures/import-adapter.mjs';
globalThis.IDBKeyRange=IDBKeyRange;
async function setup(){let s={};const local={async get(k){return {[k]:structuredClone(s[k])};},async set(v){Object.assign(s,v);}};const store=new IndexedArchiveStore(local,{indexedDB:new IDBFactory()});await store.consent(true);const ledger=new ImportLedger(store,{verifiedAdapters:['synthetic-v1']});return {store,ledger,transport:async(method,q)=>ledger[method](q,'test-page')};}
const file=(n=65)=>new Blob([JSON.stringify(Array.from({length:n},(_,i)=>syntheticRow(i+1)))]);
test('unverified production adapter completes syntax inspection but never touches transport or archives',async()=>{let calls=0;const c=new ImportCoordinator({transport:async()=>{calls++;}});await c.select(file(1),{consent:true});const r=await c.preflight();assert.equal(r.phase,'unsupported');assert.equal(calls,0);await assert.rejects(c.commit(),{code:'SCHEMA_UNVERIFIED'});});
test('coordinator batches with backpressure and keeps preview separate from explicit commit',async()=>{const {store,transport}=await setup();let inFlight=0,max=0;const c=new ImportCoordinator({adapter:syntheticAdapter,transport:async(m,q)=>{max=Math.max(max,++inFlight);try{return await transport(m,q);}finally{inFlight--;}}});await c.select(file(),{consent:true});const p=await c.preflight();assert.equal(p.checkedBatches,3);assert.equal((await store.snapshot()).records.length,0);const r=await c.commit();assert.equal(r.phase,'completed');assert.equal(r.counts.added,65);assert.equal(max,1);assert.equal((await store.snapshot()).records.length,65);});
test('lost acknowledgement resumes from atomic committed checkpoint after file reselection',async()=>{const {store,ledger,transport}=await setup();let drop=true;const c=new ImportCoordinator({adapter:syntheticAdapter,transport:async(m,q)=>{const r=await transport(m,q);if(m==='commit'&&drop){drop=false;throw Error('SYNTHETIC_LOST_ACK');}return r;}});await c.select(file(),{consent:true});const p=await c.preflight();await assert.rejects(c.commit());assert.equal((await store.snapshot()).records.length,32);assert.equal((await ledger.status(p.taskId)).committedBatches,1);const again=new ImportCoordinator({adapter:syntheticAdapter,transport});await again.select(file(),{consent:true,taskId:p.taskId});await again.preflight();const r=await again.commit();assert.equal(r.counts.added,65);assert.equal((await store.snapshot()).records.length,65);});
test('pause discards the selected file and requires new consent instead of silently resuming',async()=>{const {transport}=await setup(),c=new ImportCoordinator({adapter:syntheticAdapter,transport});await c.select(file(1),{consent:true});await c.preflight();await c.pause();assert.equal(c.hasFile,false);await assert.rejects(c.commit(),{code:'CONSENT_REQUIRED'});await assert.rejects(c.select(file(1),{consent:false}),{code:'CONSENT_REQUIRED'});});
test('pause while begin awaits acknowledgement revokes the arriving grant before any preflight',async()=>{const {transport,store,ledger}=await setup();let entered,release;const waiting=new Promise(r=>entered=r),gate=new Promise(r=>release=r);let task;const c=new ImportCoordinator({adapter:syntheticAdapter,transport:async(m,q)=>{const r=await transport(m,q);if(m==='begin'){task=r.taskId;entered();await gate;}return r;}});await c.select(file(),{consent:true});const run=c.preflight();await waiting;await c.pause();release();await assert.rejects(run,{code:'CANCELLED'});assert.equal(c.hasFile,false);assert.equal((await ledger.status(task)).checkedBatches,0);assert.equal(ledger.grants.size,0);assert.equal((await store.snapshot()).records.length,0);});
test('a corrupt later ZIP shard prevents every archive write, even after earlier preflight batches',async()=>{const {zip:syntheticZip}=await import('./fixtures/import-zip.mjs');const {transport,store}=await setup(),c=new ImportCoordinator({adapter:syntheticAdapter,transport});const zip=syntheticZip([{name:'conversations-1.json',text:JSON.stringify(Array.from({length:33},(_,i)=>syntheticRow(i+1)))},{name:'conversations-2.json',text:JSON.stringify([syntheticRow(99)]),badCrc:true}]);await c.select(zip,{consent:true});await assert.rejects(c.preflight(),{code:'ZIP_INTEGRITY'});assert.equal((await store.snapshot()).records.length,0);assert.equal(c.hasFile,false);});
