import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';import {IndexedArchiveStore} from '../core/indexed-store.js';import {STORES} from '../core/idb-repository.js';
globalThis.IDBKeyRange=IDBKeyRange;
test('additive database v1 to v2 upgrade preserves every old row, index, and setting',async()=>{
 const idb=new IDBFactory();let state={};const local={async get(k){return {[k]:structuredClone(state[k])};},async set(v){Object.assign(state,structuredClone(v));}};const seed=new IndexedArchiveStore(local,{indexedDB:idb,name:'seed'});await seed.consent(true);await seed.capture({epoch:(await seed.status()).epoch,adapterVersion:'0.3.0',chat:{id:'synthetic-chat-001',url:'https://chatgpt.com/c/synthetic-chat-001',title:'Synthetic'},messages:[{sourceMessageId:'synthetic-message-001',pageOrder:1,originalText:'Synthetic kept'}]});let snapshot=await seed.snapshot();await seed.updateLibrary(snapshot.library.blocks[0].id,{libraryText:'Synthetic authored',note:'Synthetic note'});snapshot=await seed.snapshot();const saved=structuredClone(state),tables=STORES.filter(n=>!n.startsWith('import')),rows={},indices={};
 for(const name of tables){rows[name]=await seed.repository.transaction(false,t=>t.all(name));const s=seed.repository.db.transaction(name).objectStore(name);indices[name]=[...s.indexNames].map(n=>{const i=s.index(n);return {name:n,keyPath:i.keyPath,unique:i.unique,multiEntry:i.multiEntry};});}
 const old=await new Promise((resolve,reject)=>{const r=idb.open('upgrade',1);r.onupgradeneeded=()=>{for(const name of tables){const st=r.result.createObjectStore(name,{keyPath:'id'});for(const i of indices[name])st.createIndex(i.name,i.keyPath,{unique:i.unique,multiEntry:i.multiEntry});for(const row of rows[name])st.put(row);}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});old.close();
 const upgraded=new IndexedArchiveStore(local,{indexedDB:idb,name:'upgrade'});assert.deepEqual(await upgraded.snapshot(),snapshot);assert.deepEqual(state,saved);assert.equal(upgraded.repository.db.version,2);
 for(const name of tables){assert.deepEqual(await upgraded.repository.transaction(false,t=>t.all(name)),rows[name]);assert.deepEqual([...upgraded.repository.db.transaction(name).objectStore(name).indexNames],indices[name].map(i=>i.name));}
 for(const name of STORES.filter(n=>n.startsWith('import')))assert.equal(await upgraded.repository.transaction(false,t=>t.count(name)),0);
 await upgraded.repository.close();await assert.rejects(new Promise((resolve,reject)=>{const r=idb.open('upgrade',1);r.onerror=()=>reject(r.error);r.onsuccess=()=>resolve(r.result);}),{name:'VersionError'});
});
