import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {DocumentEditor} from '../ui/library.js';
import {WorkingInputSaveSession} from '../ui/working-input-save.js';
import {InputRecoveryPresentation,recoveredInputFields,recoveredInputCopy,recoveredInputInvalidated} from '../ui/input-recovery-presentation.js';
import {setup,inputEdit} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
const value=b=>({libraryText:b.libraryText,note:b.note,excluded:b.excluded});
async function editorFixture({stale=false,unknown=false,same=false}={}){
 const {s}=await setup(OrganizerStore),snapshot=await s.snapshot(),before=snapshot.library.blocks[0],document=snapshot.conversations.find(row=>row.id===before.documentId);
 const edit={operationId:crypto.randomUUID(),documentId:before.documentId,blocks:[{id:before.id,expectedRevision:before.revision,libraryText:'SYNTHETIC recovered local draft',note:before.note,excluded:before.excluded}]};
 if(stale)await inputEdit(s,before.id,{libraryText:same?edit.blocks[0].libraryText:'SYNTHETIC later canonical body'});
 const current=await s.input(before.id),calls=[],statuses=[],editor=Object.create(DocumentEditor.prototype);
 Object.assign(editor,{id:before.documentId,title:document.userTitle,savedTitle:document.userTitle,titleRevision:document.titleRevision,entries:new Map([[before.id,{saved:value(current),local:value(current),revision:current.revision,signature:current.provenanceSignature,original:snapshot.records[0].originalText}]]),saveSession:new WorkingInputSaveSession(async(type,args)=>{calls.push({type,args});if(unknown){if(type==='EDIT_DOCUMENT')throw Error('SYNTHETIC lost channel');return {state:'unknown'};}return type==='EDIT_DOCUMENT'?s.editDocument(args.edit):s.operationOutcome(args.query);}),autosave:{cancel(){}},paint(){},onStatus:(...args)=>statuses.push(args),onRecovered(){},admitRecoveryInputs:async()=>{},recovery:{epoch:await s.recoveryDraftEpoch(),load:async()=>({token:edit.operationId,operation:{type:'EDIT_DOCUMENT',edit}}),clear:async()=>true}});
 return {s,before,editor,edit,calls,statuses};
}
test('S02 emits only IDs after the original stale recovery attempt and adds no canonical write',async()=>{
 const {s,before,editor,edit,calls,statuses}=await editorFixture({stale:true}),canonical=await s.input(before.id);assert.equal(await editor.restoreRecovery(),false);assert.deepEqual(calls,[{type:'EDIT_DOCUMENT',args:{edit}}]);assert.deepEqual(editor.recoveryConflict,{documentId:before.documentId,title:false,inputIds:[before.id]});assert.equal(JSON.stringify(editor.recoveryConflict).includes('SYNTHETIC'),false);assert.equal(statuses.at(-1)[1],'conflict');assert.equal(editor.entries.get(before.id).local.libraryText,edit.blocks[0].libraryText);assert.equal(await editor.flush(),false);assert.equal(calls.length,1);assert.deepEqual(await s.input(before.id),canonical);assert.equal(recoveredInputFields(editor)[0].text,edit.blocks[0].libraryText);
});
test('S02 excludes successful replay, unknown outcomes and ordinary conflicts',async()=>{
 for(const unknown of [false,true]){const {s,before,editor,statuses}=await editorFixture({unknown});assert.equal(await editor.restoreRecovery(),!unknown);await new Promise(resolve=>setImmediate(resolve));assert.equal(editor.recoveryConflict,undefined);assert.deepEqual(recoveredInputFields(editor),[]);if(unknown){assert.equal(statuses.at(-1)[1],'unknown');assert.equal((await s.input(before.id)).libraryText,before.libraryText);}else assert.equal((await s.input(before.id)).libraryText,'SYNTHETIC recovered local draft');}
 assert.deepEqual(recoveredInputFields({id:'doc',conflicted:true,entries:new Map()}),[]);
});
class Node{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.parentNode=null;this.dataset={};this.attributes=new Map();this.listeners=new Map();this.hidden=false;this.inert=false;this.disabled=false;this._text='';const classes=new Set();this.classList={contains:name=>classes.has(name),add:name=>classes.add(name),remove:name=>classes.delete(name),toggle(name,force){const use=force??!classes.has(name);if(use)classes.add(name);else classes.delete(name);return use;}};}
 get textContent(){return this._text+this.children.map(node=>node.textContent).join('');}set textContent(text){this.replaceChildren();this._text=String(text);}
 get firstElementChild(){return this.children[0];}get lastElementChild(){return this.children.at(-1);}get nextSibling(){return this.parentNode?.children[this.parentNode.children.indexOf(this)+1]||null;}get isConnected(){return this===document.body||!!this.parentNode?.isConnected;}
 append(...nodes){for(const node of nodes)this.insertBefore(node,null);}insertBefore(node,before){node.remove();node.parentNode=this;this.children.splice(before?this.children.indexOf(before):this.children.length,0,node);}replaceChildren(...nodes){this._text='';for(const node of [...this.children])node.remove();this.append(...nodes);}remove(){if(this.parentNode){this.parentNode.children.splice(this.parentNode.children.indexOf(this),1);this.parentNode=null;}}
 contains(node){return node===this||this.children.some(child=>child.contains(node));}setAttribute(name,value){this.attributes.set(name,String(value));}getAttribute(name){return this.attributes.get(name)??null;}removeAttribute(name){this.attributes.delete(name);}addEventListener(name,handler){this.listeners.set(name,handler);}click(){return this.listeners.get('click')?.();}focus(){if(!this.disabled)document.activeElement=this;}
}
async function dom(run){
 const names=['document','window','navigator'],prior=new Map(names.map(name=>[name,Object.getOwnPropertyDescriptor(globalThis,name)])),body=new Node(),copied=[];
 const globals={document:{body,documentElement:{lang:'zh-CN'},activeElement:body,createElement:tag=>new Node(tag),addEventListener(){},querySelector:()=>null},window:{scrollY:0,scrollTo(_x,y){this.scrollY=y;}},navigator:{clipboard:{writeText:async text=>copied.push(text)}}};
 for(const [name,v]of Object.entries(globals))Object.defineProperty(globalThis,name,{configurable:true,writable:true,value:v});try{await run({body,copied});}finally{for(const [name,v]of prior)if(v)Object.defineProperty(globalThis,name,v);else delete globalThis[name];}
}
function owner(){return {id:'doc',conflicted:true,disposed:false,title:'SYNTHETIC local title',savedTitle:'saved title',root:new Node(),recovery:{epoch:'epoch'},recoveryConflict:{documentId:'doc',title:true,inputIds:['one','two']},entries:new Map([
 ['one',{local:{libraryText:'SYNTHETIC local first\n\n完整末行',note:'SYNTHETIC local note',excluded:false},saved:{libraryText:'remote first',note:'remote note',excluded:false},revision:2,signature:'source-one',original:'SYNTHETIC original one'}],['two',{local:{libraryText:'',note:'',excluded:false},saved:{libraryText:'remote second',note:'',excluded:false},revision:2,signature:'source-two',original:'SYNTHETIC original two'}]]),text(entry){return entry.local.libraryText??entry.original;}};}
function mounted(body){const active=owner(),host=new Node(),home=new Node(),compare=new Node('button'),next=new Node();compare.textContent='查看两份文字';home.append(compare,next);host.append(home,active.root);body.append(host);const current={view:'library',documentId:'doc',editor:active,state:{recoveryEpoch:'epoch',library:{blocks:[]}}},surface=new InputRecoveryPresentation({host,compare,read:()=>current});return {active,host,home,compare,next,current,surface};}
test('S02 projects full title, multiple bodies, notes and empty text without truncation or unaffected content',()=>dom(()=>{
 const active=owner(),before=structuredClone([...active.entries]),fields=recoveredInputFields(active);assert.deepEqual(fields.map(field=>field.id),['title','one:body','one:note','two:body']);assert.equal(recoveredInputCopy(fields),'标题\nSYNTHETIC local title\n\n正文 · 1\nSYNTHETIC local first\n\n完整末行\n\n备注 · 1\nSYNTHETIC local note\n\n正文 · 2\n');assert.deepEqual([...active.entries],before);active.entries.get('one').local.libraryText='界'.repeat(120000);assert.equal(recoveredInputFields(active)[1].text.length,120000);document.documentElement.lang='en';assert.match(recoveredInputCopy(recoveredInputFields(active)),/^Title\n/);
}));
test('S02 never reads old purged bodies, unavailable rows, stale Source fallback or replaced epochs',()=>dom(()=>{
 const active=owner(),state={recoveryEpoch:'epoch',library:{blocks:[{id:'one',recoveryPurgeRevision:3,provenanceSignature:'purged'}]},unavailableTrackedInputIds:['two']};assert.deepEqual(recoveredInputFields(active,state).map(field=>field.id),['title']);active.recoveryConflict.title=false;assert.deepEqual(recoveredInputFields(active,state),[]);delete state.library.blocks[0].recoveryPurgeRevision;active.entries.get('one').local.libraryText=null;assert.deepEqual(recoveredInputFields(active,state).map(field=>field.id),['one:note']);state.library.blocks[0].provenanceSignature='source-one';assert.equal(recoveredInputFields(active,state)[0].text,'SYNTHETIC original one');state.recoveryEpoch='replaced';assert.deepEqual(recoveredInputFields(active,state),[]);state.recoveryEpoch='epoch';active.disposed=true;assert.deepEqual(recoveredInputFields(active,state),[]);
}));
test('S02 keeps the same editor and Compare node, copies current fields and restores its original home without navigation',()=>dom(async({body,copied})=>{
 const {active,home,compare,next,surface}=mounted(body);let comparisons=0;compare.addEventListener('click',()=>comparisons++);window.scrollY=132;const root=active.root;surface.sync();assert.equal(surface.root.hidden,false);assert.equal(active.root,root);assert.equal(root.inert,true);assert.equal(compare.parentNode,surface.actions);assert.deepEqual(body.dataset,{});const first=surface.fields.children[0];surface.sync();assert.equal(surface.fields.children[0],first);compare.click();assert.equal(comparisons,1);active.entries.get('one').local.note='SYNTHETIC latest note';await surface.copyDraft();assert.match(copied.at(-1),/latest note/);assert.doesNotMatch(copied.at(-1),/remote|original/);compare.focus();active.conflicted=false;surface.sync();assert.equal(surface.root.hidden,true);assert.equal(surface.fields.textContent,'');assert.equal(active.recoveryConflict,null);assert.equal(root.inert,false);assert.equal(compare.parentNode,home);assert.equal(compare.nextSibling,next);assert.equal(compare.textContent,'查看两份文字');assert.equal(compare.getAttribute('aria-describedby'),null);assert.equal(document.activeElement,root);assert.equal(window.scrollY,132);active.conflicted=true;surface.sync();assert.equal(surface.root.hidden,true);
}));
test('S02 removed fields and a new route clear presentation before copying and do not steal focus',()=>dom(async({body,copied})=>{
 const {active,current,surface}=mounted(body);surface.sync();active.entries.clear();active.recoveryConflict.title=false;await surface.copyDraft();assert.equal(copied.length,0);assert.equal(surface.fields.textContent,'');assert.equal(surface.root.hidden,true);active.recoveryConflict.title=true;surface.sync();const target=new Node('button');body.append(target);target.focus();current.view='settings';surface.sync();assert.equal(document.activeElement,target);assert.equal(active.root.inert,false);
}));
test('S02 cannot issue persistence commands or replace navigation, and original rebase still precedes explicit retry',async()=>{
 const source=await readFile(new URL('../ui/input-recovery-presentation.js',import.meta.url),'utf8'),archive=await readFile(new URL('../ui/archive.js',import.meta.url),'utf8');assert.doesNotMatch(source,/\brequest\s*\(|chrome\.|\.flush\s*\(|\.clear\s*\(|\.save\s*\(|navigate\s*\(|history\.|localStorage|sessionStorage/);assert.match(source,/copyReadingText\(text,\{fallback:false\}\)/);assert.match(archive,/\$\('reload-document'\)\.addEventListener\('click'/);assert.match(archive,/active\.failed=false;active\.conflicted=false;active\.revisions\.last=null;status\('尚未保存，核对后可重试保存。','error'\)/);
});
test('S02 delayed clipboard rejection cannot revive text after purge, disposal or newer copying',()=>dom(async({body})=>{
 for(const change of ['purge','dispose','newer']){const {active,current,surface,host}=mounted(body);surface.sync();let reject;navigator.clipboard.writeText=()=>new Promise((_resolve,fail)=>reject=fail);const pending=surface.copyDraft();if(change==='purge'){current.state.recoveryEpoch='replaced';surface.sync();}else if(change==='dispose'){active.disposed=true;surface.sync();}else{active.entries.get('one').local.libraryText='SYNTHETIC newer';surface.sync();navigator.clipboard.writeText=async()=>{};await surface.copyDraft();}reject(Error('SYNTHETIC late denial'));await pending;assert.equal(body.children.some(node=>node.tagName==='DIALOG'),false);if(change!=='newer')assert.equal(surface.fields.textContent,'');else assert.equal(surface.copyButton.textContent,'已复制');surface.hide();host.remove();}
}));
const compareFunction=async()=>{const source=await readFile(new URL('../ui/archive.js',import.meta.url),'utf8'),start=source.indexOf('async function compareInputConflict(){');return source.slice(start,source.indexOf("\ndocument.addEventListener('paia:open-topic'",start));};
const remoteFor=active=>({library:{blocks:[...active.entries].map(([id,e])=>({id,...e.saved,revision:3,provenanceSignature:e.signature}))},records:[],conversations:[{id:active.id,userTitle:'remote title',titleRevision:3}]});
test('S02 deferred comparison refuses disposed/replaced owners and either snapshot purge or epoch invalidation',async()=>{
 const fn=await compareFunction();for(const change of ['disposed-read','replaced-read','purged-read','purged-confirm','purged-response','epoch-response']){const active=owner();active.collect=()=>{};active.revisions={last:null};const remote=remoteFor(active),current={recoveryEpoch:'epoch',library:{blocks:remote.library.blocks.map(row=>({...row}))}};let finishRead,finishConfirm;const dialogs=[],context={editor:active,documentId:'doc',state:current,recoveredInputInvalidated,inputRecovery:{owner:active,beginComparison:()=>true,endComparison(){},watchComparison(){},releaseComparison(){}},request:()=>new Promise(resolve=>finishRead=resolve),element:()=>({append(){}}),notify(){},status(){throw Error('Invalidated compare cannot rebase');},confirmReaderAction:details=>{dialogs.push(details);return new Promise(resolve=>finishConfirm=resolve);}};vm.createContext(context);const pending=vm.runInContext(fn+';compareInputConflict()',context),initial=structuredClone([...active.entries]);if(change==='disposed-read')active.disposed=true;else if(change==='replaced-read')context.editor=owner();else if(change==='purged-read')current.library.blocks[0].recoveryPurgeRevision=4;if(change==='purged-response')remote.library.blocks[0].recoveryPurgeRevision=4;else if(change==='epoch-response')remote.recoveryEpoch='replacement';finishRead(remote);await new Promise(resolve=>setImmediate(resolve));if(change==='purged-confirm'){assert.equal(dialogs.length,1);current.library.blocks[0].recoveryPurgeRevision=4;finishConfirm(true);}else assert.equal(dialogs.length,0);await pending;assert.deepEqual([...active.entries],initial);assert.equal(active.conflicted,true);}
});
test('S02 closes and clears an open comparison after current Source or owner invalidation',()=>dom(({body})=>{
 for(const change of ['purge','epoch','owner']){const {active,current,surface,host}=mounted(body);current.state.library.blocks=[{id:'one',provenanceSignature:'source-one'}];surface.sync();let closed=false;const content=new Node();content.textContent='SYNTHETIC old compared text';content.closest=()=>({close(){closed=true;}});surface.watchComparison(active,content);if(change==='purge')current.state.library.blocks[0].recoveryPurgeRevision=3;else if(change==='epoch')current.state.recoveryEpoch='replacement';else current.editor=owner();surface.sync();assert.equal(closed,true);assert.equal(content.textContent,'');assert.equal(surface.comparison,null);surface.hide();host.remove();}
}));
test('S02 busy lock spans deferred read and original modal but duplicate clicks cannot create another comparison',async()=>{
 const fn=await compareFunction(),active=owner();active.collect=()=>{};let busy=false,reads=0,finishRead,finishConfirm;const dialogs=[],remote=remoteFor(active),compare={id:'original-button'},context={editor:active,documentId:'doc',state:{recoveryEpoch:'epoch',library:{blocks:remote.library.blocks}},recoveredInputInvalidated,inputRecovery:{owner:active,compare,beginComparison(){if(busy)return false;busy=true;return true;},endComparison(){busy=false;},watchComparison(){},releaseComparison(){}},request:()=>{reads++;return new Promise(resolve=>finishRead=resolve);},element:()=>({append(){}}),notify(){},confirmReaderAction:details=>{dialogs.push(details);return new Promise(resolve=>finishConfirm=resolve);}};vm.createContext(context);vm.runInContext(fn,context);const first=vm.runInContext('compareInputConflict()',context);await vm.runInContext('compareInputConflict()',context);assert.equal(reads,1);finishRead(remote);await new Promise(resolve=>setImmediate(resolve));assert.equal(dialogs.length,1);assert.equal(dialogs[0].invoker,compare);await vm.runInContext('compareInputConflict()',context);assert.equal(reads,1);finishConfirm(false);await first;assert.equal(busy,false);
});
test('S02 watches additional live dirty Inputs collected before recovery finished',()=>{const active=owner();active.entries.set('extra',{local:{libraryText:'live edit',note:'',excluded:false},saved:{libraryText:'prior',note:'',excluded:false},revision:1,signature:'extra-source'});assert.equal(recoveredInputInvalidated(active,{library:{blocks:[{id:'extra',provenanceSignature:'extra-source',recoveryPurgeRevision:2}]}}),true);});
test('S02 logical busy lock leaves the original modal invoker focusable during cancellation',()=>dom(({body})=>{
 const {active,compare,surface}=mounted(body);surface.sync();assert.equal(surface.beginComparison(active),true);assert.equal(compare.disabled,true);assert.equal(surface.beginComparison(active),false);const content=new Node();surface.watchComparison(active,content);assert.equal(compare.disabled,false);surface.sync();assert.equal(compare.disabled,false);compare.focus();assert.equal(document.activeElement,compare);assert.equal(surface.beginComparison(active),false);surface.releaseComparison(content);surface.endComparison(active);assert.equal(compare.disabled,false);
}));
test('Stale-revision recovery with identical canonical fields keeps the original Compare entry and leave resolution',async()=>{
 const {editor:active}=await editorFixture({stale:true,same:true});assert.equal(await active.restoreRecovery(),false);assert.deepEqual(recoveredInputFields(active),[]);active.collect=()=>{};active.revisions={last:{}};const remote=remoteFor(active);remote.conversations[0].userTitle=active.title;const statuses=[],context={editor:active,documentId:active.id,state:{recoveryEpoch:active.recovery.epoch,library:{blocks:remote.library.blocks}},recoveredInputInvalidated,inputRecovery:{owner:null,beginComparison(){throw Error('A hidden presenter must not lock comparison');},endComparison(){throw Error('No presentation lock was acquired');},watchComparison(){throw Error('No S02 surface exists');},releaseComparison(){}},request:async()=>remote,element:()=>({append(){}}),notify(){},status:(...args)=>statuses.push(args),confirmReaderAction:async()=>true};vm.createContext(context);await vm.runInContext(await compareFunction()+';compareInputConflict()',context);assert.equal(active.conflicted,false);assert.equal(active.failed,false);assert.equal(await active.flush(),true);assert.equal(statuses.at(-1)[1],'error');
});

test('S02 typography keeps proportional leading and coarse-size targets',async()=>{
 const css=await readFile(new URL('../ui/input-recovery-presentation.css',import.meta.url),'utf8');assert.doesNotMatch(css,/line-height:\s*[0-9.]+px|font:[^;{}]*\/\s*[0-9.]+px/);assert.match(css,/@media\(max-width:767px\),\(pointer:coarse\).*min-height:44px/);
});
