import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,cp,rm,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {FakeChatGPT,conversation,eventually} from './harness/fake-chatgpt.mjs';import {inputDigest} from '../scripts/compatibility-gate.mjs';
const targetVersion=JSON.parse(await readFile('manifest.json','utf8')).version;
test('frozen v0611 upgrades in isolated Chrome: old unknown cache re-evaluates with reason counters and source invariants',{timeout:120000},async()=>{
 const parent=await mkdtemp(join(tmpdir(),'paia-coverage-upgrade-')),old=join(parent,'old'),installed=join(parent,'installed'),next=join(parent,'next');let h;
 try{
  await mkdir(old);execFileSync('git',['archive','1e00c23','-o',join(parent,'old.tar')]);execFileSync('tar',['-xf',join(parent,'old.tar'),'-C',old]);const build="import sys;sys.path.insert(0,'scripts');from build_internal import build_internal;build_internal(sys.argv[1],sys.argv[2])";execFileSync('/usr/bin/python3',['-c',build,old,installed]);execFileSync('/usr/bin/python3',['-c',build,process.cwd(),next]);
  h=await FakeChatGPT.start({extensionPath:installed});const manager=await h.context.newPage();await manager.goto('chrome://extensions');await manager.locator('#devMode').click();await manager.close();let p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();const c=conversation('coverage-upgrade-synthetic');c.messages=['继续','开始吧','再生成一个','这个呢','继续，但不要修改原始数据','朽才是不朽'].map((text,n)=>({id:'coverage-synthetic-'+n,text}));await h.open(c);await eventually(async()=>(await h.state()).records.length===6);
  const send=async type=>(await p.evaluate(type=>chrome.runtime.sendMessage({type}),type)).data;await eventually(async()=>(await send('FILTER_DIAGNOSTICS'))?.pending===0);const prior=await send('FILTER_DIAGNOSTICS');assert.equal(prior.filter,0);assert.equal(prior.uncertain,6);
  const tables=['records','times','tombstones','blocks','documents','libraryDocuments','inputStates','inputRemovals','revisions','importTasks','importBatches','importEvidence','importSources'];const read=()=>p.evaluate(async tables=>{const v=(await indexedDB.databases()).find(d=>d.name==='paia-archive').version;const mod=await import(v===5?'../core/thought-store.js':'../core/smart-filter-store.js');const S=mod.LibraryFoundationStore||mod.SmartFilterStore;const s=new S(chrome.storage.local);await s.filterStatus();const result=await s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(tables.map(async n=>[n,await t.all(n)]))));await s.repository.close();return result;},tables);
  const before=await read(),identity=h.extensionId;await p.close();await cp(next,installed,{recursive:true});const popup=await h.context.newPage();await popup.goto(`chrome-extension://${identity}/ui/popup.html`);await popup.locator('#development-reload').click().catch(()=>{});p=await h.context.newPage();h.archive=p;p.on('pageerror',e=>h.errors.push(e.message));await eventually(async()=>{try{await p.goto(`chrome-extension://${identity}/ui/archive.html`);return await p.evaluate(()=>chrome.runtime.getManifest().version)===targetVersion;}catch{return false;}},'isolated v062 reload');
  await eventually(async()=>{const d=await send('FILTER_DIAGNOSTICS');return d?.checked===6&&d.pending===0&&d.taskState==='idle';});const current=await send('FILTER_DIAGNOSTICS');assert.equal(current.previousReasonState,'available');assert.equal(current.previousUncertainReasonCounts.metadata_unknown,6);assert.equal(current.previousReasonPolicyVersion,1);assert.equal(current.filter,3);assert.equal(current.keep,3);assert.equal(current.reasonCounts.pure_continue,1);assert.equal(current.reasonCounts.pure_start,1);assert.equal(current.reasonCounts.pure_regenerate,1);assert.equal(current.reasonCounts.reference_possible,1);assert.equal(current.reasonCounts.substantive_content,2);assert.equal(current.policyVersion,2);assert.equal(current.classifierVersion,'deterministic-light-2');assert.deepEqual(await read(),before);assert.equal(await p.evaluate(()=>chrome.runtime.id),identity);
  await p.locator('.conversation-document').click();await eventually(async()=>await p.locator('.library-prose:visible').count()===3);await p.locator('[data-view="settings"]').click();await p.locator('#filter-advanced > summary').click();await p.locator('#filter-diagnostics').getByText('reason / pure_continue',{exact:true}).waitFor();await mkdir('work',{recursive:true});await p.screenshot({path:'work/v062-reasons-synthetic.png',fullPage:true});assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  await writeFile('work/v062-upgrade-evidence.json',JSON.stringify({productVersion:targetVersion,scope:'isolated-synthetic',runtimeDigest:await inputDigest({runtimeOnly:true}),sameExtensionId:true,selfReload:true,sourceInputTimeDeletionRevisionImportEquality:true,priorAggregate:prior,currentAggregate:current,defaultReading:true,reasonUI:true,networkRequests:0},null,2)+'\n');
 }finally{await h?.close();await rm(parent,{recursive:true,force:true});}
});
