import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {completeFixture,rows} from './harness/original-complete.mjs';
import {exported,prepared} from './harness/backup-v081.mjs';
import {seedLongTerm} from './fixtures/long-term-v081.mjs';
import {BackupService} from '../core/backup-service.js';
const op=()=>crypto.randomUUID();
test('500 synthetic Inputs / 30 Topics / 360 Entries: reading, merge, revisions, backup and isolated recovery',{timeout:120000},async()=>{
 const f=await completeFixture({texts:[]}),start=performance.now(),fixture=await seedLongTerm(f.s),seedMs=performance.now()-start;assert.equal((await rows(f.s,'records')).length,499);assert.equal((await rows(f.s,'topics')).length,30);assert.equal((await rows(f.s,'thoughts')).length,360);assert.equal((await rows(f.s,'tombstones')).length,1);const gridStart=performance.now(),grid=await f.s.libraryIndexPage({mode:'recent'}),gridMs=performance.now()-gridStart;assert.equal(grid.items.length,30);assert.equal(grid.items[0].id,fixture.topicIds[0]);const topicId=fixture.topicIds[0],readingStart=performance.now(),ascending=await f.s.topicDocumentPage({topicId,sort:'asc'}),descending=await f.s.topicDocumentPage({topicId,sort:'desc'}),readingMs=performance.now()-readingStart;for(const section of fixture.sectionIds[0])assert.deepEqual(descending.items.filter(x=>x.placement.sectionId===section).map(x=>x.entry.id),ascending.items.filter(x=>x.placement.sectionId===section).map(x=>x.entry.id).reverse());assert.equal((await f.s.topicDocumentPage({topicId,sort:'asc',query:'合成备注'})).items.length,1);
 const suggestions=await f.s.topicMergeSuggestions();assert.ok(suggestions.items.length>0);const source=await f.s.topic(fixture.topicIds[2]),target=await f.s.topic(fixture.topicIds[1]);await f.s.startLayout({kind:'topic_merge',topicId:source.id,survivorId:target.id,expectedTopicRevision:source.organizationRevision,expectedSurvivorRevision:target.organizationRevision,operationId:op()});await f.s.drainLibraryMaintenance();assert.equal((await f.s.topicDocumentPage({topicId:target.id,sort:'asc'})).items.length,24);assert.equal((await f.s.libraryIndexPage()).items.length,29);
 const service=new BackupService(f.s,{appVersion:'0.8.1'}),exportStart=performance.now(),items=await exported(service),exportMs=performance.now()-exportStart,serialized=items.map(x=>JSON.stringify(x)).join('\n');assert.doesNotMatch(serialized,/synthetic-test-key|synthetic-only/);const recovery=await completeFixture({texts:[]}),restore=new BackupService(recovery.s,{appVersion:'0.8.1'}),restoreStart=performance.now(),stage=await prepared(restore,items);assert.equal(stage.preview.canRestore,true);await restore.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});await recovery.s.drainLibraryMaintenance();const restoreMs=performance.now()-restoreStart;
 for(const name of ['records','blocks','thoughts','topics','sections','placements','provenance','dependencies','revisions','thoughtSuppressions','inputRemovals','tombstones'])assert.equal((await rows(recovery.s,name)).length,(await rows(f.s,name)).length,name+' counts');
 const before=await rows(f.s,'thoughts'),after=await rows(recovery.s,'thoughts');assert.deepEqual(after.map(e=>[e.id,e.thoughtText,e.title?.trim()?e.title:undefined,e.note,e.revision,e.protections,e.sourceRecordIds]),before.map(e=>[e.id,e.thoughtText,e.title?.trim()?e.title:undefined,e.note,e.revision,e.protections,e.sourceRecordIds]));assert.deepEqual(await rows(recovery.s,'provenance'),await rows(f.s,'provenance'));assert.deepEqual((await rows(recovery.s,'revisions')).map(r=>[r.id,r.before,r.after,r.reason,r.important]),(await rows(f.s,'revisions')).map(r=>[r.id,r.before,r.after,r.reason,r.important]));assert.equal((await recovery.s.libraryProvenance(fixture.entryIds[0])).items[0].availability,'resolvable');assert.equal((await recovery.s.topic(fixture.topicIds[2])).id,fixture.topicIds[1]);assert.equal((await recovery.s.searchLibrary({query:'产品原则'})).items.some(x=>x.entryId===fixture.entryIds[0]),true);
 // Recovered merge history can still restore the pre-merge layout, with no loss.
 const history=(await recovery.s.revisions({kind:'topic',entityId:target.id})).items.find(x=>x.reason==='merge');const live=await recovery.s.topic(target.id);await recovery.s.restoreRevision({id:history.id,side:'before',expectedRevision:live.revision,operationId:op()});assert.equal((await recovery.s.libraryIndexPage()).items.length,30);assert.equal((await rows(recovery.s,'thoughts')).length,360);assert.equal(recovery.requests.length,0);
 const report={syntheticOnly:true,capturedInputs:500,remainingSources:499,topics:30,entries:360,removedInput:1,tombstones:1,userEditedEntries:20,aiFixtureRequests:fixture.aiRequests,seedMs,gridMs,readingMs,exportMs,restoreMs,backupBytes:new TextEncoder().encode(serialized).length,backupItems:items.length-2,importantRevisions:(await rows(f.s,'revisions')).filter(x=>x.important).length,checks:['grid','section-time-order','topic-search','merge','backup','restore','source-fences','user-edits','provenance','important-revisions','merge-undo-after-restore']};await mkdir(new URL('../work/v081-long-term/',import.meta.url),{recursive:true});await writeFile(new URL('../work/v081-long-term/acceptance.json',import.meta.url),JSON.stringify(report,null,2));
});
