import {assertRetiredContext} from './harness/retired-context.mjs';
import {admitPreGatePurgeFixture} from './harness/pre-gate-purge-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {setup,local,derived,inputEdit} from './harness/thought-m1.mjs';import {OrganizerStore} from '../core/organizer/store.js';import {MemoryService} from '../core/memory/service.js';import {BackupService} from './harness/historical-backup.mjs';import {exported,prepared} from './harness/backup-v081.mjs';import {IntegrityChecker} from '../core/integrity-checker.js';import {key,configDefault,profileDefault} from '../core/memory/model.js';
async function fixture(){const {s,storage,indexedDB}=await setup(OrganizerStore);await s.setFilterMode('off');const block=(await s.snapshot()).library.blocks[0],e=await derived(s,[block.id],{body:'PAIA 来源忠实的合成整理。'}),topic=await s.createTopic({name:'PAIA',operationId:crypto.randomUUID()});await s.placeEntry({operationId:crypto.randomUUID(),topicId:topic.id,entryId:e.id,expectedEntryRevision:e.revision,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision});const session=local(),m=new MemoryService(s,{session});/* Seed synthetic pre-retirement compatibility metadata. */await m.ready();await s.repository.transaction(true,async t=>{await t.put('meta',profileDefault());await t.put('meta',{id:key('topic','default',topic.id),kind:'topic',version:1,profileId:'default',topicId:topic.id,decision:'allowed',layoutGeneration:1});});return {s,m,session,block,e,topic,storage,indexedDB};}
test('Current retirement: Memory privacy gate precedes Thought body reads; Source/Input bodies are never retrieved',async()=>{await assertRetiredContext({owner:'memory',method:'build',variant:'denied'});});
test('Current retirement: CURRENT B-02 refusal + historical fixture: Memory Source tombstone, missing Source row, hidden Source and Input removal cannot leak even edited Thought',async()=>{for(const variant of ['missing','hidden','removed'])await assertRetiredContext({owner:'memory',method:'share',variant});const f=await assertRetiredContext({owner:'memory',method:'build'});await admitPreGatePurgeFixture(f.s,f.input.sourceRecordId);await assert.rejects(f.memory.build({query:'PRIVATE'}),{code:'FEATURE_UNAVAILABLE'});});
test('Current retirement: Memory publication rechecks data after activity commit rather than blessing an outdated preview',async()=>{await assertRetiredContext({owner:'memory',method:'build',variant:'edited'});});
test('Memory migration adds only the config metadata row, repeated initialization is idempotent and transaction crash rolls back',async()=>{const {s}=await setup(OrganizerStore);await s.finishFoundation();const names=['records','blocks','thoughts','topics','revisions'],before=await s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(names.map(async n=>[n,await t.all(n)]))));const original=s.repository.transaction.bind(s.repository);let crash=true;s.repository.transaction=(write,fn,stores)=>original(write,t=>{const put=t.put.bind(t);t.put=(name,row)=>{if(crash&&row.id==='memory:config')throw Error('synthetic initialization interruption');return put(name,row);};return fn(t);},stores);const m=new MemoryService(s);await assert.rejects(m.status(),{code:'STORAGE_FAILED'});crash=false;assert.equal(await original(false,t=>t.get('meta','memory:config')),undefined);await m.status();await new MemoryService(s).status();assert.equal(s.repository.db.version,5);assert.deepEqual(await s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(names.map(async n=>[n,await t.all(n)])))),before);const rows=(await original(false,t=>t.all('meta'))).filter(r=>r.id.startsWith('memory:'));assert.deepEqual(rows.map(r=>r.id).sort(),['memory:config']);});
test('Memory Backup v1 round trip includes policy/profile/exclusion/instruction but no session, query, context or key; conflict never overwrites',async()=>{const {s,m,topic,e}=await fixture();const custom={...profileDefault(),id:key('profile','legacy'),profileId:'legacy',name:'产品开发',budget:'short',instruction:'回答简洁。'};await s.repository.transaction(true,t=>t.put('meta',custom));await assert.rejects(m.build({query:'PAIA SECRET_QUERY_ABC'}),{code:'FEATURE_UNAVAILABLE'});await m.exclude({entryId:e.id,excluded:true});const b=new BackupService(s,{appVersion:'0.10.0'}),items=await exported(b);const metadata=items.filter(i=>i.section==='organizationState'&&i.value.id.startsWith('memory:'));assert.ok(metadata.some(i=>i.value.data.kind==='entry'));assert.ok(metadata.some(i=>i.value.data.instruction==='回答简洁。'));assert.doesNotMatch(JSON.stringify(metadata),/SECRET_QUERY_ABC|PAIA Context|来源忠实|grants|apiKey/);await m.authorize({topicIds:[topic.id],decision:'denied'});assert.equal((await prepared(b,items)).preview.reason,'BACKUP_TARGET_NOT_EMPTY');assert.equal((await m.status()).allowed,0);
 const {IDBFactory}=await import('./vendor/fake-indexeddb/build/esm/index.js');const empty=new OrganizerStore(local(),{indexedDB:new IDBFactory()});await empty.consent(true);await empty.finishFoundation();const restore=new BackupService(empty,{appVersion:'0.10.0'}),stage=await prepared(restore,items);assert.equal(stage.preview.canRestore,true);await restore.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});const restored=new MemoryService(empty);assert.equal((await restored.status()).allowed,1);assert.equal((await restored.status()).excluded,1);assert.equal((await restored.status()).profiles.find(x=>x.profileId===custom.profileId).instruction,'回答简洁。');await assert.rejects(restored.build({query:'PAIA'}),{code:'FEATURE_UNAVAILABLE'});
});
test('Old v092 Backup remains valid and a new Memory-only local edit blocks restore',async()=>{const {s}=await setup(OrganizerStore);await s.finishFoundation();const items=await exported(new BackupService(s,{appVersion:'0.9.2'}));assert.ok(!items.some(i=>i.value?.id?.startsWith('memory:')));const {IDBFactory}=await import('./vendor/fake-indexeddb/build/esm/index.js');const target=new OrganizerStore(local(),{indexedDB:new IDBFactory()});await target.consent(true);const m=new MemoryService(target);await m.settings({localOnly:true});const stage=await prepared(new BackupService(target,{appVersion:'0.10.0'}),items);assert.equal(stage.preview.reason,'BACKUP_TARGET_NOT_EMPTY');assert.equal((await m.status()).config.localOnly,true);});
test('Memory integrity detects dangling Topic, Entry, Profile and malformed rules without repair',async()=>{const {s,m}=await fixture();await m.status();await s.repository.transaction(true,async t=>{await t.put('meta',{id:key('topic','missing-profile','missing-topic'),kind:'topic',version:1,profileId:'missing-profile',topicId:'missing-topic',decision:'allowed',layoutGeneration:1});await t.put('meta',{id:key('entry','missing-entry'),kind:'entry',version:1,entryId:'missing-entry',excluded:true});});const check=new IntegrityChecker(s),before=s.repository.metrics.writes;let r=await check.begin();while(r.state==='loading')r=await check.page(r);for(const k of ['dangling_memory_authorization','missing_memory_topic','excluded_missing_entry','invalid_memory_profile_ref'])assert.ok(r.counts[k]>0);assert.equal(s.repository.metrics.writes,before);assert.doesNotMatch(JSON.stringify(r),/missing-entry|missing-topic/);});

test('Current retirement: Memory uses only current evidence-bound AI synthesis, always keeps Thought evidence first and never sends a request',async()=>{await assertRetiredContext({owner:'memory',method:'candidates',variant:'edited'});});

test('Memory metadata rejects prototype names as budgets and row kinds before persistence or backup restore',async()=>{const {validateMemoryRow}=await import('../core/memory/model.js');const {m}=await fixture();for(const budget of ['__proto__','constructor','toString',['short'],null]){assert.equal(validateMemoryRow({...configDefault(),budget}),false);assert.equal(validateMemoryRow({...profileDefault(),budget}),false);await assert.rejects(m.settings({budget}),{code:'FEATURE_UNAVAILABLE'});await assert.rejects(m.build({budget}),{code:'FEATURE_UNAVAILABLE'});}assert.equal(validateMemoryRow({version:1,kind:'__proto__',id:'memory:config'}),false);assert.equal((await m.status()).config.budget,'standard');});

test('CURRENT B-02 refusal + historical fixture: Memory activity and authorization labels cannot resurrect an unprotected purged-source Topic title',async()=>{const {s,m,topic,block}=await fixture();await s.repository.transaction(true,async t=>{const row=await t.get('topics',topic.id);await t.put('topics',{...row,name:'PURGED_TOPIC_TITLE_SECRET',sourceRecordIds:[block.sourceRecordId],protections:{...row.protections,name:{locked:false}}});});await assert.rejects(m.build({query:''}),{code:'FEATURE_UNAVAILABLE'});await admitPreGatePurgeFixture(s,block.sourceRecordId);const status=await m.status();assert.doesNotMatch(JSON.stringify(status),/PURGED_TOPIC_TITLE_SECRET/);await assert.rejects(m.build({query:''}),{code:'FEATURE_UNAVAILABLE'});});