import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {FakeChatGPT,conversation,eventually} from './harness/fake-chatgpt.mjs';

const root=new URL('../',import.meta.url).pathname;
test('isolated Chrome runs the manual Original bootstrap through DeepSeek HTTP fixture into Thought Library',{timeout:120000},async()=>{
 const dir=await mkdtemp(join(tmpdir(),'paia-original-rescue-'));let h;
 try{
  await cp(root,dir,{recursive:true,filter:path=>!/(\/\.git(?:\/|$)|\/work(?:\/|$)|\/outputs(?:\/|$))/.test(path)});const workerPath=join(dir,'background/service-worker.js');await writeFile(workerPath,(await readFile(workerPath,'utf8'))+`\nconst originalRescueRequests=[];deepSeekProvider.fetchImpl=async(_url,init)=>{const body=JSON.parse(init.body),request=JSON.parse(body.messages[1].content);originalRescueRequests.push(body);return {status:200,ok:true,headers:{get:()=>null},text:async()=>JSON.stringify({choices:[{message:{content:JSON.stringify({items:request.inputs.map(input=>({inputRef:input.ref,topic:{proposedName:'浏览器合成主题'},section:{proposedName:'思考过程'},type:'idea',relatedGroupingCandidate:null,spans:[],uncertain:false}))})}}]})};};globalThis.originalRescueSynthetic={store,requests:originalRescueRequests};\n`);
  h=await FakeChatGPT.start({extensionPath:dir});const page=h.archive;
  await page.locator('#consent-check').check();await page.locator('#enable-consent').click();await h.open(conversation('original-rescue-visible'));await eventually(async()=>(await h.state()).records.length===3);
  await page.locator('[data-view=settings]').click();await page.locator('#deepseek-api-key').fill('synthetic-browser-key');await page.locator('#deepseek-save').click();await eventually(async()=>await page.locator('#deepseek-status').textContent().then(x=>x.includes('已配置')));await page.locator('#organizer-advanced > summary').click();await eventually(async()=>await page.locator('#original-organizer-status').textContent().then(x=>x.includes('3 条待整理')));
  const worker=()=>h.context.serviceWorkers().find(x=>x.url().includes(h.extensionId));await worker().evaluate(async()=>{const s=globalThis.originalRescueSynthetic.store,now=Date.now();await s.foundationWrite(t=>t.put('meta',{id:'organizer-budget',startedAt:now-999999,dailyAt:now,sessionId:'legacy-lifetime-session',session:{inputs:256,bytes:2097152,requests:128},daily:{inputs:0,bytes:0,requests:0}}));});
  if(!await page.locator('#original-organizer-status + button').isVisible())await page.locator('#organizer-advanced > summary').click();await page.locator('#original-organizer-status + button').click();await eventually(async()=>await worker().evaluate(()=>globalThis.originalRescueSynthetic.requests.length===1),'one click must send exactly one batch request');await eventually(async()=>await page.locator('#original-organizer-trace').textContent().then(x=>x.includes('阶段：completed')),'UI must leave running after commit');const requests=await worker().evaluate(()=>structuredClone(globalThis.originalRescueSynthetic.requests));assert.equal(requests.length,1);const sent=requests[0];assert.equal(sent.model,'deepseek-v4-flash');assert.deepEqual(sent.thinking,{type:'disabled'});assert.deepEqual(sent.response_format,{type:'json_object'});assert.equal(sent.stream,false);
  const safe=await worker().evaluate(async()=>{const s=globalThis.originalRescueSynthetic.store,status=await s.originalOrganizerStatus(),entries=await s.entryPage(),topics=await s.libraryIndexPage(),receipts=await s.repository.transaction(false,t=>t.all('operationReceipts')),budget=await s.repository.transaction(false,t=>t.get('meta','organizer-budget'),['meta']);return {processed:status.bootstrap.processed,entryBodies:entries.items.map(x=>x.body),topicCount:topics.items.length,batchReceipts:receipts.filter(x=>x.namespace==='original-simple').length,inputReceipts:receipts.filter(x=>x.namespace==='original-simple-input').length,diagnostics:status.diagnostics,budget:{sessionId:budget.sessionId,session:budget.session,daily:budget.daily,runtimeRepairVersion:budget.runtimeRepairVersion}};});const evidence=JSON.stringify(safe);assert.equal(safe.processed,3,evidence);assert.equal(safe.entryBodies.length,2,evidence);assert.ok(safe.entryBodies.every(x=>x.includes('虚构')),evidence);assert.equal(safe.topicCount,1,evidence);assert.equal(safe.batchReceipts,1,evidence);assert.equal(safe.inputReceipts,3,evidence);assert.equal(safe.diagnostics.stage,'completed',evidence);assert.equal(safe.diagnostics.httpStatus,200,evidence);assert.ok(safe.diagnostics.responseBytes>0,evidence);assert.equal(safe.diagnostics.committedItemCount,3,evidence);assert.notEqual(safe.budget.sessionId,'legacy-lifetime-session',evidence);assert.equal(safe.budget.runtimeRepairVersion,1,evidence);assert.equal(safe.budget.session.inputs,3,evidence);assert.equal(safe.budget.session.requests,1,evidence);assert.equal(safe.budget.daily.inputs,3,evidence);
  await h.restartWorker();const after=await h.state();assert.equal(after.records.length,3);await page.reload();await page.locator('[data-view=thoughts]').click();await eventually(async()=>await page.locator('.topic-index-row').count()===1);assert.deepEqual(h.errors,[]);
 }finally{await h?.close();await rm(dir,{recursive:true,force:true});}
});
