import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {DeepSeekOrganizerProvider,DeepSeekSessionCredentials} from '../core/organizer/deepseek.js';
import {SimpleOriginalOrganizerRunner} from '../core/organizer/original-simple.js';

const response=(body,status=200)=>({status,ok:status>=200&&status<300,headers:{get:()=>null},text:async()=>JSON.stringify(body)});
function success(init,mutate=x=>x){const request=JSON.parse(JSON.parse(init.body).messages[1].content),items=request.inputs.map(input=>mutate({inputRef:input.ref,topic:{proposedName:'Cost-safe topic'},section:{proposedName:'Timeline'},type:'idea',relatedGroupingCandidate:null,spans:[],uncertain:false},input));return response({choices:[{message:{content:JSON.stringify({items})}}]});}
async function fixture(fetchImpl,options={}){const f=await setup(OrganizerStore),data={},session={get:async key=>({[key]:data[key]}),set:async row=>Object.assign(data,structuredClone(row)),remove:async key=>{delete data[key];}},credentials=new DeepSeekSessionCredentials(session);await credentials.configure({apiKey:'synthetic-key'});const provider=new DeepSeekOrganizerProvider({limits:f.s.organizerBudget.limits,timeoutMs:options.timeoutMs||100,fetchImpl}),runner=new SimpleOriginalOrganizerRunner(f.s,{provider,credentials});return {...f,data,credentials,provider,runner};}
async function ledger(store){return store.repository.transaction(false,async t=>(await t.all('meta')).filter(x=>String(x.id).startsWith('originalProviderRequest:')),['meta']);}

test('one explicit action sends exactly one DeepSeek request and stores only a safe committed ledger',async()=>{let calls=0;const f=await fixture(async(_url,init)=>{calls++;return success(init);}),result=await f.runner.wake({userActionId:'one-click'}),rows=await ledger(f.s);assert.equal(calls,1);assert.equal(result.providerRequestCount,1);assert.equal(rows.length,1);assert.equal(rows[0].state,'committed');assert.equal(rows[0].inputCount,1);assert.equal(JSON.stringify(rows).includes('Synthetic explicit working input'),false);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,1);});

test('provider, transport, output, and validation failures never retry or advance',async()=>{const cases=[['timeout',async()=>await new Promise(()=>{}),'PROVIDER_TIMEOUT',5],['400',async()=>response({},400),'PROVIDER_BAD_REQUEST'],['401',async()=>response({},401),'INVALID_CREDENTIAL'],['429',async()=>response({},429),'RATE_LIMITED'],['500',async()=>response({},500),'PROVIDER_UNAVAILABLE'],['network',async()=>{throw new Error('synthetic network failure');},'NETWORK_ERROR'],['malformed',async()=>response({choices:[{message:{content:'not json'}}]}),'INVALID_JSON']];for(const [name,fetchImpl,code,timeoutMs] of cases){let calls=0;const f=await fixture(async(...args)=>{calls++;return fetchImpl(...args);},{timeoutMs}),result=await f.runner.wake({userActionId:'failure-'+name});assert.equal(result.error,code,name);assert.equal(calls,1,name);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0,name);assert.equal((await f.s.entryPage()).items.length,0,name);assert.equal((await ledger(f.s))[0].state,'failed',name);}});

test('commit failure does not advance and explicit Retry is the only action that makes fetch count two',async()=>{let calls=0;const f=await fixture(async(_url,init)=>{calls++;return success(init);}),commit=f.s.libraryCommit.commitOriginalBatch.bind(f.s.libraryCommit);f.s.libraryCommit.commitOriginalBatch=async()=>{throw {code:'STORAGE_FAILED'};};const first=await f.runner.wake({userActionId:'commit-fail'});assert.equal(first.error,'LIBRARY_COMMIT_FAILED');assert.equal(calls,1);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0);await f.runner.reconcileInterrupted();assert.equal(calls,1);f.s.libraryCommit.commitOriginalBatch=commit;const second=await f.runner.wake({userActionId:'explicit-retry'});assert.equal(calls,2);assert.ok(second.result);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,1);});

test('one userActionId can never cross the sent boundary twice',async()=>{let calls=0;const f=await fixture(async()=>{calls++;return response({},429);});const first=await f.runner.wake({userActionId:'same-action'}),second=await f.runner.wake({userActionId:'same-action'});assert.equal(first.error,'RATE_LIMITED');assert.equal(second.error,'SINGLE_FLIGHT_ACQUIRE_FAILED');assert.equal(second.providerRequestCount,0);assert.equal(calls,1);});

test('single-flight rejects a second action and Stop aborts without another request',async()=>{let calls=0,aborted=false;const f=await fixture(async(_url,{signal})=>{calls++;return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(Object.assign(new Error('aborted'),{name:'AbortError'}));},{once:true}));},{timeoutMs:10000}),first=f.runner.wake({userActionId:'flight-1'});while(calls!==1)await new Promise(resolve=>setTimeout(resolve,0));const duplicate=await f.runner.wake({userActionId:'flight-2'});assert.equal(duplicate.error,'REQUEST_ALREADY_IN_FLIGHT');assert.equal(calls,1);await f.runner.stop();const stopped=await first;assert.equal(stopped.error,'CANCELLED');assert.equal(aborted,true);assert.equal(calls,1);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0);});

test('clearing the session credential aborts active work and cannot schedule another request',async()=>{let calls=0;const f=await fixture(async(_url,{signal})=>{calls++;return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true}));},{timeoutMs:10000}),active=f.runner.wake({userActionId:'clear-active'});while(calls!==1)await new Promise(resolve=>setTimeout(resolve,0));await f.runner.stop();await f.credentials.disable();assert.equal((await active).error,'CANCELLED');assert.equal((await f.credentials.status()).hasCredential,false);assert.equal(calls,1);await new Promise(resolve=>setTimeout(resolve,10));assert.equal(calls,1);});

test('worker restart after sent becomes outcome_unknown and the late worker cannot commit',async()=>{let calls=0,finish;const f=await fixture(async(_url,init)=>{calls++;return new Promise(resolve=>{finish=()=>resolve(success(init));});},{timeoutMs:10000}),old=f.runner.wake({userActionId:'interrupted'});while(calls!==1)await new Promise(resolve=>setTimeout(resolve,0));const restarted=new SimpleOriginalOrganizerRunner(f.s,{provider:f.provider,credentials:f.credentials}),recovery=await restarted.reconcileInterrupted();assert.equal(recovery.error,'OUTCOME_UNKNOWN');assert.equal(calls,1);finish();const result=await old;assert.equal(result.error,'OUTCOME_UNKNOWN');assert.equal(calls,1);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0);assert.equal((await f.s.entryPage()).items.length,0);assert.equal((await ledger(f.s))[0].state,'outcome_unknown');});

test('production runtime has no smoke, auto-dispatch, retry timer, or recursive Original continuation',async()=>{const [worker,provider,store,ui,html]=await Promise.all([readFile(new URL('../background/service-worker.js',import.meta.url),'utf8'),readFile(new URL('../core/organizer/deepseek.js',import.meta.url),'utf8'),readFile(new URL('../core/organizer/store.js',import.meta.url),'utf8'),readFile(new URL('../ui/archive.js',import.meta.url),'utf8'),readFile(new URL('../ui/archive.html',import.meta.url),'utf8')]);assert.doesNotMatch(provider,/Synthetic organizer connectivity check|runInternalSmoke|internalSmokeRequest/);assert.doesNotMatch(worker,/scheduleOriginalIncremental/);assert.equal((worker.match(/originalOrganizer\.wake\(/g)||[]).length,1);assert.match(store,/async autoUpdateOriginalView\(\)\{return null;\}/);assert.match(worker,/CLEAR_DEEPSEEK': await boundedOrganizer\.stop\(\);await aiOrganizer\.stop\(\);await originalOrganizer\.stop/);assert.match(ui,/STOP_ORIGINAL_LIBRARY_VIEW/);assert.match(html,/重试将再次调用 DeepSeek API/);});
