import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {ArchiveRepository} from '../core/idb-repository.js';
import {DeepSeekOrganizerProvider,DeepSeekSessionCredentials} from '../core/organizer/deepseek.js';
import {SimpleOriginalOrganizerRunner} from '../core/organizer/original-simple.js';

globalThis.IDBKeyRange=IDBKeyRange;
const response=body=>({status:200,ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(body)});
function success(init){const request=JSON.parse(JSON.parse(init.body).messages[1].content);return response({choices:[{message:{content:JSON.stringify({items:request.inputs.map(input=>({inputRef:input.ref,topic:{proposedName:'Prepare topic'},section:{proposedName:'Timeline'},type:'idea',relatedGroupingCandidate:null,spans:[],uncertain:false}))})}}]});}
async function fixture(){const f=await setup(OrganizerStore),sessionData={},session={get:async key=>({[key]:sessionData[key]}),set:async row=>Object.assign(sessionData,structuredClone(row)),remove:async key=>{delete sessionData[key];}},credentials=new DeepSeekSessionCredentials(session);await credentials.configure({apiKey:'synthetic-key'});let calls=0;const provider=new DeepSeekOrganizerProvider({limits:f.s.organizerBudget.limits,fetchImpl:async(_url,init)=>{calls++;return success(init);}}),runner=new SimpleOriginalOrganizerRunner(f.s,{provider,credentials});return {...f,credentials,provider,runner,get calls(){return calls;}};}
function failOnePut(store,predicate,dbCategory){const original=store.foundationWrite.bind(store);let armed=true;store.foundationWrite=fn=>original(async t=>{const put=t.put.bind(t);t.put=async(name,value,key)=>{if(armed&&predicate(name,value)){armed=false;throw Object.assign(new Error(dbCategory),{code:'STORAGE_FAILED',dbCategory});}return put(name,value,key);};return fn(t);});}

test('durable ledger and budget reservation succeed before exactly one fetch and full commit',async()=>{const f=await fixture(),result=await f.runner.wake({userActionId:'prepare-success'}),status=await f.s.originalOrganizerStatus();assert.ok(result.result);assert.equal(f.calls,1);assert.equal(status.diagnostics.providerRequestCount,1);assert.equal(status.diagnostics.localWriteStep,'completed');assert.equal(status.diagnostics.committedItemCount,1);assert.equal((await f.s.entryPage()).items.length,1);});

test('ledger write failure records its exact local step and fetch stays zero',async()=>{const f=await fixture();failOnePut(f.s,(name,value)=>name==='meta'&&String(value?.id).startsWith('originalProviderRequest:'),'constraint');const result=await f.runner.wake({userActionId:'ledger-fail'}),status=await f.s.originalOrganizerStatus();assert.equal(result.error,'PREPARE_LEDGER_WRITE_FAILED');assert.equal(result.localWriteStep,'request_ledger');assert.equal(result.dbErrorCategory,'constraint');assert.equal(f.calls,0);assert.equal(status.diagnostics.providerRequestCount,0);assert.equal((await f.s.entryPage()).items.length,0);});

test('transaction inactive and invalid index value failures remain pre-fetch batch-state errors',async()=>{for(const [name,predicate,category,step] of [['inactive',(store,value)=>store==='meta'&&value?.id==='organizer-budget','transaction_inactive','budget_state'],['invalid-index',(store)=>store==='organizerUsage','invalid_key_or_index_value','usage_reservation']]){const f=await fixture();failOnePut(f.s,predicate,category);const result=await f.runner.wake({userActionId:name}),status=await f.s.originalOrganizerStatus();assert.equal(result.error,'BATCH_STATE_WRITE_FAILED',name);assert.equal(result.localWriteStep,step,name);assert.equal(result.dbErrorCategory,category,name);assert.equal(f.calls,0,name);assert.equal(status.diagnostics.providerRequestCount,0,name);}});

test('duplicate single-flight marker fails explicitly and cannot issue a second request',async()=>{const f=await fixture();let calls=0;f.provider.fetchImpl=async()=>{calls++;return {status:429,ok:false,headers:{get:()=>null},text:async()=>''};};await f.runner.wake({userActionId:'same-action'});const result=await f.runner.wake({userActionId:'same-action'});assert.equal(result.error,'SINGLE_FLIGHT_ACQUIRE_FAILED');assert.equal(result.localWriteStep,'single_flight_check');assert.equal(calls,1);});

test('legacy lifetime session budget rotates once for a new Chrome session without weakening daily budget',async()=>{const f=await fixture(),now=Date.now();await f.s.foundationWrite(t=>t.put('meta',{id:'organizer-budget',startedAt:now-999999,dailyAt:now,sessionId:'old-session',session:{inputs:256,bytes:2097152,requests:128},daily:{inputs:0,bytes:0,requests:0}}));f.s.organizerLedger.setSessionId('new-session');const result=await f.runner.wake({userActionId:'session-rotation'}),row=await f.s.repository.transaction(false,t=>t.get('meta','organizer-budget'),['meta']);assert.ok(result.result);assert.equal(f.calls,1);assert.equal(row.sessionId,'new-session');assert.equal(row.runtimeRepairVersion,1);assert.deepEqual(row.session,{inputs:1,bytes:row.session.bytes,requests:1});assert.ok(row.session.bytes>0);assert.equal(row.daily.inputs,1);});

test('a current-session budget denial keeps the ledger, reports budget reservation, and fetch stays zero',async()=>{const f=await fixture(),now=Date.now();f.s.organizerLedger.setSessionId('same-session');await f.s.foundationWrite(t=>t.put('meta',{id:'organizer-budget',startedAt:now,dailyAt:now,sessionId:'same-session',session:{inputs:256,bytes:0,requests:0},daily:{inputs:0,bytes:0,requests:0}}));const result=await f.runner.wake({userActionId:'budget-denied'}),status=await f.s.originalOrganizerStatus();assert.equal(result.error,'BUDGET_EXCEEDED');assert.equal(result.dbErrorCategory,'policy_denied');assert.equal(f.calls,0);assert.equal(status.diagnostics.providerRequestCount,0);assert.equal(status.diagnostics.localWriteStep,'budget_state');});

test('service-worker restart after durable local prepare does not fetch and becomes an explicit interruption',async()=>{const f=await fixture(),underlying=f.provider.execute.bind(f.provider),gate=new Promise(()=>{});f.provider.execute=async()=>gate;const active=f.runner.wake({userActionId:'restart-after-prepare'});while(!(await f.s.originalOrganizerStatus()).diagnostics.providerRequestState)await new Promise(resolve=>setTimeout(resolve,0));const restarted=new SimpleOriginalOrganizerRunner(f.s,{provider:{execute:underlying},credentials:f.credentials}),recovery=await restarted.reconcileInterrupted();assert.equal(recovery.error,'WORKER_INTERRUPTED');assert.equal(f.calls,0);await f.runner.stop();void active;});

test('v4 database missing Organizer runtime store and indexes upgrades additively',async()=>{const indexedDB=new IDBFactory(),local={get:async()=>({}),set:async()=>{}},repository=new ArchiveRepository(local,{indexedDB,name:'organizer-runtime-upgrade',ia:true,smartFilter:true,thoughtLibrary:true});const old=await new Promise((resolve,reject)=>{const request=indexedDB.open('organizer-runtime-upgrade',4);request.onupgradeneeded=()=>{for(const name of repository.stores)if(name!=='organizerUsage')request.result.createObjectStore(name,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});old.close();await repository.open();assert.equal(repository.db.version,5);assert.ok(repository.db.objectStoreNames.contains('organizerUsage'));const store=repository.db.transaction('organizerUsage').objectStore('organizerUsage');for(const index of ['byJob','byWindow','byState','byCreated'])assert.ok(store.indexNames.contains(index));});
