import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {setup} from './harness/thought-m1.mjs';
import {OrganizerStore} from '../core/organizer/store.js';
import {DeepSeekOrganizerProvider,DeepSeekSessionCredentials} from '../core/organizer/deepseek.js';
import {SimpleOriginalOrganizerRunner} from '../core/organizer/original-simple.js';

const envelope=(content,status=200,textImpl=null)=>({status,ok:status>=200&&status<300,headers:{get:()=>null},text:textImpl||(async()=>JSON.stringify({choices:[{message:{content:typeof content==='string'?content:JSON.stringify(content)}}]}))});
function valid(init,mutate=x=>x){const dto=JSON.parse(JSON.parse(init.body).messages[1].content);return envelope({items:dto.inputs.map((input,index)=>mutate({inputRef:input.ref,topic:{proposedName:'Trace topic'},section:{proposedName:'Timeline'},type:'idea',relatedGroupingCandidate:null,spans:[],uncertain:false},input,index))});}
async function fixture(fetchImpl,{timeoutMs=80}={}){const f=await setup(OrganizerStore),sessionData={},session={get:async key=>({[key]:sessionData[key]}),set:async row=>Object.assign(sessionData,structuredClone(row)),remove:async key=>{delete sessionData[key];}},credentials=new DeepSeekSessionCredentials(session);await credentials.configure({apiKey:'synthetic-key'});const provider=new DeepSeekOrganizerProvider({limits:f.s.organizerBudget.limits,timeoutMs,fetchImpl}),runner=new SimpleOriginalOrganizerRunner(f.s,{provider,credentials});return {...f,provider,runner};}
async function trace(store){return store.repository.transaction(false,async t=>{const p=await t.get('meta','originalProviderRequestCurrent');return t.get('meta','originalProviderRequest:'+p.requestId);},['meta']);}

test('real DeepSeek request uses one fixed JSON request and records every successful phase',async()=>{let calls=0,seen;const f=await fixture(async(url,init)=>{calls++;seen={url,init};return valid(init);}),result=await f.runner.wake({userActionId:'trace-success'}),row=await trace(f.s);assert.ok(result.result);assert.equal(calls,1);assert.equal(seen.url,'https://api.deepseek.com/chat/completions');const body=JSON.parse(seen.init.body);assert.equal(body.model,'deepseek-v4-flash');assert.deepEqual(body.thinking,{type:'disabled'});assert.deepEqual(body.response_format,{type:'json_object'});assert.equal(body.stream,false);assert.equal(row.state,'committed');assert.equal(row.phase,'completed');for(const phase of ['preparing','fetch_started','headers_received','body_reading','body_received','json_parsing','schema_validating','span_validating','committing','completed'])assert.ok(row.phaseTimestamps[phase],phase);assert.equal(row.httpStatus,200);assert.ok(row.responseBytes>0);assert.equal(row.committedItemCount,1);assert.equal(JSON.stringify(row).includes('Synthetic explicit working input'),false);});

test('headers received followed by a body that never ends hits the same absolute deadline',async()=>{let calls=0;const f=await fixture(async()=>{calls++;return envelope({},200,async()=>new Promise(()=>{}));},{timeoutMs:10}),result=await f.runner.wake({userActionId:'body-hang'}),row=await trace(f.s);assert.equal(calls,1);assert.equal(result.error,'PROVIDER_TIMEOUT');assert.equal(row.phase,'body_reading');assert.equal(row.httpStatus,200);assert.equal(row.errorCode,'PROVIDER_TIMEOUT');assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0);});

test('body read, JSON parse, and schema failures preserve their exact phase and never retry',async()=>{const cases=[['body',async()=>envelope({},200,async()=>{throw new Error('synthetic body failure');}),'RESPONSE_BODY_READ_FAILED','body_reading'],['outer-json',async()=>({status:200,ok:true,headers:{get:()=>null},text:async()=>'{'}),'INVALID_JSON','json_parsing'],['inner-json',async()=>envelope('{'),'INVALID_JSON','json_parsing'],['schema',async()=>envelope({wrong:[]}),'INVALID_SCHEMA','schema_validating']];for(const [name,fetchImpl,code,phase] of cases){let calls=0;const f=await fixture(async(...args)=>{calls++;return fetchImpl(...args);}),result=await f.runner.wake({userActionId:'phase-'+name}),row=await trace(f.s);assert.equal(calls,1,name);assert.equal(result.error,code,name);assert.equal(row.phase,phase,name);assert.equal(row.errorCode,code,name);assert.equal(row.committedItemCount,0,name);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0,name);}});

test('fetch and HTTP failures stop at the exact phase with one request',async()=>{const cases=[['fetch',async()=>{throw new Error('offline');},'NETWORK_ERROR','fetch_started',null],['auth',async()=>envelope({},401),'INVALID_CREDENTIAL','headers_received',401],['rate',async()=>envelope({},429),'RATE_LIMITED','headers_received',429]];for(const [name,fetchImpl,code,phase,http] of cases){let calls=0;const f=await fixture(async(...args)=>{calls++;return fetchImpl(...args);}),result=await f.runner.wake({userActionId:'transport-'+name}),row=await trace(f.s);assert.equal(calls,1,name);assert.equal(result.error,code,name);assert.equal(row.phase,phase,name);assert.equal(row.httpStatus,http,name);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0,name);}});

test('one invalid span is manual while valid items commit in the same one-request batch',async()=>{const f=await fixture(async(_url,init)=>valid(init,(row,input,index)=>index===4?{...row,spans:[{start:0,end:input.text.length+1}]}:row));const epoch=(await f.s.status()).epoch;await f.s.capture({epoch,adapterVersion:'0.3.0',chat:{id:'m1-synthetic-chat',url:'https://chatgpt.com/c/m1-synthetic-chat',title:'Synthetic chat'},messages:Array.from({length:4},(_,i)=>({sourceMessageId:'trace-'+i,pageOrder:i+2,originalText:'Trace input '+i}))});const result=await f.runner.wake({userActionId:'partial-span'}),row=await trace(f.s);assert.equal(result.providerRequestCount,1);assert.equal(result.result.created.length,4);assert.equal(result.result.manualInputCount,1);assert.equal(row.phase,'completed');assert.equal(row.committedItemCount,4);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,5);});

test('commit failure stops at committing and leaves the cursor unchanged',async()=>{let calls=0;const f=await fixture(async(_url,init)=>{calls++;return valid(init);});f.s.libraryCommit.commitOriginalBatch=async()=>{throw {code:'STORAGE_FAILED'};};const result=await f.runner.wake({userActionId:'commit-phase'}),row=await trace(f.s);assert.equal(calls,1);assert.equal(result.error,'LIBRARY_COMMIT_FAILED');assert.equal(row.phase,'committing');assert.equal(row.errorCode,'LIBRARY_COMMIT_FAILED');assert.equal(row.committedItemCount,0);assert.equal((await f.s.originalOrganizerStatus()).bootstrap.processed,0);});

test('message interruption and UI watchdog are concrete and Original has no generic unknown label',async()=>{const previous=globalThis.chrome;globalThis.chrome={runtime:{sendMessage:async()=>{throw new Error('The message port closed before a response was received.');}}};try{const {request}=await import('../ui/common.js?trace-rescue');await assert.rejects(request('UPDATE_ORIGINAL_LIBRARY_VIEW'),error=>error.code==='MESSAGE_CHANNEL_INTERRUPTED');}finally{globalThis.chrome=previous;}const [ui,common,worker]=await Promise.all([readFile(new URL('../ui/archive.js',import.meta.url),'utf8'),readFile(new URL('../ui/common.js',import.meta.url),'utf8'),readFile(new URL('../background/service-worker.js',import.meta.url),'utf8')]);assert.match(ui,/MESSAGE_RESPONSE_TIMEOUT/);assert.match(ui,/35000/);assert.doesNotMatch(common,/状态暂不可用/);assert.match(worker,/\.catch\(error => sendResponse\(\{ ok: false/);});
