import {organizeSingleUI} from './harness/reading-closure.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
import {productHistory,productReply,themes} from './fixtures/product-history-v080.mjs';
const out=new URL('../work/v080-product-e2e/',import.meta.url).pathname;
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const original=p=>rpc(p,'GET_ORIGINAL_ORGANIZER_STATUS');
const ai=p=>rpc(p,'GET_AI_PRESENTATION_STATUS');
const screenshot=(p,name)=>p.screenshot({path:out+name+'.png',fullPage:true});
async function editEntry(p,id,suffix){const e=await rpc(p,'GET_LIBRARY_ENTRY',{id});return rpc(p,'EDIT_LIBRARY_FIELDS',{edit:{id,expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,operationId:crypto.randomUUID(),changes:{body:e.body+suffix}}});}

test('v0.8.0 visible complete product: 50 Chinese Inputs → conservative Topics → cached synthesis → evidence → edits → delta',{timeout:240000},async()=>{
 await mkdir(out,{recursive:true});const h=await FakeChatGPT.start({headless:false,deepSeekFixture:productReply});let failures=0;
 try{
  const p=h.archive;await p.setViewportSize({width:1440,height:1000});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await p.locator('[data-view=thoughts]').click();
  assert.match(await p.locator('#thought-empty').innerText(),/默认内容优先保留你的原话/);await screenshot(p,'01-empty-onboarding');await p.locator('[data-view=settings]').click();await p.locator('#start-thought-library').click();await eventually(async()=>/Input Archive/.test(await p.locator('#ai-update-feedback').textContent()));assert.equal(h.deepSeekRequests.length,0);
  await rpc(p,'FILTER_MODE',{mode:'off'});await h.open({id:'product-history',title:'虚构产品验收历史',base:1785542400,messages:productHistory});await eventually(async()=>(await h.state()).records.length===50,'all fifty synthetic Inputs captured');
  await p.locator('[data-view=settings]').click();await p.locator('#deepseek-api-key').fill('synthetic-product-v080');await p.locator('#deepseek-save').click();await eventually(async()=>/已配置/.test(await p.locator('#deepseek-status').textContent()));assert.equal(h.deepSeekRequests.length,0);assert.equal(await p.locator('#organizer-daily-limit').inputValue(),'20');assert.equal(await p.locator('#original-organizer-trace').isVisible(),false);
  await p.locator('[data-view=thoughts]').click();
  for(const processed of [20,40,50]){const before=h.deepSeekRequests.length,preview=(await original(p)).preview;assert.ok(preview.inputCount<=20);await organizeSingleUI(p);await eventually(async()=>(await original(p)).bootstrap.processed===processed,'explicit Original batch finishes');assert.equal(h.deepSeekRequests.length,before+1);await pause(150);assert.equal(h.deepSeekRequests.length,before+1);}
  assert.equal((await original(p)).pendingInput,0);assert.equal(h.deepSeekRequests.length,3);await eventually(async()=>await p.locator('.topic-index-row').count()===5);assert.equal((await p.locator('#thought-list').evaluate(e=>getComputedStyle(e).gridTemplateColumns)).split(' ').length,3);
  const topics=(await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'all'}})).items,ids=topics.map(x=>x.id);assert.deepEqual(new Set(topics.map(t=>t.name)),new Set(themes.map(t=>t.name)));
  let entryCount=0;for(const topic of topics){const page=await rpc(p,'TOPIC_DOCUMENT_PAGE',{options:{topicId:topic.id}});for(const {entry} of page.items){assert.ok(productHistory.some(x=>x.text===entry.body),'source-faithful body is exact local text');entryCount++;}}assert.equal(entryCount,49);
  await eventually(async()=>!(await p.locator('#thought-list').textContent()).includes('正在统计'));await screenshot(p,'02-default-grid');await p.setViewportSize({width:980,height:900});assert.equal((await p.locator('#thought-list').evaluate(e=>getComputedStyle(e).gridTemplateColumns)).split(' ').length,2);await screenshot(p,'03-medium-grid');await p.setViewportSize({width:600,height:900});assert.equal((await p.locator('#thought-list').evaluate(e=>getComputedStyle(e).gridTemplateColumns)).split(' ').length,1);await p.setViewportSize({width:1440,height:1000});
  const topic=topics.find(t=>t.name==='PAIA 产品设计');await p.locator('[data-topic-id="'+topic.id+'"]').click();await eventually(async()=>await p.locator('#topic-body .entry-prose').count()===9);assert.ok(await p.locator('.entry-sent-time').first().isVisible());assert.equal(await p.locator('.entry-sent-time').first().isVisible(),true);await screenshot(p,'04-source-reading');
  const body=p.locator('#topic-body .entry-prose').first(),entryId=await body.evaluate(e=>e.closest('[data-entry-id]').dataset.entryId),initial=await body.textContent();await body.fill(initial+' 人工补充的产品原则。');await p.locator('h1').last().click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id:entryId})).body.endsWith('人工补充的产品原则。'));await p.locator('#library-undo').click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id:entryId})).body===initial);await p.locator('#library-redo').click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id:entryId})).body.endsWith('人工补充的产品原则。'));
  const countBeforeToggle=h.deepSeekRequests.length;await p.locator('#ai-presentation-toggle').check();assert.equal(h.deepSeekRequests.length,countBeforeToggle);
  // This Topic has nine entries: the bounded AI update finishes it in two explicit clicks.
  for(let i=0;i<2;i++){const before=h.deepSeekRequests.length;await p.locator('#ai-library-update').click();await eventually(async()=>h.deepSeekRequests.length===before+1&&(await ai(p)).runtime?.state==='committed'&&await p.locator('[data-ai-field=currentView]').count()===1);assert.equal(h.deepSeekRequests.length,before+1);await pause(120);assert.equal(h.deepSeekRequests.length,before+1);}
  assert.equal((await ai(p)).pendingTopics,4);let presentation=(await ai(p)).topics.find(x=>x.topicId===topic.id).presentation;assert.ok(presentation.currentView);assert.equal(presentation.harmlessExtra,undefined);await eventually(async()=>await p.locator('[data-ai-field=currentView]').count()===1);await screenshot(p,'05-ai-reading');
  await p.locator('.ai-evidence summary').first().click();await p.locator('.ai-evidence button').first().click();await eventually(async()=>await p.locator('#library-dialog').isVisible());assert.ok((await p.locator('#library-dialog .entry-prose').textContent()).includes('PAIA'));await p.locator('#library-dialog .library-entry').hover();await p.locator('#library-dialog').getByRole('button',{name:'内容操作',exact:true}).click();await p.locator('#library-dialog .library-actions[open]').getByRole('button',{name:'来源',exact:true}).click();await eventually(async()=>await p.locator('#library-dialog .entry-provenance button').count()>0);await screenshot(p,'06-evidence');await p.locator('#library-dialog .entry-provenance button').first().click();await eventually(async()=>await p.locator('#view-title').isHidden());assert.equal((await h.state()).records.every(r=>!r.originalText.includes('人工补充')),true);await p.locator('[data-view=thoughts]').click();
  await eventually(async()=>await p.locator('[data-ai-field=currentView]').count()===1&&await p.locator('[data-ai-field=currentView]').isVisible());await p.locator('[data-ai-field=currentView]').fill('这是用户亲自维护的综合理解。');await p.locator('h1').last().click();await eventually(async()=>(await ai(p)).topics.find(x=>x.topicId===topic.id).presentation.currentView==='这是用户亲自维护的综合理解。');await p.locator('#revision-history').click();await eventually(async()=>await p.locator('#library-dialog').isVisible());const revisions=await rpc(p,'GET_AI_PRESENTATION_REVISIONS',{options:{topicId:topic.id}});assert.deepEqual(revisions.items.map(x=>x.actor),['ai','ai','user']);await screenshot(p,'07-independent-revisions');await p.locator('#library-dialog-close').click();
  await editEntry(p,entryId,' 新增的局部修正。');await eventually(async()=>(await ai(p)).topics.find(x=>x.topicId===topic.id).pending);const beforeUpdate=h.deepSeekRequests.length;await p.locator('#ai-library-update').click();await eventually(async()=>!(await p.locator('#ai-update-feedback').textContent()).includes('正在'));assert.equal(h.deepSeekRequests.length,beforeUpdate+1);presentation=(await ai(p)).topics.find(x=>x.topicId===topic.id).presentation;assert.equal(presentation.currentView,'这是用户亲自维护的综合理解。');const deltaRequest=JSON.parse(h.deepSeekRequests.at(-1).messages[1].content);assert.equal(deltaRequest.inputs.length,1);assert.equal(deltaRequest.topicCandidates.length,1);assert.equal(deltaRequest.topicCandidates[0].id,topic.id);
  await p.locator('#back').click();await eventually(async()=>await p.locator('#thought-list').textContent().then(x=>x.includes('项核心内容')));await screenshot(p,'08-ai-grid');assert.deepEqual(new Set((await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'all'}})).items.map(x=>x.id)),new Set(ids));const switchOrder=(await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'all'}})).items.map(x=>x.id);const beforeSwitch=h.deepSeekRequests.length;await p.locator('#ai-presentation-toggle').uncheck();await p.locator('#ai-presentation-toggle').check();assert.equal(h.deepSeekRequests.length,beforeSwitch);assert.deepEqual((await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'all'}})).items.map(x=>x.id),switchOrder);assert.equal(await p.locator('#ai-onboarding').count(),0);
  await p.locator('#thought-search').fill('可检验');await eventually(async()=>await p.locator('.topic-index-row').count()>0);await p.locator('.topic-index-row').first().click();await eventually(async()=>await p.locator('[data-ai-field=blockSummary]').count()===1);await screenshot(p,'09-ai-search-hit');
  await editEntry(p,entryId,' 再次修正以验证失败保留。');await h.context.route('https://api.deepseek.com/**',route=>{failures++;return route.fulfill({status:500,contentType:'application/json',body:'{}'});});const saved=(await ai(p)).topics.find(x=>x.topicId===topic.id).presentation;await p.locator('#ai-library-update').click();await eventually(async()=>/重试将再次调用/.test(await p.locator('#ai-update-feedback').textContent()));assert.equal(failures,1);assert.equal((await ai(p)).topics.find(x=>x.topicId===topic.id).presentation.revision,saved.revision);assert.match(await p.locator('#library-update-diagnostic').textContent(),/PROVIDER_UNAVAILABLE/);await screenshot(p,'10-failure-preserves-cache');await pause(200);assert.equal(failures,1);
  const callsBeforeRestart=h.deepSeekRequests.length+failures;await h.restartWorker();await p.reload();await p.locator('[data-view=settings]').click();await eventually(async()=>/已配置|未配置/.test(await p.locator('#deepseek-status').textContent()));assert.equal(h.deepSeekRequests.length+failures,callsBeforeRestart);await screenshot(p,'11-settings-normal');assert.doesNotMatch(await p.locator('#settings-panel').innerText(),/fetch_started|body_reading|database none|阶段：|HTTP：|policyVersion|classifier\/rules|reason \/ pure_continue/);await p.locator('#organizer-advanced > summary').click();await eventually(async()=>await p.locator('#original-organizer-trace').isVisible());await screenshot(p,'12-settings-advanced');
  const controls=await rpc(p,'GET_ORGANIZER_CONTROLS');await p.locator('#organizer-daily-limit').fill(String(controls.usedRequests));await p.locator('#organizer-daily-limit').dispatchEvent('change');await eventually(async()=>(await rpc(p,'GET_ORGANIZER_CONTROLS')).dailyRequests===controls.usedRequests);await p.locator('[data-view=thoughts]').click();await eventually(async()=>await p.locator('#ai-presentation-toggle').isChecked());await p.locator('[data-topic-id="'+topic.id+'"]').click();await p.locator('#ai-library-update').click();await eventually(async()=>/上限/.test(await p.locator('#ai-update-feedback').textContent()));assert.equal(h.deepSeekRequests.length+failures,callsBeforeRestart);
  assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);for(const body of h.deepSeekRequests){const r=JSON.parse(body.messages[1].content);assert.equal(body.model,'deepseek-v4-flash');assert.equal(body.response_format.type,'json_object');assert.ok(r.inputs.length<=(r.taskProfile==='ai_synthesis'?8:20));assert.doesNotMatch(JSON.stringify(r),/FAKE_ASSISTANT|FAKE_DRAFT|sourceRecordId|synthetic-product-v080/);}
  await writeFile(out+'acceptance.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,inputCount:50,sourceEntryCount:entryCount,topics:5,originalRequests:3,aiRequests:h.deepSeekRequests.length-3,failedRequests:failures,externalRequests:h.externalRequests,checks:['A','B','C','D','E','F','G','H','J','K','L','M','N','O'],errors:h.errors},null,2));
 }catch(error){await screenshot(h.archive,'failure').catch(()=>{});await writeFile(out+'failure.json',JSON.stringify({message:error.message,errors:h.errors,requestCount:h.deepSeekRequests.length,failures},null,2));throw error;}finally{await h.close();}
});

test('v0.8.0 visible partial Original result keeps valid items and clear update-center feedback',{timeout:60000},async()=>{
 await mkdir(out,{recursive:true});const h=await FakeChatGPT.start({headless:false,deepSeekFixture:body=>productReply(body,{partial:true})});try{const p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await h.open({id:'product-partial',title:'虚构部分成功验收',base:1785542400,messages:productHistory.slice(0,5)});await eventually(async()=>(await h.state()).records.length===5);await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-product-partial'}});await p.locator('[data-view=thoughts]').click();await p.locator('[data-view=settings]').click();await p.locator('#start-thought-library').click();await eventually(async()=>/部分成功/.test(await p.locator('#ai-update-feedback').textContent()));assert.equal(h.deepSeekRequests.length,1);assert.equal((await original(p)).diagnostics.manualInputCount,1);assert.equal((await original(p)).organizedInputCount,4);assert.equal((await original(p)).manualRequiredInputCount,1);assert.equal((await rpc(p,'GET_THOUGHTS')).items.length,4);assert.equal((await h.state()).records.length,5);await screenshot(p,'13-partial-success');assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);await writeFile(out+'partial.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,valid:4,manualRequired:1,requests:1,check:'I'},null,2));}finally{await h.close();}
});
