import test from 'node:test';import assert from 'node:assert/strict';import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';import {seedMemoryRPC} from './fixtures/memory-v0100.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(q=>chrome.runtime.sendMessage(q),{type,...fields});assert.equal(r.ok,true);return r.data;};
test('Identical content invalidation is invisible; an obsolete delayed search cannot paint over the latest query',{timeout:45000},async()=>{
 const h=await FakeChatGPT.start({headless:true}),p=h.archive;try{
  await p.locator('#consent-check').check();await p.locator('#enable-consent').click();const f=await seedMemoryRPC((t,o)=>rpc(p,t,o));await p.locator('[data-view=thoughts]').click();await p.locator(`[data-topic-id="${f.paia.id}"]`).click();await p.locator('[data-entry-field=body]').first().waitFor();await p.waitForTimeout(400);
  await p.evaluate(()=>{window.sameMutations=0;window.sameReads=0;window.readingSameRoot=document.querySelector('#topic-body');window.sameObserver=new MutationObserver(ms=>window.sameMutations+=ms.filter(x=>x.type==='childList').length);window.sameObserver.observe(window.readingSameRoot,{subtree:true,childList:true});const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.restoreSame=()=>chrome.runtime.sendMessage=send;chrome.runtime.sendMessage=q=>{if(q.type==='TOPIC_DOCUMENT_PAGE')window.sameReads++;return send(q);};});
  const topic=await rpc(p,'GET_LIBRARY_TOPIC',{id:f.paia.id});await rpc(p,'EDIT_LIBRARY_TOPIC',{edit:{id:topic.id,expectedRevision:topic.revision,changes:{name:topic.name},operationId:crypto.randomUUID()}});await eventually(()=>p.evaluate(()=>window.sameReads>0));await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>window.sameMutations),0);await p.evaluate(()=>{window.sameObserver.disconnect();window.restoreSame();});
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);window.restoreSearchRace=()=>chrome.runtime.sendMessage=send;window.stalePaint=false;const root=document.querySelector('#original-reading-body');window.searchRaceObserver=new MutationObserver(()=>{const nodes=root.querySelectorAll('[data-entry-field=body]');if(nodes.length===1&&nodes[0].textContent.includes('PAIA 新决定'))window.stalePaint=true;});window.searchRaceObserver.observe(root,{subtree:true,childList:true});chrome.runtime.sendMessage=async q=>{if(q.type==='TOPIC_DOCUMENT_PAGE'&&q.options.query==='PAIA 新决定'){window.oldSearchEntered=true;const response=await send(q);await new Promise(r=>window.releaseOldSearch=r);return response;}return send(q);};});
  await p.locator('#topic-search').fill('PAIA 新决定');await eventually(()=>p.evaluate(()=>window.oldSearchEntered));await p.locator('#topic-search').fill('PAIA 偏好');await p.waitForTimeout(250);await p.evaluate(()=>window.releaseOldSearch());await eventually(async()=>await p.locator('#original-reading-body [data-entry-field=body]').count()===1&&(await p.locator('#original-reading-body').textContent()).includes('PAIA 偏好'));
  assert.equal(await p.evaluate(()=>window.stalePaint),false);assert.equal(await p.evaluate(()=>window.readingSameRoot===document.querySelector('#topic-body')),true);await p.evaluate(()=>{window.searchRaceObserver.disconnect();window.restoreSearchRace();});assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
 }finally{await h.close();}
});
