import test from 'node:test';import assert from 'node:assert/strict';
import {InputReview} from '../ui/review.js';import {PresentationNode as Node} from './harness/presentation-dom.mjs';
const gate=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};};
const input=id=>({id,revision:7,branchStatus:'pending'}),doc=id=>({id,originalConversationTitle:id});
function fixture(send){const nodes=new Map(),body=new Node();globalThis.document={body,documentElement:{lang:'zh-CN'},createElement:t=>new Node(t),createElementNS:(ns,t)=>new Node(t,ns),createTextNode:t=>{const n=new Node('#text');n.textContent=t;return n;},getElementById:id=>{if(!nodes.has(id)){const n=new Node();n.id=id;body.append(n);nodes.set(id,n);}return nodes.get(id);}};globalThis.chrome={runtime:{sendMessage:async m=>({ok:true,data:await send(m)})}};const get=document.getElementById,dialog=get('review-dialog');dialog.showModal=()=>{dialog.open=true;};dialog.close=()=>{dialog.open=false;dialog.listeners.get('close')?.();};let refreshes=0;const owner=new InputReview({navigate:async()=>{},refresh:async()=>{refreshes++;}});owner.enter('settings');owner.paint('excluded');return{owner,get,dialog,refreshes:()=>refreshes,close:()=>get('review-dialog-close').listeners.get('click')()};}
const page=ids=>({documents:ids.map(doc),nextCursor:null});
test('A closed then B opened cannot acquire A late options or confirmation handler',async()=>{const a=gate(),b=gate(),calls=[];let reads=0;const f=fixture(async m=>{calls.push(m);return m.type==='GET_PAGE'?(++reads===1?a.promise:b.promise):{documentId:m.payload.documentId};});const first=f.owner.choose(input('a'),doc('origin-a'));f.close();const second=f.owner.choose(input('b'),doc('origin-b'));b.resolve(page(['target-b']));await second;a.resolve(page(['target-a']));await first;assert.deepEqual(f.get('review-document').children.map(n=>n.value),['origin-b','target-b']);f.get('review-document').value='target-b';await f.get('review-assign').onclick();assert.equal(calls.find(m=>m.type==='IMPORT_RESOLVE_BRANCH').payload.id,'b');});
test('opening replacement clears old confirmation before its first read completes',async()=>{const hold=gate(),calls=[];let reads=0;const f=fixture(async m=>{calls.push(m);return m.type==='GET_PAGE'?(++reads===1?page(['target-a']):hold.promise):{};});await f.owner.choose(input('a'),doc('origin-a'));f.close();const next=f.owner.choose(input('b'),doc('origin-b'));try{assert.equal(f.get('review-assign').disabled,true);await f.get('review-assign').onclick?.();assert.equal(calls.filter(m=>m.type==='IMPORT_RESOLVE_BRANCH').length,0);}finally{hold.resolve(page(['target-b']));await next;}});
test('duplicate confirmation submits one exact CAS request and late durable ACK cannot close B',async()=>{const ack=gate(),calls=[];const f=fixture(async m=>{calls.push(m);return m.type==='GET_PAGE'?page(['target']):ack.promise;});await f.owner.choose(input('a'),doc('origin-a'));f.get('review-document').value='target';const confirm=f.get('review-assign').onclick,first=confirm(),second=confirm();f.close();await f.owner.choose(input('b'),doc('origin-b'));ack.resolve({documentId:'target'});await Promise.all([first,second]);assert.equal(calls.filter(m=>m.type==='IMPORT_RESOLVE_BRANCH').length,1);const payload=calls.find(m=>m.type==='IMPORT_RESOLVE_BRANCH').payload;assert.equal(payload.expectedRevision,7);assert.equal(payload.action,'existing');assert.equal(payload.documentId,'target');assert.match(payload.operationId,/^[a-f0-9-]{36}$/);assert.equal(f.dialog.open,true);assert.equal(f.refreshes(),0);assert.deepEqual(f.get('review-document').children.map(n=>n.value),['origin-b','target']);});
test('closed initial read failure cannot replace the new dialog status',async()=>{const hold=gate();let reads=0;const f=fixture(async()=>++reads===1?hold.promise:page(['b-target']));const first=f.owner.choose(input('a'),doc('a'));f.close();await f.owner.choose(input('b'),doc('b'));const status=f.get('review-choice-status').textContent;hold.reject(Error('synthetic read refused'));await first;assert.equal(f.get('review-choice-status').textContent,status);assert.equal(f.get('review-assign').disabled,false);});
test('current read failure remains retryable and cannot confirm before a successful read',async()=>{let reads=0;const f=fixture(async()=>{if(++reads===1)throw Error('synthetic read refused');return page(['target']);});await f.owner.choose(input('a'),doc('a'));assert.equal(f.get('review-assign').disabled,true);assert.equal(f.get('review-documents-more').hidden,false);f.get('review-documents-more').onclick();await new Promise(r=>setImmediate(r));assert.equal(f.get('review-assign').disabled,false);});
test('current CAS refusal retains selection and permits an explicit retry',async()=>{let writes=0;const f=fixture(async m=>{if(m.type==='GET_PAGE')return page(['target']);if(++writes===1)throw Error('CONFLICT');return {documentId:'target'};});await f.owner.choose(input('a'),doc('a'));f.get('review-document').value='target';await f.get('review-assign').onclick();assert.equal(f.dialog.open,true);assert.equal(f.get('review-document').value,'target');assert.equal(f.get('review-assign').disabled,false);assert.match(f.get('review-choice-status').textContent,/处理未完成/);await f.get('review-assign').onclick();assert.equal(writes,2);assert.equal(f.dialog.open,false);assert.equal(f.refreshes(),1);});
test('route leave and Escape invalidate saved handlers even if called directly',async()=>{let writes=0;const f=fixture(async m=>{if(m.type==='GET_PAGE')return page(['target']);writes++;return{};});await f.owner.choose(input('a'),doc('a'));const first=f.get('review-assign').onclick;f.owner.paint('settings');await first();assert.equal(writes,0);f.owner.paint('excluded');await f.owner.choose(input('b'),doc('b'));const second=f.get('review-assign').onclick;f.dialog.listeners.get('cancel')();f.dialog.close();await second();assert.equal(writes,0);});
