import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';import {chooseConsumerGroup} from './harness/settings-consumer-presentation.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),out=join(root,'work/settings-next');
// Borrowed restart profiles need the same bounded filesystem cleanup as the
// harness-owned profiles, after the actual spawned browser has exited.
async function removeStoppedProfile(h,profile){
 await h?.close();
 const child=h?.externalChrome?.processHandle;
 if(child)assert.ok(child.exitCode!==null||child.signalCode!==null,'Chrome must exit before its isolated restart profile is removed');
 await rm(profile,{recursive:true,force:true,maxRetries:10,retryDelay:100});
}
const read=p=>p.evaluate(async()=>{const r=await chrome.runtime.sendMessage({type:'PAIA_PROMPT_NEXT_STATUS'});if(!r.ok)throw Error(JSON.stringify(r));return r.data;});
async function open(p){await p.setViewportSize({width:1440,height:900});await p.locator('.sidebar-bottom [data-view="settings"]').click();await chooseConsumerGroup(p,'ai');await eventually(()=>p.locator('#settings-next-enabled').isEnabled());}
async function compactKeyboard(p,variant){
 await chooseConsumerGroup(p,'reading');await p.locator('#ux-language').selectOption('en');await eventually(()=>p.locator('html').getAttribute('lang').then(x=>x==='en'));await chooseConsumerGroup(p,'ai');await p.setViewportSize({width:320,height:900});
 const toggle=p.locator('#settings-next-enabled'),dialog=p.locator('#settings-next-consent'),focus=()=>p.evaluate(()=>document.activeElement?.id);
 await p.evaluate(()=>{const nodes=[document.getElementById('settings-next-enabled'),...document.querySelectorAll('#settings-next-consent,#settings-next-consent *')];globalThis.__nextScale=nodes.map(node=>({node,value:node.style.getPropertyValue('font-size'),priority:node.style.getPropertyPriority('font-size'),base:parseFloat(getComputedStyle(node).fontSize)}));for(const row of __nextScale)row.node.style.setProperty('font-size',row.base*2+'px','important');const original=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__nextKeyboard={original,writes:[]};chrome.runtime.sendMessage=async message=>{if(message.type==='PAIA_PROMPT_NEXT_CONFIGURE')__nextKeyboard.writes.push(message.enabled);return original(message);};});
 try{
  assert.equal(await p.evaluate(()=>__nextScale.every(row=>Math.abs(parseFloat(getComputedStyle(row.node).fontSize)-row.base*2)<.1)),true,'actual computed text sizes doubled');
  await toggle.focus();await p.keyboard.press('Space');await dialog.waitFor({state:'visible'});assert.equal(await focus(),'settings-next-cancel');assert.equal((await read(p)).enabled,false);
  const geometry=await dialog.evaluate(node=>{const r=node.getBoundingClientRect();return{x:r.x,right:r.right,width:r.width,overflow:node.scrollWidth-node.clientWidth,pageOverflow:document.documentElement.scrollWidth-innerWidth};});console.log('SET2_NEXT_COMPACT',JSON.stringify({variant,geometry}));
  assert.ok(geometry.x>=0&&geometry.right<=320&&geometry.overflow<=2&&geometry.pageOverflow<=2,'320px doubled-text dialog has no horizontal clipping');await p.screenshot({path:join(out,variant+'-dialog-320-en-text200.png')});
  await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>{const active=document.activeElement;return active===document.body||document.getElementById('settings-next-consent').contains(active);}),true,'native modal Tab never focuses an underlying app control');await p.keyboard.press('Shift+Tab');assert.equal(await focus(),'settings-next-cancel');
  await p.keyboard.press('Shift+Tab');assert.equal(await focus(),'settings-next-confirm');await p.keyboard.press('Tab');assert.equal(await focus(),'settings-next-cancel');await p.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await focus(),'settings-next-enabled');assert.equal((await read(p)).enabled,false);
  await p.keyboard.press('Space');await dialog.waitFor({state:'visible'});await p.keyboard.press('Space');await dialog.waitFor({state:'hidden'});assert.equal(await focus(),'settings-next-enabled');assert.equal((await read(p)).enabled,false);assert.deepEqual(await p.evaluate(()=>__nextKeyboard.writes),[],'Escape and keyboard cancel never grant consent');
  await p.keyboard.press('Space');await dialog.waitFor({state:'visible'});await p.keyboard.press('Shift+Tab');assert.equal(await focus(),'settings-next-confirm');const button=await p.locator('#settings-next-confirm').boundingBox();assert.ok(button.x>=0&&button.x+button.width<=320&&button.y>=0&&button.y+button.height<=900,'focused confirmation remains reachable');await p.keyboard.press('Enter');await eventually(()=>toggle.isChecked());assert.equal((await read(p)).enabled,true);assert.deepEqual(await p.evaluate(()=>__nextKeyboard.writes),[true],'one native confirmation sends exactly one enable');await toggle.focus();await p.keyboard.press('Space');await eventually(async()=>!await toggle.isChecked());assert.deepEqual(await p.evaluate(()=>__nextKeyboard.writes),[true,false]);
 }finally{await p.evaluate(()=>{const d=document.getElementById('settings-next-consent');if(d.open)d.close();chrome.runtime.sendMessage=__nextKeyboard.original;for(const row of __nextScale){if(row.value)row.node.style.setProperty('font-size',row.value,row.priority);else row.node.style.removeProperty('font-size');}delete globalThis.__nextKeyboard;delete globalThis.__nextScale;});await p.setViewportSize({width:1440,height:900});}
}
for(const variant of ['source','release'])test('SET2-03 '+variant+' consent and shared browser-session owner',{timeout:90000},async()=>{
 const release=variant==='release'?await mkdtemp(join(tmpdir(),'paia-set2-release-')):null,profile=await mkdtemp(join(tmpdir(),'paia-set2-profile-'));if(release)execFileSync('python3',['scripts/build_current_release.py',release],{cwd:root,stdio:'pipe'});let h;await mkdir(out,{recursive:true});
 try{h=await FakeChatGPT.start({extensionPath:release||root,headless:true,userDataDir:profile,launchThroughPort:true});const p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await open(p);const c=p.locator('#settings-next-enabled');assert.equal(await c.isChecked(),false);
 await c.click();await p.locator('#settings-next-consent').waitFor({state:'visible'});assert.equal((await read(p)).enabled,false);await p.locator('#settings-next-cancel').click();assert.equal((await read(p)).enabled,false);assert.equal(await p.evaluate(()=>document.activeElement.id),'settings-next-enabled');
 await compactKeyboard(p,variant);
 await c.click();await p.locator('#settings-next-confirm').click();await eventually(()=>c.isChecked());assert.equal((await read(p)).enabled,true);const peer=await h.context.newPage();await peer.goto(p.url());await open(peer);assert.equal(await peer.locator('#settings-next-enabled').isChecked(),true);await peer.locator('#settings-next-enabled').click();await eventually(async()=>!await c.isChecked());
 await p.bringToFront();await c.click();await p.locator('#settings-next-confirm').click();await eventually(()=>c.isChecked());await p.reload();await open(p);assert.equal(await c.isChecked(),true,'page reload retains browser-session consent');assert.equal(JSON.stringify(await p.evaluate(()=>chrome.storage.local.get(null))).includes('promptNextAuthorizationV1'),false);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);await chooseConsumerGroup(p,'reading');await p.locator('#ux-language').selectOption('en');await eventually(()=>p.locator('html').getAttribute('lang').then(x=>x==='en'));await chooseConsumerGroup(p,'ai');assert.match(await p.locator('#settings-next-explanation').innerText(),/browser session/);await p.setViewportSize({width:320,height:900});await p.screenshot({path:join(out,variant+'-narrow.png'),fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await h.close();h=null;await rm(join(profile,'DevToolsActivePort'),{force:true});h=await FakeChatGPT.start({extensionPath:release||root,headless:true,userDataDir:profile,launchThroughPort:true,onboarding:true});await open(h.archive);assert.equal((await read(h.archive)).enabled,false,'actual browser restart clears consent');assert.equal(await h.archive.locator('#settings-next-enabled').isChecked(),false);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
 }catch(error){console.error('SET2_DIAGNOSTIC',JSON.stringify({errors:h?.errors,body:await h?.archive.locator('body').innerText()}));throw error;}finally{await removeStoppedProfile(h,profile);if(release)await rm(release,{recursive:true,force:true});}
});
