import test from 'node:test';import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';import {OrganizerStore} from '../core/organizer/store.js';
async function fixture(n=43){const {s}=await setup(OrganizerStore);await s.finishFoundation();for(let i=0;i<n;i++){const t=await s.createTopic({name:'SYNTHETIC removed '+i,operationId:crypto.randomUUID()});await s.removeTopic({id:t.id,expectedRevision:(await s.topic(t.id)).revision,operationId:crypto.randomUUID()});}return s;}
test('removed Topics use bounded complete pages without losing typed identities',async()=>{const s=await fixture(),a=await s.removedTopics({limit:20});assert.equal(a.items.length,20);assert.ok(a.nextCursor);const b=await s.removedTopics({limit:20,cursor:a.nextCursor}),c=await s.removedTopics({limit:20,cursor:b.nextCursor});assert.equal(b.items.length,20);assert.equal(c.items.length,3);assert.equal(c.nextCursor,null);assert.equal(new Set([...a.items,...b.items,...c.items].map(x=>x.id)).size,43);});
test('real restore makes previous removed Topic continuation stale',async()=>{const s=await fixture(3),a=await s.removedTopics({limit:1});await s.restoreTopicContainer({id:a.items[0].id,expectedRevision:a.items[0].revision,operationId:crypto.randomUUID()});const b=await s.removedTopics({limit:1,cursor:a.nextCursor});assert.equal(b.cursorInvalid,true);assert.deepEqual(b.items,[]);});

test('strict continuation rejects malformed tuples and unknown options',async()=>{const s=await fixture(2),page=await s.removedTopics({limit:1});for(const cursor of [{...page.nextCursor,extra:true},{...page.nextCursor,key:[0,1,'500000000000',0,'id']},{...page.nextCursor,key:[1,1,5,0,'id']},{...page.nextCursor,generation:-1},{...page.nextCursor,recoveryEpoch:''}])await assert.rejects(s.removedTopics({cursor}),{code:'INVALID_REQUEST'});await assert.rejects(s.removedTopics({limit:101}),{code:'INVALID_REQUEST'});});
test('restore epoch invalidates continuation even if data generation is unchanged',async()=>{const s=await fixture(2),page=await s.removedTopics({limit:1});await s.repository.transaction(true,t=>t.put('meta',{id:'recovery-restore-epoch',value:'SYNTHETIC restored epoch'}));const result=await s.removedTopics({cursor:page.nextCursor});assert.equal(result.cursorInvalid,true);assert.deepEqual(result.items,[]);});
test('filtered inactive rows preserve bounded continuation instead of false terminal emptiness',async()=>{const s=await fixture(3),first=await s.removedTopics({limit:1});await s.repository.transaction(true,async t=>{const row=await t.get('topics',first.items[0].id);row.lifecycle='merged';row.redirectTo='SYNTHETIC successor';await t.put('topics',row);});const empty=await s.removedTopics({limit:1});assert.deepEqual(empty.items,[]);assert.ok(empty.nextCursor);const next=await s.removedTopics({limit:1,cursor:empty.nextCursor});assert.equal(next.items.length,1);});

test('removed Topic read uses one bounded indexed page and never scans topics',async()=>{const s=await fixture(5),original=s.repository.transaction.bind(s.repository),pages=[];s.repository.transaction=(write,run,...rest)=>original(write,t=>run(new Proxy(t,{get(target,key){if(key==='all')return(name,...args)=>{assert.notEqual(name,'topics','no whole Topic scan');return target.all(name,...args);};if(key==='rangePage')return(...args)=>{if(args[0]==='topics')pages.push(args);return target.rangePage(...args);};const value=target[key];return typeof value==='function'?value.bind(target):value;}})),...rest);const result=await s.removedTopics({limit:2});assert.equal(result.items.length,2);assert.equal(pages.length,1);assert.equal(pages[0][1],'byIndex');assert.equal(pages[0][4],2);});
