import test from 'node:test';import assert from 'node:assert/strict';
import {BackupPanel} from '../ui/backup.js';
import {PresentationNode as Node} from './harness/presentation-dom.mjs';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function fixture(send){const nodes=new Map();globalThis.document={documentElement:{lang:'zh-CN'},createElement:t=>new Node(t),getElementById:id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id);}};globalThis.chrome={runtime:{sendMessage:async m=>({ok:true,data:await send(m)})}};const panel=Object.assign(Object.create(BackupPanel.prototype),{busy:false,sessionId:'old',mode:'empty',preview:{canRestore:true,integrity:'old-integrity',targetGeneration:1},pickerDescription:null});return{panel,node:id=>document.getElementById(id)};}
const invalidFile=()=>Object.assign(new Blob(['invalid\n']),{name:'synthetic.paia-backup'});
test('cancel immediately fences native/programmatic restore and reselect until acknowledged',async()=>{const gate=deferred(),calls=[];const {panel,node}=fixture(async m=>{calls.push(m);if(m.type==='PAIA_BACKUP_CANCEL')await gate.promise;return{};});const cancelling=panel.cancel();try{assert.equal(panel.busy,true);assert.equal(node('backup-restore').disabled,true);await panel.restore();await panel.inspect([invalidFile()]);assert.deepEqual(calls.map(m=>m.type),['PAIA_BACKUP_CANCEL']);}finally{gate.resolve();await cancelling;}assert.equal(panel.busy,false);assert.equal(panel.sessionId,null);assert.equal(panel.preview,null);assert.equal(node('backup-choose').disabled,false);assert.equal(node('backup-restore').disabled,true);});
test('two file changes cannot both cross the old-session cancellation await',async()=>{const gate=deferred(),calls=[];const {panel}=fixture(async m=>{calls.push(m);if(m.type==='PAIA_BACKUP_CANCEL'&&m.options.sessionId==='old')await gate.promise;return{sessionId:'new'};});const first=panel.inspect([invalidFile()]),second=panel.inspect([invalidFile()]);gate.resolve();await Promise.all([first,second]);assert.equal(calls.filter(m=>m.type==='PAIA_BACKUP_BEGIN_RESTORE').length,1);assert.equal(calls.filter(m=>m.type==='PAIA_BACKUP_CANCEL'&&m.options.sessionId==='old').length,1);assert.equal(panel.busy,false);});
test('repeated cancel shares no second remote mutation and reselect works after acknowledgement',async()=>{const gate=deferred(),calls=[];const {panel}=fixture(async m=>{calls.push(m);if(m.type==='PAIA_BACKUP_CANCEL'&&m.options.sessionId==='old')await gate.promise;return{sessionId:'new'};});const first=panel.cancel(),second=panel.cancel();gate.resolve();await Promise.all([first,second]);assert.equal(calls.length,1);await panel.inspect([invalidFile()]);assert.equal(calls.filter(m=>m.type==='PAIA_BACKUP_BEGIN_RESTORE').length,1);assert.equal(panel.busy,false);assert.equal(panel.sessionId,null);});
test('cancel rejection still releases controls without dispatching any restore',async()=>{const {panel,node}=fixture(async()=>{throw Error('synthetic disconnected channel');});await panel.cancel();assert.equal(panel.sessionId,null);assert.equal(panel.preview,null);assert.equal(panel.busy,false);assert.equal(node('backup-choose').disabled,false);assert.equal(node('backup-restore').disabled,true);});
test('a stale cancellation result cannot clear a different session identity',async()=>{const gate=deferred();const {panel}=fixture(async()=>{await gate.promise;return{};});const old=panel.cancel();panel.sessionId='different';const preview={canRestore:false};panel.preview=preview;gate.resolve();await old;assert.equal(panel.sessionId,'different');assert.equal(panel.preview,preview);});
test('duplicate file changes with no previous session admit one inspection',async()=>{const calls=[];const {panel}=fixture(async m=>{calls.push(m);return{sessionId:'new'};});panel.sessionId=null;await Promise.all([panel.inspect([invalidFile()]),panel.inspect([invalidFile()])]);assert.equal(calls.filter(m=>m.type==='PAIA_BACKUP_BEGIN_RESTORE').length,1);});
test('replace still requires explicit confirmation and retains exact preview identity',async()=>{const calls=[];const {panel,node}=fixture(async m=>{calls.push(m);throw Object.assign(Error('synthetic refusal'),{code:'BACKUP_CHANGED'});});panel.mode='replace';node('backup-confirm-replace').checked=false;await panel.restore();assert.equal(calls.length,0);node('backup-confirm-replace').checked=true;await panel.restore();assert.deepEqual(calls[0],{type:'PAIA_BACKUP_RESTORE',options:{sessionId:'old',confirmation:'old-integrity',mode:'replace',targetGeneration:1,confirmReplace:true,confirmMerge:false}});assert.equal(panel.preview.integrity,'old-integrity');assert.equal(panel.busy,false);});
