import test from 'node:test';import assert from 'node:assert/strict';
import {TopicController} from '../ui/topic-workspace.js';
import {PresentationNode as Node} from './harness/presentation-dom.mjs';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function fixture(send){const nodes=new Map(),body=new Node();globalThis.document={body,addEventListener(){},documentElement:{lang:'zh-CN'},createElement:t=>new Node(t),getElementById:id=>{if(!nodes.has(id)){const n=new Node();n.id=id;body.append(n);nodes.set(id,n);}return nodes.get(id);}};globalThis.chrome={runtime:{sendMessage:async m=>({ok:true,data:await send(m)})}};const owner=Object.assign(Object.create(TopicController.prototype),{onStatus:()=>{},refresh:async()=>{},revisions:async()=>{}});return{owner,list:document.getElementById('library-management-list')};}
const entry=id=>({id,body:id,revision:1});
test('actual TopicController rejects a late Topic response after selecting removed Entries',async()=>{const h=deferred(),f=fixture(m=>m.type==='GET_LIBRARY_REMOVED_TOPICS'?h.promise:{items:[entry('entry-a')],nextCursor:null});const old=f.owner.removedTopics();await f.owner.removed();h.resolve({items:[{id:'topic-a',name:'obsolete-topic',revision:1}]});await old;assert.match(f.list.textContent,/entry-a/);assert.doesNotMatch(f.list.textContent,/obsolete-topic/);});
test('actual TopicController admits a cursor once while its page is pending',async()=>{const h=deferred();let reads=0;const f=fixture(m=>{if(!m.options.cursor)return{items:[entry('first')],nextCursor:'cursor-1'};reads++;return h.promise;});await f.owner.removed();const a=f.owner.removed('cursor-1'),b=f.owner.removed('cursor-1');h.resolve({items:[entry('second')],nextCursor:null});await Promise.all([a,b]);assert.equal(reads,1);assert.equal(f.list.textContent.match(/second/g)?.length,1);assert.doesNotMatch(f.list.textContent,/更多已删除内容/);});
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const findButton=(node,text)=>node.children.flatMap(n=>[n,...n.children]).find(n=>n.tagName==='BUTTON'&&n.textContent===text);
test('failed continuation preserves rows and retries the same cursor once',async()=>{let fail=true;const f=fixture(m=>{if(!m.options.cursor)return{items:[entry('first')],nextCursor:'next'};if(fail)throw Error('read failed');return{items:[entry('second')],nextCursor:null};});await f.owner.removed();const first=f.list.children[0];await assert.rejects(f.owner.removed('next')); assert.equal(f.list.children[0],first);assert.equal(findButton(f.list,'更多已删除内容').disabled,false);fail=false;await f.owner.removed('next');assert.equal(f.list.children[0],first);assert.match(f.list.textContent,/second/);});
test('route hide and reopen invalidates a held response even when currently visible',async()=>{const h=deferred(),f=fixture(()=>h.promise);const p=f.owner.removed();const presenter=f.owner.removedList();let records=[{attributeName:'hidden'},{attributeName:'hidden'}];presenter.observer={takeRecords:()=>{const r=records;records=[];return r;}};h.resolve({items:[entry('late')],nextCursor:null});await p;assert.doesNotMatch(f.list.textContent,/late/);});
test('restore acknowledgement cannot replace a newer list type and duplicate clicks do not dispatch',async()=>{const ack=deferred(),writes=[];let refresh=0;const f=fixture(m=>{if(m.type.startsWith('RESTORE_')){writes.push(m);return ack.promise;}return{items:m.type==='GET_LIBRARY_REMOVED_TOPICS'?[{id:'topic-b',name:'Topic B',revision:2}]:[entry('entry-a')],nextCursor:null};});f.owner.refresh=async()=>refresh++;await f.owner.removed();const b=findButton(f.list,'恢复内容');b.listeners.get('click')();b.listeners.get('click')();await tick();assert.equal(writes.length,1);assert.equal(b.disabled,true);assert.equal(writes[0].edit.expectedRevision,1);await f.owner.removedTopics();ack.resolve({});await tick();assert.match(f.list.textContent,/Topic B/);assert.doesNotMatch(f.list.textContent,/entry-a/);assert.equal(refresh,0);});
test('failed restore retains the exact row and retry operation identity',async()=>{const writes=[];const f=fixture(m=>{if(m.type.startsWith('RESTORE_')){writes.push(m);throw Error('ack unknown');}return{items:[entry('entry-a')],nextCursor:null};});await f.owner.removed();const row=f.list.children[0],b=findButton(f.list,'恢复内容');b.listeners.get('click')();await tick();assert.equal(f.list.children[0],row);assert.equal(b.disabled,false);b.listeners.get('click')();await tick();assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);});
test('disconnected or hidden destination cannot start reads or stale actions',async()=>{let reads=0;const f=fixture(()=>{reads++;return{items:[entry('entry-a')],nextCursor:null};});await f.owner.removed();const b=findButton(f.list,'恢复内容');document.getElementById('settings-panel').hidden=true;await f.owner.removedTopics();b.listeners.get('click')();await tick();assert.equal(reads,1);});
test('a restore failure delivered after switching type does not publish an error on the new list',async()=>{let reject;const ack=new Promise((_,r)=>reject=r),f=fixture(m=>m.type.startsWith('RESTORE_')?ack:{items:m.type==='GET_LIBRARY_REMOVED_TOPICS'?[{id:'topic-b',name:'Topic B',revision:2}]:[entry('entry-a')],nextCursor:null});const notices=[];f.owner.onStatus=(...args)=>notices.push(args);const error=document.getElementById('error');error.hidden=true;await f.owner.removed();findButton(f.list,'恢复内容').listeners.get('click')();await tick();await f.owner.removedTopics();reject(Error('late failure'));await tick();assert.deepEqual(notices,[]);assert.equal(error.hidden,true);assert.match(f.list.textContent,/Topic B/);});
test('actual checked conflict remains visible on the current list and never removes its row',async()=>{const notices=[],f=fixture(m=>m.type.startsWith('RESTORE_')?{conflict:true}:{items:[entry('entry-a')],nextCursor:null});f.owner.onStatus=(...args)=>notices.push(args);await f.owner.removed();const row=f.list.children[0];findButton(f.list,'恢复内容').listeners.get('click')();await tick();assert.equal(f.list.children[0],row);assert.equal(notices.length,1);assert.equal(notices[0][1],'conflict');});
test('a current post-restore list read failure is reported and retains the old row',async()=>{let restored=false;const f=fixture(m=>{if(m.type.startsWith('RESTORE_')){restored=true;return{};}if(restored)throw Error('read failed');return{items:[entry('entry-a')],nextCursor:null};});const error=document.getElementById('error');error.hidden=true;await f.owner.removed();const row=f.list.children[0];findButton(f.list,'恢复内容').listeners.get('click')();await tick();assert.equal(f.list.children[0],row);assert.equal(error.hidden,false);});

test('actual Topic list continues through filtered empty pages and invalid cursor reload preserves old rows',async()=>{const calls=[];let invalid=false;const f=fixture(m=>{calls.push(m);if(m.options.cursor==='one')return{items:[],nextCursor:'two'};if(m.options.cursor==='two')return invalid?{items:[],nextCursor:null,cursorInvalid:true}:{items:[{id:'late',name:'SYNTHETIC late',revision:1}],nextCursor:null};return{items:[],nextCursor:'one'};});await f.owner.removedTopics();assert.doesNotMatch(f.list.textContent,/没有已删除/);findButton(f.list,'更多已删除主题').listeners.get('click')();await tick();assert.equal(calls.at(-1).options.cursor,'one');assert.doesNotMatch(f.list.textContent,/没有已删除/);invalid=true;findButton(f.list,'更多已删除主题').listeners.get('click')();await tick();assert.equal(calls.at(-1).options.cursor,'two');assert.ok(findButton(f.list,'列表已改变，重新加载'));const reads=calls.length;assert.equal(reads,3);findButton(f.list,'列表已改变，重新加载').listeners.get('click')();await tick();assert.equal(calls.at(-1).options.cursor,null);assert.equal(calls.length,reads+1);});

test('queued stale reload cannot reopen Topic kind after switching to Entries',async()=>{const calls=[],f=fixture(m=>{calls.push(m);return m.options.cursor?{items:[],cursorInvalid:true,nextCursor:null}:{items:[],nextCursor:'old'};});await f.owner.removedTopics();findButton(f.list,'更多已删除主题').listeners.get('click')();await tick();const old=findButton(f.list,'列表已改变，重新加载');old.listeners.get('click')();const current=f.owner.removed();await current;await tick();assert.equal(calls.filter(m=>m.type==='GET_LIBRARY_REMOVED_TOPICS').length,2,'old queued reload sends no third Topic read');});
