import test from 'node:test';
import assert from 'node:assert/strict';
import {PresentationNode} from './harness/presentation-dom.mjs';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('privacy pill keeps the same native labeled checkbox and acknowledged mask owner',async()=>{
 const names=['document','navigator','chrome','MutationObserver'],prior=new Map(names.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)])),nodes=[],make=tag=>{const n=new PresentationNode(tag);n.getClientRects=()=>[{}];nodes.push(n);return n;},body=make('body'),head=make('head'),root=make('html'),host=make('div');host.id='settings-privacy-host';body.append(host);let finishRead,finishWrite;const calls=[];
 const doc={body,head,documentElement:root,activeElement:null,createElement:make,createElementNS:(_ns,tag)=>make(tag),getElementById:id=>nodes.find(n=>n.id===id)||null,querySelector:()=>null,querySelectorAll:()=>[]};root.lang='en';
 const values={document:doc,navigator:{storage:{}},MutationObserver:class{observe(){}},chrome:{runtime:{getURL:path=>path,onMessage:{addListener(){}},sendMessage:message=>{calls.push(message);return new Promise(resolve=>{if(message.type==='GET_PAGE')finishRead=resolve;else if(message.type==='UPDATE_PREFERENCES')finishWrite=resolve;else throw Error('unexpected command');});}},storage:{onChanged:{addListener(){}}}}};
 for(const [key,value]of Object.entries(values))Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});
 try{const {installR6Settings,refreshR6Settings}=await import('../ui/r6-settings.js?pill-owner');installR6Settings();const input=doc.getElementById('r6-hide-content-previews');assert.ok(input);assert.equal(root.classList.contains('paia-hide-content-previews'),true);assert.equal(input.disabled,true);assert.equal(input.getAttribute('role'),'switch');assert.equal(input.getAttribute('aria-labelledby'),'r6-preview-name');assert.equal(nodes.filter(n=>n.tagName==='INPUT').length,1);const label=nodes.find(n=>n.tagName==='LABEL');assert.equal(label.contains(input),true);assert.equal(label.contains(doc.getElementById('r6-preview-description')),true);assert.equal(nodes.find(n=>n.className==='ux-preview-pill').getAttribute('aria-hidden'),'true');
 finishRead({ok:false,error:'STORAGE_FAILED'});await tick();assert.equal(input.dataset.loaded,'error','failed read is not an endless loading state');assert.equal(input.disabled,true);assert.equal(root.classList.contains('paia-hide-content-previews'),true);assert.match(doc.getElementById('r6-preview-status').textContent,/Could not refresh/);const retry=refreshR6Settings();finishRead({ok:true,data:{preferences:{hideContentPreviews:true}}});await retry;assert.equal(doc.getElementById('r6-preview-status').textContent,'');assert.equal(input.disabled,false);assert.equal(input.dataset.loaded,'true');doc.activeElement=input;input.checked=false;input.listeners.get('change')();assert.equal(input.checked,true,'pending switch retains confirmed value');assert.equal(root.classList.contains('paia-hide-content-previews'),true);assert.deepEqual(calls.at(-1),{type:'UPDATE_PREFERENCES',changes:{hideContentPreviews:false}});finishWrite({ok:true,data:{ok:true}});await tick();assert.equal(input.checked,false);assert.equal(root.classList.contains('paia-hide-content-previews'),false);assert.equal(doc.getElementById('r6-hide-content-previews'),input);assert.equal(doc.activeElement,input);assert.equal(nodes.filter(n=>n.tagName==='INPUT').length,1);
 const staleRead=refreshR6Settings();finishRead({ok:false,error:'STORAGE_FAILED'});await staleRead;assert.match(doc.getElementById('r6-preview-status').textContent,/Could not refresh/);
 input.checked=true;input.listeners.get('change')();await refreshR6Settings();finishWrite({ok:false,error:'STORAGE_FAILED'});await tick();finishRead({ok:true,data:{preferences:{hideContentPreviews:false}}});await tick();assert.match(doc.getElementById('r6-preview-status').textContent,/Save was not confirmed/);finishRead({ok:true,data:{preferences:{hideContentPreviews:false}}});await tick();assert.match(doc.getElementById('r6-preview-status').textContent,/Save was not confirmed.*Retry/,'a queued successful refresh cannot erase a newer write failure');assert.equal(input.checked,false);assert.equal(root.classList.contains('paia-hide-content-previews'),false);
 }finally{for(const [key,value]of prior)if(value)Object.defineProperty(globalThis,key,value);else delete globalThis[key];}
});
