import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {IAStore} from '../core/ia-store.js';import {SmartFilterStore} from '../core/smart-filter-store.js';import {FilterRunner} from '../core/filter-runner.js';
globalThis.IDBKeyRange=IDBKeyRange;
const presence={version:1,attachment:'absent',reference:'absent',confidence:'verified'};
function local(){let d={};return {async get(k){return {[k]:structuredClone(d[k])};},async set(v){Object.assign(d,structuredClone(v));}};}
async function setup(Type=SmartFilterStore){const storage=local(),indexedDB=new IDBFactory(),s=new Type(storage,{indexedDB});await s.consent(true);return {storage,indexedDB,s};}
async function add(s,text='继续',id='synthetic-source-1',extra={}){return s.capture({epoch:(await s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'synthetic-diag-chat',url:'https://chatgpt.com/c/synthetic-diag-chat',title:'SYNTHETIC_PRIVATE_TITLE'},messages:[{sourceMessageId:id,pageOrder:1,originalText:text,presence,...extra}]});}
const drain=s=>new FilterRunner(s).wake();
const fields=['active','checked','pending','keep','filter','uncertain','userProtected','failed','mode','filterRatio','filterVersion','policyVersion','classifierVersion','lastCheckedAt','taskState','reasonCounts','uncertainReasonCounts','reasonTaxonomyVersion','previousReasonState','previousReasonPolicyVersion','previousUncertainReasonCounts'].sort();
async function records(s){return s.repository.transaction(false,t=>t.all('filterInputs'));}
test('v060 Light migration queues every unexamined historical input without inventing metadata',async()=>{
 const {s:old,storage,indexedDB}=await setup(IAStore);await add(old);const before=await old.snapshot();await old.repository.close();const s=new SmartFilterStore(storage,{indexedDB});assert.equal((await s.filterStatus()).pending,1);assert.equal((await s.filterDiagnostics()).pending,1);await drain(s);const d=await s.filterDiagnostics();assert.equal(d.checked,1);assert.equal(d.uncertain,0);assert.equal(d.filter,1);assert.equal(d.pending,0);for(const key of ['records','library','sourceTimes','tombstones'])assert.deepEqual((await s.snapshot())[key],before[key]);
});
test('v061 bad done flag is repaired once and failed work resumes across worker recreation',async()=>{
 const {s,storage,indexedDB}=await setup();await add(s);await s.repository.transaction(true,async t=>{const meta=await t.get('meta','smart-filter');delete meta.diagnosticsVersion;await t.put('meta',meta);const row=(await t.all('filterInputs'))[0];row.pendingKey=1;row.authorship='legacy_unknown';row.presence=null;await t.put('filterInputs',row);});await s.repository.close();const next=new SmartFilterStore(storage,{indexedDB});assert.equal((await next.filterStatus()).pending,1);
 const original=next.evaluateFilters.bind(next);next.evaluateFilters=async()=>{throw Error('SYNTHETIC_PRIVATE_EXCEPTION');};await drain(next);let d=await next.filterDiagnostics();assert.equal(d.failed,1);assert.equal(d.pending,1);assert.equal(d.taskState,'failed');assert.ok(!JSON.stringify(d).includes('PRIVATE'));next.evaluateFilters=original;await next.repository.close();const reopen=new SmartFilterStore(storage,{indexedDB});await drain(reopen);d=await reopen.filterDiagnostics();assert.equal(d.pending,0);assert.equal(d.failed,0);assert.equal(d.taskState,'idle');
});
test('aggregate partitions match active decision records and exclude removed inputs',async()=>{
 const {s}=await setup();await add(s);await add(s,'SYNTHETIC_PRIVATE_BODY','synthetic-2');await add(s,'继续','synthetic-3',{presence:{...presence,attachment:'present'}});await add(s,'继续','synthetic-4');await add(s,'继续','synthetic-5');const blocks=(await s.snapshot()).library.blocks;await s.protectUserInput(blocks[3].id);await s.excludeLibrary(blocks[4].id,true);await drain(s);const d=await s.filterDiagnostics();assert.deepEqual({active:d.active,checked:d.checked,pending:d.pending,keep:d.keep,filter:d.filter,uncertain:d.uncertain,userProtected:d.userProtected,failed:d.failed},{active:4,checked:4,pending:0,keep:2,filter:1,uncertain:1,userProtected:1,failed:0});assert.equal(d.filterRatio,0.25);assert.deepEqual(Object.keys(d).sort(),fields);assert.ok(Object.values(d).every(v=>typeof v==='number'||['light','idle','deterministic-light-2','available','not_captured'].includes(v)||v&&typeof v==='object'&&Object.values(v).every(Number.isSafeInteger)));assert.equal((await s.recentFiltered()).items.length,d.filter);
});
test('Off pauses without clearing decisions; Light and recovery reuse valid cached rows',async()=>{
 const {s}=await setup();await add(s);await drain(s);const before=await records(s);await s.setFilterMode('off');await drain(s);assert.equal((await s.filterDiagnostics()).taskState,'paused');assert.equal((await s.filterDiagnostics()).filter,1);await s.setFilterMode('light');await s.recoverFilters();await drain(s);assert.deepEqual(await records(s),before);assert.equal((await s.filterDiagnostics()).filter,1);
});
test('bounded runner drains more than four batches without another external request and yields for capture',async()=>{
 const {s}=await setup();for(let n=0;n<211;n++)await add(s,'继续','synthetic-many-'+n);let yields=0;const runner=new FilterRunner(s,{yieldBatch:async()=>{if(++yields===1)await add(s,'SYNTHETIC_CAPTURE_DURING_WORK','synthetic-concurrent');}});await runner.wake();const d=await s.filterDiagnostics();assert.equal(d.checked,212);assert.equal(d.pending,0);assert.equal(d.filter,211);assert.ok(yields>=5);
});
test('diagnostics uses bounded transactions and does not export source bodies or identity fields',async()=>{
 const {s}=await setup();await add(s,'SYNTHETIC_SECRET_BODY');await drain(s);const original=s.repository.transaction.bind(s.repository);let pages=0;s.repository.transaction=(write,fn)=>original(write,async t=>{const get=t.get.bind(t),all=t.all.bind(t),page=t.page.bind(t);t.get=(store,...args)=>{assert.notEqual(store,'records');return get(store,...args);};t.all=(store,...args)=>{assert.notEqual(store,'records');return all(store,...args);};t.page=(store,options)=>{if(store==='blockIndex'){assert.ok(options.limit<=100);pages++;}return page(store,options);};return fn(t);});const d=await s.filterDiagnostics();assert.ok(pages);assert.deepEqual(Object.keys(d).sort(),fields);for(const forbidden of ['SYNTHETIC','sourceId','title','url','hash','messageId','originalText'])assert.ok(!JSON.stringify(d).includes(forbidden));
});
test('presence reader and provider permissions remain explicitly bounded',async()=>{
 const source=await readFile('adapter/input-presence.js','utf8');
 for(const forbidden of ['.textContent','.innerText','.getAttribute(','.href','.src','localStorage','sessionStorage','fetch(','XMLHttpRequest','chrome.'])assert.equal(source.includes(forbidden),false,forbidden);
 assert.match(source,/if\(\+\+count>256\)return unknown\(\)/);assert.match(source,/attachment:'present',reference:'unknown'/);assert.match(source,/attachment:'unknown',reference:'present'/);
 const manifest=JSON.parse(await readFile('manifest.json','utf8'));assert.deepEqual(manifest.permissions,['storage']);assert.deepEqual(manifest.host_permissions,['https://api.deepseek.com/*']);assert.equal(manifest.incognito,'not_allowed');assert.equal(manifest.content_security_policy.extension_pages,"default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'none'; connect-src https://api.deepseek.com; object-src 'none'; base-uri 'none'; form-action 'none'; frame-src 'none'");assert.equal(manifest.content_scripts.length,3);for(const script of manifest.content_scripts)assert.deepEqual(script.matches,['https://chatgpt.com/*']);assert.deepEqual(manifest.content_scripts.map(x=>x.world),['ISOLATED','MAIN','ISOLATED']);
});
test('recovery repairs missing and stale rows while protected inputs stay visible',async()=>{
 const {s}=await setup();await add(s);await add(s,'继续','synthetic-missing');await add(s,'继续','synthetic-protected');const [a,b,c]=(await s.snapshot()).library.blocks;await drain(s);await s.updateLibrary(c.id,{libraryText:'Synthetic authored constraint'});await s.repository.transaction(true,async t=>{await t.delete('filterInputs',b.id);const row=await t.get('filterInputs',a.id);row.basedOnContentRevision=-1;await t.put('filterInputs',row);});assert.equal((await s.filterDiagnostics()).pending,2);await s.recoverFilters();await drain(s);const d=await s.filterDiagnostics();assert.equal(d.pending,0);assert.equal(d.userProtected,1);assert.equal(d.filter,2);assert.equal(d.uncertain,0);assert.equal((await s.page({documentId:c.documentId})).pageItemIds.includes(c.id),true);
});
test('worker recreation clears a completed but interrupted running marker',async()=>{const {s}=await setup();await s.setFilterTask('running');await drain(s);assert.equal((await s.filterDiagnostics()).taskState,'idle');});
test('capture arriving during runner shutdown requests another pass instead of stranding the queue',async()=>{
 const {s}=await setup();await add(s);const original=s.setFilterTask.bind(s);let raced=false;const runner=new FilterRunner(s);s.setFilterTask=async state=>{if(state==='idle'&&!raced){raced=true;await add(s,'继续','synthetic-shutdown-capture');void runner.wake();}return original(state);};await runner.wake();for(let n=0;n<10;n++){await new Promise(setImmediate);if(runner.running)await runner.running;else break;}const d=await s.filterDiagnostics();assert.equal(d.checked,2);assert.equal(d.pending,0);
});
test('reason taxonomy counters are anonymous, exhaustive and follow re-evaluation rather than relabeling old decisions',async()=>{
 const {s,storage,indexedDB}=await setup();for(const [n,text]of ['继续','可以','这个呢','继续，但不要修改原始数据','嗯','unknown wording','続けて'].entries())await add(s,text,'synthetic-reason-'+n);await drain(s);let d=await s.filterDiagnostics();assert.equal(Object.values(d.reasonCounts).reduce((a,b)=>a+b,0),d.checked);assert.equal(Object.values(d.uncertainReasonCounts).reduce((a,b)=>a+b,0),d.uncertain);assert.equal(d.reasonCounts.ambiguous_ack,1);assert.equal(d.reasonCounts.reference_possible,1);assert.equal(d.reasonCounts.substantive_content,1);assert.equal(d.uncertainReasonCounts.context_insufficient,1);assert.equal(d.uncertainReasonCounts.rule_no_match,1);assert.equal(d.uncertainReasonCounts.unsupported_expression,1);
 await s.repository.transaction(true,async t=>{const m=await t.get('meta','smart-filter');m.policyVersion=1;m.classifierVersion='deterministic-light-1';await t.put('meta',m);for(const row of await t.all('filterInputs')){row.policyVersion=1;row.classifierVersion='deterministic-light-1';row.authorship='legacy_unknown';row.presence=null;row.decision='uncertain';row.reasonCode='metadata_unknown';delete row.filteredKey;await t.put('filterInputs',row);}});await s.repository.close();const next=new SmartFilterStore(storage,{indexedDB});const pending=await next.filterDiagnostics();assert.equal(pending.pending,7);assert.equal(pending.previousUncertainReasonCounts.metadata_unknown,7);assert.equal(pending.previousReasonPolicyVersion,1);assert.equal(pending.previousReasonState,'available');await drain(next);d=await next.filterDiagnostics();assert.equal(d.filter,1);assert.equal(d.reasonCounts.metadata_unknown,0);assert.equal(d.reasonCounts.ambiguous_ack,1);
 await next.repository.transaction(true,async t=>{const row=(await t.all('filterInputs')).find(r=>r.decision==='uncertain');row.reasonCode='SYNTHETIC_PRIVATE_REASON';await t.put('filterInputs',row);});d=await next.filterDiagnostics();assert.ok(!JSON.stringify(d).includes('SYNTHETIC_PRIVATE'));assert.equal(d.uncertainReasonCounts.other,1);
});
test('malformed presence is distinguishable from ordinary historical unknown and fails visible',async()=>{
 const {s}=await setup();await add(s,'继续','synthetic-invalid-presence',{presence:{version:1,attachment:'present',reference:'absent',confidence:'verified',extra:'invalid'}});await drain(s);const d=await s.filterDiagnostics();assert.equal(d.filter,0);assert.equal(d.uncertainReasonCounts.metadata_unknown,1);assert.equal((await s.recentFiltered()).items.length,0);
});
