import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {IAStore} from '../core/ia-store.js';
import {SmartFilterStore} from '../core/smart-filter-store.js';
globalThis.IDBKeyRange=IDBKeyRange;
const presence={version:1,attachment:'absent',reference:'absent',confidence:'verified'};
function local(){let d={};return {async get(k){return {[k]:structuredClone(d[k])};},async set(v){Object.assign(d,structuredClone(v));}};}
async function add(s,text='继续',id='synthetic-filter-001',extra={}){return s.capture({epoch:(await s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'synthetic-filter-chat',url:'https://chatgpt.com/c/synthetic-filter-chat',title:'Synthetic filter conversation'},messages:[{sourceMessageId:id,pageOrder:1,originalText:text,presence,...extra}]});}
async function setup(){const storage=local(),indexedDB=new IDBFactory(),s=new SmartFilterStore(storage,{indexedDB});await s.consent(true);return {storage,indexedDB,s};}
test('new Input filters without altering source, text, time, revisions; full search/context remains available',async()=>{
 const {s}=await setup();await add(s);const before=await s.snapshot(),b=before.library.blocks[0];await s.evaluateFilters();const state=await s.filterStatus();assert.equal(state.mode,'light');assert.equal((await s.page({documentId:b.documentId})).pageItemIds.length,0);assert.deepEqual((await s.searchInputs({query:'继续'})).items.map(x=>x.id),[b.id]);assert.equal((await s.searchInputs({query:'继续'})).items[0].filtered,true);assert.equal((await s.page({documentId:b.documentId,contextInputId:b.id})).pageItemIds.length,1);assert.deepEqual((await s.snapshot()).records,before.records);assert.deepEqual((await s.snapshot()).library,before.library);assert.equal((await s.recentFiltered()).items.length,1);
 await s.setFilterMode('off');assert.equal((await s.page({documentId:b.documentId})).pageItemIds.length,1);await s.setFilterMode('light');assert.equal((await s.page({documentId:b.documentId})).pageItemIds.length,0);
});
test('keep latch survives re-evaluation, edit undo and removal undo, never revives tombstones',async()=>{
 const {s}=await setup();await add(s);let b=(await s.snapshot()).library.blocks[0];await s.evaluateFilters();await s.keepInput(b.id);await s.evaluateFilters();assert.equal((await s.recentFiltered()).items.length,0);await s.excludeLibrary(b.id,true);assert.equal((await s.searchInputs({query:'继续'})).items.length,0);await s.excludeLibrary(b.id,false);assert.equal((await s.page({documentId:b.documentId})).pageItemIds.length,1);
 await s.permanentDelete(b.sourceRecordId);await add(s);assert.equal((await s.snapshot()).records.length,0);assert.equal((await s.recentFiltered()).items.length,0);await assert.rejects(s.keepInput(b.id));
});
test('v060 migration is lossless, legacy is retained, onboarding is once and new install is silent',async()=>{
 const storage=local(),indexedDB=new IDBFactory(),old=new IAStore(storage,{indexedDB});await old.consent(true);await add(old);const before=await old.snapshot();await old.repository.close();const s=new SmartFilterStore(storage,{indexedDB});const after=await s.snapshot();for(const k of ['records','library','settings','preferences','tombstones','sourceTimes'])assert.deepEqual(after[k],before[k]);await s.evaluateFilters();assert.equal((await s.page({documentId:after.conversations[0].id})).pageItemIds.length,0);assert.equal((await s.takeFilterNotice()).show,true);assert.equal((await s.takeFilterNotice()).show,false);const fresh=await setup();assert.equal((await fresh.s.takeFilterNotice()).show,false);
});
test('reading boundary pins visibility and late decision never removes already visible text',async()=>{
 const {s}=await setup();await add(s);const b=(await s.snapshot()).library.blocks[0],first=await s.page({documentId:b.documentId});assert.equal(first.pageItemIds.length,1);await s.evaluateFilters();assert.equal((await s.page({documentId:b.documentId,readingSnapshot:first.readingSnapshot})).pageItemIds.length,1);assert.equal((await s.page({documentId:b.documentId})).pageItemIds.length,0);
});
test('Input edit and undo permanently protect original text; same source snapshots inherit keep',async()=>{
 const {s}=await setup();await add(s);let b=(await s.snapshot()).library.blocks[0];await s.updateLibrary(b.id,{libraryText:'Synthetic authored'});await s.updateLibrary(b.id,{libraryText:null});await s.evaluateFilters();assert.equal((await s.recentFiltered()).items.length,0);assert.equal((await s.snapshot()).library.blocks[0].libraryText,null);await add(s,'请继续');await s.evaluateFilters();assert.equal((await s.recentFiltered()).items.length,0);assert.equal((await s.page({documentId:b.documentId})).pageItemIds.length,2);
});
test('late evaluation, mode changes, purge and optional queue failures fail visible',async()=>{
 const {s}=await setup();await add(s);const b=(await s.snapshot()).library.blocks[0];let used=false;s.repository.checkpoint=async name=>{if(name==='filter-evaluated'&&!used){used=true;await s.keepInput(b.id);}};await s.evaluateFilters();assert.equal((await s.recentFiltered()).items.length,0);
 const {s:other}=await setup();const originalWrite=other.write.bind(other);other.write=()=>Promise.reject(Error('SYNTHETIC_QUEUE_FAILURE'));await add(other);other.write=originalWrite;assert.equal((await other.snapshot()).records.length,1);assert.equal((await other.recentFiltered()).items.length,0);
 const third=await setup();await add(third.s);third.s.repository.checkpoint=async name=>{if(name==='filter-evaluated')await third.s.setFilterMode('off');};assert.equal((await third.s.evaluateFilters()).processed,0);
});
test('migration interruption resumes without rewriting legacy/import/source data or duplicating notice',async()=>{
 const storage=local(),indexedDB=new IDBFactory(),old=new IAStore(storage,{indexedDB});await old.consent(true);await add(old,'Synthetic legacy');const b=(await old.snapshot()).library.blocks[0];await old.excludeLibrary(b.id,true);const stores=['records','times','tombstones','inputRemovals','importTasks','importBatches','importEvidence','importSources','revisions'];await old.repository.transaction(true,async t=>{for(const name of stores.filter(x=>x.startsWith('import')))await t.put(name,{id:'synthetic-'+name,sourceKey:'a'.repeat(64),status:'paused',checkpoint:7});});const before=await old.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(stores.map(async n=>[n,await t.all(n)]))));await old.repository.close();let crash=true;
 const interrupted=new SmartFilterStore(storage,{indexedDB,checkpoint:async name=>{if(name==='filter-migration-batch'&&crash){crash=false;throw Error('SYNTHETIC_CRASH');}}});await assert.rejects(interrupted.snapshot());await interrupted.repository.close();const s=new SmartFilterStore(storage,{indexedDB});await s.snapshot();const after=await s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(stores.map(async n=>[n,await t.all(n)]))));assert.deepEqual(after,before);assert.equal((await s.filterStatus()).phase,'active');assert.equal((await s.takeFilterNotice()).show,true);await s.repository.close();const reopen=new SmartFilterStore(storage,{indexedDB});assert.equal((await reopen.takeFilterNotice()).show,false);assert.equal((await reopen.searchInputs({query:'Synthetic'})).items.length,0);
});
test('cached decisions are reused on mode changes; version mismatch conservatively re-evaluates on reopen',async()=>{
 const {s,storage,indexedDB}=await setup();await add(s);await s.evaluateFilters();const before=await s.filterStatus();await s.setFilterMode('off');await s.setFilterMode('light');assert.equal((await s.evaluateFilters()).processed,0);assert.equal((await s.filterStatus()).decisionSequence,before.decisionSequence);
 await s.repository.transaction(true,async t=>{const state=await t.get('meta','smart-filter');state.classifierVersion='synthetic-old-version';await t.put('meta',state);const row=(await t.all('filterInputs'))[0];row.classifierVersion='synthetic-old-version';await t.put('filterInputs',row);});await s.repository.close();const next=new SmartFilterStore(storage,{indexedDB});const b=(await next.snapshot()).library.blocks[0];assert.equal((await next.page({documentId:b.documentId})).pageItemIds.length,1);assert.equal((await next.evaluateFilters()).processed,1);assert.equal((await next.recentFiltered()).items.length,1);
});
test('reference evidence cannot be erased and search pagination reaches filtered hits after first page',async()=>{
 const {s}=await setup();await add(s,'继续','synthetic-filter-001',{presence:{...presence,attachment:'present'}});await add(s);await s.evaluateFilters();assert.equal((await s.recentFiltered()).items.length,0);
 for(let i=0;i<105;i++)await add(s,'继续','synthetic-page-'+String(i).padStart(3,'0'));await s.evaluateFilters({limit:100});await s.evaluateFilters();let cursor=null,ids=[];do{const r=await s.searchInputs({query:'继续',cursor,limit:20});ids.push(...r.items.map(x=>x.id));cursor=r.nextCursor;}while(cursor!==null);assert.equal(new Set(ids).size,106);assert.equal(ids.length,106);
 const st=await s.snapshot(),b=st.library.blocks.at(-1),context=await s.page({documentId:b.documentId,contextInputId:b.id});assert.ok(context.pageItemIds.includes(b.id));
});
test('filter policy affects future candidate eligibility but never rewrites existing Thoughts',async()=>{
 const {s}=await setup();await add(s);const b=(await s.snapshot()).library.blocks[0],thought=await s.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic prior Thought'});await s.evaluateFilters();assert.equal((await s.inputEligibility(b.id)).eligible,false);assert.deepEqual(await s.thought(thought.id),thought);await s.keepInput(b.id);assert.equal((await s.inputEligibility(b.id)).eligible,true);await s.excludeLibrary(b.id,true);assert.equal((await s.inputEligibility(b.id,{contextOnly:true})).eligible,false);
});
test('context-only eligibility requires a visible anchor and at most two same-document neighbours',async()=>{
 const {s}=await setup();await add(s,'Synthetic informative anchor','synthetic-anchor');await add(s);await s.evaluateFilters();const [anchor,filtered]=(await s.snapshot()).library.blocks;
 assert.equal((await s.inputEligibility(filtered.id,{contextOnly:true})).eligible,false);assert.deepEqual(await s.inputEligibility(filtered.id,{contextOnly:true,anchorId:anchor.id}),{eligible:true,role:'context_only',contentRevision:0});await assert.rejects(s.createThought({provenanceType:'input_derived',inputRefs:[filtered.id],thoughtText:'Should not extract filtered target'}));await s.excludeLibrary(anchor.id,true);assert.equal((await s.inputEligibility(filtered.id,{contextOnly:true,anchorId:anchor.id})).eligible,false);
});
