import test from 'node:test';import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {inputDigest} from '../scripts/compatibility-gate.mjs';
import {FakeChatGPT,eventually,pause,conversation} from './harness/fake-chatgpt.mjs';

test('Smart Filter isolated Chrome: capture, Light reading, full search/context, keep, Off and no document controls',{timeout:90000},async()=>{
 const h=await FakeChatGPT.start();try{
  const p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();
  const c=conversation('smart-filter-chrome');c.messages=[{id:'synthetic-smart-001',text:'继续'},{id:'synthetic-smart-002',text:'继续，但不要修改原始数据'},{id:'synthetic-smart-003',text:'好的，就选第二个'},{id:'synthetic-smart-004',text:'请继续'},{id:'synthetic-smart-005',text:'这个呢'}];
  const chat=await h.open(c,{arrival:'empty'});await chat.evaluate(c=>{window.fake.render(c);for(const root of document.querySelectorAll('#messages > div')){const article=document.createElement('article');article.dataset.testid='conversation-turn-'+root.dataset.messageId;root.before(article);article.append(root);if(root.dataset.messageId==='synthetic-smart-005'){const image=document.createElement('span');image.dataset.testid='attachment-image';image.textContent='SYNTHETIC_ATTACHMENT_CONTENT_NOT_CAPTURED';article.append(image);}}},c);
  await eventually(async()=>(await h.state()).records.length===5);
  await eventually(async()=>(await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_RECENT'}))).data.items.length===2);
  const baseline=(await h.state()).records;assert.ok(baseline.every(r=>!r.originalText.includes('SYNTHETIC_ATTACHMENT')));
  await p.locator('.conversation-document').click();await eventually(async()=>await p.locator('.library-prose:visible').count()===3);assert.equal(await p.locator('#document-panel').getByText('智能过滤内容',{exact:true}).count(),0);assert.equal(await p.locator('#filter-onboarding:visible').count(),0);
  await p.locator('#back').click();await p.locator('#search').fill('请继续');await p.locator('.search-input').waitFor();assert.equal(await p.locator('.filter-search-label').textContent(),'智能过滤内容');await mkdir('work',{recursive:true});await p.screenshot({path:'work/smart-filter-search-synthetic.png',fullPage:true});await p.locator('.search-input').click();await eventually(async()=>(await p.locator('.library-prose').allTextContents()).includes('请继续'));
  assert.equal((await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_RECENT'}))).data.items.length,2);
  await p.locator('#back').click();await p.locator('#search').fill('');await p.locator('[data-view="settings"]').click();await p.locator('[name="smart-filter-mode"][value="light"]').waitFor();await eventually(async()=>await p.locator('[value="light"]').isChecked(),'Settings must render the persisted Light mode');assert.equal(await p.locator('[value="light"]').isChecked(),true);await p.locator('#filter-recent-open').click();await p.locator('.filter-recent-row').first().waitFor();await p.screenshot({path:'work/smart-filter-recent-synthetic.png',fullPage:true});await p.locator('.filter-recent-row').first().getByRole('button',{name:'恢复到 Input Archive'}).click();await eventually(async()=>(await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_RECENT'}))).data.items.length===1);await p.locator('#filter-recent-close').click();await p.locator('[value="off"]').check();await p.locator('[data-view="library"]').click();await p.locator('.conversation-document').click();await eventually(async()=>await p.locator('.library-prose:visible').count()===5);
  await p.locator('[data-view="settings"]').click();await p.locator('[value="light"]').check();await p.locator('[data-view="library"]').click();await p.locator('.conversation-document').click();await eventually(async()=>await p.locator('.library-prose:visible').count()===4);
  const fields=p.locator('.library-prose');await fields.first().fill('Synthetic protected edit');await eventually(async()=>(await h.state()).library.blocks.some(b=>b.libraryText==='Synthetic protected edit'));await fields.first().press(process.platform==='darwin'?'Meta+z':'Control+z');await eventually(async()=>!(await h.state()).library.blocks.some(b=>b.libraryText==='Synthetic protected edit'));
  await p.locator('.input-remove').first().click();await eventually(async()=>(await h.state()).library.blocks.some(b=>b.excluded));await p.locator('#notice').getByRole('button',{name:'撤销',exact:true}).click();await eventually(async()=>(await h.state()).library.blocks.every(b=>!b.excluded));assert.deepEqual((await h.state()).records,baseline);
  await mkdir('work',{recursive:true});await p.screenshot({path:'work/smart-filter-reading-synthetic.png',fullPage:true});await p.locator('[data-view="settings"]').click();await p.screenshot({path:'work/smart-filter-settings-synthetic.png',fullPage:true});
  await h.restartWorker();assert.equal((await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_RECENT'}))).data.items.length,1);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);await writeFile('work/smart-filter-ui-evidence.json',JSON.stringify({productVersion:await p.evaluate(()=>chrome.runtime.getManifest().version),scope:'isolated-synthetic',runtimeDigest:await inputDigest({runtimeOnly:true}),defaultLight:true,readingFilter:true,fullSearch:true,contextDoesNotKeep:true,restoreProtects:true,lightOff:true,editUndo:true,removalUndo:true,workerRestart:true,noDocumentFilterControls:true,sourceTimesUnchanged:true,networkRequests:0},null,2)+'\n');
 }finally{await h.close();}
});

test('presence evidence is bounded, body-free, attachment/reference-aware and unknown without complete scope',{timeout:60000},async()=>{
 const h=await FakeChatGPT.start();try{const p=await h.open(conversation('presence-synthetic'),{arrival:'empty'});
  const result=await p.evaluate(async source=>{
   // Synthetic page only: exercise packaged isolated-world helper with no private content.
   const script=document.createElement('script');script.textContent=source;document.head.append(script);
   const cases=[];for(const extra of ['', '<span data-testid="attachment-file">PRIVATE_SYNTHETIC_FILENAME</span>','<a href="https://example.invalid">PRIVATE_SYNTHETIC_URL</a>','<div data-message-author-role="assistant">NEVER_READ</div>','<div>'.repeat(260)+'</div>'.repeat(260),'<span>UNCLASSIFIED_SYNTHETIC_CONTENT</span>']){
    const article=document.createElement('article');article.dataset.testid='conversation-turn-presence';article.innerHTML='<div data-message-author-role="user"><div class="whitespace-pre-wrap">继续</div></div>'+extra;document.body.append(article);article.querySelectorAll=()=>{throw Error('SYNTHETIC_UNBOUNDED_ENUMERATION');};const root=article.firstElementChild;cases.push(globalThis.PAIAInputPresence.collect(root,root.firstElementChild));article.remove();
   }return cases;
  },await (await import('node:fs/promises')).readFile('adapter/input-presence.js','utf8'));
  assert.deepEqual(result[0],{version:1,attachment:'absent',reference:'absent',confidence:'verified'});assert.equal(result[1].attachment,'present');assert.equal(result[2].reference,'present');assert.equal(result[3].confidence,'unknown');assert.equal(result[4].confidence,'unknown');assert.equal(result[5].confidence,'unknown');assert.ok(!JSON.stringify(result).includes('PRIVATE'));
 }finally{await h.close();}
});

test('first input event protects even when immediate Undo leaves no changed text to autosave',{timeout:60000},async()=>{
 const h=await FakeChatGPT.start();try{const p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();const c=conversation('instant-undo-synthetic');c.messages=[{id:'instant-undo-source',text:'继续'}];const chat=await h.open(c,{arrival:'empty'});await chat.evaluate(c=>{window.fake.render(c);const root=document.querySelector('#messages > div'),article=document.createElement('article');article.dataset.testid='conversation-turn-0';root.before(article);article.append(root);},c);await eventually(async()=>(await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_RECENT'}))).data.items.length===1);
  const before=await h.state();await p.locator('[data-view="settings"]').click();await p.locator('[value="off"]').check();await p.locator('[data-view="library"]').click();await p.locator('.conversation-document').click();const field=p.locator('.library-prose');await field.fill('Synthetic brief edit');await field.press(process.platform==='darwin'?'Meta+z':'Control+z');await eventually(async()=>await field.textContent()==='继续');await eventually(async()=>(await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_RECENT'}))).data.items.length===0);await p.locator('[data-view="settings"]').click();await p.locator('[value="light"]').check();await p.locator('[data-view="library"]').click();await p.locator('.conversation-document').click();await field.waitFor();assert.equal(await field.textContent(),'继续');assert.deepEqual((await h.state()).records,before.records);assert.equal((await h.state()).library.blocks[0].libraryText,null);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
 }finally{await h.close();}
});
