import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,cp,rm,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {FakeChatGPT,conversation,eventually} from './harness/fake-chatgpt.mjs';import {inputDigest} from '../scripts/compatibility-gate.mjs';

const targetVersion=JSON.parse(await readFile('manifest.json','utf8')).version;
test('frozen v060 internal self-reload migrates isolated Chrome without resetting sources, history, removals or import checkpoints',{timeout:120000},async()=>{
 const parent=await mkdtemp(join(tmpdir(),'paia-smart-upgrade-')),old=join(parent,'old'),installed=join(parent,'installed'),next=join(parent,'next');let h;
 try{
  await mkdir(old);execFileSync('git',['archive','01a6350','-o',join(parent,'old.tar')]);execFileSync('tar',['-xf',join(parent,'old.tar'),'-C',old]);
  const build="import sys;sys.path.insert(0,'scripts');from build_internal import build_internal;build_internal(sys.argv[1],sys.argv[2])";
  execFileSync('/usr/bin/python3',['-c',build,old,installed]);execFileSync('/usr/bin/python3',['-c',build,process.cwd(),next]);
  h=await FakeChatGPT.start({extensionPath:installed});const manager=await h.context.newPage();await manager.goto('chrome://extensions');await manager.locator('#devMode').click();assert.equal(await manager.locator('#devMode').getAttribute('aria-pressed'),'true');await manager.close();let p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();const c=conversation('smart-upgrade-synthetic');await h.open(c);await eventually(async()=>(await h.state()).records.length===3);
  const original=await h.state(),[a,b,d]=original.library.blocks;
  await p.evaluate(async({a,b,d})=>{const send=async(type,rest)=>{const r=await chrome.runtime.sendMessage({type,...rest});if(!r.ok)throw Error('SYNTHETIC_SETUP_FAILED');return r;};await send('UPDATE_LIBRARY',{id:a.id,changes:{libraryText:'Synthetic retained edit',note:'Synthetic note'}});await send('UPDATE_DOCUMENT',{id:a.documentId,changes:{userTitle:'Synthetic retained title'}});await send('EXCLUDE_LIBRARY',{id:b.id,excluded:true});await send('PURGE_SOURCE',{id:d.sourceRecordId,confirm:true});await send('SET_ENABLED',{enabled:false});const {IAStore}=await import('../core/ia-store.js');const s=new IAStore(chrome.storage.local);await s.snapshot();await s.repository.transaction(true,async t=>{for(const name of ['importTasks','importBatches','importEvidence','importSources'])await t.put(name,{id:'synthetic-'+name,sourceKey:'a'.repeat(64),status:'paused',checkpoint:9});});await s.repository.close();},{a,b,d});
  const tables=['records','times','tombstones','blocks','documents','libraryDocuments','inputStates','inputRemovals','revisions','importTasks','importBatches','importEvidence','importSources'];
  const read=async module=>p.evaluate(async({module,tables})=>{const mod=await import('../core/'+module),S=mod.LibraryFoundationStore||mod.SmartFilterStore||mod.IAStore,s=new S(chrome.storage.local);const snapshot=await s.snapshot();const rows=await s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(tables.map(async name=>[name,await t.all(name)]))));await s.repository.close();return {rows,settings:snapshot.settings,preferences:snapshot.preferences};},{module,tables});
  const before=await read('ia-store.js'),identity=h.extensionId;await p.close();await cp(next,installed,{recursive:true});
  const popup=await h.context.newPage();await popup.goto(`chrome-extension://${identity}/ui/popup.html`);await popup.locator('#development-reload').click().catch(()=>{});p=await h.context.newPage();h.archive=p;p.on('pageerror',e=>h.errors.push(e.message));await eventually(async()=>{try{await p.goto(`chrome-extension://${identity}/ui/archive.html`);return await p.evaluate(()=>chrome.runtime.getManifest().version)===targetVersion;}catch{return false;}},'same-path v061 self reload');
  await p.locator('#filter-onboarding').waitFor({state:'visible'});assert.match(await p.locator('#filter-onboarding').textContent(),/已启用轻度智能过滤/);const after=await read('thought-store.js');assert.deepEqual(after,before);
  const marker=(await p.evaluate(()=>chrome.runtime.sendMessage({type:'FILTER_STATUS'}))).data;assert.equal(marker.phase,'active');assert.equal(marker.migrationVersion,1);assert.equal(marker.verified,true);assert.equal(marker.noticePending,false);assert.equal(marker.mode,'light');
  assert.equal(await p.evaluate(()=>chrome.runtime.id),identity);assert.equal(await p.evaluate(async()=>{const dbs=await indexedDB.databases();return dbs.find(d=>d.name==='paia-archive').version;}),5);
  await p.reload();await p.locator('.conversation-document').waitFor();assert.equal(await p.locator('#filter-onboarding:visible').count(),0);await p.locator('.conversation-document').click();await p.locator('.library-prose').waitFor();assert.equal(await p.locator('.library-prose:visible').count(),1);assert.equal(await p.locator('.library-prose').textContent(),'Synthetic retained edit');
  await p.evaluate(()=>chrome.runtime.sendMessage({type:'SET_ENABLED',enabled:true}));const fresh=conversation('smart-upgrade-new-synthetic');await h.open(fresh);await eventually(async()=>(await h.state()).records.length===5);const actual=await h.state();for(const r of before.rows.records)assert.deepEqual(actual.records.find(x=>x.id===r.id),r.value);assert.deepEqual(actual.tombstones,before.rows.tombstones.map(x=>x.value));assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  await mkdir('work',{recursive:true});await writeFile('work/smart-filter-migration-evidence.json',JSON.stringify({productVersion:targetVersion,scope:'isolated-synthetic',runtimeDigest:await inputDigest({runtimeOnly:true}),sameExtensionId:true,selfReload:true,physicalSchema:5,controlSchema:6,marker,sourceTimeAndHistoryFieldEquality:true,removalsAndTombstonesPreserved:true,historyCompletionPreserved:true,onboardingOnce:true,captureAfterUpgrade:true,networkRequests:0},null,2)+'\n');
 }finally{await h?.close();await rm(parent,{recursive:true,force:true});}
});
