import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {local,capture,inputEdit} from './harness/thought-m1.mjs';
import {LibraryDocumentsStore} from '../core/library-documents-store.js';
import {BrowserNativeSyncCore} from '../core/browser-native-sync/core.js';
import {SourceBootstrapJournal} from '../core/browser-native-sync/source-bootstrap-journal.js';
import {FilterIntentSyncJournal} from '../core/browser-native-sync/filter-intent-journal.js';
import {InputWorkingSyncJournal} from '../core/browser-native-sync/input-working-journal.js';
import {buildCheckpoint,StagedSyncRestore} from '../core/browser-native-sync/checkpoints.js';
import {prepareCurrentSourceWorkingGroupCheckpointPlan} from '../core/browser-native-sync/group-checkpoint-plan.js';
import {prepareGroupScope,requireGroupScope} from '../core/browser-native-sync/group-checkpoint-scope.js';
import {assertSourceWorkingDefaultMeta,assertSourceWorkingRestoredDefaultMeta} from '../core/browser-native-sync/source-working-default-meta.js';
import {equalSourceWorkingPhysicalTree} from '../core/browser-native-sync/source-working-physical.js';
globalThis.IDBKeyRange=IDBKeyRange;
const freeze=value=>{if(value&&typeof value==='object'){for(const item of Object.values(value))freeze(item);Object.freeze(value);}return value;};
const all=x=>x.s.repository.transaction(false,async t=>{const rows={};for(const name of x.s.repository.stores)rows[name]=await t.all(name);return rows;});
async function fresh(device){const s=new LibraryDocumentsStore(local(),{indexedDB:new IDBFactory(),clock:()=> '2026-10-10T00:00:00.000Z'});await s.consent(true);await s.finishFoundation();return {s,core:new BrowserNativeSyncCore(s.repository,{datasetId:'SYNTHETIC_source_successor',deviceId:device})};}
function bind(x){x.s.sourceBootstrapJournal=new SourceBootstrapJournal(x.core);x.s.filterIntentJournal=new FilterIntentSyncJournal(x.core);x.s.inputWorkingJournal=new InputWorkingSyncJournal(x.core,{filterJournal:x.s.filterIntentJournal,logicalCommits:true});}
async function view(x){const operations=[];for await(const row of x.core.rows('revision'))operations.push(row.operation);const plan=await prepareCurrentSourceWorkingGroupCheckpointPlan(x.core,operations),scope=await prepareGroupScope(plan);return {plan,scope,rows:freeze(await all(x)),control:freeze(structuredClone(x.s.controlCache)),databaseId:x.s.databaseId};}
const qualify=(x,v)=>assertSourceWorkingRestoredDefaultMeta(x.core,v.scope,v.plan,v.rows,v.control,v.databaseId);
async function fixture(){let a,b;const objects=new Map(),transport={async putImmutable(ref,bytes){if(objects.has(ref.id))assert.deepEqual(objects.get(ref.id),bytes);objects.set(ref.id,bytes.slice());},async get(ref){assert.ok(objects.has(ref.id));return objects.get(ref.id).slice();}};try{a=await fresh('SYNTHETIC_A');bind(a);await a.s.capture(capture((await a.s.status()).epoch));const input=(await a.s.snapshot()).library.blocks[0].id;await inputEdit(a.s,input,{libraryText:'SYNTHETIC A Working 中文🙂',note:'SYNTHETIC first'});const initial=await view(a);assertSourceWorkingDefaultMeta(a.core,initial.scope,initial.plan,initial.rows,initial.control,initial.databaseId);const cp=await buildCheckpoint(a.core,transport,{grouped:{store:a.s}});await a.s.repository.close();a=null;b=await fresh('SYNTHETIC_B');const restore=new StagedSyncRestore(b.core,{grouped:{store:b.s}});await restore.stageCheckpoint(cp.ref,ref=>transport.get(ref));await restore.activate();const uncleaned=await view(b);let clean;do{clean=await restore.cleanup({limit:3});assert.ok(clean.deleted<=3);}while(!clean.complete);await b.s.repository.transaction(false,t=>requireGroupScope(b.s,t,initial.scope));bind(b);return {b,input,transport,uncleaned,restore,async close(){await b.s.repository.close();}};}catch(e){await a?.s.repository.close();await b?.s.repository.close();throw e;}}

test('original cleaned restored Source/Working cut admits truthful local counters without imported UI receipts',async()=>{const f=await fixture();try{const v=await view(f.b);assert.equal(v.rows.operationReceipts.length,0);assert.equal(v.rows.invalidations.length,1);assert.equal(v.rows.meta.find(r=>r.id==='aiu:delta:sequence').value,1);assert.throws(()=>assertSourceWorkingDefaultMeta(f.b.core,v.scope,v.plan,v.rows,v.control,v.databaseId),{code:'BNS_GROUP_CANONICAL_UNREPRESENTED'});await qualify(f.b,v);assert.equal(Object.keys(v.rows).length,37);assert.equal(equalSourceWorkingPhysicalTree(await all(f.b),v.rows),true);}finally{await f.close();}});

test('genuine restored second Working journal edit and fresh third restore preserve complete original portable scope',async()=>{const f=await fixture();let c;try{await inputEdit(f.b.s,f.input,{libraryText:'SYNTHETIC B Working 中文🙂',note:'SYNTHETIC second'});const v=await view(f.b);assert.equal(v.rows.operationReceipts.length,1);assert.equal(v.rows.invalidations.length,2);assert.equal(v.rows.meta.find(r=>r.id==='input-delta-sequence').value,3);assert.equal(v.rows.meta.find(r=>r.id==='aiu:delta:sequence').value,2);await qualify(f.b,v);const cp=await buildCheckpoint(f.b.core,f.transport,{grouped:{store:f.b.s}});await f.b.s.repository.close();c=await fresh('SYNTHETIC_C');const restore=new StagedSyncRestore(c.core,{grouped:{store:c.s}});await restore.stageCheckpoint(cp.ref,ref=>f.transport.get(ref));await restore.activate();let clean;do{clean=await restore.cleanup({limit:3});}while(!clean.complete);await c.s.repository.transaction(false,t=>requireGroupScope(c.s,t,v.scope));bind(c);const restored=await view(c);assert.equal(restored.rows.operationReceipts.length,0);assert.equal(restored.rows.invalidations.length,2);assert.equal(restored.rows.meta.find(r=>r.id==='aiu:delta:sequence').value,1);await qualify(c,restored);assert.equal((await c.s.input(f.input)).libraryText,'SYNTHETIC B Working 中文🙂');assert.equal((await c.s.input(f.input)).note,'SYNTHETIC second');}finally{await c?.s.repository.close();await f.close();}});

test('restored qualification refuses uncleaned control and complete-inventory/protocol/counter tampering',async()=>{const f=await fixture();try{await assert.rejects(qualify(f.b,f.uncleaned));const v=await view(f.b),before=await all(f.b);for(const change of [r=>r.meta.find(x=>x.id.endsWith(':restore:')).cleanup.complete=false,r=>r.meta.find(x=>x.id.endsWith(':restore:')).manifest.parents=['f'.repeat(64)],r=>r.meta.find(x=>x.id.endsWith(':restore:')).extra=true,r=>r.meta.find(x=>x.id.endsWith(':restore:')).graphDigest='a'.repeat(64),r=>r.meta.push({id:'bns:v1:SYNTHETIC_other:generation:initial:unknown:',value:true}),r=>r.meta.push({id:'SYNTHETIC unknown local',value:true}),r=>r.meta.splice(r.meta.findIndex(x=>x.id.includes(':receipt:')),1),r=>r.meta.find(x=>x.id==='aiu:delta:sequence').value++,r=>r.meta.find(x=>x.id.startsWith('aiu:delta:known:')).sequence++,r=>r.operationReceipts.push({id:'SYNTHETIC forged imported retry'}),r=>r.invalidations.pop()]){const rows=structuredClone(v.rows);change(rows);await assert.rejects(qualify(f.b,{...v,rows:freeze(rows)}));}assert.equal(equalSourceWorkingPhysicalTree(await all(f.b),before),true);}finally{await f.close();}});
