import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {FakeChatGPT} from './harness/fake-chatgpt.mjs';

test('real IndexedDB 1k/10k/100k: bounded page/edit/capture, durable counts, search and no local bodies', {timeout:900000},async()=>{
 const h=await FakeChatGPT.start();const reports=[];
 try{for(const size of [1000,10000,100000]){
  const result=await h.archive.evaluate(async size=>{
   const {IndexedArchiveStore}=await import('../core/indexed-store.js');const {recordIndex,blockIndex,sourceCount}=await import('../core/idb-repository.js');
   let values={};const local={async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}};
   const s=new IndexedArchiveStore(local,{name:'paia-performance-'+size});await s.consent(true);const status=await s.status();
   await s.capture({epoch:status.epoch,adapterVersion:'0.3.0',chat:{id:'perf-template',url:'https://chatgpt.com/c/perf-template',title:'Synthetic template'},messages:[{sourceMessageId:'perf-template-msg',pageOrder:1,originalText:'Synthetic template'}]});
   const template=await s.snapshot(),r0=template.records[0],b0=template.library.blocks[0],d0=template.conversations[0];
   await s.repository.transaction(true,async t=>{for(const name of ['records','recordIndex','blocks','blockIndex','documents','libraryDocuments','sourceCounts'])for(const key of await t.keys(name))await t.delete(name,key);});
   const began=performance.now();
   for(let start=0;start<size;start+=1000){await s.repository.transaction(true,async t=>{
    const pending=[];for(let i=start;i<Math.min(start+1000,size);i++){
     const group=Math.floor(i/200),chatId='perf-chat-'+group,docId='document:perf-'+group,id='perf-record-'+String(i).padStart(8,'0'),sourceKey=i.toString(16).padStart(64,'0');
     const r={...r0,id,chatId,chatUrl:'https://chatgpt.com/c/'+chatId,chatTitle:'Synthetic performance '+group,sourceMessageId:'perf-message-'+i,sourceKey,dedupeKey:sourceKey,originalText:'Synthetic performance input '+i+' '+('x'.repeat(i%100===0?10000:180)),sourceSentAt:new Date(1609459200000+i*1000).toISOString(),timeSource:'chatgpt_response_create_time',timeConfidence:'high',pageOrder:i%200+1,conversationOrder:i%200+1};
     const b={...b0,id:'block:'+id,documentId:docId,sourceRecordId:id,originalTextReference:id,provenance:[{sourceRecordId:id}],provenanceSignature:JSON.stringify([{sourceRecordId:id}])};
     pending.push(t.put('records',{id,value:r}),t.put('recordIndex',recordIndex(r,i)),t.put('blocks',{id:b.id,value:b}),t.put('blockIndex',blockIndex(b,i,[r])),t.put('sourceCounts',sourceCount(docId,sourceKey,[r],[b],chatId)));
     if(i%200===0){const doc={...d0,id:docId,sourceConversationId:chatId,originalConversationTitle:r.chatTitle,firstSourceSentAt:r.sourceSentAt,lastSourceSentAt:new Date(1609459200000+Math.min(group*200+199,size-1)*1000).toISOString()};delete doc.sourceRecordIds;pending.push(t.put('documents',{id:docId,sequence:group,chatKey:'chatgpt:'+chatId,displayKey:[-Date.parse(doc.lastSourceSentAt),docId],libraryDisplay:[-Date.parse(doc.lastSourceSentAt),docId],archiveDisplay:[-Date.parse(doc.lastSourceSentAt),docId],value:doc}),t.put('libraryDocuments',{id:docId,value:doc}));}
    }await Promise.all(pending);
   });}
   await s.repository.transaction(true,t=>t.put('meta',{id:'sequence',records:size,blocks:size,documents:Math.ceil(size/200)}));
   const seedMs=performance.now()-began;
   const metric=async fn=>{s.repository.metrics={reads:0,writes:0,scans:0};const at=performance.now(),value=await fn();return {ms:performance.now()-at,...s.repository.metrics,value};};
   const collection=await metric(()=>s.page({limit:10})),docId=collection.value.documents[0].id;
   const document=await metric(()=>s.page({documentId:docId,limit:20}));const b=document.value.library.blocks[0];
   const edit=await metric(()=>s.editDocument({documentId:docId,blocks:[{id:b.id,expectedRevision:b.revision,libraryText:'Synthetic retained authored result',note:'Synthetic note',excluded:false}]}));
   const capture=await metric(()=>s.capture({epoch:status.epoch,adapterVersion:'0.3.0',chat:{id:'perf-chat-0',url:'https://chatgpt.com/c/perf-chat-0',title:'Synthetic performance'},messages:[{sourceMessageId:'perf-new-source',pageOrder:201,originalText:'Synthetic new captured source'}]}));
   const search=await s.page({query:'Synthetic retained authored result',limit:10});
   await s.repository.close();const reopened=new IndexedArchiveStore(local,{name:'paia-performance-'+size});const count=(await reopened.page({view:'settings'})).stats.total;
   await reopened.repository.close();const {IAStore}=await import('../core/ia-store.js');const ia=new IAStore(local,{name:'paia-performance-'+size}),iaAt=performance.now();const iaCount=(await ia.page({view:'settings'})).stats.total;const iaMigrationMs=performance.now()-iaAt;const iaBlock=await ia.input(b.id);ia.repository.metrics={reads:0,writes:0,scans:0};const iaEditAt=performance.now();await ia.editDocument({documentId:docId,blocks:[{id:b.id,expectedRevision:iaBlock.revision,libraryText:'Synthetic IA revision result',note:iaBlock.note,excluded:false}]});const iaEdit={ms:performance.now()-iaEditAt,...ia.repository.metrics};const iaThoughtCount=(await ia.thoughtPage()).items.length;const iaHistory=(await ia.revisions({documentId:docId})).items.length;const bytes=(await navigator.storage.estimate()).usage;await ia.repository.close();
   const {SmartFilterStore}=await import('../core/smart-filter-store.js');const sf=new SmartFilterStore(local,{name:'paia-performance-'+size}),sfAt=performance.now();const sfCount=(await sf.page({view:'settings'})).stats.total;const sfMigrationMs=performance.now()-sfAt;
   sf.repository.metrics={reads:0,writes:0,scans:0};const sfPageAt=performance.now();const sfPage=await sf.page({documentId:docId,limit:20});const sfPageMetrics={ms:performance.now()-sfPageAt,...sf.repository.metrics,count:sfPage.pageItemIds.length};
   await sf.repository.transaction(true,async t=>{const rows=await t.page('filterInputs',{limit:100});for(const {value:r}of rows.rows){r.authorship='untouched';r.userEdited=false;r.filterOverride='none';r.presence={version:1,attachment:'absent',reference:'absent',confidence:'verified'};r.pendingKey=0;await t.put('filterInputs',r);}});
   sf.repository.metrics={reads:0,writes:0,scans:0};const evalAt=performance.now(),evaluated=await sf.evaluateFilters({limit:100});const sfEvaluation={ms:performance.now()-evalAt,...sf.repository.metrics,processed:evaluated.processed};
   sf.repository.metrics={reads:0,writes:0,scans:0};const searchAt=performance.now();await sf.searchInputs({query:'does-not-exist-synthetic'});const sfSearch={ms:performance.now()-searchAt,...sf.repository.metrics};await sf.repository.close();
   // M1: upgrade a non-empty v4 Thought store, then measure the same Input under
   // 1k/10k dependent entries. This fixture runs only in a temporary Chrome origin.
   const fanout=Math.min(size,10000);await sf.repository.open();
   for(let start=0;start<fanout;start+=100)await sf.repository.transaction(true,async t=>{for(let i=start;i<Math.min(start+100,fanout);i++)await t.put('thoughts',{id:'legacy-perf-'+String(i).padStart(6,'0'),thoughtText:'Synthetic legacy performance',title:'',note:'',inputRefs:[{inputBlockId:b.id,basedOnContentRevision:1}],sourceRecordIds:[b.sourceRecordId],userEdited:false,revision:0,contentRevision:0,provenanceType:'input_derived'});});await sf.repository.close();
   const {LibraryFoundationStore}=await import('../core/thought-store.js');const lf=new LibraryFoundationStore(local,{name:'paia-performance-'+size});const transactionTimes=[];const originalTx=lf.repository.transaction.bind(lf.repository);lf.repository.transaction=async(write,fn,stores)=>{const at=performance.now();try{return await originalTx(write,fn,stores);}finally{if(write)transactionTimes.push(performance.now()-at);}};
   const m1At=performance.now();await lf.libraryStatus();const m1MigrationMs=performance.now()-m1At,marker=await lf.libraryStatus();
   const evidence=await lf.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body']}]);const entry=await lf.createEntry({operationId:crypto.randomUUID(),actor:'ai',type:'judgment',formation:'explicit',body:'Synthetic dependent performance',evidence,generator:{providerId:'fixture',providerVersion:'1',modelVersion:'deterministic',taskSchemaVersion:1,promptTemplateVersion:1,policyVersion:1}});
   const templateEntry=await lf.repository.transaction(false,t=>t.get('thoughts',entry.id)),templateDependency=(await lf.entryDependencies(entry.id))[0];
   for(let start=0;start<fanout;start+=100)await lf.repository.transaction(true,async t=>{for(let i=start;i<Math.min(start+100,fanout);i++){const id='entry-perf-'+String(i).padStart(6,'0');await t.put('thoughts',{...templateEntry,id});await t.put('dependencies',{...templateDependency,id,thoughtId:id,targetId:id});}});
   const edits=[];for(let i=0;i<5;i++){const current=await lf.input(b.id);lf.repository.metrics={reads:0,writes:0,scans:0};const at=performance.now();await lf.editDocument({operationId:crypto.randomUUID(),documentId:docId,blocks:[{id:b.id,expectedRevision:current.revision,libraryText:'Synthetic M1 revision '+i,note:current.note,excluded:false}]});edits.push({ms:performance.now()-at,...lf.repository.metrics});}
   const invalidationEvents=[],originalInvalidationBatch=lf.processInvalidations.bind(lf);let eventAt=performance.now();lf.processInvalidations=async options=>{const result=await originalInvalidationBatch(options);if(result.processed>0&&result.processed<100){invalidationEvents.push(performance.now()-eventAt);eventAt=performance.now();}return result;};
   const invalidationAt=performance.now();const invalidation=await lf.drainInvalidations(),invalidationMs=performance.now()-invalidationAt;const stale=(await lf.entry(entry.id)).freshness;
   const purgeAt=performance.now();await lf.permanentDelete(b.sourceRecordId);const fenceBody=(await lf.entry(entry.id)).body;const purge=await lf.drainPurgeCleanup(),purgeMs=performance.now()-purgeAt;
   const remaining=await lf.repository.transaction(false,async t=>({thoughts:await t.count('thoughts'),dependencies:await t.count('dependencies'),revisions:await t.count('revisions')}));
   const sorted=transactionTimes.sort((a,b)=>a-b),quantile=(v,q)=>v[Math.min(v.length-1,Math.floor(v.length*q))];const m1={physicalSchema:lf.repository.db.version,fanout:fanout+1,migrationMs:m1MigrationMs,mapped:marker.mapped,quarantined:marker.quarantined,edits,editP50:quantile(edits.map(x=>x.ms).sort((a,b)=>a-b),.5),editP95:quantile(edits.map(x=>x.ms).sort((a,b)=>a-b),.95),invalidationMs,invalidationEvents,eventP95:quantile([...invalidationEvents].sort((a,b)=>a-b),.95),invalidationBatches:invalidation.batches,stale,fenceBodyEmpty:fenceBody==='',purgeMs,purgeBatches:purge.batches,remaining,transactionP50:quantile(sorted,.5),transactionP95:quantile(sorted,.95),transactionMax:sorted.at(-1),transactionCount:sorted.length};await lf.repository.close();
   return {m1,size,seedMs,sfCount,sfMigrationMs,sfPageMetrics,sfEvaluation,sfSearch,iaCount,iaMigrationMs,iaEdit,iaThoughtCount,iaHistory,collection:{ms:collection.ms,reads:collection.reads,bodyCount:collection.value.records.length},document:{ms:document.ms,reads:document.reads,bodyCount:document.value.records.length},edit:{ms:edit.ms,reads:edit.reads,writes:edit.writes,ok:edit.value.ok},capture:{ms:capture.ms,reads:capture.reads,writes:capture.writes,added:capture.value.added},searchMatched:search.documents.some(d=>d.id===docId),count,bytes,localHasText:JSON.stringify(values).includes('Synthetic retained authored result')};
  },size);
  assert.equal(result.m1.invalidationEvents.length,5);assert.equal(result.m1.physicalSchema,5);assert.equal(result.m1.mapped,Math.min(size,10000));assert.equal(result.m1.stale,'stale');assert.equal(result.m1.fenceBodyEmpty,true);assert.equal(result.m1.remaining.thoughts,0);assert.equal(result.m1.remaining.dependencies,0);for(const e of result.m1.edits){assert.ok(e.reads<150);assert.ok(e.writes<40);}assert.equal(result.sfCount,size+1);assert.equal(result.sfEvaluation.processed,100);assert.ok(result.sfEvaluation.reads<850);assert.ok(result.sfEvaluation.writes<=102,'100 decision rows + state + one backup generation marker');assert.ok(result.sfPageMetrics.reads<250);assert.ok(result.sfSearch.reads<1100);assert.ok(result.sfEvaluation.ms<5000);assert.equal(result.iaCount,size+1);assert.equal(result.iaThoughtCount,0);assert.ok(result.iaHistory>0);assert.ok(result.iaEdit.reads<40);assert.ok(result.iaEdit.writes<20);assert.equal(result.count,size+1);assert.equal(result.localHasText,false);assert.equal(result.collection.bodyCount,0);assert.ok(result.document.bodyCount<=20);assert.ok(result.document.reads<150);assert.ok(result.edit.reads<20);assert.ok(result.edit.writes<10);assert.equal(result.edit.ok,true);assert.equal(result.capture.added,1);assert.ok(result.capture.reads<150);assert.equal(result.searchMatched,true);assert.ok(result.edit.ms<2000);assert.ok(result.document.ms<3000);reports.push(result);
 }
 await writeFile('work/v070-m1-performance.json',JSON.stringify({format:'paia-m1-synthetic-performance-v1',reports:reports.map(r=>({inputs:r.size,bytes:r.bytes,...r.m1}))},null,2)+'\n');
 await writeFile('work/v050-performance.json',JSON.stringify({format:'paia-synthetic-performance-v1',reports},null,2)+'\n');
 }finally{await h.close();}
});
