import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory, IDBKeyRange} from './vendor/fake-indexeddb/build/esm/index.js';
import {IAStore} from '../core/ia-store.js';
import {SmartFilterStore} from '../core/smart-filter-store.js';
import {LibraryFoundationStore} from '../core/thought-store.js';
import {LIBRARY_STORES, LIBRARY_INDEXES} from '../core/thought-schema.js';
import {STORAGE_KEY} from '../core/constants.js';
globalThis.IDBKeyRange = IDBKeyRange;
import {local,capture,setup,inputEdit,derived} from './harness/thought-m1.mjs';
const tables=['records','recordIndex','blocks','blockIndex','documents','libraryDocuments','times','tombstones','inputStates','inputRemovals','revisions','importTasks','importBatches','importEvidence','importSources'];
const snapshotTables=(s,names=tables)=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(names.map(async n=>[n,await t.all(n)]))));

for(const [label,Old] of [['v3',IAStore],['v4',SmartFilterStore]])test('M1 '+label+' migration preserves every Source/Input/import/filter field and all stores',async()=>{
 const {s:old,storage,indexedDB}=await setup(Old);const b=(await old.snapshot()).library.blocks[0];await inputEdit(old,b.id,{libraryText:'Synthetic authored',note:'Synthetic note'});await old.excludeLibrary(b.id,true);await old.updateDocument(b.documentId,{userTitle:'Synthetic title'});
 await old.repository.transaction(true,async t=>{for(const name of ['importTasks','importBatches','importEvidence','importSources'])await t.put(name,{id:'fixture-'+name,sourceKey:'a'.repeat(64),checkpoint:17,status:'paused'});});
 const names=[...tables,...(label==='v4'?['filterInputs','filterIntents']:[])],before=await snapshotTables(old,names),localBefore=await storage.get(STORAGE_KEY);await old.repository.close();
 const s=new LibraryFoundationStore(storage,{indexedDB});await s.snapshot();assert.equal(s.repository.db.version,5);assert.equal(s.repository.db.objectStoreNames.length,37);assert.deepEqual(await snapshotTables(s,names),before);assert.deepEqual(await storage.get(STORAGE_KEY),localBefore);assert.equal((await s.libraryStatus()).phase,'active');assert.equal((await s.entryPage()).items.length,0);
 for(const name of LIBRARY_STORES)assert.ok(s.repository.db.objectStoreNames.contains(name));for(const [name,indexes]of Object.entries(LIBRARY_INDEXES)){const tx=s.repository.db.transaction(name);for(const index of Object.keys(indexes))assert.ok(tx.objectStore(name).indexNames.contains(index));}
});
test('M1 actual version provenance ignores note-only changes when only body was used',async()=>{
 const {s}=await setup();const b=(await s.snapshot()).library.blocks[0],result=await derived(s,[b.id]);await inputEdit(s,b.id,{note:'Synthetic note change'});assert.equal((await s.entry(result.id)).freshness,'current');await s.drainInvalidations();assert.equal((await s.entry(result.id)).freshness,'current');
 const deps=await s.entryDependencies(result.id);assert.equal(deps[0].basedOnContentRevision,0);assert.equal(deps[0].validatedAgainstContentRevision,1);await inputEdit(s,b.id,{libraryText:'Synthetic changed body'});assert.equal((await s.entry(result.id)).freshness,'stale');await s.drainInvalidations();assert.equal((await s.entry(result.id)).freshness,'stale');
});
test('M1 inferred auto create and stale supplied evidence are rejected',async()=>{
 const {s}=await setup();const b=(await s.snapshot()).library.blocks[0];await assert.rejects(derived(s,[b.id],{formation:'inferred'}));const evidence=await s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body']}]);await inputEdit(s,b.id,{libraryText:'Synthetic newer content'});await assert.rejects(derived(s,[b.id],{evidence}));
});
test('M1 per-field human edit protection survives undo and blocks only matching AI fields',async()=>{
 const {s}=await setup();const b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);await s.editEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID(),changes:{title:'Synthetic user title'}});let e=await s.entry(r.id);assert.equal(e.protections.title.locked,true);assert.equal(e.protections.body.locked,false);await s.editEntry({id:e.id,expectedRevision:e.revision,operationId:crypto.randomUUID(),changes:{title:''}});e=await s.entry(e.id);assert.equal(e.protections.title.locked,true);await assert.rejects(s.editEntry({id:e.id,expectedRevision:e.revision,actor:'ai',operationId:crypto.randomUUID(),changes:{title:'Forbidden'}}));
});
test('M1 suppression has no body and same evidence cannot resurrect deleted result',async()=>{
 const {s}=await setup();const b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);await s.removeEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID()});const retry=await derived(s,[b.id],{body:'Different phrasing of removed result'});assert.equal(retry.suppressed,true);assert.equal(retry.eligibleFutureCandidate,false);const rows=await s.repository.transaction(false,t=>t.all('thoughtSuppressions'));assert.ok(!JSON.stringify(rows).includes('Synthetic conclusion'));
});
test('M1 removing the last evidence invalidates AI content but preserves authored content',async()=>{
 const {s}=await setup();const b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]),u=await derived(s,[b.id],{body:'Another synthetic result'});await s.editEntry({id:u.id,expectedRevision:0,operationId:crypto.randomUUID(),changes:{note:'User work'}});await inputEdit(s,b.id,{excluded:true});assert.equal((await s.entry(r.id)).lifecycle,'invalidated');assert.equal((await s.entry(u.id)).integrity,'detached');await s.drainInvalidations();assert.equal((await s.entryPage()).items.length,1);
});

test('M1 nonempty legacy Thought quarantine preserves payload and old revisions without inventing formation',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore),b=(await old.snapshot()).library.blocks[0];
 const legacy=await old.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Legacy synthetic body',title:'Legacy synthetic title',note:'Legacy synthetic note',topics:['Legacy Topic'],types:['Idea']});await old.editThought({id:legacy.id,expectedRevision:0,changes:{note:'Legacy authored note'}});
 const prior=await old.repository.transaction(false,t=>t.get('thoughts',legacy.id)),history=await old.revisions({documentId:legacy.id});await old.repository.transaction(true,t=>t.put('thoughts',{id:'unknown-fixture',experimentalPayload:{text:'Unknown synthetic payload'},sourceRecordIds:[b.sourceRecordId]}));await old.repository.close();
 const s=new LibraryFoundationStore(storage,{indexedDB});await s.snapshot();const mapped=await s.repository.transaction(false,t=>t.get('thoughts',legacy.id));for(const key of ['thoughtText','title','note','revision','contentRevision','provenance'])assert.deepEqual(mapped[key],prior[key]);assert.equal(mapped.formation,undefined);assert.equal(mapped.lifecycle,'quarantined');for(const p of Object.values(mapped.protections))assert.equal(p.locked,true);assert.deepEqual(await s.revisions({documentId:legacy.id}),history);assert.equal((await s.entryPage()).items.length,0);await assert.rejects(s.entry(legacy.id));assert.equal((await s.repository.transaction(false,t=>t.get('thoughts','unknown-fixture'))).experimentalPayload.text,'Unknown synthetic payload');
});
for(const phase of ['thoughts','dependencies','verify'])test('M1 migration crash after '+phase+' commit resumes idempotently',async()=>{
 const {s:old,storage,indexedDB}=await setup(IAStore),b=(await old.snapshot()).library.blocks[0];await old.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic migration payload'});const before=await snapshotTables(old);await old.repository.close();let crashed=false;
 const s=new LibraryFoundationStore(storage,{indexedDB,checkpoint:async name=>{if(name==='thought-migration-'+phase&&!crashed){crashed=true;throw Error('SYNTHETIC_CRASH');}}});await assert.rejects(s.snapshot());assert.equal(crashed,true);await s.repository.close();const again=new LibraryFoundationStore(storage,{indexedDB});await again.snapshot();assert.deepEqual(await snapshotTables(again),before);assert.equal((await again.libraryStatus()).mapped,1);const row=await again.repository.transaction(false,t=>t.all('thoughts'));await again.repository.close();const twice=new LibraryFoundationStore(storage,{indexedDB});await twice.snapshot();assert.deepEqual(await twice.repository.transaction(false,t=>t.all('thoughts')),row);
});
test('M1 actual note dependency becomes stale while conversation title alone does not',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];const evidence=await s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body','note']}]),r=await derived(s,[b.id],{evidence});await s.updateDocument(b.documentId,{userTitle:'Synthetic renamed conversation'});assert.equal((await s.entry(r.id)).freshness,'current');await inputEdit(s,b.id,{note:'Synthetic dependent note'});assert.equal((await s.entry(r.id)).freshness,'stale');
});
test('M1 context-only cannot form an Entry or bypass removed/filtered source gates',async()=>{
 const {s}=await setup();await s.capture(capture((await s.status()).epoch,'m1-synthetic-message-002','继续'));const [a,b]=(await s.snapshot()).library.blocks;await s.evaluateFilters();
 await assert.rejects(s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body']}]));const evidence=await s.evidenceFor([{inputId:a.id,role:'primary',selectedFields:['body']},{inputId:b.id,role:'context_only',selectedFields:['body']}]);const r=await derived(s,[a.id],{evidence});assert.equal((await s.entryProvenance(r.id)).length,2);await assert.rejects(s.evidenceFor([{inputId:b.id,role:'context_only',selectedFields:['body']}]));await inputEdit(s,b.id,{excluded:true});await assert.rejects(s.evidenceFor([{inputId:a.id,role:'primary',selectedFields:['body']},{inputId:b.id,role:'context_only',selectedFields:['body']}]));
});
test('M1 new non-context evidence only allows a future candidate, not resurrection',async()=>{
 const {s}=await setup();const a=(await s.snapshot()).library.blocks[0],r=await derived(s,[a.id]);await s.removeEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID()});await inputEdit(s,a.id,{note:'Does not change used body'});assert.equal((await derived(s,[a.id])).eligibleFutureCandidate,false);await s.capture(capture((await s.status()).epoch,'m1-new-source','Synthetic new evidence'));const b=(await s.snapshot()).library.blocks.find(b=>b.id!==a.id);const result=await derived(s,[a.id,b.id]);assert.equal(result.suppressed,true);assert.equal(result.eligibleFutureCandidate,true);assert.equal((await s.entryPage()).items.length,0);
});
test('M1 two-tab CAS and operation receipts survive worker replacement',async()=>{
 const {s,storage,indexedDB}=await setup(),b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);const second=new LibraryFoundationStore(storage,{indexedDB});await second.snapshot();const writes=await Promise.all([s.editEntry({id:r.id,operationId:crypto.randomUUID(),expectedRevision:0,changes:{body:'Synthetic first tab'}}),second.editEntry({id:r.id,operationId:crypto.randomUUID(),expectedRevision:0,changes:{body:'Synthetic second tab'}})]);assert.equal(writes.filter(x=>x.conflict).length,1);assert.equal((await s.entry(r.id)).revision,1);
 const op={id:r.id,operationId:crypto.randomUUID(),expectedRevision:1,changes:{note:'Synthetic retained retry'}};const first=await s.editEntry(op);await s.repository.close();const third=new LibraryFoundationStore(storage,{indexedDB});assert.deepEqual(await third.editEntry(op),first);await assert.rejects(third.editEntry({...op,changes:{note:'Different request'}}));
});
test('M1 multi-source entry remains partial until its last effective evidence disappears',async()=>{
 const {s}=await setup();await s.capture(capture((await s.status()).epoch,'m1-multi-002','Synthetic second source'));const [a,b]=(await s.snapshot()).library.blocks,r=await derived(s,[a.id,b.id]);await inputEdit(s,a.id,{excluded:true});await s.drainInvalidations();assert.equal((await s.entry(r.id)).integrity,'partial');assert.equal((await s.entry(r.id)).lifecycle,'active');await inputEdit(s,b.id,{excluded:true});await s.drainInvalidations();assert.equal((await s.entry(r.id)).lifecycle,'invalidated');
});
test('M1 purge fence immediately hides every historical payload before incremental cleanup',async()=>{
 const {s}=await setup(),state=await s.snapshot(),b=state.library.blocks[0],r=await derived(s,[b.id]);await inputEdit(s,b.id,{libraryText:'Synthetic input revision'});const priorHistory=await s.revisions({documentId:b.documentId});await s.permanentDelete(state.records[0].id);assert.equal((await s.entry(r.id)).body,'');assert.equal((await s.entry(r.id)).lifecycle,'invalidated');assert.equal((await s.revisions({documentId:b.documentId})).items.length,0);assert.equal((await s.entryProvenance(r.id)).length,0);await assert.rejects(s.restoreRevision({id:priorHistory.items[0].id,expectedRevision:1}));await s.drainPurgeCleanup();await assert.rejects(s.entry(r.id));
});
test('M1 purge cleans all indexed future payload stores and preserves independent authored work',async()=>{
 const {s}=await setup(),state=await s.snapshot(),b=state.library.blocks[0],r=await derived(s,[b.id]);await s.editEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID(),changes:{body:'Independent synthetic user text',note:'Independent user note'}});
 const names=['organizerSuggestions','organizerWorkItems','librarySearchTerms','entryRelations','libraryMigrationItems'];await s.repository.transaction(true,async t=>{for(const n of names)await t.put(n,{id:'future-'+n,sourceRecordIds:[b.sourceRecordId],payload:'SYNTHETIC_PURGE_SENTINEL'});await t.put('thoughts',{id:'quarantine-purge',storageSchema:2,lifecycle:'quarantined',sourceRecordIds:[b.sourceRecordId],experimentalPayload:'SYNTHETIC_PURGE_SENTINEL'});});await s.permanentDelete(state.records[0].id);await s.drainPurgeCleanup();for(const n of names)assert.equal(await s.repository.transaction(false,t=>t.count(n)),0);const e=await s.entry(r.id);assert.equal(e.body,'Independent synthetic user text');assert.equal(e.note,'Independent user note');assert.equal(e.integrity,'detached');assert.equal(await s.repository.transaction(false,t=>t.get('thoughts','quarantine-purge')),undefined);assert.equal((await s.revisions({documentId:r.id})).items.length,0);
});
test('M1 Topic and persistent Section IDs survive rename, with shared Entry placement and human organization protection',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]),a=await s.createTopic({name:'Synthetic Topic A',operationId:crypto.randomUUID()}),z=await s.createTopic({name:'Synthetic Topic B',operationId:crypto.randomUUID()});
 const section=await s.createSection({topicId:a.id,expectedTopicRevision:0,title:'Synthetic Section',operationId:crypto.randomUUID()});await s.renameTopic({id:a.id,expectedRevision:0,name:'Synthetic Renamed Topic',operationId:crypto.randomUUID()});await s.placeEntry({entryId:r.id,topicId:a.id,sectionId:section.sectionId,expectedEntryRevision:0,expectedTopicRevision:1,operationId:crypto.randomUUID()});await s.placeEntry({entryId:r.id,topicId:z.id,expectedEntryRevision:1,expectedTopicRevision:0,operationId:crypto.randomUUID()});const e=await s.entry(r.id);assert.equal(e.protections.topics.locked,true);assert.equal(e.protections.body.locked,false);assert.equal(await s.repository.transaction(false,t=>t.count('thoughts')),1);assert.equal(await s.repository.transaction(false,t=>t.count('placements')),2);assert.equal((await s.repository.transaction(false,t=>t.get('topics',a.id))).name,'Synthetic Renamed Topic');
});
test('M1 Library revision restore is a new protected CAS operation, not history rewriting',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);await s.editEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID(),changes:{body:'Synthetic user revision'}});const history=await s.revisions({documentId:r.id}),edit=history.items.find(x=>x.reason==='edit');await s.restoreLibraryRevision({id:edit.id,expectedRevision:1,side:'before',operationId:crypto.randomUUID()});const e=await s.entry(r.id);assert.equal(e.body,'Synthetic conclusion');assert.equal(e.revision,2);assert.equal(e.protections.body.locked,true);assert.equal((await s.revisions({documentId:r.id})).items.filter(x=>x.reason==='restore').length,1);
});
test('M1 Topic Section Placement revisions restore through current CAS and preserve human organization',async()=>{
 const {s}=await setup(),r=await derived(s,[(await s.snapshot()).library.blocks[0].id]),topic=await s.createTopic({name:'Synthetic original',operationId:crypto.randomUUID()});
 await s.renameTopic({id:topic.id,name:'Synthetic changed',expectedRevision:0,operationId:crypto.randomUUID()});let h=await s.revisions({documentId:topic.id,kind:'topic'});await s.restoreRevision({id:h.items[0].id,expectedRevision:1,operationId:crypto.randomUUID()});assert.equal((await s.repository.transaction(false,t=>t.get('topics',topic.id))).name,'Synthetic original');
 const section=await s.editSection({topicId:topic.id,sectionId:topic.sectionId,expectedRevision:0,title:'Synthetic section',operationId:crypto.randomUUID()});h=await s.revisions({documentId:topic.id,kind:'section'});await s.restoreRevision({id:h.items.find(x=>x.reason==='edit').id,expectedRevision:section.revision,operationId:crypto.randomUUID()});
 const placed=await s.placeEntry({entryId:r.id,topicId:topic.id,expectedEntryRevision:0,expectedTopicRevision:2,operationId:crypto.randomUUID()});h=await s.revisions({documentId:topic.id,kind:'placement'});await s.restoreRevision({id:h.items[0].id,expectedRevision:placed.placementRevision,expectedEntryRevision:placed.revision,expectedTopicRevision:placed.topicRevision,operationId:crypto.randomUUID()});const e=await s.entry(r.id);assert.deepEqual(e.organizationIntents.excluded,[topic.id]);assert.equal(e.protections.body.locked,false);
});
test('M1 legacy authored current fields survive purge while unknown payloads and histories are erased',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore),state=await old.snapshot(),b=state.library.blocks[0];const r=await old.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic old body'});await old.editThought({id:r.id,expectedRevision:0,changes:{thoughtText:'Synthetic independent user work'}});await old.repository.transaction(true,async t=>{const row=await t.get('thoughts',r.id);await t.put('thoughts',{...row,experimentalPayload:'SYNTHETIC_UNSAFE_OLD'});await t.put('thoughts',{id:'sealed-unknown',unknownPayload:'SYNTHETIC_UNTRACEABLE'});});await old.repository.close();const s=new LibraryFoundationStore(storage,{indexedDB});await s.snapshot();assert.equal((await s.libraryStatus()).libraryActivation,'blocked_quarantine');await s.permanentDelete(state.records[0].id);await s.drainPurgeCleanup();const row=await s.repository.transaction(false,t=>t.get('thoughts',r.id));assert.equal(row.thoughtText,'Synthetic independent user work');assert.equal(row.experimentalPayload,undefined);assert.equal(await s.repository.transaction(false,t=>t.get('thoughts','sealed-unknown')),undefined);
});
test('M1 revision retention keeps every recent and newest 20 important; AI and user windows never coalesce',async()=>{
 const {journal}=await import('../core/thought-journal.js');let now='2026-01-01T00:00:00.000Z';const {s}=await setup(LibraryFoundationStore,{clock:()=>now});
 for(let i=0;i<25;i++)await s.write(t=>journal(s,t,{kind:'topic',entityId:'retention-topic',before:{name:String(i)},after:{name:String(i+1)},fieldMask:['name'],actor:i%2?'ai':'user',reason:'edit',important:true,sourceRecordIds:[]}));
 now='2026-05-01T00:00:00.000Z';for(const actor of ['ai','user','user'])await s.write(t=>journal(s,t,{kind:'topic',entityId:'retention-topic',before:{name:'same'},after:{name:'same'},fieldMask:['name'],actor,reason:'edit',important:false,sourceRecordIds:[]}));
 const h=await s.revisions({documentId:'retention-topic',kind:'topic'});assert.equal(h.items.filter(x=>x.important).length,20);assert.equal(h.items.filter(x=>!x.important).length,2);
});
test('M1 forged evidence and command fields cannot modify Source/Input; empty working body has no Source fallback',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],before=await snapshotTables(s);const ev=await s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body']}]);for(const changes of [{sourceRecordIds:['forged']},{basedOnContentRevision:99},{role:'assistant'},{selectedFields:['originalText']}])await assert.rejects(derived(s,[b.id],{evidence:[{...ev[0],...changes}]}));await assert.rejects(derived(s,[b.id],{updateSource:'forbidden'}));assert.deepEqual(await snapshotTables(s),before);await inputEdit(s,b.id,{libraryText:''});const current=await s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body']}]);const {hashText}=await import('../core/dedupe.js');assert.equal(current[0].fieldDigests.body,await hashText(''));
});
test('M1 invalidation interruption cursor resumes and edit cost is independent of dependency fan-out',async()=>{
 const {s,storage,indexedDB}=await setup(),b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);await s.repository.transaction(true,async t=>{const d=(await t.all('dependencies'))[0],row=await t.get('thoughts',r.id);for(let i=0;i<250;i++){const id='synthetic-fanout-'+i;await t.put('thoughts',{...row,id});await t.put('dependencies',{...d,id,thoughtId:id,targetId:id});}});
 const before={...s.repository.metrics};await inputEdit(s,b.id,{libraryText:'Synthetic changed'});assert.ok(s.repository.metrics.reads-before.reads<150);assert.equal((await s.repository.transaction(false,t=>t.get('thoughts',r.id))).freshness,'current');const batch=await s.processInvalidations({limit:17});assert.equal(batch.processed,17);await s.repository.close();const next=new LibraryFoundationStore(storage,{indexedDB});await next.drainInvalidations();const rows=await next.repository.transaction(false,t=>t.all('thoughts'));assert.equal(rows.filter(x=>x.freshness==='stale').length,251);
});
test('M1 transaction abort rolls back Entry provenance revision and receipt together',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];const before=await snapshotTables(s,['thoughts','provenance','dependencies','revisions','operationReceipts']);const original=s.uuid;s.uuid=()=>{throw Error('SYNTHETIC_ABORT');};await assert.rejects(derived(s,[b.id]));s.uuid=original;assert.deepEqual(await snapshotTables(s,['thoughts','provenance','dependencies','revisions','operationReceipts']),before);
});
test('M1 delayed validated output and invalidation batch cannot commit across edit or purge',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];let changed=false;s.repository.checkpoint=async name=>{if(name==='thought-evidence-validated'&&!changed){changed=true;await inputEdit(s,b.id,{libraryText:'Synthetic edit during delay'});}};await assert.rejects(derived(s,[b.id]));assert.equal(changed,true);s.repository.checkpoint=async()=>{};const r=await derived(s,[b.id]);await inputEdit(s,b.id,{note:'Synthetic event'});let purged=false;s.repository.checkpoint=async name=>{if(name==='thought-invalidation-read'&&!purged){purged=true;await s.permanentDelete(b.sourceRecordId);}};await s.processInvalidations();assert.equal((await s.entry(r.id)).body,'');await s.drainPurgeCleanup();await assert.rejects(s.entry(r.id));
});
test('M1 all supported fields protect independently and context-only additions cannot unlock suppression',async()=>{
 const {s}=await setup();await s.capture(capture((await s.status()).epoch,'context-new-002','Synthetic neighbor'));const [a,b]=(await s.snapshot()).library.blocks,r=await derived(s,[a.id]);let revision=0;for(const [field,value]of Object.entries({body:'Synthetic human body',note:'Synthetic human note',type:'idea',formation:'inferred'})){const out=await s.editEntry({id:r.id,expectedRevision:revision,changes:{[field]:value},operationId:crypto.randomUUID()});revision=out.revision;assert.equal((await s.entry(r.id)).protections[field].locked,true);}await s.removeEntry({id:r.id,expectedRevision:revision,operationId:crypto.randomUUID()});const evidence=await s.evidenceFor([{inputId:a.id,role:'primary',selectedFields:['body']},{inputId:b.id,role:'context_only',selectedFields:['body']}]);const out=await derived(s,[a.id],{evidence});assert.equal(out.suppressed,true);assert.equal(out.eligibleFutureCandidate,false);
});
test('M1 source purge survives cleanup interruption and cannot recapture or restore deleted sources',async()=>{
 const {s,storage,indexedDB}=await setup(),state=await s.snapshot(),b=state.library.blocks[0],r=await derived(s,[b.id]);await s.removeEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID()});await s.permanentDelete(b.sourceRecordId);await assert.rejects(s.restoreEntry({id:r.id,expectedRevision:1,operationId:crypto.randomUUID()}));await s.processPurgeCleanup({limit:1});await s.repository.close();const next=new LibraryFoundationStore(storage,{indexedDB});await next.drainPurgeCleanup();await next.capture(capture((await next.status()).epoch));assert.equal((await next.snapshot()).records.length,0);assert.equal((await next.entryPage()).items.length,0);
});
test('M1 quota-like abort after payload writes leaves no partial entry or receipt',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],before=await snapshotTables(s,['thoughts','dependencies','provenance','revisions','operationReceipts']);const prune=s.pruneEntity;s.pruneEntity=()=>{throw Error('SYNTHETIC_STORAGE_FULL');};await assert.rejects(derived(s,[b.id]));s.pruneEntity=prune;assert.deepEqual(await snapshotTables(s,['thoughts','dependencies','provenance','revisions','operationReceipts']),before);
});
test('M1 independent authored entries allow equal and empty bodies without invented AI provenance',async()=>{
 const {s}=await setup();for(let i=0;i<2;i++)await s.createEntry({actor:'user',type:'creation',formation:'inferred',body:'',evidence:[],operationId:crypto.randomUUID()});const p=await s.entryPage();assert.equal(p.items.length,2);for(const e of p.items){assert.equal(e.integrity,'detached');assert.equal((await s.entryProvenance(e.id)).length,0);assert.equal(e.family,'Creation');}
});
test('M1 redirect identity rejects loops and stale renamed IDs; rank exhaustion fails without reordering',async()=>{
 const {rankBetween}=await import('../core/thought-model.js');assert.equal(rankBetween('000000000010','000000000020'),'000000000015');assert.throws(()=>rankBetween('000000000010','000000000011'));const {s}=await setup(),a=await s.createTopic({name:'Synthetic A',operationId:crypto.randomUUID()}),b=await s.createTopic({name:'Synthetic B',operationId:crypto.randomUUID()});await s.repository.transaction(true,async t=>{const row=await t.get('topics',a.id);await t.put('topics',{...row,redirectTo:b.id});});assert.equal((await s.repository.transaction(false,t=>s.canonicalTopic(t,a.id))).id,b.id);await assert.rejects(s.renameTopic({id:a.id,expectedRevision:0,name:'Forbidden old ID',operationId:crypto.randomUUID()}));await s.repository.transaction(true,async t=>{const row=await t.get('topics',b.id);await t.put('topics',{...row,redirectTo:a.id});});await assert.rejects(s.repository.transaction(false,t=>s.canonicalTopic(t,a.id)));
});
test('M1 untraceable quarantine revision is fenced and erased with its unknown owner on source purge',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore),b=(await old.snapshot()).library.blocks[0];await old.repository.transaction(true,async t=>{await t.put('thoughts',{id:'unknown-history',experimentalPayload:'SYNTHETIC_UNKNOWN'});await t.put('revisions',{id:'unknown-revision',kind:'thought',entityId:'unknown-history',entityKey:'thought:unknown-history',documentId:'unknown-history',documentList:['unknown-history',999],listKey:['thought:unknown-history',999],sequence:999,before:{body:'SYNTHETIC_UNKNOWN'},after:{body:'SYNTHETIC_UNKNOWN'},sourceRecordIds:[]});});await old.repository.close();const s=new LibraryFoundationStore(storage,{indexedDB});await s.snapshot();assert.equal((await s.revisions({documentId:'unknown-history'})).items.length,0);await s.permanentDelete(b.sourceRecordId);await s.drainPurgeCleanup();assert.equal(await s.repository.transaction(false,t=>t.get('revisions','unknown-revision')),undefined);
});
test('M1 experimental storageSchema=2 is not trusted as a completed migration or source authority',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore);await old.repository.transaction(true,t=>t.put('thoughts',{id:'experimental-two',storageSchema:2,lifecycle:'active',thoughtText:'Synthetic unverified legacy',inputRefs:[],sourceRecordIds:['missing-source']}));await old.repository.close();const s=new LibraryFoundationStore(storage,{indexedDB});await s.snapshot();assert.equal((await s.entryPage()).items.length,0);const raw=await s.repository.transaction(false,t=>t.get('thoughts','experimental-two'));assert.equal(raw.lifecycle,'quarantined');assert.equal(raw.quarantineSealed,true);await assert.rejects(s.createEntry({operationId:crypto.randomUUID(),actor:'user',body:'Synthetic',type:'idea',formation:'explicit',evidence:[]}));
});
test('M1 Input capture and editing continue between migration batches and after a Library mapping failure',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore),b=(await old.snapshot()).library.blocks[0];await old.repository.transaction(true,async t=>{for(let i=0;i<250;i++)await t.put('thoughts',{id:'migration-interleave-'+i,thoughtText:'Synthetic legacy',inputRefs:[{inputBlockId:b.id}],sourceRecordIds:[b.sourceRecordId],provenanceType:'input_derived'});});await old.repository.close();let crashed=false;const s=new LibraryFoundationStore(storage,{indexedDB,checkpoint:async name=>{if(name==='thought-migration-thoughts'&&!crashed){crashed=true;throw Error('SYNTHETIC_MAPPING_FAILURE');}}});await s.status();await inputEdit(s,b.id,{libraryText:'Synthetic edit during paused migration'});await s.capture(capture((await s.status()).epoch,'migration-live-source','Synthetic capture during paused migration'));assert.equal((await s.input(b.id)).libraryText,'Synthetic edit during paused migration');await assert.rejects(s.entryPage());await s.repository.close();const next=new LibraryFoundationStore(storage,{indexedDB});await next.libraryStatus();assert.equal((await next.input(b.id)).libraryText,'Synthetic edit during paused migration');assert.equal((await next.snapshot()).records.length,2);
});
test('M1 unavailable used versions never masquerade as current Input; purge reports pending until cleanup finishes',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);await inputEdit(s,b.id,{libraryText:'Synthetic later version'});let p=await s.entryProvenance(r.id);assert.equal(p[0].basedOnContentRevision,0);assert.equal(p[0].availability,'version_unavailable');const result=await s.permanentDelete(b.sourceRecordId);assert.equal(result.libraryCleanup,'pending');assert.ok((await s.libraryStatus()).pendingCleanupJobs>0);await s.drainPurgeCleanup();assert.equal((await s.libraryStatus()).pendingCleanupJobs,0);
});
test('M1 every approved Type maps to exactly one Family; Unicode byte limit never truncates',async()=>{
 const {s}=await setup(),expected={fact:'Information',event:'Information',preference:'Thinking',decision:'Thinking',judgment:'Thinking',idea:'Thinking',goal_plan:'Thinking',reflection:'Thinking',creation:'Creation'};for(const [type,family]of Object.entries(expected)){const r=await s.createEntry({operationId:crypto.randomUUID(),actor:'user',type,formation:'explicit',body:'Synthetic\nplain text',evidence:[]});assert.equal((await s.entry(r.id)).family,family);}await assert.rejects(s.createEntry({operationId:crypto.randomUUID(),actor:'user',type:'unknown',formation:'explicit',body:'Synthetic',evidence:[]}));await assert.rejects(s.createEntry({operationId:crypto.randomUUID(),actor:'user',type:'idea',formation:'explicit',body:'字'.repeat(70000),evidence:[]}));const body='x'.repeat(200*1024);const r=await s.createEntry({operationId:crypto.randomUUID(),actor:'user',type:'creation',formation:'explicit',body,evidence:[]});assert.equal((await s.entry(r.id)).body,body);
});
test('M1 hot 200KiB revision growth keeps all young history and suppression beyond retention',async()=>{
 let time='2026-01-01T00:00:00Z';const {s}=await setup(LibraryFoundationStore,{clock:()=>time}),body='x'.repeat(200*1024-10),r=await s.createEntry({operationId:crypto.randomUUID(),actor:'user',type:'creation',formation:'explicit',body,evidence:[]});let revision=0;for(let i=0;i<24;i++){time=new Date(Date.parse('2026-01-01')+i*61000).toISOString();const out=await s.editEntry({id:r.id,expectedRevision:revision,operationId:crypto.randomUUID(),changes:{body:body+i}});revision=out.revision;}assert.equal((await s.revisions({documentId:r.id})).items.length,25);await s.removeEntry({id:r.id,expectedRevision:revision,operationId:crypto.randomUUID()});time='2026-06-01T00:00:00Z';await s.pruneRevisions();assert.equal(await s.repository.transaction(false,t=>t.count('thoughtSuppressions')),1);assert.equal((await s.revisions({documentId:r.id})).items.filter(x=>x.important).length,2);
});
test('M1 selected-note-only change cannot unlock removed Thought suppression',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];await inputEdit(s,b.id,{note:'Synthetic selected note'});let evidence=await s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body','note']}]);const r=await derived(s,[b.id],{evidence});await s.removeEntry({id:r.id,expectedRevision:0,operationId:crypto.randomUUID()});await inputEdit(s,b.id,{note:'Synthetic changed note only'});evidence=await s.evidenceFor([{inputId:b.id,role:'primary',selectedFields:['body','note']}]);const out=await derived(s,[b.id],{evidence});assert.equal(out.suppressed,true);assert.equal(out.eligibleFutureCandidate,false);
});
test('M1 unrelated queued jobs cannot starve purge; staged payloads are removed',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];await derived(s,[b.id]);await s.repository.transaction(true,async t=>{for(let i=0;i<150;i++)await t.put('organizerJobs',{id:'other-job-'+i,kind:'reserved',stateKey:0,nextAttemptAt:0,priority:0,sequence:i});await t.put('organizerJobs',{id:'staged-payload',kind:'reserved',stateKey:0,nextAttemptAt:0,priority:0,sequence:0,sourceRecordIds:[b.sourceRecordId],payload:'SYNTHETIC_PURGE_JOB_PAYLOAD'});});await s.permanentDelete(b.sourceRecordId);assert.equal((await s.libraryStatus()).pendingCleanupJobs,1);await s.drainPurgeCleanup();assert.equal(await s.repository.transaction(false,t=>t.get('organizerJobs','staged-payload')),undefined);assert.equal((await s.libraryStatus()).pendingCleanupJobs,0);
});
test('M1 mapping transaction failure rolls back partial Thought/category mapping, then resumes',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore),b=(await old.snapshot()).library.blocks[0];const row=await old.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic migration atomicity',topics:['Synthetic category']});const before=await snapshotTables(old);await old.repository.close();const s=new LibraryFoundationStore(storage,{indexedDB,uuid:()=>{throw Error('SYNTHETIC_MAPPING_QUOTA');}});await assert.rejects(s.snapshot());assert.deepEqual(await s.repository.transaction(false,t=>t.get('thoughts',row.id)),row);assert.equal(await s.repository.transaction(false,t=>t.count('libraryMigrationItems')),0);assert.deepEqual(await snapshotTables(s),before);await s.repository.close();const next=new LibraryFoundationStore(storage,{indexedDB});await next.snapshot();assert.equal((await next.libraryStatus()).mapped,1);
});
test('M1 ten Topic placements do not duplicate Entry body or Entry history',async()=>{
 const {s}=await setup(),r=await s.createEntry({operationId:crypto.randomUUID(),actor:'user',type:'idea',formation:'explicit',body:'SYNTHETIC_SHARED_BODY',evidence:[]});let revision=0;for(let i=0;i<10;i++){const topic=await s.createTopic({name:'Synthetic Topic '+i,operationId:crypto.randomUUID()}),out=await s.placeEntry({entryId:r.id,topicId:topic.id,expectedEntryRevision:revision,expectedTopicRevision:0,operationId:crypto.randomUUID()});revision=out.revision;}assert.equal(await s.repository.transaction(false,t=>t.count('thoughts')),1);const placements=await s.repository.transaction(false,t=>t.all('placements'));assert.equal(placements.length,10);assert.equal(JSON.stringify(placements).includes('SYNTHETIC_SHARED_BODY'),false);assert.equal((await s.revisions({documentId:r.id})).items.length,1);
});
test('M1 empty evidence body cannot authorize automatic content and empty AI output is rejected',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0];await assert.rejects(derived(s,[b.id],{body:''}));await inputEdit(s,b.id,{libraryText:''});await assert.rejects(derived(s,[b.id]));
});
test('M1 incomplete Library activation fences Library history while Input history remains available',async()=>{
 const {s:old,storage,indexedDB}=await setup(SmartFilterStore),b=(await old.snapshot()).library.blocks[0],r=await old.createThought({provenanceType:'user_created',inputRefs:[],thoughtText:'Synthetic old authored body'});await old.repository.close();const s=new LibraryFoundationStore(storage,{indexedDB,checkpoint:async name=>{if(name==='thought-migration-thoughts')throw Error('SYNTHETIC_PAUSE');}});await s.status();assert.equal((await s.revisions({documentId:r.id})).items.length,0);assert.ok((await s.revisions({documentId:b.documentId})).items.length>0);
});
test('M1 rapid Input remove/restore cannot revive an old AI Entry before or after queue consumption',async()=>{
 const {s}=await setup(),b=(await s.snapshot()).library.blocks[0],r=await derived(s,[b.id]);await inputEdit(s,b.id,{excluded:true});assert.equal((await s.entry(r.id)).lifecycle,'invalidated');await inputEdit(s,b.id,{excluded:false});assert.equal((await s.entry(r.id)).lifecycle,'invalidated');const fresh=await derived(s,[b.id],{body:'Synthetic new version-scoped result'});assert.equal((await s.entry(fresh.id)).lifecycle,'active');await s.drainInvalidations();assert.equal((await s.entry(r.id)).lifecycle,'invalidated');assert.equal((await s.entry(fresh.id)).lifecycle,'active');assert.equal((await s.entryDependencies(r.id)).length,0);assert.equal((await s.entryDependencies(fresh.id)).length,1);
});
test('M1 supporting/context removal histories are not cleared by restoration or worker replacement',async()=>{
 const {s,storage,indexedDB}=await setup();await s.capture(capture((await s.status()).epoch,'removal-race-second','Synthetic second source'));const [a,b]=(await s.snapshot()).library.blocks,r=await derived(s,[a.id,b.id]);await inputEdit(s,a.id,{excluded:true});await inputEdit(s,a.id,{excluded:false});assert.equal((await s.entry(r.id)).integrity,'partial');await s.repository.close();const next=new LibraryFoundationStore(storage,{indexedDB});await inputEdit(next,b.id,{excluded:true});await inputEdit(next,b.id,{excluded:false});assert.equal((await next.entry(r.id)).lifecycle,'invalidated');await next.drainInvalidations();assert.equal((await next.entry(r.id)).lifecycle,'invalidated');
});
