import {mkdtemp,appendFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,conversation} from './harness/fake-chatgpt.mjs';

test('M1 isolated Chrome v3/v4 nonempty migration, DDL abort, blocked upgrade and old binary fail closed',{timeout:120000},async()=>{
 const fixture=await mkdtemp(join(tmpdir(),'paia-m1-worker-fixture-'));execFileSync('/usr/bin/python3',['-c',"import sys;sys.path.insert(0,'scripts');from build_internal import build_internal;build_internal(sys.argv[1],sys.argv[2])",process.cwd(),fixture]);await appendFile(join(fixture,'background/service-worker.js'),"\nimport {IAStore as SyntheticIA} from '../core/ia-store.js';import {SmartFilterStore as SyntheticFilter} from '../core/smart-filter-store.js';globalThis.__m1Fixture={IAStore:SyntheticIA,SmartFilterStore:SyntheticFilter,LibraryFoundationStore:IndexedArchiveStore};\n");
 const h=await FakeChatGPT.start({extensionPath:fixture});try{
  await h.state();const worker=h.context.serviceWorkers().find(w=>w.url().endsWith('/background/service-worker.js'));const results=[];
  for(const version of [3,4])results.push(await worker.evaluate(async version=>{
   const {IAStore,SmartFilterStore,LibraryFoundationStore}=globalThis.__m1Fixture;
   const values={},local={async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}},name='synthetic-m1-upgrade-'+version,Old=version===3?IAStore:SmartFilterStore,old=new Old(local,{name});await old.consent(true);await old.capture({epoch:(await old.status()).epoch,adapterVersion:'0.3.0',chat:{id:'m1-browser-fixture',url:'https://chatgpt.com/c/m1-browser-fixture',title:'Synthetic'},messages:[{sourceMessageId:'m1-browser-source',pageOrder:1,originalText:'Synthetic source'}]});const b=(await old.snapshot()).library.blocks[0];await old.editDocument({documentId:b.documentId,blocks:[{id:b.id,expectedRevision:0,libraryText:'Synthetic retained user work',note:'Synthetic note',excluded:false}]});await old.createThought({provenanceType:'input_derived',inputRefs:[b.id],thoughtText:'Synthetic legacy thought',topics:['Synthetic topic']});
   const tables=['records','recordIndex','blocks','blockIndex','times','documents','libraryDocuments','inputStates','inputRemovals','revisions','tombstones','importTasks','importBatches','importEvidence','importSources',...(version===4?['filterInputs','filterIntents']:[])],dump=s=>s.repository.transaction(false,async t=>Object.fromEntries(await Promise.all(tables.map(async n=>[n,await t.all(n)]))));const before=await dump(old),control=JSON.stringify(values);await old.repository.close();
   // An aborted DDL must leave the actual database on its previous version.
   await new Promise(resolve=>{const r=indexedDB.open(name,5);r.onupgradeneeded=()=>r.transaction.abort();r.onerror=()=>resolve();});const afterAbort=(await indexedDB.databases()).find(d=>d.name===name).version;
   const blocker=await new Promise((resolve,reject)=>{const r=indexedDB.open(name,version);r.onsuccess=()=>resolve(r.result);r.onerror=reject;});blocker.onversionchange=()=>{};const blocked=new LibraryFoundationStore(local,{name});let blockedClosed=false;try{await blocked.libraryStatus();}catch{blockedClosed=true;}blocker.close();await new Promise(resolve=>setTimeout(resolve,100));
   const s=new LibraryFoundationStore(local,{name});const marker=await s.libraryStatus(),after=await dump(s),empty=(await s.entryPage()).items.length===0,storeCount=s.repository.db.objectStoreNames.length;const quarantined=await s.repository.transaction(false,t=>t.count('thoughts'));await s.repository.close();let downgradeClosed=false;try{await new Old(local,{name}).snapshot();}catch{downgradeClosed=true;}
   return {fromVersion:version,toVersion:5,storeCount,quarantined,empty,marker,fieldEquality:JSON.stringify(before)===JSON.stringify(after),controlEquality:control===JSON.stringify(values),afterAbort,blockedClosed,downgradeClosed};
  },version));
  for(const r of results){assert.equal(r.fieldEquality,true);assert.equal(r.controlEquality,true);assert.equal(r.storeCount,37);assert.equal(r.quarantined,1);assert.equal(r.empty,true);assert.equal(r.afterAbort,r.fromVersion);assert.equal(r.blockedClosed,true);assert.equal(r.downgradeClosed,true);assert.equal(r.marker.verified,true);}
  await mkdir('work',{recursive:true});await writeFile('work/v070-m1-chrome-schema.json',JSON.stringify({scope:'isolated-synthetic-background-writer',chromeVersion:(await h.cdp.send('Browser.getVersion')).product,results,networkRequests:h.extensionNetworkRequests},null,2)+'\n');assert.equal(h.extensionNetworkRequests,0);
 }finally{await h.close();await rm(fixture,{recursive:true,force:true});}
});

test('M1 actual runtime schema and worker restart retain source capture, edit, outbox and privacy gates',{timeout:65000},async()=>{
 const h=await FakeChatGPT.start();try{
  const p=h.archive;await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await h.open(conversation('m1-runtime-synthetic'));await eventually(async()=>(await h.state()).records.length===3);const state=await h.state(),b=state.library.blocks[0];await p.evaluate(id=>chrome.runtime.sendMessage({type:'UPDATE_LIBRARY',id,changes:{libraryText:'Synthetic M1 worker edit'}}),b.id);await h.restartWorker();const after=await h.state();assert.equal(after.library.blocks[0].libraryText,'Synthetic M1 worker edit');assert.deepEqual(after.records,state.records);
  assert.equal(await p.evaluate(async()=>{const d=(await indexedDB.databases()).find(d=>d.name==='paia-archive');return d.version;}),5);assert.equal((await p.evaluate(()=>chrome.runtime.sendMessage({type:'CREATE_THOUGHT',body:'Synthetic forbidden'}))).ok,false);assert.equal((await p.evaluate(()=>chrome.runtime.sendMessage({type:'ORGANIZER_RUN'}))).ok,false);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
 }finally{await h.close();}
});
