import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,mkdir} from 'node:fs/promises';import {FakeChatGPT} from './harness/fake-chatgpt.mjs';
test('M2 real Chrome performance: 1k/10k Entries, 1/3/10 Topics, first40/next, search, long body, memory, merge/reorder',{timeout:600000},async()=>{const h=await FakeChatGPT.start();try{const reports=[];for(const size of [1000,10000]){const report=await h.archive.evaluate(async size=>{
 const {LibraryDocumentsStore}=await import('../core/library-documents-store.js');let values={};const local={async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}};const s=new LibraryDocumentsStore(local,{name:'m2-synthetic-performance-'+size});await s.consent(true);const topics=[];for(let i=0;i<10;i++)topics.push(await s.createTopic({name:'Synthetic topic '+i,operationId:crypto.randomUUID()}));const one=await s.createEntry({actor:'user',operationId:crypto.randomUUID(),title:'Synthetic',body:'Synthetic library text',note:'',type:'idea',formation:'explicit',evidence:[]});const template=await s.repository.transaction(false,t=>t.get('thoughts',one.id));await s.repository.transaction(true,t=>t.delete('thoughts',one.id));
 const metric=async fn=>{s.repository.metrics={reads:0,writes:0,scans:0};const at=performance.now(),value=await fn();return {ms:performance.now()-at,...s.repository.metrics,value};};
 for(let offset=0;offset<size;offset+=200)await s.repository.transaction(true,async t=>{for(let i=offset;i<Math.min(size,offset+200);i++){const id='synthetic-entry-'+String(i).padStart(6,'0'),e={...template,id,title:'Synthetic entry '+i,thoughtText:'Synthetic library document content '+i+(i===size-1?' uniqueneedle':'')};delete e.searchVersion;delete e.indexedSearchVersion;await t.put('thoughts',e);await t.put('placements',{id:JSON.stringify([topics[0].id,1,id]),topicId:topics[0].id,layoutGeneration:1,entryId:id,sectionId:topics[0].sectionId,sectionRank:'499999999999',rank:String(1000000+i*1024).padStart(12,'0'),revision:0,activeKey:0,lifecycle:'active',membershipAuthorship:'user',sectionProtection:true,orderProtection:true});}});
 const first=await metric(()=>s.topicDocumentPage({topicId:topics[0].id})),next=await metric(()=>s.topicDocumentPage({topicId:topics[0].id,cursor:first.value.nextCursor}));const memberships=[];
 for(const count of [1,3,10]){if(count>1)for(let offset=0;offset<size;offset+=200)await s.repository.transaction(true,async t=>{for(let i=offset;i<Math.min(size,offset+200);i++){const id='synthetic-entry-'+String(i).padStart(6,'0');for(let j=count===3?1:3;j<count;j++)await t.put('placements',{id:JSON.stringify([topics[j].id,1,id]),topicId:topics[j].id,layoutGeneration:1,entryId:id,sectionId:topics[j].sectionId,sectionRank:'499999999999',rank:String(1000000+i*1024).padStart(12,'0'),revision:0,activeKey:0,lifecycle:'active',membershipAuthorship:'user',sectionProtection:true,orderProtection:true});}});const r=await metric(()=>s.topicDocumentPage({topicId:topics[0].id}));memberships.push({topicsPerEntry:count,ms:r.ms,reads:r.reads,writes:r.writes,scans:r.scans,count:r.value.items.length});}
 const rebuild=await metric(async()=>{await s.rebuildLibrarySearch();await s.drainLibraryMaintenance();});const search=await metric(()=>s.searchLibrary({query:'uniqueneedle'}));
 const e=await s.entry('synthetic-entry-000000');const edit=await metric(()=>s.editLibraryFields({id:e.id,expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,changes:{body:'L'.repeat(200*1024)},operationId:crypto.randomUUID()}));const long=await metric(()=>s.topicDocumentPage({topicId:topics[0].id}));const full=await s.entry(e.id);
 const reorder=await metric(async()=>s.reorderPlacement({topicId:topics[0].id,entryId:'synthetic-entry-000000',otherEntryId:'synthetic-entry-000001',expectedTopicRevision:(await s.topic(topics[0].id)).organizationRevision,operationId:crypto.randomUUID()}));
 const merge=await metric(async()=>{await s.startLayout({kind:'topic_merge',topicId:topics[9].id,survivorId:topics[0].id,expectedTopicRevision:(await s.topic(topics[9].id)).organizationRevision,expectedSurvivorRevision:(await s.topic(topics[0].id)).organizationRevision,operationId:crypto.randomUUID()});await s.drainLibraryMaintenance();});
 const rows=await s.repository.transaction(false,async t=>({entries:await t.count('thoughts'),placements:await t.count('placements'),postings:await t.count('librarySearchTerms'),stores:t.tx.objectStoreNames.length}));
 const {LibraryEntryEditor}=await import('../ui/library-entry-editor.js');const root=document.createElement('div');document.body.append(root);const editor=new LibraryEntryEditor(root,[s.documentEntry(full)],()=>{});for(let i=0;i<30;i++)editor.change([{id:e.id,field:'body',before:full.body,after:'X'.repeat(200*1024)}]);editor.autosave.cancel();const editorMemory={journalBytes:editor.journal.bytes,undoSteps:editor.journal.undo.length,mountedEntries:editor.entries.size};editor.dispose();root.remove();await s.repository.close();
 const safe=x=>({ms:x.ms,reads:x.reads,writes:x.writes,scans:x.scans});return {size,first40:{...safe(first),count:first.value.items.length,transportBytes:new TextEncoder().encode(JSON.stringify(first.value)).length},next:{...safe(next),count:next.value.items.length},memberships,rebuild:safe(rebuild),search:{...safe(search),matches:search.value.items.length},longEdit:safe(edit),longPage:{...safe(long),separate:long.value.items.some(x=>x.entry.large),exactBodyBytes:new TextEncoder().encode(full.body).length},reorder:safe(reorder),merge:safe(merge),rows,editorMemory,chrome: navigator.userAgent};
 },size);assert.equal(report.first40.count,40);assert.equal(report.next.count,40);assert.ok(report.first40.transportBytes<=256*1024);assert.equal(report.search.matches,1);assert.equal(report.rows.entries,size);assert.equal(report.rows.stores,37);assert.equal(report.longPage.exactBodyBytes,200*1024);assert.ok(report.longPage.separate);assert.ok(report.editorMemory.journalBytes<=2000002);assert.ok(report.memberships.every(x=>x.count===40));reports.push(report);}
 await mkdir('work',{recursive:true});await writeFile('work/v070-m2-performance.json',JSON.stringify({syntheticOnly:true,reports},null,2)+'\n');assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
 }finally{await h.close();}});
