import test from 'node:test';import assert from 'node:assert/strict';
import {withTopicActions,tick,find} from './harness/topic-action-dom.mjs';
test('real ordinary workspace uses the sole production draft and acknowledged save',()=>withTopicActions(async f=>{const host=document.createElement('section');document.body.append(host);const opening=f.owner.compose({topicId:'topic',sectionId:'named',workspace:{host}});await tick();await f.respond({ok:true,data:{items:[{id:'topic',name:'Topic'}],nextCursor:null}});await opening;assert.equal(f.owner.dialog.open,false);assert.equal(f.owner.surface.workspace,true);const editor=f.owner.draft;editor.value='SYNTHETIC workspace\n\nprose';find(host,n=>n.tagName==='BUTTON'&&n.textContent==='保存想法').onclick();await tick();assert.equal(f.calls[0].sectionId,'named');await f.respond({ok:true,data:{id:'saved'}});assert.equal(f.owner.surface,null);}));
async function open(f){const host=document.createElement('section');document.body.append(host);const pending=f.owner.compose({topicId:'topic',sectionId:'named',workspace:{host}});await tick();await f.respond({ok:true,data:{items:[{id:'topic',name:'Topic'}],nextCursor:null}});await pending;return host;}
for(const boundary of ['IME','pending','cancel'])test('ordinary workspace refuses '+boundary+' leave without losing its draft or session',()=>withTopicActions(async f=>{await open(f);const editor=f.owner.draft,owner=f.owner.surface;editor.value='SYNTHETIC protected';if(boundary==='IME')editor.listeners.get('compositionstart')();if(boundary==='pending'){find(owner.content,n=>n.tagName==='BUTTON'&&n.textContent==='保存想法').onclick();await tick();}if(boundary==='cancel')globalThis.confirm=()=>false;assert.equal(f.owner.leave(),false);assert.equal(f.owner.surface,owner);assert.equal(f.owner.draft,editor);assert.equal(editor.value,'SYNTHETIC protected');if(boundary==='pending')await f.respond({ok:false,error:{code:'STORAGE_FAILED'}});}));
test('workspace unknown ACK keeps exact request and late success cannot erase newer prose',()=>withTopicActions(async f=>{const host=await open(f),editor=f.owner.draft,save=find(host,n=>n.tagName==='BUTTON'&&n.textContent==='保存想法');editor.value='SYNTHETIC original';save.onclick();await tick();await f.respond({ok:false,error:{code:'TIMEOUT'}});editor.value='SYNTHETIC new prose';save.onclick();await tick();assert.deepEqual(f.calls[1],f.calls[0]);await f.respond({ok:true,data:{id:'saved'}});assert.equal(f.owner.draft,editor);assert.equal(editor.value,'SYNTHETIC new prose');}));
test('workspace Back shares explicit dirty discard and restores its original trigger once',()=>withTopicActions(async f=>{const trigger=document.createElement('button');document.body.append(trigger);trigger.focus();const host=await open(f),original=f.owner.surface.trigger;f.owner.draft.value='SYNTHETIC draft';let calls=0;f.owner.onWorkspaceChange=()=>calls++;globalThis.confirm=()=>false;find(host,n=>n.tagName==='BUTTON'&&n.textContent==='返回').onclick();assert.ok(f.owner.surface);globalThis.confirm=()=>true;find(host,n=>n.tagName==='BUTTON'&&n.textContent==='返回').onclick();assert.equal(f.owner.surface,null);assert.equal(document.activeElement,original);assert.equal(calls,1);}));
import {presentAppShell} from '../ui/app-shell-state.js';
test('single AppShell presentation hides underlying containers without changing route identity',()=>{const ids=['collection-panel','document-panel','thought-panel','settings-panel','thought-writing-workspace','archive-reader-navigator-slot'],nodes=new Map(ids.map(id=>[id,{hidden:false}])),header={hidden:false},root={getElementById:id=>nodes.get(id),querySelector:()=>header,querySelectorAll:()=>[]},route={view:'library',documentId:'same',originKey:'same-origin'};presentAppShell(root,route,{consented:true,writing:true});assert.equal(nodes.get('thought-writing-workspace').hidden,false);assert.equal(nodes.get('document-panel').hidden,true);assert.equal(header.hidden,true);assert.equal(route.originKey,'same-origin');presentAppShell(root,route,{consented:true,writing:false});assert.equal(nodes.get('document-panel').hidden,false);assert.equal(nodes.get('thought-writing-workspace').hidden,true);assert.equal(header.hidden,false);});

test('workspace Topic context follows only the actual picker and preserves literal draft',()=>withTopicActions(async f=>{const host=await open(f),context=find(host,n=>n.className==='thought-compose-context'),select=find(host,n=>n.tagName==='SELECT'),editor=f.owner.draft;assert.equal(context.textContent,'Topic');editor.value='SYNTHETIC literal';select.value='';select.onchange();assert.equal(context.textContent,'暂不加入主题');assert.equal(f.owner.draft,editor);assert.equal(editor.value,'SYNTHETIC literal');select.value='topic';select.onchange();assert.equal(context.textContent,'Topic');assert.equal(find(host,n=>n.className==='thought-compose-created-at').textContent,'创建时间为这次保存的时间');}));

import {TopicController} from '../ui/topic-workspace.js';
for(const phase of ['before','during'])test('actual Root painter defers '+phase+' hydration without consuming the existing DOM anchor',async()=>{let release,deferred=0,painted=0;const held=new Promise(resolve=>release=resolve),collection={windowRevision:1,hydrateWindow:()=>held},w=Object.assign(Object.create(TopicController.prototype),{serial:1,homeCollection:collection,actions:{surface:phase==='before'?{workspace:true}:null,onDeferredRead:()=>deferred++},paintHome:()=>painted++});const pending=w.renderHomeReader({key:'same-root',top:140});w.actions.surface={workspace:true};release(true);assert.equal(await pending,false);assert.equal(painted,0);assert.equal(deferred,1);assert.equal(w.homeCollection,collection);});
test('actual Topic painter refuses a held body hydration after writing begins',async()=>{let release,deferred=0,painted=0;const held=new Promise(resolve=>release=resolve),reader={windowRevision:1,hydrateWindow:()=>held},w=Object.assign(Object.create(TopicController.prototype),{serial:1,topicReader:reader,openIntent:2,view:'original',actions:{surface:null,onDeferredRead:()=>deferred++},renderDocument:()=>painted++});const pending=w.renderTopicReader({id:'same-entry',top:140});w.actions.surface={workspace:true};release(true);assert.equal(await pending,false);assert.equal(painted,0);assert.equal(deferred,1);});
test('direct Root paint cannot write slots during an active ordinary writing session',()=>{let deferred=0;const w=Object.assign(Object.create(TopicController.prototype),{actions:{surface:{workspace:true},onDeferredRead:()=>deferred++},personalRoot:{render(){assert.fail('must not paint Root');}}});w.paintHome({items:[],complete:true},'');assert.equal(deferred,1);});

for(const topicId of ['topic',undefined])test('workspace context is truthful while the original Topic read is pending '+(topicId||'unassigned'),()=>withTopicActions(async f=>{
 const host=document.createElement('section');document.body.append(host);
 const opening=f.owner.compose({topicId,sectionId:topicId?'named':undefined,workspace:{host}});await tick();
 const context=find(host,n=>n.className==='thought-compose-context'),editor=f.owner.draft;
 assert.equal(context.textContent,topicId?'保存到当前主题':'暂不加入主题');
 editor.value='SYNTHETIC draft while actual Topic read is held';globalThis.confirm=()=>false;
 assert.equal(f.owner.leave(),false);assert.equal(f.owner.draft,editor);assert.equal(f.calls.length,0);
 await f.respond({ok:true,data:{items:[{id:'topic',name:'SYNTHETIC qualified Topic'}],nextCursor:null}});await opening;
 assert.equal(context.textContent,topicId?'SYNTHETIC qualified Topic':'暂不加入主题');
 assert.equal(f.owner.draft,editor);assert.equal(editor.value,'SYNTHETIC draft while actual Topic read is held');assert.equal(f.calls.length,0);
}));
