import test from 'node:test';
import assert from 'node:assert/strict';
import {TopicController} from '../ui/topic-workspace.js';
const source={id:'placement',topicId:'topic',entryId:'entry',sectionId:'default',layoutGeneration:1,revision:2,lifecycle:'active'};
async function fixture(run){
 const old=Object.getOwnPropertyDescriptor(globalThis,'chrome'),writes=[],calls=[];
 let live={...source},failOnce=false;
 const w=Object.assign(Object.create(TopicController.prototype),{id:'topic',view:'original',openIntent:1,presentationIntent:1,editor:{composing:false},onStatus:()=>{},syncSectionActionControls:()=>{},flushEditors:async()=>true,topicSectionRows:async()=>[{sectionId:'default',isDefault:true,revision:0,layoutGeneration:1,title:''},{sectionId:'target',revision:0,layoutGeneration:1,title:'Target'}],form:async()=>({id:'target'}),mutate:async fn=>{try{await fn();return true;}catch{return false;}},checked:async(type,data)=>{writes.push({type,...structuredClone(data)});if(failOnce){failOnce=false;throw Error('connection lost');}return {id:'entry',revision:4,placementRevision:3,topicRevision:6};},focusSection:async()=>{},refresh:async()=>{}});
 globalThis.chrome={runtime:{sendMessage:async r=>{calls.push(r);return {ok:true,data:r.type==='GET_LIBRARY_ENTRY'?{id:'entry',revision:3,lifecycle:'active'}:r.type==='GET_LIBRARY_TOPIC'?{id:'topic',organizationRevision:5,activeLayoutGeneration:1}:r.type==='GET_LIBRARY_PATHS'?[{topicId:'topic',placement:{...live}}]:r.type==='GET_LIBRARY_PLACEMENT'?{...live}:null};}}};
 try{await run({w,writes,calls,source:{...source},setLive:v=>live=v,loseAck:()=>failOnce=true});}finally{if(old)Object.defineProperty(globalThis,'chrome',old);else delete globalThis.chrome;}
}
test('move refuses route changed while destination form was open',()=>fixture(async({w,writes,source})=>{w.form=async()=>{w.id='other';w.openIntent++;return {id:'target'};};await w.entryActions('entry',source,'section');assert.equal(writes.length,0);}));
test('move refuses source placement changed while destination form was open',()=>fixture(async({w,writes,source,setLive})=>{w.form=async()=>{setLive({...source,revision:3,sectionId:'different'});return {id:'target'};};await w.entryActions('entry',source,'section');assert.equal(writes.length,0);}));
test('unknown acknowledgement retries the identical operation payload',()=>fixture(async({w,writes,source,loseAck})=>{loseAck();await w.entryActions('entry',source,'section');await w.entryActions('entry',source,'section');assert.equal(writes.length,2);assert.deepEqual(writes[1],writes[0]);}));
for(const mode of ['IME','dirty','cancel','round-trip','view','target-removed','target-renamed','generation','source-changed-during-leave'])test('move refuses '+mode+' without a write',()=>fixture(async({w,writes,source,setLive})=>{
 if(mode==='IME')w.editor.composing=true;
 if(mode==='dirty')w.flushEditors=async()=>false;
 if(mode==='cancel')w.form=async()=>null;
 if(mode==='round-trip')w.form=async()=>{w.openIntent+=2;return {id:'target'};};
 if(mode==='view')w.form=async()=>{w.view='ai';return {id:'target'};};
 if(['target-removed','target-renamed','generation'].includes(mode)){let n=0;w.topicSectionRows=async()=>++n===1?[{sectionId:'target',revision:0,layoutGeneration:1,title:'Target'}]:mode==='target-removed'?[]:[{sectionId:'target',revision:mode==='target-renamed'?1:0,layoutGeneration:mode==='generation'?2:1,title:'Target'}];}
 if(mode==='source-changed-during-leave')w.mutate=async run=>{setLive({...source,revision:3});try{await run();return true;}catch{return false;}};
 await w.entryActions('entry',source,'section');assert.equal(writes.length,0);
}));
test('unknown result cannot be retargeted by a new choice or refreshed placement',()=>fixture(async({w,writes,source,loseAck,setLive})=>{loseAck();await w.entryActions('entry',source,'section');w.form=async()=>{throw Error('must not ask a new destination');};setLive({...source,revision:3,sectionId:'target'});await w.entryActions('entry',{...source,revision:3,sectionId:'target'},'section');assert.deepEqual(writes[1],writes[0]);assert.equal(w.entryMoveAttempts.size,0);}));
test('duplicate activation is ignored while source read is pending',()=>fixture(async({w,writes,source})=>{let release;w.flushEditors=()=>new Promise(r=>release=r);const first=w.entryActions('entry',source,'section');await Promise.resolve();await w.entryActions('entry',source,'section');release(true);await first;assert.equal(writes.length,1);assert.equal(w.entryMovePending,false);}));
test('cancelled dialog and same Section produce no operation or revision',()=>fixture(async({w,writes,source})=>{w.form=async()=>({id:'default'});await w.entryActions('entry',source,'section');assert.equal(writes.length,0);assert.equal(w.entryMoveAttempts.size,0);}));
test('actual placement owner replays lost acknowledgement once and retains body and protected history',async()=>{
 const {setup}=await import('./harness/thought-m1.mjs'),{OrganizerStore}=await import('../core/organizer/store.js');const {s}=await setup(OrganizerStore),op=()=>crypto.randomUUID(),topic=await s.createTopic({name:'SYNTHETIC move owner',operationId:op()}),section=await s.createSection({topicId:topic.id,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision,title:'Target',operationId:op()}),created=await s.continueThinking({topicId:topic.id,body:'Synthetic unchanged body',operationId:op()});
 const before=await s.entry(created.id),placement=await s.libraryPlacement(topic.id,created.id),request={entryId:created.id,topicId:topic.id,sectionId:section.sectionId,expectedEntryRevision:before.revision,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision,expectedPlacementRevision:placement.revision,operationId:op()};
 const first=await s.placeEntry(request),replayed=await s.placeEntry(structuredClone(request));assert.deepEqual(replayed,first);const after=await s.libraryPlacement(topic.id,created.id);assert.equal(after.revision,placement.revision+1);assert.equal(after.sectionId,section.sectionId);assert.equal(after.sectionProtection,true);assert.equal(after.orderProtection,true);assert.equal((await s.entry(created.id)).body,before.body);
 const stale=await s.placeEntry({...request,operationId:op()});assert.equal(stale.conflict,true);assert.deepEqual(await s.libraryPlacement(topic.id,created.id),after);
});
test('move remains busy through exact Section focus and rejects a rapid second operation',()=>fixture(async({w,writes,source})=>{let release,entered;const started=new Promise(r=>entered=r);w.focusSection=async()=>{entered();await new Promise(r=>release=r);};const pending=w.entryActions('entry',source,'section');await started;assert.equal(w.entryMovePending,true);assert.equal(w.sectionActionPending,true);await w.entryActions('entry',source,'section');assert.equal(writes.length,1);release();await pending;assert.equal(w.entryMovePending,false);assert.equal(w.sectionActionPending,false);}));
test('eight unknown moves are retained, block new entries but allow their exact retry',()=>fixture(async({w,writes,source})=>{w.entryMoveAttempts=new Map(Array.from({length:8},(_,i)=>[JSON.stringify(['topic','held-'+i]),{operationId:'held-'+i}]));await w.entryActions('entry',source,'section');assert.equal(writes.length,0);assert.equal(w.entryMoveAttempts.size,8);const request={entryId:'entry',topicId:'topic',sectionId:'target',expectedEntryRevision:3,expectedTopicRevision:5,expectedPlacementRevision:2,operationId:'original-unknown'};w.entryMoveAttempts.delete(JSON.stringify(['topic','held-0']));w.entryMoveAttempts.set(JSON.stringify(['topic','entry']),request);await w.entryActions('entry',source,'section');assert.deepEqual(writes[0].placement,request);assert.equal(w.entryMoveAttempts.size,7);}));
