import test from 'node:test';import assert from 'node:assert/strict';
import {setup} from './harness/thought-m1.mjs';import {OrganizerStore} from '../core/organizer/store.js';
const op=()=>crypto.randomUUID();
async function fixture(){const {s}=await setup(OrganizerStore);await s.finishFoundation();const topic=await s.createTopic({operationId:op(),name:'SYNTHETIC writing'}),section=await s.createSection({topicId:topic.id,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision,title:'SYNTHETIC named',operationId:op()});return {s,topic,section};}
test('explicit Section writing uses that durable identity, not default Section',async()=>{const {s,topic,section}=await fixture(),started=Date.now();const r=await s.continueThinking({operationId:op(),topicId:topic.id,sectionId:section.sectionId,body:'SYNTHETIC writing body'});const paths=await s.entryPaths(r.id);assert.equal(paths[0].sectionId,section.sectionId);const entry=await s.repository.transaction(false,t=>t.get('thoughts',r.id));assert.equal(entry.provenanceType,'user_created');assert.equal(entry.origin,'user');assert.equal(entry.bodyBinding,'thought');assert.ok(Date.parse(entry.createdAt)>=started&&Date.parse(entry.createdAt)<=Date.now());});
const rows=(s,name)=>s.repository.transaction(false,t=>t.all(name));
test('omitted Section chooses stable default and Root writing remains unassigned',async()=>{const {s,topic}=await fixture();const a=await s.continueThinking({operationId:op(),topicId:topic.id,body:'SYNTHETIC default'}),b=await s.continueThinking({operationId:op(),body:'SYNTHETIC unassigned'});assert.equal((await s.entryPaths(a.id))[0].sectionId,(await s.topic(topic.id)).defaultSectionId);assert.deepEqual(await s.entryPaths(b.id),[]);});
for(const mode of ['missing','removed','redirected','wrong-topic','no-topic'])test('explicit '+mode+' destination refuses atomically',async()=>{const {s,topic,section}=await fixture();let target=section.sectionId,topicId=topic.id;if(mode==='missing')target='missing';if(mode==='no-topic')topicId=undefined;if(mode==='wrong-topic')topicId=(await s.createTopic({operationId:op(),name:'other'})).id;if(['removed','redirected'].includes(mode))await s.repository.transaction(true,async t=>{const key=JSON.stringify([topic.id,(await t.get('topics',topic.id)).activeLayoutGeneration,target]),r=await t.get('sections',key);if(mode==='removed')r.lifecycle='removed';else r.redirectTo='another';await t.put('sections',r);});const before=await Promise.all(['thoughts','placements','operationReceipts','records'].map(x=>rows(s,x)));await assert.rejects(s.continueThinking({operationId:op(),...(topicId?{topicId}:{}),sectionId:target,body:'SYNTHETIC rejected'}));assert.deepEqual(await Promise.all(['thoughts','placements','operationReceipts','records'].map(x=>rows(s,x))),before);});
test('rename preserves Section identity; receipt replay survives later removal and never duplicates',async()=>{const {s,topic,section}=await fixture();await s.editSection({topicId:topic.id,sectionId:section.sectionId,expectedRevision:0,title:'SYNTHETIC renamed',operationId:op()});const request={operationId:op(),topicId:topic.id,sectionId:section.sectionId,body:'SYNTHETIC precise body'},sources=await rows(s,'records'),a=await s.continueThinking(request);assert.equal((await s.entryPaths(a.id))[0].sectionId,section.sectionId);const count=(await rows(s,'thoughts')).length;await s.repository.transaction(true,async t=>{const key=JSON.stringify([topic.id,(await t.get('topics',topic.id)).activeLayoutGeneration,section.sectionId]),r=await t.get('sections',key);r.lifecycle='removed';await t.put('sections',r);});assert.deepEqual(await s.continueThinking(request),a);assert.equal((await rows(s,'thoughts')).length,count);assert.deepEqual(await rows(s,'records'),sources);await assert.rejects(s.continueThinking({...request,sectionId:'different'}));});
import {withTopicActions,tick,find} from './harness/topic-action-dom.mjs';
import {TopicController} from '../ui/topic-workspace.js';
test('actual composer retries exact Section payload after unknown ACK while retaining newer text',()=>withTopicActions(async f=>{await f.owner.compose({topicId:'topic',sectionId:'named'});await f.submit('SYNTHETIC original');assert.equal(f.calls[0].sectionId,'named');await f.respond({ok:false,error:{code:'MESSAGE_CHANNEL_INTERRUPTED'}});f.owner.draft.value='SYNTHETIC newer';await f.submit();assert.deepEqual(f.calls[1],f.calls[0]);await f.respond({ok:true,data:{id:'saved'}});assert.equal(f.owner.draft.value,'SYNTHETIC newer');assert.equal(f.owner.dialog.open,true);}));
test('actual composer IME blocks writes and definitive failure preserves same editor and draft',()=>withTopicActions(async f=>{await f.owner.compose({topicId:'topic',sectionId:'named'});const editor=f.owner.draft;editor.listeners.get('compositionstart')();await f.submit('SYNTHETIC composing');assert.equal(f.calls.length,0);editor.listeners.get('compositionend')();await f.submit();await f.respond({ok:false,error:{code:'INVALID_REQUEST'}});assert.equal(f.owner.draft,editor);assert.equal(editor.value,'SYNTHETIC composing');assert.equal(f.owner.dialog.open,true);}));
test('changing Topic clears the captured Section destination in the actual composer request',()=>withTopicActions(async f=>{await f.owner.compose({topicId:'topic',sectionId:'named'});const choices=find(f.owner.content,n=>n.tagName==='DETAILS');choices.open=true;choices.listeners.get('toggle')();await tick();await f.respond({ok:true,data:{items:[{id:'topic',name:'old'},{id:'other',name:'new'}],nextCursor:null}});const checks=[];function scan(n){if(n.tagName==='INPUT'&&n.type==='checkbox')checks.push(n);for(const c of n.children)scan(c);}scan(f.owner.content);assert.equal(checks.length,2);checks[0].checked=false;checks[0].onchange();checks[1].checked=true;checks[1].onchange();assert.equal(f.owner.content.children.some(n=>n.textContent==='保存到所选章节'),false);await f.submit('SYNTHETIC other');assert.equal(f.calls[0].topicId,'other');assert.equal(Object.hasOwn(f.calls[0],'sectionId'),false);await f.respond({ok:true,data:{id:'saved'}});}));
test('controller only passes an explicit qualified same-route Section, never scroll-derived identity',async()=>{for(const mode of ['current','stale-intent','other-topic','AI']){const calls=[],w=Object.assign(Object.create(TopicController.prototype),{id:'topic',view:mode==='AI'?'ai':'original',openIntent:3,presentationIntent:2,writingSection:{topicId:mode==='other-topic'?'other':'topic',sectionId:'named',openIntent:mode==='stale-intent'?1:3,presentationIntent:2},actions:{compose:async r=>calls.push(r)}});await w.createEntry();assert.equal(calls[0].sectionId,mode==='current'?'named':undefined);assert.equal(calls[0].isCurrent(),true);w.openIntent++;assert.equal(calls[0].isCurrent(),false);}});

test('unknown ACK keeps original Section even when Topic choices round trip',()=>withTopicActions(async f=>{await f.owner.compose({topicId:'topic',sectionId:'named'});await f.submit('SYNTHETIC same');await f.respond({ok:false,error:{code:'TIMEOUT'}});const choices=find(f.owner.content,n=>n.tagName==='DETAILS');choices.open=true;choices.listeners.get('toggle')();await tick();await f.respond({ok:true,data:{items:[{id:'topic',name:'old'},{id:'other',name:'new'}],nextCursor:null}});const checks=[];function scan(n){if(n.tagName==='INPUT'&&n.type==='checkbox')checks.push(n);for(const c of n.children)scan(c);}scan(f.owner.content);for(const [i,on]of [[0,false],[1,true],[1,false],[0,true]]){checks[i].checked=on;checks[i].onchange();}await f.submit('SYNTHETIC same');assert.deepEqual(f.calls[1],f.calls[0]);await f.respond({ok:true,data:{id:'saved'}});assert.equal(f.calls.length,2);assert.equal(f.owner.dialog.open,true,'changed destination remains visible after old receipt ACK');assert.equal(f.owner.draft.value,'SYNTHETIC same');}));
test('late placement storage failure rolls back the new Entry, history, receipt and original Source',async()=>{const {s,topic,section}=await fixture(),names=['thoughts','placements','revisions','operationReceipts','records'],before=await Promise.all(names.map(n=>rows(s,n))),original=s.placeEntryInTransaction.bind(s);s.placeEntryInTransaction=async(...args)=>{await original(...args);throw Error('SYNTHETIC_STORAGE_FAILURE');};await assert.rejects(s.continueThinking({operationId:op(),topicId:topic.id,sectionId:section.sectionId,body:'SYNTHETIC rolled back'}),e=>e.code==='STORAGE_FAILED');assert.deepEqual(await Promise.all(names.map(n=>rows(s,n))),before);});
