import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {resolve} from 'node:path';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';import {thoughtPrimary} from './harness/current-thought-navigation.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(m=>chrome.runtime.sendMessage(m),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
for(const variant of ['source','release'])test('Section-aware actual writing owner '+variant,{timeout:90000},async()=>{
 const release=variant==='release'?await mkdtemp(resolve(tmpdir(),'paia-section-writing-')):null;let h;
 try{if(release)execFileSync('python3',['scripts/build_current_release.py',release],{stdio:'pipe'});h=await FakeChatGPT.start({extensionPath:release||resolve('.'),headless:true,launchThroughPort:true});const p=h.archive;await p.setViewportSize({width:1440,height:1000});await p.locator('#enable-consent').click();
 const seed=await p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local),op=()=>crypto.randomUUID();await s.finishFoundation();await s.capture({epoch:(await s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'section-writing-source',url:'https://chatgpt.com/c/section-writing-source',title:'Synthetic Source'},messages:[{sourceMessageId:'section-writing-input',pageOrder:1,originalText:'SYNTHETIC immutable Source'}]});await s.finishFoundation();const t=await s.createTopic({name:'SYNTHETIC writing destination',operationId:op()}),section=await s.createSection({topicId:t.id,expectedTopicRevision:(await s.topic(t.id)).organizationRevision,title:'SYNTHETIC named Section',operationId:op()});return {topicId:t.id,sectionId:section.sectionId,source:await s.repository.transaction(false,t=>t.all('records'))};});
 const state=()=>p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local);await s.finishFoundation();return s.repository.transaction(false,async t=>({entries:await t.all('thoughts'),placements:await t.all('placements'),sources:await t.all('records')}));});
 await p.reload();await thoughtPrimary(p,'thoughts');const sectionLink=p.locator(`.personal-topic-block[data-topic-id="${seed.topicId}"] .personal-section-link[data-section-id="${seed.sectionId}"]`);await sectionLink.click();
 await eventually(()=>p.evaluate(id=>document.activeElement?.closest('.topic-section')?.dataset.sectionId===id,seed.sectionId),'qualified Section heading arrival');await p.locator('#create-entry').click();const draft=p.locator('#topic-action-dialog textarea'),save=p.locator('#topic-action-dialog').getByRole('button',{name:'保存想法',exact:true});await draft.fill('SYNTHETIC new thought\n\n中文 é 👩🏽‍💻');assert.match(await p.locator('#topic-action-dialog').innerText(),/保存到所选章节/);
 // Rename through the real owner while the editor remains open: identity survives.
 await rpc(p,'EDIT_LIBRARY_SECTION',{edit:{topicId:seed.topicId,sectionId:seed.sectionId,expectedRevision:0,title:'SYNTHETIC renamed Section',operationId:crypto.randomUUID()}});
 // Controlled acknowledgement loss after the real worker commits, not a fake save.
 await p.evaluate(()=>{globalThis.writeTrace=[];globalThis.originalWriteSend=chrome.runtime.sendMessage;let lose=true;chrome.runtime.sendMessage=async m=>{if(m.type==='CONTINUE_THINKING'){writeTrace.push(structuredClone(m.thought));const r=await originalWriteSend(m);if(lose&&r.ok){lose=false;return {ok:false,error:{code:'MESSAGE_CHANNEL_INTERRUPTED'}};}return r;}return originalWriteSend(m);};});
 const before=await state();await save.click();await eventually(()=>p.locator('#topic-action-dialog').innerText().then(t=>t.includes('尚未确认')),'unknown ACK remains explicit');assert.equal(await draft.inputValue(),'SYNTHETIC new thought\n\n中文 é 👩🏽‍💻');await save.click();await p.locator('#topic-action-dialog').waitFor({state:'hidden'});const after=await state(),created=after.entries.filter(x=>!before.entries.some(y=>y.id===x.id));assert.equal(created.length,1);assert.equal(after.placements.find(x=>x.entryId===created[0].id).sectionId,seed.sectionId);assert.deepEqual(after.sources,seed.source);const trace=await p.evaluate(()=>writeTrace);assert.equal(trace.length,2);assert.deepEqual(trace[1],trace[0]);await p.evaluate(()=>chrome.runtime.sendMessage=originalWriteSend);
 // Existing in-app Root navigation keeps a Topic route, not a Section fragment.
 // Reload has no explicit writing destination and must use the stable default.
 assert.equal(new URL(p.url()).hash,'');await p.reload();await p.locator('#create-entry').waitFor({state:'visible'});await p.locator('#create-entry').click();await draft.fill('SYNTHETIC default after reload');await save.click();await p.locator('#topic-action-dialog').waitFor({state:'hidden'});const final=await state(),last=final.entries.find(x=>x.thoughtText==='SYNTHETIC default after reload'),topic=await rpc(p,'GET_LIBRARY_TOPIC',{id:seed.topicId});assert.equal(final.placements.find(x=>x.entryId===last.id).sectionId,topic.defaultSectionId);assert.deepEqual(final.sources,seed.source);assert.equal(final.placements.find(x=>x.entryId===created[0].id).sectionId,seed.sectionId,'earlier acknowledged Entry stays in its named Section');
 // Existing strict public Topic/Section fragment supplies a fresh explicit target.
 const direct=new URL(p.url());direct.hash='paia-thought?'+new URLSearchParams({topic:seed.topicId,section:seed.sectionId});await p.goto(direct.href);await p.reload();await eventually(()=>p.evaluate(id=>document.activeElement?.closest('.topic-section')?.dataset.sectionId===id,seed.sectionId),'strict fragment reload qualifies its exact Section');await p.locator('#create-entry').click();await draft.fill('SYNTHETIC explicit fragment reload');await save.click();await p.locator('#topic-action-dialog').waitFor({state:'hidden'});const directState=await state(),directEntry=directState.entries.find(x=>x.thoughtText==='SYNTHETIC explicit fragment reload');assert.ok(directEntry);assert.equal(directState.placements.find(x=>x.entryId===directEntry.id).sectionId,seed.sectionId);assert.deepEqual(directState.sources,seed.source);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);
 }catch(error){if(h)console.error('WRITING_DIAGNOSTIC',JSON.stringify(await h.archive.evaluate(()=>({url:location.href,active:document.activeElement?.tagName,root:document.getElementById('thought-list')?.innerText,body:document.getElementById('thought-document')?.innerText,status:document.getElementById('library-search-status')?.innerText}))),h.errors);throw error;}finally{await h?.close();if(release)await rm(release,{recursive:true,force:true});}
});
