import test from 'node:test';import assert from 'node:assert/strict';
import {PresentationNode} from './harness/presentation-dom.mjs';
import {renderTopicSectionProse} from '../ui/topic-section-prose.js';
class Node extends PresentationNode {
 constructor(tag='div'){super(tag);this.style={};}
 get innerText(){return this.textContent;}
 matches(selector){return selector.split(',').some(value=>value.startsWith('[data-')?this.parentElement?.querySelectorAll(value).includes(this):this.tagName===value.toUpperCase());}
 closest(selector){for(let node=this;node;node=node.parentElement)if(node.matches(selector))return node;return null;}
 querySelectorAll(selector){const rows=this.children.flatMap(node=>[node,...node.querySelectorAll('*')]);if(selector==='*')return rows;if(selector.startsWith('.'))return rows.filter(node=>node.classList.contains(selector.slice(1)));if(selector.startsWith('[data-')){const [,raw,value]=selector.match(/^\[data-([^=\]]+)(?:="([^"]*)")?\]$/)||[];const key=raw?.replace(/-([a-z])/g,(_,x)=>x.toUpperCase());return rows.filter(node=>key in node.dataset&&(value===undefined||node.dataset[key]===value));}return rows.filter(node=>node.tagName===selector.toUpperCase());}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 scrollIntoView(options){this.scrolled=options;}
 focus(options){super.focus();this.focusOptions=options;}
 getBoundingClientRect(){return {top:100,bottom:180,height:80};}
}
async function withDOM(run){
 const keys=['document','chrome','scrollY','scrollBy','scrollTo','requestAnimationFrame'],prior=new Map(keys.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)])),nodes=new Map(),body=new Node('body');
 const get=id=>{if(!nodes.has(id)){const node=new Node();node.id=id;nodes.set(id,node);body.append(node);}return nodes.get(id);};
 globalThis.document={body,activeElement:body,documentElement:{lang:'en'},createElement:tag=>new Node(tag),createElementNS:(_namespace,tag)=>new Node(tag),getElementById:get,querySelector:selector=>body.querySelector(selector)};globalThis.requestAnimationFrame=callback=>callback();globalThis.scrollY=0;globalThis.scrollBy=()=>{};
 const entryNode=({entry})=>{const node=new Node();node.className='library-entry';node.dataset.entryId=entry.id;const prose=new Node();prose.dataset.entryField='body';prose.className='entry-prose';prose.textContent=entry.body;node.append(prose);return node;};
 try{return await run({body:get('original-reading-body'),get,entryNode});}finally{for(const [key,descriptor]of prior)if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}
}
const page=(sections,items)=>({nextCursor:null,previousCursor:null,sectionCursor:null,kind:'section_reading',topic:{id:'topic',defaultSectionId:'default'},sections,items});

const section={sectionId:'default',topicId:'topic',rank:'1',title:'',isDefault:true};
const row=id=>({entry:{id,revision:1,lifecycle:'active',freshness:'current',staleReasons:[],body:'同一原文 👩‍💻 é\n条件保持。',title:'',note:'',type:'idea',formation:'explicit',bodyBinding:'thought',reverseEditEnabled:false,archiveChanged:false,provenanceType:'user_created',integrity:'detached',fieldRevisions:{title:0,body:0,note:0,type:0,formation:0},protections:{body:{locked:true,reason:'user_created',operationId:id,at:'2026-01-01'}}},placement:{sectionId:'default',topicId:'topic',revision:1}});
const options=items=>({enabled:true,presentation:{topicId:'topic',revision:1,stale:false,evidenceEntryIds:items.map(x=>x.entry.id)},isCurrent:()=>true});
test('actual Section renderer folds only current exact-repeat originals and expands original nodes',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')];renderTopicSectionProse({body,page:page([section],items),entryNode,repeats:options(items)});const nodes=body.querySelectorAll('[data-entry-id]');assert.equal(nodes[1].hidden,true);const button=body.querySelector('[data-exact-repeat]');assert.ok(button);button.listeners.get('click')();assert.equal(nodes[1].hidden,false);assert.equal(body.querySelectorAll('[data-entry-id]')[1],nodes[1]);assert.equal(nodes[1].firstElementChild.textContent,items[1].entry.body);}));
for(const [name,change]of Object.entries({note:x=>x.entry.note='Different manual note',title:x=>x.entry.title='Different title',negation:x=>x.entry.body+='不',whitespace:x=>x.entry.body+=' ',unicode:x=>x.entry.body=x.entry.body.normalize('NFC'),type:x=>x.entry.type='fact',binding:x=>x.entry.bodyBinding='input',protected:x=>x.entry.protections.body.reason='user_edit',unknownProtection:x=>x.entry.protections.extra={locked:true,reason:'unknown'},edited:x=>x.entry.fieldRevisions.body=1,large:x=>x.entry.large=true,stale:x=>x.entry.staleReasons=['source_changed'],missing:x=>delete x.entry.note,otherSection:x=>x.placement.sectionId='other'}))test('actual renderer leaves '+name+' distinct/unknown content unfolded',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')];change(items[1]);renderTopicSectionProse({body,page:page([section],items),entryNode,repeats:options(items)});assert.equal(body.querySelectorAll('[data-exact-repeat]').length,0);assert.ok(body.querySelectorAll('[data-entry-id]').every(n=>!n.hidden));}));
test('unprocessed evidence, stale projection, OFF, search, pins and spacer prevent folding',()=>withDOM(({body,entryNode})=>{for(const mode of ['new','stale','off','search','pins','spacer','arrival']){const items=[row('a'),row('b')],data=page([section],items),config=options(items),pins=new Set();if(mode==='new')config.presentation.evidenceEntryIds=['a'];if(mode==='stale')config.presentation.stale=true;if(mode==='off')config.enabled=false;if(mode==='search')data.query='同一';if(mode==='pins')pins.add('b');if(mode==='arrival')config.revealId='b';if(mode==='spacer')data.windowLayout=[{kind:'item',item:items[0]},{kind:'spacer',sectionId:'default',from:1,to:2,height:300},{kind:'item',item:items[1]}];renderTopicSectionProse({body,page:data,entryNode,pins,repeats:config});assert.equal(body.querySelectorAll('[data-exact-repeat]').length,0,mode);assert.ok(body.querySelectorAll('[data-entry-id]').every(n=>!n.hidden),mode);}}));
test('OFF and changed protection reveal retained original nodes; expanded run does not refold',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')],config=options(items),render=()=>renderTopicSectionProse({body,page:page([section],items),entryNode,repeats:config});render();const old=body.querySelectorAll('[data-entry-id]')[1];body.querySelector('[data-exact-repeat]').listeners.get('click')();render();assert.equal(old.hidden,false);assert.equal(body.querySelector('[data-exact-repeat]'),null);config.enabled=false;render();config.enabled=true;render();assert.equal(old.hidden,true);items[1].entry.note='User note now differs';render();assert.equal(old.hidden,false);assert.equal(body.querySelectorAll('[data-entry-id]')[1],old);}));
test('new rendering preserves noncollapsed selection and focused body without hiding it',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')],data=page([section],items);renderTopicSectionProse({body,page:data,entryNode});const nodes=body.querySelectorAll('[data-entry-id]');nodes[1].firstElementChild.focus();renderTopicSectionProse({body,page:data,entryNode,repeats:options(items)});assert.equal(nodes[1].hidden,false);assert.equal(document.activeElement,nodes[1].firstElementChild);document.activeElement=document.body;const before=globalThis.getSelection;globalThis.getSelection=()=>({rangeCount:1,isCollapsed:false,getRangeAt:()=>({intersectsNode:node=>node===nodes[1]})});try{renderTopicSectionProse({body,page:data,entryNode,repeats:options(items)});assert.equal(nodes[1].hidden,false);}finally{globalThis.getSelection=before;}}));

for(const mode of ['source','unknown'])test('two equally '+mode+' bindings stay unfolded',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')];for(const {entry}of items)if(mode==='source')entry.bodyBinding='input';else entry.provenanceType='unknown';renderTopicSectionProse({body,page:page([section],items),entryNode,repeats:options(items)});assert.equal(body.querySelector('[data-exact-repeat]'),null);}));
for(const event of ['input','compositionstart'])test('first original '+event+' reveals other originals immediately',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')];renderTopicSectionProse({body,page:page([section],items),entryNode,repeats:options(items)});const nodes=body.querySelectorAll('[data-entry-id]');body.listeners.get(event)({target:nodes[0].firstElementChild});assert.equal(nodes[1].hidden,false);assert.equal(body.querySelector('[data-exact-repeat]'),null);}));
test('existing fold is revealed when retained DOM differs from qualified DTO',()=>withDOM(({body,entryNode})=>{const items=[row('a'),row('b')],render=()=>renderTopicSectionProse({body,page:page([section],items),entryNode,repeats:options(items)});render();const nodes=body.querySelectorAll('[data-entry-id]');nodes[0].firstElementChild.textContent='SYNTHETIC unsaved human draft';render();assert.equal(nodes[1].hidden,false);assert.equal(nodes[0].firstElementChild.textContent,'SYNTHETIC unsaved human draft');}));
