import {conversation} from './fixtures/history-v090.mjs';
import {chooseConsumerGroup as chooseGroup} from './harness/settings-consumer-presentation.mjs';
import {historicalBackupItems} from './harness/historical-backup-browser.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile,mkdtemp,rm} from 'node:fs/promises';
import {execFile} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {promisify} from 'node:util';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';

const execFileAsync=promisify(execFile);
const rpc=async(page,type,fields={})=>{const response=await page.evaluate(message=>chrome.runtime.sendMessage(message),{type,...fields});assert.equal(response.ok,true,JSON.stringify(response));return response.data;};
async function consent(page){const action=page.locator('#enable-consent');await action.waitFor({state:'visible'});await eventually(async()=>!(await action.isDisabled()));await action.click();await eventually(async()=>(await rpc(page,'GET_STATUS')).consented===true);const onboarding=await rpc(page,'GET_ONBOARDING');assert.equal(onboarding.step,'history');assert.equal(onboarding.historyState,'not_started');assert.equal(await page.locator('#onboarding-history-step').isVisible(),false,'Archive hides the card without skipping optional import');}

async function openData(page){
 const compact=await page.evaluate(()=>innerWidth<768);
 await eventually(()=>page.evaluate(compact=>{const button=document.querySelector('.sidebar [data-view="settings"]'),menu=document.getElementById('archive-compact-navigation');return compact?button?.parentElement?.id==='archive-compact-nav-items'&&menu.hidden===false:button?.parentElement?.classList.contains('sidebar-bottom');},compact),'Settings primary control has settled in its real breakpoint owner');
 if(compact){await page.locator('#archive-compact-navigation > summary').click();await page.locator('#archive-compact-nav-items [data-view="settings"]').click();}else await page.locator('.sidebar-bottom [data-view="settings"]').click();await eventually(()=>page.locator('#settings-panel').isVisible());await chooseGroup(page,'data');}
async function shot(page,name){await mkdir('work/ux-r6',{recursive:true});await page.screenshot({path:`work/ux-r6/${name}.png`,fullPage:true});}
async function assertNoNetwork(h){assert.equal(h.deepSeekRequests.length,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);}

async function assertDataOwners(page){
 const group=page.locator('[data-group="data"]');
 for(const id of ['backup-settings','r6-source-records']){
  const item=page.locator(`#${id}`);assert.equal(await item.count(),1,`${id} keeps one DOM owner`);assert.equal(await item.evaluate(el=>el.closest('.ux-settings-group')?.dataset.group),'data',`${id} remains in its Data destination`);
 }
 const destinations=await group.locator(':scope > details.ux-settings-detail > summary').allTextContents();assert.deepEqual(destinations,['从已有 PAIA 备份恢复','已移除的内容']);assert.equal(await group.locator('#settings-storage').count(),1);assert.equal(await page.locator('#r6-data-status').count(),1);assert.equal(await page.locator('#r6-data-status').evaluate(node=>node.closest('dialog')?.id),'settings-storage-dialog');assert.equal(await page.locator('#product-diagnostics').isVisible(),false,'fault-only maintenance is not an ordinary Data destination');
 assert.equal(await page.locator('#backup-settings #r6-complete-export').count(),0,'complete export is not nested inside Backup');
 assert.equal(await page.locator('#backup-create').count(),0);assert.equal(await page.locator('#backup-settings #backup-choose').count(),1);
 assert.equal(await page.locator('#r6-complete-export,#r6-export-json,#r6-export-markdown').count(),0);
 assert.equal(await page.locator('#r6-data-status #r6-storage-estimate').count(),1);assert.equal(await page.locator('#r6-last-backup').count(),0);
 assert.equal(await page.locator('#r6-source-records [data-view="archive"]').count(),1,'scoped Source Records keeps its existing navigation owner');
 for(const id of ['backup-choose','backup-restore'])assert.equal(await page.locator(`#${id}`).count(),1,`${id} is not duplicated`);
assert.equal(await group.locator('#settings-ai-context').count(),0,'Context has no duplicate Data owner');
}

async function readOnlyDetails(page,variant){
 const viewport=page.viewportSize(),saved=(await rpc(page,'GET_PAGE',{page:{view:'settings'}})).preferences,originalLanguage=await page.evaluate(()=>document.documentElement.lang);
 try{await rpc(page,'UPDATE_PREFERENCES',{changes:{language:'en',appearance:'dark'}});await eventually(()=>page.evaluate(()=>document.documentElement.lang==='en'));await page.setViewportSize({width:320,height:900});for(const [group,id]of [['data','settings-storage'],['privacy','settings-supported-sites-open']]){await chooseGroup(page,group);const row=page.locator('#'+id),dialog=page.locator('#'+id+'-dialog');await row.focus();await page.keyboard.press('Enter');await dialog.waitFor({state:'visible'});assert.equal(await dialog.getAttribute('aria-labelledby'),id+'-title');assert.equal(await dialog.locator('.ux-settings-detail-close').evaluate(node=>document.activeElement===node),true);await page.keyboard.press('Tab');assert.equal(await dialog.evaluate(node=>node.contains(document.activeElement)),true,'native modal retains keyboard focus');await dialog.evaluate(node=>{globalThis.__detailFont=[...node.querySelectorAll('h2,p,button')].map(el=>({el,size:el.style.fontSize}));for(const {el}of __detailFont)el.style.fontSize=(parseFloat(getComputedStyle(el).fontSize)*2)+'px';});assert.ok(await dialog.evaluate(node=>node.scrollWidth-node.clientWidth)<=2);await shot(page,`set2-${variant}-${id}-320-dark-en-2x`);await dialog.evaluate(()=>{for(const {el,size}of __detailFont)el.style.fontSize=size;delete globalThis.__detailFont;});await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await row.evaluate(node=>document.activeElement===node),true);await row.click();await dialog.waitFor({state:'visible'});await page.evaluate(()=>history.back());await dialog.waitFor({state:'hidden'});assert.equal(await page.locator('#settings-panel').isVisible(),true);assert.equal(await row.evaluate(node=>document.activeElement===node),true,'Browser Back returns to the same destination');}
 await chooseGroup(page,'data');await page.evaluate(()=>{globalThis.__storageEstimate=navigator.storage.estimate.bind(navigator.storage);navigator.storage.estimate=async()=>({quota:1048576});});try{await page.locator('#settings-storage').click();await eventually(async()=>/not available/.test(await page.locator('#r6-storage-estimate').textContent()));assert.match(await page.locator('#settings-storage').textContent(),/Unknown/);await page.keyboard.press('Escape');await page.evaluate(()=>{navigator.storage.estimate=async()=>{throw Error('synthetic estimate failure');};});await page.locator('#settings-storage').click();await eventually(async()=>/Could not read/.test(await page.locator('#r6-storage-estimate').textContent()));assert.equal(await page.locator('#r6-storage-estimate').isVisible(),true);assert.match(await page.locator('#settings-storage').textContent(),/Unavailable/);await shot(page,`set2-${variant}-storage-read-error`);await page.keyboard.press('Escape');}finally{await page.evaluate(()=>{navigator.storage.estimate=__storageEstimate;delete globalThis.__storageEstimate;});}
 }finally{await page.evaluate(()=>{for(const {el,size}of globalThis.__detailFont||[])el.style.fontSize=size;delete globalThis.__detailFont;for(const dialog of document.querySelectorAll('.ux-settings-detail-dialog[open]'))dialog.close();});if(viewport)await page.setViewportSize(viewport);await rpc(page,'UPDATE_PREFERENCES',{changes:{language:saved.language,appearance:saved.appearance}});await eventually(()=>page.evaluate(language=>document.documentElement.lang===language,originalLanguage));await chooseGroup(page,'data');}
}

async function rejectAndReselectBackup(page,backupBytes){
 const destination=page.locator('details').filter({has:page.locator('#backup-settings')});if(!await page.locator('#backup-choose').isVisible())await destination.locator(':scope > summary').click();
 const invalid={name:'S05-invalid.paia-backup',mimeType:'application/x-ndjson',buffer:Buffer.from('{"not":"a PAIA backup"}\n')};
 const choose=async files=>{const picker=page.waitForEvent('filechooser');await page.locator('#backup-choose').click();await (await picker).setFiles(files);};
 await page.evaluate(()=>{globalThis.__s05Picker=document.getElementById('backup-choose');globalThis.__s05File=document.getElementById('backup-file');});
 await choose(invalid);await page.locator('#backup-settings[data-inspection-failure]').waitFor();await eventually(()=>page.locator('#backup-failure-return').isEnabled());
 assert.equal(await page.locator('#backup-restore').isDisabled(),true);assert.equal(await page.locator('h1:visible').count(),1);assert.equal(await page.locator('#backup-failure-page-title').isVisible(),true);assert.equal((await page.locator('#history-settings:visible,#onboarding-history-step:visible').count())===1,false,'backup rejection isolates the history destination');
 const reason=await page.locator('#backup-status').innerText();await choose([]);assert.equal(await page.locator('#backup-status').innerText(),reason,'empty picker result leaves the rejected inspection visible');
 await choose(invalid);await eventually(()=>page.locator('#backup-failure-return').isEnabled());assert.equal(await page.locator('#backup-status').innerText(),reason,'the same rejected file can be chosen again');
 await page.locator('#backup-failure-return').focus();await page.keyboard.press('Enter');await page.locator('#backup-settings[data-inspection-failure]').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>document.activeElement?.id),'backup-choose');assert.equal((await page.locator('#history-settings:visible,#onboarding-history-step:visible').count())===1,true,'backup return restores the history destination');assert.equal(await page.locator('#r6-export-json').count(),0);await assertDataOwners(page);
 await choose(invalid);await page.locator('#backup-settings[data-inspection-failure]').waitFor();await eventually(()=>page.locator('#backup-choose').isEnabled());
 await choose({name:'UIR-04-data.paia-backup',mimeType:'application/x-ndjson',buffer:backupBytes});await page.locator('#backup-preview').waitFor({state:'visible'});
 assert.equal(await page.locator('#backup-settings[data-inspection-failure]').count(),0);assert.equal(await page.locator('#backup-failure-page-title').isVisible(),false);assert.equal((await page.locator('#history-settings:visible,#onboarding-history-step:visible').count())===1,true,'backup return restores the history destination');
 assert.equal(await page.evaluate(()=>globalThis.__s05Picker===document.getElementById('backup-choose')&&globalThis.__s05File===document.getElementById('backup-file')),true,'failed and valid inspections keep the same picker and file owners');

 // Locale-only rendering must not change recovery authority or selected files.
 await page.evaluate(()=>{const original=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__backupLocale={original,calls:[],file:document.getElementById('backup-file').files[0],nodes:[...document.getElementById('backup-preview-content').children]};chrome.runtime.sendMessage=async m=>{globalThis.__backupLocale.calls.push(m.type);return original(m);};document.getElementById('backup-cancel').focus();document.documentElement.lang='en';});
 try{
  await eventually(()=>page.locator('#backup-status').textContent().then(t=>t==='Check the backup details and confirm the selected restore mode.'));
  assert.equal(await page.locator('#backup-mode option[value=replace]').textContent(),'Replace the current library');
  assert.match(await page.locator('#backup-confirm-replace-label').textContent(),/replacement will clear the current library/);
  assert.equal(await page.evaluate(()=>document.getElementById('backup-file').files[0]===globalThis.__backupLocale.file),true);
  assert.equal(await page.evaluate(()=>globalThis.__backupLocale.nodes.every((n,i)=>n===document.getElementById('backup-preview-content').children[i])),true);
  assert.equal(await page.evaluate(()=>document.activeElement?.id),'backup-cancel');
  await page.evaluate(()=>{document.documentElement.lang='zh-CN';});await eventually(()=>page.locator('#backup-status').textContent().then(t=>t==='请核对备份信息并确认所选恢复方式。'));
  assert.deepEqual(await page.evaluate(()=>globalThis.__backupLocale.calls),[]);
 }finally{await page.evaluate(()=>{chrome.runtime.sendMessage=globalThis.__backupLocale.original;document.documentElement.lang='zh-CN';delete globalThis.__backupLocale;});}
 // Hold an actual CANCEL response: stale preview and programmatic file events
 // must not send a restore or start a second session while cancellation owns it.
 await page.evaluate(()=>{const original=chrome.runtime.sendMessage.bind(chrome.runtime),state={calls:[],held:false,release:null};globalThis.__backupCancelRace=state;state.original=original;chrome.runtime.sendMessage=async message=>{if(message.type.startsWith('PAIA_BACKUP_'))state.calls.push(message.type);const result=await original(message);if(message.type==='PAIA_BACKUP_CANCEL'&&!state.held){state.held=true;await new Promise(resolve=>state.release=resolve);}return result;};});
 try{
  await page.locator('#backup-cancel').click();await eventually(()=>page.evaluate(()=>globalThis.__backupCancelRace.held));
  assert.equal(await page.locator('#backup-choose').isDisabled(),true);assert.equal(await page.locator('#backup-restore').isDisabled(),true);
  await page.evaluate(()=>{document.getElementById('backup-restore').dispatchEvent(new MouseEvent('click'));document.getElementById('backup-file').dispatchEvent(new Event('change'));document.getElementById('backup-file').dispatchEvent(new Event('change'));document.getElementById('backup-cancel').dispatchEvent(new MouseEvent('click'));});
  assert.deepEqual(await page.evaluate(()=>globalThis.__backupCancelRace.calls),['PAIA_BACKUP_CANCEL']);
  await page.evaluate(()=>globalThis.__backupCancelRace.release());await eventually(()=>page.locator('#backup-choose').isEnabled());assert.equal(await page.locator('#backup-preview').isVisible(),false);
 }finally{await page.evaluate(()=>{globalThis.__backupCancelRace.release?.();chrome.runtime.sendMessage=globalThis.__backupCancelRace.original;delete globalThis.__backupCancelRace;});}
 await choose({name:'UIR-04-data.paia-backup',mimeType:'application/x-ndjson',buffer:backupBytes});await page.locator('#backup-preview').waitFor({state:'visible'});await eventually(()=>page.locator('#backup-choose').isEnabled());
 await page.evaluate(()=>{delete globalThis.__s05Picker;delete globalThis.__s05File;});
}

async function pendingInputDialogSafety(h){
 const p=h.archive;await openData(p);const detail=p.locator('details').filter({has:p.locator('#settings-history')});if(!await p.locator('#settings-history').isVisible())await detail.locator(':scope > summary').click();await p.locator('#settings-history').click();const a=conversation(9101,1),b=conversation(9102,1),c=conversation(9104,1),d=conversation(9105,1),e=conversation(9106,1);for(const item of [a,b,c,d,e])delete item.current_node;
 await p.locator('#history-file-consent').check();await p.locator('#history-file').setInputFiles({name:'synthetic-pending-owner.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([a,b,conversation(9103,1),c,d,e]))});await eventually(()=>p.locator('#history-commit').isEnabled());await p.locator('#history-commit').click();await eventually(()=>p.locator('#history-success').isVisible());const state=await h.state(),pending=state.library.blocks.filter(x=>x.branchStatus),target=state.conversations.find(d=>d.sourceConversationId===conversation(9103).id);assert.equal(pending.length,5);assert.ok(target);await p.locator('#history-review').click();
 const open=async row=>{await p.locator('.conversation-document[data-document-id="'+row.documentId+'"]').click();await p.getByRole('button',{name:'归入现有聊天窗口',exact:true}).click();};
 await p.evaluate(()=>{const original=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__pendingDialog={original,reads:0,writes:0,releases:[],held:false};chrome.runtime.sendMessage=async m=>{const response=await original(m);if(m.type==='GET_PAGE'&&m.page?.view==='library'&&!m.page.documentId&&++__pendingDialog.reads===1)await new Promise(r=>__pendingDialog.releases.push(r));if(m.type==='IMPORT_RESOLVE_BRANCH'){__pendingDialog.writes++;__pendingDialog.held=true;await new Promise(r=>__pendingDialog.releases.push(r));}return response;};});
 try{
  await open(pending[0]);await eventually(()=>p.evaluate(()=>__pendingDialog.releases.length===1));assert.equal(await p.locator('#review-assign').isEnabled(),false);await p.locator('#review-dialog-close').click();await p.locator('#back').click();await open(pending[1]);await eventually(()=>p.locator('#review-assign').isEnabled());await p.locator('#review-document').selectOption(target.id);await p.evaluate(()=>__pendingDialog.releases.shift()());await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await p.locator('#review-document').inputValue(),target.id);
  await p.locator('#review-assign').click();await eventually(()=>p.evaluate(()=>__pendingDialog.held));await p.locator('#review-assign').evaluate(n=>n.dispatchEvent(new MouseEvent('click')));assert.equal(await p.evaluate(()=>__pendingDialog.writes),1);assert.equal((await rpc(p,'GET_INPUT',{id:pending[1].id})).documentId,target.id,'real B assignment commits while acknowledgement held');await p.locator('#review-dialog-close').click();await p.locator('#back').click();await open(pending[0]);await eventually(()=>p.locator('#review-assign').isEnabled());const selected=await p.locator('#review-document').inputValue();await p.evaluate(()=>__pendingDialog.releases.shift()());await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await p.locator('#review-dialog').isVisible(),true);assert.equal(await p.locator('#review-document').inputValue(),selected);assert.ok((await rpc(p,'GET_INPUT',{id:pending[0].id})).branchStatus,'late B acknowledgement never assigns A');await p.locator('#review-dialog-close').click();
 }finally{await p.evaluate(()=>{for(const release of __pendingDialog.releases)release();chrome.runtime.sendMessage=__pendingDialog.original;delete globalThis.__pendingDialog;});}
 for(const [row,label,action] of [[pending[0],'保留为独立整理文档','standalone'],[pending[2],'忽略','ignore']]){
  await openData(p);const detail=p.locator('details').filter({has:p.locator('#manage-excluded')});if(!await p.locator('#manage-excluded').isVisible())await detail.locator(':scope > summary').click();await p.locator('#manage-excluded').click();await p.locator('.conversation-document[data-document-id="'+row.documentId+'"]').click();
  await p.evaluate(()=>{const original=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__pendingAction={original,calls:0,release:null};chrome.runtime.sendMessage=async m=>{if(m.type!=='IMPORT_RESOLVE_BRANCH')return original(m);__pendingAction.calls++;const result=await original(m);await new Promise(r=>__pendingAction.release=r);return result;};});
  try{const button=p.getByRole('button',{name:label,exact:true});await button.evaluate(n=>__pendingAction.button=n);await button.click();await eventually(()=>p.evaluate(()=>!!__pendingAction.release));await p.evaluate(()=>__pendingAction.button.dispatchEvent(new MouseEvent('click')));assert.equal(await p.evaluate(()=>__pendingAction.calls),1);const saved=await rpc(p,'GET_INPUT',{id:row.id});assert.equal(!!saved.branchStatus,false);assert.equal(saved.excluded,action==='ignore','real standalone/ignore durability before UI ACK');await openData(p);const route=await p.evaluate(()=>JSON.stringify(history.state)),status=await p.locator('#review-result').textContent();await p.evaluate(()=>__pendingAction.release());await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await p.locator('#settings-panel').isVisible(),true);assert.equal(await p.evaluate(()=>JSON.stringify(history.state)),route);assert.equal(await p.locator('#review-result').textContent(),status,'late action ACK leaves current result UI unchanged');}
  finally{await p.evaluate(()=>{__pendingAction.release?.();chrome.runtime.sendMessage=__pendingAction.original;delete globalThis.__pendingAction;});}
 }
 for(const [row,label,copy] of [[pending[3],'保留为独立整理文档','已确认归属。'],[pending[4],'忽略','已移入已移除输入；来源保留，可以恢复。']]){
  await openData(p);const detail=p.locator('details').filter({has:p.locator('#manage-excluded')});if(!await p.locator('#manage-excluded').isVisible())await detail.locator(':scope > summary').click();await p.locator('#manage-excluded').click();await p.locator('.conversation-document[data-document-id="'+row.documentId+'"]').click();await p.getByRole('button',{name:label,exact:true}).click();await eventually(async()=>await p.locator('#review-result').isVisible()&&(await p.locator('#review-result').textContent()).includes(copy));assert.equal(!!(await rpc(p,'GET_INPUT',{id:row.id})).branchStatus,false,'last pending row commits and displays its own result');
 }
 assert.deepEqual((await h.state()).records,state.records,'Source bytes unchanged by assignment');await openData(p);
}

async function removedInputSafety(h){
 const page=h.archive,marker='SYNTHETIC SET2 removed Input owner';await h.open({id:'set2-removed-input',title:'SET2 removed Input',base:1609459200,messages:[{id:'set2-removed-input-message',text:marker}]});await eventually(async()=>(await h.state()).records.some(r=>r.originalText===marker));await page.bringToFront();
 const index=await rpc(page,'GET_PAGE',{page:{view:'library',limit:100}}),doc=index.documents.find(d=>d.originalConversationTitle==='SET2 removed Input');assert.ok(doc);const data=await rpc(page,'GET_PAGE',{page:{view:'library',documentId:doc.id,limit:100}}),input=data.library.blocks[0];assert.equal(data.library.blocks.length,1);assert.equal(input.documentId,doc.id);
 const show=async()=>{await openData(page);const detail=page.locator('details').filter({has:page.locator('#manage-excluded')});if(!await page.locator('#manage-excluded').isVisible())await detail.locator(':scope > summary').click();await page.locator('#manage-excluded').click();await page.locator('.conversation-document[data-document-id="'+doc.id+'"]').click();await page.getByRole('button',{name:'恢复到输入档案',exact:true}).waitFor();};
 await rpc(page,'EXCLUDE_LIBRARY',{id:input.id,excluded:true});await show();
 await page.evaluate(()=>{const original=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__inputRestore={original,calls:0,held:false,release:null,button:[...document.querySelectorAll('.review-actions button')].find(n=>n.textContent==='恢复到输入档案')};chrome.runtime.sendMessage=async message=>{if(message.type==='EXCLUDE_LIBRARY'&&message.excluded===false){__inputRestore.calls++;const response=await original(message);__inputRestore.held=true;await new Promise(r=>__inputRestore.release=r);return response;}return original(message);};});
 try{await page.getByRole('button',{name:'恢复到输入档案',exact:true}).click();await eventually(()=>page.evaluate(()=>__inputRestore.held));await page.evaluate(()=>__inputRestore.button.dispatchEvent(new MouseEvent('click')));assert.equal(await page.evaluate(()=>__inputRestore.calls),1);assert.equal((await rpc(page,'GET_INPUT',{id:input.id})).excluded,false,'real restore commits despite held acknowledgement');await openData(page);const history=await page.evaluate(()=>JSON.stringify(window.history.state));await page.evaluate(()=>__inputRestore.release());await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.locator('#settings-panel').isVisible(),true);assert.equal(await page.evaluate(()=>JSON.stringify(window.history.state)),history,'old restore cannot steal current Settings route');}
 finally{await page.evaluate(()=>{__inputRestore.release?.();chrome.runtime.sendMessage=__inputRestore.original;delete globalThis.__inputRestore;});}
 await rpc(page,'EXCLUDE_LIBRARY',{id:input.id,excluded:true});await show();await page.getByRole('button',{name:'恢复到输入档案',exact:true}).click();await eventually(()=>page.locator('#document-panel').isVisible());assert.equal((await rpc(page,'GET_INPUT',{id:input.id})).excluded,false);assert.match(await page.locator('#document-body').textContent(),/SYNTHETIC SET2 removed Input owner/);await openData(page);
}

async function removedListSafety(page){
 await page.setViewportSize({width:1440,height:900});await chooseGroup(page,'data');
 const topic=await rpc(page,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC removed Topic',operationId:crypto.randomUUID()}});
 const ids=[];for(let i=0;i<41;i++){const row=await rpc(page,'CONTINUE_THINKING',{thought:{body:'SYNTHETIC removed Entry '+i,operationId:crypto.randomUUID()}});const current=await rpc(page,'GET_LIBRARY_ENTRY',{id:row.id});await rpc(page,'REMOVE_LIBRARY_ENTRY',{edit:{id:row.id,expectedRevision:current.revision,operationId:crypto.randomUUID()}});ids.push(row.id);}
 await rpc(page,'REMOVE_LIBRARY_TOPIC',{edit:{id:topic.id,expectedRevision:topic.revision,operationId:crypto.randomUUID()}});
 const details=page.locator('details').filter({has:page.locator('#library-management')});if(!await page.locator('#library-management > summary').isVisible())await details.locator(':scope > summary').click();if(!await page.locator('#library-removed').isVisible())await page.locator('#library-management > summary').click();
 const hold=async(type,cursorOnly=false)=>page.evaluate(({type,cursorOnly})=>{const original=chrome.runtime.sendMessage.bind(chrome.runtime);let release;const gate=new Promise(r=>release=r);window.__removedRead={original,release,count:0,held:false};chrome.runtime.sendMessage=async(message,...args)=>{const result=await original(message,...args);if(message.type===type&&(!cursorOnly||message.options?.cursor)){window.__removedRead.count++;window.__removedRead.held=true;await gate;}return result;};},{type,cursorOnly});
 const release=async()=>{await page.evaluate(()=>{const state=window.__removedRead;chrome.runtime.sendMessage=state.original;state.release();});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));};
 try{
  await hold('GET_LIBRARY_REMOVED_TOPICS');await page.locator('#library-removed-topics').click();await eventually(()=>page.evaluate(()=>window.__removedRead.held));await page.locator('#library-removed').click();await eventually(()=>page.locator('#library-management-list').getByRole('button',{name:'恢复内容',exact:true}).count().then(n=>n===40));await release();assert.equal(await page.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).count(),0,'old Topic response cannot replace Entry list');
  await hold('GET_LIBRARY_REMOVED',true);const more=page.locator('#library-management-list').getByRole('button',{name:'更多已删除内容',exact:true});await more.click();await eventually(()=>page.evaluate(()=>window.__removedRead.held));assert.equal(await more.isDisabled(),true);assert.equal(await page.evaluate(()=>window.__removedRead.count),1);await release();await eventually(()=>page.locator('#library-management-list').getByRole('button',{name:'恢复内容',exact:true}).count().then(n=>n===41));assert.equal(await more.count(),0,'terminal page removes the consumed cursor control');
  await hold('RESTORE_LIBRARY_ENTRY');await page.locator('#library-management-list').getByRole('button',{name:'恢复内容',exact:true}).first().click();await eventually(()=>page.evaluate(()=>window.__removedRead.held));await page.locator('#library-removed-topics').click();await eventually(()=>page.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).count().then(n=>n===1));await release();assert.equal(await page.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).count(),1,'late restore ACK cannot steal newer Topic list');
  const restored=[];for(const id of ids){const row=await rpc(page,'GET_LIBRARY_ENTRY',{id});if(row.lifecycle!=='removed')restored.push(id);assert.match(row.body,/^SYNTHETIC removed Entry /);}assert.equal(restored.length,1,'only explicitly selected Entry is restored');
  await hold('GET_LIBRARY_REMOVED');await page.locator('#library-removed').click();await eventually(()=>page.evaluate(()=>window.__removedRead.held));await chooseGroup(page,'reading');await chooseGroup(page,'data');await release();assert.equal(await page.locator('#library-management-list').getByRole('button',{name:'恢复主题',exact:true}).count(),1,'leaving and reopening invalidates the old list response');
  await page.locator('#library-removed').click();await eventually(()=>page.locator('#library-management-list').getByRole('button',{name:'恢复内容',exact:true}).count().then(n=>n===40));
 }finally{await page.evaluate(()=>{const state=window.__removedRead;if(state){chrome.runtime.sendMessage=state.original;state.release();delete window.__removedRead;}});}
}

async function sourceAndBackup(marker){
 const h=await FakeChatGPT.start({onboarding:true});let backupBytes;
 try{
  const page=h.archive;await consent(page);await rpc(page,'UPDATE_PREFERENCES',{changes:{language:'zh-CN',appearance:'light'}});
  await h.open({id:'uir04-data-source',title:'UIR-04 数据恢复',base:1609459200,messages:[{id:'uir04-data-message',text:marker}]});await eventually(async()=>(await h.state()).records.some(row=>row.originalText===marker));await page.bringToFront();
  await page.setViewportSize({width:1440,height:900});await openData(page);await assertDataOwners(page);await eventually(async()=>!(await page.locator('#r6-storage-estimate').textContent()).includes('正在读取'));
  await removedInputSafety(h);await pendingInputDialogSafety(h);await readOnlyDetails(page,'source');const before=await h.state();backupBytes=Buffer.from((await historicalBackupItems(page)).map(row=>JSON.stringify(row)).join('\n')+'\n');assert.deepEqual(await h.state(),before,'historical fixture encoding is read-only');
  await shot(page,'uir-04-data-1440x900-light');await page.setViewportSize({width:390,height:844});await assertDataOwners(page);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=2);await shot(page,'uir-04-data-390x844-light');await removedListSafety(page);await assertNoNetwork(h);
 }finally{await h.close();}
 return backupBytes;
}

async function restoreJourney(backupBytes,marker){
 const h=await FakeChatGPT.start({onboarding:true});
 try{
  const page=h.archive;await consent(page);await openData(page);const before=await h.state();await rejectAndReselectBackup(page,backupBytes);assert.deepEqual(await h.state(),before,'rejected/preview-only inspections never change the current library');
  await eventually(()=>page.locator('#backup-preview').isVisible(),'restore preview is explicit');assert.equal(await page.locator('#backup-restore').isEnabled(),true,'validated empty-library restore requires the explicit confirm action');assert.match(await page.locator('#backup-status').textContent(),/请核对/);await shot(page,'uir-04-data-restore-preview');
  await page.locator('#backup-restore').click();await eventually(async()=>/恢复已完成/.test(await page.locator('#backup-status').textContent()),'explicit restore completes');
  const index=await rpc(page,'GET_PAGE',{page:{view:'archive',limit:100}}),doc=index.documents.find(row=>row.originalConversationTitle==='UIR-04 数据恢复');assert.ok(doc?.id);const records=await rpc(page,'GET_PAGE',{page:{view:'archive',documentId:doc.id,limit:100}});assert.ok(records.records.some(row=>row.originalText===marker));await assertDataOwners(page);await assertNoNetwork(h);
 }finally{await h.close();}
}

async function releaseJourney(backupBytes){
 const releasePath=await mkdtemp(join(tmpdir(),'paia-uir04-data-release-'));await execFileAsync('python3',['scripts/build_current_release.py',releasePath],{cwd:process.cwd(),maxBuffer:16*1024*1024});const h=await FakeChatGPT.start({extensionPath:releasePath,onboarding:true});
 try{const page=h.archive;await consent(page);await page.setViewportSize({width:390,height:844});await openData(page);await assertDataOwners(page);await readOnlyDetails(page,'release');assert.equal(await page.locator('#filter-advanced').count(),0,'current release keeps diagnostics pruning');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=2);await shot(page,'uir-04-current-release-data-390x844-light');const before=await h.state();await rejectAndReselectBackup(page,backupBytes);assert.deepEqual(await h.state(),before,'release inspection never commits a restore');assert.equal(await page.locator('#backup-restore').isEnabled(),true);await page.locator('#backup-cancel').click();assert.equal(await page.locator('#backup-preview').isVisible(),false);await removedListSafety(page);await removedInputSafety(h);await pendingInputDialogSafety(h);await assertNoNetwork(h);}finally{await h.close();await rm(releasePath,{recursive:true,force:true});}
}

test('UIR-04 Data & devices separates Backup, complete export, local status and scoped Source owners while preserving explicit restore in source and current release Chrome',{timeout:300000},async()=>{
 const marker='UIR04_DATA_PRIVATE synthetic input for local-only data presentation.';const backupBytes=await sourceAndBackup(marker);assert.ok(backupBytes?.length);await restoreJourney(backupBytes,marker);await releaseJourney(backupBytes);
});
