import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,rows} from './harness/original-complete.mjs';
import {MemoryService} from '../core/memory/service.js';
import {PassportService} from '../core/passport.js';
import {ContextPackageService} from '../core/context-package-service.js';
const op=()=>crypto.randomUUID();
async function setup(){const f=await completeFixture({texts:['AUTH_MATCH 可核验的合成材料']}),memory=new MemoryService(f.s),passport=new PassportService(f.s),service=new ContextPackageService(memory,passport);await memory.ready();const b=(await rows(f.s,'blocks'))[0].value,topic=await f.s.createTopic({name:'授权范围',operationId:op()}),entry=await f.s.addToTopics({kind:'input',id:b.id,expectedRevision:b.revision,topicIds:[topic.id],operationId:op()});await memory.authorize({topicIds:[topic.id],decision:'allowed'});return {...f,memory,passport,service,b,topic,entry};}
test('UX-R4 grant-bound identity keeps once consumption, revocation, scope and intent fences independently of manual output',async()=>{const f=await setup(),built=await f.service.build({query:'AUTH_MATCH'}),grant=await f.passport.create({consumer:'chatgpt',purpose:'research',duration:'once'});await f.service.bind(built.previewId,grant.grantId);await assert.rejects(f.service.share({previewId:built.previewId,format:'copy'}),{code:'MEMORY_DENIED'});await assert.rejects(f.service.manual({action:'read',selectionId:built.previewId,generation:0},'tab'),{code:'MEMORY_EXPIRED'});const results=await Promise.allSettled([1,2].map(()=>f.service.share({previewId:built.previewId,grantId:grant.grantId,format:'copy'})));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.passport.status()).grants[0].useCount,1);const next=await f.service.build({query:'AUTH_MATCH'}),revoked=await f.passport.create({consumer:'claude',purpose:'writing',duration:'7d'});await f.service.bind(next.previewId,revoked.grantId);await f.passport.revoke(revoked.grantId);await assert.rejects(f.service.share({previewId:next.previewId,grantId:revoked.grantId}),{code:'MEMORY_DENIED'});assert.equal(f.requests.length,0);});
test('UX-R4 mixed generated paragraphs inherit every evidence restriction and clear output on purge; selection does not change any grant',async()=>{const f=await setup(),id=f.entry.id;await f.s.foundationWrite(async t=>{await t.put('meta',{id:'aiPresentation:'+f.topic.id,topicId:f.topic.id,schemaVersion:1,revision:1,blockSummary:'AI 合成总览',currentView:'AI 连接语',keyInformation:[],preferences:[],decisions:[],judgments:[],openQuestions:[],possibleEvolution:[],evidenceEntryIds:[id],protections:{},stale:false,needsUpdate:false});});let state=await f.service.manual({action:'create'},'tab');async function call(action,options={}){state=await f.service.manual({action,selectionId:state.selectionId,generation:state.generation,...options},'tab');return state;}await call('add',{refs:[{kind:'ai',id:f.topic.id,field:'currentView',revision:1}]});await call('preview');assert.ok(state.text.includes('AI 整理 / Generated'));assert.ok(state.text.includes('AI 连接语'));await f.s.permanentDelete(f.b.originalTextReference);await call('read');assert.equal(state.state,'blocked');assert.equal(state.items[0].body,'');assert.equal(state.text,'');await assert.rejects(call('share',{format:'copy'}),{code:'MEMORY_DENIED'});assert.equal((await f.passport.status()).grants.length,0);});
test('UX-R4 bind and final output serialize on one package boundary and report the exact emitted item count',async()=>{let enteredResolve,releaseResolve,uuid=0;const entered=new Promise(r=>enteredResolve=r),release=new Promise(r=>releaseResolve=r);const memory={async build(){return {previewId:'preview-race',budget:'standard',generation:1,items:[{id:'a'},{id:'b'}],characters:7,tokens:2,retrievalConfidence:'high',partial:false};},async share(){enteredResolve();await release;return {text:'one',characters:3,tokens:1,itemCount:1,generation:2};}};const passport={async resolve(grantId,{profileId}){return {grantId,profileId,consumer:'chatgpt',purpose:'research'};},async authorize(){},async consume(){},async audit(){}};const service=new ContextPackageService(memory,passport,{clock:()=>0,uuid:()=>`pkg-${++uuid}`}),built=await service.build(),sharing=service.share({previewId:built.previewId,format:'copy',removed:['b']});await entered;const binding=service.bind(built.previewId,'grant-race');releaseResolve();const output=await sharing,bound=await binding;assert.equal(output.contextPackage.itemCount,1);assert.equal(output.contextPackage.characters,3);assert.equal(output.contextPackage.tokens,1);assert.equal(bound.grantId,'grant-race');assert.equal(service.package(built.previewId).grantId,'grant-race');assert.equal(service.package(built.previewId).itemCount,1);});
