import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
import {openArchiveWindow} from './harness/archive-navigator.mjs';
import {thoughtPrimary,thoughtHistoryAction} from './harness/current-thought-navigation.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const op=()=>crypto.randomUUID();
async function ready(h){const p=h.archive;await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN'}});return p;}
const offline=h=>{assert.equal(h.externalRequests,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);};
async function shot(p,name){await mkdir('work/ux-r3',{recursive:true});await p.screenshot({path:`work/ux-r3/${name}.png`});}
const nav=thoughtPrimary;
for(const variant of ['source','release'])test(`UX-R3 removed mid-topic reading anchor opens the nearby Thought with an explicit location notice (${variant})`,{timeout:90000},async()=>{
 const release=variant==='release'?await mkdtemp(join(tmpdir(),'paia-nearby-anchor-')):null;
 if(release)execFileSync('python3',['scripts/build_current_release.py',release],{stdio:'pipe'});
 const h=await FakeChatGPT.start({onboarding:true,...(release?{extensionPath:release}:{})});try{const p=await ready(h),topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'Synthetic nearby position',operationId:op()}});for(let i=0;i<7;i++)await rpc(p,'CONTINUE_THINKING',{thought:{operationId:op(),body:'Synthetic readable neighbor '+i,topicId:topic.id}});
  const page=await rpc(p,'TOPIC_DOCUMENT_PAGE',{options:{topicId:topic.id,sort:'asc'}}),middle=page.items[3].entry,next=page.items[4].entry;await rpc(p,'THOUGHT_POSITION',{position:{topicId:topic.id,entryId:middle.id,revision:middle.revision,offset:6,sort:'asc',expanded:[]}});const paths=await rpc(p,'GET_LIBRARY_PATHS',{id:middle.id}),current=await rpc(p,'GET_LIBRARY_TOPIC',{id:topic.id});await rpc(p,'PLACE_LIBRARY_ENTRY',{placement:{entryId:middle.id,topicId:topic.id,expectedEntryRevision:middle.revision,expectedTopicRevision:current.organizationRevision,expectedPlacementRevision:paths[0].placement.revision,remove:true,operationId:op()}});
  const resolvedBeforeOpen=await rpc(p,'THOUGHT_POSITION',{position:{topicId:topic.id}});assert.equal(resolvedBeforeOpen.entryId,next.id,'nearest persisted anchor is the next surviving Thought');
  await nav(p,'thoughts');await p.locator(`[data-topic-id="${topic.id}"]`).click();await p.getByText('原位置已移除，从附近继续。',{exact:true}).waitFor();const diagnostic=await p.evaluate(async expected=>{
   const sample=stage=>({stage,scrollY,maxScroll:document.documentElement.scrollHeight-innerHeight,viewport:innerHeight,clientHeight:document.documentElement.clientHeight,scrollBehavior:getComputedStyle(document.documentElement).scrollBehavior,fonts:document.fonts.status,rows:[...document.querySelectorAll('#topic-body [data-entry-id]')].map(el=>{const r=el.getBoundingClientRect(),body=el.querySelector('[data-entry-field="body"]'),b=body?.getBoundingClientRect();let rangeTop=null;if(el.dataset.entryId===expected.id&&body){const walker=document.createTreeWalker(body,NodeFilter.SHOW_TEXT);let node,offset=expected.offset;while(node=walker.nextNode()){if(offset<=node.length){const range=document.createRange();range.setStart(node,offset);range.collapse(true);rangeTop=range.getBoundingClientRect().top;break;}offset-=node.length;}}return {id:el.dataset.entryId,top:r.top,bottom:r.bottom,bodyTop:b?.top,bodyBottom:b?.bottom,rangeTop};})});
   const initial=sample('initial'),firstVisible=initial.rows.find(row=>row.bottom>140&&row.top<innerHeight)?.id||null;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const frame=sample('two-animation-frames');await document.fonts.ready;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {expected,firstVisible,samples:[initial,frame,sample('fonts-ready-two-frames')]};
  },{id:next.id,offset:resolvedBeforeOpen.offset});const resolved=await rpc(p,'THOUGHT_POSITION',{position:{topicId:topic.id}});console.log('REMOVED_ANCHOR_DIAGNOSTIC '+JSON.stringify({...diagnostic,resolvedBeforeOpen,resolved}));await mkdir('work/ux-r3',{recursive:true});await writeFile(`work/ux-r3/removed-anchor-diagnostic-${variant}.json`,JSON.stringify({...diagnostic,resolvedBeforeOpen,resolved},null,2));await shot(p,'removed-topic-anchor-diagnostic-'+variant);
  // Continuous prefetch can reveal a predecessor card above the correct text
  // anchor. Check exact identity and physically feasible text alignment instead.
  assert.equal(resolved.entryId,next.id,'persisted nearest target survives prefetch');
  for(const settled of diagnostic.samples){const target=settled.rows.find(row=>row.id===next.id);
  assert.ok(target&&Number.isFinite(target.rangeTop),'resolved next Thought has a measurable text anchor');
  assert.ok(target.rangeTop>=139&&target.rangeTop<settled.viewport,'next Thought text anchor is inside the readable viewport');
  assert.ok(Math.abs(target.rangeTop-140)<=1||(Math.abs(settled.scrollY-settled.maxScroll)<=1&&target.rangeTop>140),'text aligns at140 unless the exact remaining scroll range cannot reach it');}assert.equal(await p.locator(`#topic-body [data-entry-id="${middle.id}"]`).count(),0);assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:middle.id})).body,middle.body);await shot(p,'removed-topic-anchor-'+variant);offline(h);
 }finally{await h.close();if(release)await rm(release,{recursive:true,force:true});}
});
test('UX-R3 real Reader → add whole Input → two Topics → independent edit → restore; headless responsive matrix',{timeout:180000},async()=>{const h=await FakeChatGPT.start({onboarding:true});try{const p=await ready(h);await p.setViewportSize({width:1440,height:900});const text='UXR3_ARCHIVE 原始文字，保留过去的事实。\n中文 👩🏽‍💻 é 与换行。';await h.open({id:'uxr3-source',title:'合成旧记录',base:1609459200,messages:[{id:'uxr3-msg',text}]});await eventually(async()=>(await h.state()).records.length===1);await p.bringToFront();await p.locator('.archive-navigator-group-toggle').filter({hasText:'未归属 Project'}).waitFor();await openArchiveWindow(p,{label:'UX-R3 Archive window is reachable'});const field=p.locator('.library-prose').first();await field.waitFor();const inputId=await field.getAttribute('data-edit-id');await field.click({button:'right'});await p.locator('#context-menu button').filter({hasText:'加入主题'}).click();const dialog=p.locator('#topic-action-dialog');await dialog.getByRole('button',{name:'新建主题',exact:true}).click();await dialog.getByLabel('新主题名称').fill('主题 A');await dialog.getByRole('button',{name:'创建主题',exact:true}).click();await dialog.getByLabel('主题 A',{exact:true}).waitFor();for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});await shot(p,`picker-${appearance}-${width}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}}await p.setViewportSize({width:1440,height:900});await dialog.getByRole('button',{name:'加入',exact:true}).click();await eventually(()=>dialog.isVisible().then(x=>!x));assert.equal((await rpc(p,'GET_INPUT',{id:inputId})).libraryText,null);await nav(p,'thoughts');await p.locator('[data-topic-id]').filter({hasText:'主题 A'}).click();const thought=p.locator('#topic-body [data-entry-field="body"]').first();await thought.waitFor();const id=await thought.evaluate(el=>el.closest('[data-entry-id]').dataset.entryId);await thought.fill('UXR3_MANUAL 今天人工改写的思想');await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).body==='UXR3_MANUAL 今天人工改写的思想');assert.equal((await rpc(p,'GET_INPUT',{id:inputId})).libraryText,null);await thoughtHistoryAction(p,'library-undo');await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).body===text);assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id})).bodyBinding,'input');await thoughtHistoryAction(p,'library-redo');await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).body==='UXR3_MANUAL 今天人工改写的思想');
 const second=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'主题 B',operationId:op()}});const row=await rpc(p,'GET_LIBRARY_ENTRY',{id});await rpc(p,'ADD_TO_TOPICS',{selection:{id,kind:'thought',expectedRevision:row.revision,operationId:op(),topicIds:[second.id]}});await p.locator('#back').click();await p.locator('[data-topic-id]').filter({hasText:'主题 B'}).click();await eventually(()=>thought.textContent().then(x=>x==='UXR3_MANUAL 今天人工改写的思想'));const b=await rpc(p,'GET_INPUT',{id:inputId});await rpc(p,'EDIT_DOCUMENT',{edit:{operationId:op(),documentId:b.documentId,blocks:[{id:b.id,expectedRevision:b.revision,libraryText:'UXR3_UPDATED 档案更新',note:b.note,excluded:false}]}});await eventually(()=>p.locator('.entry-stale').filter({hasText:'档案有更新'}).isVisible());assert.equal(await thought.textContent(),'UXR3_MANUAL 今天人工改写的思想');
 for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});await pause(120);await shot(p,`topic-${appearance}-${width}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}}
 await p.setViewportSize({width:1440,height:900});const actions=p.locator('#topic-body .library-entry .library-actions').first();await actions.locator('summary').click();await actions.getByRole('button',{name:'查看档案当前文字',exact:true}).click();await dialog.getByRole('button',{name:'恢复为档案当前文字'}).waitFor();for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});await shot(p,`compare-${appearance}-${width}`);}}await p.setViewportSize({width:1440,height:900});await shot(p,'compare');p.once('dialog',d=>d.accept());await dialog.getByRole('button',{name:'恢复为档案当前文字'}).click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id})).bodyBinding==='input');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id})).body,'UXR3_UPDATED 档案更新');offline(h);
 }finally{await h.close();}});

test('UX-R3 advanced whole/partial edits, one-time Undo confirmation, dirty/IME buffers and mobile Done use the real worker',{timeout:180000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  const p=await ready(h);await p.setViewportSize({width:1440,height:900});const original='UXR3_ADV 原始完整内容 👩🏽‍💻，保留来源。';await h.open({id:'uxr3-advanced',title:'Synthetic advanced',messages:[{id:'advanced-source',text:original}]});await eventually(async()=>(await h.state()).records.length===1);await openArchiveWindow(p,{label:'UX-R3 Archive window is reachable'});const field=p.locator('.library-prose').first();await field.waitFor();const inputId=await field.getAttribute('data-edit-id'),input=await rpc(p,'GET_INPUT',{id:inputId}),topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'高级编辑验证',operationId:op()}});
  const add=span=>rpc(p,'ADD_TO_TOPICS',{selection:{kind:'input',id:inputId,expectedRevision:input.revision,...(span?{span}:{}),topicIds:[topic.id],operationId:op()}}),whole=await add();await field.evaluate(el=>{const range=document.createRange();range.setStart(el.firstChild,0);range.setEnd(el.firstChild,8);getSelection().removeAllRanges();getSelection().addRange(range);});await p.locator('.reader-selection').getByRole('button',{name:'加入主题',exact:true}).click();const picker=p.locator('#topic-action-dialog');assert.equal(await picker.locator('.topic-selection-preview').textContent(),original.slice(0,8));await picker.getByLabel('高级编辑验证',{exact:true}).check();await picker.getByRole('button',{name:'加入',exact:true}).click();await eventually(()=>picker.isVisible().then(x=>!x));const partial=await add({start:0,end:8});await nav(p,'settings');await p.locator('[data-settings-group=advanced]').click();await p.locator('#thought-reverse-edit').check();await eventually(async()=>(await rpc(p,'GET_THOUGHT_REVERSE_EDIT')).enabled);await nav(p,'thoughts');await p.locator('[data-topic-id]').filter({hasText:'高级编辑验证'}).click();const body=id=>p.locator(`[data-entry-id="${id}"] [data-entry-field="body"]`);
  await body(whole.id).click();assert.equal(await body(whole.id).evaluate(el=>document.activeElement===el),true);await body(whole.id).evaluate(el=>{el.textContent='UXR3 双向的新文字';el.closest('[data-entry-id]').querySelector('[data-entry-field="note"]').value='UXR3 同次编辑的备注';el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText'}));});await eventually(async()=>(await rpc(p,'GET_INPUT',{id:inputId})).libraryText==='UXR3 双向的新文字');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:whole.id})).note,'UXR3 同次编辑的备注');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:partial.id})).body,original.slice(0,8));await rpc(p,'SET_THOUGHT_REVERSE_EDIT',{enabled:false});assert.equal(await p.locator('#library-undo').evaluate(el=>getComputedStyle(el).pointerEvents),'auto');assert.equal(await p.locator('#library-undo').isEnabled(),true);let prompt=p.waitForEvent('dialog');await thoughtHistoryAction(p,'library-undo');await (await prompt).dismiss();assert.equal((await rpc(p,'GET_INPUT',{id:inputId})).libraryText,'UXR3 双向的新文字');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:whole.id})).note,'UXR3 同次编辑的备注');prompt=p.waitForEvent('dialog');await thoughtHistoryAction(p,'library-undo');await (await prompt).accept();await eventually(async()=>(await rpc(p,'GET_INPUT',{id:inputId})).libraryText===original);assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:whole.id})).note,'');assert.equal((await rpc(p,'GET_THOUGHT_REVERSE_EDIT')).enabled,false);
  await rpc(p,'SET_THOUGHT_REVERSE_EDIT',{enabled:true});await body(partial.id).fill('选段只改思想');await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id:partial.id})).body==='选段只改思想');assert.equal((await rpc(p,'GET_INPUT',{id:inputId})).libraryText,original);
  await body(partial.id).evaluate(el=>{window.r3ActiveNode=el;el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.textContent='中文正在组合 👩🏽‍💻';el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertCompositionText',data:'合',isComposing:true}));});
  await rpc(p,'CONTINUE_THINKING',{thought:{operationId:op(),body:'UXR3 新材料在编辑时到达',topicId:topic.id}});await pause(1000);assert.equal(await body(partial.id).evaluate(el=>el===window.r3ActiveNode),true);assert.equal(await body(partial.id).textContent(),'中文正在组合 👩🏽‍💻');assert.equal((await rpc(p,'GET_LIBRARY_ENTRY',{id:partial.id})).body,'选段只改思想');await body(partial.id).dispatchEvent('compositionend',{data:'合'});await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id:partial.id})).body==='中文正在组合 👩🏽‍💻');
  await p.locator('#topic-heading h1').click();await p.setViewportSize({width:390,height:844});await eventually(()=>body(partial.id).getAttribute('contenteditable').then(v=>v==='plaintext-only'));const item=p.locator(`[data-entry-id="${partial.id}"]`);assert.equal(await item.locator('.thought-mobile-edit,.thought-mobile-done').count(),0,'responsive width does not add a second edit mode');await body(partial.id).fill('手机上直接编辑');await p.locator('#topic-heading h1').click();await eventually(async()=>(await rpc(p,'GET_LIBRARY_ENTRY',{id:partial.id})).body==='手机上直接编辑');assert.equal(await body(partial.id).getAttribute('contenteditable'),'plaintext-only');await shot(p,'narrow-direct-edit');offline(h);
 }finally{await h.close();}
});

test('UX-R3 current root and held Write workspace preserve data, IME and explicit leave ownership',{timeout:180000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  const p=await ready(h);await p.setViewportSize({width:1440,height:900});await h.open({id:'uxr3-current-write-source',title:'SYNTHETIC protected Source',messages:[{id:'uxr3-current-write-input',text:'SYNTHETIC unchanged Source and Input 👩🏽‍💻'}]});await eventually(async()=>(await h.state()).records.length===1);
  const before=await h.state(),protectedBefore={records:before.records,blocks:before.library.blocks},created=await rpc(p,'CONTINUE_THINKING',{thought:{operationId:op(),body:'UXR3_TODAY 今天独立记录 👩🏽‍💻'}}),row=await rpc(p,'GET_LIBRARY_ENTRY',{id:created.id});
  assert.equal(row.body,'UXR3_TODAY 今天独立记录 👩🏽‍💻');assert.equal(row.bodyBinding,'thought');assert.ok(Math.abs(Date.now()-Date.parse(row.createdAt))<60000);assert.equal(row.provenanceType,'user_created');
  await nav(p,'thoughts');await p.locator('#library-unplaced').click();await p.locator(`[data-unplaced-id="${row.id}"]`).click();await p.locator('#library-dialog [data-entry-field="body"]').waitFor();await p.locator('#library-dialog-close').click();
  for(const name of ['稳定主题一','稳定主题二','稳定主题三'])await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name,operationId:op()}});await eventually(()=>p.locator('#thought-list [data-topic-id]').count().then(x=>x===3));const order=await p.locator('#thought-list [data-topic-id]').evaluateAll(els=>els.map(e=>e.dataset.topicId));await rpc(p,'RECORD_TOPIC_READ',{id:order[2]});await eventually(async()=>((await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'stable'}})).recent||[]).some(item=>item.id===order[2]),'recent-read metadata remains recorded');assert.equal(await p.locator('#thought-recent').count(),0);assert.deepEqual(await p.locator('#thought-list [data-topic-id]').evaluateAll(els=>els.map(e=>e.dataset.topicId)),order);
  assert.equal((await rpc(p,'GET_THOUGHT_LAYOUT')).layout,'list');assert.equal(await p.locator('#thought-list').evaluate(el=>el.classList.contains('topic-compact-list')),true);assert.equal(await p.locator('#thought-root-source').getByRole('button',{name:'列表 / 网格',exact:true}).count(),0);await rpc(p,'SET_THOUGHT_LAYOUT',{layout:'grid'});assert.equal((await rpc(p,'GET_THOUGHT_LAYOUT')).layout,'list');
  await p.emulateMedia({reducedMotion:'reduce'});for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});await pause(80);await shot(p,`current-home-${appearance}-${width}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}}
  await p.evaluate(()=>document.body.style.zoom='2');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement===document.body),false);await shot(p,'current-home-200-percent');await p.evaluate(()=>document.body.style.zoom='1');
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__heldWriteCalls=[];chrome.runtime.sendMessage=(message,...args)=>{if(['CONTINUE_THINKING','CREATE_LIBRARY_TOPIC'].includes(message.type))__heldWriteCalls.push(structuredClone(message));return send(message,...args);};});
  await p.locator('#thought-root-source').getByRole('button',{name:'接着写',exact:true}).click();const workspace=p.locator('.thought-compose-workspace'),draft=workspace.getByRole('textbox',{name:'今天的新想法'}),body='UXR3_CURRENT 新的未保存表达 👩🏽‍💻\n保留每一行。';await draft.fill(body);await draft.evaluate(node=>globalThis.__currentWriteDraft=node);
  assert.equal(await p.locator('#topic-action-dialog').isVisible(),false);assert.equal(await workspace.getByRole('button',{name:'保存想法',exact:true}).isDisabled(),true);assert.equal(await workspace.getByRole('button',{name:'取消',exact:true}).isDisabled(),true);assert.equal(await p.locator('.dvn-preview-back').isDisabled(),true);assert.match(await workspace.locator('.thought-compose-preview-note').innerText(),/保存与返回尚未接通/);
  await draft.dispatchEvent('compositionstart');await draft.press('Control+Enter');assert.equal(await draft.evaluate(node=>node===__currentWriteDraft),true);assert.equal(await draft.inputValue(),body);await draft.dispatchEvent('compositionend');await draft.press('Control+Enter');assert.deepEqual(await p.evaluate(()=>__heldWriteCalls),[],'current Save/shortcut cannot enter the withdrawn writing path');
  for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});await pause(80);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot(p,`current-compose-${appearance}-${width}`);assert.equal(await draft.evaluate(node=>node===__currentWriteDraft),true);assert.equal(await draft.inputValue(),body);}}
  p.once('dialog',dialog=>dialog.dismiss());await nav(p,'settings');assert.equal(await workspace.isVisible(),true,'declined leave keeps the real workspace');assert.equal(await draft.evaluate(node=>node===__currentWriteDraft),true);assert.equal(await draft.inputValue(),body);
  p.once('dialog',dialog=>dialog.accept());await nav(p,'settings');await eventually(()=>p.locator('#settings-panel').isVisible());await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'en'}});await nav(p,'thoughts');await p.locator('#thought-root-source').getByRole('button',{name:'Continue thinking',exact:true}).click();await workspace.getByRole('heading',{name:'Write a thought',exact:true}).waitFor();await shot(p,'current-compose-English');assert.equal(await workspace.locator('textarea').inputValue(),'');assert.equal(await workspace.getByRole('button',{name:'Save thought',exact:true}).isDisabled(),true);
  assert.deepEqual(await p.evaluate(()=>__heldWriteCalls),[]);assert.deepEqual(await rpc(p,'GET_LIBRARY_ENTRY',{id:row.id}),row);const after=await h.state();assert.deepEqual({records:after.records,blocks:after.library.blocks},protectedBefore);offline(h);
 }finally{await h.close();}
});

async function closeComposeFixture(h,release,primaryFailure){
 let cleanupFailure;try{await h.close();}catch(error){cleanupFailure=error;}try{if(release)await rm(release,{recursive:true,force:true});}catch(error){cleanupFailure??=error;}
 if(cleanupFailure){if(primaryFailure)console.error('Secondary synthetic compose cleanup failure:',cleanupFailure.message);else throw cleanupFailure;}
}

for(const variant of ['source','release'])test(`UX-R3 independent today draft survives earlier Add acknowledgement (${variant})`,{timeout:120000},async()=>{
 const release=variant==='release'?await mkdtemp(join(tmpdir(),'paia-add-owner-')):null;if(release)execFileSync('python3',['scripts/build_current_release.py',release],{stdio:'pipe'});
 const h=await FakeChatGPT.start({onboarding:true,...(release?{extensionPath:release}:{})});let p,failure;const trace={variant,head:process.env.PAIA_TESTED_HEAD,stage:'start'};
 try{
  p=await ready(h);await h.open({id:'synthetic-add-owner-source',title:'SYNTHETIC Add owner',messages:[{id:'synthetic-add-owner-message',text:'SYNTHETIC immutable Add Source 👩‍💻'}]});await eventually(async()=>(await h.state()).records.length===1);const initial=await h.state(),protectedBefore={records:initial.records,blocks:initial.library.blocks},topic=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name:'SYNTHETIC selected Topic',operationId:op()}});
  await openArchiveWindow(p,{label:'Synthetic Add owner Archive'});const input=p.locator('.library-prose').first();await input.waitFor();await input.click({button:'right'});await p.locator('#context-menu button').filter({hasText:'加入主题'}).click();const host=p.locator('#topic-action-dialog');await host.getByLabel('SYNTHETIC selected Topic',{exact:true}).check();
  await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);globalThis.__addOwnerCalls=[];chrome.runtime.sendMessage=async(message,...args)=>{if(message.type!=='ADD_TO_TOPICS')return send(message,...args);__addOwnerCalls.push(structuredClone(message.selection));const response=await send(message,...args);globalThis.__addOwnerResult=response;return new Promise(resolve=>globalThis.__releaseAddOwner=()=>resolve(response));};});
  await host.getByRole('button',{name:'加入',exact:true}).click();await eventually(()=>p.evaluate(()=>!!globalThis.__releaseAddOwner));assert.equal(await host.locator('.topic-action-content').evaluate(node=>node.inert),true);await host.getByRole('button',{name:'关闭',exact:true}).click();await nav(p,'thoughts');await p.locator('#thought-root-source').getByRole('button',{name:'接着写',exact:true}).click();const workspace=p.locator('#desktop-appearance-preview-workspace .thought-compose-workspace'),draft=workspace.getByRole('textbox',{name:'今天的新想法'}),body='SYNTHETIC newer draft after Add 👩‍💻\nRemain here.';await draft.fill(body);await draft.evaluate(node=>globalThis.__draftAfterAdd=node);await p.evaluate(()=>__releaseAddOwner());await p.locator('#notice').getByRole('button',{name:'查看',exact:true}).waitFor();assert.ok((await p.locator('#notice').textContent()).startsWith('已加入主题'));assert.equal(await workspace.isVisible(),true);assert.equal(await host.isVisible(),false);assert.equal(await draft.evaluate(node=>node===__draftAfterAdd),true);assert.equal(await draft.inputValue(),body);assert.equal(await draft.evaluate(node=>document.activeElement===node),true);assert.equal(await p.evaluate(()=>__addOwnerCalls.length),1);
  const page=await rpc(p,'TOPIC_DOCUMENT_PAGE',{options:{topicId:topic.id,sort:'asc'}});assert.equal(page.items.length,1);assert.equal(page.items[0].entry.body,'SYNTHETIC immutable Add Source 👩‍💻');const current=await h.state();assert.deepEqual({records:current.records,blocks:current.library.blocks},protectedBefore);trace.calls=await p.evaluate(()=>__addOwnerCalls);offline(h);trace.stage='PASS';
 }catch(error){failure=error;throw error;}finally{if(p)try{await mkdir('work/ux-r3',{recursive:true});await p.screenshot({path:`work/ux-r3/compose-add-owner-${variant}.png`});await writeFile(`work/ux-r3/compose-add-owner-${variant}.json`,JSON.stringify(trace,null,2));}catch{/* Preserve the original failure. */}await closeComposeFixture(h,release,failure);}
});

test('UX-R3 F-LARGE 100k Inputs / 1000 documents / 300 Topics / 5000 Thoughts: bounded page, real UI, anchor and Back/Forward',{timeout:300000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{const p=await ready(h);const report=await p.evaluate(async()=>{
   const {OrganizerStore}=await import('../core/organizer/store.js'),{recordIndex,blockIndex,sourceCount}=await import('../core/idb-repository.js'),{ReaderStateService}=await import('../core/reader-state.js'),{RevisitService}=await import('../core/revisit.js');
   const values={},local={async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}},s=new OrganizerStore(chrome.storage.local);await s.consent(true);await s.capture({epoch:(await s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'large-template',url:'https://chatgpt.com/c/large-template',title:'Synthetic large template'},messages:[{sourceMessageId:'large-template-one',pageOrder:1,originalText:'Synthetic template'}]});const template=await s.snapshot(),r0=template.records[0],b0=template.library.blocks[0],d0=template.conversations[0];
   await s.repository.transaction(true,async t=>{for(const name of ['records','recordIndex','blocks','blockIndex','documents','libraryDocuments','sourceCounts','inputStates','filterInputs','filterIntents'])await t.clear(name);});const began=performance.now();let pulses=0;const timer=setInterval(()=>pulses++,20);
   for(let start=0;start<100000;start+=500)await s.repository.transaction(true,async t=>{const writes=[];for(let i=start;i<start+500;i++){
    const group=Math.floor(i/100),chatId='large-chat-'+group,docId='document:large-'+group,id='large-record-'+String(i).padStart(8,'0'),sourceKey=i.toString(16).padStart(64,'0'),r={...r0,id,chatId,chatUrl:'https://chatgpt.com/c/'+chatId,chatTitle:'Synthetic source '+group,sourceMessageId:'large-message-'+i,sourceKey,dedupeKey:sourceKey,originalText:i===50110?'长文👩‍💻\n'+'中'.repeat(50000):'Synthetic 中文 input '+i+' '+('text '.repeat(30)),sourceSentAt:new Date(1609459200000+i*1000).toISOString(),timeSource:'chatgpt_response_create_time',timeConfidence:'high',pageOrder:i%100+1,conversationOrder:i%100+1};
    const b={...b0,id:'block:'+id,documentId:docId,sourceRecordId:id,originalTextReference:id,provenance:[{sourceRecordId:id}],provenanceSignature:JSON.stringify([{sourceRecordId:id}])};writes.push(t.put('inputStates',{id:b.id,documentId:docId,contentRevision:0,removalState:'active',sourcePurged:false,sourceRecordIds:[id],deltaSequence:i}),t.put('records',{id,value:r}),t.put('recordIndex',recordIndex(r,i)),t.put('blocks',{id:b.id,value:b}),t.put('blockIndex',blockIndex(b,i,[r])),t.put('sourceCounts',sourceCount(docId,sourceKey,[r],[b],chatId)));
    if(i%100===0){const doc={...d0,id:docId,sourceConversationId:chatId,originalConversationTitle:r.chatTitle,firstSourceSentAt:r.sourceSentAt,lastSourceSentAt:r.sourceSentAt};delete doc.sourceRecordIds;const key=[-Date.parse(r.sourceSentAt),docId];writes.push(t.put('documents',{id:docId,sequence:group,chatKey:'chatgpt:'+chatId,displayKey:key,libraryDisplay:key,archiveDisplay:key,value:doc}),t.put('libraryDocuments',{id:docId,value:doc}));}
   }await Promise.all(writes);});await s.repository.transaction(true,t=>t.put('meta',{id:'sequence',records:100000,blocks:100000,documents:1000}));
   const first=await s.createTopic({name:'Synthetic 5000 entry topic',operationId:crypto.randomUUID()}),entry=await s.createEntry({actor:'user',formation:'explicit',body:'Synthetic standalone entry',type:'idea',evidence:[],operationId:crypto.randomUUID()}),topic0=await s.repository.transaction(false,t=>t.get('topics',first.id)),entry0=await s.repository.transaction(false,t=>t.get('thoughts',entry.id)),section0=await s.repository.transaction(false,t=>t.get('sections',JSON.stringify([first.id,1,topic0.defaultSectionId])));
   for(let start=0;start<5000;start+=500)await s.repository.transaction(true,async t=>{const writes=[];for(let i=start;i<start+500;i++){const id=i? 'large-entry-'+i:entry.id;writes.push(t.put('thoughts',{...entry0,id}),t.put('placements',{id:JSON.stringify([first.id,1,id]),topicId:first.id,layoutGeneration:1,entryId:id,sectionId:topic0.defaultSectionId,sectionRank:'499999999999',rank:String(100000+i).padStart(12,'0'),revision:0,activeKey:0,lifecycle:'active'}));if(i>0&&i<300)writes.push(t.put('topics',{...topic0,id:'large-topic-'+i,name:'Synthetic topic '+i,nameKey:'synthetic topic '+i}),t.put('sections',{...section0,id:JSON.stringify(['large-topic-'+i,1,topic0.defaultSectionId]),topicId:'large-topic-'+i}));}await Promise.all(writes);});clearInterval(timer);

   s.repository.metrics={reads:0,writes:0,scans:0};const start=performance.now(),page=await s.topicDocumentPage({topicId:first.id,sort:'asc',limit:40});const timing={ms:performance.now()-start,...s.repository.metrics};const anchor=page.items[20].entry;await s.topicPosition({topicId:first.id,entryId:anchor.id,revision:anchor.revision,offset:8,sort:'asc',expanded:[]});const index=await s.libraryIndexPage({mode:'stable',limit:40}),counts=await s.repository.transaction(false,async t=>({inputs:await t.count('blocks'),documents:await t.count('documents'),topics:await t.count('topics'),entries:await t.count('thoughts')}));return {counts,topicId:first.id,anchorId:anchor.id,seedMs:performance.now()-began,pulses,timing,pageCount:page.items.length,hasMore:!!page.nextCursor,indexCount:index.items.length,indexHasMore:!!index.nextCursor};
  });await mkdir('work/ux-r3',{recursive:true});await writeFile('work/ux-r3/large-fixture.json',JSON.stringify(report,null,2));assert.deepEqual(report.counts,{inputs:100000,documents:1000,topics:300,entries:5000});assert.equal(report.pageCount,40);assert.equal(report.hasMore,true);assert.equal(report.indexCount,40);assert.equal(report.indexHasMore,true);assert.ok(report.pulses>0);await nav(p,'thoughts');await p.locator(`[data-topic-id="${report.topicId}"]`).click();await p.locator(`[data-entry-id="${report.anchorId}"]`).waitFor().catch(async error=>{await writeFile('work/ux-r3/large-ui-debug.json',JSON.stringify({history:await p.evaluate(()=>history.state),text:await p.locator('body').innerText(),anchor:await rpc(p,'THOUGHT_POSITION',{position:{topicId:report.topicId}}),page:await rpc(p,'TOPIC_DOCUMENT_PAGE',{options:{topicId:report.topicId,sort:'asc',anchorId:report.anchorId}})},null,2));throw error;});// ANS-08 P06 freezes a 120-entry clean DOM window; each RPC page remains 40 (asserted above).
  const visibleIds=await p.locator('#topic-body [data-entry-id]').evaluateAll(nodes=>nodes.map(node=>node.dataset.entryId));assert.ok(visibleIds.length>0&&visibleIds.length<=120,'ANS-08 clean Topic window stays within 120 entries');assert.equal(new Set(visibleIds).size,visibleIds.length,'continuous prefetch must not duplicate entries');await shot(p,'large-topic-page');await p.locator('#back').click();await p.waitForFunction(()=>history.state?.paiaReader?.topicId===null);await waitLargeRoot(p,'Back');await p.goBack();await p.locator(`[data-entry-id="${report.anchorId}"]`).waitFor().catch(async error=>{await writeFile('work/ux-r3/large-ui-debug.json',JSON.stringify({history:await p.evaluate(()=>history.state),text:await p.locator('body').innerText(),anchor:await rpc(p,'THOUGHT_POSITION',{position:{topicId:report.topicId}}),page:await rpc(p,'TOPIC_DOCUMENT_PAGE',{options:{topicId:report.topicId,sort:'asc',anchorId:report.anchorId}})},null,2));throw error;});await p.goForward();await waitLargeRoot(p,'Forward');await shot(p,'large-home');offline(h);
 }finally{await h.close();}
});

async function waitLargeRoot(p,stage){try{await p.locator('#thought-list [data-topic-id]').first().waitFor();}catch(error){await writeFile('work/ux-r3/large-root-'+stage+'.json',JSON.stringify(await p.evaluate(stage=>({stage,history:history.state,rows:document.querySelectorAll('#thought-list [data-topic-id]').length,text:document.body.innerText.slice(0,4000)}),stage),null,2));await shot(p,'large-root-'+stage+'-failure');throw error;}}
