import {admitPreGatePurgeFixture} from './harness/pre-gate-purge-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,rows,append} from './harness/original-complete.mjs';
import {backupHash,validateBackupItem} from '../core/backup-format.js';
import {BackupService} from '../core/backup-service.js';
import {exported,prepared} from './harness/backup-v081.mjs';
import {migrateBindings,BINDING_ROW} from '../core/thought-binding.js';
const op=()=>crypto.randomUUID();
async function fixture(){const f=await completeFixture({texts:['UXR3_COMPAT 合成原文']});const b=(await rows(f.s,'blocks'))[0].value,t=await f.s.createTopic({name:'保留主题',operationId:op()}),r=await f.s.addToTopics({id:b.id,kind:'input',expectedRevision:b.revision,operationId:op(),topicIds:[t.id]});return {...f,b,t,id:r.id};}
test('UX-R3 new Backup round trip retains binding, independent body, history and layout while reverse editing stays off',async()=>{const f=await fixture(),e=await f.s.entry(f.id);await f.s.editLibraryFields({id:e.id,operationId:op(),expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,expectedInputRevision:e.currentInputRevision,changes:{body:'UXR3 独立人工正文'}});await f.s.reverseEditSetting(true);await f.s.thoughtLayout('list');const items=await exported(new BackupService(f.s)),target=await completeFixture({texts:[]}),service=new BackupService(target.s),stage=await prepared(service,items);await service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});const restored=await target.s.entry(e.id);assert.equal(restored.body,'UXR3 独立人工正文');assert.equal(restored.bodyBinding,'thought');assert.equal(restored.workingInputId,undefined);assert.equal((await target.s.reverseEditSetting()).enabled,false);assert.equal((await target.s.thoughtLayout()).layout,'list');assert.deepEqual((await rows(target.s,'revisions')).map(x=>x.before),(await rows(f.s,'revisions')).map(x=>x.before));assert.equal(JSON.stringify(items).includes('thought-reverse-edit'),false);assert.equal(target.requests.length,0);});
test('UX-R3 old backup and interrupted metadata batches resume without changing body, revision, identity or grants',async()=>{const f=await fixture();for(let i=0;i<3;i++)await f.s.continueThinking({operationId:op(),body:'旧版独立思想 '+i});await f.s.foundationWrite(async t=>{for(const row of await t.all('thoughts')){delete row.bodyBinding;delete row.bindingRevision;delete row.bindingLength;await t.put('thoughts',row);}await t.delete('meta',BINDING_ROW);});const before=await rows(f.s,'thoughts'),sources=await rows(f.s,'records');const checkpoint=f.s.repository.checkpoint;f.s.repository.checkpoint=async label=>{if(label==='thought-binding-batch')throw Error('SIMULATED_POWER_LOSS');};await assert.rejects(migrateBindings(f.s,{limit:1}));f.s.repository.checkpoint=checkpoint;await migrateBindings(f.s,{limit:1});await migrateBindings(f.s,{limit:1});const after=await rows(f.s,'thoughts');assert.deepEqual(after.map(x=>[x.id,x.thoughtText,x.revision,x.createdAt,x.sourceRecordIds]),before.map(x=>[x.id,x.thoughtText,x.revision,x.createdAt,x.sourceRecordIds]));assert.deepEqual(await rows(f.s,'records'),sources);assert.equal((await f.s.reverseEditSetting()).enabled,false);const oldItems=await exported(new BackupService(f.s));let chain='';for(const item of oldItems){if(item.section==='entries')for(const key of ['bodyBinding','bindingRevision','bindingLength','thoughtEditedAt'])delete item.value[key];if(item.section==='revisions')for(const side of ['before','after'])if(item.value[side])for(const key of ['bodyBinding','bindingRevision','bindingLength','thoughtEditedAt','bodyProtection','bodyAuthorship'])delete item.value[side][key];if(item.type==='footer')item.integrity.root=chain;else chain=await backupHash(chain,item);}assert.equal(oldItems.some(item=>item.section==='entries'&&item.value.bodyBinding),false);const target=await completeFixture({texts:[]}),service=new BackupService(target.s),stage=await prepared(service,oldItems);await service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});assert.equal((await target.s.entry(f.id)).bodyBinding,'input');await append(target.s,'UXR3_COMPAT 合成原文','complete-0');assert.equal((await rows(target.s,'thoughts')).length,4);});
test('UX-R3 topic position uses shared bounded device metadata, validates placement/revision and stays out of Backup',async()=>{const f=await fixture(),e=await f.s.entry(f.id);assert.equal(await f.s.topicPosition({topicId:f.t.id}),null);await f.s.topicPosition({topicId:f.t.id,entryId:e.id,revision:e.revision,offset:4,sort:'desc',expanded:[]});const anchor=await f.s.topicPosition({topicId:f.t.id});assert.equal(anchor.entryId,e.id);assert.equal(anchor.offset,4);const before=await rows(f.s,'thoughts');assert.equal((await f.s.topicPosition({topicId:f.t.id,entryId:e.id,revision:e.revision+1,offset:4,sort:'asc',expanded:[]})).saved,false);assert.deepEqual(await rows(f.s,'thoughts'),before);assert.equal(JSON.stringify(await exported(new BackupService(f.s))).includes('"anchors"'),false);});
test('UX-R3 multi-topic transaction rejects changed source or unavailable target without partial creation/placement',async()=>{const f=await fixture(),count=(await rows(f.s,'thoughts')).length;await assert.rejects(f.s.addToTopics({kind:'input',id:f.b.id,expectedRevision:f.b.revision,span:{start:0,end:4},operationId:op(),topicIds:[f.t.id,'missing-topic']}));assert.equal((await rows(f.s,'thoughts')).length,count);assert.equal((await f.s.addToTopics({kind:'input',id:f.b.id,expectedRevision:f.b.revision+1,operationId:op(),topicIds:[f.t.id]})).conflict,true);await assert.rejects(f.s.continueThinking({operationId:op(),body:' \n '}));assert.equal((await rows(f.s,'thoughts')).length,count);});
test('CURRENT B-02 refusal + historical fixture: UX-R3 explicit Thought excerpt reuses exact selection only, preserves source restrictions and never binds to Input',async()=>{const f=await fixture(),e=await f.s.entry(f.id),selection={kind:'thought',id:e.id,expectedRevision:e.revision,span:{start:0,end:4},topicIds:[f.t.id],operationId:op()},a=await f.s.addToTopics(selection),b=await f.s.addToTopics({...selection,operationId:op()});assert.equal(a.id,b.id);assert.notEqual(a.id,e.id);assert.equal((await f.s.entry(a.id)).body,e.body.slice(0,4));assert.equal((await f.s.entry(a.id)).bodyBinding,'thought');await admitPreGatePurgeFixture(f.s,f.b.originalTextReference);assert.equal((await f.s.entry(a.id)).body,'');});

test('UX-R3 Backup rejects unknown binding and malformed live metadata without downgrading fields',async()=>{const f=await fixture(),item=(await exported(new BackupService(f.s))).find(x=>x.section==='entries');for(const patch of [{bodyBinding:'future'},{bindingRevision:-1},{bindingLength:-2},{workingInputId:''},{bodyBinding:'thought'}])assert.throws(()=>validateBackupItem({...item,value:{...item.value,...patch}}));});

test('UX-R3 removed Topic positions resolve to the next safe neighbor in either time order, including legacy anchors',async()=>{
 for(const sort of ['asc','desc']){const f=await fixture();for(let i=0;i<6;i++)await f.s.continueThinking({operationId:op(),body:'Synthetic nearby thought '+i,topicId:f.t.id});const page=await f.s.topicDocumentPage({topicId:f.t.id,sort}),middle=page.items[3].entry,next=page.items[4].entry;
  await f.s.topicPosition({topicId:f.t.id,entryId:middle.id,revision:middle.revision,offset:4,sort,expanded:[]});const saved=(await rows(f.s,'meta')).find(x=>x.id==='reading:v1');assert.deepEqual(Object.keys(saved.anchors[0].position).sort(),['entryId','sectionId','sectionRank','time']);assert.doesNotMatch(JSON.stringify(saved),/Synthetic|thoughtText|body|snippet/);
  const paths=await f.s.entryPaths(middle.id),topic=await f.s.topic(f.t.id);await f.s.placeEntry({entryId:middle.id,topicId:f.t.id,expectedEntryRevision:middle.revision,expectedTopicRevision:topic.organizationRevision,expectedPlacementRevision:paths[0].placement.revision,remove:true,operationId:op()});
  let anchor=await f.s.topicPosition({topicId:f.t.id});assert.equal(anchor.nearby,true);assert.equal(anchor.entryId,next.id);assert.equal(anchor.offset,0);assert.equal((await f.s.topicDocumentPage({topicId:f.t.id,sort,anchorId:anchor.entryId})).items[0].entry.id,next.id);assert.equal((await f.s.entry(middle.id)).body,middle.body);
  await f.s.foundationWrite(async t=>{const old=await t.get('meta','reading:v1');delete old.anchors[0].position;await t.put('meta',old);});anchor=await f.s.topicPosition({topicId:f.t.id});assert.equal(anchor.entryId,next.id);assert.equal(JSON.stringify(await exported(new BackupService(f.s))).includes('"anchors"'),false);
 }
});

test('CURRENT B-02 refusal + historical fixture: UX-R3 purged Topic anchor keeps only an ordering point and never resumes at the cleared quote',async()=>{
 const f=await completeFixture({texts:['Synthetic first quote','Synthetic middle quote','Synthetic final quote']}),topic=await f.s.createTopic({name:'Synthetic purge neighbors',operationId:op()});for(const {value:b}of await rows(f.s,'blocks'))await f.s.addToTopics({id:b.id,kind:'input',expectedRevision:b.revision,operationId:op(),topicIds:[topic.id]});
 const page=await f.s.topicDocumentPage({topicId:topic.id,sort:'asc'}),middle=page.items[1].entry,next=page.items[2].entry;await f.s.topicPosition({topicId:topic.id,entryId:middle.id,revision:middle.revision,offset:7,sort:'asc',expanded:[]});const source=(await f.s.entryProvenance(middle.id))[0].sourceRecordIds[0];await admitPreGatePurgeFixture(f.s,source);
 const anchor=await f.s.topicPosition({topicId:topic.id});assert.equal(anchor.nearby,true);assert.equal(anchor.entryId,next.id);assert.equal(anchor.offset,0);assert.equal((await f.s.entry(middle.id)).body,'');await f.s.drainPurgeCleanup();assert.equal((await f.s.topicPosition({topicId:topic.id})).entryId,next.id);
});


test('VS-04 Topic removal and restore preserve Source and Archive Input independently',async()=>{
 const f=await fixture();
 const sourceBefore=await rows(f.s,'records'),inputBefore=await rows(f.s,'blocks');
 const bodyBefore=(await f.s.entry(f.id)).body;
 const topicBefore=await f.s.topic(f.t.id);
 const removed=await f.s.removeTopic({id:f.t.id,expectedRevision:topicBefore.revision,operationId:op()});
 assert.equal(removed.removed,true);
 assert.equal((await f.s.repository.transaction(false,tx=>tx.get('topics',f.t.id),['topics'])).lifecycle,'removed');
 assert.equal((await f.s.entry(f.id)).body,bodyBefore,'Topic removal leaves the Thought body available');
 assert.deepEqual(await rows(f.s,'records'),sourceBefore,'Topic removal cannot purge Source');
 assert.deepEqual(await rows(f.s,'blocks'),inputBefore,'Topic removal cannot hide Archive Inputs');

 const restored=await f.s.restoreTopicContainer({id:f.t.id,expectedRevision:removed.revision,operationId:op()});
 assert.equal(restored.restored,true);
 assert.equal((await f.s.repository.transaction(false,tx=>tx.get('topics',f.t.id),['topics'])).lifecycle,'active');
 assert.equal((await f.s.entry(f.id)).body,bodyBefore);
 assert.deepEqual(await rows(f.s,'records'),sourceBefore);
 assert.deepEqual(await rows(f.s,'blocks'),inputBefore);
});

// Ephemeral UI-operation ownership; domain fixtures above remain unchanged.
import {withTopicActions,tick,success,find,clickText,openChoices,createPendingTopic} from './harness/topic-action-dom.mjs';
test('older successful acknowledgement retains newer literal text and its textarea',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A\n');const field=f.owner.draft;field.value='SYNTHETIC B\n👩‍💻';await f.respond(success);assert.equal(f.owner.draft,field);assert.equal(field.value,'SYNTHETIC B\n👩‍💻');assert.equal(f.owner.dialog.open,true);assert.equal(f.calls.length,1);}));
test('older successful acknowledgement cannot close a reopened compose owner',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A');f.owner.close(true);await f.owner.compose();const field=f.owner.draft;field.value='SYNTHETIC B';await f.respond(success);assert.equal(f.owner.draft,field);assert.equal(f.owner.dialog.open,true);}));
test('older failure cannot write into reopened feedback',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A');f.owner.close(true);await f.owner.compose();const feedback=f.owner.feedback;await f.respond({ok:false,error:'STORAGE_FAILED'});assert.equal(f.owner.feedback,feedback);assert.equal(feedback.textContent,'');assert.equal(f.owner.dialog.open,true);}));
test('acknowledged unchanged payload cannot resubmit after IME settles',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A');const field=f.owner.draft;field.listeners.get('compositionstart')();await f.respond(success);assert.equal(f.owner.draft,field);assert.equal(f.owner.dialog.open,true);field.listeners.get('compositionend')();await f.submit();assert.equal(f.calls.length,1);assert.equal(f.owner.dialog.open,false);}));
test('unknown outcome remains sticky across failed reconciliation and changed current text',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A');await f.respond({ok:false,error:'MESSAGE_CHANNEL_INTERRUPTED'});f.owner.draft.value='SYNTHETIC B';await f.submit();assert.deepEqual(f.calls[1],f.calls[0]);await f.respond({ok:false,error:'STORAGE_FAILED'});assert.equal(f.owner.composeSession.uncertain,true);await f.submit();assert.deepEqual(f.calls[2],f.calls[0]);const field=f.owner.draft;await f.respond(success);assert.equal(f.owner.draft,field);assert.equal(field.value,'SYNTHETIC B');assert.equal(f.calls.length,3);}));
test('malformed acknowledgement is uncertain and reuses the exact earlier operation',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A');await f.respond({ok:false,error:{code:'STORAGE_FAILED'}});assert.equal(f.owner.composeSession.uncertain,true);await f.submit();assert.deepEqual(f.calls[1],f.calls[0]);await f.respond(success);assert.equal(f.owner.dialog.open,false);}));
test('well-formed definitive failure keeps existing failure copy and exact draft',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC A\n');await f.respond({ok:false,error:'STORAGE_FAILED'});assert.equal(f.owner.composeSession.uncertain,false);assert.equal(f.owner.draft.value,'SYNTHETIC A\n');assert.equal(f.owner.feedback.textContent,'尚未保存，文字仍在这里。可以重试或复制。');}));
test('late Topic-list continuation cannot append controls or focus into a newer composer',()=>withTopicActions(async f=>{const work=f.owner.add({id:'synthetic-input',kind:'input',expectedRevision:0},'SYNTHETIC quote');await tick();assert.equal(f.rpcCalls.at(-1).type,'LIBRARY_INDEX_PAGE');f.owner.close(true);await f.owner.compose();const field=f.owner.draft,count=f.owner.content.children.length;field.value='SYNTHETIC newer';await f.respond({ok:true,data:{items:[],nextCursor:null}});await work;assert.equal(f.owner.draft,field);assert.equal(f.owner.content.children.length,count);assert.equal(document.activeElement,field);}));
test('late Topic-read failure cannot change newer feedback or focus',()=>withTopicActions(async f=>{const choices=find(f.owner.content,node=>node.tagName==='DETAILS');choices.open=true;choices.listeners.get('toggle')();await tick();f.owner.close(true);await f.owner.compose();const field=f.owner.draft,feedback=f.owner.feedback;await f.respond({ok:false,error:'STORAGE_FAILED'});assert.equal(feedback.textContent,'');assert.equal(document.activeElement,field);}));
test('held Add acknowledgement cannot close a newer draft',()=>withTopicActions(async f=>{const work=f.owner.add({id:'synthetic-input',kind:'input',expectedRevision:0},'SYNTHETIC quote');await tick();await f.respond({ok:true,data:{items:[{id:'synthetic-topic',name:'SYNTHETIC Topic'}],nextCursor:null}});await work;const box=find(f.owner.content,node=>node.type==='checkbox');box.checked=true;box.onchange();clickText(f.owner.content,'加入');await tick();assert.equal(f.rpcCalls.at(-1).type,'ADD_TO_TOPICS');f.owner.close(true);await f.owner.compose();const field=f.owner.draft;field.value='SYNTHETIC newer';await f.respond({ok:true,data:{id:'synthetic-thought'}});assert.equal(f.owner.draft,field);assert.equal(f.owner.dialog.open,true);}));
test('held Restore acknowledgement cannot close a newer draft',()=>withTopicActions(async f=>{const work=f.owner.compare('synthetic-thought');await tick();await f.respond({ok:true,data:{entry:{thoughtText:'SYNTHETIC retained',revision:2},input:{body:'SYNTHETIC current Input',revision:3}}});await work;clickText(f.owner.content,'恢复为档案当前文字');await tick();assert.equal(f.rpcCalls.at(-1).type,'RESTORE_THOUGHT_INPUT');f.owner.close(true);await f.owner.compose();const field=f.owner.draft;field.value='SYNTHETIC newer';await f.respond({ok:true,data:{}});assert.equal(f.owner.draft,field);assert.equal(f.owner.dialog.open,true);}));
test('pending Topic creation blocks Thought Save until the selected Topic is acknowledged',()=>withTopicActions(async f=>{f.owner.draft.value='SYNTHETIC body';await createPendingTopic(f);const save=find(f.owner.content,node=>node.textContent==='保存想法');assert.equal(save.disabled,true);await f.submit();assert.equal(f.calls.length,0);await f.respond({ok:true,data:{id:'synthetic-topic'}});assert.equal(save.disabled,false);await f.submit();assert.equal(f.calls[0].topicId,'synthetic-topic');await f.respond(success);assert.equal(f.owner.dialog.open,false);}));
test('unknown Topic creation retains its operation and blocks dependent Thought Save through failed retry',()=>withTopicActions(async f=>{f.owner.draft.value='SYNTHETIC body';const input=await createPendingTopic(f),first=f.rpcCalls.at(-1);await f.respond({ok:false,error:'MESSAGE_CHANNEL_INTERRUPTED'});assert.equal(input.readOnly,true);await f.submit();assert.equal(f.calls.length,0);clickText(f.owner.content,'创建主题');await tick();assert.deepEqual(f.rpcCalls.at(-1),first);await f.respond({ok:false,error:'STORAGE_FAILED'});assert.equal(input.readOnly,true);await f.submit();assert.equal(f.calls.length,0);clickText(f.owner.content,'创建主题');await tick();assert.deepEqual(f.rpcCalls.at(-1),first);await f.respond({ok:true,data:{id:'synthetic-topic'}});await f.submit();assert.equal(f.calls[0].topicId,'synthetic-topic');await f.respond(success);}));

test('acknowledged relation hash cannot close newer text typed during digest',()=>withTopicActions(async f=>{
 f.owner.close(true);await f.owner.compose({relatedThought:{id:'synthetic-related',revision:0,body:'SYNTHETIC prior body'}});const relation=find(f.owner.content,node=>node.type==='checkbox');relation.checked=true;
 await f.submit('SYNTHETIC acknowledged');await f.waitForRequest('CONTINUE_THINKING');const field=f.owner.draft;field.listeners.get('compositionstart')();await f.respond(success);field.listeners.get('compositionend')();
 const original=crypto.subtle.digest;let release;crypto.subtle.digest=function(...args){return new Promise(resolve=>release=()=>resolve(original.apply(this,args)));};
 try{await f.submit();assert.equal(typeof release,'function');field.value='SYNTHETIC newer during digest 👩‍💻\n';release();await tick();await tick();assert.equal(f.owner.draft,field);assert.equal(field.value,'SYNTHETIC newer during digest 👩‍💻\n');assert.equal(f.owner.dialog.open,true);assert.equal(f.calls.length,1);}
 finally{crypto.subtle.digest=original;}
}));

test('missing successful creation identity retains a composer and its exact uncertain operation',()=>withTopicActions(async f=>{await f.submit('SYNTHETIC exact draft');const field=f.owner.draft;await f.respond({ok:true,data:{}});assert.equal(f.owner.draft,field);assert.equal(f.owner.composeSession.uncertain,true);await f.submit();assert.deepEqual(f.calls[1],f.calls[0]);await f.respond(success);assert.equal(f.owner.dialog.open,false);}));
test('missing Topic identity blocks dependent Save and retries its same creation',()=>withTopicActions(async f=>{await createPendingTopic(f);const first=f.rpcCalls.at(-1);await f.respond({ok:true,data:{}});assert.equal(f.owner.surface.pendingChoices,1);clickText(f.owner.content,'创建主题');await tick();assert.deepEqual(f.rpcCalls.at(-1),first);await f.respond({ok:true,data:{id:'synthetic-topic'}});assert.equal(f.owner.surface.pendingChoices,0);}));
test('unknown Add result reconciles original Topic choices through failed retry and preserves new choices',()=>withTopicActions(async f=>{
 const work=f.owner.add({id:'synthetic-input',kind:'input',expectedRevision:0},'SYNTHETIC quote');await tick();await f.respond({ok:true,data:{items:[{id:'topic-a',name:'SYNTHETIC A'},{id:'topic-b',name:'SYNTHETIC B'}],nextCursor:null}});await work;
 const list=find(f.owner.content,node=>node.className==='topic-choice-list'),boxes=list.children.map(label=>label.children[0]);boxes[0].checked=true;boxes[0].onchange();clickText(f.owner.content,'加入');await tick();const first=f.rpcCalls.at(-1);await f.respond({ok:false,error:'MESSAGE_CHANNEL_INTERRUPTED'});
 boxes[0].checked=false;boxes[0].onchange();boxes[1].checked=true;boxes[1].onchange();clickText(f.owner.content,'加入');await tick();assert.deepEqual(f.rpcCalls.at(-1),first);await f.respond({ok:false,error:'STORAGE_FAILED'});clickText(f.owner.content,'加入');await tick();assert.deepEqual(f.rpcCalls.at(-1),first);await f.respond(success);assert.equal(f.owner.dialog.open,true);assert.equal(boxes[1].checked,true);assert.equal(f.owner.feedback.textContent,'先前选择已加入主题。这里的新选择仍未提交。');
 clickText(f.owner.content,'加入');await tick();const next=f.rpcCalls.at(-1);assert.notEqual(next.selection.operationId,first.selection.operationId);assert.deepEqual(next.selection.topicIds,['topic-b']);await f.respond(success);assert.equal(f.owner.dialog.open,false);
}));
