import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {FakeChatGPT,eventually} from './harness/fake-chatgpt.mjs';

const rpc=async(page,type,fields={})=>{const r=await page.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
async function consent(page){const button=page.locator('#enable-consent');await button.waitFor({state:'visible'});await eventually(async()=>!(await button.isDisabled()));await button.click();await eventually(async()=>(await rpc(page,'GET_STATUS')).consented===true);if(await page.locator('#onboarding-skip').isVisible())await page.locator('#onboarding-skip').click();}
async function openSettings(page,group){await page.locator('.sidebar-bottom [data-view="settings"]').click();await eventually(()=>page.locator('#settings-panel').isVisible());await page.locator(`[data-settings-group="${group}"]`).click();await page.locator(`[data-group="${group}"]`).waitFor({state:'visible'});}
async function assertNoNetwork(h){assert.equal(h.deepSeekRequests.length,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);}
async function matrix(page){
 await mkdir('work/ux-r6',{recursive:true});
 for(const [width,height] of [[1440,900],[1024,768],[390,844],[320,720]])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height});await rpc(page,'UPDATE_PREFERENCES',{changes:{appearance:theme}});await eventually(async()=>await page.evaluate(()=>document.documentElement.dataset.paiaTheme)===theme);
  for(const group of ['privacy','data']){
   await page.locator(`[data-settings-group="${group}"]`).click();const root=page.locator(`[data-group="${group}"]`);await root.waitFor({state:'visible'});
   const measure=await root.evaluate(node=>{const rgb=s=>(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number),lum=c=>c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0),contrast=el=>{let p=el,bg;while(p){const value=getComputedStyle(p).backgroundColor;if(value!=='rgba(0, 0, 0, 0)'&&value!=='transparent'){bg=rgb(value);break;}p=p.parentElement;}const fg=rgb(getComputedStyle(el).color),a=lum(fg),b=lum(bg||[255,255,255]);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);};const texts=[...node.querySelectorAll('p,h2,h3,strong,label')].filter(el=>el.getClientRects().length&&getComputedStyle(el).fontSize!=='0px');return {overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,contrast:Math.min(...texts.map(contrast)),r6Buttons:[...node.querySelectorAll('#r6-complete-export button')].filter(el=>el.getClientRects().length).map(el=>({w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height}))};});
   assert.ok(measure.overflow<=2,`${group} ${width} ${theme}: overflow ${measure.overflow}`);assert.ok(measure.contrast>=4.5,`${group} ${width} ${theme}: contrast ${measure.contrast}`);if(width<800)assert.ok(measure.r6Buttons.every(x=>x.w>=44&&x.h>=44),`${group}: R6 mobile targets remain at least 44px`);await page.screenshot({path:`work/ux-r6/${group}-${width}x${height}-${theme}.png`,fullPage:true});
  }
 }
}

test('UX-R6 complete Settings closes preview privacy, open export, Backup status and cross-size release paths without network',{timeout:300000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});let backupBytes;
 try{
  const p=h.archive,marker='UXR6_PRIVATE_PREVIEW 合成私人预览只用于本机发布验收。';await consent(p);await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN',appearance:'light'}});
  await h.open({id:'ux-r6-private',title:'UX-R6 私密预览',base:1609459200,messages:[{id:'ux-r6-private-message',text:marker}]});await eventually(async()=>(await h.state()).records.some(row=>row.originalText===marker),'synthetic Source is captured');await p.bringToFront();
  await p.keyboard.press('Control+k');await eventually(()=>p.locator('#universal-search-dialog').isVisible());const search=p.locator('#universal-search-dialog input[type="search"]');await search.fill('UXR6_PRIVATE_PREVIEW');await eventually(async()=>await p.locator('.universal-open p').first().isVisible());assert.match(await p.locator('.universal-open p').first().textContent(),/UXR6_PRIVATE_PREVIEW/);await p.locator('.universal-close').click();
  await openSettings(p,'privacy');const mask=p.locator('#r6-hide-content-previews');await mask.waitFor();assert.equal(await mask.isChecked(),false,'MIG-01/new preference defaults fail-visible, not hidden');await mask.check();await eventually(async()=>await p.evaluate(()=>document.documentElement.classList.contains('paia-hide-content-previews')));assert.match(await p.locator('#r6-preview-status').textContent(),/不是加密/);
  await p.locator('#ux-settings-back').click();await eventually(()=>p.locator('#core-loop-home').isVisible());await p.keyboard.press('Control+k');await eventually(()=>p.locator('#universal-search-dialog').isVisible());await search.fill('UXR6_PRIVATE_PREVIEW');await eventually(async()=>await p.locator('.universal-open').first().isVisible());assert.equal(await p.locator('.universal-open p').first().evaluate(el=>getComputedStyle(el).display),'none','mask hides the card excerpt but keeps the search result');await p.locator('.universal-open').first().click();await eventually(()=>p.locator('#document-panel').isVisible());assert.match(await p.locator('#document-body').textContent(),/UXR6_PRIVATE_PREVIEW/,'opening the full body remains readable');await p.locator('#back').click();await eventually(()=>p.locator('#universal-search-dialog').isVisible());await p.locator('.universal-close').click();
  await openSettings(p,'data');await eventually(async()=>!(await p.locator('#r6-storage-estimate').textContent()).includes('正在读取'));assert.match(await p.locator('#r6-storage-estimate').textContent(),/已用约|未报告本机已用空间/);assert.match(await p.locator('[data-group="data"]').textContent(),/未提供设备同步/);
  const openDownload=p.waitForEvent('download');await p.locator('#r6-export-json').click();const openFile=await openDownload,openPath=await openFile.path(),bundle=JSON.parse(await readFile(openPath,'utf8'));assert.equal(bundle.format,'PAIA Open Export');assert.ok(bundle.records.some(row=>row.role==='immutable_source_record'&&row.originalText===marker));assert.ok(bundle.records.some(row=>row.role==='input_working_copy'));assert.equal(JSON.stringify(bundle).includes('apiKey'),false);assert.equal(JSON.stringify(bundle).includes('operationReceipts'),false);
  const backupDownload=p.waitForEvent('download');await p.locator('#backup-create').click();const backup=await backupDownload,backupPath=await backup.path();backupBytes=await readFile(backupPath);await eventually(async()=>/最近成功创建备份/.test(await p.locator('#r6-last-backup').textContent()));
  await matrix(p);await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'en'}});await eventually(async()=>await p.locator('#r6-complete-export h3').textContent()==='Complete export');assert.match(await p.locator('#r6-last-backup').textContent(),/Last successful backup/);
  await p.reload();await eventually(async()=>await p.evaluate(()=>document.documentElement.classList.contains('paia-hide-content-previews')),'preview mask survives reload');assert.equal((await rpc(p,'GET_PAGE',{page:{view:'settings'}})).preferences.hideContentPreviews,true);await assertNoNetwork(h);
 }finally{await h.close();}
 assert.ok(backupBytes?.length,'a real local Backup download was captured for restore verification');
 const restored=await FakeChatGPT.start({onboarding:true});
 try{
  const p=restored.archive;await consent(p);await openSettings(p,'data');await p.locator('#backup-file').setInputFiles({name:'UX-R6-roundtrip.paia-backup',mimeType:'application/x-ndjson',buffer:backupBytes});await eventually(()=>p.locator('#backup-preview').isVisible(),'Backup preview is explicit before restore');await eventually(async()=>!(await p.locator('#backup-restore').isDisabled()),'empty-library restore is allowed after validation');await p.locator('#backup-restore').click();await eventually(async()=>/恢复已完成/.test(await p.locator('#backup-status').textContent()));const state=await rpc(p,'GET_PAGE',{page:{view:'settings'}});assert.equal(state.preferences.hideContentPreviews,true,'privacy preview preference round-trips through formal Backup');await eventually(async()=>await p.evaluate(()=>document.documentElement.classList.contains('paia-hide-content-previews')));const archive=await rpc(p,'GET_PAGE',{page:{view:'archive',limit:100}});assert.ok(archive.records.some(row=>row.originalText===marker),'restored Source remains immutable and readable');await assertNoNetwork(restored);
 }finally{await restored.close();}
});
