import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,rows} from './harness/original-complete.mjs';
import {searchMaterialPage} from '../core/search-material-page.js';
const op=()=>crypto.randomUUID();
test('UX-R4 history searches immutable Source text, not present-day edits at an old date; unknown time is never replaced by capture time',async()=>{const f=await completeFixture({texts:['原来的表达 保留甲','时间未知 保留乙']});const blocks=(await rows(f.s,'blocks')).map(r=>r.value),b=blocks[0];await f.s.editDocument({operationId:op(),documentId:b.documentId,blocks:[{id:b.id,expectedRevision:b.revision,libraryText:'今天改写 UNIQUE_NEW',note:'',excluded:false}]});const past=await searchMaterialPage(f.s,{query:'保留',mode:'history'});assert.equal(past.items.length,2);await f.s.repository.transaction(true,async t=>{const r=await t.get('records',b.originalTextReference);r.value.platform='claude';await t.put('records',r);});assert.equal((await searchMaterialPage(f.s,{query:'保留',source:'claude'})).items.length,0);assert.equal((await searchMaterialPage(f.s,{query:'保留',mode:'history',source:'claude'})).items.length,1);assert.ok(past.items.every(i=>i.ref.kind==='source'&&i.body.includes('保留')&&!i.body.includes('UNIQUE_NEW')&&i.sourceSentAt===null));assert.equal((await searchMaterialPage(f.s,{query:'UNIQUE_NEW',mode:'history'})).items.length,0);assert.equal((await searchMaterialPage(f.s,{query:'UNIQUE_NEW'})).items.length,1);await f.s.permanentDelete(b.originalTextReference);assert.equal((await searchMaterialPage(f.s,{query:'保留',mode:'history'})).items.length,1);});
test('UX-R4 page cursors fully enumerate stable IDs, bind query/filter/version, expose partial coverage and respect local scope',async()=>{const f=await completeFixture({texts:Array.from({length:57},(_,i)=>'PAGE_MATCH '+i)});let cursor=null,all=[],first;do{const page=await searchMaterialPage(f.s,{query:'PAGE_MATCH',limit:7,cursor});first??=page;assert.ok(page.items.length<=7);all.push(...page.items);cursor=page.nextCursor;}while(cursor);assert.equal(all.length,57);assert.equal(new Set(all.map(i=>i.ref.id)).size,57);assert.equal(first.complete,false);await assert.rejects(searchMaterialPage(f.s,{query:'OTHER',cursor:first.nextCursor}));const local=await searchMaterialPage(f.s,{query:'PAGE_MATCH',documentId:'missing'});assert.equal(local.items.length,0);const b=(await rows(f.s,'blocks'))[0].value;await f.s.editDocument({operationId:op(),documentId:b.documentId,blocks:[{id:b.id,expectedRevision:b.revision,libraryText:'changed',note:'',excluded:false}]});assert.equal((await searchMaterialPage(f.s,{query:'PAGE_MATCH',limit:7,cursor:first.nextCursor})).changed,true);});
test('UX-R4 Thought placements dedupe by content identity while independent human rewrites and AI authorship stay distinct',async()=>{const f=await completeFixture({texts:['MATCH 源文字']}),b=(await rows(f.s,'blocks'))[0].value;const a=await f.s.createTopic({name:'甲',operationId:op()}),other=await f.s.createTopic({name:'乙',operationId:op()}),made=await f.s.addToTopics({kind:'input',id:b.id,expectedRevision:b.revision,topicIds:[a.id,other.id],operationId:op()});let result=await searchMaterialPage(f.s,{query:'MATCH'});assert.equal(result.items.length,1);const e=await f.s.entry(made.id);await f.s.editLibraryFields({id:e.id,operationId:op(),expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,expectedInputRevision:e.currentInputRevision,changes:{body:'MATCH 独立改写'}});result=await searchMaterialPage(f.s,{query:'MATCH'});assert.equal(result.items.length,2);assert.equal(result.items.find(i=>i.kind==='thought').paths.length,2);assert.equal((await searchMaterialPage(f.s,{query:'MATCH',topicId:a.id})).items.length,2);assert.equal(f.requests.length,0);});

test('VS-04 universal search includes Smart Filter content only by explicit scope and binds cursor to it',async()=>{
 const f=await completeFixture({texts:['unrelated baseline text']});
 const presence={version:1,attachment:'absent',reference:'absent',confidence:'verified'};
 await f.s.capture({epoch:(await f.s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'vs04-filter-search',url:'https://chatgpt.com/c/vs04-filter-search',title:'Filter search fixture'},messages:[{sourceMessageId:'vs04-filter-001',pageOrder:1,originalText:'继续',presence}]});
 await f.s.evaluateFilters();
 const basic=await searchMaterialPage(f.s,{query:'继续',types:['input']});
 assert.equal(basic.items.length,0,'filtered Input stays hidden in ordinary universal results');
 const included=await searchMaterialPage(f.s,{query:'继续',types:['input'],includeFiltered:true});
 assert.equal(included.items.length,1);
 assert.equal(included.items[0].filtered,true);
 const cursor=(await searchMaterialPage(f.s,{query:'',types:['input'],limit:1})).nextCursor;
 assert.ok(cursor);
 await assert.rejects(searchMaterialPage(f.s,{query:'',types:['input'],includeFiltered:true,limit:1,cursor}),{code:'INVALID_REQUEST'});
 await f.s.setFilterMode('off');
 assert.equal((await searchMaterialPage(f.s,{query:'继续',types:['input']})).items.length,1,'Off mode shows the same saved Input without changing it');
});
