import {openRetainedSearchComponent} from './harness/retained-search-component.mjs';
import {settleContextCapture,assertContextUnavailable,assertNoContextSession,contextSafetySnapshot,observeContextEffects,assertNoContextEffects} from './current-context-scope-helper.mjs';
import {seedUXLarge} from './harness/ux-large.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT} from './harness/fake-chatgpt.mjs';
const dir=new URL('../work/ux-r4/',import.meta.url);
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',attempts=120){for(let i=0;i<attempts;i++){if(await fn())return;await pause(100);}throw Error('Timed out: '+label);}
const rpc=(p,type,fields={})=>p.evaluate(async x=>{const r=await chrome.runtime.sendMessage(x);if(!r?.ok)throw Error(JSON.stringify(r));return r.data;},{type,...fields});
async function waitForStableDataGeneration(p,label='portable data generation settles'){
 let previous=null,stable=0;
 await until(async()=>{
  const current=await p.evaluate(async()=>{
   const {OrganizerStore}=await import('../core/organizer/store.js');
   const s=new OrganizerStore(chrome.storage.local);
   return s.run(()=>s.repository.transaction(false,async t=>(await t.get('meta','backup-data-generation'))?.value||0,['meta']));
  });
  if(current===previous)stable++;else{previous=current;stable=0;}
  return stable>=4;
 },label,80);
}
async function start(messages){const h=await FakeChatGPT.start(),p=h.archive;try{await mkdir(dir,{recursive:true});await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await until(async()=>(await rpc(p,'GET_STATUS')).consented);const chat=await h.open({id:'uxr4-synthetic',title:'UX-R4 synthetic',base:1609459200,messages:messages.map((text,i)=>({id:'uxr4-input-'+i,text}))});await until(async()=>(await h.state()).records.length===messages.length,'fixture capture');return {h,p,chat};}catch(e){await h.close();throw e;}}
async function search(p,q){await p.evaluate(()=>{if(globalThis.__uxr4Search)return;globalThis.__uxr4Search=[];const send=chrome.runtime.sendMessage.bind(chrome.runtime);chrome.runtime.sendMessage=async(...args)=>{const result=await send(...args);if(args[0]?.type==='SEARCH_INPUTS')globalThis.__uxr4Search.push({options:args[0].options,ok:result.ok,error:result.error,count:result.data?.items?.length,cursor:result.data?.nextCursor});return result;};});assert.equal(await p.locator('#universal-search-open').isVisible(),false);assert.equal(await p.locator('#archive-select-materials').count(),0);await openRetainedSearchComponent(p,{types:['input','thought','ai']});await p.getByRole('searchbox',{name:'全局搜索'}).fill(q);await until(async()=>(await p.locator('#universal-search-dialog').getAttribute('data-query'))===q&&await p.locator('.universal-hit').count()>0,'completed query');}
const clean=h=>{assert.equal(h.deepSeekRequests.length,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);};
// Original Context UI journeys remain byte-identical in historical-uxr4-context-chrome-e2e.test.mjs.
test('UX-R4 retained Search preserves Reader return, pagination and query freshness while retired Tray selection remains absent',{timeout:180000},async()=>{const {h,p,chat}=await start(Array.from({length:45},(_,i)=>'UXR4_SEARCH 合成材料 '+i));try{await search(p,'UXR4_SEARCH');const worker=h.context.serviceWorkers().find(w=>w.url().includes('/background/service-worker.js'));assert.ok(worker);await p.evaluate(()=>{globalThis.__uxr4StableHit=document.querySelector('.universal-hit');});await worker.evaluate(()=>{void chrome.runtime.sendMessage({type:'ARCHIVE_CHANGED',cause:'RECORD_TOPIC_READ'}).catch(()=>{});});await pause(250);assert.equal(await p.evaluate(()=>globalThis.__uxr4StableHit===document.querySelector('.universal-hit')),true,'maintenance notification must not remount Universal Search results');
// A delayed older response must not replace the newer query; composition must not issue requests.
await p.evaluate(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);chrome.runtime.sendMessage=async(...a)=>{const r=await send(...a);if(a[0]?.type==='SEARCH_INPUTS'&&a[0].options.query==='材料 1')await new Promise(r=>setTimeout(r,700));return r;};});
const box=p.getByRole('searchbox',{name:'全局搜索'});await box.fill('材料 1');await pause(300);await box.fill('材料 2');await until(async()=>(await p.locator('#universal-search-dialog').getAttribute('data-query'))==='材料 2');await pause(800);assert.equal(await p.locator('#universal-search-dialog').getAttribute('data-query'),'材料 2');
const calls=await p.evaluate(()=>globalThis.__uxr4Search.length);await box.evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart'));el.value='UXR4_SEARCH';el.dispatchEvent(new InputEvent('input',{isComposing:true,bubbles:true}));});await pause(300);assert.equal(await p.evaluate(()=>globalThis.__uxr4Search.length),calls);await box.evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend')));await until(async()=>(await p.locator('#universal-search-dialog').getAttribute('data-query'))==='UXR4_SEARCH');
await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'en'}});await until(()=>p.getByRole('searchbox',{name:'Global search'}).isVisible());assert.ok((await p.locator('.universal-hit').first().textContent()).includes('合成材料'));assert.ok((await p.locator('.universal-status').textContent()).includes('Currently loaded'));await p.screenshot({path:new URL('search-english.png',dir).pathname});await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN'}});await until(()=>p.getByRole('searchbox',{name:'全局搜索'}).isVisible());
await until(async()=>await p.locator('.universal-hit').count()===40);assert.equal(await p.locator('.universal-hit input[type=checkbox],.universal-selection').count(),0,'the retired Tray has no search selection controls');await p.locator('.universal-pagination').getByRole('button',{name:'下一页',exact:true}).click();try{await until(async()=>await p.locator('.universal-hit').count()===5,'second search page');}catch(e){await writeFile(new URL('search-debug.json',dir),JSON.stringify({status:await p.locator('.universal-status').textContent(),count:await p.locator('.universal-hit').count(),errors:h.errors,requests:await p.evaluate(()=>globalThis.__uxr4Search)}));throw e;}await p.locator('.universal-open').first().click();await until(()=>p.locator('#document-panel').isVisible());await p.locator('#back').click();await until(()=>p.locator('#universal-search-dialog').isVisible());assert.equal(await p.getByRole('searchbox',{name:'全局搜索'}).inputValue(),'UXR4_SEARCH');assert.equal(await p.locator('.universal-hit').count(),5);assert.equal(await p.locator('.universal-hit input[type=checkbox],.universal-selection').count(),0,'Reader return cannot revive retired Tray selection');
await assertNoContextSession(p);
await p.getByRole('searchbox',{name:'全局搜索'}).fill('材料 4');await until(async()=>await p.locator('.universal-hit').count()!==5);
const scanBefore=(await rpc(p,'GET_PAGE',{page:{view:'settings'}})).diagnostics.lastScanAt;await h.edit(chat,'uxr4-input-0','UXR4_SEARCH 合成材料 0',false);await until(async()=>String((await rpc(p,'GET_PAGE',{page:{view:'settings'}})).diagnostics.lastScanAt)!==String(scanBefore),'duplicate capture scan');
assert.equal(await p.locator('.universal-hit input[type=checkbox],.universal-selection').count(),0,'duplicate capture cannot revive retired Tray selection');
await h.open({id:'uxr4-additional',title:'Additional',base:1609459200,messages:Array.from({length:20},(_,i)=>({id:'uxr4-extra-'+i,text:'UXR4_SEARCH 新材料 '+i}))});await until(async()=>(await h.state()).records.length===65);
assert.equal(await p.locator('.universal-hit input[type=checkbox],.universal-selection').count(),0,'new captured inputs cannot start a Tray');
await assertNoContextSession(p);clean(h);}finally{await h.close();}});
test('UX-R4 Local-only worker refuses Provider work and current Context remains unavailable without altering stored material',{timeout:180000},async()=>{const {h,p,chat}=await start(['合成姓名甲 UXR4_PRIVATE '+ '完整长文 👩🏽‍💻 '.repeat(400),'合成姓名甲 UXR4_PRIVATE 第二条','合成姓名甲 UXR4_EXTRA 补充材料']);try{await mkdir(dir,{recursive:true});await rpc(p,'PAIA_MEMORY_SETTINGS',{options:{externalAccess:false,localOnly:true}});for(const type of ['SAVE_DEEPSEEK_CREDENTIAL','UPDATE_ORIGINAL_LIBRARY_VIEW']){const denied=await p.evaluate(type=>chrome.runtime.sendMessage({type}),type);assert.equal(denied.error,'AI_SERVICE_UNAVAILABLE');}assert.equal(h.extensionNetworkRequests,0);await settleContextCapture(h);
const before=await contextSafetySnapshot(p);await observeContextEffects(p);await assertContextUnavailable(p);assert.deepEqual(await contextSafetySnapshot(p),before);await assertNoContextEffects(p,h);clean(h);}finally{await h.close();}});
test('UX-R4 retained historical Search and comparison keep original Source bodies and unknown time across the responsive matrix',{timeout:240000},async()=>{const {h,p}=await start(['UXR4_MATRIX 当时的想法甲','UXR4_MATRIX 当时的想法乙','UXR4_MATRIX 未知时间表达']);try{await mkdir(dir,{recursive:true});await h.open({id:'uxr4-unknown-time',title:'Unknown source time',messages:[{id:'uxr4-unknown-input',text:'UXR4_MATRIX 时间证据未知'}]});await until(async()=>(await h.state()).records.length===4);await search(p,'UXR4_MATRIX');await matrix('search');const original=await rpc(p,'SEARCH_INPUTS',{options:{universal:true,paged:true,query:'UXR4_MATRIX'}}),first=original.items[0],b=await rpc(p,'GET_INPUT',{id:first.id});await rpc(p,'EDIT_DOCUMENT',{edit:{documentId:b.documentId,operationId:crypto.randomUUID(),blocks:[{id:b.id,expectedRevision:b.revision,libraryText:'今天改写 UXR4_CURRENT_ONLY',note:b.note,excluded:false}]}});await p.getByRole('button',{name:'按时间看 · 以前的我',exact:true}).click();await until(async()=>await p.locator('.historical-body').count()===4);assert.equal((await p.locator('.universal-results').textContent()).includes('UXR4_CURRENT_ONLY'),false);await p.getByRole('button',{name:'选择并置',exact:true}).nth(0).click();await p.getByRole('button',{name:'选择并置',exact:true}).nth(0).click();await p.getByRole('button',{name:'并置所选两条',exact:true}).click();assert.equal(await p.locator('.historical-comparison pre').count(),2);
 async function matrix(name){for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});await pause(80);await p.screenshot({path:new URL(name+'-'+appearance+'-'+width+'.png',dir).pathname});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' horizontal overflow');}}}
 assert.ok((await p.locator('.universal-results').textContent()).includes('发送时间未知'));await matrix('history');await assertNoContextSession(p);clean(h);}finally{await h.close();}});
test('UX-R4 F-LARGE search and direct long Input reuse stay bounded; retired Context refuses full long Input without truncation',{timeout:300000},async()=>{const h=await FakeChatGPT.start(),p=h.archive;try{await p.locator('#consent-check').check();await p.locator('#enable-consent').click();await until(async()=>(await rpc(p,'GET_STATUS')).consented);const seed=await seedUXLarge(p);assert.deepEqual(seed.counts,{inputs:100000,documents:1000,topics:300,entries:5000});const measure=await p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js');const s=new OrganizerStore(chrome.storage.local);await s.finishFoundation();s.repository.metrics={reads:0,writes:0,scans:0};const start=performance.now(),page=await s.searchInputs({universal:true,paged:true,query:'',documentId:'document:large-501',types:['input'],limit:40});return {ms:performance.now()-start,...s.repository.metrics,count:page.items.length,scanned:page.scanned,next:!!page.nextCursor};});assert.equal(measure.count,40);assert.ok(measure.scanned<=200);assert.equal(measure.writes,0);await search(p,'Synthetic');assert.ok(await p.locator('.universal-hit').count()<=40);await p.screenshot({path:new URL('large-search.png',dir).pathname});await p.locator('.universal-close').click();const input=await rpc(p,'GET_INPUT',{id:'block:large-record-00050110'});const original=await p.evaluate(async id=>{const {OrganizerStore}=await import('../core/organizer/store.js'),store=new OrganizerStore(chrome.storage.local);return store.run(()=>store.repository.transaction(false,async t=>(await t.get('records',id)).value.originalText,['records']));},input.originalTextReference);const readable=input.libraryText??original;assert.ok(readable.includes('中'.repeat(50000)),'full long Input resolves its preserved Source without truncation or Tray');for(const action of ['create','add','task','compile','confirmReview','share']){const result=await p.evaluate(action=>chrome.runtime.sendMessage({type:'PAIA_CONTEXT_MANUAL',options:{action}}),action);assert.equal(result.error,'FEATURE_UNAVAILABLE');}assert.deepEqual(await rpc(p,'GET_INPUT',{id:input.id}),input);await writeFile(new URL('large-fixture.json',dir),JSON.stringify({seed,search:measure,retiredContextRejected:true,readCharacters:readable.length},null,2));
 clean(h);
 }finally{await h.close();}});

test('UX-R4 real worker legacy revocation remains available while new grants and manual output refuse',{timeout:120000},async()=>{const {h,p,chat}=await start(['UXR4_GRANT_MATCH 合成受控文字']);try{
 await until(async()=>p.evaluate(async()=>{
  const {OrganizerStore}=await import('../core/organizer/store.js');
  const {SourceStructureStore}=await import('../core/source-structure-store.js');
  const row=await new SourceStructureStore(new OrganizerStore(chrome.storage.local)).conversation({platform:'chatgpt',sourceConversationId:'uxr4-synthetic'});
  return row?.membership.state==='unassigned';
 }),'grant fixture source observation settles');
 // The grant concurrency test starts from a settled archive, without a live
 // producer invalidating its preview between build and the two share calls.
 await chat.close();

 // This test exercises Grant once/revoke concurrency, not capture freshness.
 // Wait until all real capture/enrichment/source-structure writes have stopped
 // changing the same portable-data generation that MemoryService binds into a
 // preview. A later real data change must still produce MEMORY_STALE.
 await until(async()=>{const filter=await rpc(p,'FILTER_STATUS');return filter.pending===0&&filter.taskState==='idle';},'grant fixture capture/filter quiescence');
 await waitForStableDataGeneration(p,'grant fixture portable data generation settles');
const before=await contextSafetySnapshot(p);for(const type of ['PAIA_MEMORY_BUILD','PAIA_PASSPORT_CREATE','PAIA_CONTEXT_BIND','PAIA_MEMORY_SHARE','PAIA_CONTEXT_MANUAL']){const result=await p.evaluate(type=>chrome.runtime.sendMessage({type}),type);assert.equal(result.error,'FEATURE_UNAVAILABLE');}assert.deepEqual(await contextSafetySnapshot(p),before,'retired grant creation and output do not consume or mutate anything');
await p.evaluate(async()=>{const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local);await s.finishFoundation();await s.foundationWrite(t=>t.put('meta',{id:'passport:grant:uxr4-legacy',kind:'grant',version:1,grantId:'uxr4-legacy',consumer:'chatgpt',purpose:'research',resourceScope:'profile',profileId:'default',permission:'context_export',duration:'once',createdAt:new Date().toISOString(),expiresAt:null,revokedAt:null,consumedAt:null,lastUsedAt:null,useCount:0}));});
await rpc(p,'PAIA_PASSPORT_REVOKE',{grantId:'uxr4-legacy'});const grant=(await rpc(p,'PAIA_PASSPORT_STATUS')).grants.find(x=>x.grantId==='uxr4-legacy');assert.equal(grant.state,'revoked');assert.equal(grant.useCount,0);clean(h);
}finally{await h.close();}});

// The worker-lifetime fence previously appeared after the withdrawn UI tray
// journey. Exercise the same real worker contract without enabling that UI.
test('UX-R4 retained real worker retired output refuses before and after worker restart with Source and policy intact',{timeout:120000},async()=>{
 const text='UXR4_WORKER_EXPIRY 原始完整文字\n<literal> 👩🏽‍💻\n\n第二段仍保持原样。', {h,p}=await start([text]);
 try{
  await settleContextCapture(h);await assertNoContextSession(p);
  const originals=structuredClone((await h.state()).records),memory=await rpc(p,'PAIA_MEMORY_STATUS'),passport=await rpc(p,'PAIA_PASSPORT_STATUS');
  const results=await rpc(p,'SEARCH_INPUTS',{options:{universal:true,paged:true,query:'UXR4_WORKER_EXPIRY',types:['input']}});
  assert.equal(results.items.length,1);
  for(const action of ['create','add','compile','confirmReview','share']){const denied=await p.evaluate(action=>chrome.runtime.sendMessage({type:'PAIA_CONTEXT_MANUAL',options:{action,selectionId:'historical-selection',generation:0}}),action);assert.equal(denied.error,'FEATURE_UNAVAILABLE');}
  await h.restartWorker();const deniedAfterRestart=await p.evaluate(()=>chrome.runtime.sendMessage({type:'PAIA_CONTEXT_MANUAL',options:{action:'share',selectionId:'historical-selection',generation:0,format:'copy'}}));assert.equal(deniedAfterRestart.error,'FEATURE_UNAVAILABLE','old output cannot become reachable across a real worker restart');
  await assertNoContextSession(p);assert.equal(await p.locator('#material-output-text').count(),0);
  assert.deepEqual((await h.state()).records,originals,'worker review and expiry never rewrite Source');
  assert.deepEqual((await rpc(p,'PAIA_MEMORY_STATUS')).config,memory.config);assert.deepEqual((await rpc(p,'PAIA_PASSPORT_STATUS')).grants,passport.grants);clean(h);
 }finally{await h.close();}
});
