import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
async function ready(h){const p=h.archive;await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN'}});await eventually(async()=>(await p.evaluate(()=>document.documentElement.lang))==='zh-CN');return p;}
async function navigate(p,detail){await p.evaluate(detail=>document.dispatchEvent(new CustomEvent('paia:navigate',{detail})),detail);await eventually(()=>p.locator(detail.view==='revisit'?'#revisit-panel':detail.documentId?'#document-panel':'#collection-panel').isVisible());}
const input=p=>p.locator('.library-prose').first();
async function menu(p,label,field=input(p)){await field.click({button:'right'});await p.locator('#context-menu button').filter({hasText:label}).click();}
function offline(h){assert.equal(h.externalRequests,0);assert.equal(h.extensionNetworkRequests,0);assert.equal(h.deepSeekRequests.length,0);assert.deepEqual(h.errors,[]);}
async function shot(p,name){await mkdir('work/ux-r2',{recursive:true});await p.screenshot({path:`work/ux-r2/${name}.png`,fullPage:false});}

test('UX-R2 overlapping startup reads wait for the rendered Reader; late stale failures cannot move or fail the resumed page',{timeout:90000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  let p=await ready(h);const chatPage=await h.open({id:'uxr2-interleaved',title:'Synthetic interleaved Reader',base:1609459200,messages:[{id:'uxr2-interleaved-message-001',text:'UXR2_INTERLEAVED '+('Long synthetic reading line.\n'.repeat(400))}]});await eventually(async()=>(await h.state()).records.length===1);const b=(await h.state()).library.blocks[0],offset=400;
  await rpc(p,'PAIA_READER_SAVE',{anchor:{documentId:b.documentId,inputId:b.id,revision:b.revision,offset,sort:'asc',expanded:[b.id]}});await p.close();p=await h.context.newPage();h.archive=p;p.on('pageerror',e=>h.errors.push(e.message));
  // Real worker responses and mutation notifications are retained. Only their
  // delivery order is controlled, so the obsolete read must lose ownership.
  await p.addInitScript(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);let firstBoot=true;globalThis.__uxR2Reads=[];globalThis.__uxR2HoldReads=true;chrome.runtime.sendMessage=async message=>{const response=await send(message);if(message.type==='GET_ONBOARDING'&&firstBoot){firstBoot=false;globalThis.__uxR2BootPending=true;await new Promise(resolve=>{globalThis.__uxR2ReleaseBoot=resolve;});}if(message.type==='GET_PAGE'&&message.page.documentId&&globalThis.__uxR2HoldReads){const pending={};globalThis.__uxR2Reads.push(pending);await new Promise(resolve=>{pending.release=resolve;});if(pending.fail)throw Error('SYNTHETIC_DELAYED_READ_FAILURE');}return response;};});
  await p.goto(`chrome-extension://${h.extensionId}/ui/archive.html`,{waitUntil:'commit'});await p.locator('.reader-resume-action').first().waitFor();assert.equal(await p.evaluate(()=>globalThis.__uxR2BootPending),true);await p.locator('.reader-resume-action').first().click();await p.evaluate(()=>globalThis.__uxR2ReleaseBoot());await eventually(()=>p.evaluate(()=>globalThis.__uxR2Reads.length>=1));await h.send(chatPage,{id:'uxr2-interleaved-message-002',text:'UXR2_INTERLEAVED concurrent capture 2'});await eventually(async()=>(await h.state()).records.length===2,'policy chat captured');await eventually(()=>p.evaluate(()=>globalThis.__uxR2Reads.length>=2));await p.evaluate(()=>globalThis.__uxR2Reads[0].release());await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  assert.equal(await p.evaluate(()=>history.state?.paiaReader?.documentId),null,'stale completion cannot commit a route before its Reader exists');assert.equal(await p.locator('.library-prose').count(),0);await p.evaluate(()=>{globalThis.__uxR2HoldReads=false;for(const pending of globalThis.__uxR2Reads)pending.release();});
  const assertPosition=async()=>{await eventually(()=>p.evaluate(id=>history.state?.paiaReader?.documentId===id,b.documentId));const prose=p.locator(`.library-prose[data-item-id="${b.id}"]`);await prose.waitFor();assert.ok(await p.evaluate(()=>scrollY)>100,'resume enters long prose');assert.ok(Math.abs(await prose.evaluate((el,offset)=>{const r=document.createRange();r.setStart(el.firstChild,offset);r.collapse(true);return r.getBoundingClientRect().top;},offset)-140)<=2,'the saved character aligns after the authoritative render');};
  await assertPosition();await p.locator('#back').click();await eventually(()=>p.evaluate(()=>history.state?.paiaReader?.documentId===null));await p.evaluate(()=>{globalThis.__uxR2Reads=[];globalThis.__uxR2HoldReads=true;});await p.locator('.reader-resume-action').first().click();await eventually(()=>p.evaluate(()=>globalThis.__uxR2Reads.length>=1));await h.send(chatPage,{id:'uxr2-interleaved-message-003',text:'UXR2_INTERLEAVED concurrent capture 3'});await eventually(async()=>(await h.state()).records.length===3,'unexcluded conversation captured');await eventually(()=>p.evaluate(()=>globalThis.__uxR2Reads.length>=2));await p.evaluate(()=>{globalThis.__uxR2HoldReads=false;for(const pending of globalThis.__uxR2Reads.slice(1))pending.release();});await assertPosition();
  await p.evaluate(()=>{const pending=globalThis.__uxR2Reads[0];pending.fail=true;pending.release();});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await p.locator('#error').isVisible(),false,'obsolete rejected reads do not report failure on the current Reader');await assertPosition();await shot(p,'overlapping-resume');offline(h);
 }finally{await h.close();}
});

test('UX-R2 true dwell position survives another capture, tab reopen, paging and sort; default/selected responsive matrix',{timeout:180000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  let p=await ready(h);await p.setViewportSize({width:1440,height:900});
  const long='UXR2_LONG_TARGET 中文与 emoji 👩‍💻\n'+('一段仍然可以完整搜索与复制的中文。代码 <script>不执行</script> https://example.invalid/long/path\n'.repeat(750));
  const chat={id:'uxr2-read-a',title:'阅读 A · 连续记录',base:1609459200,messages:Array.from({length:135},(_,i)=>({id:'uxr2-a-'+i,text:i===110?long:`UXR2_A_${i} 这是合成记录第 ${i} 条，用于验证跨页定位。\n保持原始段落身份。`}))};
  const aPage=await h.open(chat);await eventually(async()=>(await h.state()).records.length===135,'all synthetic live inputs captured',35000);await p.bringToFront();
  assert.deepEqual(await rpc(p,'PAIA_READER_RECENT'),[],'capture is not reading');
  await p.locator('#search').fill('UXR2_LONG_TARGET');await eventually(()=>p.locator('.search-input').isVisible(),'search locates text beyond the first 100 inputs');await p.locator('.search-input').click();
  const target=p.locator('.library-prose').filter({hasText:'UXR2_LONG_TARGET'});await target.waitFor();assert.equal(await target.evaluate(el=>el.classList.contains('reader-collapsed')),false);assert.ok(await p.locator('.library-prose').count()<=100,'Reader mounts bounded surrounding Inputs');
  const id=await target.getAttribute('data-edit-id'),before=await rpc(p,'GET_INPUT',{id});
  await target.evaluate(el=>{el.focus();const r=document.createRange();r.setStart(el.firstChild,42);r.collapse(true);const s=getSelection();s.removeAllRanges();s.addRange(r);const rect=r.getBoundingClientRect();scrollBy(0,rect.top-180);});
  await pause(1000);assert.deepEqual(await rpc(p,'PAIA_READER_RECENT'),[],'instant search preview is not formal reading');
  await eventually(async()=>(await rpc(p,'PAIA_READER_RECENT'))[0]?.inputId===id,'three second visible dwell establishes the actual Input position');
  const anchor=(await rpc(p,'PAIA_READER_RECENT'))[0];assert.equal(anchor.offset,42);assert.equal(anchor.documentId,before.documentId);
  await h.open({id:'uxr2-read-b',title:'后来收录 B',base:1700000000,messages:[{id:'uxr2-b-one',text:'UXR2_B This capture must never replace reading A.'}]});await eventually(async()=>(await h.state()).records.length===136);await p.bringToFront();assert.equal((await rpc(p,'PAIA_READER_RECENT'))[0].inputId,id);
  const scrollBefore=await p.evaluate(()=>scrollY),topBefore=await target.evaluate(el=>el.getBoundingClientRect().top);await h.send(aPage,{id:'uxr2-a-late',text:'UXR2_SAME_CHAT_LATE 新内容只能提示，不能挪动阅读现场。'});await eventually(()=>p.locator('#reader-load-new').isVisible(),'same-conversation capture offers an explicit refresh');await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const scrollAfter=await p.evaluate(()=>scrollY),topAfter=await target.evaluate(el=>el.getBoundingClientRect().top);assert.ok(Math.abs(scrollAfter-scrollBefore)<=2,`same-conversation capture must not jump the Reader: scroll ${scrollBefore} → ${scrollAfter}, prose ${topBefore} → ${topAfter}`);assert.ok(Math.abs(topAfter-topBefore)<=2,'new-content feedback preserves the visible prose position');assert.equal((await rpc(p,'PAIA_READER_RECENT'))[0].inputId,id);await p.mouse.move(10,10);await eventually(()=>p.locator('#reader-load-new').isHidden(),'transient notice expires without moving the Reader',12000);await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.ok(Math.abs((await p.evaluate(()=>scrollY))-scrollBefore)<=2,'notice expiration preserves scroll');assert.ok(Math.abs((await target.evaluate(el=>el.getBoundingClientRect().top))-topBefore)<=2,'notice expiration preserves visible prose');
  await p.close();p=await h.context.newPage();h.archive=p;p.on('pageerror',e=>h.errors.push(e.message));await p.addInitScript(()=>{const send=chrome.runtime.sendMessage.bind(chrome.runtime);let first=true;chrome.runtime.sendMessage=async message=>{const result=await send(message);if(message.type==='GET_ONBOARDING'&&first){first=false;globalThis.__uxR2BootReadPending=true;await new Promise(resolve=>{globalThis.__uxR2ReleaseBoot=resolve;});globalThis.__uxR2BootReadPending=false;}return result;};});await p.goto(`chrome-extension://${h.extensionId}/ui/archive.html`,{waitUntil:'commit'});
  await eventually(()=>p.locator('.reader-resume-action').isVisible(),'new tab shows real Continue');assert.match(await p.locator('.reader-resume-action').first().textContent(),/阅读 A/);assert.match(await p.locator('#core-loop-continue').textContent(),/阅读 A/,'Recently Captured independently follows the actual latest capture');
  assert.equal(await p.evaluate(()=>globalThis.__uxR2BootReadPending),true,'Continue can be selected while the first real onboarding read is still pending');await p.locator('.reader-resume-action').first().click();await p.evaluate(()=>globalThis.__uxR2ReleaseBoot());await eventually(()=>p.evaluate(documentId=>history.state?.paiaReader?.documentId===documentId,before.documentId),'resume navigation commits after restoring its position');await eventually(()=>p.locator('.library-prose').filter({hasText:'UXR2_LONG_TARGET'}).isVisible());
  assert.ok(await p.evaluate(()=>scrollY)>100,'resume returns into long prose instead of the top');assert.ok(Math.abs(await p.locator('.library-prose').filter({hasText:'UXR2_LONG_TARGET'}).evaluate(el=>{const r=document.createRange();r.setStart(el.firstChild,42);r.collapse(true);return r.getBoundingClientRect().top;})-140)<=2,'resume aligns the saved character offset in the viewport');
  const orderToggle=p.locator('#input-time-toggle');assert.equal(await p.locator('#input-time-order button').count(),1,'Input order is a single toggle');
  await orderToggle.click();await eventually(async()=>(await orderToggle.getAttribute('aria-pressed'))==='true'&&(await orderToggle.getAttribute('data-current-sort'))==='desc');assert.equal(await p.locator('.library-prose').filter({hasText:'UXR2_LONG_TARGET'}).count(),1,'sort preserves target across pages');
  await orderToggle.click();await eventually(async()=>(await orderToggle.getAttribute('aria-pressed'))==='false'&&(await orderToggle.getAttribute('data-current-sort'))==='asc');
  const matrix=[[1440,900],[1024,768],[390,844],[320,720]],measurements=[];
  for(const [width,height]of matrix){await p.setViewportSize({width,height});for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});await eventually(async()=>await p.evaluate(()=>document.documentElement.dataset.paiaTheme)===appearance);await p.evaluate(()=>{getSelection().removeAllRanges();document.activeElement?.blur();scrollTo(0,0);});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await shot(p,`reader-${width}x${height}-${appearance}`);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);assert.ok(overflow<=2,`${width} ${appearance} overflow ${overflow}`);assert.equal(await p.locator('.reader-mobile-edit').first().isVisible(),width<800,'per-Input Edit is mobile-only');assert.equal(await p.locator('.input-remove').first().evaluate(el=>getComputedStyle(el,'::before').display),'none','legacy pseudo-icon is not stacked with the current trash icon');measurements.push({width,height,appearance,overflow});}}
  await p.setViewportSize({width:1440,height:900});const selected=p.locator('.library-prose').filter({hasText:'UXR2_LONG_TARGET'});await selected.evaluate(el=>{el.focus();const r=document.createRange();r.setStart(el.firstChild,0);r.setEnd(el.firstChild,15);getSelection().removeAllRanges();getSelection().addRange(r);el.scrollIntoView();});await eventually(()=>p.locator('.reader-selection').isVisible());await shot(p,'reader-selected');
  await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);
  const cdp=await h.context.newCDPSession(p);await p.setViewportSize({width:640,height:900});await cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:2});await shot(p,'reader-200pct');await cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:1});await cdp.detach();
  await writeFile('work/ux-r2/reader-matrix.json',JSON.stringify({fixture:{inputs:137,longCharacters:long.length},measurements,externalRequests:h.externalRequests,extensionNetworkRequests:h.extensionNetworkRequests},null,2));offline(h);
 }finally{await h.close();}
});

test('UX-R2 IME saves only complete text; failed save preserves buffer, retry/undo/revision/Source and mobile Done work',{timeout:180000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  const p=await ready(h),original='UXR2_EDIT 原始输入不可改变。\n第二行。',chat={id:'uxr2-edit',title:'编辑与核对',base:1609459200,messages:[{id:'uxr2-edit-one',text:original},{id:'uxr2-edit-two',text:'UXR2_EDIT_SECOND 另一条输入，不能跨界剪切合并。'}]};await h.open(chat);await eventually(async()=>(await h.state()).records.length===2,'permanent Source purge committed');await p.bringToFront();await p.locator('#core-loop-continue').click();await input(p).waitFor();
  const field=input(p),id=await field.getAttribute('data-edit-id'),before=await rpc(p,'GET_INPUT',{id});
  await field.evaluate(el=>{el.focus();el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:''}));el.textContent='尚未完成的拼音 ni';el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertCompositionText',isComposing:true,data:'ni'}));});await pause(900);assert.equal((await rpc(p,'GET_INPUT',{id})).revision,before.revision,'composition writes no partial body');
  const edited='UXR2_EDIT 我今天决定保留完整中文、👩‍💻 和原来的换行。\n这是最终输入。';
  await field.evaluate((el,text)=>{el.textContent=text;el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:text}));el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));},edited);await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText===edited);
  // Inject one storage failure at the actual IndexedDB boundary, not the UI/RPC.
  const worker=h.context.serviceWorkers()[0];await worker.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...args){if(this.name==='blocks'&&value?.value?.libraryText?.includes('UXR2_SAVE_FAIL')){IDBObjectStore.prototype.put=put;throw new DOMException('Synthetic storage failure','QuotaExceededError');}return put.call(this,value,...args);};});
  const failed=edited+'\nUXR2_SAVE_FAIL 当前草稿必须保留。';await field.fill(failed);await eventually(()=>p.locator('#retry').isVisible(),'real failed transaction surfaces Retry');assert.equal(await field.innerText(),failed);assert.equal((await rpc(p,'GET_INPUT',{id})).libraryText,edited);assert.equal(await p.locator('#reader-copy-buffer').isVisible(),true);await shot(p,'reader-save-failure');await p.locator('#primary-nav [data-view="library"]').click();assert.equal(await p.locator('#document-panel').isVisible(),true,'failed save blocks navigation without losing the draft');assert.equal(await field.innerText(),failed);
  await p.evaluate(()=>{globalThis.__copied='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{globalThis.__copied=text;}}});});await p.locator('#reader-copy-buffer').click();assert.match(await p.evaluate(()=>globalThis.__copied),/UXR2_SAVE_FAIL/,'Copy uses the unsaved buffer');
  await p.locator('#retry').click();await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText===failed);await field.focus();await p.keyboard.press('Control+z');await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText===edited,'undo commits through real revision transaction');await p.keyboard.press('Control+Shift+z');await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText===failed);
  // Cross-Input modification is refused, while the native range remains copyable.
  assert.equal(await p.evaluate(()=>{const fields=[...document.querySelectorAll('.library-prose')],r=document.createRange();r.setStart(fields[0].firstChild,0);r.setEnd(fields[1].firstChild,5);getSelection().removeAllRanges();getSelection().addRange(r);return fields[0].dispatchEvent(new InputEvent('beforeinput',{bubbles:true,cancelable:true,inputType:'deleteByCut'}));}),false);
  await field.click();await menu(p,'查看当时记录',field);await eventually(()=>p.locator('#info-dialog').evaluate(el=>el.open),'Source dialog opened');assert.equal(await p.locator('#info-content .source-original').innerText(),original);assert.equal(await p.locator('#info-content [contenteditable]').count(),0);assert.match(await p.locator('#info-content').textContent(),/2021|缺少当时/);await shot(p,'reader-source');for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});await eventually(async()=>await p.evaluate(()=>document.documentElement.dataset.paiaTheme)===appearance);await shot(p,`source-${width}x${height}-${appearance}`);const box=await p.locator('#info-dialog').boundingBox();assert.ok(box.width<=width&&box.height<=height,'Source panel fits the current viewport');assert.ok(await p.locator('#info-dialog').evaluate(el=>el.scrollWidth-el.clientWidth)<=2,'Source text wraps without horizontal overflow');}}await p.setViewportSize({width:1280,height:720});await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:'light'}});await p.locator('#close-info').click();
  const revisions=await rpc(p,'GET_REVISIONS',{options:{documentId:before.documentId,kind:'input',entityId:id}}),chosen=revisions.items.sort((a,b)=>b.sequence-a.sequence)[0],expected=chosen.before.libraryText;await menu(p,'版本历史',field);await eventually(()=>p.locator('#revision-dialog').evaluate(el=>el.open));await p.locator('.revision-row').first().locator('button').filter({hasText:'恢复操作前'}).click();await eventually(()=>p.locator('.reader-confirm').isVisible(),'capture-scope confirmation visible');assert.match(await p.locator('.reader-confirm').textContent(),/今天的新版本/);await p.locator('.reader-confirm .primary').click();await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText===expected,'restoring creates a new working revision');assert.ok((await rpc(p,'GET_INPUT',{id})).revision>before.revision+2);assert.equal((await h.state()).records.find(x=>x.id===before.originalTextReference).originalText,original);
  await field.evaluate(el=>{el.focus();el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.textContent='UXR2_LOCAL_CONFLICT 需要保留的本地草稿。';});const current=await rpc(p,'GET_INPUT',{id});await rpc(p,'EDIT_DOCUMENT',{edit:{documentId:before.documentId,operationId:crypto.randomUUID(),blocks:[{id,expectedRevision:current.revision,libraryText:'UXR2_REMOTE_CONFLICT 另一页面保存的版本。',note:current.note,excluded:false}]}});await field.evaluate(el=>el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await eventually(()=>p.locator('#reload-document').isVisible(),'concurrent change offers a comparison');assert.match(await field.innerText(),/UXR2_LOCAL_CONFLICT/);await p.locator('#reload-document').click();await eventually(()=>p.locator('.reader-confirm').isVisible());assert.match(await p.locator('.reader-confirm').textContent(),/UXR2_LOCAL_CONFLICT/);assert.match(await p.locator('.reader-confirm').textContent(),/UXR2_REMOTE_CONFLICT/);await p.locator('.reader-confirm .primary').click();await p.locator('#retry').click();await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).libraryText.includes('UXR2_LOCAL_CONFLICT'),'explicit comparison and CAS retry preserve the chosen draft');
  await p.setViewportSize({width:390,height:844});await navigate(p,{view:'library'});await p.locator('#core-loop-continue').click();await input(p).waitFor();assert.equal(await input(p).getAttribute('contenteditable'),'false');await p.locator('.reader-mobile-edit').first().click();assert.equal(await input(p).getAttribute('contenteditable'),'plaintext-only');await input(p).fill('UXR2_MOBILE 手机编辑完整保留。');await p.locator('.reader-mobile-edit').first().click();await eventually(async()=>await input(p).getAttribute('contenteditable')==='false','Done waits for the durable save');await p.locator('#back').click();await eventually(()=>p.locator('#core-loop-home').isVisible());assert.equal((await rpc(p,'GET_INPUT',{id})).libraryText,'UXR2_MOBILE 手机编辑完整保留。');offline(h);
 }finally{await h.close();}
});

test('UX-R2 live capture scope, remove/undo/recapture, opt-in exclusions and purge remain authoritative',{timeout:150000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  const p=await ready(h),chat={id:'uxr2-policy',title:'合成私人内容',base:1609459200,messages:[{id:'uxr2-policy-one',text:'UXR2_PRIVATE 这条不希望主动重现的合成内容。'},{id:'uxr2-policy-two',text:'UXR2_NORMAL 同一对话的另一条材料。'}]},sourcePage=await h.open(chat);await eventually(async()=>(await h.state()).records.length===2);await p.bringToFront();await p.locator('#core-loop-continue').click();await input(p).waitFor();const id=await input(p).getAttribute('data-edit-id'),b=await rpc(p,'GET_INPUT',{id});
  await menu(p,'会话收录设置');await eventually(()=>p.locator('.reader-confirm').isVisible());await p.locator('.reader-confirm .primary').click();await eventually(async()=>(await rpc(p,'PAIA_READER_POLICY')).capture.excludedChats.includes('chatgpt:'+chat.id),'capture exclusion persisted');await h.send(sourcePage,{id:'uxr2-blocked',text:'UXR2_BLOCKED This should never be captured.'});await pause(1200);assert.equal((await h.state()).records.length,2);await h.restartWorker();await h.send(sourcePage,{id:'uxr2-blocked-restart',text:'UXR2_BLOCKED_RESTART'});await pause(1200);assert.equal((await h.state()).records.length,2);
  await h.open({id:'uxr2-other-policy',title:'未排除的对话',base:1700000000,messages:[{id:'uxr2-other-one',text:'UXR2_ALLOWED Other conversation capture still works.'}]});await eventually(async()=>(await h.state()).records.length===3);await p.bringToFront();
  await p.locator('.input-remove').first().click();await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).excluded,'Input removal persisted');await p.locator('#notice button').filter({hasText:'撤销'}).click();await eventually(async()=>!(await rpc(p,'GET_INPUT',{id})).excluded,'Input removal undo persisted');await p.locator('.input-remove').first().click();await eventually(async()=>(await rpc(p,'GET_INPUT',{id})).excluded);await h.render(sourcePage,chat);await pause(900);assert.equal((await rpc(p,'GET_INPUT',{id})).excluded,true,'capture never cancels removal');
  await navigate(p,{view:'revisit'});await p.locator('#revisit-old-toggle').check();await eventually(async()=>(await rpc(p,'PAIA_READER_POLICY')).revisit.oldContent,'old-content revisit opt-in persisted');await p.locator('#revisit-refresh').click();await eventually(()=>p.locator('.revisit-card').filter({hasText:'UXR2_NORMAL'}).isVisible(),'eligible revisit card visible');const card=p.locator('.revisit-card').filter({hasText:'UXR2_NORMAL'});await card.locator('summary').click();await card.getByRole('button',{name:'不主动回顾这个对话',exact:true}).click();await eventually(async()=>!(await p.locator('.revisit-card').filter({hasText:'UXR2_NORMAL'}).count()),'conversation revisit exclusion applied');assert.equal((await rpc(p,'SEARCH_INPUTS',{options:{query:'UXR2_NORMAL'}})).items.length,1,'Revisit exclusion leaves explicit search usable');
  await p.locator('.revisit-close').click();await eventually(()=>p.locator('#collection-panel').isVisible(),'collection panel restored');await navigate(p,{view:'library',documentId:b.documentId});await menu(p,'查看当时记录');await eventually(()=>p.locator('#info-dialog').evaluate(el=>el.open));await p.locator('#info-content button').filter({hasText:'永久删除来源'}).click();await eventually(()=>p.locator('.reader-confirm').isVisible());assert.match(await p.locator('.reader-confirm').textContent(),/无法撤销|外部平台/);assert.match(await p.evaluate(()=>document.activeElement.textContent),/取消/);await p.locator('.reader-confirm .danger').click();await eventually(async()=>(await h.state()).records.length===2);await eventually(async()=>!(await p.locator('#info-dialog').evaluate(el=>el.open)),'purge closes the Source dialog after the archive refresh');assert.equal(await p.locator('#info-content').textContent(),'');await shot(p,'reader-empty-after-purge');
  await h.render(sourcePage,chat);await pause(900);assert.equal((await h.state()).records.length,2);await p.locator('.sidebar-bottom [data-view="settings"]').click();await eventually(()=>p.locator('#settings-panel').isVisible(),'Settings visible after purge');await p.locator('[data-settings-group="reading"]').click();await eventually(()=>p.locator('#reader-capture-list button').isVisible(),'capture exclusion listed after purge');await p.locator('#reader-capture-list button').click();await eventually(()=>p.locator('.reader-confirm').isVisible());await p.locator('.reader-confirm .primary').click();await eventually(async()=>(await rpc(p,'PAIA_READER_POLICY')).capture.excludedChats.length===0,'capture exclusion remains explicitly reversible after Source purge');offline(h);
 }finally{await h.close();}
});

test('UX-R2 topic exclusion removes related Input previews; Revisit visual matrix and keyboard remain usable',{timeout:120000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  const p=await ready(h),chat={id:'uxr2-topic',title:'主题回顾材料',base:1609459200,messages:[{id:'uxr2-topic-one',text:'UXR2_TOPIC_PRIVATE 合成主题原话，不应绕过回顾排除。'}]};await h.open(chat);await eventually(async()=>(await h.state()).records.length===1);
  const topic=await p.evaluate(async()=>{
   const {OrganizerStore}=await import('../core/organizer/store.js'),s=new OrganizerStore(chrome.storage.local);await s.status();const b=(await s.page({view:'library',limit:1})).recentCapturedDocument,page=await s.page({view:'library',documentId:b.id}),input=page.library.blocks[0];
   const evidence=await s.evidenceFor([{inputId:input.id,role:'primary',selectedFields:['body']}]);const e=await s.createEntry({operationId:crypto.randomUUID(),actor:'ai',body:'UXR2_TOPIC_DERIVED 合成派生材料',type:'judgment',formation:'explicit',evidence,generator:{providerId:'fixture',providerVersion:'1',modelVersion:'deterministic-1',taskSchemaVersion:1,promptTemplateVersion:1,policyVersion:1}}),topic=await s.createTopic({operationId:crypto.randomUUID(),name:'UXR2_TOPIC_PRIVATE_THEME'});
   await s.placeEntry({entryId:e.id,topicId:topic.id,expectedEntryRevision:(await s.entry(e.id)).revision,expectedTopicRevision:(await s.topic(topic.id)).organizationRevision,operationId:crypto.randomUUID()});await s.repository.close();return {id:topic.id,inputId:input.id};
  });
  await p.bringToFront();await navigate(p,{view:'revisit'});assert.equal(await p.locator('#revisit-old-toggle').isChecked(),false);await p.locator('.revisit-close').click();await navigate(p,{view:'revisit'});await p.locator('#revisit-old-toggle').check();await eventually(()=>p.locator('.revisit-card').filter({hasText:'UXR2_TOPIC_PRIVATE 合成主题原话'}).isVisible(),'explicit opt-in reveals eligible old Input');
  const topicCard=p.locator(`.revisit-card[data-topic-id="${topic.id}"]`);await eventually(()=>topicCard.isVisible(),'real pending topic material reaches Revisit');await topicCard.locator('summary').click();await topicCard.getByRole('button',{name:'不主动回顾这个主题',exact:true}).click();await eventually(async()=>await p.locator('.revisit-card').count()===0,'topic exclusion removes both topic and related Input previews');assert.equal((await rpc(p,'SEARCH_INPUTS',{options:{query:'UXR2_TOPIC_PRIVATE'}})).items.length,1);
  for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]]){await p.setViewportSize({width,height});for(const appearance of ['light','dark']){await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance}});await eventually(async()=>await p.evaluate(()=>document.documentElement.dataset.paiaTheme)===appearance);await shot(p,`revisit-quiet-${width}x${height}-${appearance}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=2);}}
  await p.locator('#revisit-old-toggle').focus();assert.equal(await p.evaluate(()=>document.activeElement.id),'revisit-old-toggle');await p.keyboard.press('Space');await eventually(async()=>(await rpc(p,'PAIA_READER_POLICY')).revisit.oldContent===false);offline(h);
 }finally{await h.close();}
});

test('UX-R2 F-LARGE real IndexedDB: 100k Inputs, 1000 documents, 300 topics and 5000 entries keep Reader/Revisit bounded',{timeout:300000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true});try{
  await ready(h);const report=await h.archive.evaluate(async()=>{
   const {OrganizerStore}=await import('../core/organizer/store.js'),{recordIndex,blockIndex,sourceCount}=await import('../core/idb-repository.js'),{ReaderStateService}=await import('../core/reader-state.js'),{RevisitService}=await import('../core/revisit.js');
   const values={},local={async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}},s=new OrganizerStore(local,{name:'ux-r2-synthetic-large'});await s.consent(true);await s.capture({epoch:(await s.status()).epoch,adapterVersion:'0.3.0',chat:{id:'large-template',url:'https://chatgpt.com/c/large-template',title:'Synthetic large template'},messages:[{sourceMessageId:'large-template-one',pageOrder:1,originalText:'Synthetic template'}]});const template=await s.snapshot(),r0=template.records[0],b0=template.library.blocks[0],d0=template.conversations[0];
   await s.repository.transaction(true,async t=>{for(const name of ['records','recordIndex','blocks','blockIndex','documents','libraryDocuments','sourceCounts'])await t.clear(name);});const began=performance.now();let pulses=0;const timer=setInterval(()=>pulses++,20);
   for(let start=0;start<100000;start+=500)await s.repository.transaction(true,async t=>{const writes=[];for(let i=start;i<start+500;i++){
    const group=Math.floor(i/100),chatId='large-chat-'+group,docId='document:large-'+group,id='large-record-'+String(i).padStart(8,'0'),sourceKey=i.toString(16).padStart(64,'0'),r={...r0,id,chatId,chatUrl:'https://chatgpt.com/c/'+chatId,chatTitle:'Synthetic source '+group,sourceMessageId:'large-message-'+i,sourceKey,dedupeKey:sourceKey,originalText:i===50110?'长文👩‍💻\n'+'中'.repeat(50000):'Synthetic 中文 input '+i+' '+('text '.repeat(30)),sourceSentAt:new Date(1609459200000+i*1000).toISOString(),timeSource:'chatgpt_response_create_time',timeConfidence:'high',pageOrder:i%100+1,conversationOrder:i%100+1};
    const b={...b0,id:'block:'+id,documentId:docId,sourceRecordId:id,originalTextReference:id,provenance:[{sourceRecordId:id}],provenanceSignature:JSON.stringify([{sourceRecordId:id}])};writes.push(t.put('records',{id,value:r}),t.put('recordIndex',recordIndex(r,i)),t.put('blocks',{id:b.id,value:b}),t.put('blockIndex',blockIndex(b,i,[r])),t.put('sourceCounts',sourceCount(docId,sourceKey,[r],[b],chatId)));
    if(i%100===0){const doc={...d0,id:docId,sourceConversationId:chatId,originalConversationTitle:r.chatTitle,firstSourceSentAt:r.sourceSentAt,lastSourceSentAt:r.sourceSentAt};delete doc.sourceRecordIds;const key=[-Date.parse(r.sourceSentAt),docId];writes.push(t.put('documents',{id:docId,sequence:group,chatKey:'chatgpt:'+chatId,displayKey:key,libraryDisplay:key,archiveDisplay:key,value:doc}),t.put('libraryDocuments',{id:docId,value:doc}));}
   }await Promise.all(writes);});await s.repository.transaction(true,t=>t.put('meta',{id:'sequence',records:100000,blocks:100000,documents:1000}));
   const first=await s.createTopic({name:'Synthetic 5000 entry topic',operationId:crypto.randomUUID()}),entry=await s.createEntry({actor:'user',formation:'explicit',body:'Synthetic standalone entry',type:'idea',evidence:[],operationId:crypto.randomUUID()}),topic0=await s.repository.transaction(false,t=>t.get('topics',first.id)),entry0=await s.repository.transaction(false,t=>t.get('thoughts',entry.id));
   for(let start=0;start<5000;start+=500)await s.repository.transaction(true,async t=>{const writes=[];for(let i=start;i<start+500;i++){const id=i? 'large-entry-'+i:entry.id;writes.push(t.put('thoughts',{...entry0,id}),t.put('placements',{id:JSON.stringify([first.id,1,id]),topicId:first.id,layoutGeneration:1,entryId:id,sectionId:topic0.defaultSectionId,sectionRank:'499999999999',rank:String(100000+i).padStart(12,'0'),revision:0,activeKey:0,lifecycle:'active'}));if(i>0&&i<300)writes.push(t.put('topics',{...topic0,id:'large-topic-'+i,name:'Synthetic topic '+i,nameKey:'synthetic topic '+i}));}await Promise.all(writes);});clearInterval(timer);
   const metric=async fn=>{s.repository.metrics={reads:0,writes:0,scans:0};const at=performance.now(),data=await fn();return {ms:performance.now()-at,...s.repository.metrics,data};},reader=new ReaderStateService(s),revisit=new RevisitService(s),docId='document:large-501',inputId='block:large-record-00050110';
   const page=await metric(()=>s.page({view:'library',documentId:docId,contextInputId:inputId,limit:100}));await reader.save({documentId:docId,inputId,revision:0,offset:41000,sort:'asc',expanded:[inputId]});const resume=await metric(()=>reader.resolve(docId));await revisit.status();await s.repository.transaction(true,async t=>{const row=await t.get('meta','revisit:v2');row.boundary=99600;await t.put('meta',row);});const visit=await metric(()=>revisit.status()),counts=await s.repository.transaction(false,async t=>({inputs:await t.count('blocks'),documents:await t.count('documents'),topics:await t.count('topics'),entries:await t.count('thoughts')}));
   const compact=x=>({ms:x.ms,reads:x.reads,writes:x.writes,scans:x.scans});await s.repository.close();return {counts,seedMs:performance.now()-began,pulses,page:{...compact(page),blocks:page.data.library.blocks.length,bodies:page.data.records.length},resume:{...compact(resume),inputId:resume.data.inputId,offset:resume.data.offset},revisit:{...compact(visit),fresh:visit.data.newInputs.count,cards:visit.data.newInputs.items.length},localHasBody:JSON.stringify(values).includes('Synthetic 中文 input')};
  });
  await mkdir('work/ux-r2',{recursive:true});await writeFile('work/ux-r2/large-fixture.json',JSON.stringify(report,null,2));assert.deepEqual(report.counts,{inputs:100000,documents:1000,topics:300,entries:5000});assert.ok(report.page.blocks<=100);assert.ok(report.page.bodies<=100);assert.ok(report.page.reads<600);assert.ok(report.resume.reads<10);assert.equal(report.resume.offset,41000);assert.ok(report.revisit.reads<6000);assert.ok(report.revisit.cards<=5);assert.ok(report.page.ms<3000);assert.ok(report.resume.ms<1000);assert.ok(report.pulses>0);assert.equal(report.localHasBody,false);await mkdir('work/ux-r2',{recursive:true});await writeFile('work/ux-r2/large-fixture.json',JSON.stringify(report,null,2));offline(h);
 }finally{await h.close();}
});
