import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';

const dir='work/ux-r5',op=()=>crypto.randomUUID();
const original='R5 恢复验收原话：当前材料与人工理解不能被候选悄悄覆盖。';
const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
const requestOf=body=>JSON.parse(body.messages[1].content);
const output=(r,n)=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({topicId:r.topicCandidates[0].id,blockSummary:`R5 恢复摘要 ${n}`,currentView:`R5 恢复理解 ${n}`,keyInformation:[],preferences:[],decisions:[],judgments:[],openQuestions:[],possibleEvolution:[],evidenceEntryIds:r.inputs.map(x=>x.ref)})}}]});
async function ready(h){const p=h.archive;await p.locator('#enable-consent').click();await eventually(async()=>(await rpc(p,'GET_STATUS')).consented);if(await p.locator('#onboarding-skip').isVisible())await p.locator('#onboarding-skip').click();await rpc(p,'UPDATE_PREFERENCES',{changes:{language:'zh-CN',appearance:'light'}});await rpc(p,'PAIA_MEMORY_SETTINGS',{options:{externalAccess:true,localOnly:false}});await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-r5-certification-key'}});await mkdir(dir,{recursive:true});return p;}
async function makeTopic(p,name){const t=await rpc(p,'CREATE_LIBRARY_TOPIC',{topic:{name,operationId:op()}});await rpc(p,'CONTINUE_THINKING',{thought:{operationId:op(),body:original,topicId:t.id}});return t;}
async function openTopic(p,t){const panel=p.locator('#thought-panel'),documentView=p.locator('#thought-document'),list=p.locator('#thought-list'),heading=p.locator('#topic-heading h1').filter({hasText:t.name}),nav=p.locator('[data-view="thoughts"]').first();if(await nav.getAttribute('aria-current')!=='page')await nav.click();await panel.waitFor({state:'visible'});await eventually(async()=>await heading.isVisible()||await documentView.isVisible()||await list.isVisible(),'Thought navigation settles before selecting a Topic');if(await heading.isVisible())return;if(await documentView.isVisible()){await p.locator('#back').click();await list.waitFor({state:'visible'});}const target=p.locator(`[data-topic-id="${t.id}"]`);await target.waitFor({state:'visible'});await target.click();await heading.waitFor();}
async function organized(p){const toggle=p.locator('#ai-presentation-toggle');await eventually(()=>toggle.isEnabled());if(!await toggle.isChecked())await toggle.check();}
async function generate(p){await p.getByRole('button',{name:'生成 AI整理',exact:true}).click();const d=p.locator('#library-dialog[open]');await d.waitFor();await d.locator('select[name="approval"]').selectOption('confirm');await d.locator('button[type="submit"]').click();}
async function state(p,id){const s=await rpc(p,'GET_AI_PRESENTATION_STATUS');return {...s,selected:s.topics.find(t=>t.topicId===id)};}
async function screenshot(p,name){await p.screenshot({path:`${dir}/${name}.png`,fullPage:true});}
async function matrix(p,selector,name){
 const evidence=[];
 for(const [width,height]of [[1440,900],[1024,768],[390,844],[320,720]])for(const theme of ['light','dark']){
  await p.setViewportSize({width,height});await rpc(p,'UPDATE_PREFERENCES',{changes:{appearance:theme}});await eventually(async()=>await p.evaluate(()=>document.documentElement.dataset.paiaTheme)===theme);
  const panel=p.locator(selector);await panel.waitFor();await panel.scrollIntoViewIfNeeded();
  const measure=await panel.evaluate(root=>{
   const rgb=s=>(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number),lum=c=>c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);
   const contrast=node=>{let parent=node,bg;while(parent){const value=getComputedStyle(parent).backgroundColor;if(value!=='rgba(0, 0, 0, 0)'&&value!=='transparent'){bg=rgb(value);break;}parent=parent.parentElement;}const fg=rgb(getComputedStyle(node).color),a=lum(fg),b=lum(bg||[255,255,255]);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);};
   return {overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,contrast:Math.min(...[...root.querySelectorAll('p,h2,h3,strong')].filter(n=>n.getClientRects().length).map(contrast)),buttons:[...root.querySelectorAll('button')].map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height}))};
  });
  assert.ok(measure.overflow<=2,`${name} ${width} ${theme}: overflow ${measure.overflow}`);assert.ok(measure.contrast>=4.5,`${name} ${width} ${theme}: text contrast ${measure.contrast}`);
  if(width<800)assert.ok(measure.buttons.every(b=>b.width>=44&&b.height>=44),`${name}: mobile controls retain 44px targets`);
  evidence.push({width,height,theme,...measure});await screenshot(p,`recovery-${name}-${width}x${height}-${theme}`);
 }
 await writeFile(`${dir}/recovery-${name}-measurements.json`,JSON.stringify(evidence,null,2));
}

test('UX-R5 recovery certifies readable themes, responsive comparison, IME, keyboard staging and stale CAS without hidden requests',{timeout:240000},async()=>{
 let calls=0;const h=await FakeChatGPT.start({onboarding:true,deepSeekFixture:async body=>output(requestOf(body),++calls)});
 try{
  const p=await ready(h),topic=await makeTopic(p,'R5 恢复验收');await openTopic(p,topic);await organized(p);await p.locator('[data-ai-first-generation]').waitFor();
  await matrix(p,'[data-ai-first-generation]','first-generation');assert.equal(calls,0,'all eight first-generation views are local');
  await p.setViewportSize({width:1440,height:900});await generate(p);await eventually(async()=>(await state(p,topic.id)).runtime?.state==='committed','real worker commits the first generation');await p.locator('[data-ai-field="currentView"]').waitFor();await eventually(async()=>(await p.locator('#ai-update-feedback').textContent()).trim()==='','a committed success must not be shown as a runtime error');assert.equal((await state(p,topic.id)).runtime.errorCode,null);assert.equal(calls,1);
  const field=p.locator('[data-ai-field="currentView"]'),human='人工输入法尚在组合的理解：必须保留。',toggle=p.locator('#ai-presentation-toggle');
  await field.focus();await field.dispatchEvent('compositionstart',{data:''});await field.fill(human);await field.dispatchEvent('input',{inputType:'insertCompositionText',data:human,isComposing:true});await toggle.focus();await p.keyboard.press('Space');await eventually(async()=>await toggle.isEnabled()&&await toggle.isChecked(),'IME blocks leaving the current draft');await pause(700);assert.equal(await field.textContent(),human);assert.notEqual((await state(p,topic.id)).selected.presentation.currentView,human);await screenshot(p,'recovery-ime-unsaved');
  await field.dispatchEvent('compositionend',{data:human});await field.press('Tab');await eventually(async()=>(await state(p,topic.id)).selected.presentation.currentView===human,'composition end saves through the real service');
  await p.emulateMedia({reducedMotion:'reduce'});await toggle.focus();await p.keyboard.press('Space');await eventually(async()=>!await toggle.isChecked());await p.getByLabel('内容正文').filter({hasText:original}).first().waitFor();assert.equal(await p.evaluate(()=>document.activeElement?.id),'ai-presentation-toggle');assert.equal(await p.evaluate(()=>document.documentElement.classList.contains('paia-recomposing')),false);await p.keyboard.press('Space');await field.waitFor();assert.equal(calls,1,'cached reduced-motion switching is local');
  await rpc(p,'CONTINUE_THINKING',{thought:{operationId:op(),body:'R5 恢复验收新增材料：形成新候选，而不代替人工理解。',topicId:topic.id}});await openTopic(p,topic);await organized(p);await p.locator('#ai-library-update').click();await p.locator('[data-ai-candidate]').waitFor();const before=(await state(p,topic.id)).selected.presentation;assert.equal(before.currentView,human);assert.equal(calls,2);
  await matrix(p,'[data-ai-candidate]','candidate');assert.equal(calls,2,'theme and viewport changes never regenerate a candidate');
  await p.setViewportSize({width:1024,height:768});const adopt=p.locator('[data-ai-candidate-field="blockSummary"] [data-candidate-decision="adopt"]'),keep=p.locator('[data-ai-candidate-field="currentView"] [data-candidate-decision="keep"]');
  await adopt.focus();await p.keyboard.press('Space');await eventually(async()=>await adopt.getAttribute('aria-pressed')==='true');assert.equal(await adopt.evaluate(n=>n===document.activeElement),true,'candidate rebuilding must restore the same keyboard control');await keep.focus();await p.keyboard.press('Space');await eventually(async()=>await keep.getAttribute('aria-pressed')==='true');assert.equal(await keep.evaluate(n=>n===document.activeElement),true);assert.equal((await state(p,topic.id)).selected.presentation.revision,before.revision,'staging is not persistence');await screenshot(p,'recovery-candidate-selected');
  await p.evaluate(()=>document.documentElement.style.setProperty('--paia-prose-size','34px'));assert.equal(await field.evaluate(n=>getComputedStyle(n).fontSize),'34px');await screenshot(p,'recovery-candidate-200pct-prose');await p.evaluate(()=>document.documentElement.style.setProperty('--paia-prose-size','17px'));
  const cdp=await p.context().newCDPSession(p);try{await p.setViewportSize({width:640,height:900});await cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:2});assert.equal(await p.evaluate(()=>visualViewport.scale),2);await keep.scrollIntoViewIfNeeded();await screenshot(p,'recovery-candidate-200pct-page-scale');}finally{await cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:1});await cdp.detach();}
  await p.reload();await openTopic(p,topic);await organized(p);await p.locator('[data-ai-candidate]').waitFor();assert.equal((await state(p,topic.id)).selected.presentation.revision,before.revision,'closing without saving cannot apply local choices');assert.equal(await adopt.getAttribute('aria-pressed'),'false');assert.equal(calls,2);
  const latest=(await state(p,topic.id)).selected.presentation;await rpc(p,'EDIT_AI_PRESENTATION',{edit:{topicId:topic.id,field:'currentView',value:'另一窗口保存的人工理解',expectedRevision:latest.revision,operationId:op()}});await p.reload();await openTopic(p,topic);await organized(p);await p.locator('[data-ai-candidate]').waitFor();const stale=(await state(p,topic.id)).selected;assert.equal(stale.candidate.stale,true);assert.equal(stale.presentation.currentView,'另一窗口保存的人工理解');assert.equal(await p.getByRole('button',{name:'保存这些选择',exact:true}).count(),0);await p.getByRole('button',{name:'重新更新 AI整理',exact:true}).waitFor();await screenshot(p,'recovery-candidate-stale');assert.equal(calls,2);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);
 }finally{await h.close();}
});

test('UX-R5 recovery keeps Original readable after a provider failure and never retries on status reads',{timeout:90000},async()=>{
 const h=await FakeChatGPT.start({onboarding:true,deepSeekFixture:async()=>({choices:[{message:{content:'not valid provider JSON'}}]})});
 try{const p=await ready(h),topic=await makeTopic(p,'R5 失败仍可阅读');await openTopic(p,topic);await organized(p);await generate(p);await eventually(async()=>(await state(p,topic.id)).runtime?.state==='failed','provider failure is durable');await eventually(async()=>(await p.locator('#ai-update-feedback').textContent()).trim().length>0,'failure feedback is visible');assert.equal((await state(p,topic.id)).selected.presentation,null);assert.equal(await p.getByLabel('内容正文').filter({hasText:original}).first().isVisible(),true);await screenshot(p,'recovery-provider-failed');for(let i=0;i<3;i++)await state(p,topic.id);assert.equal(h.deepSeekRequests.length,1);assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);}finally{await h.close();}
});

test('UX-R5 recovery reads actual interrupted-worker outcome_unknown without automatic paid retry',{timeout:120000},async()=>{
 let release;const gate=new Promise(resolve=>{release=resolve;});const h=await FakeChatGPT.start({onboarding:true,deepSeekFixture:async body=>{await gate;return output(requestOf(body),1);}});
 try{const p=await ready(h),topic=await makeTopic(p,'R5 中断结果未知');await openTopic(p,topic);await organized(p);await generate(p);await eventually(()=>Promise.resolve(h.deepSeekRequests.length===1),'one dispatched request');assert.equal(await p.getByLabel('内容正文').filter({hasText:original}).first().isVisible(),true);await h.restartWorker();await eventually(async()=>(await state(p,topic.id)).runtime?.state==='outcome_unknown','fresh worker reconciles the durable sent row');for(let i=0;i<3;i++){const s=await state(p,topic.id);assert.equal(s.runtime.errorCode,'OUTCOME_UNKNOWN');assert.equal(s.selected.presentation,null);}assert.equal(h.deepSeekRequests.length,1);await p.reload();await openTopic(p,topic);await organized(p);await p.locator('[data-ai-first-generation]').waitFor();assert.equal((await state(p,topic.id)).runtime.state,'outcome_unknown');await screenshot(p,'recovery-outcome-unknown');assert.equal(h.deepSeekRequests.length,1,'reopen and status reads never repeat a paid request');assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);}finally{release?.();await h.close();}
});
