import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,rows} from './harness/original-complete.mjs';
import {migrateBindings,BINDING_ROW} from '../core/thought-binding.js';
import {keyedHash} from '../core/thought-model.js';
const op=()=>crypto.randomUUID();
async function setup(){const f=await completeFixture({texts:['旧时的完整原话 👩🏽‍💻 与 é，保留每个字符。']});const b=(await rows(f.s,'blocks'))[0].value;const topics=await Promise.all(['问题一','问题二'].map(name=>f.s.createTopic({name,operationId:op()})));const selection={operationId:op(),kind:'input',id:b.id,expectedRevision:b.revision,topicIds:topics.map(t=>t.id)};const added=await f.s.addToTopics(selection);return {...f,b,topics,id:added.id,selection};}
async function edit(s,id,body){const e=await s.entry(id);return s.editLibraryFields({id,operationId:op(),expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,expectedInputRevision:e.currentInputRevision,changes:{body}});}
async function inputEdit(s,b,body){const live=await s.input(b.id);return s.editDocument({operationId:op(),documentId:b.documentId,blocks:[{id:b.id,expectedRevision:live.revision,libraryText:body,note:live.note,excluded:false}]});}
test('UX-R3 default detach retains one Thought across placements and all canonical reads; Source/Input remain unchanged',async()=>{const f=await setup();assert.equal((await f.s.entry(f.id)).bodyBinding,'input');assert.equal((await f.s.entryPaths(f.id)).length,2);assert.equal((await f.s.addToTopics(f.selection)).id,f.id);assert.equal((await rows(f.s,'thoughts')).length,1);await edit(f.s,f.id,'今天人工改写的思想');assert.equal((await f.s.input(f.b.id)).libraryText,null);assert.equal((await f.s.entry(f.id)).bodyBinding,'thought');await inputEdit(f.s,f.b,'档案后来更新');await f.s.drainInvalidations();assert.equal((await f.s.entry(f.id)).body,'今天人工改写的思想');for(const t of f.topics)assert.equal((await f.s.topicDocumentPage({topicId:t.id,sort:'asc'})).items[0].entry.body,'今天人工改写的思想');assert.equal((await f.s.readingEntry(f.id)).archiveChanged,true);await f.s.drainLibraryMaintenance();assert.equal((await f.s.searchLibrary({query:'人工改写'})).items[0].entryId,f.id);assert.equal((await rows(f.s,'records'))[0].value.originalText,'旧时的完整原话 👩🏽‍💻 与 é，保留每个字符。');});
test('UX-R3 explicit selection cannot substitute a differing manual Thought; selected span respects Unicode boundaries',async()=>{const f=await setup();await edit(f.s,f.id,'不同的人工正文');const added=await f.s.addToTopics({...f.selection,operationId:op()});assert.notEqual(added.id,f.id);assert.equal((await f.s.entry(added.id)).bodyBinding,'input');await assert.rejects(f.s.addToTopics({...f.selection,operationId:op(),span:{start:10,end:11}}));});
test('UX-R3 advanced reverse edit is default off and valid only for whole current bindings with two CAS checks',async()=>{const f=await setup();assert.equal((await f.s.reverseEditSetting()).enabled,false);const e=await f.s.entry(f.id);assert.equal((await f.s.editLibraryFields({id:f.id,operationId:op(),expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,changes:{body:'不可绕过'}})).conflict,true);await f.s.reverseEditSetting(true);await edit(f.s,f.id,'明确同步完整正文');assert.equal((await f.s.input(f.b.id)).libraryText,'明确同步完整正文');const stale=await f.s.entry(f.id);await inputEdit(f.s,f.b,'另一标签的档案改动');assert.equal((await f.s.editLibraryFields({id:f.id,operationId:op(),expectedRevision:stale.revision,expectedFieldRevisions:stale.fieldRevisions,expectedInputRevision:stale.currentInputRevision,changes:{body:'不应写入'}})).conflict,true);assert.equal((await f.s.input(f.b.id)).libraryText,'另一标签的档案改动');});
test('UX-R3 restoring the current Input is explicit, versioned and does not replay past Thought edits',async()=>{const f=await setup();await edit(f.s,f.id,'人工思想');await f.s.reverseEditSetting(true);await edit(f.s,f.id,'仍只属于思想');assert.equal((await f.s.input(f.b.id)).libraryText,null);const c=await f.s.compareThought(f.id);await f.s.restoreThoughtInput({id:f.id,operationId:op(),expectedRevision:c.entry.revision,expectedInputRevision:c.input.revision});assert.equal((await f.s.entry(f.id)).bodyBinding,'input');assert.equal((await f.s.entry(f.id)).body,c.input.body);assert.ok((await f.s.revisions({kind:'library_entry',entityId:f.id})).items.some(r=>r.reason==='restore_binding'&&r.before.body==='仍只属于思想'));});
test('UX-R3 legacy migration is metadata-only and resumable; ambiguous link is protected',async()=>{const f=await setup();await f.s.foundationWrite(async t=>{const row=await t.get('thoughts',f.id);delete row.bodyBinding;delete row.bindingRevision;delete row.bindingLength;row.thoughtText='歧义旧版人工内容';await t.put('thoughts',row);await t.delete('meta',BINDING_ROW);});const before=(await rows(f.s,'thoughts'))[0];await migrateBindings(f.s,{limit:1,maxBatches:1});await migrateBindings(f.s);const after=(await rows(f.s,'thoughts'))[0];assert.equal(after.thoughtText,before.thoughtText);assert.equal(after.revision,before.revision);assert.equal(after.bodyBinding,'thought');assert.equal(after.workingInputId,undefined);await inputEdit(f.s,f.b,'档案再次变化');assert.equal((await f.s.entry(f.id)).body,before.thoughtText);});
test('UX-R3 new thought is independently authored today and survives source purge while referenced rewrites do not',async()=>{const f=await setup();await edit(f.s,f.id,'仅改写来源引用');const fresh=await f.s.continueThinking({body:'今天独立补充的新想法',inputId:f.b.id,operationId:op()});assert.equal((await f.s.entry(fresh.id)).provenanceType,'user_created');assert.equal((await f.s.entryProvenance(fresh.id))[0].role,'context_only');await f.s.permanentDelete(f.b.originalTextReference);assert.equal((await f.s.entry(f.id)).body,'');assert.equal((await f.s.entry(fresh.id)).body,'今天独立补充的新想法');await f.s.drainPurgeCleanup();await f.s.drainInvalidations();assert.equal((await f.s.entry(fresh.id)).body,'今天独立补充的新想法');assert.equal((await f.s.entry(f.id)).body,'');});
test('UX-R3 Undo detach restores binding; reverse Undo checks both versions and requires one-time confirmation after setting off',async()=>{const f=await setup();let e=await f.s.entry(f.id);let saved=await f.s.editLibraryBatch({operationId:op(),entries:[{id:e.id,expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,expectedInputRevision:e.currentInputRevision,changes:{body:'独立编辑'}}]});e=await f.s.entry(e.id);let undo={operationId:op(),items:[{id:e.id,revisionId:saved.items[0].revisionId,side:'before',expectedRevision:e.revision,expectedInputRevision:e.currentInputRevision}]};assert.equal((await f.s.thoughtEditHistory(undo)).items.length,1);assert.equal((await f.s.entry(e.id)).bodyBinding,'input');await f.s.reverseEditSetting(true);e=await f.s.entry(e.id);saved=await f.s.editLibraryBatch({operationId:op(),entries:[{id:e.id,expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,expectedInputRevision:e.currentInputRevision,changes:{body:'双向修改'}}]});await f.s.reverseEditSetting(false);e=await f.s.entry(e.id);undo={operationId:op(),items:[{id:e.id,revisionId:saved.items[0].revisionId,side:'before',expectedRevision:e.revision,expectedInputRevision:e.currentInputRevision}]};assert.equal((await f.s.thoughtEditHistory(undo)).requiresArchiveConfirmation,true);assert.equal((await f.s.input(f.b.id)).libraryText,'双向修改');assert.equal((await f.s.thoughtEditHistory({...undo,confirmArchive:true})).items.length,1);assert.equal((await f.s.reverseEditSetting()).enabled,false);assert.equal((await f.s.input(f.b.id)).libraryText,'旧时的完整原话 👩🏽‍💻 与 é，保留每个字符。');});
test('UX-R3 partial excerpt never restores or reverse edits a complete Input even with the setting on',async()=>{const f=await setup();const partial=await f.s.addToTopics({...f.selection,operationId:op(),span:{start:0,end:4}});await f.s.reverseEditSetting(true);assert.equal((await f.s.compareThought(partial.id)).input,null);await edit(f.s,partial.id,'只有选段的改写');assert.equal((await f.s.input(f.b.id)).libraryText,null);assert.equal((await f.s.restoreThoughtInput({id:partial.id,operationId:op(),expectedRevision:(await f.s.entry(partial.id)).revision,expectedInputRevision:0})).conflict,true);});

test('UX-R3 shared body and note Undo/Redo restore the complete edit, require current authority and remain atomic on failure',async()=>{
 const f=await setup();await f.s.reverseEditSetting(true);const before=await f.s.entry(f.id),saved=await f.s.editLibraryBatch({operationId:op(),entries:[{id:f.id,expectedRevision:before.revision,expectedFieldRevisions:before.fieldRevisions,expectedInputRevision:before.currentInputRevision,changes:{body:'Synthetic shared body update',note:'Synthetic companion note'}}]});const revision=(await rows(f.s,'revisions')).find(x=>x.id===saved.items[0].revisionId);assert.deepEqual(revision.fieldMask,['body','note']);assert.equal(revision.reason,'shared_entry_edit');
 await f.s.reverseEditSetting(false);let row=await f.s.entry(f.id);const undo={operationId:op(),items:[{id:f.id,revisionId:revision.id,side:'before',expectedRevision:row.revision,expectedInputRevision:row.currentInputRevision}]};assert.equal((await f.s.thoughtEditHistory(undo)).requiresArchiveConfirmation,true);const transaction=f.s.repository.transaction.bind(f.s.repository);let fail=true;f.s.repository.transaction=(write,fn,stores)=>transaction(write,async t=>{const put=t.put.bind(t);t.put=(name,value)=>{if(fail&&name==='thoughts'&&value.note===''){fail=false;throw Error('SYNTHETIC_UNDO_FAILURE');}return put(name,value);};return fn(t);},stores);
 await assert.rejects(f.s.thoughtEditHistory({...undo,confirmArchive:true}));assert.equal((await f.s.input(f.b.id)).libraryText,'Synthetic shared body update');assert.equal((await f.s.entry(f.id)).note,'Synthetic companion note');await f.s.thoughtEditHistory({...undo,confirmArchive:true});row=await f.s.entry(f.id);assert.equal(row.body,before.body);assert.equal(row.note,before.note);assert.equal(row.bodyBinding,'input');assert.deepEqual(row.protections.body,before.protections.body);
 await f.s.thoughtEditHistory({operationId:op(),confirmArchive:true,items:[{id:f.id,revisionId:revision.id,side:'after',expectedRevision:row.revision,expectedInputRevision:row.currentInputRevision}]});row=await f.s.entry(f.id);assert.equal(row.body,'Synthetic shared body update');assert.equal(row.note,'Synthetic companion note');assert.equal((await f.s.reverseEditSetting()).enabled,false);assert.equal((await rows(f.s,'records'))[0].value.originalText,before.body);
});

test('UX-R3 one batch may edit two live Thoughts for the same Input and Undo/Redo both without stale sibling revisions',async()=>{
 const f=await setup();await edit(f.s,f.id,'Synthetic independent earlier edit');const other=await f.s.addToTopics({...f.selection,operationId:op()}),compare=await f.s.compareThought(f.id);await f.s.restoreThoughtInput({id:f.id,operationId:op(),expectedRevision:compare.entry.revision,expectedInputRevision:compare.input.revision});await f.s.reverseEditSetting(true);const before=await Promise.all([f.id,other.id].map(id=>f.s.entry(id)));
 const saved=await f.s.editLibraryBatch({operationId:op(),entries:before.map((row,i)=>({id:row.id,expectedRevision:row.revision,expectedFieldRevisions:row.fieldRevisions,expectedInputRevision:row.currentInputRevision,changes:{body:'Synthetic matching batch body',...(i?{note:'Synthetic second note'}:{})}}))});assert.ok(saved.items.every(x=>x.shared&&x.revisionId));
 for(const side of ['before','after']){const items=[];for(const item of saved.items){const current=await f.s.entry(item.id);items.push({id:item.id,revisionId:item.revisionId,side,expectedRevision:current.revision,expectedInputRevision:current.currentInputRevision});}assert.equal((await f.s.thoughtEditHistory({operationId:op(),items})).items.length,2);for(const [i,initial]of before.entries()){const current=await f.s.entry(initial.id);assert.equal(current.bodyBinding,'input');assert.equal(current.body,side==='before'?initial.body:'Synthetic matching batch body');assert.equal(current.note,side==='before'?initial.note:i?'Synthetic second note':'');}}
});

test('UX-R3 note-only Undo preserves a live binding after the Input body changes',async()=>{
 const f=await setup(),before=await f.s.entry(f.id),saved=await f.s.editLibraryBatch({operationId:op(),entries:[{id:f.id,expectedRevision:before.revision,expectedFieldRevisions:before.fieldRevisions,changes:{note:'Synthetic note only'}}]});await inputEdit(f.s,f.b,'Synthetic later Input body');const current=await f.s.entry(f.id);await f.s.thoughtEditHistory({operationId:op(),items:[{id:f.id,revisionId:saved.items[0].revisionId,side:'before',expectedRevision:current.revision,expectedInputRevision:current.currentInputRevision}]});const after=await f.s.entry(f.id);assert.equal(after.bodyBinding,'input');assert.equal(after.body,'Synthetic later Input body');assert.equal(after.note,'');assert.equal((await f.s.input(f.b.id)).libraryText,after.body);
});

test('UX-R3 restoring an automatic whole body cannot clear protection or purge a later independent human note',async()=>{
 const f=await completeFixture({texts:['Synthetic automatically organized original']});await f.runner.wake({userActionId:op()});const b=(await rows(f.s,'blocks'))[0].value,initial=await f.s.entry((await rows(f.s,'thoughts'))[0].id);assert.equal(initial.hasHumanAction,false);await f.s.reverseEditSetting(true);
 const saved=await f.s.editLibraryBatch({operationId:op(),entries:[{id:initial.id,expectedRevision:initial.revision,expectedFieldRevisions:initial.fieldRevisions,expectedInputRevision:initial.currentInputRevision,changes:{body:'Synthetic body edit'}}]});let current=await f.s.entry(initial.id);await f.s.editLibraryFields({id:initial.id,expectedRevision:current.revision,expectedFieldRevisions:current.fieldRevisions,operationId:op(),changes:{note:'Synthetic independent human note'}});current=await f.s.entry(initial.id);const protection=structuredClone(current.protections.note);
 await f.s.thoughtEditHistory({operationId:op(),items:[{id:initial.id,revisionId:saved.items[0].revisionId,side:'before',expectedRevision:current.revision,expectedInputRevision:current.currentInputRevision}]});current=await f.s.entry(initial.id);assert.equal(current.body,initial.body);assert.equal(current.note,'Synthetic independent human note');assert.equal(current.hasHumanAction,true);assert.equal(current.userEdited,true);assert.deepEqual(current.protections.note,protection);await f.s.permanentDelete(b.originalTextReference);await f.s.drainPurgeCleanup();assert.equal((await f.s.entry(initial.id)).note,'Synthetic independent human note');assert.equal((await f.s.entry(initial.id)).body,'');
});

async function mixedSharedBatch(){
 const f=await setup();await edit(f.s,f.id,'Synthetic earlier detached work');const other=await f.s.addToTopics({...f.selection,operationId:op()}),compare=await f.s.compareThought(f.id);await f.s.restoreThoughtInput({id:f.id,operationId:op(),expectedRevision:compare.entry.revision,expectedInputRevision:compare.input.revision});await f.s.reverseEditSetting(true);
 const before=await Promise.all([f.id,other.id].map(id=>f.s.entry(id))),entries=before.map((row,i)=>({id:row.id,expectedRevision:row.revision,expectedFieldRevisions:row.fieldRevisions,expectedInputRevision:row.currentInputRevision,changes:i?{note:'Synthetic companion metadata',type:'reflection'}:{body:'Synthetic final shared body'}}));
 return {...f,before,entries};
}
for(const metadataFirst of [false,true])test('UX-R3 mixed shared batch returns final versions and safe signatures with '+(metadataFirst?'metadata first':'body first'),async()=>{
 const f=await mixedSharedBatch(),request={operationId:op(),entries:metadataFirst?[...f.entries].reverse():f.entries},saved=await f.s.editLibraryBatch(request),secret=(await rows(f.s,'meta')).find(x=>x.id==='thought-suppression-key').value;
 assert.deepEqual(await f.s.editLibraryBatch(request),saved);
 for(const item of saved.items){const row=await f.s.entry(item.id);assert.equal(row.body,'Synthetic final shared body');assert.equal(row.bodyBinding,'input');assert.equal(item.revision,row.revision,'returned revision must match the final sibling mirror');assert.deepEqual(item.fieldRevisions,row.fieldRevisions);assert.equal(item.currentInputRevision,row.currentInputRevision);assert.equal(item.bodyBinding,row.bodyBinding);if(row.exactSignature!==undefined)assert.equal(row.exactSignature,await keyedHash(secret,['body',row.type,row.body]),'a stored signature must describe the final body and type');}
 const companion=await f.s.entry(f.before[1].id);assert.equal(companion.note,'Synthetic companion metadata');assert.equal(companion.type,'reflection');assert.equal((await f.s.input(f.b.id)).libraryText,'Synthetic final shared body');assert.equal((await rows(f.s,'records'))[0].value.originalText,f.before[0].body);
});
test('UX-R3 mixed history returns committed versions when companion metadata precedes shared Input Undo and Redo',async()=>{
 const f=await mixedSharedBatch(),saved=await f.s.editLibraryBatch({operationId:op(),entries:f.entries});
 for(const side of ['before','after']){const items=[];for(const ref of [...saved.items].reverse()){const row=await f.s.entry(ref.id);items.push({id:ref.id,revisionId:ref.revisionId,side,expectedRevision:row.revision,expectedInputRevision:row.currentInputRevision});}const request={operationId:op(),items},result=await f.s.thoughtEditHistory(request);assert.deepEqual(await f.s.thoughtEditHistory(request),result);
  for(const item of result.items){const row=await f.s.entry(item.id);assert.equal(item.revision,row.revision,'history result must include later sibling propagation');assert.equal(row.body,side==='before'?f.before[0].body:'Synthetic final shared body');assert.equal(row.bodyBinding,'input');}
  const companion=await f.s.entry(f.before[1].id);assert.equal(companion.note,side==='before'?f.before[1].note:'Synthetic companion metadata');assert.equal(companion.type,side==='before'?f.before[1].type:'reflection');assert.equal((await f.s.input(f.b.id)).libraryText,companion.body);
 }
});
for(const rebindFirst of [false,true])test('UX-R3 shared Undo rejects an incompatible historical Input rebind atomically with '+(rebindFirst?'rebind first':'shared first'),async()=>{
 const f=await mixedSharedBatch(),shared=await f.s.editLibraryBatch({operationId:op(),entries:[f.entries[0]]});await f.s.reverseEditSetting(false);const other=await f.s.entry(f.before[1].id),detached=await f.s.editLibraryBatch({operationId:op(),entries:[{id:other.id,expectedRevision:other.revision,expectedFieldRevisions:other.fieldRevisions,expectedInputRevision:other.currentInputRevision,changes:{body:'Synthetic detached rebind target'}}]});
 const refs=[shared.items[0],detached.items[0]],items=[];for(const ref of rebindFirst?refs.reverse():refs){const row=await f.s.entry(ref.id);items.push({id:ref.id,revisionId:ref.revisionId,side:'before',expectedRevision:row.revision,expectedInputRevision:row.currentInputRevision});}
 const state=async()=>Object.fromEntries(await Promise.all(['blocks','thoughts','provenance','dependencies','revisions','operationReceipts'].map(async store=>[store,await rows(f.s,store)]))),before=await state(),result=await f.s.thoughtEditHistory({operationId:op(),items,confirmArchive:true});assert.equal(result.conflict,true);assert.equal(result.sourceChanged,true);assert.deepEqual(await state(),before,'incompatible planned Input bodies must not commit any edit, evidence, history or receipt');assert.equal((await f.s.input(f.b.id)).libraryText,'Synthetic final shared body');assert.equal((await f.s.entry(other.id)).body,'Synthetic detached rebind target');
});

test('VS-05 compact root default preserves a saved grid choice and never rewrites Topic content',async()=>{
 const f=await completeFixture({texts:['Synthetic untouched source']});
 const topic=await f.s.createTopic({name:'Synthetic full Topic name',operationId:op()});
 assert.deepEqual(await f.s.thoughtLayout(),{layout:'list'});
 assert.deepEqual(await f.s.thoughtLayout('grid'),{layout:'grid'});
 assert.deepEqual(await f.s.thoughtLayout(),{layout:'grid'});
 assert.deepEqual(await f.s.thoughtLayout('list'),{layout:'list'});
 await assert.rejects(f.s.thoughtLayout('unknown'));
 assert.deepEqual(await f.s.thoughtLayout(),{layout:'list'});
 assert.equal((await f.s.topic(topic.id)).name,'Synthetic full Topic name');
 assert.equal((await rows(f.s,'records'))[0].value.originalText,'Synthetic untouched source');
});
