import test from 'node:test';
import assert from 'node:assert/strict';
import {completeFixture,rows,append} from './harness/original-complete.mjs';
import {backupHash,validateBackupItem} from '../core/backup-format.js';
import {BackupService} from '../core/backup-service.js';
import {exported,prepared} from './harness/backup-v081.mjs';
import {migrateBindings,BINDING_ROW} from '../core/thought-binding.js';
const op=()=>crypto.randomUUID();
async function fixture(){const f=await completeFixture({texts:['UXR3_COMPAT 合成原文']});const b=(await rows(f.s,'blocks'))[0].value,t=await f.s.createTopic({name:'保留主题',operationId:op()}),r=await f.s.addToTopics({id:b.id,kind:'input',expectedRevision:b.revision,operationId:op(),topicIds:[t.id]});return {...f,b,t,id:r.id};}
test('UX-R3 new Backup round trip retains binding, independent body, history and layout while reverse editing stays off',async()=>{const f=await fixture(),e=await f.s.entry(f.id);await f.s.editLibraryFields({id:e.id,operationId:op(),expectedRevision:e.revision,expectedFieldRevisions:e.fieldRevisions,expectedInputRevision:e.currentInputRevision,changes:{body:'UXR3 独立人工正文'}});await f.s.reverseEditSetting(true);await f.s.thoughtLayout('list');const items=await exported(new BackupService(f.s)),target=await completeFixture({texts:[]}),service=new BackupService(target.s),stage=await prepared(service,items);await service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});const restored=await target.s.entry(e.id);assert.equal(restored.body,'UXR3 独立人工正文');assert.equal(restored.bodyBinding,'thought');assert.equal(restored.workingInputId,undefined);assert.equal((await target.s.reverseEditSetting()).enabled,false);assert.equal((await target.s.thoughtLayout()).layout,'list');assert.deepEqual((await rows(target.s,'revisions')).map(x=>x.before),(await rows(f.s,'revisions')).map(x=>x.before));assert.equal(JSON.stringify(items).includes('thought-reverse-edit'),false);assert.equal(target.requests.length,0);});
test('UX-R3 old backup and interrupted metadata batches resume without changing body, revision, identity or grants',async()=>{const f=await fixture();for(let i=0;i<3;i++)await f.s.continueThinking({operationId:op(),body:'旧版独立思想 '+i});await f.s.foundationWrite(async t=>{for(const row of await t.all('thoughts')){delete row.bodyBinding;delete row.bindingRevision;delete row.bindingLength;await t.put('thoughts',row);}await t.delete('meta',BINDING_ROW);});const before=await rows(f.s,'thoughts'),sources=await rows(f.s,'records');const checkpoint=f.s.repository.checkpoint;f.s.repository.checkpoint=async label=>{if(label==='thought-binding-batch')throw Error('SIMULATED_POWER_LOSS');};await assert.rejects(migrateBindings(f.s,{limit:1}));f.s.repository.checkpoint=checkpoint;await migrateBindings(f.s,{limit:1});await migrateBindings(f.s,{limit:1});const after=await rows(f.s,'thoughts');assert.deepEqual(after.map(x=>[x.id,x.thoughtText,x.revision,x.createdAt,x.sourceRecordIds]),before.map(x=>[x.id,x.thoughtText,x.revision,x.createdAt,x.sourceRecordIds]));assert.deepEqual(await rows(f.s,'records'),sources);assert.equal((await f.s.reverseEditSetting()).enabled,false);const oldItems=await exported(new BackupService(f.s));let chain='';for(const item of oldItems){if(item.section==='entries')for(const key of ['bodyBinding','bindingRevision','bindingLength','thoughtEditedAt'])delete item.value[key];if(item.section==='revisions')for(const side of ['before','after'])if(item.value[side])for(const key of ['bodyBinding','bindingRevision','bindingLength','thoughtEditedAt','bodyProtection','bodyAuthorship'])delete item.value[side][key];if(item.type==='footer')item.integrity.root=chain;else chain=await backupHash(chain,item);}assert.equal(oldItems.some(item=>item.section==='entries'&&item.value.bodyBinding),false);const target=await completeFixture({texts:[]}),service=new BackupService(target.s),stage=await prepared(service,oldItems);await service.restore({sessionId:stage.sessionId,confirmation:stage.preview.integrity});assert.equal((await target.s.entry(f.id)).bodyBinding,'input');await append(target.s,'UXR3_COMPAT 合成原文','complete-0');assert.equal((await rows(target.s,'thoughts')).length,4);});
test('UX-R3 topic position uses shared bounded device metadata, validates placement/revision and stays out of Backup',async()=>{const f=await fixture(),e=await f.s.entry(f.id);assert.equal(await f.s.topicPosition({topicId:f.t.id}),null);await f.s.topicPosition({topicId:f.t.id,entryId:e.id,revision:e.revision,offset:4,sort:'desc',expanded:[]});const anchor=await f.s.topicPosition({topicId:f.t.id});assert.equal(anchor.entryId,e.id);assert.equal(anchor.offset,4);const before=await rows(f.s,'thoughts');assert.equal((await f.s.topicPosition({topicId:f.t.id,entryId:e.id,revision:e.revision+1,offset:4,sort:'asc',expanded:[]})).saved,false);assert.deepEqual(await rows(f.s,'thoughts'),before);assert.equal(JSON.stringify(await exported(new BackupService(f.s))).includes('"anchors"'),false);});
test('UX-R3 multi-topic transaction rejects changed source or unavailable target without partial creation/placement',async()=>{const f=await fixture(),count=(await rows(f.s,'thoughts')).length;await assert.rejects(f.s.addToTopics({kind:'input',id:f.b.id,expectedRevision:f.b.revision,span:{start:0,end:4},operationId:op(),topicIds:[f.t.id,'missing-topic']}));assert.equal((await rows(f.s,'thoughts')).length,count);assert.equal((await f.s.addToTopics({kind:'input',id:f.b.id,expectedRevision:f.b.revision+1,operationId:op(),topicIds:[f.t.id]})).conflict,true);await assert.rejects(f.s.continueThinking({operationId:op(),body:' \n '}));assert.equal((await rows(f.s,'thoughts')).length,count);});
test('UX-R3 explicit Thought excerpt reuses exact selection only, preserves source restrictions and never binds to Input',async()=>{const f=await fixture(),e=await f.s.entry(f.id),selection={kind:'thought',id:e.id,expectedRevision:e.revision,span:{start:0,end:4},topicIds:[f.t.id],operationId:op()},a=await f.s.addToTopics(selection),b=await f.s.addToTopics({...selection,operationId:op()});assert.equal(a.id,b.id);assert.notEqual(a.id,e.id);assert.equal((await f.s.entry(a.id)).body,e.body.slice(0,4));assert.equal((await f.s.entry(a.id)).bodyBinding,'thought');await f.s.permanentDelete(f.b.originalTextReference);assert.equal((await f.s.entry(a.id)).body,'');});

test('UX-R3 Backup rejects unknown binding and malformed live metadata without downgrading fields',async()=>{const f=await fixture(),item=(await exported(new BackupService(f.s))).find(x=>x.section==='entries');for(const patch of [{bodyBinding:'future'},{bindingRevision:-1},{bindingLength:-2},{workingInputId:''},{bodyBinding:'thought'}])assert.throws(()=>validateBackupItem({...item,value:{...item.value,...patch}}));});
