import {organizeSingleUI} from './harness/reading-closure.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
import {FakeChatGPT,eventually,pause} from './harness/fake-chatgpt.mjs';import {conversation,branched} from './fixtures/history-v090.mjs';import {productReply} from './fixtures/product-history-v080.mjs';
const out='work/ux-v091/';const rpc=async(p,type,fields={})=>{const r=await p.evaluate(x=>chrome.runtime.sendMessage(x),{type,...fields});assert.equal(r.ok,true,JSON.stringify(r));return r.data;};
async function consent(p){await p.locator('#consent-check').check();await p.locator('#enable-consent').click();}
async function imported(p,data){await p.locator('#settings-history').click();await p.locator('#history-file-consent').check();await p.locator('#history-file').setInputFiles({name:'synthetic-ux.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await eventually(()=>p.locator('#history-commit').isEnabled());await p.locator('#history-commit').click();await eventually(()=>p.locator('#history-success').isVisible());}
test('v091 visible Settings, review return paths, Input order and single history entry',{timeout:90000},async()=>{
 await mkdir(out,{recursive:true});const h=await FakeChatGPT.start({headless:false}),p=h.archive;try{
  await p.setViewportSize({width:1440,height:1000});await consent(p);await p.locator('[data-view=settings]').click();await p.locator('#deepseek-api-key').waitFor();
  for(const id of ['deepseek-api-key','deepseek-save','deepseek-clear','organizer-batch-mode','organizer-daily-limit'])assert.equal(await p.locator('#'+id).isVisible(),true);
  assert.equal(await p.locator('#organizer-advanced').getAttribute('open'),null);for(const id of ['original-batch-preview','original-organizer-trace','organizer-budget-status','original-organizer-cost-note'])assert.equal(await p.locator('#'+id).isVisible(),false);
  await p.locator('#deepseek-api-key').fill('synthetic-ux-key');await p.locator('#deepseek-save').click();await eventually(async()=>/已配置/.test(await p.locator('#deepseek-status').textContent()));await p.locator('#deepseek-clear').click();await eventually(async()=>!/已配置/.test(await p.locator('#deepseek-status').textContent()));
  await p.locator('#deepseek-settings').scrollIntoViewIfNeeded();await p.screenshot({path:out+'settings.png'});
  await imported(p,[branched(),conversation(2,125)]);await p.locator('#history-review').click();await eventually(async()=>/Settings.*历史补全/.test(await p.locator('#review-breadcrumb').textContent()));assert.match(await p.locator('#review-breadcrumb').textContent(),/Settings.*历史补全/);assert.equal(await p.locator('#review-back').isVisible(),true);
  const pending=(await h.state()).library.blocks.find(b=>b.branchStatus);await p.locator('[data-document-id="'+pending.documentId+'"]').click();const row=p.locator('[data-block-id="'+pending.id+'"]');await row.locator('.excluded-prose').waitFor();for(const label of ['归入现有聊天窗口','保留为独立整理文档','忽略','暂不处理'])assert.equal(await row.getByRole('button',{name:label,exact:true}).isVisible(),true);
  await row.getByRole('button',{name:'暂不处理',exact:true}).click();assert.ok((await rpc(p,'GET_INPUT',{id:pending.id})).branchStatus);await p.screenshot({path:out+'review.png'});
  await row.getByRole('button',{name:'保留为独立整理文档',exact:true}).click();await eventually(()=>p.locator('#review-result').isVisible());await p.locator('#review-result').getByRole('button',{name:'查看对应文档'}).click();await p.locator('.library-prose').waitFor();assert.equal((await rpc(p,'GET_INPUT',{id:pending.id})).branchStatus,undefined);
  await p.locator('#revision-history').click();await p.locator('#revision-dialog').waitFor();assert.ok(await p.locator('.revision-row').count()>0);await p.locator('#close-revisions').click();await p.locator('#document-menu').click();assert.equal(await p.locator('#context-menu button').filter({hasText:'版本历史'}).count(),0);
  await p.locator('[data-view=library]').click();const d=(await h.state()).conversations.find(d=>d.sourceConversationId===conversation(2).id);await p.locator('[data-document-id="'+d.id+'"]').click();await p.locator('.library-prose').first().waitFor();const asc=await p.locator('.library-prose').first().textContent();await p.locator('[data-input-sort=desc]').click();await eventually(async()=>(await p.locator('.library-prose').first().textContent()).includes(' / 125'));
  assert.notEqual(await p.locator('.library-prose').first().textContent(),asc);await p.screenshot({path:out+'input-desc.png'});await p.locator('.pagination').getByRole('button',{name:'下一部分'}).click();await eventually(async()=>(await p.locator('.library-prose').first().textContent()).includes(' / 25'));
  await p.reload();await p.locator('[data-document-id="'+d.id+'"]').click();await eventually(async()=>(await p.locator('.library-prose').first().textContent()).includes(' / 125'));assert.equal(await p.locator('[data-input-sort=desc]').getAttribute('aria-pressed'),'true');assert.equal((await rpc(p,'GET_ORGANIZER_CONTROLS')).readingSort,'asc');
  await p.locator('[data-view=settings]').click();await p.locator('#settings-branch-review').click();await p.locator('#review-back').click();await p.locator('#settings-panel').waitFor();assert.equal(await p.locator('#settings-panel').isVisible(),true);assert.equal(h.extensionNetworkRequests,0);assert.deepEqual(h.errors,[]);
  await writeFile(out+'review-reading.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,settingsQuiet:true,reviewActions:true,contextReturn:true,sourcePreserved:true,globalInputOrder:true,independentPreference:true,oneDocumentHistory:true,requests:0,errors:h.errors},null,2));
 }finally{await h.close();}
});
test('v091 quiet Thought homepage; only explicit failed actions show local budget or retry feedback',{timeout:90000},async()=>{
 await mkdir(out,{recursive:true});const h=await FakeChatGPT.start({headless:false,deepSeekFixture:productReply}),p=h.archive;try{
  await p.setViewportSize({width:1440,height:1000});await consent(p);await p.locator('[data-view=settings]').click();await imported(p,[conversation(2,5)]);await p.locator('#history-thoughts').click();await rpc(p,'SAVE_DEEPSEEK_CREDENTIAL',{config:{apiKey:'synthetic-ux-only'}});await organizeSingleUI(p);await eventually(async()=>await p.locator('.topic-index-row').count()>0);const originalCalls=h.deepSeekRequests.length;
  const topic=(await rpc(p,'LIBRARY_INDEX_PAGE',{options:{mode:'all'}})).items[0];await p.locator('[data-topic-id="'+topic.id+'"]').click();assert.equal(await p.locator('#revision-history').isVisible(),true);await p.locator('#topic-menu summary').click();assert.equal(await p.locator('#topic-menu button').filter({hasText:'版本历史'}).count(),0);await p.locator('#topic-menu summary').click();await p.locator('[data-reading-sort=desc]').click();await eventually(async()=>(await rpc(p,'GET_ORGANIZER_CONTROLS')).readingSort==='desc');assert.equal((await rpc(p,'GET_ORGANIZER_CONTROLS')).inputReadingSort,'asc');
  await p.locator('#back').click();await p.locator('#ai-presentation-toggle').check();
  await p.evaluate(()=>{const actual=chrome.runtime.sendMessage.bind(chrome.runtime);window.restoreUXRPC=()=>{chrome.runtime.sendMessage=actual;};window.uxFailure='budget';window.uxActions=0;chrome.runtime.sendMessage=async q=>{if(q.type==='GET_LIBRARY_MERGE_SUGGESTIONS'&&window.uxMerge)return {ok:true,data:{items:[{id:'synthetic-merge'}]}};if(q.type==='START_BOUNDED_ORGANIZER'){window.uxBudgetRemaining=false;return {ok:true,data:{state:'budget_limited',error:'BUDGET_EXCEEDED'}};}if(q.type==='UPDATE_AI_PRESENTATION'){window.uxActions++;return {ok:true,data:{error:window.uxFailure==='budget'?'BUDGET_EXCEEDED':'HTTP_ERROR',phase:'preparing'}};}const r=await actual(q);if(q.type==='GET_ORGANIZER_CONTROLS')return {...r,data:{...r.data,usedRequests:window.uxBudgetRemaining?19:20,dailyRequests:20,resetAt:'2030-01-01T00:00:00.000Z'}};if(q.type==='GET_BOUNDED_ORGANIZER')return {ok:true,data:{state:'budget_limited',kind:'ai',maxRequests:3,maxTopics:3,requestsReserved:0}};return r;};});
  await p.locator('#thought-search').fill(' ');await pause(300);await p.locator('#thought-search').fill('');await pause(400);assert.equal(await p.locator('#library-cost-preview').textContent(),'');assert.equal(await p.locator('#ai-update-feedback').textContent(),'');assert.equal(await p.locator('#bounded-progress').isVisible(),false);assert.equal(await p.locator('#ai-library-retry').isVisible(),false);assert.equal(await p.locator('#topic-merge-suggestions').isVisible(),false);assert.equal(await p.locator('#bounded-ai-start').isVisible(),false);
  await p.screenshot({path:out+'thought-home.png'});await p.locator('[data-view=settings]').click();await p.locator('#bounded-ai-start').click();await p.locator('#library-dialog-close').click();assert.equal(await p.locator('#ai-update-feedback').textContent(),'');await p.evaluate(()=>{window.uxBudgetRemaining=true;});await p.locator('#bounded-ai-start').click();await p.locator('#library-form button[type=submit]').click();await eventually(async()=>/重置时间/.test(await p.locator('#ai-update-feedback').textContent()));assert.equal(h.deepSeekRequests.length,originalCalls);await p.locator('[data-view=thoughts]').click();await p.locator('[data-topic-id="'+topic.id+'"]').click();await p.locator('#ai-library-update').click();await eventually(async()=>/重置时间/.test(await p.locator('#ai-update-feedback').textContent()));assert.match(await p.locator('#ai-update-feedback').textContent(),/Settings/);assert.equal(await p.locator('#ai-library-retry').isVisible(),false);await p.screenshot({path:out+'action-budget.png'});assert.equal(h.deepSeekRequests.length,originalCalls);
  await p.evaluate(()=>{window.uxFailure='http';});await p.locator('#ai-library-update').click();await eventually(()=>p.locator('#ai-library-retry').isVisible());assert.match(await p.locator('#ai-update-feedback').textContent(),/重试将再次调用/);const attempts=await p.evaluate(()=>window.uxActions);await pause(1300);assert.equal(await p.evaluate(()=>window.uxActions),attempts);await p.screenshot({path:out+'action-failed.png'});
  await p.evaluate(()=>window.restoreUXRPC());await p.locator('[data-view=settings]').click();assert.equal(await p.locator('#original-organizer-cost-note').isVisible(),false);await p.locator('[data-view=thoughts]').click();assert.equal(await p.locator('#ai-update-feedback').textContent(),'');assert.equal(await p.locator('#ai-library-retry').isVisible(),false);
  await p.locator('#ai-library-update').click();await eventually(async()=>(await rpc(p,'GET_AI_PRESENTATION_STATUS')).pendingTopics===0);await eventually(async()=>!await p.locator('#ai-library-update').isVisible());assert.equal(await p.locator('#bounded-ai-start').isVisible(),false);assert.equal(await p.locator('#library-view-status').textContent(),'');await p.setViewportSize({width:760,height:900});await p.screenshot({path:out+'thought-narrow.png'});assert.equal(h.externalRequests,0);assert.deepEqual(h.errors,[]);
  await writeFile(out+'thought-actions.json',JSON.stringify({syntheticOnly:true,visibleChrome:true,quietPassiveBudget:true,mergeManagementInSettings:true,boundedBudgetLocal:true,cancelDoesNotShowFailure:true,localBudgetResetAndSettings:true,localFailureRetry:true,noAutomaticRetry:true,conditionalAIButtons:true,thoughtOrderIndependent:true,oneTopicHistory:true,explicitProviderRequests:h.deepSeekRequests.length,errors:h.errors},null,2));
 }finally{await h.close();}
});
