import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {readTopicRootSlots,saveTopicRootSlots} from '../ui/topic-root-slots.js';
import {RouteHistory,validRoute,routeViews} from '../ui/route-history.js';
const source=readFileSync(new URL('../ui/reader-navigation.js',import.meta.url),'utf8');
function fixture(){
 const listeners={},entries=[null];let refuse=false;let at=0,current={view:'library',documentId:null,searchQuery:''};
 const history={get state(){return entries[at];},replaceState(s){entries[at]=structuredClone(s);},pushState(s){entries.splice(++at);entries[at]=structuredClone(s);},async back(){if(at)await listeners.popstate({state:entries[--at]});},async forward(){if(at+1<entries.length)await listeners.popstate({state:entries[++at]});}};
 const context={RouteHistory,validRoute,views:routeViews,appShellRoute:r=>structuredClone(r),presentAppShell(){},crypto,structuredClone,location:{href:'chrome-extension://synthetic/ui/archive.html'},history,document:{addEventListener(){},querySelectorAll:()=>[]},window:{addEventListener:(name,fn)=>listeners[name]=fn},readTopicRootSlots:()=>readTopicRootSlots(history)};
 vm.createContext(context);vm.runInContext(source.slice(source.indexOf('export function installReaderNavigation')).replace('export function','function')+'\nthis.install=installReaderNavigation;',context);
 const routes=context.install({current:()=>current,navigate:async(view,documentId,_input,options)=>{if(refuse)return false;current={view,documentId,topicId:options.topicId,originKey:options.originKey,searchQuery:options.searchQuery};}});routes.commit({replace:true});
 return {history,routes,forgePrevious:value=>entries[at-1]=structuredClone(value),reject:value=>refuse=value,set:r=>{current=r;},current:()=>current};
}
test('rejected popstate restores the exact current committed state including Root slots, shell and origin',async()=>{const f=fixture();f.history.replaceState({...f.history.state,paiaTopicRootSlots:{version:1,views:[[4,['synthetic-topic']]],removed:[]}});f.set({view:'thoughts',topicId:'synthetic-topic',originKey:'11111111-1111-4111-8111-111111111111'});f.routes.commit();const before=structuredClone(f.history.state);f.reject(true);await f.history.back();assert.deepEqual(f.history.state,before);assert.equal(f.current().topicId,'synthetic-topic');});
test('rejected browser Back from Search keeps its marker and qualified query origin',async()=>{const f=fixture();f.history.pushState({...f.history.state,paiaSearch:true});f.set({view:'library',documentId:null,searchQuery:'SYNTHETIC',originKey:'11111111-1111-4111-8111-111111111111'});f.routes.commit({replace:true});const before=structuredClone(f.history.state);f.reject(true);await f.history.back();assert.deepEqual(f.history.state,before);assert.equal(f.history.state.paiaSearch,true);});
test('successful history arrival becomes the current checkpoint for subsequent refusal',async()=>{const f=fixture();f.set({view:'thoughts',topicId:'one'});f.routes.commit();f.set({view:'thoughts',topicId:'two'});f.routes.commit();await f.history.back();const before=structuredClone(f.history.state);f.reject(true);await f.history.back();assert.deepEqual(f.history.state,before);});
test('a refused forged target never replaces the trusted current checkpoint',async()=>{const f=fixture();f.set({view:'thoughts',topicId:'safe'});f.routes.commit();const before=structuredClone(f.history.state);f.forgePrevious({paiaSearch:true,paiaTopicRootSlots:{version:1,views:[[4,['forged']]],removed:[]},paiaReader:{view:'library',unexpected:'forged'}});f.reject(true);await f.history.back();assert.deepEqual(f.history.state,before);assert.equal(f.current().topicId,'safe');});
test('actual Root slot metadata written after route commit is checkpointed on writing entry before refusal',async()=>{const f=fixture();f.set({view:'thoughts',topicId:'named'});f.routes.commit();const slots=readTopicRootSlots(f.history);slots.reconcile(['named','later'],{columns:4,complete:true});assert.equal(saveTopicRootSlots(slots,f.history),true);assert.equal(f.routes.checkpoint(),true);const before=structuredClone(f.history.state);f.reject(true);await f.history.back();assert.deepEqual(f.history.state,before);assert.deepEqual(f.history.state.paiaTopicRootSlots,slots.snapshot());});
test('writing checkpoint refuses mismatched target history instead of trusting it',()=>{const f=fixture();f.set({view:'thoughts',topicId:'current'});f.routes.commit();f.history.replaceState({paiaReader:{view:'thoughts',topicId:'other'}});assert.equal(f.routes.checkpoint(),false);});

function writingReturnFixture(){let release;const held=new Promise(resolve=>release=resolve),restores=[];const c={Promise,scrollY:0,view:'thoughts',documentId:null,navigationIntent:1,writingRefreshPending:true,writingReturn:null,topicActions:{surface:{workspace:true},openIntent:1},routes:{checkpoint(){}},render(){},scrollTo:(x,y)=>restores.push({scroll:y}),refresh:()=>held,thoughts:{id:'topic',openIntent:1,originalPane:{},topicAnchor:()=>({id:'first',top:140}),topicReader:{restoreAnchor:(_root,anchor)=>restores.push(anchor)}}};vm.createContext(c);const code=readFileSync(new URL('../ui/archive.js',import.meta.url),'utf8');vm.runInContext(code.slice(code.indexOf('topicActions.onWorkspaceChange='),code.indexOf('topicActions.onDeferredRead=')),c);return {c,release,restores};}
test('old writing return cannot restore after a newer writing session opens and closes',async()=>{const {c,release,restores}=writingReturnFixture();c.topicActions.onWorkspaceChange();c.topicActions.surface=null;c.topicActions.openIntent++;c.topicActions.onWorkspaceChange();c.topicActions.surface={workspace:true};c.topicActions.openIntent++;c.thoughts.topicAnchor=()=>({id:'second',top:240});c.topicActions.onWorkspaceChange();c.topicActions.surface=null;c.topicActions.openIntent++;c.topicActions.onWorkspaceChange();await Promise.resolve();release();await Promise.resolve();await Promise.resolve();assert.deepEqual(restores.map(x=>x.id),['second']);});

for(const boundary of ['route','topic','scroll'])test('pending writing return refuses changed '+boundary,async()=>{const {c,release,restores}=writingReturnFixture();c.topicActions.onWorkspaceChange();c.topicActions.surface=null;c.topicActions.openIntent++;c.topicActions.onWorkspaceChange();if(boundary==='route')c.navigationIntent++;if(boundary==='topic')c.thoughts.id='other';if(boundary==='scroll')c.scrollY=300;release();await Promise.resolve();await Promise.resolve();assert.deepEqual(restores,[]);});
test('missing exact Entry on return does not fall back to an unrelated scroll position',async()=>{const {c,release,restores}=writingReturnFixture();let calls=0;c.thoughts.topicReader.restoreAnchor=()=>{calls++;return false;};c.topicActions.onWorkspaceChange();c.topicActions.surface=null;c.topicActions.openIntent++;c.topicActions.onWorkspaceChange();release();await Promise.resolve();await Promise.resolve();assert.equal(calls,1);assert.deepEqual(restores,[]);});
