"""Shared real-browser checks of synthetic homepage and standalone illustrations.
Retired export/task gates are replaced by the approved four-card model. These
checks certify website behavior, never real product grants or AI connections.
"""

def verify_core(page, check, en=True, download_dir=None, offline=False):
    prefix = 'EN' if en else 'ZH'
    def test(value, label):
        check(value, f'{prefix} core: {label}')
    def on(selector):
        return page.locator(selector).get_attribute('aria-pressed') == 'true'
    def open_card(key):
        page.locator(f'[data-card-open="{key}"]').click()
        test(page.locator(f'[data-card-detail="{key}"]').is_visible(), f'{key} opens its own detail')
        test(not page.locator('[data-context-overview]').is_visible(), 'detail replaces overview')
    def back(key):
        page.locator(f'[data-card-detail="{key}"] [data-context-back]').click()
        test(page.locator(f'[data-card-open="{key}"]').evaluate('e=>e===document.activeElement'), 'Back restores card focus')

    test(page.locator('[data-core-preview]').count() == 1, 'one shared product illustration')
    test(page.locator('.pc-nav a').count() == 4, 'four post-capture sections')
    test(page.locator('[data-core-preview] img').count() == 0, 'brand artwork is not repeated in features')
    expected_close = 0 if page.locator('body').get_attribute('data-page') == 'demo.html' else 1
    test(page.locator('.core-close img').count() == expected_close, 'original closing brand usage retained')
    test(page.locator('[data-topic-export], [data-authorize], [data-confirm-candidate], [data-build], [data-export]').count() == 0, 'retired export and task-approval controls are absent')
    original = page.locator('[data-original="a"]').text_content()
    changed = 'Example working text <img src=x onerror=alert(1)> — user-authored.'
    page.locator('[data-working="a"]').fill(changed)
    test(page.locator('[data-original="a"]').text_content() == original, 'source remains immutable')
    test(page.locator('[data-thought-text="a"]').inner_text() == changed, 'whole-input reference follows working text')
    test(page.locator('[data-thought-text="a"] img').count() == 0, 'working text cannot inject HTML')
    page.locator('[data-reading-style]').select_option('balanced')
    test(page.locator('[data-reading-output]').get_attribute('data-stale') == 'true', 'source edit retires preset AI reading')
    page.locator('[data-archive-search]').fill('Example working text')
    test(page.locator('[data-input]:visible').count() == 1, 'search uses current working text')
    page.locator('[data-working="a"]').fill('The matching phrase has now been edited away.')
    test(page.locator('[data-working="a"]').is_visible() and page.locator('[data-working="a"]').evaluate('e=>e===document.activeElement'), 'search never hides the input being edited')
    page.locator('[data-archive-search]').focus()
    test(page.locator('[data-input]:visible').count() == 0, 'leaving the editor reapplies the current search')
    page.locator('[data-archive-search]').fill('')
    page.locator('[data-working="a"]').fill(changed)
    page.locator('[data-archive-search]').fill('no-match-website-core-xyz')
    test(page.locator('[data-archive-empty]').is_visible(), 'empty search state')
    page.locator('[data-archive-search]').fill('')
    page.locator('[data-sort]').click()
    test(page.locator('[data-records]>article').first.get_attribute('data-input') == 'c', 'time order reverses')
    page.locator('[data-sort]').click()
    test(page.locator('[data-records]>article').first.get_attribute('data-input') == 'a', 'time order restores')
    prompt = 'A personal edited prompt, not a preset.'
    page.locator('#pc-prompt-0').fill(prompt)
    page.locator('[data-prompt-row="0"] [data-insert]').click()
    test(page.locator('#pc-composer').input_value() == prompt, 'empty composer receives edited prompt')
    page.locator('#pc-composer').fill('An existing draft must survive.')
    page.locator('[data-prompt-row="0"] [data-insert]').click()
    test(page.locator('#pc-composer').input_value() == 'An existing draft must survive.\n\n' + prompt, 'insertion preserves existing draft')
    page.locator('[data-prompt-row="0"] [data-move="1"]').click()
    test(page.locator('[data-prompt-list]>div').nth(1).get_attribute('data-prompt-row') == '0', 'prompt order changes')
    test(page.locator('[data-prompt-row="0"] [data-rank]').inner_text() == '02', 'rank follows order')
    page.locator('[data-prompt-row="0"] [data-move="-1"]').click()
    draft = page.locator('#pc-composer').input_value()
    page.locator('[data-suggestion]').click()
    test(page.locator('#pc-composer').input_value() == draft + '\n\n' + page.locator('[data-suggestion]').inner_text(), 'optional preset preserves prior draft without sending')
    page.locator('[data-topic-view="connected"]').click()
    test('is-connected' in page.locator('[data-topic-stage]').get_attribute('class'), 'topic organization changes view')
    test(page.locator('[data-thought]').count() == 4, 'same four entries survive organization')
    test(page.locator('[data-thought-text="a"]').inner_text() == changed, 'organization preserves user meaning')
    page.locator('[data-topic-view="separate"]').click()
    test('is-connected' not in page.locator('[data-topic-stage]').get_attribute('class'), 'organization is reversible')

    test(page.locator('[data-context-card]').count() == 4, 'exactly four independent Context cards')
    test(page.locator('[data-context-overview] textarea, [data-context-overview] input').count() == 0, 'overview has no personal body or checkbox matrix')
    test(page.locator('[data-card-allow][aria-pressed=true], [data-topic-allow][aria-pressed=true]').count() == 0 and not on('[data-context-global]'), 'all scope starts closed')
    page.locator('[data-card-allow="rules"]').click()
    test(not on('[data-context-global]'), 'opening a card does not open global access')
    test(page.locator('[data-context-preview] strong').count() == 0, 'paused scope releases no example material')
    open_card('rules')
    rule = 'User rule <script>neverRun()</script>'
    page.locator('[data-context-text="rules"]').fill(rule)
    test(page.locator('[data-working="a"]').input_value() == changed, 'independent Context edit never writes Archive')
    back('rules')
    page.locator('[data-context-global]').click()
    test(rule in page.locator('[data-context-preview]').inner_text(), 'allowed card shows literal current content')
    test(page.locator('[data-context-preview] script').count() == 0, 'Context cannot inject markup')
    test(page.locator('[data-context-preview] strong').count() == 1, 'other cards stay out of scope')
    open_card('inputs')
    page.locator('[data-topic-allow="product"]').click()
    test(not on('[data-card-allow="inputs"]'), 'opening a topic does not open parent card')
    test(changed not in page.locator('[data-context-preview]').inner_text(), 'closed My Inputs denies an open topic')
    test(page.locator('[data-topic-allow="product"]').inner_text() == ('Open' if en else '已开放'), 'closed parent never labels a retained topic AI-readable')
    back('inputs')
    page.locator('[data-card-allow="inputs"]').click()
    preview = page.locator('[data-context-preview]').inner_text()
    test(changed in preview and page.locator('[data-thought-text="note"]').inner_text() in preview, 'open topic scope includes complete sample bodies')
    test(page.locator('[data-topic-allow="product"]').inner_text() == ('AI readable' if en else 'AI 可读'), 'topic label reflects effective access')
    test(('Writing practice' if en else '写作习惯') not in preview, 'unopened topic stays excluded')
    page.locator('[data-context-pause]').click()
    test(not on('[data-context-global]') and on('[data-card-allow="rules"]') and on('[data-topic-allow="product"]'), 'pause preserves lower choices')
    test(page.locator('[data-context-preview] strong').count() == 0, 'pause removes effective scope')
    page.locator('[data-context-global]').click()
    open_card('inputs')
    page.locator('[data-topic-allow="product"]').click()
    test(rule in page.locator('[data-context-preview]').inner_text() and changed not in page.locator('[data-context-preview]').inner_text(), 'closing a topic preserves independent Rules')
    back('inputs')
    open_card('rules')
    page.locator('[data-context-remove="rules"]').click()
    test(rule not in page.locator('[data-context-preview]').inner_text(), 'removed item leaves allowed scope')
    page.locator('[data-context-undo="rules"]').click()
    test(page.locator('[data-context-text="rules"]').input_value() == rule, 'undo restores exact local item')
    back('rules')
    page.locator('[data-context-clear]').click()
    test(page.locator('[data-card-allow][aria-pressed=true], [data-topic-allow][aria-pressed=true]').count() == 0 and not on('[data-context-global]'), 'withdraw clears permissions')
    test(page.locator('[data-context-text="rules"]').input_value() == rule, 'withdraw does not delete content')
    test(page.locator('.pc-access-boundary').is_visible(), 'real-connection limitation stays visible')
    page.locator('[data-reset-inputs]').click()
    test(page.locator('[data-working="a"]').input_value() == original, 'reset restores working text')
    test(page.locator('[data-thought-text="a"]').inner_text() == original, 'reset updates explicit topic reference')
    test(page.locator('[data-reading-output]').get_attribute('data-stale') == 'false', 'matching source allows preset again')
    for style in ('original', 'balanced', 'concise'):
        page.locator('[data-reading-style]').select_option(style)
        test(bool(page.locator('[data-reading-output]').inner_text().strip()), f'{style} reading is visible')
        test(page.locator('[data-working="a"]').input_value() == original, f'{style} never overwrites working text')
    page.locator('[data-reading-style]').select_option('original')
