"""Shared browser journeys for the four fictional homepage previews.
Run against both the candidate HTTP site and the current production site.
No account connection, private content, form submission or AI call is made.
"""
from pathlib import Path

def verify_core(page, check, en=True, download_dir=None, offline=False):
    prefix='EN' if en else 'ZH'
    def test(value, label):
        check(value, f'{prefix} core: {label}')
    test(page.locator('[data-core-preview]').count()==1,'four-function preview exists')
    test(page.locator('.pc-nav a').count()==4,'four post-capture sections')
    test(page.locator('[data-core-preview] img').count()==0,'owner artwork is not repeated in feature sections')
    test(page.locator('.core-close img').count()==1,'original closing brand artwork retained')
    test(page.locator('[data-v3-context]').count()==0,'retired context-picker is absent')
    original=page.locator('[data-original="a"]').text_content()
    changed='Example working text <img src=x onerror=alert(1)> — user-authored.'
    page.locator('[data-working="a"]').fill(changed)
    test(page.locator('[data-original="a"]').text_content()==original,'source text remains immutable')
    test(page.locator('[data-thought-text="a"]').inner_text()==changed,'topic inherits working-text edits')
    test(page.locator('[data-thought-text="a"] img').count()==0,'working text cannot inject HTML')
    page.locator('[data-archive-search]').fill('Example working text')
    test(page.locator('[data-input]:visible').count()==1,'search filters actual working text')
    page.locator('[data-archive-search]').fill('no-match-website-core-xyz')
    test(page.locator('[data-archive-empty]').is_visible(),'empty search state')
    page.locator('[data-archive-search]').fill('')
    page.locator('[data-sort]').click()
    test(page.locator('[data-records]>article').first.get_attribute('data-input')=='c','time order actually reverses')
    page.locator('[data-sort]').click()
    test(page.locator('[data-records]>article').first.get_attribute('data-input')=='a','time order reverses back')
    prompt='A personal edited prompt, not a preset.'
    page.locator('#pc-prompt-0').fill(prompt)
    page.locator('[data-prompt-row="0"] [data-insert]').click()
    test(page.locator('#pc-composer').input_value()==prompt,'edited prompt fills composer without sending')
    page.locator('[data-prompt-row="0"] [data-move="1"]').click()
    test(page.locator('[data-prompt-list]>div').nth(1).get_attribute('data-prompt-row')=='0','prompt order really changes')
    test(page.locator('[data-prompt-row="0"] [data-rank]').inner_text()=='02','displayed rank follows order')
    page.locator('[data-prompt-row="0"] [data-move="-1"]').click()
    page.locator('[data-suggestion]').click()
    test(page.locator('#pc-composer').input_value()==page.locator('[data-suggestion]').inner_text(),'preset next-step suggestion fills composer')
    page.locator('[data-topic-view="connected"]').click()
    test('is-connected' in page.locator('[data-topic-stage]').get_attribute('class'),'topic organization visibly changes')
    test(page.locator('[data-thought]').count()==4,'same four records survive reorganization')
    test(page.locator('[data-thought-text="a"]').inner_text()==changed,'organization does not rewrite user meaning')
    if offline:
        page.evaluate("""window.__coreNativeURL=URL.createObjectURL; URL.createObjectURL=blob=>{window.__coreExport=blob;return window.__coreNativeURL(blob)};document.addEventListener('click',e=>{if(e.target.closest('a[download]'))e.preventDefault()},true)""")
        page.locator('[data-topic-export]').click()
        exported=page.evaluate('window.__coreExport.text()')
        test(changed in exported and original not in exported,'export blob includes working text (offline; download not certified)')
    elif download_dir:
        with page.expect_download() as info:
            page.locator('[data-topic-export]').click()
        download=info.value
        destination=Path(download_dir)/f'core-example-{prefix}.md'
        download.save_as(str(destination))
        exported=destination.read_text()
        test(changed in exported,'real Markdown export contains working text')
        test(original not in exported,'export does not silently substitute source for edits')
        test(download.suggested_filename=='paia-example-thought-trail.md','explicit example export filename')
    page.locator('[data-topic-view="separate"]').click()
    test('is-connected' not in page.locator('[data-topic-stage]').get_attribute('class'),'topic view is reversible')
    test(page.locator('[data-authorize]').is_disabled(),'cannot authorize empty scope')
    test(page.locator('[data-context-item="candidate"]').is_disabled(),'unconfirmed candidate cannot be selected')
    page.locator('[data-context-item="preference"]').check()
    page.locator('#pc-personal-note').fill('User note <script>neverRun()</script>')
    test('<script>neverRun()</script>' in page.locator('[data-context-preview]').inner_text(),'personal note appears literally in preview')
    test(page.locator('[data-context-preview] script').count()==0,'personal context cannot inject HTML')
    page.locator('[data-authorize]').click()
    test(page.locator('[data-revoke]').is_visible(),'example permission can be granted')
    page.locator('#pc-personal-note').fill('Updated preference')
    test(not page.locator('[data-revoke]').is_visible(),'editing context invalidates previous permission')
    test(page.locator('[data-authorize]').is_visible(),'changed context requires new permission')
    page.locator('[data-context-item="project"]').check()
    test(page.locator('[data-context-preview]>p').count()==2,'only selected facts enter scope')
    page.locator('[data-authorize]').click()
    page.locator('[data-revoke]').click()
    test(page.locator('[data-authorize]').is_visible(),'revocation returns to not-authorized state')
    page.locator('[data-confirm-candidate]').click()
    candidate=page.locator('[data-context-item="candidate"]')
    test(candidate.is_enabled() and not candidate.is_checked(),'confirmation does not imply selection or authorization')
    candidate.check()
    test(page.locator('[data-context-preview]>p').count()==3,'confirmed candidate can explicitly join scope')
    page.locator('[data-context-item="project"]').uncheck()
    test(page.locator('[data-context-preview]>p').count()==2,'excluded fact removed from preview')
    test(page.locator('[data-usage-log]>li').count()>=4,'permission actions leave a visible local activity trail')
    test(page.locator('.pc-access-boundary').is_visible(),'no-transmission boundary is visible')
    page.locator('[data-reset-inputs]').click()
    test(page.locator('[data-working="a"]').input_value()==original,'working-text reset restores the example')
    test(page.locator('[data-thought-text="a"]').inner_text()==original,'reset propagates to dependent topic')
