"""Synthetic browser evidence; not measured human comprehension or retention."""


def verify_home(page, check, en=True, offline=False):
    def test(value,label): check(value, ('EN' if en else 'ZH') + ' V2 value proof: ' + label)
    root=page.locator('[data-value-proof]')
    mobile=page.viewport_size['width']<=760
    def view(name):
        if mobile: page.locator(f'[data-proof-view-pick="{name}"]').click()
    test(page.locator('[data-core-preview]').count()==0,'home does not repeat the full four-part Demo')
    test(root.count()==1 and page.locator('.fs-topic-window').count()==1,'one shared reading/task workbench')
    test(page.locator('.fs-expression').count()==4,'four complete source-attributed human inputs')
    test(page.locator('.hero-description br').count()==0,'natural hero word boundaries survive reflow')
    test(page.locator('[data-preview-tab] span').all_text_contents()==(['Input Archive','Thought Library','AI Context'] if en else ['输入档案','思想库','AI Context']),'product tabs follow website language')
    test(page.locator('.pv-context-card .is-closed').count()==4,'all hero Context cards default off')
    test(page.locator('.desktop-nav a[href$="demo.html"]').count()==1 and page.locator('.desktop-nav a[href$="blog.html"]').count()==0,'product experience is primary navigation')
    test(page.locator('.site-footer a[href$="blog.html"]').count()==1 and page.locator('.site-footer a[href$="about.html"]').count()==1,'editorial and origin remain in the footer')
    test(page.locator('.vp-native-sources a').count()==3,'native Search Projects Memory have official references')
    test(page.locator('[data-proof-line][data-state=included]').count()==0,'no value-proof success before original wording is inserted')
    view('reading')
    source=page.locator('.fs-source').first
    source.locator('summary').focus();page.keyboard.press('Enter')
    test(source.evaluate('e=>e.open') and 'ChatGPT' in source.inner_text(),'the source is keyboard readable')
    source.locator('summary').press('Enter')
    original=page.locator('[data-proof-expression="a"]>p').inner_text()
    boundary=page.locator('[data-proof-expression="c"]>p').inner_text()
    view('draft')
    composer=page.locator('#pc-composer')
    initial=composer.input_value()
    test(bool(initial),'the present task exists before any reuse')
    composer.fill(initial+' Existing draft stays.')
    preserved=composer.input_value()
    view('reading')
    page.locator('[data-story-reuse="a"]').click()
    test(page.locator('[data-nb-check-body]').inner_text()==original,'selection reveals complete wording, not a summary')
    test(composer.input_value()==preserved,'inspection does not itself insert text')
    test(page.locator('[data-proof-line][data-state=included]').count()==0,'inspection alone does not claim a changed request')
    page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()==preserved+'\n\n'+original,'explicit insertion preserves the existing draft')
    test(page.locator('[data-proof-line="a"]').get_attribute('data-state')=='included' and page.locator('[data-proof-line="c"]').get_attribute('data-state')=='missing','the argument is present but the evidence limit is still missing')
    view('reading')
    page.locator('[data-story-reuse="c"]').click()
    page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()==preserved+'\n\n'+original+'\n\n'+boundary,'the task now contains the exact argument and evidence boundary')
    test(page.locator('[data-proof-line][data-state=included]').count()==2,'only the two exact sample passages produce the two guide observations')
    test(('Not sent' if en else '没有发送') in page.locator('[data-prompt-status]').inner_text(),'nothing is automatically sent')
    composer.fill(initial+' This looks like a stronger argument.')
    test(page.locator('[data-proof-line][data-state=included]').count()==0,'arbitrary input is not interpreted as a successful semantic match')
    composer.fill(initial+'\n'+original[:-1])
    test(page.locator('[data-proof-line][data-state=included]').count()==0,'partial wording is never claimed to contain the full condition')
    composer.fill(initial+'\n'+original)
    view('reading');view('draft')
    test(composer.input_value()==initial+'\n'+original,'mobile view changes preserve one draft, rather than copying state')
    composer.dispatch_event('compositionstart')
    test(page.locator('[data-proof-reset]').is_disabled(),'request reset cannot interrupt synthetic active composition')
    composer.dispatch_event('compositionend')
    page.locator('[data-proof-reset]').click()
    test(composer.input_value()==initial and page.locator('[data-proof-line][data-state=included]').count()==0,'reset restores the request and reverses the guide observations')
    test(page.locator('[data-proof-expression="a"]>p').text_content()==original,'all reuse paths leave source material intact')
    if mobile:
        test(page.locator('[data-proof-pane=reading]').get_attribute('hidden') is not None and page.locator('[data-proof-pane=draft]').is_visible(),'one mobile pane is visible after deliberate navigation')
    if not offline:
        test(not page.evaluate('localStorage.length || sessionStorage.length'),'the illustrative task has no persistence')


def verify_narrow(page, check, en=True, offline=False):
    prefix='EN' if en else 'ZH'
    def test(value,label):check(value,f'{prefix} NIB v4 example: {label}')
    root=page.locator('[data-narrow-board]');card=page.locator('#pc-prompt-card');toggle=page.locator('[data-prompt-toggle]')
    composer=page.locator('#pc-composer')
    test(not card.is_visible() and toggle.get_attribute('aria-expanded')=='false','starts as an orb, not an automatically opened panel')
    toggle.focus();page.keyboard.press('Enter')
    test(card.is_visible() and toggle.get_attribute('aria-expanded')=='true','explicit keyboard action expands the board')
    width=card.bounding_box()['width']
    test(width<=336.1,'normal board does not exceed 336 CSS px')
    test(page.locator('[data-prompt-pick]').evaluate_all('els=>els.length===3&&els.every(e=>e.getBoundingClientRect().height>=44&&getComputedStyle(e.querySelector("span")).whiteSpace==="nowrap")'),'three candidates use one-line wording and at least 44px rows')
    test(page.locator('[data-rank]:visible').count()==0,'ordinary rows do not expose ranking metadata')
    page.locator('h1').click()
    test(card.is_visible(),'losing focus does not collapse the panel')
    def same_width(label):test(abs(card.bounding_box()['width']-width)<1,label+' keeps the same width')
    def manage(key):
        page.locator(f'[data-prompt-manage="{key}"]').click()
        test(page.locator(f'#pc-prompt-manage-{key}').is_visible(),'manual edit opens on deliberate action')
        same_width('Editing')
        return page.locator(f'[data-prompt-row="{key}"]')
    original=page.locator('#pc-prompt-0').input_value()
    working=page.locator('[data-working="a"]').input_value()
    row=manage('0')
    prompt='A deliberately long personal input with exact wording.\nKeep the second line too.'
    page.locator('#pc-prompt-0').fill(prompt)
    page.locator('#pc-prompt-0').press('Escape')
    test(page.locator('#pc-prompt-manage-0').is_visible(),'Escape protects a dirty edit instead of silently losing it')
    toggle.click()
    test(card.is_visible() and page.locator('#pc-prompt-0').input_value()==prompt,'close protects an unsaved edit')
    row.locator('[data-edit-save]').click()
    test(not page.locator('#pc-prompt-manage-0').is_visible() and page.locator('[data-prompt-label]').first.text_content()==prompt,'explicit Save updates only the frequent wording')
    test(page.locator('[data-working="a"]').input_value()==working,'editing a reusable phrase never rewrites the archive')
    composer.fill('')
    page.locator('[data-prompt-pick="0"]').click()
    test(root.get_attribute('data-mode')=='check' and composer.input_value()=='','clipped or multiline wording opens inspection before insertion')
    test(page.locator('[data-nb-check-body]').inner_text()==prompt,'inspection reveals the exact full wording')
    same_width('Full-text inspection')
    page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()==prompt,'explicit whole-text insertion is exact')
    before,after='Before.','After.'
    composer.fill(before+after)
    composer.evaluate('(el,p)=>{el.setSelectionRange(p,p);el.dispatchEvent(new Event("select",{bubbles:true}));}',len(before))
    page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()==before+'\n\n'+prompt+'\n\n'+after,'a reliable middle caret preserves both sides of the draft')
    test(composer.evaluate('(el,p)=>el.selectionStart===p&&el.selectionEnd===p',len(before)+2+len(prompt)),'the insertion caret follows the added wording')
    before,selected,after='Keep ','these selected words',' and the rest.'
    composer.fill(before+selected+after)
    composer.evaluate('(el,p)=>{el.setSelectionRange(p[0],p[1]);el.dispatchEvent(new Event("select",{bubbles:true}));}',[len(before),len(before+selected)])
    page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()==before+selected+'\n\n'+prompt+'\n\n'+after,'composer selection is preserved; insertion follows selectionEnd')
    composer.fill('')
    page.locator('[data-nb-check-body]').evaluate('el=>{const r=document.createRange();r.setStart(el.firstChild,2);r.setEnd(el.firstChild,24);const s=getSelection();s.removeAllRanges();s.addRange(r);document.dispatchEvent(new Event("selectionchange"));}')
    page.locator('[data-nb-insert-selection]').click()
    test(composer.input_value()==prompt[2:24],'only the explicitly selected inspection range is inserted')
    # Stub clipboard writes so browser tests never touch the computer clipboard.
    page.evaluate('Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText:async value=>{window.__copiedExample=value;}}})')
    page.locator('[data-nb-copy-full]').click()
    test(page.evaluate('window.__copiedExample')==prompt,'copy-full has no hidden source, title or metadata prefix')
    page.locator('[data-nb-copy-selection]').click()
    test(page.evaluate('window.__copiedExample')==prompt[2:24],'copy-selection contains only the selected range')
    page.evaluate('()=>{navigator.clipboard.writeText=async()=>{throw new Error("synthetic denial")};}')
    page.locator('[data-nb-copy-full]').click()
    test(('Copy failed' if en else '未能复制') in page.locator('[data-nb-status]').inner_text(),'clipboard denial is reported honestly')
    page.evaluate('delete navigator.clipboard;delete window.__copiedExample')
    # Separate length protection from the independently tested unavailable-band state.
    root.evaluate('el=>el.style.minHeight="52rem"')
    composer.fill('x'*990);page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()=='x'*990,'overflow never truncates wording or overwrites the draft')
    composer.fill('IME draft')
    composer.dispatch_event('compositionstart');page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()=='IME draft','synthetic composition gate blocks insertion during IME (not an OS IME test)')
    composer.dispatch_event('compositionend')
    root.evaluate('el=>el.style.minHeight=""')
    page.locator('[data-nb-back]').click();same_width('Return to candidates')
    row=manage('0');row.locator('[data-move="1"]').click()
    test(page.locator('[data-prompt-list]>div').nth(1).get_attribute('data-prompt-row')=='0','manual ordering remains available')
    row.locator('[data-move="-1"]').click();row.locator('[data-edit-cancel]').click()
    row=manage('2');row.locator('[data-pin]').click()
    test(row.locator('[data-pin]').get_attribute('aria-pressed')=='true' and page.locator('[data-prompt-list]>div').first.get_attribute('data-prompt-row')=='2','pinning places a phrase above unpinned phrases')
    test(row.locator('[data-move="1"]').is_disabled(),'manual ordering cannot silently cross a pin boundary')
    row.locator('[data-pin]').click();row.locator('[data-edit-cancel]').click()
    # Search reads the current working owner, not an outdated fixture or prompt override.
    page.locator('[data-working="a"]').fill('Needle42: a newly edited historical input, with an exact condition.')
    page.locator('[data-nb-search-open]').click();page.locator('[data-nb-query]').fill('Needle42')
    test(page.locator('[data-nb-result]').count()==1,'archive search finds current working text')
    same_width('Archive search')
    page.locator('[data-nb-result="a"]').click()
    old_draft=composer.input_value()
    test('Needle42:' in page.locator('[data-nb-check-body]').inner_text(),'search result inspection reads the current complete owner')
    page.locator('[data-working="a"]').fill('Needle42: changed while the inspection was open.')
    page.locator('[data-nb-insert-full]').click()
    test(composer.input_value()==old_draft,'a stale inspection cannot insert an obsolete body')
    page.locator('[data-nb-back]').click()
    test(page.locator('[data-nb-query]').input_value()=='Needle42','return preserves the search query')
    page.locator('[data-nb-query]').fill('Needle42')
    page.locator('[data-working="a"]').fill('Needle42: changed again before selecting the result.')
    page.locator('[data-nb-result="a"]').click()
    test(root.get_attribute('data-mode')=='check' and composer.input_value()==old_draft and 'changed again' in page.locator('[data-nb-check-body]').inner_text(),'a result changed before selection requires fresh inspection, never silent insertion')
    page.locator('[data-nb-back]').click()
    page.locator('[data-nb-query]').fill('no-match-nib-v4-xyz')
    test(page.locator('[data-nb-empty]').is_visible() and page.locator('[data-nb-result]').count()==0,'no-match is honest and does not invent AI candidates')
    toggle.click();toggle.click()
    test(page.locator('[data-nb-query]').input_value()=='no-match-nib-v4-xyz','explicit close/reopen preserves the current board state')
    root.evaluate('el=>{el.style.minHeight="130px";el.style.height="130px";}')
    page.wait_for_function('document.querySelector("[data-narrow-board]").dataset.layoutAvailable==="false"')
    test(toggle.get_attribute('aria-expanded')=='true' and page.locator('[data-nb-query]').input_value()=='no-match-nib-v4-xyz','no usable band preserves logical expansion and the query')
    root.evaluate('el=>{el.style.minHeight="";el.style.height="";}')
    page.wait_for_function('document.querySelector("[data-narrow-board]").dataset.layoutAvailable==="true"')
    test(card.is_visible(),'restoring geometry restores the same board without an automatic mode change')
    test(root.evaluate('e=>{const c=e.querySelector(".pc-palette").getBoundingClientRect(),h=e.querySelector(".nb-native-head").getBoundingClientRect(),i=e.querySelector(".nb-composer").getBoundingClientRect();return c.top>=h.bottom+11&&c.bottom<=i.top-11;}'),'panel stays below host controls and above the complete composer')
    page.locator('[data-nb-back]').click()
    page.locator('[data-working="a"]').fill(working)
    row=manage('0');page.locator('#pc-prompt-0').fill(original);row.locator('[data-edit-save]').click()
    composer.fill('')
    if not offline:
        test(not page.evaluate('localStorage.length || sessionStorage.length'),'all board edits and searches remain in current-page memory')
