"""Home proves one outcome; the separate Demo contains the full operations."""
from html import escape
from story import inputs, title
from prompt_preview import narrow_board


def render(t,a,button,icon):
    def ctl(label,attr='',cls='pc-control'):
        return f'<button type="button" class="{cls}" {attr} disabled>{label}</button>'
    data=inputs(t)
    def entry(row):
        return f'<article class="fs-expression"><time>2026 · {row["date"]}</time><p>{escape(row["text"])}</p><details class="fs-source"><summary>{t("查看来源","View source")}</summary><p>ChatGPT · {row["source"]} · {row["time"]}</p><p>{t("虚构用户输入。原始来源不会被工作文字的编辑覆盖。","Fictional user input. Editing working text does not overwrite its original source.")}</p></details></article>'
    difference=f'''<section class="fs-difference wrap" id="input-library" aria-labelledby="fs-difference-title"><h2 id="fs-difference-title">{t('聊天记录已经有了，<br>为什么还需要 PAIA？','You have chat history.<br>Why keep your own archive?')}</h2><div><p>{t('因为你要找的，有时不是某次对话，而是自己当时终于说清楚的那件事。','Sometimes you’re not looking for a conversation. You’re looking for the moment you finally said what you meant.')}</p><p class="fs-secondary">{t('从获准保存的用户输入出发：保留原始来源，修改工作文字，按自己的主题持续积累。不是再存一份 AI 的回答。','Start with the user inputs you authorize: keep their original sources, edit your working text, and develop personal topics over time. Not another collection of AI’s answers.')}</p></div></section>'''
    story=f'''<section class="fs-story wrap" id="thought-library" aria-labelledby="fs-story-title"><div class="fs-story-heading"><div><p class="eyebrow">{t('一个虚构的小计划，一种真实的用法','A FICTIONAL PROJECT. A PRACTICAL USE.')}</p><h2 id="fs-story-title">{t('想做的事情，<br>比一个聊天窗口长。','A project lasts longer<br>than a single chat.')}</h2></div><p>{t('八月，想给家人做一本食谱。九月，终于开始写第一道菜。散落在不同对话里的决定，不必再从头想一次。','In August, an idea for a family cookbook. In September, the first page. Decisions scattered across conversations don’t have to be made all over again.')}</p></div><div class="fs-story-layout"><div class="fs-story-aside"><span class="fs-story-number" aria-hidden="true">01 / 02</span><h3>{t('把“我想怎么做”，<br>留成可以继续的内容。','Keep your approach.<br>Keep developing it.')}</h3><p>{t('这不是 AI 对你的总结。这里是你自己的原话，放进亲自建立的主题和章节，按原来的意思连续读下去。','This is not an AI summary of you. These are your own words, read continuously in topics and sections you made yourself.')}</p><div class="fs-human-note"><span>{t('人工组织','HUMAN ORGANIZATION')}</span><p>{t('“想留住什么”和“开始做这本书”都是示例用户建立的章节。','“What I want to keep” and “Making the book” are sections created by the example person.')}</p></div>{a('demo.html',t('在完整演示里，试着编辑和找回','Try editing and retrieval in the full demo'),'text-link', '#thought-library')}<details class="fs-ai-note"><summary>{t('受控 AI 整理能做什么？','Where does controlled AI organization fit?')}</summary><p>{t('正式规划允许在合格内容和处理授权范围内整理主题或生成阅读呈现，但不能覆盖你的修改、命名和组织决定。真实 AI 服务尚未开放；这里仅展示人工组织。','The approved plan allows organization and derivative reading within eligible, authorized processing scopes. It cannot override your edits, names or organization decisions. The real AI service is not available yet; this view is manually organized.')}</p></details></div><div class="fs-topic-window"><header><span>{icon('topic','mini-icon')}{t('思想库','Thought Library')}</span><span>{t('已打开的个人主题 · 虚构数据','SELECTED PERSONAL TOPIC · FICTIONAL DATA')}</span></header><div class="fs-topic-paper"><p class="fs-topic-back">← {t('我的主题','My topics')}</p><h3>{title(t)}</h3><section><h4>{t('想留住什么','What I want to keep')}</h4>{entry(data[0])}{entry(data[2])}</section><section><h4>{t('开始做这本书','Making the book')}</h4>{entry(data[1])}{entry(data[3])}</section><div class="fs-use-moment"><p>{t('下一页怎么写？先把最初这句带上。','Ready for the next page? Bring that first intention with you.')}</p><a class="text-link" href="#prompt-reuse" data-story-reuse="a">{t('用上“妈妈的原话”这句','Use the words about Mum’s voice')} <span aria-hidden="true">↗</span></a></div></div></div></div></section>'''
    reuse=f'''<section class="fs-reuse" id="prompt-reuse" aria-labelledby="fs-reuse-title"><div class="wrap fs-reuse-layout"><div><p class="eyebrow">{t('积累真正派上用场的那一刻','THE MOMENT YOUR ARCHIVE HELPS')}</p><h2 id="fs-reuse-title">{t('下一次开口，<br>已经有了自己的起点。','Your next conversation.<br>With your own starting point.')}</h2><p>{t('不用重新解释这本食谱为什么重要。在 ChatGPT 旁找回那句话，核对完整内容，填进新的输入。原来的草稿还在，消息不会自动发送。','You don’t have to explain again why the cookbook matters. Find that sentence beside ChatGPT, inspect it, and insert it into your next input. Existing draft text stays; nothing sends automatically.')}</p><p class="fs-invite-try">{t('点开右侧浮球，或从上方主题带一句话过来。','Open the orb, or bring a sentence from the topic above.')}</p><p class="fs-availability-note">{t('v4 获批设计示例；扩展尚未实施此浮板。免费复用不依赖 Pro。Pro AI 推荐、真实 AI 连接与云同步尚未开放。','Approved v4 design illustration; this board is not yet implemented in the extension. Free reuse does not require Pro. Pro AI recommendations, real AI connections and cloud sync are not available yet.')}</p>{a('demo.html',t('完整演示：查找、编辑、复用与权限','Full demo: find, edit, reuse and permissions'),'text-link')}</div>{narrow_board(t,ctl)}</div></section>'''
    privacy=f'''<section class="fs-privacy wrap" id="personal-context" aria-labelledby="fs-privacy-title"><div><p class="eyebrow">{t('留给自己，不等于交给 AI','SAVED FOR YOU. NOT AUTOMATICALLY SHARED.')}</p><h2 id="fs-privacy-title">{t('留下多少，<br>不代表开放多少。','Keep your words.<br>Keep control of access.')}</h2></div><div><p>{t('AI Context 将个人信息、规则、近况和允许读取的主题分开管理。首次使用时，全局、卡片和新主题都关闭；不会因为你保存了内容就自动授权。','AI Context separates your information, rules, current work and topics open for reading. Global access, cards and new topics start closed. Saving content is not permission to share it.')}</p><p class="fs-secondary">{t('你可以先使用本地的保存、查找、编辑和手动复用。真实外部连接仍待开放，本站也不读取或发送你的档案。','Local capture, retrieval, editing and manual reuse do not need a live AI connection. Real external connections are still pending; this website does not read or send your archive.')}</p>{a('demo.html',t('亲手试试：只开放一个主题','Try allowing just one topic'),'text-link','#personal-context')}{a('status.html',t('查看当前可用范围','See current availability'),'text-link')}</div></section>'''
    questions=[(t('ChatGPT 本身不是也能搜索历史吗？','Doesn’t ChatGPT already search history?'),t('能。如果只是偶尔找回某次对话，原生历史可能已经够用。PAIA 的重点是把你自己的输入保留为可编辑、可按个人主题积累、可继续复用的内容，而不是再造一个聊天搜索框。','Yes. For an occasional conversation lookup, native history may be enough. PAIA focuses on your own inputs as editable material that you can organize into personal topics and reuse—not another chat search box.')),(t('和笔记、提示词管理器有什么不同？','How is this different from notes or a prompt manager?'),t('笔记适合主动写下来的内容，提示词管理器适合已经整理好的模板。PAIA 从支持范围内、经你授权保存的用户输入开始，把还没有整理成文的表达也留下来，并保留来源。','Notes suit material you deliberately write down; prompt managers suit reusable templates. PAIA starts with supported user inputs you authorize it to save, preserving the source of expressions that have not yet become finished notes.')),(t('现在能安装使用吗？','Can I install it now?'),t('网页演示现在就能操作，无需邮箱或安装。扩展为桌面 Chrome 和 ChatGPT 网页版的邀请制测试；申请不等于立即获邀。获邀时会说明具体版本与限制，不包含尚未开放的 AI、Pro 推荐或云同步服务。','The web demo works without an email address or installation. The extension is an invite-only test for desktop Chrome and ChatGPT Web; applying does not guarantee an invitation. An invitation includes the specific build and limitations, without promising unavailable AI, Pro recommendations or cloud sync.'))]
    faq='<section class="fs-faq wrap" aria-label="'+t('常见问题','Common questions')+'">'+''.join(f'<details><summary>{q}</summary><p>{answer}</p></details>' for q,answer in questions)+'</section>'
    close=f'''<section class="core-close" data-close-brand><div class="core-close-inner wrap"><div><p class="eyebrow">{t('下一次，不必重新想一遍','NEXT TIME, DON’T START OVER')}</p><h2>{t('你已经说清楚的，<br>值得留下来。','You found the words.<br>Keep them useful.')}</h2><p>{t('先用虚构数据，看看自己的表达如何被找回和复用。再决定 PAIA 是否适合你正在做的事。','Try finding and reusing the fictional words first. Then decide whether PAIA belongs in your own work.')}</p><div class="actions">{button('demo.html',t('试用交互演示','Try the interactive demo'))}{a('beta.html',t('申请内测','Request beta access'),'text-link')}</div><p class="fs-close-scope">{t('桌面 Chrome · ChatGPT · 邀请制测试','Desktop Chrome · ChatGPT · Invite-only beta')}</p></div><div class="core-close-mark"><img src="/assets/website/brand/paia-logo-v1.webp" width="480" height="480" alt="PAIA" loading="lazy" decoding="async"></div></div></section>'''
    return '<div class="flagship-home">'+difference+story+reuse+privacy+faq+close+'</div>'
