"""Designed public journeys, using fictional examples and approved product scope."""
from home import icon


def render_pages(t, a, button, invitation):
    def intro(kicker, title, body='', extra='', cls=''):
        return f'''<section class="nr-intro wrap {cls}"><div><p class="eyebrow">{kicker}</p><h1>{title}</h1></div><div class="nr-intro-aside">{f'<p class="lead">{body}</p>' if body else ''}{extra}</div></section>'''

    def window_bar(title, detail=''):
        return f'<div class="nr-window-bar"><span class="nr-window-mark" aria-hidden="true"></span><strong>{title}</strong><span>{detail}</span></div>'

    def sample_caption(label):
        return f'<figcaption class="nr-scene-caption"><span class="nr-caption-line" aria-hidden="true"></span>{label}</figcaption>'

    pages = []
    steps = [
        ('capture', t('留下', 'Capture')),
        ('archive', t('找回', 'Find')),
        ('thought', t('积累', 'Organize')),
        ('prompt', t('复用', 'Reuse')),
        ('context', t('接续', 'Continue')),
    ]
    how = intro(t('如何使用', 'HOW PAIA WORKS'), t('一句话，<br>不只用一次。', 'One thought.<br>More than one moment.'), t('照常与 AI 对话。让已经说过的话，有自己的位置，也有继续生长的方式。', 'Keep talking with AI. Give the words you have already shared a place to stay, and a way to grow.'), a('demo.html', t('直接体验产品示例', 'Try the interactive example'), 'text-link'))
    how += f'''<div class="nr-process-top wrap"><nav class="nr-process-index" aria-label="{t('使用步骤', 'The five steps')}">{''.join(f'<a href="#{slug}"><span>0{i + 1}</span><strong>{label}</strong><span aria-hidden="true">↗</span></a>' for i, (slug, label) in enumerate(steps))}</nav><p class="nr-scope">{t('以下展示正式计划的完整体验。当前为 Chrome / ChatGPT 邀请制内测。', 'The complete experience in the approved plan. Currently an invite-only Chrome / ChatGPT beta.')} {a('status.html', t('查看可用范围', 'View availability'))}</p></div>'''

    capture = f'''<figure class="nr-scene nr-scene-capture" data-reveal><div class="nr-window nr-capture-window">{window_bar('ChatGPT', t('示例会话', 'Example conversation'))}<div class="nr-conversation"><span class="nr-ui-label">{t('产品的第一步', 'A product’s first step')}</span><p class="nr-chat-message">{t('第一版先帮创作者找回自己的素材。生成更多内容，可以以后再说。', 'Start by helping creators find their own material. Generating more content can wait.')}</p><div class="nr-chat-response" aria-hidden="true"><span></span><span></span><span></span></div></div></div><div class="nr-capture-slip"><span class="nr-slip-icon">{icon('collect', 'mini-icon')}</span><div><strong>{t('留在 Input Archive', 'Kept in Input Archive')}</strong><span>{t('你的原话 · 来源 · 时间', 'Your words · Source · Time')}</span></div><span aria-hidden="true">↗</span></div>{sample_caption(t('界面示意 · 只保存已开启采集的受支持输入', 'Interface illustration · Capture applies only when enabled and supported'))}</figure>'''
    archive = f'''<figure class="nr-scene nr-scene-archive" data-reveal><div class="nr-window nr-reader-window">{window_bar('Input Archive', t('示例', 'Example'))}<div class="nr-reader"><div class="nr-reader-source"><span>ChatGPT</span><span>{t('产品探索 / 第一版', 'Product exploration / First release')}</span></div><h3>{t('先让自己的素材，<br>重新被找到。', 'Make your own material<br>findable again.')}</h3><p>{t('第一版先帮创作者找回自己的素材。', 'Start by helping creators find their own material.')}</p><p><mark>{t('生成更多内容，可以以后再说。', 'Generating more content can wait.')}</mark></p><details class="nr-source-detail"><summary>{t('核对这条输入的原话', 'Check the original input')} <span aria-hidden="true">+</span></summary><p>{t('“第一版先帮创作者找回自己的素材。生成更多内容，可以以后再说。”', '“Start by helping creators find their own material. Generating more content can wait.”')}</p><span>{t('虚构来源 · 示例会话', 'Fictional source · Example conversation')}</span></details></div></div>{sample_caption(t('找回一条输入，接上完整语境', 'Return to one input, with its context intact'))}</figure>'''
    thought = f'''<figure class="nr-scene nr-scene-thought" data-reveal><div class="nr-thought-overview-state"><p class="nr-ui-label">{t('主题概览 · 示例', 'TOPIC OVERVIEW · EXAMPLE')}</p><div class="nr-topic-overview"><div class="nr-topic-title"><h3>{t('产品的第一步', 'A product’s first step')}</h3></div><div class="nr-section-links"><a href="#how-thought-question">{t('问题与真实需求', 'The problem and the need')}</a><a href="#how-thought-boundaries">{t('第一版的边界', 'Boundaries for a first release')}</a></div></div></div><div class="nr-thought-reader-state"><p class="nr-ui-label">{t('同一主题 · 连续阅读局部', 'THE SAME TOPIC · CONTINUOUS READING DETAIL')}</p><div class="nr-window nr-thought-window">{window_bar('Thought Library', t('当前主题', 'Current topic'))}<div class="nr-topic-reader"><h3>{t('产品的第一步', 'A product’s first step')}</h3><section id="how-thought-question"><h4>{t('问题与真实需求', 'The problem and the need')}</h4><p>{t('先帮创作者找回自己的素材。让下一次任务，可以接上以前的积累。', 'Help creators find their own material, so their next task can build on earlier work.')}</p></section><section id="how-thought-boundaries"><h4>{t('第一版的边界', 'Boundaries for a first release')}</h4><p>{t('先验证素材找回，暂不做多人协作。', 'Validate retrieval first. Leave collaboration out.')}</p></section></div></div></div>{sample_caption(t('主题概览与同一主题的连续阅读 · 虚构界面示意', 'Topic overview and continuous reading in the same topic · Fictional illustration'))}</figure>'''
    chosen_prompt = t('给出最强的反例和遗漏变量。', 'Give the strongest counterexample and missing variables.')
    prompt = f'''<figure class="nr-scene nr-scene-prompt" data-reveal><div class="nr-prompt-sheet"><div class="nr-prompt-sheet-header"><span class="nr-ui-label">{t('下一次对话', 'YOUR NEXT CONVERSATION')}</span><span aria-hidden="true">↗</span></div><p>{t('请评估这个产品方向。', 'Please evaluate this product direction.')}</p><div class="nr-prompt-insertion">{chosen_prompt}</div><span class="nr-ui-label">{t('填入后，仍由你检查并发送', 'Review it. Send it yourself.')}</span></div><div class="nr-prompt-palette" role="group" aria-label="{t('个人提示词示意', 'Personal prompt illustration')}"><div class="nr-prompt-choice nr-prompt-chosen"><span>{chosen_prompt}</span><span aria-hidden="true">↗</span></div><div class="nr-prompt-choice"><span>{t('先说明判断依据，再给出结论。', 'Explain the reasoning before giving your conclusion.')}</span></div><div class="nr-prompt-choice"><span>{t('请把下一步拆成可以执行的具体动作。', 'Break the next step into concrete actions I can take.')}</span></div></div>{sample_caption(t('个人提示词示意 · 不会自动发送', 'Personal prompt illustration · Never sends automatically'))}</figure>'''
    card_data = [
        (t('我的信息', 'My Information'), t('你希望 AI 了解的背景。', 'Background you want AI to know.')),
        (t('我的规则', 'My Rules'), t('你希望它如何回应。', 'How you want it to respond.')),
        (t('我的现在', 'My Now'), t('眼下的工作与变化。', 'Your current work and changes.')),
        (t('我的输入', 'My Inputs'), t('允许深入读取的主题。', 'Topics open for deeper reading.')),
    ]
    context = f'''<figure class="nr-scene nr-scene-context" data-reveal><div class="nr-context-frame"><div class="nr-context-heading"><strong>AI Context</strong><span class="nr-authorized"><i aria-hidden="true"></i>{t('示例已授权', 'Authorized in this example')}</span></div><div class="nr-context-cards">{''.join(f'<div class="nr-context-card"><div><span class="nr-card-number">{t("1 条内容", "1 item") if i < 3 else t("1 个主题已开放", "1 topic open")}</span><span class="nr-permission-mark" role="img" aria-label="{t("示例中已允许", "Allowed in this example")}">✓</span></div><h3>{label}</h3><p>{copy}</p></div>' for i, (label, copy) in enumerate(card_data))}</div><p class="nr-context-foot">{t('示例无真实连接 · 真实访问默认关闭', 'No real connection · Real access starts off')}</p></div>{sample_caption(t('四张独立卡片 · 真实外部 AI 连接仍在开发', 'Four independent cards · Live external AI connections are in development'))}</figure>'''
    flow = [
        ('capture', '01', t('留下你已经<br>说过的话。', 'Keep the words<br>you already share.'), t('获邀安装后，主动开启保存。PAIA 留下受支持 ChatGPT 页面中已发送的用户文字，连同来源和时间。', 'After installing your invited build, turn on capture. PAIA keeps sent user text from supported ChatGPT pages, together with its source and time.'), t('可以暂停保存。导入官方历史文件，是另一次主动操作。', 'Pause whenever you need. Importing an official history file is a separate choice.'), capture),
        ('archive', '02', t('找到那句话，<br>也找到当时的自己。', 'Find the sentence.<br>Remember the context.'), t('按来源、会话或关键词找回输入，展开连续阅读。可以修订工作文字，也能核对最初的表达。', 'Find inputs by source, conversation or keyword, then read continuously. Revise your working text while keeping the original available.'), t('重复指令可以暂时从阅读中过滤。过滤不会删除原话。', 'Filter repeated instructions from reading without deleting the source.'), archive),
        ('thought', '03', t('让同一个问题，<br>跨过许多次对话。', 'Let one question<br>span many conversations.'), t('围绕个人主题安排章节，把相关内容放在一起。命名、排列、修改和排除，始终由你掌握。', 'Create sections within personal topics and bring related material together. Your names, order, edits and exclusions stay in your hands.'), t('计划中的 AI 整理提供三种衍生阅读方式，不覆盖原文。', 'Planned AI organization offers three derived reading styles without replacing the source.'), thought),
        ('prompt', '04', t('自己的好表达，<br>随手再用。', 'Your useful phrases.<br>Always within reach.'), t('修改、固定和排列常用提示词。下一次用 AI 时，选择一条填入输入框，再按当前任务调整。', 'Edit, pin and arrange your personal prompts. In your next AI conversation, choose one to fill the composer and adapt it to the task.'), t('已有草稿保留；最后一步发送，仍然属于你。', 'Your existing draft stays. Sending is always your action.'), prompt),
        ('context', '05', t('继续时，<br>让背景跟得上。', 'When you move on,<br>let context keep up.'), t('用四张卡片管理背景、规则、近况和允许读取的主题。真实连接可用后，获准的 AI 可以按需读取。', 'Use four cards for your background, rules, current context and allowed topics. Once live connections are available, authorized AI can read when needed.'), t('真实访问默认关闭。你决定开放范围，也可以暂停之后的读取。', 'Real access starts off. You set the scope and can pause future reads.'), context),
    ]
    how += '<div class="nr-process wrap">' + ''.join(f'''<section id="{slug}" class="nr-process-step nr-step-{slug}"><div class="nr-step-copy" data-reveal><span class="nr-step-number">{num}</span><h2>{title}</h2><p>{copy}</p><p class="nr-step-note">{note}</p></div>{visual}</section>''' for slug, num, title, copy, note, visual in flow) + '</div>' + invitation()
    pages.append(('how-it-works.html', t('PAIA — 如何使用', 'PAIA — How it works'), t('从留下输入，到找回原话、个人主题、提示词复用和四卡 Context。', 'From capture to retrieval, personal topics, prompt reuse and four-card Context.'), how))

    use = intro(t('使用场景', 'WAYS TO USE PAIA'), t('这一次，<br>从已有的积累开始。', 'This time,<br>start with what you know.'), t('一个项目，一个问题，一次选择。真正重要的事情，往往需要不止一次对话。', 'A project, a question, a decision. The things that matter rarely fit into a single conversation.'), f'<p class="nr-scope">{t("以下情景均为虚构示例。", "The following scenarios are fictional illustrations.")}</p>', 'nr-use-intro')
    cases = [
        ('project', '01', t('一个长期项目', 'AN ONGOING PROJECT'), t('边界记得住，<br>下一版才走得远。', 'Keep the boundaries.<br>Move the work forward.'), t('不必重新解释目标，也不必再次讨论已经放弃的方向。找到当时的决定，在新的任务里继续。', 'Keep the goal in view without explaining discarded options again. Recover the earlier decision and build on it.'), t('之前已经想清楚的', 'WHAT YOU ALREADY WORKED OUT'), t('第一版只验证素材找回。<br>面向独立创作者。<br>暂不做多人协作。', 'Validate retrieval in the first release.<br>For independent creators.<br>No collaboration features yet.'), t('下一次可以这样问', 'YOUR NEXT QUESTION'), t('在这些边界内，下一版最值得验证什么？', 'Within these boundaries, what should the next release test?'), t('Input Archive 找回决定；Thought Library 把项目放在一起。', 'Recover the decision in Input Archive. Keep the project together in Thought Library.')),
        ('research', '02', t('一个研究问题', 'A RESEARCH QUESTION'), t('接上推理，<br>保留每一步的条件。', 'Continue the reasoning.<br>Keep its conditions.'), t('找回先前的问题、假设和未解之处。引用是引用，试探是试探，自己的判断仍能回到来源核对。', 'Recover earlier questions, assumptions and open problems. Keep quotations and experiments distinct from your conclusions, with sources close at hand.'), t('先前留下的问题', 'THE QUESTION YOU KEPT'), t('这个结论依赖哪些假设？<br>哪一步仍然没有被验证？', 'Which assumptions does this conclusion depend on?<br>Which step is still untested?'), t('下一次可以这样问', 'YOUR NEXT QUESTION'), t('如果改变第二个假设，推理会从哪里开始不同？', 'If the second assumption changes, where does the reasoning begin to differ?'), t('沿主题连续阅读；需要时，回到那条原始输入。', 'Read continuously within a topic. Return to the original input when needed.')),
        ('decision', '03', t('一次重要选择', 'AN IMPORTANT DECISION'), t('新的信息，<br>值得一次新的判断。', 'New information.<br>A fresh point of view.'), t('过去的表达带着当时的背景。对照以前的限制与现在的变化，让选择跟上自己。', 'Your earlier words carry the circumstances of that moment. Compare the old constraints with what has changed, so your decision can change too.'), t('曾经的考虑', 'WHAT MATTERED THEN'), t('城市是首要条件。<br>也希望工作留下学习空间。', 'Location comes first.<br>The work should leave room to learn.'), t('现在重新比较', 'LOOK AT IT AGAIN'), t('工作内容更重要了。用更新后的条件，再比较这两个选择。', 'The work itself matters more now. Compare these two options using the updated priorities.'), t('修改自己的工作内容；AI Context 中的近况也可独立更新。', 'Revise your working content. Update current context independently in AI Context.')),
    ]
    use += '<div class="nr-case-list wrap">'
    for slug, num, kicker, title, copy, before_label, before, after_label, after, connection in cases:
        use += f'''<section class="nr-case nr-case-{slug}"><header class="nr-case-header" data-reveal><div><span class="nr-case-number">{num}</span><p class="eyebrow">{kicker}</p></div><h2>{title}</h2><p>{copy}</p></header><div class="nr-case-story" data-reveal><div class="nr-case-past"><span class="nr-ui-label">{before_label}</span><blockquote>{before}</blockquote><div class="nr-source-line"><span aria-hidden="true"></span>{t('来自你保留的输入 · 虚构示例', 'From your saved inputs · Fictional example')}</div></div><div class="nr-case-transition" aria-hidden="true"><span></span>↗<span></span></div><div class="nr-case-next"><span class="nr-ui-label">{after_label}</span><p>{after}</p><span class="nr-composer-mark" aria-hidden="true">↑</span></div></div><footer class="nr-case-footer"><p>{connection}</p>{a('demo.html', t('亲自试一试', 'Explore an example'), 'text-link')}</footer></section>'''
    use += '</div>' + invitation()
    pages.append(('use-cases.html', t('PAIA — 使用场景', 'PAIA — Use cases'), t('让长期项目、研究与重要选择，接上自己的积累。', 'Bring your accumulated thinking into projects, research and important decisions.'), use))

    articles = [
        ('context', '01', t('关于积累', 'ON CONTINUITY'), t('聊天历史之外，<br>还需要什么？', 'What do you need<br>beyond chat history?'), t('留下说过的话，也留下管理和再次使用它们的能力。', 'Keep what you said, and the ability to manage and use it again.'), t('对话会结束。<br>你的思考不必结束。', 'A conversation ends.<br>Your thinking can continue.'), [
            (t('找到原话，而不是重新猜一次。', 'Return to your words.'), t('一次对话包含问题、试探、引用和后来放弃的方向。PAIA 从你自己的输入出发，保留来源与时间，让你回到具体的一句话，再修订工作版本。', 'A conversation contains questions, experiments, quotations and abandoned directions. PAIA starts from your own inputs and keeps their source and time. Return to a particular sentence, then revise its working version.'), t('摘要可以帮助理解，却不该成为所有原话唯一的替代品。需要核对时，原始表达仍然重要。', 'A summary can help you understand. It should not become the only replacement for all your words. The original expression still matters when you need to check.')),
            (t('对话会结束，主题可以继续。', 'A conversation ends. A topic can continue.'), t('同一个项目可能分散在许多会话里。个人主题与章节把它们放在一处，让先前的决定、仍待验证的问题和新的材料能够连续阅读。', 'A project may run through many conversations. Personal topics and sections bring it together, so earlier decisions, open questions and new material can be read continuously.'), t('你的命名、排列、修改和排除始终优先。AI 整理是在这些内容之上的阅读帮助，而不是另一份不可修改的结论。', 'Your names, order, edits and exclusions take priority. AI organization is a reading aid over that material, not another unchangeable conclusion.')),
            (t('保存与允许读取，是两次选择。', 'Keeping and allowing access are separate choices.'), t('Context 的我的信息、我的规则、我的现在和我的输入，把背景与允许范围放在明处。真实连接可用后，AI 才能按获准范围按需读取。', 'My Information, My Rules, My Now and My Inputs make your background and reading permissions explicit. Once real connections are available, AI can read on demand within the allowed scope.'), t('安装或保存本身不会自动开放整个档案。真实 AI 整理与外部连接仍在开发，官网展示的是正式计划的目标体验。', 'Installation or capture does not open the whole archive. Live AI organization and external connections are still in development; the website illustrates the experience in the approved plan.')),
        ]),
        ('beliefs', '02', t('关于表达', 'ON EXPRESSION'), t('发给 AI 的，<br>不一定是你的观点。', 'Not every input<br>is a belief.'), t('引用、试探和任务指令，都需要保留各自的语境。', 'Quotations, experiments and instructions need their own context.'), t('你说过什么，<br>不等于你永远相信什么。', 'What you once said<br>is not all you believe.'), [
            (t('输入里有多种声音。', 'An input can contain several voices.'), t('你可能把一份岗位说明、一段待改写文字或一个假设发给 AI。这能证明你发送过这些文字，但不能证明每句话都是你的长期立场。', 'You might send AI a job description, a draft to rewrite or a hypothetical argument. The record establishes that you sent those words. It does not establish that every sentence is a lasting belief.'), t('所以，保存表达也需要保存语境：文字来自哪里、为何被提出，以及哪些只是有待讨论的可能性。', 'Keeping an expression also means keeping its context: where it came from, why it was raised, and what was only a possibility to discuss.')),
            (t('整理要能够回到来源。', 'Organization must stay traceable.'), t('原话优先、平衡整理和更加概括，改变的是衍生阅读方式。无论哪一种，都需要保留条件、立场与不确定性，并能回到来源核对。', 'Original-first, Balanced and More concise change the derived reading view. Each must preserve conditions, perspective and uncertainty, and remain traceable to sources.'), t('AI 不应替你发明观点，也不应因为概括得更顺畅，就删去原本关键的限制条件。真实 AI 整理服务仍在开发。', 'AI should not invent a position for you or remove a crucial condition for the sake of a smoother summary. The live AI organization service is still in development.')),
            (t('当前选择仍然属于你。', 'The current choice still belongs to you.'), t('过去说过的话不一定适用于现在。你可以修改工作内容、管理主题，以及关闭 AI 访问。', 'Past words may no longer apply. You can revise working content, manage topics and close AI access.'), t('让旧表达成为可参考的材料，不让它自动变成对未来行为的授权。这是个人积累应有的边界。', 'Let an earlier expression become useful reference material, without making it automatic permission for a future action. A personal archive should keep that boundary clear.')),
        ]),
        ('reuse', '03', t('关于复用', 'ON REUSE'), t('自己的常用说法，<br>应该就在手边。', 'Keep your useful<br>phrases close.'), t('不用一次次翻旧聊天，也不替你自动发送。', 'Less searching through old chats. Sending stays with you.'), t('不是重新说一遍。<br>是接着说下去。', 'Less starting again.<br>More moving forward.'), [
            (t('复用已经适合自己的表达。', 'Reuse expressions that suit your work.'), t('反复使用的分析要求、写作标准或追问方式，是你自己的工作习惯。PAIA 的个人提示词围绕这些真实表达组织，把相似说法放在一起。', 'Repeated analysis requests, writing standards and follow-up questions are part of your own practice. PAIA organizes personal prompts around those expressions and related wordings.'), t('不必先挑选一套公共模板。自己已经用得顺手的说法，就是一个足够好的起点。', 'You do not need to begin with a public template collection. A phrase that already works for you is a useful starting point.')),
            (t('表达可以跟着工作改变。', 'Let your phrases change with your work.'), t('你可以改写、固定、排序或隐藏自己的提示词。下一次点选填入 AI 输入框，检查和修改后再发送。', 'Rewrite, pin, reorder or hide your prompts. Next time, choose one to fill the AI composer, review or edit it, then send.'), t('已有草稿保留。提示词库不会替你点击发送，也不会把旧指令当作新的执行许可。', 'Your existing draft stays. The prompt library does not send on your behalf or turn an old instruction into fresh execution authority.')),
            (t('请求与背景，各有位置。', 'Your request and your background have their own place.'), t('个人提示词帮助你更快表达当前请求；四卡 Context 管理你允许连接的 AI 按需了解的背景和主题。', 'Personal prompts help you express the current request. Four-card Context manages the background and topics a connected AI may read when needed.'), t('它们互相补充，不要求你每次复制整段历史。真实 Context 连接仍在开发，本地提示词能力以获邀版本为准。', 'They complement one another without asking you to copy an entire history. Real Context connections are still in development. Local prompt availability depends on the invited build.')),
        ]),
    ]

    def editorial_art(slug):
        if slug == 'context':
            words = [t('一次对话', 'A conversation'), t('一个主题', 'A topic'), t('持续的思考', 'Ongoing thought')]
        elif slug == 'beliefs':
            words = [t('“假如……”', '“What if…”'), t('“有人说……”', '“Someone said…”'), t('“我认为……”', '“I think…”')]
        else:
            words = [t('给出反例。', 'Find the counterexample.'), t('说明依据。', 'Show the reasoning.'), t('接着说下去。', 'Keep thinking.')]
        sheets = ''.join(f'<span class="nr-art-sheet nr-art-sheet-{i + 1}"><i>0{i + 1}</i><strong>{word}</strong></span>' for i, word in enumerate(words))
        return f'<div class="nr-editorial-art nr-art-{slug}" aria-hidden="true"><div class="nr-editorial-axis"></div>{sheets}</div>'

    blog = intro(t('产品文章', 'NOTES FROM PAIA'), t('关于表达。<br>关于积累。<br><span>关于下一步。</span>', 'On expression.<br>On continuity.<br><span>On what comes next.</span>'), t('几个简单的原则，决定了 PAIA 如何对待你的文字。', 'A few simple principles shape the way PAIA treats your words.'), cls='nr-journal-intro')
    blog += '<section class="nr-journal wrap" aria-label="' + t('产品文章', 'Product notes') + '">'
    for slug, num, topic, title, summary, pull, sections in articles:
        label = f'<div class="nr-journal-copy"><div class="nr-journal-meta"><span>{num}</span><span>{topic}</span></div><h2>{title}</h2><p>{summary}</p><span class="nr-read-link">{t("阅读全文", "Read the note")} <span aria-hidden="true">↗</span></span></div>{editorial_art(slug)}'
        blog += a('article-' + slug + '.html', label, 'nr-journal-entry nr-journal-' + slug)
    blog += '</section>'
    pages.append(('blog.html', t('PAIA — 产品文章', 'PAIA — Product notes'), t('关于个人表达、上下文与复用的产品思考。', 'Product notes on personal expression, context and reuse.'), blog))

    for index, (slug, num, topic, title, summary, pull, sections) in enumerate(articles):
        body = f'''<header class="nr-article-header wrap"><div class="nr-article-label">{a('blog.html', t('产品文章', 'Product notes'))}<span aria-hidden="true">/</span><span>{num} · {topic}</span></div><h1>{title}</h1><p class="lead">{summary}</p>{editorial_art(slug)}</header><div class="nr-article-layout wrap"><aside class="nr-article-aside"><p class="nr-ui-label">{t('本篇内容', 'IN THIS NOTE')}</p><nav aria-label="{t('文章目录', 'Article contents')}">{''.join(f'<a href="#section-{i + 1}"><span>0{i + 1}</span>{heading}</a>' for i, (heading, _, _) in enumerate(sections))}</nav>{a('demo.html', t('体验产品示例', 'Explore the example'), 'text-link')}</aside><article class="nr-article-body">'''
        for i, (heading, paragraph, second) in enumerate(sections):
            body += f'<section id="section-{i + 1}" data-reveal><span class="nr-article-section-number">0{i + 1}</span><h2>{heading}</h2><p>{paragraph}</p><p>{second}</p></section>'
            if i == 0:
                body += f'<blockquote class="nr-pullquote" data-reveal><span aria-hidden="true">“</span><p>{pull}</p></blockquote>'
        next_article = articles[(index + 1) % len(articles)]
        body += f'''<nav class="nr-article-next" aria-label="{t('继续阅读', 'Continue reading')}"><span class="nr-ui-label">{t('下一篇', 'NEXT NOTE')}</span>{a('article-' + next_article[0] + '.html', f'<strong>{next_article[3]}</strong><span aria-hidden="true">↗</span>')}{a('blog.html', t('查看全部文章', 'All product notes'), 'text-link')}</nav></article></div>'''
        pages.append(('article-' + slug + '.html', 'PAIA — ' + title.replace('<br>', ' ').replace('<br/>', ' '), summary, body))
    return pages
