"""Public explanations of the approved product, its boundaries and availability.

These pages are website illustrations, never extension settings or live clients.
Product authority is recorded in website/PRODUCT_CAPABILITY_MAP.md.
"""
from core import render as render_core
from home import icon


def render_demo(t, a, button):
    return f'''<section class="nr-demo-intro wrap"><div><p class="eyebrow">{t('交互示例', 'THE INTERACTIVE EXAMPLE')}</p><h1>{t('把话接着用。', 'Put your words to work.')}</h1></div><p class="lead">{t('用“给家人的食谱”这组虚构输入，试着编辑工作文字、按主题阅读、找回旧话，再决定允许什么。所有操作只在本页，不调用 AI。', 'Use the fictional family-cookbook inputs to edit working text, read a topic, retrieve old wording and choose what is allowed. Everything stays on this page; no AI is called.')}</p></section><div class="product-demo-page nr-demo-body">{render_core(t, a, button, icon, standalone=True)}</div>'''


def render_trust(t, a, invitation):
    choices = [
        ('01', t('自己的本地档案', 'Your local archive'), t('保存、找回、编辑与手动整理。', 'Capture, find, edit and organize manually.'), 'collect'),
        ('02', t('允许 AI 整理', 'Allow AI organization'), t('按处理许可使用必要材料。', 'Use necessary material with processing permission.'), 'note'),
        ('03', t('允许外部 AI 读取', 'Allow external AI access'), t('分别选择卡片与主题范围。', 'Choose access to cards and topics separately.'), 'connect'),
        ('04', t('同步到自己的云账号', 'Sync to your cloud account'), t('主动开启，同一生态内恢复。', 'Opt in to recovery within the same ecosystem.'), 'reuse'),
    ]
    cards = [
        (t('我的信息', 'My Information'), t('你希望 AI 了解的个人背景。', 'The background you want AI to know.')),
        (t('我的规则', 'My Rules'), t('回答方式与任务边界。', 'Response preferences and task boundaries.')),
        (t('我的现在', 'My Now'), t('当前项目、近况与变化。', 'Current projects, recent context and changes.')),
        (t('我的输入', 'My Inputs'), t('允许深入读取的个人主题。', 'Personal topics allowed for deeper reading.')),
    ]
    choice_markup = ''.join(f'<div class="nr-choice nr-choice-{i}"><div><span>{num}</span>{icon(ico, "mini-icon")}</div><h3>{label}</h3><p>{copy}</p></div>' for i, (num, label, copy, ico) in enumerate(choices))
    return f'''<section class="nr-intro nr-trust-intro wrap"><div><p class="eyebrow">{t('数据与权限', 'YOUR DATA. YOUR CHOICES.')}</p><h1>{t('留下来的，<br>仍然由你掌握。', 'Keep your words.<br>Keep your say.')}</h1></div><div class="nr-intro-aside"><p class="lead">{t('保存、整理、读取与同步，是四个独立的选择。你的档案，不应因为一个开关就向所有地方开放。', 'Keeping, organizing, sharing access and syncing are separate choices. One switch should not open your archive to everything.')}</p>{a('demo.html', t('体验四卡访问范围', 'Explore the four-card controls'), 'text-link')}</div></section>
<section class="nr-choice-map wrap" aria-label="{t('四个独立的数据选择', 'Four independent data choices')}" data-reveal><div class="nr-choice-map-heading"><span class="nr-ui-label">{t('四种选择，不互相代替', 'FOUR CHOICES. SEPARATE PERMISSIONS.')}</span><p>{t('AI 服务、真实连接与云同步仍在开发。', 'AI services, real connections and cloud sync are still in development.')}</p></div><div class="nr-choice-grid">{choice_markup}</div></section>
<div class="nr-trust-layout wrap"><aside class="nr-article-aside"><p class="nr-ui-label">{t('本页内容', 'ON THIS PAGE')}</p><nav aria-label="{t('数据与权限目录', 'Data and permissions contents')}"><a href="#local"><span>01</span>{t('本地与云', 'Local and cloud')}</a><a href="#source"><span>02</span>{t('原话与修改', 'Originals and edits')}</a><a href="#permission"><span>03</span>{t('AI 的允许范围', 'AI permissions')}</a><a href="#recovery"><span>04</span>{t('管理与恢复', 'Management and recovery')}</a><a href="#website"><span>05</span>{t('这个网站', 'This website')}</a></nav></aside>
<article class="nr-trust-body"><section id="local" data-reveal><span class="nr-article-section-number">01</span><h2>{t('日常使用，<br>从本地开始。', 'Everyday use<br>starts locally.')}</h2><p>{t('保存、阅读、查找、工作文字编辑、手动管理 Context 和本地提示词复用，不依赖 PAIA 的远程 AI 服务。', 'Capture, reading, search, working-text edits, manual Context management and local prompt reuse do not depend on PAIA’s remote AI service.')}</p><p>{t('本地优先不等于材料永不离开设备。计划中的 AI 整理与自动维护，在得到相应处理许可后使用必要材料；外部 AI 连接另有读取许可。', 'Local-first does not mean material can never leave your device. Planned AI organization and automatic maintenance use necessary material under processing permission. External AI connections have separate reading permissions.')}</p>
<div class="nr-sync-map"><div><span>Chrome</span><strong>Google Drive</strong></div><div><span>Edge</span><strong>OneDrive</strong></div><div><span>Safari</span><strong>iCloud</strong></div></div><p class="nr-inline-note">{t('可选同步的正式方向是自己的浏览器云账号。主动开启后，可在同一生态的新设备恢复已成功同步的数据；真实传输和恢复仍在开发，不会自动跨生态互通。无需建立 PAIA 内容云账号。', 'Optional sync is planned through your own browser cloud account. Once enabled, a new device in the same ecosystem can restore successfully synced data. Live transfer and recovery remain in development. There is no automatic cross-ecosystem sync or required PAIA content-cloud account.')}</p></section>
<section id="source" data-reveal><span class="nr-article-section-number">02</span><h2>{t('可以改写，<br>也能回到原话。', 'Make an edit.<br>Keep the original in view.')}</h2><p>{t('输入档案保留来源事实，工作文字承接当前修改。普通编辑不会覆盖原始来源。可逆的阅读过滤，也不等于删除或授权。', 'The archive retains source records while working text holds your edits. Ordinary editing does not overwrite the original source. Reversible reading filters are neither deletion nor permission.')}</p><figure class="nr-source-comparison"><div><span class="nr-ui-label">{t('原始记录 · 示例', 'ORIGINAL · EXAMPLE')}</span><p>{t('“先看看哪些功能可能有价值。”', '“Explore which features could be useful.”')}</p></div><div><span class="nr-ui-label">{t('工作版本 · 示例', 'WORKING VERSION · EXAMPLE')}</span><p>{t('“先验证素材找回，暂不做多人协作。”', '“Validate retrieval first. Leave collaboration out.”')}</p></div></figure><p>{t('Thought Library 按个人主题、章节和内容组织。AI 的三种整理方式是衍生阅读：原话优先、平衡整理、更加概括。它应保留来源、条件与不确定性，不能覆盖人工命名、移动、排除或写作。', 'Thought Library uses personal topics, sections and entries. The three AI organization styles are derived reading views: Original-first, Balanced and More concise. They must preserve sources, conditions and uncertainty, without overriding your names, moves, exclusions or writing.')}</p>{a('article-beliefs.html', t('为什么输入不等于个人观点', 'Why an input is not necessarily a belief'), 'text-link')}</section>
<section id="permission" data-reveal><span class="nr-article-section-number">03</span><h2>{t('四张卡片，<br>分别决定。', 'Four cards.<br>Separate controls.')}</h2><div class="nr-permission-cards">{''.join(f'<div><span>0{i + 1}</span><h3>{label}</h3><p>{copy}</p></div>' for i, (label, copy) in enumerate(cards))}</div>
<div class="nr-access-path"><div><span>01</span><strong>{t('总访问', 'Main access')}</strong><span>{t('默认关闭', 'Starts off')}</span></div><div><span>02</span><strong>{t('独立卡片', 'Individual cards')}</strong><span>{t('默认关闭', 'Start off')}</span></div><div><span>03</span><strong>{t('我的输入中的主题', 'Topics in My Inputs')}</strong><span>{t('新主题默认关闭', 'New topics start off')}</span></div></div>
<p>{t('建立连接不会自动打开任何访问。允许后，AI 才能按需读取合格内容；不必每次挑选并导出一份 Context 包。没有开放的主题，不能退回去读取整个输入档案。', 'Connecting an AI does not open access automatically. Once allowed, it may read eligible content on demand, without a Context packet assembled for every task. A closed topic does not grant fallback access to the entire Input Archive.')}</p><details class="nr-details"><summary>{t('暂停或关闭后，会发生什么？', 'What happens when I pause or close access?')}<span aria-hidden="true">+</span></summary><div><p>{t('暂停保留原来的卡片与主题选择，但会阻止之后的读取。撤回不能收回已经交给外部 AI 的内容。', 'Pausing retains your card and topic choices while stopping future reads. Withdrawal cannot recall content already delivered to an external AI.')}</p><p>{t('关闭一个主题只改变该主题的访问。其他卡片中独立保存的内容，仍需分别管理。打开下一级范围，也不会自动打开上一级。', 'Closing a topic changes only that topic’s access. Independent items saved in other cards keep their own controls. Opening a lower scope does not open its parent automatically.')}</p></div></details></section>
<section id="recovery" data-reveal><span class="nr-article-section-number">04</span><h2>{t('每一种管理动作，<br>都有清楚的含义。', 'Every management action<br>has its own meaning.')}</h2><p>{t('过滤、从主题移除、从档案移除和永久删除不是同一件事。来源平台与 PAIA 是各自的副本，一处删除不会自动删除另一处。', 'Filtering, removing a topic placement, removing an archive record and permanent deletion are different actions. PAIA and the source platform hold separate copies; deletion in one does not automatically delete the other.')}</p><p>{t('官方历史文件导入、已有备份文件恢复和故障恢复保留在正式计划中。生成内容导出、生成新备份和 Context 打包分享已不属于当前产品方向。同步也不等于无限期备份。', 'Official history-file import, recovery from existing backup files and failure recovery remain in the product plan. Content exports, generating new backups and packaged Context sharing are not part of the current direction. Sync is not an unlimited backup history.')}</p><p class="nr-inline-note">{t('测试版不应成为重要资料的唯一副本。按获邀版本的说明操作，并保留原平台或其他独立来源。本地存储不代表加密或永久无损保证。', 'The beta should not be the only copy of important material. Follow the instructions for your invited build and retain the original platform or another independent source. Local storage is not an encryption or permanent lossless-storage guarantee.')}</p></section>
<section id="website" data-reveal><span class="nr-article-section-number">05</span><h2>{t('这个网站，<br>不连接你的档案。', 'This website does not<br>connect to your archive.')}</h2><p>{t('没有分析脚本、广告跟踪器或远程字体。产品示例只使用当前页面内存，刷新即清除。', 'There are no analytics scripts, ad trackers or remote fonts. Product examples use current-page memory and clear on reload.')}</p><p>{t('只有主动提交内测申请，表单字段才会通过 FormSubmit 转发至项目邮箱。网站托管与表单服务有各自的数据处理边界。', 'Only submitting the beta application sends form fields through FormSubmit to the project email. Hosting and the form service have their own data-processing boundaries.')}</p>{a('privacy-policy.html', t('阅读隐私政策', 'Read the privacy policy'), 'text-link')}</section></article></div>{invitation()}'''


def render_status(t, a, invitation, statusmini):
    rows = [
        (t('输入档案', 'Input Archive'), t('本地基础', 'LOCAL FOUNDATION'), t('Chrome / ChatGPT 的本地采集、查找、编辑与来源核对已有集成实现。', 'Local Chrome / ChatGPT capture, search, working-text editing and source readback are integrated.')),
        (t('个人提示词', 'Personal prompts'), t('本地基础', 'LOCAL FOUNDATION'), t('常用表达、编辑、固定、排序和手动填入已有实现。默认关闭的本地下一步建议已合入开发版；实际范围以获邀版本和真实站点验证为准。', 'Reusable phrases, editing, pinning, ordering and manual insertion are implemented. Optional local next-step suggestions, off by default, are integrated into development builds. Actual support depends on your invited build and site validation.')),
        (t('思想库','Thought Library'), t('体验完善中', 'EXPERIENCE IN PROGRESS'), t('个人主题与章节阅读已有基础。完整写作、组织和 AI 阅读方式仍在完善。', 'Personal topics and section reading have a foundation. Full writing, organization and AI reading are still being completed.')),
        (t('窄长输入浮板 v4', 'Narrow Input Board v4'), t('已批准 · 未实施', 'APPROVED · NOT IMPLEMENTED'), t('v4 规范已随 PR229 合并。当前执行记录仍未启动 NIB 运行时；官网提供目标交互示例，不代表已安装版本。', 'The v4 specification was merged in PR229. NIB runtime work remains unselected in the current execution record. The website illustrates the target, not your installed version.')),
        (t('四卡 Context', 'Four-card Context'), t('本地基础', 'LOCAL FOUNDATION'), t('本地卡片和手动内容管理已有基础。完整自动维护与真实外部 AI 按需读取尚未开放。', 'Local cards and manual management have a foundation. Full automatic maintenance and live external AI reading are not available.')),
        (t('AI 整理与协助', 'AI organization & assistance'), t('后续计划', 'PLANNED'), t('三种整理方式与用户控制已确定。真实模型服务、质量和费用支持尚未上线。', 'Three reading styles and user controls are approved. Live model services, quality validation and billing support are not launched.')),
        (t('自己的云账号同步', 'Personal cloud sync'), t('后续计划', 'PLANNED'), t('方案已确定，部分本地基础已实现。三种生态的真实云传输与新设备恢复尚未开放。', 'The approach is approved, with part of the local foundation implemented. Live cloud transport and new-device recovery are not available.')),
    ]
    return f'''<section class="nr-intro nr-status-intro wrap"><div><p class="eyebrow">{t('体验与可用范围', 'EXPERIENCE & AVAILABILITY')}</p><h1>{t('看见方向。<br>知道现在能做什么。', 'See where we are going.<br>Know what is here.')}</h1></div><div class="nr-intro-aside"><p class="lead">{t('官网展示正式计划的目标体验。网页示例、邀请制测试与后续能力，在这里分清楚。', 'The website presents the experience in the approved plan. Here is the distinction between the web example, invited builds and what comes next.')}</p>{statusmini()}</div></section>
<section class="nr-availability-paths wrap"><article class="nr-availability nr-available-now" data-reveal><span class="nr-availability-state"><i aria-hidden="true"></i>{t('现在体验', 'TRY NOW')}</span><h2>{t('打开网页，<br>先用一遍。', 'Open the example.<br>Try it for yourself.')}</h2><p>{t('用虚构输入体验查找、编辑、提示词、主题阅读和四卡范围。无需安装，不连接 AI 或私人资料。', 'Try search, edits, prompts, topic reading and four-card scope using fictional inputs. No installation, AI connection or personal data.')}</p>{a('demo.html', t('打开交互示例', 'Open the interactive example') + ' <span aria-hidden="true">→</span>', 'button')}</article><article class="nr-availability nr-beta-available" data-reveal><span class="nr-availability-state"><i aria-hidden="true"></i>{t('邀请制测试', 'INVITE-ONLY BETA')}</span><h2>{t('从 Chrome<br>与 ChatGPT 开始。', 'Start with Chrome<br>and ChatGPT.')}</h2><p>{t('申请后按当前范围邀请。获邀时提供具体版本、安装说明与限制；申请不等于立即安装。', 'Invitations follow the current testing scope. Invited participants receive a specific build, setup instructions and limitations. Applying is not instant installation.')}</p>{a('beta.html', t('申请测试版', 'Request a beta invitation'), 'text-link')}</article></section>
<section class="nr-capabilities wrap"><header class="nr-section-header"><div><p class="eyebrow">{t('目标与进展', 'THE PRODUCT IN PROGRESS')}</p><h2>{t('基础已经建立，<br>完整体验继续生长。', 'The foundation is here.<br>The full experience is growing.')}</h2></div><p>{t('“已有实现”指开发版本中的集成基础，不代表公开商店发布或你已安装的版本。当前没有经过核验的公开安装包或商店下载入口。', '“Implemented” means an integrated foundation in the development version. It does not imply a public store release or availability in your installed build. There is no verified public installer or store download.')}</p></header><div class="nr-capability-list">{''.join(f'<article class="nr-capability-row"><div><span class="nr-capability-number">0{i + 1}</span><h3>{name}</h3></div><span class="nr-capability-state">{state}</span><p>{copy}</p></article>' for i, (name, state, copy) in enumerate(rows))}</div></section>
<section class="nr-source-scope wrap"><div><span class="nr-ui-label">{t('来源与安装', 'SOURCES & INSTALLATION')}</span><h2>{t('从明确支持的范围，<br>一步步向前。', 'Move forward from<br>a clearly supported scope.')}</h2></div><div><p>{t('当前采集面向受支持的 ChatGPT 页面和已发送用户文字。Claude、Gemini 等其他来源仍按后续计划推进。安装不会自动收集全部账号历史、所有 AI 回复、任意网页或草稿。', 'Current capture targets supported ChatGPT pages and sent user text. Other sources, including Claude and Gemini, remain planned. Installation does not automatically collect a complete account history, all AI replies, arbitrary webpages or drafts.')}</p><p>{t('真实来源、设备、签名发行、更新和导入恢复，按各自范围验证。具体可体验什么，以当次邀请中的版本说明为准。', 'Live sources, devices, signed distribution, updates and import recovery need validation within their own scope. The instructions with your invitation determine what you can try.')}</p>{a('principles.html', t('了解数据与权限', 'Read about data and permissions'), 'text-link')}</div></section>
<div class="nr-status-sources wrap"><p>{t('产品依据核对于 2026-10-10（main d516c43）；版本能力不会随这张页面自动更新。', 'Product sources checked 10 October 2026 (main d516c43). This page does not automatically track each development build.')}</p><a href="https://github.com/haohongfei2001-png/paia/blob/main/website/PRODUCT_CAPABILITY_MAP.md" rel="noreferrer">{t('查看产品依据', 'View the product sources')} <span aria-hidden="true">↗</span></a></div>{invitation()}'''


def render_about(t, a, invitation):
    return f'''<section class="nr-about-opening wrap"><p class="eyebrow">{t('为什么是 PAIA', 'WHY PAIA')}</p><h1>{t('你投入过的思考，<br><span>值得留下。</span>', 'The thinking you put in<br><span>deserves a place to stay.</span>')}</h1><div class="nr-about-opening-foot"><span class="nr-about-spelling">Personal AI Input Archive</span><p>{t('一次次对话里，你解释背景、推翻假设、描述自己在意什么。那些表达已经有价值，不该只停留在那一次对话。', 'In conversation after conversation, you explain the background, test assumptions and describe what matters. Those expressions already have value. Give them a life beyond that one chat.')}</p></div></section>
<section class="nr-about-statement wrap" data-reveal><div class="nr-about-strata" aria-hidden="true"><span>Input Archive</span><span>Thought Library</span><span>AI Context</span></div><div><p class="eyebrow">{t('自己的表达，自己的积累', 'YOUR WORDS. YOUR OWN CONTINUITY.')}</p><h2>{t('让过去的表达，<br>参与下一步。', 'Let past expression<br>be part of what comes next.')}</h2><p>{t('Input Archive 留下原话与来源。Thought Library 围绕自己的主题组织持续思考。个人提示词把好用的说法留在手边。AI Context 则让你决定，连接的 AI 可以了解哪些背景与内容。', 'Input Archive keeps your words and their sources. Thought Library organizes ongoing ideas around your topics. Personal prompts keep useful phrases close. AI Context lets you decide what a connected AI may learn about your background and material.')}</p>{a('how-it-works.html', t('看完整的使用方式', 'See how it comes together'), 'text-link')}</div></section>
<section class="nr-about-belief wrap" data-reveal><div><span class="nr-ui-label">{t('我们坚持的边界', 'A BOUNDARY WE KEEP')}</span><h2>{t('帮助你整理，<br>让表达仍然是你的。', 'Help you organize.<br>Keep the expression yours.')}</h2></div><div><p>{t('一段话可能是引用、试探，也可能只是当时的想法。它不应该因为进入一个 AI 系统，就悄悄变成永久的个人画像。', 'A passage may be a quotation, an experiment or simply what you thought at that moment. Entering an AI system should not silently turn it into a permanent personal profile.')}</p><p>{t('整理应能回到来源，保留条件与不确定性。你的改写、命名、排列和允许范围，始终有自己的位置。', 'Organization should remain traceable to its sources and preserve conditions and uncertainty. Your edits, names, order and permission choices keep their own place.')}</p>{a('principles.html', t('数据与权限如何体现这些原则', 'How these principles shape data and access'), 'text-link')}</div></section>
<section class="nr-brand-origin wrap" data-reveal><figure class="nr-brand-art"><img src="/assets/website/brand/paia-logo-v1.webp" width="480" height="480" alt="{t('PAIA 的原始品牌画面：小女孩的背影、手中的信与旧信箱。', 'PAIA’s original artwork: a girl seen from behind, a letter in her hand and an old mailbox.')}" loading="lazy" decoding="async"/><figcaption>{t('PAIA · 最初的画面', 'PAIA · THE ORIGINAL IMAGE')}</figcaption></figure><div class="nr-origin-copy"><p class="eyebrow">{t('一封尚未寄出的信', 'A LETTER NOT YET SENT')}</p><h2>{t('人与自己的表达，<br>有时隔着一点距离。', 'Sometimes there is distance<br>between us and our words.')}</h2><p>{t('小女孩的背影、旧信箱和信，是 PAIA 的品牌原点。它们关乎投递、遗失与保存，也关乎我们如何重新找回自己的表达。', 'The girl seen from behind, the old mailbox and the letter are PAIA’s original image. They hold the ideas of sending, losing and keeping, and of finding our own expressions again.')}</p><p>{t('这幅画留在品牌的起点。产品向前：让表达被留下，在需要时重新变得可用。', 'That image stays at the beginning of the story. The product moves forward: giving expressions somewhere to remain, and a way to become useful again.')}</p></div></section>{invitation()}'''
