"""NIB v4 website illustration; not an extension frame or a live recommender."""
from html import escape
import json
from story import inputs, prompts, current_task


def narrow_board(t, ctl):
    rows=[]
    for i,value in enumerate(prompts(t)):
        rows.append(f'''<div class="pc-prompt-row" data-prompt-row="{i}">{ctl('<span data-prompt-label>'+escape(value)+'</span>',f'data-prompt-pick="{i}"','pc-prompt-pick')}{ctl('···',f'data-prompt-manage="{i}" aria-expanded="false" aria-controls="pc-prompt-manage-{i}" aria-label="{t("编辑这条常用输入","Edit this frequent input")}"','pc-row-menu')}<div class="pc-prompt-management" id="pc-prompt-manage-{i}" hidden><div class="pc-prompt-rank"><span data-rank>{i+1:02d}</span><span class="pc-grip" aria-hidden="true">⠿</span></div><label class="visually-hidden" for="pc-prompt-{i}">{t('编辑常用输入','Edit frequent input')} {i+1}</label><textarea id="pc-prompt-{i}" data-prompt-text rows="3" maxlength="350" disabled>{escape(value)}</textarea><div class="pc-prompt-actions">{ctl('↑','data-move="-1" aria-label="'+t('上移提示词','Move prompt up')+'"','pc-tiny')}{ctl('↓','data-move="1" aria-label="'+t('下移提示词','Move prompt down')+'"','pc-tiny')}{ctl(t('固定','Pin'),'data-pin aria-pressed="false"','pc-pin')}{ctl(t('填入','Insert'),'data-insert','pc-insert')}</div><div class="nb-edit-actions">{ctl(t('保存修改','Save changes'),'data-edit-save','pc-control')}{ctl(t('放弃修改','Discard changes'),'data-edit-cancel','pc-quiet')}</div></div></div>''')
    fixture=json.dumps(inputs(t),ensure_ascii=False).replace('<','\\u003c')
    return f'''<div class="pc-prompt-scene nb-host" data-narrow-board data-locale="{t('zh','en')}" data-mode="candidates"><div data-nb-fixture hidden>{escape(fixture)}</div><div class="nb-native-head"><strong>ChatGPT</strong><span>{t('虚构页面 · 不是实际连接','FICTIONAL PAGE · NOT CONNECTED')}</span></div><div class="nb-task"><p class="nb-when">{t('新任务 · 从自己的观察写一篇文章','NEW TASK · WRITE FROM YOUR OWN OBSERVATIONS')}</p><p>{t('论点和证据边界，之前已经讨论过。现在把需要的原话带进请求。','The question and evidence limits were already discussed. Bring the wording you need into this request.')}</p><span>{t('页面示意，不提供 AI 回答。','Page illustration. No AI response is provided.')}</span></div>
<div class="pc-palette-wrap nb-anchor"><div class="nb-toggle-line"><span class="nb-open-label">{t('点开，用上自己的原话','Open your own words')}</span>{ctl('<i class="paia-orb" aria-hidden="true"></i>','data-prompt-toggle aria-expanded="false" aria-controls="pc-prompt-card" aria-label="'+t('展开或收起常用输入','Expand or collapse frequent inputs')+'"','pc-orb-button')}</div><div class="pc-palette" id="pc-prompt-card" hidden><header class="nb-head">{ctl('←','data-nb-back aria-label="'+t('返回浮板上一层','Back within the board')+'" hidden','pc-quiet')}<span data-nb-label>{t('常用输入','Frequent inputs')}</span>{ctl('⌕','data-nb-search-open aria-label="'+t('搜索示例输入档案','Search example input archive')+'"','pc-quiet')}</header><div class="nb-content"><div data-nb-view="candidates"><div data-prompt-list>{''.join(rows)}</div></div><div data-nb-view="search" hidden><label class="visually-hidden" for="nb-search">{t('搜索本页虚构输入','Search this page’s fictional inputs')}</label><input id="nb-search" type="search" data-nb-query placeholder="{t('搜索输入档案','Search input archive')}" autocomplete="off" disabled><p class="nb-search-scope">{t('仅本页 4 条虚构输入','Only the four fictional inputs on this page')}</p><div data-nb-results></div><p data-nb-empty hidden>{t('没有找到。试试“两周”或“解释”。','No match. Try “two weeks” or “explain”.')}</p></div><div data-nb-view="check" hidden><p class="nb-source" data-nb-source></p><div class="nb-check-body" data-nb-check-body tabindex="0" role="region" aria-label="{t('核对完整原话，可选择其中一段','Inspect full wording; select a passage if needed')}"></div><div class="nb-check-actions">{ctl(t('填入全文','Insert full text'),'data-nb-insert-full','pc-control')}{ctl(t('复制全文','Copy full text'),'data-nb-copy-full','pc-quiet')}{ctl(t('填入选中段落','Insert selection'),'data-nb-insert-selection','pc-control')}{ctl(t('复制选中段落','Copy selection'),'data-nb-copy-selection','pc-quiet')}</div></div></div><footer class="nb-foot"><span data-nb-status role="status">{t('只填入，不发送','Insert only. Never send.')}</span></footer></div></div>
<div class="pc-composer nb-composer"><label for="pc-composer">{t('接下来，你准备说的话','YOUR NEXT INPUT')}</label><textarea id="pc-composer" rows="2" maxlength="1000" placeholder="{t('展开浮板，选一句试试…','Open the board and choose your words…')}" disabled>{escape(current_task(t))}</textarea><div><span data-prompt-status role="status">{t('演示不会发送消息','This demo never sends a message')}</span><span class="pc-send-decoration" aria-hidden="true">↑</span></div></div><p class="nb-layout-notice" data-nb-layout-notice hidden>{t('可用空间不足。浮板状态已保留；缩短输入框或增加页面高度后继续。','Not enough space. Your board state is retained; shorten the composer or increase the page height to continue.')}</p></div>'''


def prompt_section(t,ctl):
    return f'''<section class="pc-section pc-prompts" id="prompt-reuse" aria-labelledby="pc-prompts-title"><div class="wrap pc-split"><div class="pc-prompt-copy"><p class="eyebrow">03 / {t('自己的原话，再用一次','YOUR WORDS, READY AGAIN')}</p><h2 id="pc-prompts-title">{t('不用再说一遍，<br>你在意的是什么。','Keep what matters.<br>Bring it to the next chat.')}</h2><p class="pc-body-copy">{t('展开 ChatGPT 旁的小浮板，点一句常用表达，或搜索自己曾经说过的话。长内容先完整核对，再填入；原有草稿保留，什么时候发送仍由你决定。','Open the small board beside ChatGPT. Choose a frequent phrase or find an earlier input. Inspect long text before inserting it. Your draft stays intact; you decide when to send.')}</p><p class="pc-instruction">{t('点开浮球；再试试搜索“两周”。','Open the orb, then try searching “two weeks”.')}</p><p class="pc-plan-note"><span>{t('v4 获批设计 · 尚未接入扩展','APPROVED v4 DESIGN · NOT YET IN THE EXTENSION')}</span>{t('本页只是固定宽度的交互示例。免费用户保留常用输入、搜索、手动编辑和复用。','This is a same-width interactive illustration. Frequent inputs, search, manual editing and reuse remain available to Free users.')}</p><details class="nb-pro-note"><summary>{t('Pro AI 推荐与免费复用有什么不同？','How do Pro AI recommendations differ?')}</summary><p>{t('Pro 的 AI 推荐依赖真实服务、会员资格、相应处理许可和预算，目前尚未开放。这里没有 AI 推荐、付费按钮或模拟开通；普通查找和复用不依赖它。','Pro recommendations require a real service, membership, scoped processing permission and budget. They are not available yet. There is no AI recommendation, payment action or simulated activation here; ordinary retrieval and reuse do not depend on them.')}</p></details></div>{narrow_board(t,ctl)}</div></section>'''
