"""Practical first-use instructions and three bounded, fictional use cases."""
from html import escape
from story import inputs, title, sections, prompts, current_task


def render_usage_pages(t, a, button, invitation, icon):
    rows = inputs(t)
    headings = sections(t)
    def frame(label, content, sub=''):
        return f'<div class="nr-window"><div class="nr-window-bar"><span class="nr-window-mark" aria-hidden="true"></span><strong>{label}</strong><span>{sub}</span></div><div class="usage-paper">{content}</div></div>'
    def caption(zh,en):
        return f'<figcaption class="nr-scene-caption">{t(zh,en)}</figcaption>'
    def steps_intro():
        return f'''<section class="nr-intro wrap"><div><p class="eyebrow">{t('如何使用','HOW IT WORKS')}</p><h1>{t('从第一条输入，<br>到下一次用上。','From your first input<br>to using it again.')}</h1></div><div class="nr-intro-aside"><p class="lead">{t('这页说明实际操作顺序。先检查保存与来源，再编辑、组织、复用；AI 连接不是开始使用的前提。','Follow the practical sequence: check capture and source, then edit, organize and reuse. An AI connection is not a prerequisite.')}</p>{a('demo.html',t('用虚构数据练习','Practice with fictional inputs'),'text-link')}<p class="nr-scope">{t('扩展需获邀安装。下方是目标使用方式；当前版本限制见可用范围。','The extension requires an invitation. Below is the intended workflow; see availability for current limits.')} {a('status.html',t('可用范围','Availability'))}</p></div></section>'''
    capture = frame('ChatGPT',f'''<span class="nr-ui-label">{t('你发送的输入 · 虚构示例','YOUR SENT INPUT · FICTIONAL')}</span><p class="usage-original">{escape(rows[0]['text'])}</p><div class="usage-source-strip"><span>{t('用户输入','User input')}</span><span>{rows[0]['date']}</span><span>{t('保留来源','Source retained')}</span></div>''',t('支持的网页范围','Supported pages'))
    edited = t('文章要讨论的是能否独立解释，而不是读了多少书。','The article asks whether I can explain an idea independently, not how many books I read.')
    archive = frame(t('输入档案','Input Archive'),f'''<p class="usage-quiet">{t('查找关键词：解释','Search term: explain')}</p><h3>{t('怎样知道自己学会了','How do I know I have learned it?')}</h3><p class="nr-ui-label">{t('工作版本 · 示例用户主动改写','WORKING VERSION · EDITED BY THE EXAMPLE USER')}</p><p class="usage-original">{edited}</p><details class="nr-source-detail"><summary>{t('核对原始来源','Check original source')}</summary><p>{escape(rows[0]['text'])}</p><span>ChatGPT · {rows[0]['date']} · {rows[0]['source']}</span></details>''',t('来源与工作文字分开','Source and working text stay separate'))
    topic = frame(t('思想库','Thought Library'),f'''<h3>{title(t)}</h3><section><h4>{headings[0]}</h4><p>{escape(rows[1]['text'])}</p></section><section><h4>{headings[1]}</h4><p>{escape(rows[2]['text'])}</p></section><p class="usage-quiet">{t('同一主题里的连续阅读局部；不是 AI 摘要。','A continuous-reading detail in one topic, not an AI summary.')}</p>''',t('已打开的主题','Selected topic'))
    prompt = f'''<div class="usage-reuse"><div class="usage-narrow" aria-label="{t('窄浮板静态示意，非实际控件','Static narrow-board illustration, not live controls')}"><span class="nr-ui-label">{t('常用输入 · v4 设计示意','FREQUENT INPUTS · v4 DESIGN')}</span>{''.join('<p>'+escape(x)+'</p>' for x in prompts(t))}</div><p class="usage-quiet">{t('长内容先打开全文检查，再决定使用全文或选中段落。','Inspect long wording before choosing the whole text or a selected passage.')}</p><div class="usage-request"><span class="nr-ui-label">{t('示例用户主动填入后的请求','REQUEST AFTER DELIBERATE INSERTION')}</span><p>{current_task(t)}</p><p>{escape(rows[2]['text'])}</p><span>{t('没有发送，没有生成答案','Not sent. No answer generated.')}</span></div></div>'''
    cards=[t('我的信息','My Information'),t('我的规则','My Rules'),t('我的现在','My Now'),t('我的输入','My Inputs')]
    context=frame('AI Context',f'''<p class="usage-global">{t('AI 访问：关','AI access: off')}</p><div class="usage-context-cards">{''.join('<div><h3>'+x+'</h3><span>'+t('仅自己','Only me')+'</span></div>' for x in cards)}</div><p class="usage-quiet">{t('无真实连接。全局、卡片和新主题都默认关闭。','No real connection. Global access, cards and new topics start off.')}</p>''',t('静态默认状态','Static default state'))
    flow=[
        ('capture',t('先确认，保存的是<br>你自己的输入。','First, check that it is<br>your input being saved.'),t('获邀安装桌面 Chrome 测试版后，在支持的 ChatGPT 页面主动开启保存。发送一条非关键输入，再到输入档案检查内容、来源和时间。','After installing an invited desktop Chrome build, enable capture on supported ChatGPT pages. Send a non-critical input, then check its wording, source and time in Input Archive.'),t('安装不会自动收集整个账号历史；历史导入是另一次主动操作。本站演示不采集任何聊天。','Installation does not ingest an entire account history. History import is a separate action. This website captures no chats.'),capture),
        ('archive',t('找到原话，<br>修改工作版本。','Find the original.<br>Edit the working version.'),t('在档案里搜索“解释”，打开匹配的输入。修改工作文字后，展开原始来源核对；改变的是工作版本，不是当时发送过的记录。','Search the archive for “explain” and open the matching input. Edit the working text, then expand its original source. The working version changes, not the historical record of what was sent.'),t('会话内查找只定位匹配，不把其余正文过滤掉。来源不可用时，不假装已经核对。','Find within a conversation locates matches without filtering away the rest. An unavailable source is not a verified source.'),archive),
        ('thought',t('给持续的问题，<br>建立自己的主题。','Give an ongoing question<br>a topic of its own.'),t('在思想库建立个人主题，把相关内容安排进自己的章节。打开主题后连续读下去；可以修改、移动、排除，不需要等 AI 先整理。','Create a personal topic and arrange related material into your own sections. Open it to read continuously. Manual edits, moves and exclusions do not have to wait for AI organization.'),t('AI 整理是单独的衍生阅读能力，真实服务尚未开放，不能覆盖人的修改和组织。','AI organization is a separate derivative reading capability. Its real service is not available, and it cannot override human edits or organization.'),topic),
        ('prompt',t('回到新任务，<br>选准要带回的话。','Return to the task.<br>Choose the wording to bring.'),t('打开浮板，选择常用表达，或搜索已保存输入。被省略的长内容先核对全文，再明确填入。当前草稿保留，发送由你决定。','Open the board to choose a frequent phrase or search saved inputs. Inspect clipped wording in full before explicitly inserting it. Your current draft stays; you decide when to send.'),t('这里展示已批准、尚待实施的 v4 窄浮板。免费手动复用不依赖 Pro AI 推荐。','This illustrates the approved v4 narrow board, still awaiting implementation. Free manual reuse does not depend on Pro AI recommendations.'),prompt),
        ('context',t('需要共享背景时，<br>再决定开放什么。','When context is needed,<br>choose what to allow.'),t('先维护信息、规则和近况，再逐个选择可读取的个人主题。卡片和主题选择不会暗中开启全局访问；关闭上级会保留下级选择。','Maintain information, rules and current context, then choose topics individually. Selecting a card or topic does not silently turn on global access. Closing a parent keeps the lower-level choices.'),t('外部 AI 连接尚未开放。演示只是范围预览，不创建权限，也不会连接真实账号。','External AI connections are not available yet. The demo previews scope only; it grants no real permissions and connects no accounts.'),context)
    ]
    how=steps_intro()+f'<nav class="usage-index wrap" aria-label="{t("操作顺序","Workflow")}">'+''.join(f'<a href="#{key}">{i+1:02d} / '+t(['检查保存','找回与编辑','组织主题','准确复用','控制范围'][i],['Check capture','Find and edit','Organize','Reuse exactly','Control scope'][i])+'</a>' for i,(key,*_) in enumerate(flow))+'</nav><div class="nr-process wrap">'
    for i,(key,heading,body,note,visual) in enumerate(flow):
        how+=f'<section id="{key}" class="nr-process-step usage-step"><div class="nr-step-copy"><span class="nr-step-number">{i+1:02d}</span><h2>{heading}</h2><p>{body}</p><p class="nr-step-note">{note}</p>{a("demo.html",t("在完整演示中练习","Practice in the complete demo"),"text-link",["#input-library","#input-library","#thought-library","#prompt-reuse","#personal-context"][i])}</div><figure class="nr-scene">{visual}{caption("界面与输入均为虚构示意","Interface and inputs are fictional illustrations")}</figure></section>'
    how+='</div>'+invitation()
    use=f'''<section class="nr-intro wrap"><div><p class="eyebrow">{t('使用场景','USE CASES')}</p><h1>{t('同一个问题，<br>不止谈一次。','One question.<br>More than one conversation.')}</h1></div><div class="nr-intro-aside"><p class="lead">{t('PAIA 更适合需要反复回到自己的观点、理解和约束的人，而不是偶尔查一次聊天记录。以下都是虚构示例。','PAIA is most relevant when you repeatedly return to your own arguments, explanations and constraints—not just an occasional chat lookup. All examples below are fictional.')}</p></div></section><div class="nr-use-cases wrap">'''
    cases=[
        (t('长期写作','ONGOING WRITING'),t('把论点带回来，<br>也把限制条件带回来。','Keep the argument.<br>Keep the conditions too.'),rows[2]['text'],t('帮我列文章提纲。材料只来自我的两周尝试，请围绕“能否独立解释”展开，不把个人观察推成普遍结论。','Help me outline the article around explaining ideas independently. My evidence is a two-week experiment; don’t present it as a universal result.'),t('输入档案核对原话；思想库按问题连续组织；常用输入保留写作要求。这比单纯存下一份生成稿，多保留了你自己的判断。','Check exact wording in the archive, organize it by question in Thought Library, and keep recurring writing instructions close. The point is your judgment, not just a stored generated draft.')),
        (t('持续学习','CONTINUING TO LEARN'),t('下次从还没懂的地方，<br>接着问。','Pick up at the part<br>you have not understood.'),t('例题我能看懂，但换一个条件就不会解释了。下次从“为什么这个条件必要”继续，不要再从定义重讲。','I can follow the example, but not explain what changes under a different condition. Next time, begin with why that condition is necessary—not the definition again.'),t('沿用我上次没解决的问题，先让我解释条件的作用，再检查哪里不清楚。','Continue with my unresolved question. Let me explain the role of the condition before checking what is unclear.'),t('保存的是你对自己理解程度的描述，不是 AI 讲解，也不是系统的掌握评分。旧描述需要根据新的理解继续修改。','This preserves your own account of your understanding, not the AI’s explanation or a system-generated mastery score. Update it as your understanding changes.')),
        (t('长期个人计划','LONG-TERM PERSONAL PLANS'),t('条件没有变，<br>就别每次重新讨论。','When the conditions hold,<br>don’t reopen every decision.'),t('这件事每周只用周末两小时，不增加工作日任务。先做一个月再决定是否扩大。','Use only two hours each weekend, with no weekday tasks. Try it for a month before deciding whether to expand.'),t('在周末两小时的范围内，安排本周能完成的一件事，不增加工作日任务。','Choose one thing I can finish in two hours this weekend, without adding weekday tasks.'),t('从原话找回约束，再判断它们是否仍然适用。PAIA 不会自动把旧计划升级成今天的授权，也不会代替你作出新决定。','Recover the original constraints, then decide whether they still apply. PAIA does not turn an old plan into current authority or make the next decision for you.')),
    ]
    for i,(label,heading,old,new,benefit) in enumerate(cases):
        use+=f'''<section class="nr-case usage-case"><header class="nr-case-heading"><span class="nr-step-number">0{i+1}</span><p class="eyebrow">{label}</p><h2>{heading}</h2></header><div class="nr-case-story"><div class="nr-case-past"><span class="nr-ui-label">{t('之前自己的表达','YOUR EARLIER WORDING')}</span><blockquote>{escape(old)}</blockquote><p class="usage-quiet">{t('虚构用户输入 · 保留来源','Fictional user input · Source retained')}</p></div><div class="nr-case-transition" aria-hidden="true">→</div><div class="nr-case-next"><span class="nr-ui-label">{t('示例用户据此写出的新请求','A NEW REQUEST THE EXAMPLE USER WRITES')}</span><p>{escape(new)}</p><p class="usage-quiet">{t('不是 PAIA 自动生成，也不是 AI 回答','Not generated by PAIA. Not an AI response.')}</p></div></div><footer class="nr-case-footer"><p>{benefit}</p>{a('demo.html',t('实际操作一次','Try the workflow'),'text-link')}</footer></section>'''
    use+='</div>'+f'''<section class="usage-fit wrap"><h2>{t('什么时候不必安装？','When is it unnecessary?')}</h2><p>{t('只需偶尔找一个旧聊天，或已经能用 Project、Memory、笔记和模板顺畅接续工作时，原有工具可能就够了。PAIA 值得考虑的，是你反复需要核对、修改和精确使用自己输入的那条路径。','For occasional chat retrieval—or when Projects, Memory, notes and templates already carry your work smoothly—your existing tools may be enough. Consider PAIA when you repeatedly need to inspect, revise and precisely use your own inputs.')}</p>{a('index.html',t('回首页试试完整价值变化','Try the value demonstration on the home page'),'text-link','#thought-library')}</section>'''+invitation()
    return [('how-it-works.html',t('PAIA — 如何使用','PAIA — How it works'),t('检查保存、找回原话、修改工作内容、组织主题、准确复用和控制访问范围。','Check capture, find originals, revise working content, organize topics, reuse exact wording and control access.'),how),('use-cases.html',t('PAIA — 使用场景','PAIA — Use cases'),t('写作保留论点与边界，学习接续问题，长期计划沿用仍然有效的条件。','Keep arguments and limits in writing, continue learning questions, and preserve relevant constraints in long-term plans.'),use)]
