import {hashText} from '../dedupe.js';
import {prefix} from '../thought-model.js';
import {DEFAULT_PROFILE,SESSION_KEY,key,configDefault,validateMemoryRow,memoryRange,topicActive,policy,reject,idOK} from './model.js';

const generation=async t=>(await t.get('meta','backup-data-generation'))?.value||0;
const transient=()=>{const values={};return {async get(k){return {[k]:structuredClone(values[k])};},async set(v){Object.assign(values,structuredClone(v));}};};
// Fixed internal security audit policy. Legacy user retention metadata is preserved.
export const MEMORY_AUDIT_RETENTION_DAYS=30;
export const MEMORY_AUDIT_LIMIT=200;
const unavailable=()=>reject('FEATURE_UNAVAILABLE');

// Existing metadata, authorization and privacy controls remain available.
// Profile management and all Context generation are retired at this owner boundary.
export class MemoryService {
 constructor(store,{session=transient(),clock=()=>Date.now()}={}){this.s=store;this.session=session;this.clock=clock;this.previews=new Map();this.tail=Promise.resolve();}
 serial(fn){const task=this.tail.then(fn,fn);this.tail=task.then(()=>undefined,()=>undefined);return task;}
 async ready(){await this.s.finishFoundation();await this.s.run(()=>this.s.repository.transaction(true,async t=>{const c=await t.get('meta','memory:config');if(c){if(!validateMemoryRow(c))reject();if(c.externalAccess===undefined||c.includeUnorganizedInputs===undefined||c.localOnly===undefined)await t.put('meta',{...c,localOnly:c.localOnly===true,externalAccess:c.externalAccess===true,includeUnorganizedInputs:c.includeUnorganizedInputs===true});return;}await t.put('meta',configDefault());}));}
 async state(t){const rows=await t.all('meta',null,memoryRange());if(rows.some(r=>!validateMemoryRow(r)))reject();return {rows,config:rows.find(r=>r.kind==='config')||configDefault(),profiles:rows.filter(r=>r.kind==='profile')};}
 async temporary(){const data=(await this.session.get(SESSION_KEY))[SESSION_KEY];return data?.version===1&&data.grants&&typeof data.grants==='object'?data:{version:1,revision:0,grants:{}};}
 async sessionChange(fn){const state=await this.temporary();fn(state.grants);state.revision++;await this.session.set({[SESSION_KEY]:state});this.previews.clear();}
 async touch(t){const c=await t.get('meta','memory:config');await t.put('meta',{...c,revision:c.revision+1,userTouched:true});}
 async activity(t,{action,profileId=DEFAULT_PROFILE,queryDigest,topicIds=[],entryIds=[],inputIds=[]}){if(action!=='permission')unavailable();const c=await t.get('meta','memory:config'),retentionDays=Math.min(c?.retentionDays??MEMORY_AUDIT_RETENTION_DAYS,MEMORY_AUDIT_RETENTION_DAYS);if(!retentionDays)return false;const now=this.clock(),at=new Date(now).toISOString(),rows=(await t.all('meta',null,memoryRange())).filter(r=>r.kind==='activity').sort((a,b)=>a.createdAt.localeCompare(b.createdAt));for(const row of rows.filter((r,i)=>Date.parse(r.createdAt)<now-retentionDays*86400000||i<rows.length-(MEMORY_AUDIT_LIMIT-1)))await t.delete('meta',row.id);const row={id:'memory:activity:'+at+':'+crypto.randomUUID(),kind:'activity',version:1,createdAt:at,profileId,queryDigest,topicIds:[...new Set(topicIds)].filter(id=>id!=='input-archive').slice(0,1000),entryIds:[...new Set(entryIds)].slice(0,200),...(inputIds.length?{inputIds:[...new Set(inputIds)].slice(0,200)}:{}),action};await t.put('meta',row);return true;}
 async status({profileId=DEFAULT_PROFILE,query='',cursor=0,limit=50}={}){return this.serial(async()=>{await this.ready();if(!idOK(profileId)||typeof query!=='string'||query.length>200||!Number.isInteger(cursor)||cursor<0||!Number.isInteger(limit)||limit<1||limit>100)reject();const temp=await this.temporary();return this.s.run(()=>this.s.repository.transaction(false,async t=>{const state=await this.state(t);if(profileId!==DEFAULT_PROFILE&&!state.profiles.some(p=>p.profileId===profileId))reject();const topics=(await t.all('topics','byIndex',prefix([0]))).filter(topicActive),p=policy(state.rows,profileId,temp.grants,new Map(topics.map(t=>[t.id,t]))),items=[];let allowed=0,denied=0;for(const topic of topics){const decision=p.decision(topic.id);if(decision==='allowed')allowed++;else denied++;if(query&&!topic.name.normalize('NFKC').toLocaleLowerCase().includes(query.normalize('NFKC').toLocaleLowerCase()))continue;items.push({id:topic.id,name:await this.safeLabel(t,topic,'name'),decision,temporary:p.temporary(topic.id),permanentDecision:p.rules.get(topic.id)||'default',neverProfiles:state.rows.filter(r=>r.kind==='topic'&&r.topicId===topic.id&&r.decision==='never').map(r=>state.profiles.find(p=>p.profileId===r.profileId)?.name||'未知 Profile')});}const activities=await Promise.all(state.rows.filter(r=>r.kind==='activity'&&state.config.retentionDays&&Date.parse(r.createdAt)>=this.clock()-Math.min(state.config.retentionDays,MEMORY_AUDIT_RETENTION_DAYS)*86400000).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,20).map(async r=>({...r,topicNames:(await Promise.all(r.topicIds.map(async id=>{const topic=topics.find(t=>t.id===id);return topic?this.safeLabel(t,topic,'name'):'';}))).filter(Boolean),profileName:state.profiles.find(p=>p.profileId===r.profileId)?.name||'已删除的 Profile'})));return {config:state.config,profiles:state.profiles,items:items.slice(cursor,cursor+limit),nextCursor:cursor+limit<items.length?cursor+limit:null,generation:await generation(t),total:topics.length,resultCount:items.length,allowed,denied,excluded:state.rows.filter(r=>r.kind==='entry').length,excludedInputs:state.rows.filter(r=>r.kind==='input').length,temporaryCount:Object.keys(temp.grants).length,activity:activities};}));});}
 async authorize({profileId=DEFAULT_PROFILE,topicIds,decision,scope='permanent',confirmed=false}={}){if(decision==='allowed')unavailable();return this.serial(async()=>{await this.ready();if(!idOK(profileId)||!Array.isArray(topicIds)||!topicIds.length||topicIds.length>1000||topicIds.some(x=>!idOK(x))||!['allowed','denied','default','never'].includes(decision)||!['session','permanent'].includes(scope))reject();if(topicIds.length>1&&decision==='allowed'&&!confirmed)reject('MEMORY_CONFIRM_REQUIRED');const digest=await hashText(''),generations={};await this.s.run(()=>this.s.repository.transaction(false,async t=>{if(profileId!==DEFAULT_PROFILE&&!await t.get('meta',key('profile',profileId)))reject();const never=scope==='session'?new Set((await this.state(t)).rows.filter(r=>r.kind==='topic'&&r.decision==='never').map(r=>r.topicId)):new Set();for(const id of topicIds){if(scope==='session'&&decision==='allowed'&&never.has(id))reject('MEMORY_DENIED');const topic=await t.get('topics',id);if(!topicActive(topic))reject('MEMORY_UNAVAILABLE');generations[id]=topic.activeLayoutGeneration;if(scope==='session'&&['denied','never'].includes((await t.get('meta',key('topic',profileId,id)))?.decision))reject('MEMORY_DENIED');}}));if(scope==='session'){if(!['allowed','default'].includes(decision))reject();await this.sessionChange(grants=>{for(const id of topicIds){const k=key('topic',profileId,id);if(decision==='allowed')grants[k]=generations[id];else delete grants[k];}});return {saved:true,scope};}
 await this.sessionChange(grants=>{for(const id of topicIds)delete grants[key('topic',profileId,id)];});await this.s.foundationWrite(async t=>{if(profileId!==DEFAULT_PROFILE&&!await t.get('meta',key('profile',profileId)))reject();for(const id of topicIds){if(!topicActive(await t.get('topics',id)))reject('MEMORY_UNAVAILABLE');const k=key('topic',profileId,id);if(decision==='default')await t.delete('meta',k);else await t.put('meta',{id:k,kind:'topic',version:1,profileId,topicId:id,decision,layoutGeneration:generations[id]});}await this.touch(t);await this.activity(t,{action:'permission',profileId,queryDigest:digest,topicIds});});return {saved:true,scope};});}
 async exclude({entryId,inputId,excluded,topicId,sectionId}={}){return this.serial(async()=>{await this.ready();const direct=!!inputId;if(typeof excluded!=='boolean'||entryId&&inputId||(entryId?!idOK(entryId):direct?!idOK(inputId):!idOK(topicId)||!idOK(sectionId)))reject();await this.s.foundationWrite(async t=>{const kind=entryId?'entry':direct?'input':'section';if(entryId&&!await t.get('thoughts',entryId))reject();if(direct&&!await t.get('inputStates',inputId))reject();if(!entryId&&!direct){const topic=await t.get('topics',topicId);if(!topic||!await t.get('sections',JSON.stringify([topicId,topic.activeLayoutGeneration,sectionId])))reject();}const id=entryId?key(kind,entryId):direct?key(kind,inputId):key(kind,topicId,sectionId);if(excluded)await t.put('meta',{id,kind,version:1,...(entryId?{entryId}:direct?{inputId}:{topicId,sectionId}),excluded:true});else await t.delete('meta',id);await this.touch(t);});this.previews.clear();return {saved:true};});}
 async settings(options={}){
  if(!options||typeof options!=='object'||Array.isArray(options))reject();
  if(options.externalAccess===true||['budget','retentionDays','onboarded','includeUnorganizedInputs'].some(k=>Object.hasOwn(options,k)))unavailable();
  const allowed=['externalAccess','localOnly','clearTemporary','clearActivity','clearInputExclusions'];
  if(Object.keys(options).some(k=>!allowed.includes(k))||Object.values(options).some(value=>typeof value!=='boolean'))reject();
  return this.serial(async()=>{
   await this.ready();const {externalAccess,localOnly,clearTemporary=false,clearActivity=false,clearInputExclusions=false}=options;
   await this.s.foundationWrite(async t=>{
    const state=await this.state(t),config={...state.config,revision:state.config.revision+1};
    if(externalAccess!==undefined){config.externalAccess=externalAccess;config.userTouched=true;}
    if(localOnly!==undefined){config.localOnly=localOnly;config.userTouched=true;}
    await t.put('meta',config);
    for(const row of state.rows)if(clearActivity&&row.kind==='activity'||clearInputExclusions&&row.kind==='input')await t.delete('meta',row.id);
   });
   if(clearTemporary)await this.sessionChange(grants=>{for(const key of Object.keys(grants))delete grants[key];});
   this.previews.clear();return {saved:true};
  });
 }

 async safeSources(t,ids=[]){for(const id of ids){const ix=await t.get('recordIndex',id);if(!ix||!await t.has('records',id)||ix.deletedAt||ix.hidden||await t.get('tombstones','source:'+ix.sourceKey)||await t.get('tombstones','snapshot:'+ix.dedupeKey))return false;}return true;}
 async safeLabel(t,row,field){if(!row.sourceRecordIds?.length||row.protections?.[field]?.locked||await this.safeSources(t,row.sourceRecordIds))return row[field]||'';return field==='name'?'来源已移除的主题':'';}
 async permittedPaths(t,entryId,topics,p){if(p.excluded.has(entryId))return [];const paths=[];for(const placement of await t.all('placements','byEntry',prefix([entryId]))){const topic=topics.get(placement.topicId);if(!topicActive(topic)||placement.lifecycle!=='active'||placement.layoutGeneration!==topic.activeLayoutGeneration)continue;if(['denied','never'].includes(p.decision(topic.id))||p.sections.has(JSON.stringify([topic.id,placement.sectionId])))return [];if(p.decision(topic.id)==='allowed'&&!placement.excludedByUser){const section=await t.get('sections',JSON.stringify([topic.id,topic.activeLayoutGeneration,placement.sectionId]));if(section?.lifecycle==='active')paths.push({topic,section,placement});}}return paths;}
 async entries({topicId,profileId=DEFAULT_PROFILE,cursor=null}={}){return this.serial(async()=>{await this.ready();if(!idOK(topicId))reject();return this.s.run(()=>this.s.repository.transaction(false,async t=>{const topic=await t.get('topics',topicId);if(!topicActive(topic))reject();const state=await this.state(t),p=policy(state.rows,profileId),page=await t.rangePage('placements','byTopicOrder',prefix([topicId,topic.activeLayoutGeneration,0]),cursor,40),items=[];for(const {value:placement}of page.rows){const e=await t.get('thoughts',placement.entryId);if(e?.lifecycle!=='active'||!await this.safeSources(t,e.sourceRecordIds))continue;items.push({id:e.id,title:e.title,body:(e.thoughtText||'').slice(0,500),excluded:p.excluded.has(e.id),sectionId:placement.sectionId,sectionExcluded:p.sections.has(JSON.stringify([topicId,placement.sectionId]))});}const sections=[];for(const id of new Set(items.map(e=>e.sectionId))){const row=await t.get('sections',JSON.stringify([topicId,topic.activeLayoutGeneration,id]));if(row)sections.push({id,title:await this.safeLabel(t,row,'title'),excluded:p.sections.has(JSON.stringify([topicId,id]))});}return {items,sections,nextCursor:page.next};}));});}
 async profile(){unavailable();}
 async entryCandidate(){unavailable();}
 async inputCandidate(){unavailable();}
 async candidates(){unavailable();}
 async build(){unavailable();}
 async share(){unavailable();}
}
